### ISSUE TITLE
Confusion in expected result

### ISSUE THREAD

**Issue by mikecann** [mobxjs/mobx-state-tree#10]
Hi,

Im wondering a little bit about how this lib is supposed to be used exactly.

Given the following:

```
const Box = createFactory({
    color: ""
})

const BoxStore = createFactory({
    boxes: arrayOf(Box)
})

const boxStore = BoxStore()

const newBox = Box({ color: "red" });
boxStore.push(newBox);

console.log(newBox.color) // red

applySnapshot(boxStore, {
    boxes: [
        { color: "blue" }
    ]
})

console.log(newBox.color) // should this be blue now?
```

Is this the intention? 

Can I make an @observable of `newBox` then use it in a react component and expect the component to be re-rendered when a property of newBox changes due to a snapshot being applied?

Cheers,
Mike

**Comment by mweststrate** [comment]
The answer is: it might be blue. `boxStore.boxes[0].color` is definitely blue, but having references to items inside the store from outside is dangerous; the entire store might be replaced. After a replace the reference could still work if the instance was 'recycled', but it might than actually be replaced with another box.

In other words, the only absolutely stable pointer is the one to the root of the store (this is similar to immutable state trees). However, if your reference is inside a *reaction* that resolves it, then it is safe.

So this should always yield the correct value:
```
autorun(() => {
 const myBox = boxStore.boxes[0]
 console.log(myBox.color) 
})
```

**Comment by mikecann** [comment]
Awesome, thanks, that makes perfect sense 👍
