### ISSUE TITLE
Add hooks for snapshots

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#100]
Make sure snapshots are only validated after processing

**Comment by mweststrate** [comment]
Hook names will be: `preProcessSnapshot` and `postProcessSnapshot`, both of the signature `snapshot => snapshot`, and no `this`

**Comment by mattiamanzati** [comment]
I think that should be triggered either in initialize/create and apply/emitSnapshot, right?

**Comment by mweststrate** [comment]
yep :)

Op di 20 jun. 2017 om 11:00 schreef Mattia Manzati <notifications@github.com

**Comment by mweststrate** [comment]
Released as 0.8.0
