### ISSUE TITLE
Share tree structure from server to clients

### ISSUE THREAD

**Issue by BojDom** [mobxjs/mobx-state-tree#1000]
I have:

* [ x ] A conceptual question. 
  * [ x ] I've checked documentation and searched for existing issues
  * [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3) first
* [ ] I think something is not working as it should.
  * [ ] I've checked documentation and searched for existing issues
  * [ ] I've made sure your project is based on the latest MST version
  * [ ] Fork [this](https://codesandbox.io/s/jlnmjqr7xv) code sandbox or another minimal reproduction. 
  * [ ] Describe expected behavior
  * [ ] Describe observed behavior
* [ ] Feature request
   * [ ] Describe the feature and why you feel your feature needs to be generically solved inside MST
   * [ ] Are you willing to (attempt) a PR?
   

Hi everyone, what i'm trying to do is a document-sync with websockets using mobx-state-tree at server side, and then call applyPatch to client whenever onPatch is emitted.
My problem is that i have to set the types on the client before i can create and edit the tree, but theese types can differ over time due to development of the app and can cause no retrocompatibility to clients, my question now is, there is an api that can assist to share the node types trought ws ?
And if not, what could be the best approach to achieve this ?
Note that clients are apps using ReactNative, so i can't simply import the same js

**Comment by xaviergonz** [comment]
so you want to be able to serialize the types?
can't you just have a common library with everything related to models and then use this library both from the client and the server?

**Comment by BojDom** [comment]
Yes, serializing the types to pass them as string trought websocket and make them reusable to create a mst context.
My workaround now is making something like store = eval(' types.model... ' ) which works but i have to be careful.
If there are no plans to support this scenario you could close the issue

**Comment by xaviergonz** [comment]
I think your best bet is to put all your model creation inside a function (that returns the models) and then sending through the websocket the "toString()" of such function and running eval on it. Might want to check twice about security issues though.

```
// server
function createModels() {
  return {
    TMyModel: types.model({x: 10})
  }
}

// on server send createModels.toString() over ws
...
// on client
eval(receivedWsString)
const models = createModels();
models.TMyModel.create(...)
```

I don't think there are plans to support this though out of the box, so closing.
