### ISSUE TITLE
Model validation doesn't test that snapshot has not properties those are absent in model

### ISSUE THREAD

**Issue by codewylle** [mobxjs/mobx-state-tree#1008]
Nice case:
```javascript
import { types } from "../../src"

test("Model validation checks that snapshot has not properties those are absent in model", () => {
    const M = types.model({ a: "a", b: "b" })
    const S = { c: "c", d: "d" }

    expect(() => M.create(S)).toThrow()  // No error in 3.3.0
})
```

**Comment by xaviergonz** [comment]
did that fail in 3.2.x?

**Comment by codewylle** [comment]
Didn't

**Comment by mweststrate** [comment]
Superfluous fields are ignored by MST. The reason for that is that most people directly use the JSON they receive from requests to create MST models. By ignoring random additional fields, any additive changes in the JSON format, for example because the endpoints expose some new fields, don't break the client and don't require an additional step of preprocessing.

**Comment by codewylle** [comment]
Mweststrate, it is true. But if all model properties are optional any snapshot of any type fits to this model. It fits quietly in compile time and runtime. But applying it to model will not change the node. It's good place for bugs and it isn't user are waiting for if user made mistake and applied improper snapshot.

Maybe it will be better to protect user by more strict types (user can use type casting: `JSON as SnapshotIn<typeof Model>`, but it breaks backward compatibility) or by adding option of strict validation (`types.model({ a: "a" }, { strict: true })`).

**Comment by Bnaya** [comment]
TypeScript solution for this is "weak types"
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html#weak-type-detection

if you have all-optional interface, and you pass object that is not "empty", but there are no matching properties, you get an error

**Comment by xaviergonz** [comment]
If it were to be done then probably I'd move it as an option to .create() (I can't think of a reason why one might need a model to be strict and a submodel not to be)

That being said, if you need such a feature ASAP I'd make something like this:
```
const m = M.create(s)
const ss = getSnapshot(m)
// deeply traverse ss and s, if s has a property that ss doesn't have then throw
```

another option might be:
```ts
function modelStrictCheck(possibleProps, snapshot) {
  const propNames = new Set(Object.keys(possibleProps))
  for (const actualProp of Object.keys(snapshot)) {
    if (!propNames.has(actualProp) {
      throw new Error(`prop ${actualProp} was not expected`)
    }
  }
}


// for every model that requires strict checking
const props = {
  x: types.number(),
  ...
}

const M = types.model(props)
  .preProcessSnapshot((sn) => {
    modelStrictCheck(props, sn);
  }
```

**Comment by mweststrate** [comment]
@xaviergonz / @codewylle, you could do a simply check like (`Object.keys(snapshot).length !== Object.keys(type.properties))` to detect superfluos attributes (or do a proper comparision). I don't see a real reason why MST should be concerned about superfluous properties, a snapshot is either compatible with a type, or it is not. What is additionally in the snapshot is not really relevant, and imho a userland problem. Forbidding additional members causes at least more problems than allowing them (in early MST versions this was the case), and I am a  hesitant to serve options in the API, where some options have no value for MST itself. So I propose a won't-fix for this one

**Comment by xaviergonz** [comment]
personally I don't have a use for it, so a won't fix works for me
However, I still think it might be cool to offer as part of a model type the props+resolved types.

e.g.
types.model({x: 5}).props({y: M2)}.getProps() = {x: types.number, y: M2}

**Comment by xaviergonz** [comment]
@mweststrate just made a pr https://github.com/mobxjs/mobx-state-tree/pull/1016

This PR adds getPropertyMembers(type | node): {name, properties {k: IAnyType} }

I had to make it separate from the existing getMembers since to get actions/views/volatile an actual instantiated node is required due to late initialization

**Comment by xaviergonz** [comment]
marking as won't fix as @mweststrate suggested
