### ISSUE TITLE
Make protected mode the default

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#101]
Introduce unprotect
Q: Actions can only modify `this`, entire tree or subtree @mattiamanzati ?

**Comment by mattiamanzati** [comment]
Ok, Thats a though question. Imho when you call unprotect(tree) the childs and the tree can be unlocked. So basically actions can change any tree Thats unlocked. On the past we allowed only changes to subtree. Imho Thats a fair condition. Its also how redux works. You can only change subtrees and not parent or siblings. If you need to, you can put an action there and call it.
