### ISSUE TITLE
Livelyness typo

### ISSUE THREAD

**Issue by AjaxSolutions** [mobxjs/mobx-state-tree#1018]
I'm not trying to be a smart guy, but the word Livelyness is misspelled in the entire code base.

Livelyness --> Liveliness

It's probably too late to fix it(?)

I assume the word we are looking for is Liveness, not Liveliness.

https://en.wikipedia.org/wiki/Liveness

**Comment by mweststrate** [comment]
As long as it is not part of the external api, feel free to create a PR

**Comment by AjaxSolutions** [comment]
I'm going to close this issue since the public API would have to be changed.

https://github.com/mobxjs/mobx-state-tree/blob/master/API.md#setlivelynesschecking

**Comment by xaviergonz** [comment]
maybe both functions could be publicly provided marking the misspelled one as deprecated?
