### ISSUE TITLE
Hot to save and restore my states from localstorage with autosave?

### ISSUE THREAD

**Issue by markolofsen** [mobxjs/mobx-state-tree#1022]
Hot to save and restore my states from localstorage with autosave?
[My repo for example](https://github.com/markolofsen/nextjs)

```
export function initStore (isServer, snapshot = null) {
  if (isServer) {
    store = Store.create({ lastUpdate: Date.now() })
  }
  if (store === null) {
    store = Store.create({ lastUpdate: Date.now() })
  }

  if (snapshot) {
    applySnapshot(store, snapshot)
  }

  return store
}
```

**Comment by terrysahaidak** [comment]
I've created something similar to `redux-persist`:
Check it out: 
https://gist.github.com/terrysahaidak/43f316d278f8519538e69e7fd2c737a3

**Comment by agilgur5** [comment]
Just wanted to note for anyone else looking for a persistence solution for MST: I recently created [mst-persist](https://github.com/agilgur5/mst-persist) to simplify this a bit and unify the various gists and examples out there :) 

Per https://github.com/pinqy520/mobx-persist/issues/37#issuecomment-493830440 , I can confirm its working and am using it in a production app. For now just a tiny wrapper around `onSnapshot` and `applySnapshot` similar to most of the gists and examples around.
