### ISSUE TITLE
Running actions from server

### ISSUE THREAD

**Issue by stephane-r** [mobxjs/mobx-state-tree#1024]
I have:

* [x] A conceptual question. 
  * [x] I've checked documentation and searched for existing issues
  * [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3) first
* [ ] I think something is not working as it should.
  * [ ] I've checked documentation and searched for existing issues
  * [ ] I've made sure your project is based on the latest MST version
  * [ ] Fork [this](https://codesandbox.io/s/jlnmjqr7xv) code sandbox or another minimal reproduction. 
  * [ ] Describe expected behavior
  * [ ] Describe observed behavior
* [ ] Feature request
   * [ ] Describe the feature and why you feel your feature needs to be generically solved inside MST
   * [ ] Are you willing to (attempt) a PR?

Hi community :)

I use mobx-state-tree on new NextJS project with SSR. I don't know if i can, but i would like run MST actions from server : 

```
app.prepare().then(() => {
  express()
    .get('/get-command', async () => {
      const request = await callApi();
      return userStore.myActions(request);
    })
    .use(handler).listen(port);
});
```
On next, i init my store with this : 

```
const Store = types.model('Store', {
  user: types.maybe(User)
});

const createStore = Store.create({
  user: {}
});

let store = null;

const initStore = (isServer, snapshot = null) => {
  if (isServer) {
    store = createStore;
  }

  if (store === null) {
    store = createStore;
  }

  if (snapshot) {
    applySnapshot(store, snapshot);
  }

  return store;
};
```

Is it possible to run an `actions` from server ? (express in my case)

Thank you community !

**Comment by BojDom** [comment]
Obviously is possibile, what is the issue that you facing?

**Comment by mweststrate** [comment]
Also check the `onAction` / `applyAction` api's, which might simplify
things (assuming your arguments are serializable)

Op wo 26 sep. 2018 om 14:33 schreef BojDom <notifications@github.com>:

**Comment by stephane-r** [comment]
@BojDom In my first post, `return userStore.myActions(request);` return an error. I think it's normal ^^ but i don't know how i can use my store from the server

@mweststrate Thank you, I'll go and see that !

Actualty i return my response from server and i run my action from client : 

 ```
 express()
    .get('/get-command', async (req, res) => {
      const request = await callApi();
      res.json(request);
    })
```

And on my actions : 

```
async fetchCommands() {
  const commands = await callServer('/get-command');
  console.log(commands.command);
}
```

I think i can simplify the process by running my action directly from server.
