### ISSUE TITLE
What are the transaction boundaries in mobx-state-tree?

### ISSUE THREAD

**Issue by lidermanrony** [mobxjs/mobx-state-tree#1030]
I have:

* [ X] A conceptual question. 
  * [X ] I've checked documentation and searched for existing issues
  * [ X] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3) first
* [ ] I think something is not working as it should.
  * [ ] I've checked documentation and searched for existing issues
  * [ ] I've made sure your project is based on the latest MST version
  * [ ] Fork [this](https://codesandbox.io/s/jlnmjqr7xv) code sandbox or another minimal reproduction. 
  * [ ] Describe expected behavior
  * [ ] Describe observed behavior
* [ ] Feature request
   * [ ] Describe the feature and why you feel your feature needs to be generically solved inside MST
   * [ ] Are you willing to (attempt) a PR?
   
specifically i'm interested in whether actions (async ones if that makes any difference) are atomic.
meaning - should i expect a single onSnapshot callback after i execute such an action?
couldn't find any specifics about it in the documentation.

**Comment by xaviergonz** [comment]
sync actions are atomic

async actions are partially atomic (atomic between yields), e.g. see https://codesandbox.io/s/8l1n2l8qxj

so if you have 
```
someFlow: flow(function*() {
      self.title = "title part 1";
      yield new Promise(r => setTimeout(r, 1000));
      self.title += " and part 2";
    })
```
it will generate two snapshots, one with title "title part 2" and then another with "title part 1 and part 2"

**Comment by xaviergonz** [comment]
async and sync actions sorry
