### ISSUE TITLE
Update snapshot after action from service side

### ISSUE THREAD

**Issue by stephane-r** [mobxjs/mobx-state-tree#1036]
* [x] A conceptual question. 
  * [x] I've checked documentation and searched for existing issues
  * [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3) first
* [ ] I think something is not working as it should.
  * [ ] I've checked documentation and searched for existing issues
  * [ ] I've made sure your project is based on the latest MST version
  * [ ] Fork [this](https://codesandbox.io/s/jlnmjqr7xv) code sandbox or another minimal reproduction. 
  * [ ] Describe expected behavior
  * [ ] Describe observed behavior
* [ ] Feature request
   * [ ] Describe the feature and why you feel your feature needs to be generically solved inside MST
   * [ ] Are you willing to (attempt) a PR?
   
Hi community,

I init my store from server side and running actions if needed. For example : 

```
  static async getInitialProps({ Component, ctx }) {
    const token = ctx.req && ctx.req.session && ctx.req.session.token;
    const isServer = true;
    const store = initStore(isServer);
    let pageProps = {};

    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx);
    }

    if (token) {
      store.app.setConnected();
      console.log(store.app.isConnected);
    }

    return { pageProps, initialState: getSnapshot(store), isServer, store };
  }

  componentDidMount() {
    console.log(this.props.initialState);
  }
```

The first `console.log(store.app.isConnected` have good value `true`. But on `componentDidMount()` method, the value of `isConnected` is initial : `false` and i don't really understand why.

Maybe i need to update the snapshot after every action ?

```
    setConnected() {
      self.isConnected = true;
      // Update snapshot ?
    }
```

**Comment by xaviergonz** [comment]
did you decorate your react component with `@observer` ?

**Comment by xaviergonz** [comment]
Also you are not supposed to pass to the component the snapshot of the store, but the store (or parts of the store) itself.

**Comment by xaviergonz** [comment]
Basically getSnapshot is usually used to serialize it to json to store it somewhere. Once you use getSnapshot over a store it becomes a fixed immutable copy of the store at that particular moment it was called.

**Comment by xaviergonz** [comment]
```
const TStore = types.model({x: 10});
const store = TStore.create();
...
<SomeComponent store={store}/> // render() { return `x is ${this.props.store.x}` }
// or
<SomeComponent x={store.x}/> // render() { return `x is ${this.props.x}` }
```

**Comment by stephane-r** [comment]
Thank you @xaviergonz for your response.

Nop, i don't have `@oberserver` on my component, because the store become from server side :)
