### ISSUE TITLE
UMD module is always in production mode, add a debug UMD module

### ISSUE THREAD

**Issue by leonalliander** [mobxjs/mobx-state-tree#1038]
I have:

* [] A conceptual question. 
  * [] I've checked documentation and searched for existing issues
  * [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3) first
* [x] I think something is not working as it should.
  * [x] I've checked documentation and searched for existing issues
  * [x] I've made sure your project is based on the latest MST version
  * [x] Fork [this](https://codesandbox.io/s/jlnmjqr7xv) code sandbox or another minimal reproduction. 
  * [x] Describe expected behavior
  * [x] Describe observed behavior
* [ ] Feature request
   * [ ] Describe the feature and why you feel your feature needs to be generically solved inside MST
   * [ ] Are you willing to (attempt) a PR?
   
I am observing different behaviour between using MST loaded by a script tag and MST loaded as a node-module.

In the latter case model.create() does not seem to do *any* checks regarding the types. You can leave them empty or even assign a different type to a property, such as an integer instead of a string.

```
// MST and mobx loaded via script-tags:
// <script src="https://unpkg.com/mobx@5.5.0/lib/mobx.umd.js" type="text/javascript"></script>
// <script src="https://unpkg.com/mobx-state-tree@3.5.0/dist/mobx-state-tree.umd.js" type="text/javascript"></script>

const types = mobxStateTree.types;
const Todo = types.model("Todo", {
  title: types.string,
  body: types.string
})
const todo = Todo.create({
  body: 1
});
alert(JSON.stringify(todo)); // yields: { body: 1 } (instead of an error)
```

Do demo the differences between the two ways of loading MST, I have made two identical demo's, with the supposedly only difference being the way MST is added to the project:
https://codesandbox.io/s/jjyq972ko9
https://plnkr.co/edit/KigBAZkdqyhAnLDoIh8D

Am I missing a crucial part in loading MST? Or is this a core issue in MST, when loaded as a script?

Thanks for the help!

**Comment by xaviergonz** [comment]
MST checks `process.env.NODE_ENV === "development"` to enable the checks.
I think such global variable is simple not being injected anywhere in the script case, so it is running in "production" mode by default

**Comment by xaviergonz** [comment]
Actually apparently the UMD module is already pre-processed to substitute this variable as production...
@mweststrate should there be a .umd.debug.js version that substitutes this variable as "development"?

**Comment by mweststrate** [comment]
Good catch. (Also; ah, UMD builds are actually used). I think that the simplest solution to this problem is, change all the checks to `process.env.NODE_ENV !== "production"`. That means that in UMD builds strict checking is enabled by default, and that fast-mode can be opted into.

**Comment by xaviergonz** [comment]
wouldn't rollup still optimize those out anyway?

**Comment by mweststrate** [comment]
Afaik yes

Op do 11 okt. 2018 22:45 schreef Javier Gonzalez <notifications@github.com>:

**Comment by xaviergonz** [comment]
so then there would be no way to opt out since process.env wouldn't exist in the code?
my point is that that change alone is not enough the rollup config would need to be changed for the umd build so it doesn't do the process. env transformation

**Comment by mweststrate** [comment]
Oh might be confusing setups, if ugkify is applied to the umd build that
doesn't help indeed. Separating a minified umd build could help us to pre
built the distinction

Op do 11 okt. 2018 23:13 schreef Javier Gonzalez <notifications@github.com>:

**Comment by xaviergonz** [comment]
actually what about a setDebugMode that by default uses process.env and that can be overridden by the user?

pros: you can opt in for debug checks only for MST if desired, not a breaking change 
cons: debug code would not get optimized away by uglify

**Comment by leonalliander** [comment]
Thanks for the answer so far. I did not know I was using a production version and that this would be the corresponding behaviour. That explains a lot.

It would indeed be nice to have a debug/development umd version because our current development setup doesn't allow for node.js development as is usual in the react-ecosystem, so we that's why we are using the umd build. We are using mobx in a front-end framework called [UI5](https://openui5.org/).

For now, I am thinking of using the [typecheck](https://github.com/mobxjs/mobx-state-tree/blob/master/API.md#typecheck) function to do the typecheck before using model.create() and applySnapshot(). I suppose that should have the intended effect.

**Comment by xaviergonz** [comment]
You should anyway use typecheck if you intend the checking to be present on production, so that's not a good approach.

**Comment by xaviergonz** [comment]
on the next version umd version will be debug and umd.min version will be production (like in the original mobx lib)
same for middlewares (where I the umd version actually had an invalid global name)
