### ISSUE TITLE
Get an array of types.enumeration values

### ISSUE THREAD

**Issue by lidermanrony** [mobxjs/mobx-state-tree#1040]
I have:

* [x] A conceptual question. 
  * [x] I've checked documentation and searched for existing issues
  * [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3) first
* [ ] I think something is not working as it should.
  * [ ] I've checked documentation and searched for existing issues
  * [ ] I've made sure your project is based on the latest MST version
  * [ ] Fork [this](https://codesandbox.io/s/jlnmjqr7xv) code sandbox or another minimal reproduction. 
  * [ ] Describe expected behavior
  * [ ] Describe observed behavior
* [ ] Feature request
   * [ ] Describe the feature and why you feel your feature needs to be generically solved inside MST
   * [ ] Are you willing to (attempt) a PR?
   
I'd like to populate a dropdown with all possible values from an mst-defined types.enumeration. Is there any way to achieve this?

**Comment by xaviergonz** [comment]
If using TS:
```ts
export enum ColorEnum {
    Red = "Red",
    Orange = "Orange",
    Green = "Green"
}
export const colorEnumValues = Object.values(ColorEnum) as ColorEnum[]
export const M = types.model({ color: types.enumeration(colorEnumValues) })

// or alternatively
export const M = types.model({ color: types.enumeration<ColorEnum>(Object.values(ColorEnum)) })

// then use colorEnumValues/Object.values(ColorEnum) in your dropdown
```

if using plain JS:
```js
export const colorEnumValues = ["Red", "Green", "Blue"]
export const M = types.model({ color: types.enumeration(colorEnumValues) })

// use colorEnumValues in your dropdown
```

you can do the JS version on TS too of course, but then you loose strong typing

**Comment by mweststrate** [comment]
Doh, I suggested the unsafe `enumerationType.types.map(l => l.value)`, but the above is the obvious solution :-). Please let us know if that doesn't suffice @lidermanrony. 

(type reflection api's could be extended further, but it is quicky, as enumeration is just an `union` in the end, which might contain not just literals, which the code block above assumes)

**Comment by lidermanrony** [comment]
Thank you so much @xaviergonz and @mweststrate.
using the solution provided by @xaviergonz worked like a charm (which got me thinking - charms don't really work and babies don't really sleep - so why do these phrases even exist?)
