### ISSUE TITLE
Array item not updated when snapshot applied for certain union types

### ISSUE THREAD

**Issue by hamczu** [mobxjs/mobx-state-tree#1045]
I have:

* [x] I think something is not working as it should.
  * [x] I've checked documentation and searched for existing issues
  * [x] I've made sure your project is based on the latest MST version
  * [x] Fork [this](https://codesandbox.io/s/jlnmjqr7xv) code sandbox or another minimal reproduction. 
  * [x] Describe expected behavior
  * [x] Describe observed behavior

**Sandbox:** https://codesandbox.io/s/43mv0yp0v4

**Expected:**
When snapshot for an array is applied - the new value is applied to an array item.

**Observed:**
Array item is not updated. 
![screen shot 2018-10-15 at 15 05 18](https://user-images.githubusercontent.com/298715/46952649-c04b6c00-d08b-11e8-8255-b5ca117583f7.png)

Speculation - it has something to do with union type definition order in combination with maybe types, but I don't know MST well enough to be able to track this issue down.

**Comment by xaviergonz** [comment]
I just created a new sandbox based on yours

https://codesandbox.io/s/ymxv4k2z7z

seems like for some reason the type subtype when using applySnapshot is not being properly inferred (since if Submodel2.create is used inside the object inside applySnapshot then it is inferred properly

Either way, another weird thing is that if the node is accessed before applySnapshot is applied over it then MST will complain that the node is dead (or throw is setLivelynessCheck is set to error)

Nothing of this happens if the submodel type is inferred correctly (like when putting submodel1 before submodel 2 or using a dispatcher)

@k-g-a any ideas?

**Comment by xaviergonz** [comment]
unit test

```ts
describe("1045 - secondary union types with applySnapshot", () => {
    function initTest() {
        setLivelynessChecking("error")

        const Submodel1 = types.model("Submodel1", {
            id: types.identifier,
            extraField1: types.string,
            extraField2: types.maybe(types.string)
        })

        const Submodel2 = types.model("Submodel2", {
            id: types.identifier,
            extraField1: types.maybe(types.string),
            extraField2: types.string
        })

        const Submodel = types.union(Submodel2, Submodel1)

        const Model = types.model("Model", {
            array: types.array(Submodel)
        })

        const store = Model.create({
            array: [
                {
                    id: "submodel1",
                    extraField1: "extraField1"
                }
            ]
        })

        return {
            store,
            applySn: function(useCreate: boolean) {
                const sn = {
                    id: "submodel1",
                    extraField1: "new extraField1",
                    extraField2: "some value"
                }

                applySnapshot(store.array, [useCreate ? Submodel1.create(sn) : sn])

                expect(store.array.length).toBe(1)
                expect(store.array[0]).toEqual(sn)
                expect(getType(store.array[0])).toBe(Submodel1)
            }
        }
    }

    for (const useCreate of [true, false]) {
        const usingCreate = useCreate ? "using create" : "not using create"
        it(`apply snapshot works when the node is not touched - ${usingCreate}`, () => {
            const t = initTest()
            t.applySn(useCreate)
        })

        it(`apply snapshot works when the node is touched - ${usingCreate}`, () => {
            const t = initTest()
            // tslint:disable-next-line:no-unused-expression
            t.store.array[0]
            t.applySn(useCreate)
        })
    }
})

```

**Comment by xaviergonz** [comment]
only seems to happen when an array is involved, tried it with a plain submodel as a property and it was ok

**Comment by hamczu** [comment]
you're guys are absolutely fantastic! I cannot even express how much I appreciate the effort you put into this project!

I tried to show the example in a way it's easy to convert to unit test :)
