### ISSUE TITLE
Using mst model structure as a type

### ISSUE THREAD

**Issue by naorzr** [mobxjs/mobx-state-tree#1048]
I have:

* [V] A conceptual question. 
  * [V] I've checked documentation and searched for existing issues
  * [ V] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3) first

Hey,
Lets assume i have a an "EventModel" and i wish to use this model as a type outside the scope of mst and inside a function of some sort with typescript. is there a way of doing it without typing an identical interface to eventModel?

for further clarification, if i have a model as follow
```

const A = types.model(
a: types.string,
b: types.number
)
```
is there a way to generate the identical copy of a none mst model
as follow from the mst model
```
interface B{
a: string,
b: number
}
```

**Comment by zmayor** [comment]
@xaviergonz Is there any possibility to transform `interfaces` to `mst models`? In other word, can I define a mst model with `interface` but `mst types`?

**Comment by xaviergonz** [comment]
you'd need to create a tool that uses the typescript parser to parse the abstract tree of the interface and then generate a js file that generates the appropriate js code out of it

**Comment by xaviergonz** [comment]
actually that could be a cool idea for a typescript transformer, but still you'd loose optional defaults

**Comment by zmayor** [comment]
I met some trouble when I was trying to transform `type` into `interface`, can you tell me what's wrong?
This is the [codesandbox](https://codesandbox.io/s/0138m6ymjw), please look at the `schema.ts`.

**Comment by xaviergonz** [comment]
that's because the object your are declaring is actually a SnapshotOut, not an Instance

**Comment by xaviergonz** [comment]
in the docs there are more details about the differences between SnapshotIn, SnapshotOut and Instance

**Comment by xaviergonz** [comment]
https://github.com/mobxjs/mobx-state-tree/blob/master/README.md#using-a-mst-type-at-design-time

**Comment by naorzr** [comment]
thanks for the help

**Comment by xaviergonz** [comment]
no problem 😁
