### ISSUE TITLE
Existing model as a volatile state

### ISSUE THREAD

**Issue by Codeluck** [mobxjs/mobx-state-tree#1049]
Mobx-state-tree v.2.2.0
I have a gallery model with sub-model named as GalleryItem.
I wanna reuse my code and put GalleryItem as a member or as a volatile member into my core Document model. Everything goes smooth until I call an asynchronous method with ```*/yield``` generator. Looks like it freezes the model and the browser became so slow after that. For instance: when I hover over a button it become hovered only after several seconds. Can you explain what's going on there? Is it a good practice to use another unrelated models in a volatile state?

**Comment by xaviergonz** [comment]
could you create an example on codesandbox? it is hard to tell what's going on only from the description

**Comment by Codeluck** [comment]
> could you create an example on codesandbox? it is hard to tell what's going on only from the description

Sorry, I think I found the root of the issue. It's unrelated to mobx-state-tree My bad. I am closing this ticket.
