### ISSUE TITLE
types.maybe null values

### ISSUE THREAD

**Issue by robinfehr** [mobxjs/mobx-state-tree#105]
when using types.maybe a json can contain null values which of course lead to null values within the store. not sure if i'm alone but i kind of feel like that it had bee nice if these null values would become undefined so we could write the components like:

```
const { arrows = [], boxes = new Map() } = store;
const boxesValues = Array.from(boxes.values()) || [];
```

instead of

```
const arrows = store.arrows || [];
const boxes = (store.boxes && store.boxes.values()) || [];
```

**Comment by mattiamanzati** [comment]
Maybe it's intended to have null as value if not provided, maybe you're talking about the possibility of missing keys in models? Not sure if it's a good thing, what do you think @mweststrate ?

**Comment by robinfehr** [comment]
@mattiamanzati you're right it's the use case i'm currently facing. i tried to leave out some keys but had to add them which made me add the null values in the first place

**Comment by mweststrate** [comment]
Snapshot are always assumed to be complete indeed. For partial updates, `Object.assign(modelInstance, data)` might work, and possible we need a smarter merge in the future, to update trees only partially. But I noticed in the past it is a tricky problem to solve, especially for collections like arrays / maps. (recycle items? purge non-existing items? etc...)
