### ISSUE TITLE
Model for object with dynamic keys

### ISSUE THREAD

**Issue by Skyien** [mobxjs/mobx-state-tree#1054]
**_Question_**

* [X] I've checked documentation and searched for existing issues
* [X] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

What is the best way to define model for below object with dynamic keys? 
```

schedule: {
  '8c4350518b7f462aac80f047a3f94232': {
    tasks: [
      ...
    ],
  },
'2fdab8d81dfd43fb91345bf6f93a50f1': {
    tasks: [
      ...
    ],
  },
},
```

**Comment by xaviergonz** [comment]
```
const TaskList = types.model({
  tasks: types.aray(.....)
})

const Store = types.model({
  schedule: types.map(TaskList)
})
```

**Comment by Skyien** [comment]
@xaviergonz Great, thank you!

**Comment by xaviergonz** [comment]
no problem 😁
