### ISSUE TITLE
add Model life cycle hooks

### ISSUE THREAD

**Issue by yonatanmn** [mobxjs/mobx-state-tree#1056]
**_Feature request_**

**Is your feature request related to a problem? Please describe.**
I'm doing some kind of complex factory that returns a model. 
Some hooks that are relevant to store, like `onSnapshot` and `onAction`, should also be available on the model.

Lets say  => 
```js

function createBaseModel(){
  return types.model({
     x: types.number
  })
  .actions({ updateX(num) {self.x = num} )
  
}
// I use factory here since my real usage also incorporates adding custom model as an argument. 

```
and I extend it: 
```js
const baseWithCounter = 
  types.compose( 
   createBaseModel(), 
   types
     .model({ counter: types.number })
    .actions({ increment: self.counter ++ } )
)
```
now, if I want to increment counter with every `updateX`, I can create a store, add `onAction` and do `increment`, but I want this on the model for re-usability. 

**Describe the solution you'd like**
Would love to see something like: 

```js
const baseWithCounter = 
  types.compose( 
   createBaseModel(), 
   types.model({ counter: types.number })
    .actions({increment: self.counter ++} )
    .onAction(self, call => {
        if(call.name === 'updateX'){
              self.increment()
              // btw - can `call === self.updateX` work ? 
        }
    })
)
```

Even more than that, and I guess this is relevant for both for store and model - if I want to do some action based on previous state, I'd love to see some hook that provides before/after, similar to react will/did update, like: 

```js
const baseWithCounter = 
    createBaseModel()
      ...
     .onModelDidUpdate(self, prevSnapshot){ ... }

```

**Are you willing to (attempt) a PR?**
* [* ] Yes
* [ ] No

**Comment by Amareis** [comment]
I think it can be achivied via model-base effects, which is discussed in #867
Something like
```js
const baseWithCounter = 
  types.compose( 
   createBaseModel(), 
   types.model({ counter: types.number })
    .actions({increment: self.counter ++} )
    .effects(self => ({
        actionsReaction = () => onAction(self, call => {...})
    }))
)
```

**Comment by xaviergonz** [comment]
why not put onAction inside afterCreate?
```js
const baseWithCounter = 
  types.compose( 
   createBaseModel(), 
   types.model({ counter: types.number })
    .actions({increment: self.counter ++} )
    .actions(self => ({
      afterCreate() {
        self.addDisposer(self.onAction(...., () => {...})
      }
    })
)
```

**Comment by yonatanmn** [comment]
Interesting idea, I'll check this out
Though `onAction` itself does not provide the before/after comparison. Perhaps we should add `previousSnapshot` to `onSnapshot` event?

**Comment by Amareis** [comment]
Previous value also can be achived via custom effects, I think, just some extra sugar for keeping old value and pass it to function.

**Comment by xaviergonz** [comment]
Closing in favor of discussion #867
