### ISSUE TITLE
Unexpected behaviour of reference in combination with maybe

### ISSUE THREAD

**Issue by mrtnbroder** [mobxjs/mobx-state-tree#1057]
I've been trying to get this working now for quite a while now and still don't have a clue on how I'd solve this issue. In my opinion the behaviour of mobx-state-tree is incorrect.

When mobx-state-tree tries to resolve a reference like this:

[https://codesandbox.io/s/rlrjlwo67n](https://codesandbox.io/s/rlrjlwo67n)

```
import { types } from "mobx-state-tree";

const Dog = types.model("Dog", {
  id: types.identifierNumber,
  name: types.string
});

const User = types.model("User", {
  id: types.identifierNumber,
  dogs: types.optional(types.array(types.maybeNull(types.reference(Dog))), [])
});

const Root = types.model("Root", {
  dogs: types.map(Dog),
  users: types.map(User)
});

const store = Root.create({
  dogs: {
    123: {
      id: 123,
      name: "Charlie"
    }
  },
  users: {
    456: {
      id: 456,
      dogs: [45] // dog with this id does not exist
    }
  }
});
```

```
store.users.get(456)
```
then I get an error thrown at me:

```
[mobx-state-tree] Failed to resolve reference '45' to type 'Dog' (from node: /users/456/dogs/0)
```

Even though I explicitly said that the reference **can** be `null`/`undefined`

I would expect the reference to resolve to `null` in this case (and `undefined` for `types.maybe`) and **not** throw.

This might be a conceptual issue, but I have no idea how I'd otherwise get the behaviour I want.

* [x] I've checked documentation and searched for existing issues
* [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

**Comment by xaviergonz** [comment]
with
```
dogs: types.optional(types.array(types.maybeNull(types.reference(Dog))), [])
```
you are basically saying "my array named dogs can have either null elements or valid references
e.g, [null, 123] is ok, [null, null] is ok, [123] is ok
but in no case myabeNull means "this reference can be null, ok or invalid"

for a behaivor that you want (an invalid reference should resolve to null) you can use custom references https://github.com/mobxjs/mobx-state-tree#customizable-references

**Comment by mrtnbroder** [comment]
I managed to get it working now with custom references in a way that I'm happy with it for everyone else: https://codesandbox.io/s/ql506pkprq

But yes I like your idea @xaviergonz

**Comment by xaviergonz** [comment]
Then again I guess it is a matter of doing
```
function refOrNull(fn) {
  try { return fn(); } catch { return null }
}

const dog = refOrNull(() => root.badDog); // if ref doesn't exist it will return null
```

so closing :)
