### ISSUE TITLE
bug within example boxes

### ISSUE THREAD

**Issue by robinfehr** [mobxjs/mobx-state-tree#106]
i run into the same bug as the example contains: 

after fixing the webpack alias and installing the newest version of mobx i get these kind of errors when moving boxes:

`Side effects like changing state are not allowed at this point. Are you trying to modify state from, for example, the render function of a React component? Tried to modify: Box@21.x`

**Comment by robinfehr** [comment]
i've found the cause - actions are now within the second param. I'll will provide a PR

**Comment by mweststrate** [comment]
Awesome! Examples indeed still need to be updated, finalizing the api first :)

**Comment by mweststrate** [comment]
Merged and updated a bit further. Thanks a lot!
