### ISSUE TITLE
Broken reference after 3.7.1 update

### ISSUE THREAD

**Issue by gcangussu** [mobxjs/mobx-state-tree#1062]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**

https://codesandbox.io/s/k2479595yv

**Describe the expected behavior**

It should work, as it worked with 3.7.0, you can try with the codesandbox example.

**Describe the observed behavior**

`[mobx-state-tree] Failed to resolve reference '0.12033527514390441' to type 'Todo' (from node: /oneTodo)`

**Comment by xaviergonz** [comment]
In other words, references are supposed to point to non-reference nodes that are present on the store, not to random nodes not already present there

**Comment by xaviergonz** [comment]
If you don't really want a reference, but a whole new node then just use
```
oneTodo: types.maybe(Todo) // instead of types.maybe(types.reference(Todo))
```

**Comment by gcangussu** [comment]
> `oneTodo: types.maybe(Todo) // instead of types.maybe(types.reference(Todo))`

Thank you, that solved my problem with the newer version. But now I don't understand how with the older version it worked the way it was.

**Comment by xaviergonz** [comment]
Allowing it "kind of" worked but was a bug, and probably it would have given you troubles down the road :)

**Comment by xaviergonz** [comment]
For example, the snapshot of that would have given you
```
{
  todos: [ {id: 12345, title: "hey" }], oneTodo: 4444
}
```
and then you will be left wondering why it crashes when constructing it again from the snapshot (since the snapshot of references is just the id, not any other data)

**Comment by gcangussu** [comment]
Ah! Now I got it, thanks for your time!

**Comment by xaviergonz** [comment]
No problem :)
