### ISSUE TITLE
ReduxDevTools throws an error - when flow action is called first

### ISSUE THREAD

**Issue by mkramb** [mobxjs/mobx-state-tree#1065]
An issue from v3.7.0 - after redux middleware refactor https://github.com/mobxjs/mobx-state-tree/commit/d8f449efe11fe688238f0f9264793e562d209ebe

I have an issue when registering redux dev tools. On store creation, I'm immediately performing an API call (which utilizes asynchronous flow  - generator function) which happens inside `afterCreate` hook, the code looks like this:

```
export const Root = types
    .model({
        teams: types.optional(Teams, { data: [] })
    })
    .actions(self => {
        return {
            afterCreate: () => {
                self.teams.loadTeams();
            }
        };
    });

export const store = Root.create({}, { fetch });

if (process.env.NODE_ENV !== 'production') {
    const { connectReduxDevtools } = require('mst-middlewares');
    const remotedev = require('remotedev');

    connectReduxDevtools(remotedev, store);
}
```

But in that case, redux middleware throws an error:

![screenshot 2018-10-27 at 21 10 24](https://user-images.githubusercontent.com/218816/47608914-766c6980-da2d-11e8-82fa-9b67dc76df89.png)

I think the problem is in the redux middleware code flow, which doesn't account for `flow_*` being called before any `action` and in that case the `context` is `undefined`.

**Comment by xaviergonz** [comment]
@mkramb added a question to the PR

**Comment by xaviergonz** [comment]
Fix merged. Will be fixed in next mst version, thanks!
