### ISSUE TITLE
How to make use of API that returns '<attribute>Id' with mobx references?

### ISSUE THREAD

**Issue by hashwin** [mobxjs/mobx-state-tree#1069]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

Just getting the hang of MST, seems like a very powerful concept.
Looking through the docs, I have a bit of confusion between ids and references.

Take the example given in the docs:
```
const Todo = types.model({
    id: types.identifier,
    title: types.string
})

const TodoStore = types.model({
    todos: types.array(Todo),
    selectedTodo: types.reference(Todo)
})

// create a store with a normalized snapshot
const storeInstance = TodoStore.create({
    todos: [
        {
            id: "47",
            title: "Get coffee"
        }
    ],
    selectedTodo: "47"
})
```

My question here is that what if I have an API that returns the key as "selectedTodoId" rather than "selectedTodo" (as a matter of convention as you would expect an entire todo object rather than an ID otherwise), but I would still like to maintain the reference model as "selectedTodo".

i.e. the response from my API would look like this:
```
{
    todos: [
        {
            id: "47",
            title: "Get coffee"
        }
    ],
    selectedTodoId: "47"
}
```
While still being able to use ```console.log(storeInstance.selectedTodo.title)```

 I would follow the same pattern across all my models - if it ends with "Id", I would like to strip that off the key when using my reference.

Does MST support such a paradigm?

**Comment by xaviergonz** [comment]
you can use preprocessSnapshot

alternatively you can make a new view called selectedTodo that just returns the selectedTodoId property
