### ISSUE TITLE
Error with calculating type of field in TS using .props

### ISSUE THREAD

**Issue by witqq** [mobxjs/mobx-state-tree#1070]
**_Bug report_**

* [* ] I've checked documentation and searched for existing issues
* [* ] I've made sure my project is based on the latest MST version
* [* ] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/9y4k8yxp2w

**Describe the expected behavior**

when try to implement inheritance, child class cannot take correct type of field

in my case TS said that there not "type" filed in item when i try to implement findByType function

 
```javascript
import {types, IModelType, ModelProperties, IArrayType} from "mobx-state-tree";

export const BaseItem = types.model({
  id: types.string
});

export const ChildItem = BaseItem.props({
  type: types.string
});

const BaseStore = types.model({
    items: types.array(BaseItem)
  })
  .actions(self => ({
    findById(id: string) {
      return self.items.find(item => item.id === id);
    }
  }));

const ChildStore = BaseStore.props({
  items: types.array(ChildItem)
})
  .views(self => ({
    findByType(type: string) {
      return self.items.filter(item => item.type === type); // . Error here
    }
  }));
```

**Comment by xaviergonz** [comment]
The code you pasted doesn't have TS errors (and item.type is correctly inferred as string) when I tried (TS 3.1.3 and 2.9.2, MST3.7.1).

Which TS/MST versions are you using?
Did you try resetting the TS cache (if using vscode) or resetting any caches your IDE of choice might have?

**Comment by witqq** [comment]
Hello
i use TS 3.1.5 and mst 3.7.1
I Try invalidate caches in my webshtrom, but it not not help

![image](https://user-images.githubusercontent.com/25282049/47875719-1284df00-de39-11e8-82e2-cd7acf6ff212.png)

**Comment by witqq** [comment]
and there is error in codesanbox

![image](https://user-images.githubusercontent.com/25282049/47875908-9c34ac80-de39-11e8-875c-e686f69bb198.png)

**Comment by xaviergonz** [comment]
![image](https://user-images.githubusercontent.com/6306796/47876178-f3765500-de18-11e8-9570-a6742661e6ea.png)

That's using TS 3.1.5

I'm not sure which version of TS codesandbox has installed

Are you using strict mode?

**Comment by witqq** [comment]
thanks for your answer!
No, i don't use strict mode, i think
I have no ideas how to fix it =///

**Comment by xaviergonz** [comment]
can you please upload a minimal example to github?

**Comment by witqq** [comment]
https://github.com/witqq/mst-error-test/tree/master
steps to reproduce in README

**Comment by xaviergonz** [comment]
Ah, I just noticed
BaseStore
`items: types.array(BaseItem)`
ChildStore
`items: types.array(ChildItem)`

I might not be 100% sure, but I think you are not supposed to override props like that (this is, once a prop with a name is set to a type it shouldn't be changed)

**Comment by witqq** [comment]
maybe u know any workaoround to achieve same result?
If i will use factory functions, there would be generics and i can't get type of model thats generic function return

**Comment by xaviergonz** [comment]
dunno, something like this?
```ts
    const BaseItem = types.model({
        id: types.string
    })

    const ChildItem = BaseItem.props({
        type: types.string
    })

    const ReallyBaseStore = types.model({
        items: types.array(BaseItem)
    })

    function modelWithBaseStuff<IT extends IAnyModelType>(model: IT) {
        return model.actions((self: Instance<typeof ReallyBaseStore>) => ({
            findById(id: string) {
                return self.items.find(item => item.id === id)
            }
        }))
    }

    const BaseStore = modelWithBaseStuff(types.model({ items: types.array(BaseItem) }))

    const ChildStore = modelWithBaseStuff(
        types.model({ items: types.array(ChildItem) }).views(self => ({
            findByType(type: string) {
                return self.items.filter(item => item.type === type) // . Error here
            }
        }))
    )

```

**Comment by witqq** [comment]
this is not types safe, because i can use it like 
```javascript
const tmp = modelWithBaseStuff(types.model({noItemsField:types.string}))
```
