### ISSUE TITLE
TS error that index signature with Map of maps model

### ISSUE THREAD

**Issue by naorzr** [mobxjs/mobx-state-tree#1072]
**_Bug report_**

* [V] I've checked documentation and searched for existing issues
* [V] I've made sure my project is based on the latest MST version
* [V] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**

`const firstModel = types.model({
  brew1: types.map(types.number)
})`

`const secondModel = types.model({
  brew2: types.map(firstModel)
})`

`const store = secondModel.create({brew2: {outside: {brew1: {inner: 222}}} })`

`const appMod = types.model({
  aaa: secondModel
})`

`const appStore = appMod.create({
  aaa: store
})`

I'm getting a TS error that index signature is missing in type etc,
This seems to happend when im trying to create a store from a model that contains map of maps, but i might be wrong about that.

**Comment by xaviergonz** [comment]
when trying to use instances where an snapshot is wanted (or vice-versa) use cast

in this case it will "cast" (only the TS type) any mode instances into their snapshot type

```
import {cast} from "mobx-state-tree"
...
const appStore = appMod.create({ aaa: cast(store) })
```

alternatively just use proper snapshot types like this instead
```
const firstModel = types.model({ brew1: types.map(types.number) })

const secondModel = types.model({ brew2: types.map(firstModel) })

const store: SnapshotIn<typeof secondModel> = { brew2: { outside: { brew1: { inner: 222 } } } } // the type is optional

const appMod = types.model({ aaa: secondModel })

const appStore = appMod.create({ aaa: store })
```

**Comment by naorzr** [comment]
Worked like a charm.
Thanks alot!
can you explain abit further the root of this?

**Comment by elie222** [comment]
Same issue with stores that contain maps, but cast isn't working on the store for some reason.

This is the error I get when using `cast`:

```
(87,21): Argument of type 'ModelInstanceType<ModelPropertiesDeclarationToProperties<{ windows: IMapType<IModelType<ModelPropertiesDeclarationToProperties<{ id: ISimpleType<string>; windowType: ISimpleType<WindowType>; title: ISimpleType<string>; x: IMaybe<ISimpleType<number>>; y: IMaybe<ISimpleType<number>>; width: IMaybe<...>; height: IMaybe...' is not assignable to parameter of type 'ExtractCFromProps<RequiredPropsObject<ModelPropertiesDeclarationToProperties<{ windows: IMapType<IModelType<ModelPropertiesDeclarationToProperties<{ id: ISimpleType<string>; windowType: ISimpleType<WindowType>; title: ISimpleType<string>; x: IMaybe<ISimpleType<number>>; y: IMaybe<ISimpleType<number>>; width: IMaybe<...'.
  Types of property 'windows' are incompatible.
    Type 'IMSTMap<IModelType<ModelPropertiesDeclarationToProperties<{ id: ISimpleType<string>; windowType: ISimpleType<WindowType>; title: ISimpleType<string>; x: IMaybe<ISimpleType<number>>; y: IMaybe<ISimpleType<number>>; width: IMaybe<ISimpleType<...>>; height: IMaybe<...>; background: IMaybe<...>; zIndex: IMaybe<...>; }>,...' is not assignable to type 'IKeyValueMap<ExtractCFromProps<RequiredPropsObject<ModelPropertiesDeclarationToProperties<{ id: ISimpleType<string>; windowType: ISimpleType<WindowType>; title: ISimpleType<string>; x: IMaybe<ISimpleType<number>>; y: IMaybe<ISimpleType<number>>; width: IMaybe<...>; height: IMaybe<...>; background: IMaybe<...>; zInde...'.
      Index signature is missing in type 'IMSTMap<IModelType<ModelPropertiesDeclarationToProperties<{ id: ISimpleType<string>; windowType: ISimpleType<WindowType>; title: ISimpleType<string>; x: IMaybe<ISimpleType<number>>; y: IMaybe<ISimpleType<number>>; width: IMaybe<ISimpleType<...>>; height: IMaybe<...>; background: IMaybe<...>; zIndex: IMaybe<...>; }>,...'.
```

Could only things working with `as any` for now.

**Comment by Bnaya** [comment]
@elie222 no idea if its related,
but i got `Index signature is missing` error when `keyofStringsOnly` was true in my tsconfig

**Comment by xaviergonz** [comment]
Could you please post a minimal reproduction code?

**Comment by naorzr** [comment]
@xaviergonz at the time i wrote the answer it actually fixed it, but now the error reappear

**Comment by addamove** [comment]
https://mobx-state-tree.js.org/API/#casttosnapshot worked for me
