### ISSUE TITLE
No response returned (204 No-Content)

### ISSUE THREAD

**Issue by aibrahim3546** [mobxjs/mobx-state-tree#1073]
**_Question_**

* [x] I've checked documentation and searched for existing issues

How to handle, if there is no response from the requested URL. Example code 204 is returned.
Currently when there is no response returned by the URL. my request fall under catch instead of success.

**Comment by k-g-a** [comment]
MST itself does not provide any means for network requests, so this question seems unrelated.
Could you get in more details or code example?

**Comment by aibrahim3546** [comment]
@k-g-a thank you for the reply. I figured that this is not the MST problem. This problem was solved by fixing my [FETCH API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch).
