### ISSUE TITLE
[Question/Feature request] How to convert GraphQL JS object to MST model

### ISSUE THREAD

**Issue by aksonov** [mobxjs/mobx-state-tree#1075]
**_Question_**

* [x ] I've checked documentation and searched for existing issues
* [x ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

I asked this question already, got no response:
https://spectrum.chat/mobx-state-tree?thread=cd7942cd-a9b2-4485-a4ad-24a746314477

My question is still the same - what is easiest way to transfer GraphQL data into MST data with references. Currently I have to implement multiple 'storages' for 'referenced' models, add new instances to them (or change existing ones) and manually convert 'fat' graphql JSON to 'referenced' JS structures required to create MST models.

It would be great feature of MST if it would be able to automatically create/updated referenced object if real object is given, not identifier...

Example:

graphql message object:
`{message: 'hello world', owner: { id:  '1231031290389' , handle: 'user1 }}`

With current MST I have to add `user` to  some storage (`users` model) and then replace JS map to identifier: `{message: 'hello world', owner: '1231031290389' }`

Things would become VERY complicated if we have many MST models and relations between them (as reference)

**Comment by aksonov** [comment]
FYI: I tried to solve it with custom references, but didn't found the solution

**Comment by xaviergonz** [comment]
what is handle for in graphql?

**Comment by aksonov** [comment]
@xaviergonz It is just field for Profile entity, for example. So we have following GraphQL schema here:
```
Profile {
 id: ID
 handle: string
}

Message {
   message: string
   owner: Profile
}
```

**Comment by aksonov** [comment]
@xaviergonz, @mweststrate could you answer?

**Comment by xaviergonz** [comment]
so the 'profile' is the 'user'?
This is, the only field of user is an id and a handle: string?

**Comment by aksonov** [comment]
@xaviergonz It was just example. It can be arbitrary object with arbitrary data. All I want to know is how to convert JS objects returned by GraphQL client to MobX objects with references. Custom references cannot do that.

**Comment by xaviergonz** [comment]
I think your best bet would be to pass the graphql snapshot over a custom function (outside MST) and make that modify the model, but without more info it is hard to guess.

E.g.
```js
const User = types.model({
  handle: types.string,
  messages: types.array(types.string)
}).actions(self => ({
  addMessage(msg) {
    self.messages.push(msg)
  }
}))

const Store = types.model({
  users: types.map(User)
}).actions(self => ({
  addUser(id, handle) {
    return self.users.set(id, {
      handle
    })
  }
}))

const store = Store.create()

function gotMessage(graphQlObj) {
  let owner = store.users.get(graphQlObj.owner.id);
  if (!owner) {
    owner = store.addUser(graphQlObj.owner.id, graphQlObj.owner.handle)
  }
  owner.addMessage(graphQlObj.message)
}
```

Maybe it could be done in a smarter way, but the fact that graphql returns partial data while MST expects all data makes it hard. E.g. GraphQL works in a more "SQL" way by making objects have "owners", but MST is usually better used in a more traditional OOP way, where objects have their owned children as members.

Another (possibly better) approach would be to use somehing like updateSnapthot (https://github.com/mobxjs/mobx-state-tree/issues/120) but that's not yet implemented.

**Comment by xaviergonz** [comment]
Maybe what you actually want is something like this?
https://www.apollographql.com/docs/react/essentials/local-state.html

>We’ve learned how to manage remote data from our GraphQL server with Apollo Client, but what should we do with our local data? We want to be able to access boolean flags and device API results from multiple components in our app, but don’t want to maintain a separate Redux or MobX store. Ideally, we would like the Apollo cache to be the single source of truth for all data in our client application.

>That’s where apollo-link-state, our solution for managing local data in Apollo Client, comes in. apollo-link-state allows you to store your local data inside the Apollo cache alongside your remote data. To access your local data, just query it with GraphQL. You can even request local and server data within the same query!

**Comment by aksonov** [comment]
@xaviergonz Thank you for the answer but your code looks too complicated, especially if it is big model. Ok, so I understand now that MST doesn't have suitable mechanism for it and we have to do it manually...

**Comment by birkir** [comment]
https://github.com/birkir/graphql-mst

**Comment by mweststrate** [comment]
See also #1148
