### ISSUE TITLE
Using undo/redo for an editor

### ISSUE THREAD

**Issue by Dairnon** [mobxjs/mobx-state-tree#1076]
**_Question_**

* [Y ] I've checked documentation and searched for existing issues
* [X ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

I've been writing a map editor using mobx-react and pixijs. I started out with just pure mobx and was able to succesfully get a lot of what I wanted working. I ran into some issues related to updating stuff based on nested objects (finding out that I either need to observe the object itself, or use an array/map for adding/removing objects)

I however ran into an issue with undo/redo. I've been trying to study for a while on how to approach this issue using the default mobx and have tried a few different solutions. They always ended up with me running into problems tho (the biggest being losing the reference to previous objects for react). 

Researching I found a lot of people suggest mobx-state-tree (I even found suggestions for observing the removal of objects.) I am curious if mobx-state-tree would be worth switching my editor over to, since its redo/undo stuff seems built into the tree nature of it. 

I figured the editor is kinda a tree anyway (map--> items-->props?) so that maybe it'd be a good to use.

I wanted to see what people here thought about using it, and if its worth switching over to mst, or if I should continue looking for a different solution for mobx. What's most important to me is if I keep the reference of my objects when undo/redo.

**Comment by xaviergonz** [comment]
Definitely, 

also if in the future you want to allow multiple clients to edit the same map concurrently you just need to capture intended actions on the client, send them to the server, let the server apply them and replicate the actions to all the clients

**Comment by Dairnon** [comment]
Thanks, this helps a lot! I appreciate you taking the time to respond!
