### ISSUE TITLE
Composing stores

### ISSUE THREAD

**Issue by jamieallen59** [mobxjs/mobx-state-tree#1077]
**_Question_**

What is the best way to compose your stores in a large well-tested application? multiple stores, or one overarching store.

I'm asking this as `mobx-state-tree` is supposed to be opinionated and there doesn't seem to be an opinionated way to do this, and in my experience so far there are multiple trade-offs with each approach.

This basically comes down to:
```javascript
1. <Provider {...stores}>
```
Vs.
```javascript
2. <Provider {store}>
```

### Option 1
Your store will probably be constructed something like:
```javascript
// createStores.js
const createStores = () => {
    const navigation$ = NavigationStore.create({}, { cookies$ });
    const error$ = ErrorStore.create({}, { navigation$ });
    const cookies$ = CookiesStore.create({}, { error$ });

    return {
        error$,
        cookies$,
        navigation$
    }
}

export default createStores
```
This is great for testing individual stores as each store is created individually and I can pass whatever params I like to the store.

*problem!*
The problem is that in a real world app, this `createStores` function will become much larger and more unwieldy, and as you can see, different stores *depend on other stores*, so this is inherently unscalable, as we need to create everything in a *perfect order* for it to work in the long run.

To illustrate this, if you look above, `navigation$` depends on `cookies$`, so even in this trivial example with only 3 stores, this wouldn't work.

### Option 2
Your store probably looks something like:
```javascript
// App.store.js
const AppStore = types.model('AppStore', {
    error$: ErrorStore,
    navigation$: NavigationStore,
    cookies$: CookiesStore
});

 export default AppStore;
```
In this instance, we have one overarching store, and we would access other parts of the store using helpers `mobx-state-tree` provides such as `getParent` and `getRoot`.

*problem!*
What about testing? In this instance I can definitely import and test individual stores, but as soon as I use `getRoot` or `getParent`, my individual store doesn't have access to the rest of the stores, so I need to mock them out. So is the only solution to import the entire AppStore every time I want to test one small part of it? How can this scale well when your test suite increases in size?

----------------

Given the two examples my preferred option - because we have those helper functions (`getParent`, `getRoot`), and also because all the [examples are constructed as such.](https://github.com/mobxjs/mobx-state-tree/tree/master/packages) - is option 2. 

But I can't help but think, if this is the preferred option, there must be a better way to test large applications rather than either: 
1. import the entire AppStore into every single store test 
or 
2. mocking out library helpers such as `getParent` and `getEnv`

Maybe I'm missing something? I've opted for option 2 so far but would love to know what others think.

**Comment by luisherranz** [comment]
Option 2 definitely. 

We mock `self.root`:
https://github.com/frontity/saturn-theme/blob/dev-stable/src/pwa/stores/__tests__/client.tests.js
It gets a bit boring as you can see, but it works well to test stores in isolation.

**Comment by xaviergonz** [comment]
I use option 2 personally
