### ISSUE TITLE
Views based on types.array(types.reference(Model)), throw when referenced Model element gets destroyed

### ISSUE THREAD

**Issue by akryvda** [mobxjs/mobx-state-tree#1081]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**

https://codesandbox.io/s/v6m8j4lmj5
**Describe the expected behavior**
1. When you call window.App.destroyTask('task4')  **ProjectModel's** view **childTaskIds** throws, 
That enforces to manually dispose of every single reference-based view, or use hooks (or wrap every view in try/catch'es)
2. When you call window.App.detachTask('task4'), then destroy detached model, you still get thrown
**Describe the observed behavior**
My thought, would be the reference to destroy itself, one referee is destroyed.
Could you clarify expected behavior, and whether it's a bug or feature? ;)

**Comment by xaviergonz** [comment]
I think that playground is based on a really old version of MST. Does it also happen on the newest one?

**Comment by xaviergonz** [comment]
Might be related to #1080

**Comment by akryvda** [comment]
Stumbled upon the issue in our code with 2.7.1, that playground was the thing i've found long ago and used for quick repro.
Main idea was in fact, that references are not getting destroyed when destroying referring model.

**Comment by xaviergonz** [comment]
Do you mean 3.7?

**Comment by akryvda** [comment]
Correct, "mobx-state-tree": "^3.7.1",

**Comment by akryvda** [comment]
Added codepen version. We do have crashes for **both** destroy and **detach** cases

**Comment by xaviergonz** [comment]
Well, from what I can see you just expect removed references to be magically removed from arrays that hold them... that's not the case, you'd need to make the destroyTask / detachTask do that before actually destroying/detaching the object.

**Comment by akryvda** [comment]
Hmm, correct me if i'm wrong, but what's the purpose of types.reference then? 
except for saving a bit on memory consumption and processor time to resolveIdentifier every time?
> magically removed from arrays
As i understand, types.reference instance is just another object, which knows how to return referred model. I was rather thinking of destroying referred model should supposedly yield destruction of reference instances.
If i'm wrong with that assumption, what should be the correct way of building types.array(types.reference) architecture, without filtering that array every single time some referred models gets destroyed?

**Comment by k-g-a** [comment]
@akryvda do you need those references as part of the tree? I.e. do you want them to be included in snapshot as values? MST is a normalized tree data structure, references are generally supposed to be used as identifiers and their management is supposed to be decoupled from the source.
For convinience sake you can pass existing nodes during ```create()```, but those still will be converted to identifiers during serialization.

If you need a "mirror" of some array you can use ```view``` i.e.:
```typescript
const Root = types.model({
  sourceArray: types.array(Child)
  someBranch: Branch
});
const Branch = types.model({
   foo: types.string,
   ...
})
.views(self => {
   get arrayLink() {
    return getParentOfType(self, Root).sourceArray
  }
})
```

**Comment by akryvda** [comment]
Thank you, sir, for your comment.
It is my fault for using bad entity names with that synthetic example.
Let's replace Project with User and Task with Photo. And take into account that every Photo might be 'owned' by multiple users.
MST would not allow to initialize 2 exact Photo Models with the same Id as children of 2 different User Models. Thus we'll need to store only reference ids as Photos property value on User model, and store actual Photo models in separate collection somewhere else in the tree.
But we still need full Photo models to be accessible from related UserModel. Thus we need references to Photos being set up on top of existing identifiers.
So far this works fine, until one of the users deletes some shared Photo model.
Then we're getting broken references for rest of Users and application crash if we've some views based on these references.
To fix this crash we need PhotoStore to know of every User model reference to every photo (and imagine Users being not the only entity which has references to Photos). And we need manually find and destroy every such reference before even attempting to destroy a Photo Model.

**Comment by akryvda** [comment]
@xaviergonz your https://github.com/mobxjs/mobx-state-tree/pull/1087 is exactly what's needed!
Thank you sir! Eagerly waiting for that to be released.

**Comment by xaviergonz** [comment]
Closing since safeReference will be on the next release
