### ISSUE TITLE
types.custom: value is not assignable to type

### ISSUE THREAD

**Issue by JonDum** [mobxjs/mobx-state-tree#1085]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/q3wx9j5zjj

Closely follows example [here](https://github.com/mobxjs/mobx-state-tree/blob/c300c798732591e96c006433bd367319ab77eb41/packages/mobx-state-tree/__tests__/core/custom-type.test.ts#L32)
```
import { types } from "mobx-state-tree";
import { DateTime } from "luxon";

const DateTimeType = types.custom({
	name: "DateTime",

	isTargetType(value) {
		return value instanceof DateTime; //DateTime.fromISO(value).isValid
	},
	getValidationMessage(value) {
		if (value instanceof DateTime) return ""; // Ok
		return value + " is not a Luxon DateTime";
	},
	fromSnapshot(value) {
		return DateTime.fromISO(value);
	},
	toSnapshot(value) {
		return value.toISO();
	}
});

const model = types.model({
	date: DateTimeType
});

const instance = model.create({ date: "2018-11-01T07:32:21.073Z" });

```

**Describe the expected behavior**
Creating an instance with an ISO date should deserialize to a DateTime instance and vice versa.

**Describe the observed behavior**
Errors. Either MST fails because it says the ISO string is not valid, or reversing the `isTargetType` to expect a normal String causes `toSnapshot` to get called on the string (whereas it only should be called on the on DateTime instance)

**Comment by k-g-a** [comment]
snapshot (i.e. ```string``` in your case) is passed to ```getValidationMessage()``` so it should be tested like:
```typescript
 getValidationMessage(value: string): string {
        if (/\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d(\.\d+([+-][0-2]\d:[0-5]\d|Z))?/.test(value)) {
          return '';
        }
        return `'${value}' doesn't look like 'YYYY-MM-DDTHH:mm:ss.SSSZ'`;
      }
```

**Comment by JonDum** [comment]
@k-g-a Thanks! That was not clear to me from the [source code](https://github.com/mobxjs/mobx-state-tree/blob/d7499d78a5172b49c9c1788265bcfb2acebc4ba5/packages/mobx-state-tree/src/types/utility-types/custom.ts#L24) that `getValidationMessage` is given the serialized value not the deserialized value:

```js
    // a non empty string is assumed to be a validation error
    getValidationMessage(snapshot: S): string
```
I guess I fixated on the comment and not the param

For anyone from google: I got it working with 
```js
	getValidationMessage(value) {
		if(DateTime.fromISO(value).isValid)
			return ''
        return `'${value}' doesn't look like an ISO Date`;
	},
```
Using DateTime to validate it instead of a regex because ISO's can be pretty complex

**Comment by xaviergonz** [comment]
Feel free to submit a PR to the docs to make it more clear :)
