### ISSUE TITLE
types.safeReference/safeReferenceArray/safeReferenceMap

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx-state-tree#1088]
Given a pattern such as 
```
const Todo = ... with some id

const TodoStore = types.model({
  todos: types.array(Todo),
  selectedTodo: types.maybe(types.reference(Todo))
})
.actions(self => ({
  clearSelectedTodoRef() {
    self.selectedTodo = undefined
  },
  afterCreate() {
    // unselect a Todo when no longer available
    addDisposer(self, reaction(() => isValidReference(() => self.selectedTodo), (valid) => {
      if (!valid) this.clearSelectedTodo()
    });
  }
}))
```

Since that's such a common pattern it makes me wonder if there should be a types.safeReference(Todo) that automatically turns into undefined when the reference it is pointing to is no longer valid

That would solve "single row references"

For multiple rows, since with `types.array(types.safeReference(Todo))` array items would turn into undefined for those we would need something like a `types.safeReferenceArray(Todo)`, that would remove dead refs from the array automatically, and likewise `types.safeReferenceMap(Todo)`

**Comment by fabiosussetto** [comment]
I'd love to see this implemented!

**Comment by xaviergonz** [comment]
It would be like `types.maybe/maybeNull(types.reference(X))`
By the optional function you mean the custom reference bit?

**Comment by Bnaya** [comment]
Well, i personally not using references, but doing:
```ts
const Todo = ... with some id

const TodoStore = types.model({
  todos: types.array(Todo),
  selectedTodoId: types.maybe(types.string)
})
.views((self) => ({
    get selectedTodo() {
        return self.todos.find((td) => {
            td.id === self.selectedTodoId;
        })
    }
}))
.actions(self => ({
    selectToDo(todo: typeof Todo.Type) {
        self.selectedTodoId = todo.id;
    },
  clearSelectedTodo() {
    self.selectedTodoId = undefined
  }
}))
```

Maybe it will be possible to implement similar mechanism? i think its better than having changing state as sideeffect using reaction

**Comment by xaviergonz** [comment]
The problem is the snapshot, you will end up with a snapshot that has a reference to an unexisting node. Also if some other todo appears with the same ID as the previously selected one appears it will become auto selected (which might be something you may or may not want to happen)

**Comment by xaviergonz** [comment]
@fabiosussetto  that actually gave me an idea

```
types.reference(Todo, {
  // get/set if needed for custom ref,

  onInvalidated?(oldRef: IAnyStateTreeNode, setNewRef: (val) => void, parent?: IAnyStateTreeNode) {
    // this method will execute just -before- the referenced node is about to be killed

    // default implementation for types.reference is empty

    // default implementation when using types.safeReference follows
    setNewRef(undefined);

    if (parent) {
      if (parent is an array node) {
        remove oldRef from array
      }
      else if (parent is a map node) {
        remove oldRef from map
      }
    }
  }
});
```

that way `types.safeReference` would be a refrence with a custom implementation of onInvalidated and it would work as expected with `types.array(types.safeReference(Todo))` and `types.map(types.safeReference(Todo))`, even when using unions etc

This also opens the possibility of custom implementations if the default one is not ok for some reason.

**Comment by Bnaya** [comment]
> The problem is the snapshot, you will end up with a snapshot that has a reference to an unexisting node. Also if some other todo with the same ID as the previously selected one appears it will become auto selected (which might be something you may or may not want to happen, depending on the use case)

id should be globally unique. if 2 todos have the same id, they are the same.

I never had any issues, but you may:
Save the id in volatile state, delete it in postProcess snapshop, add any validation etc
