### ISSUE TITLE
Best practices for importing stores

### ISSUE THREAD

**Issue by elie222** [mobxjs/mobx-state-tree#1093]
**_Question_**

* [ x ] I've checked documentation and searched for existing issues
* [ x ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

What is considered best practice for loading stores in MST with TypeScript?

In the examples I see `Provider` with `inject("someStoreName")`, but it feels a bit dirty using inject with a string.

What I've done till now is just import the store where I need it.

I create the store at the end of each models file as needed something like this:

```ts
export const store = EntityStore.create({
  entities: [],
})
```

And then import where needed. Things seem to be working fine. Is there something wrong with this approach? What is considered best practice here?

**Comment by Bnaya** [comment]
it's a philosophical question, and not MST specific.

I personally don't like to pass around instances via the module system.
Some developers don't see any issue with it.
For me, the module system is Only for symbols and not instances.

Some of the reasons i don't like it: 
In js its harder to mock ES modules (jest supports it, with an overhead)
Makes you use singletons.
Makes you design your code like you are using globals.
There is no issues with inject. (But i personally also not using it)
The inject is only helper on top of react context.
you can write your own context based models passing, or even just use plain props

**Comment by xaviergonz** [comment]
Personally I'd either use new react context API or pass it directly as a prop, provider was made in a time when the new react context was not available and the new mobx-react-lite is not even going to provide it at all

**Comment by xaviergonz** [comment]
Now if you don't care much about tests (or want to do module mocks) you might just import it as you have done of course
