### ISSUE TITLE
[Typescript] Proper typings for types.maybeNull(types.array(MyType))

### ISSUE THREAD

**Issue by k-g-a** [mobxjs/mobx-state-tree#1098]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

Assuming I have:
```ts
const outerModel = types.model({
  items: types.maybeNull(types.array(MyInnerType)),
  ...
}).create(...)
```
```ts
interface ISomeListProps {
  propA: boolean;
  propB: string;
  items: ???
}
export class SomeList extends React.Component<ISomeListProps, {}> {...}
```
```ts
export class OuterClass extends React.Component<typeof outerModel.Type, {}> {
  render() {
    // this.props is outerModel
    return  <SomeList propA=false propB='foo' items={this.props.items}>
  }
}
```
**What type should I use for ```items``` in my ```ISomeListProps```?**
TS shows it as ```Type 'Pick<IMSTArray<IModelType<ModelPropertiesDeclarationToProperties<{ ...; ... 5 more ...; ...; }>, { ...; } & ... 18 more ... & { .....'```
I tired:
- ```Array<typeof MyInnerType.Type>```
- ```IMSTArray<typeof MyInnerType>```
- ```IArrayType<typeof MyInnerType>```
- making  optional ```items?: ...```
- marking ```this.props.items!``` as non-null

Removing ```types.maybeNull``` makes it work with  ```IMSTArray<typeof MyInnerType>```

**Comment by k-g-a** [comment]
I managed to find actual error:
```...is missing the following properties from type 'IMyInnerType[]': [Symbol.iterator], [Symbol.unscopables]```

```IMyInnerType``` is basically ```IMyInnerType extends typeof MyInnerType.Type```

**Comment by xaviergonz** [comment]
You could just do
```
const items =types.maybeNull(types.array(MyInnerType))

const outerModel = types.model({
  items
  ...
}).create(...)

interface ISomeListProps {
  propA: boolean;
  propB: string;
  items: Instance <typeof items>
}
```

**Comment by xaviergonz** [comment]
Either way if you are looking for the actual type I think it was ```Instance<IMaybeNullType<IArrayType<typeof MyInnerType >>>``` or something similar IIRC

**Comment by k-g-a** [comment]
Thanks, works like a charm! )
Will keep up with latter solution for now, as extracting ```items``` into separate declaration requires more work.
For future readers, we came up with ambient declaration:
```ts
// prettier-ignore
declare type INullableMSTArray<T> = import('mobx-state-tree').Instance<import('mobx-state-tree').IMaybeNullType<import('mobx-state-tree').IArrayType<typeof T>>>
```
Usage: 
```ts
interface ISomeListProps {
  propA: boolean;
  propB: string;
  items: INullableMSTArray<MyInnerType>
}
```
