### ISSUE TITLE
Handling of observable mst node destroying

### ISSUE THREAD

**Issue by Amareis** [mobxjs/mobx-state-tree#1099]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

I have an simple React component.
```ts
@observer
export default class MembersContainer extends React.Component {
    @observable selected?: typeof User.Type = undefined

    @computed
    get actions() {
        const actions = []
        if (this.selected) {
            actions.push(['person', this.selected.is_my ? this.gotoMe : this.gotoUser])
            if (!this.selected.is_my)
                actions.push(['forum', this.gotoPm])
        }
        return actions
    }
    //...
}
```
`selected` is pointing direct to mst node from `app` tree. All is working fine, unless I removes selected user from tree. Because I did `setLivelynessChecking('error')`, right after user deleting component try to render and boom, entire app are dead now.
There is some workarounds, of course (using ids instead models, for example, or reaction, which handles node destroying (but there can be problems with reactions run order)), but I don't want to boilerplate around all components, where I used direct links to mst nodes.
Does it possible to make some helper decorator, which handles node destroying automatically, by replacing property value to undefined? Also, I have same problem with arrays of mst nodes, in another components.

**Comment by xaviergonz** [comment]
try `if (this.selected && isAlive(this.selected)) {`

**Comment by xaviergonz** [comment]
MST 3.9 just added `types.safeReference` which kind of does this, but it is meant to be used inside models and for references

**Comment by xaviergonz** [comment]
but yeah, I see some use in having some kind of 
```
selected?: User.Type = aliveNode(this, undefined); // uses disposeOnUnmount from mobx-react internally, making a reaction with isAlive
...
this.selected = someNode
```

however that is more tied to react than to MST, which is supposed to be framework agnostic

**Comment by xaviergonz** [comment]
alternatively you could try
```
@computed
get aliveSelected() { return this.selected && isAlive(selected) }
```
and use that rather than selected

**Comment by Amareis** [comment]
>types.safeReference

Yeah! It's what I needed, but for external classes. Something, which handles references to mst and arrays/maps of it.

**Comment by Amareis** [comment]
It's should be like a `observable` in mobx, maybe tiny wrapper around it. Both decorator or boxing function, which specifically handles mst nodes.

**Comment by xaviergonz** [comment]
Something like this?
```ts
const selected = safeObservable(model.x)
selected.get(); selected.set(model2.x)

export function safeObservable(initialValue) {
  let isNode = false

  const obj = {
    get() {
      const value = obs.get();
      if (!isNode) return value;
      return isAlive(value) ? value : undefined;
    },
    set(value) {
      obs.set(value);
      isNode = isStateTreeNode(value)
    }
  };

  obj.set(initialValue);
  return obj;
}

```

**Comment by Amareis** [comment]
Yep! I need only to wrap it into decorator, and add logic for arrays.

**Comment by Amareis** [comment]
Nop, it's need to be separated decorator, which deletes dead entries from array.

**Comment by Amareis** [comment]
Simple decorator, as drop-in replacement for @observable
```ts
import {observable, IObservableValue} from 'mobx'
import {IAnyStateTreeNode, isStateTreeNode, isAlive} from 'mobx-state-tree'

export default function mstref(target: any, key: string) {
    const o: IObservableValue<IAnyStateTreeNode|undefined> = observable.box(undefined)
    let isNode = false
    Object.defineProperty(target, key, {
        get() {
            const value = o.get()
            if (!isNode || !value) return value
            return isAlive(value) ? value : undefined
        },
        set(value) {
            o.set(value)
            isNode = isStateTreeNode(value)
        },
        enumerable: true,
    })
}
```

**Comment by Amareis** [comment]
Does node destroying trriggers reactions?
```ts
    const o: IObservableArray<IAnyStateTreeNode> = observable.array()
    reaction(() => o.filter(isAlive), v => !shallowEqual(v, o) && o.replace(v))
```
That reaction is not fired after arrays children destroying.

**Comment by xaviergonz** [comment]
Maybe not, that's why there is a before destroy action, but it could be made so by internally making the node state observable I guess

**Comment by Amareis** [comment]
Uh-oh. Without that sort of reactions i don't know how to make smart mst references arrays. Maybe, it can be hacked over `array.observe` and `addDisposer`?

**Comment by xaviergonz** [comment]
Just created a PR #1100 to make isAlive reactive

**Comment by Amareis** [comment]
Ok, after some work I've got that: 
```ts
import {observable, IObservableValue, IObservableArray} from 'mobx'
import {IAnyStateTreeNode, isStateTreeNode, isAlive} from 'mobx-state-tree'

function mstRef(target: any, key: string) {
    const o: IObservableValue<IAnyStateTreeNode|undefined> = observable.box(undefined)
    let isNode = false
    Object.defineProperty(target, key, {
        get() {
            const value = o.get()
            if (!isNode || !value) return value
            return isAlive(value) ? value : undefined
        },
        set(value) {
            isNode = isStateTreeNode(value)
            o.set(value)
        },
        enumerable: true,
    })
}

mstRef.array = function mstRefArray(target: any, key: string) {
    const o: IObservableArray<IAnyStateTreeNode> = observable.array()
    const mem = new Map<IAnyStateTreeNode, () => void>()

    o.observe(() => {
        const seen = new Set<IAnyStateTreeNode>()
        for (let item of o) {
            if (!isStateTreeNode(item))
                continue
            seen.add(item)
            if (mem.has(item))
                continue
            const f = () => o.remove(item)
            mem.set(item, f)
            const node = item.$treenode
            if (!node.hasDisposer(f))
                node.addDisposer(f)
        }
        for (let [item, f] of mem.entries()) {
            if (seen.has(item))
                continue
            mem.delete(item)
            const node = item.$treenode
            if (node.hasDisposer(f))
                node.removeDisposer(f)
        }

    })
    Object.defineProperty(target, key, {
        get: () => o,
        set(value) {
            o.replace(value)
        },
        enumerable: true,
    })
}

export default mstRef
```
But it not much elegant, I never dispose that `observe` for arrays.

**Comment by xaviergonz** [comment]
Yeah you'd need to use disposeOnUnmount over the target

**Comment by Amareis** [comment]
Can we at least add some simple warning to mobx `observable` if mst node are observed? It really can be hard to find such error in some use cases.

**Comment by Amareis** [comment]
Oh, that typescript decorators is really confusing. Because property decorator is called only once, with class *prototype*, my code snippet are wrong, because if there is more than one class instances, they all will shares only one, last observable value.

**Comment by xaviergonz** [comment]
After reactive is Alive is released (already merged) it could be done as an observable + computed

**Comment by elie222** [comment]
This is crazy annoying. I've added `safeReference` to avoid my app from crashing when I call destroy on an item, but then I have to update the rest of my app to handle an array that could possibly be holding a null item in it.

There's no simple way to destroy a reference item and have the rest of the app just work nicely?

**Comment by xaviergonz** [comment]
In theory an array of safe refs should auto remove the deleted ref from the array when the target node dies. Same with map

**Comment by coolsoftwaretyler** [comment]
Hey folks, it's been about five years since the last activity in this MobX-State-Tree issue, and it looks like the original issue and follow up questions were resolved.

I'm gonna go ahead and close this out. Thanks, all!
