### ISSUE TITLE
[Typescript] Proper typings for runtime composition?

### ISSUE THREAD

**Issue by k-g-a** [mobxjs/mobx-state-tree#1104]
**_Question_**

* [x] I've checked documentation and searched for existing issues

For mst@3.9.0, how shold I type ```.create()``` arguments for runtime composition in the following case:

_composer.ts:_
```ts
const Base = types.model('Base', {
  isInitialized: types.boolean,
  myItems: types.map(types.frozen())
});

function compose<T extends IAnyType>(itemType: T) {
  const Items = types.model({
    myItems: types.map(itemType)
  });
  return types
    .compose(
      'Composed',
      Base,
      Items
    )
    // here's an error:
    .create({
      isInitialized: false,
      myItems: {}
    });
}
```

_other.ts:_
```ts
const ConcreteItem = types.model('ConcreteItem', {
  name: types.string
});

const myStore = compose(ConcreteItem);
// myStore.myItems.add({name: 'foo'});
```

```Base``` class has some actions/hooks and ```compose``` does more stuff, but I stripped down the above example to relevant part.

There is an error at composer.ts's ```create()```
```
Error:(19, 13) TS2345: Argument of type '[{ isInitialized: boolean; myItems: {}; }]' is not assignable to parameter of type 'CreateParams<ExtractCFromProps<RequiredPropsObject<ModelPropertiesDeclarationToProperties<{ isInitialized: ISimpleType<boolean>; myItems: IMapType<IType<any, any, any>>; }> & ModelPropertiesDeclarationToProperties<{ myItems: IMapType<T>; }>> & OptionalPropsObject<...>>>'.
```

I've tried:
1) removing ```myItems: types.map(types.frozen())``` fallback from ```Base```. I still get:
```
Error:(18, 13) TS2345: Argument of type '[{ isInitialized: boolean; myItems: {}; }]' is not assignable to parameter of type 'CreateParams<ExtractCFromProps<RequiredPropsObject<ModelPropertiesDeclarationToProperties<{ isInitialized: ISimpleType<boolean>; }> & ModelPropertiesDeclarationToProperties<{ myItems: IMapType<T>; }>> & OptionalPropsObject<...>>>'.
```

2) doing ```as any``` at ```create```: 
```
Error:(18, 13) TS2345: Argument of type '[any]' is not assignable to parameter of type 'CreateParams<ExtractCFromProps<RequiredPropsObject<ModelPropertiesDeclarationToProperties<{ isInitialized: ISimpleType<boolean>; }> & ModelPropertiesDeclarationToProperties<{ myItems: IMapType<T>; }>> & OptionalPropsObject<...>>>'.
```

3) ```cast```'ing whole snapshot or ```myItems``` part: no luck as it cannot infer and I can't find proper type to pass ```cast<HERE>(...)```

**Comment by xaviergonz** [comment]
which version of TS are you using?
I just pasted that code (composer.ts and other.ts) into type-system.test.ts and tried it with both TS3.0.3 and 3.1.2 and it compiled ok

**Comment by xaviergonz** [comment]
![annotation 2018-12-10 184640](https://user-images.githubusercontent.com/6306796/49750799-1c0d2c80-fcac-11e8-943b-ea2c90464818.jpg)

**Comment by xaviergonz** [comment]
just wondering though, why do you have defined myItems both in the Base and in the items class with different types?

**Comment by xaviergonz** [comment]
Or maybe some strict option is not set in tsconfig.json, just wild guessing here

**Comment by k-g-a** [comment]
Ok, thanks to your suggestions I've figured out that the reason was ```strictNullChecks: false``` in tsconfig, but I can not explain connection between those two in my head :)
