### ISSUE TITLE
Does calling set on a types.map cause observer re-render? Doesn't appear to be doing so for me

### ISSUE THREAD

**Issue by ryancole** [mobxjs/mobx-state-tree#1106]
Does calling `set` on a `types.map` cause `observer` to re-render? It doesn't seem to be doing so, for me. I have the below `model` ...

```
export default types
  .model("Store", {
    test: types.optional(types.integer, 0),
    natives: types.map(Native),
    uploads: types.map(Upload)
  })
  .actions(self => ({
    fetchAllUploads() {
      const id = Math.floor(Math.random() * Math.floor(100));
      self.uploads.set(id, {
        id,
        path: "",
        size: 100,
        dateCreated: ""
      });
    },
    setNumber(value) {
      self.test = value;
    }
  }));
```

It's just a useless bit of action logic, but I'm trying to debug. The `setNumber` action causes `observer` to re-render as expected. The `fetchAllUploads` does not cause it to re-render, though.

**Comment by xaviergonz** [comment]
That depends on how the map is being used in the component

**Comment by ryancole** [comment]
@xaviergonz I'm just reading from it. Here is the component ...

```js
class Uploads extends React.Component {
  componentDidMount() {
    setInterval(() => {
      //this.props.store.setNumber(Math.floor(Math.random() * Math.floor(100)));
      this.props.store.fetchAllUploads();
    }, 1000);
  }

  render() {
    const { uploads, test } = this.props.store;

    console.log({ test });

    return (
      <Template>
        <h1>Uploads</h1>
        <hr />
        <div className="row mt-5">
          <div className="col-12">
            <UploadTable uploads={uploads} />
          </div>
        </div>
      </Template>
    );
  }
}

export default observer(Uploads);
```

**Comment by xaviergonz** [comment]
What does UploadTable do?

**Comment by ryancole** [comment]
@xaviergonz it's just supposed to render a list of items ...

```
export default function UploadTable({ uploads }) {
  const rows = Array.from(uploads.values()).map(u => (
    <UploadTableRow upload={u} key={u.id} />
  ));

  return (
    <table className="table">
      <thead>
        <tr>
          <th>Path</th>
          <th>Size</th>
          <th>Date Created</th>
        </tr>
      </thead>
      <tbody>{rows}</tbody>
    </table>
  );
}

export default function UploadTableRow({ upload }) {
  return (
    <tr>
      <td>
        <Link to={`/upload/${upload.id}`}>{upload.path}</Link>
      </td>
      <td>{upload.size}</td>
      <td>{upload.dateCreated}</td>
    </tr>
  );
}

```

**Comment by xaviergonz** [comment]
Try using observer to wrap both function components

**Comment by xaviergonz** [comment]
Off topic, I think the Array from is not needed 😉

**Comment by ryancole** [comment]
@xaviergonz Oh, OK that seems to make it update. I figured that parent component with the observer would be enough to observer changes, but I guess I can understand it if I think about it like the map itself isn't changing, only certain items within it and so perhaps setting new entries was not enough to observe the map receiving new items.

How can you render a list of items without making it array first?

**Comment by xaviergonz** [comment]
Yep exactly

values() returns an iterator and map transforms that iterator into an array

**Comment by xaviergonz** [comment]
The key to understand mobx is that it detects changes when the thing that is mutated is actually read. Like you said the map object itself didn't change, what is changing are the items inside the map, which are read in the inner components. A render function inside an observer component is internally wrapped in a mobx autorun

**Comment by ryancole** [comment]
OK, I think it's starting to click now. I really like the structure that MST creates.

Thank you for you help!

**Comment by xaviergonz** [comment]
Ps If you ever have to work with a third party component your best shot is passing the snapshot as property, since that will actually create a whole new object any time anything inside it changes

**Comment by ryancole** [comment]
I have the `Array.from` because it doesn't look like you can call `map` on the iterator? It says it's not a function.
