### ISSUE TITLE
expose Type class or provide a way to override reconcile method

### ISSUE THREAD

**Issue by jayarjo** [mobxjs/mobx-state-tree#1110]
**_Feature request_**

**Is your feature request related to a problem? Please describe.**

Suppose you have a complex interactive object and you would like to create a custom type for it (adapt it for usage in MST that is). `types.custom` is great for primitive types, like `Decimal`, but fails to represent much more complex objects. 

**Describe the solution you'd like**

Solution is simple - provide a way to override default generic `reconcile` method of the `Type` class.

There are two possible ways of implementing this. The simplest would be to expose `Type` class, which is currently internal only, so that we could extend it with our own types (opens a way for third party extensions as well). Or for more control over what can be extended - add an option for custom reconcile method.

**Describe alternatives you've considered**

I tried `types.custom` but it unnecessarily complicates reconciliation procedure.

**Additional context**

In the case that I have here for example each object despite of being huge and containing thousands of props is uniquely identified by sequence number. So if sequence numbers do not match - objects are different, that simple. No need to take snapshots, stringify them and compare. I could probably make `toSnapshot/fromSnapshot` to operate on that sequence number only, but I would like to retain capability to export the object to the snapshot and restore it from snapshot as well.

**Are you willing to (attempt) a PR?**
* [x] Yes
* [ ] No

**Comment by k-g-a** [comment]
Good day!
Reconcilation algorithm never compares objects by value. From the [docs](https://github.com/mobxjs/mobx-state-tree#how-does-reconciliation-work):
- When applying snapshots, MST will always try to reuse existing object instances for snapshots with the same identifier (see types.identifier).
- If no identifier is specified, but the type of the snapshot is correct, MST will reconcile objects as well if they are stored in a specific model property or under the same map key.
- In arrays, items without an identifier are never reconciled.

From what you wrote, you could specify 
```ts
const MyHugeObject = types.model({
  ...
  sequenceNumber: types.identifier //or types.identifierNumber
  ...
})
```
If by "sequence number" you meant array index, you could:
```ts
const MyRootStore = types.model({
   items: types.array(MyHugeObject),
   ...
})
.preProcessSnapshot(snapshot => snapshot.map((item, index) => item.sequenceNumber = index))
```

If that's not the case, please provide more details or code example.

**Comment by jayarjo** [comment]
So you say that something like this should work nicely (I will adapt to a generic case)?

```ts
const MyHugeObjectWrapper = types.model({
  ...
  sequenceNumber: types.identifier,
  instance: types.custom<snapshotType, MyHugeObject>(MyHugeObjectPrimitive)
  ...
})
```

And then instantiate it like this?

```ts
MyHugeObjectWrapper .create({
   sequenceNumber: myHugeObjectInstance.sequenceNumber,
   instance: myHugeObjectInstance
})
```

**Comment by xaviergonz** [comment]
> Where MyHugeObject is generic class, instances of which can mutate freely, but each state of an instance is uniquely identified by sequenceNumber property.

How do you serialize this instance? (transform it into an snapshot)

**Comment by k-g-a** [comment]
Unfortunaletty I could not catch the idea.
Could you please provide simplified example of your ```HugeObject``` and the MST tree you want to squeeze it into. Could ```HugeObject``` be typed in any way or is it shape way too dynamic for it?
And what outcome do you expect? Do you want MST to emit snapshots on every change of ```HugeObject```?
