### ISSUE TITLE
Nested nodes with identifiers are not detached and not removed from the identifiers cache

### ISSUE THREAD

**Issue by DenVifer** [mobxjs/mobx-state-tree#1112]
Works good:

```
const mock1 = [{ id: '1', name: 'Kate' }, { id: '2', name: 'John' }]
const mock2 = [{ id: '3', name: 'Andrew' }, { id: '2', name: 'John' }]

const Entity = types.model({
  id: types.identifier,
  name: types.string
})

const Store = types.model({
  list: types.optional(types.array(Entity), []),
  selectedId: 2
})
.views(self => ({
  get selectedEntity() {
    return resolveIdentifier(Entity, self, self.selectedId)
  }
}))

const store = Store.create()
unprotect(store);

(async function () {
    store.list.replace(mock1)
    await delay(500)
    store.list.replace(mock2)
  })()

// Render selectedEntity
```

Throws an error:

```
const mock1 = [{ id: '1', name: 'Kate' }, { id: '2', name: 'John' }]
const mock2 = [{ id: '3', name: 'Andrew' }, { id: '2', name: 'John' }]

const mock1_2 = mock1.map((i, index) => ({ text: `Text${index}`, entity: i }))
const mock2_2 = mock1.map((i, index) => ({ text: `Text${index}`, entity: i }))

const Entity = types.model({
  id: types.identifier,
  name: types.string
})

const Wrapper = types.model({
  text: types.string,
  entity: Entity,
})

const Store = types.model({
  list: types.optional(types.array(Wrapper), []),
  selectedId: 2
})
.views(self => ({
  get selectedEntity() {
    return resolveIdentifier(Entity, self, self.selectedId)
  }
}))

const store = Store.create()
unprotect(store);

(async function () {
    store.list.replace(mock1_2)
    await delay(500)
    store.list.replace(mock2_2)
  })()

// Render selectedEntity
```

**[mobx-state-tree] Cannot resolve a reference to type 'AnonymousModel' with id: '2' unambigously, there are multiple candidates: /list/1/entity, /list/1/entity**

I tried to call the "detach" method for each existing "Wrapper" entity manually before replacing of the array items, and it works, but i think it's not good idea, because it's difficult to control the all array modifications. For example, someone can call the "applySnapshot" method on any parent node and this fix wouldn't work.

**Comment by xaviergonz** [comment]
codesandbox:
https://codesandbox.io/s/oq3v452ln5

cc @k-g-a

**Comment by k-g-a** [comment]
Provided code belongs to old version of MST (prior 3.8.1). New code for node's death does not use neither ```walk```, nor ```storedValue```, but the bug still exists in latest version of MST at codesandbox.
Unfortunatelly, I couldn't narrow down the issue today, but I'll keep looking within few days.

**Comment by DenVifer** [comment]
MST 3.9.0

```
ObjectNode$$1.prototype.die = function () {
        if (this.state === NodeLifeCycle$$1.DETACHING)
            return;
        if (isStateTreeNode$$1(this.storedValue)) {
            this.aboutToDie();
            this.finalizeDeath();
        }
    };
```

storedValue is still used.

I have replaced "storedValue" with "value" and it works.

**Comment by xaviergonz** [comment]
That would create all unacessed nodes before death. Just created a PR that does the same without creating the child nodes.

**Comment by xaviergonz** [comment]
@DenVifer thanks for the pointers btw :)
