### ISSUE TITLE
safeReference doesn't work when multiple nodes reference the a single reference that gets deleted

### ISSUE THREAD

**Issue by lonelydatum** [mobxjs/mobx-state-tree#1115]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [ ] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/6zno7n9mjz

**Describe the expected behavior**
A nodeA is type.safeReference(nodeB) . When I delete NodeB everything is ok.  

**Describe the observed behavior**
The problem is when there are multiple nodes referencing nodeB. 

The initial conversation started on Spectrum with @xaviergonz

**Comment by xaviergonz** [comment]
Apparently safeReference is not working properly when the target node is deleted and never being accessed before
