### ISSUE TITLE
Build models dynamically?

### ISSUE THREAD

**Issue by mrjjwright** [mobxjs/mobx-state-tree#112]
I am looking to use this wonderful lib as the base of a tool I want to build that let's user build mobx driven models dynamically via a UI.  The user might start building an Employee model, then a Company model and link them together so that an employee has a reference to a company.  Obviously in code, I could build this sort of model all at once using a model factory but what if I want to let the user do it incrementally:  adding and removing a single field at a time, adding references to other models, etc.   I am assuming that I would have to build up the baseModel structure separately outside the MST API and then provide it all at once via the model factory?

**Comment by mweststrate** [comment]
Yep, just save the model configuration, clone and modify the configuration and create a new factory. The cool thing is that it is trivial to migrate the model instances: `newModel = newFactory.create(getSnapshot(oldModel))`. Assuming of course a snapshot of the old model satisfies a new one

**Comment by mrjjwright** [comment]
Oh duh, that makes sense, thanks!
