### ISSUE TITLE
Typescript bug: `setLivelynessChecking`

### ISSUE THREAD

**Issue by Akaprog** [mobxjs/mobx-state-tree#1120]
**_Bug report_**

* [X] I've checked documentation and searched for existing issues
* [X] I've made sure my project is based on the latest MST version

**Sandbox link or minimal reproduction code**
Not sure, just using Typescript might be enough to reproduce

**Describe the expected behavior**
Correct build

**Describe the observed behavior**

```
/usr/src/client/node_modules/mobx-state-tree/dist/index.d.ts
(29,526): Module '"./internal"' has no exported member 'setLivelynessChecking'.

```

**Comment by Akaprog** [comment]
Proposed fix - remove deprecated 'setLivelynessChecking' export from index.d.ts - but idea need checking from someone who understands MST better than me.

**Comment by xaviergonz** [comment]
I just created a sandbox to try it and it seems to work:
https://stackblitz.com/edit/typescript-ohinbx

What code are you using to import the function?
