### ISSUE TITLE
Is it possible to assign by identifier?

### ISSUE THREAD

**Issue by elie222** [mobxjs/mobx-state-tree#1123]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

The code below doesn't work. Is it possible to do something similar that does work? Or should I find the item I need in the store and then assign that? (The item in question belongs to another store btw. Not sure if this is good practice).

```ts
import { types } from 'mobx-state-tree'
import { Item } from 'src/features/items/ItemStore'

export const NotebookStore = types
  .model('NotebookStore', {
    selectedInvestigation: types.reference(Item),
  })
  .actions(self => ({
    selectInvestigation(investigationId?: number) {
      self.selectedInvestigation = investigationId
    },
  }))
```

**Comment by k-g-a** [comment]
Hi!
You should have ```Item``` somewhere in your tree, i.e.
```typescript
.model('NotebookStore', {
    selectedInvestigation: types.reference(Item),
    items: types.array(Item)
  })
```
or use custom reference to resolve it from another tree ([docs](https://github.com/mobxjs/mobx-state-tree#customizable-references)).

**Comment by elie222** [comment]
That didn't answer the question though. How would i set it in action even
if it was in the same tree? And why must it be in the same tree?

**Comment by elie222** [comment]
Tried putting it in the same tree as part of a subtree and didn't help either.

**Comment by k-g-a** [comment]
Assuming you have:
```ts
const Item = types.mode('Notebook', {
  id: types.identifier,
  model: types.string,
  manufacturer: types.string,
})
const NotebookStore = types.model('NotebookStore', {
    selectedItem: types.reference(Item),
    items: types.array(Item)
  })
  .actions(self => ({
    selectItem(itemId: string) {
      self.selectedItem = itemId
    },
  }))
```
You need to:
```ts
const store = NotebookStore.create({
  items: [
    {id: '1', model: 'MacBook Pro', manufacturer: 'Apple'},
    {id: '2', model: 'ZenBook', manufacturer: 'Asus'}
  ],
  selectedItem: '1'
})
```
Here you put real items at ```items``` and _reference_ (by id) at ```selectedItem```, so:
```ts
console.log(store.selectedItem) // yields {id: '1', model: 'MacBook Pro', manufacturer: 'Apple'}
// same as store.items[0]
store.selectItem('2');
console.log(store.selectedItem) // yields    {id: '2', model: 'ZenBook', manufacturer: 'Asus'}
// same as store.items[1]
```

If that's not what you're looking for, then I couldn't catch the idea behind the question.

**Comment by k-g-a** [comment]
@xaviergonz , could you please advice on the TS error? 
I assume one needs to use ```castToReferenceSnapshot``` to cover such scenario?

**Comment by elie222** [comment]
It may be the issue is to do with using different stores as the comment you linked to.

**Comment by benkuly** [comment]
> 
> 
> Assuming you have:
> 
> ```ts
> const Item = types.mode('Notebook', {
>   id: types.identifier,
>   model: types.string,
>   manufacturer: types.string,
> })
> const NotebookStore = types.model('NotebookStore', {
>     selectedItem: types.reference(Item),
>     items: types.array(Item)
>   })
>   .actions(self => ({
>     selectItem(itemId: string) {
>       self.selectedItem = itemId
>     },
>   }))
> ```
> 
> You need to:
> 
> ```ts
> const store = NotebookStore.create({
>   items: [
>     {id: '1', model: 'MacBook Pro', manufacturer: 'Apple'},
>     {id: '2', model: 'ZenBook', manufacturer: 'Asus'}
>   ],
>   selectedItem: '1'
> })
> ```
> 
> Here you put real items at `items` and _reference_ (by id) at `selectedItem`, so:
> 
> ```ts
> console.log(store.selectedItem) // yields {id: '1', model: 'MacBook Pro', manufacturer: 'Apple'}
> // same as store.items[0]
> store.selectItem('2');
> console.log(store.selectedItem) // yields    {id: '2', model: 'ZenBook', manufacturer: 'Asus'}
> // same as store.items[1]
> ```
> 
> If that's not what you're looking for, then I couldn't catch the idea behind the question.
> BTW, you do not "assign" by identifier, but rather "change pointer".

I have the same problem: I can't assign a string to a reference. In the example above: I get a ts-error in the selectItem action.

**Comment by benkuly** [comment]
@xaviergonz can you reopen that please?

**Comment by xaviergonz** [comment]
> In the example above: I get a ts-error in the selectItem action.
Yeah, you need to do 
```self.selectedItem = itemId as any````
when itemId is a string currently sadly

**Comment by xaviergonz** [comment]
See RFC https://github.com/mobxjs/mobx-state-tree/issues/1282

**Comment by arusak** [comment]
In case someone is running into this issue, I suggest you to use this function that allows assigning instances to reference fields with proper typing and without hardcasting to `any`.

I had no luck avoiding the type argument for the function, so I appreciate if someone gives me a piece of code that infers it from the argument. Just in case.

```typescript
/**
 * Casts the given model instance to a reference of the same model.
 * This is useful when you need to pass a reference to a model instance to a reference field of another model.
 * The model must have an `id` attribute of type `types.reference`.
 *
 * Instances or their ids cannot be passed directly to reference fields due to MST typing limitations.
 * @see https://github.com/mobxjs/mobx-state-tree/issues/1123#issuecomment-491369379
 *
 * @example
 * const Form = types.model('Form', {id: types.identifier, name: types.string});
 * const Editor = types
 *   .model('Editor', {form: types.maybe(types.reference(Form))})
 *   .actions((self) => ({
 *     setForm(form: Instance<typeof Form>) {
 *       self.form = castInstanceReference<typeof Form>(form);
 *     },
 *   }));
 */
export const castInstanceReference = <T extends IModelType<{id: ISimpleType<string>}, unknown>>(
  model: Instance<T>,
): Instance<T> => model.id as unknown as Instance<T>;
```
