### ISSUE TITLE
How to describe [propName: string]: string like typescript with types?

### ISSUE THREAD

**Issue by zmayor** [mobxjs/mobx-state-tree#1124]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

I fetch some data array from server, but the keys of the object are uncertain.

In typescript, it's shape is:
```
interface IItem {
   [propName: string]: string;
}
```

How to describe this with types ?

**Comment by zmayor** [comment]
I tried to describe it like this? Is this the right way?

```
    data: types.array(types.frozen<{ [propName: string]: string }>()
```

**Comment by zmayor** [comment]
I cannot use map directly.

![map-error](https://user-images.githubusercontent.com/18019463/50745124-75448d80-1263-11e9-9ea5-3daf42f9a03d.png)



How to transform map into plain object? I use `getSnapshot`. Is that right?

**Comment by xaviergonz** [comment]
yep, that's the right approach

**Comment by xaviergonz** [comment]
`types.map(types.string)` is equivalent to your typescript interface btw

**Comment by zmayor** [comment]
How about this interface ?
```
interface IItem {
  id: string;
  [propName: string]: string;
}
```

**Comment by zmayor** [comment]
I tried
```
types.compose(
  types.model({ id: types.string }),
  types.map(types.string),
)
```
But this is not a right solution exactly.
Need help...
