### ISSUE TITLE
2+ depth decedents optional values are not kept/applied

### ISSUE THREAD

**Issue by jamespolanco** [mobxjs/mobx-state-tree#1134]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/r5wknjv4yq

**Describe the expected behavior**
When using a 2+ depth set of models that have optional defaults (arrays & maps), I would expect that all the optional values are respected going down the entire tree. This expectation has caused multiple issues, especially around app level stores that have n-depth trees. The challenge is that we don't always know the data structure at boot time and trying to use that to configure all the way down has lead to some harder configurations.

**Describe the observed behavior**
The root model and it's direct descdents are created using the optional & maybe types, but the children's descendents optional values are not set/used.

**Comment by xaviergonz** [comment]
change
```
  parents: types.array(parent, [{}]),
```
to
```
  parents: types.optional(types.array(parent), [{}]),
```
types.array only supports a single argument, the inner type

**Comment by xaviergonz** [comment]
Fixed sandbox
https://codesandbox.io/s/m3v67onjjj

**Comment by jamespolanco** [comment]
@xaviergonz Thanks for pointing that out. That was an error in my example with the 2nd argument in the `types.array` but our codebase has it correctly. It was the translation to a simple example that was lost. But, your fix actually pointed to my misunderstanding with the updated `types.array(x)` defaulting to `[]`. 

I was under the impression that it would cascade down the same way, e.g. `types.optional(types.array(x), [{}]) -== types.array(x)`, but this is not the case. Using my sandbox if you modify line 17 to just `types.array(parent)` it cuts off at that point. That is what threw me off.

Is this the expected behavior? That a `[]` passed to a child model is different the `[{}]` when it comes to creation?

**Comment by xaviergonz** [comment]
Yeah, one is an empty array when no array is provided, the other is an array with an empty element when no array is provided

**Comment by xaviergonz** [comment]
Optional basically means

if this field is undefined then set it to this default

**Comment by jamespolanco** [comment]
Great, thanks for the clarification! I'll close the issue.
