### ISSUE TITLE
How to check if a model property is an array

### ISSUE THREAD

**Issue by fbeaulieu** [mobxjs/mobx-state-tree#1137]
Hi, is there any way with getType(myModelInstance) or any other utility, to know if a specific
property is of type 'types.array' by using the getType(...) information flag value ?

I can always check the property name (obtained with getMembers(...).properties) and check that
it ends with '[]' but for sure I would not want to go there...

thanx !
fabien.

**Comment by xaviergonz** [comment]
If you have access to the array type then you can use https://github.com/mobxjs/mobx-state-tree/blob/master/docs/API/README.md#isarraytype

If not then you'd need something like what is propsed on https://github.com/mobxjs/mobx-state-tree/issues/1114

**Comment by fbeaulieu** [comment]
Winderfull, isArrayType will do the trick,, thanx !

**Comment by xaviergonz** [comment]
No problem!
