### ISSUE TITLE
[TypeScript] types.maybe(types.array(types.string)) + not null check  = `has no index signature` error

### ISSUE THREAD

**Issue by Bnaya** [mobxjs/mobx-state-tree#1138]
**Resolved**

When compilerOptions.keyofStringsOnly is on,
narrow down `types.maybe(types.array(types.string))` to `types.array(types.string)` not working properly.

**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version

**Sandbox link or minimal reproduction code** (sandbox don't have strict on :(
```ts
const MyModel = types
  .model("MyModel", {
    maybeArray: types.maybe(types.array(types.string)),
    notMaybeArray: types.array(types.string),
  })

// same with
// type IMyModel = typeof MyModel.Type;

type IMyModel = Instance<typeof MyModel>;

function foo(p: IMyModel): string {
  if (p.maybeArray) {
    // ...  has no index signature
    return p.maybeArray[0];
  }

  // works
  return p.notMaybeArray[0];
}
```

**Comment by Bnaya** [comment]
Thanks @xaviergonz !

**Comment by xaviergonz** [comment]
You are welcome, though you basically solved it yourself :)
