### ISSUE TITLE
How to create the main store correctly?

### ISSUE THREAD

**Issue by pustovalov** [mobxjs/mobx-state-tree#1139]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

I want to create rootStore which contains others store. The problem is that the children contain properties like:

`id: types.identifier(types.string),`

And when I create the rootStore, I get an error from the child:

> [mobx-state-tree] Error while converting `{}` to `SomeModelStore`: at path "/id" value `undefined` is not assignable to type: `identifier(string)` (Value is not a string), expected an instance of `identifier(string)` or a snapshot like `identifier(string)` instead.

I tried to use `types.late` but it did not help.

The solution I found is to wrap all properties into `types.maybe`

Examples:

error:
https://codesandbox.io/s/yvnznxyvyj?module=%2Fmodels%2FSomeModelStore.js

workaround:
https://codesandbox.io/s/0mv558yq50?module=%2Fmodels%2FSomeModelStore.js

**Comment by Rick83600** [comment]
you can assign a value by default

types.optional(types.identifier, () => lodash.uniqueId())

Or something like this

**Comment by pustovalov** [comment]
I don’t need fake value for that model. I want to create a root store with children and have access to children's methods. Wrap children properties in `maybe` looks like a hack to me.

**Comment by luisherranz** [comment]
You can also use `maybe` to indicate that a model may not be initialized:
```js
export const FirstStore = types
  .model("FirstStore", {
    item: types.maybe(SomeModelStore)
  })
```
https://codesandbox.io/s/2wkop2mp5p

**Comment by pustovalov** [comment]
Thx
