### ISSUE TITLE
How to use different subset models for one type

### ISSUE THREAD

**Issue by romantorv** [mobxjs/mobx-state-tree#1140]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

I want to build a scalable store where the "products" will included different type from a based "GenericStore". And I am stuck at the declaration for the types.

I had made a code sample from this box: https://codesandbox.io/s/oqv9lrqjx9

The  main store content (main.js):
```javascript
import { types } from "mobx-state-tree";
import * as ComposeStores from "./stores"; //3 stores: GenericStore, ComposeA, ComposeB

const MainStore = types
  .model({
    productId: "",
    products: types.array(
      types.maybe( // I have no glue about this type?
        ComposeStores.ComposeA,
        ComposeStores.ComposeB,
        ComposeStores.GenericStore
      ),
      []
    )
  })
  .actions(self => ({
    addProduct(productStore) {
      self.products.push(productStore);
    },
    getProductByType(typeName) {
      const foundProduct = self.products.find(
        product => product.typeName === typeName
      );

      if (foundProduct) {
        return foundProduct;
      }

      const newProduct = ComposeStores[typeName].create({
        id: self.products.length
      });
      self.products.push(newProduct);
      return self.products[self.products.length - 1];
    }
  }));

export { MainStore };
```
Please share with me your suggestion.
Thanks & Best regards,

**Comment by mattruby** [comment]
Try union. There's a great egghead video on this very topic.

**Comment by romantorv** [comment]
> Try union. There's a great egghead video on this very topic.

Thanks for your reply. I don't know that there is a "union" type for this case.
