### ISSUE TITLE
Question: MST Map get/set/delete key type

### ISSUE THREAD

**Issue by elie222** [mobxjs/mobx-state-tree#1141]
If a map has items with `identifierNumber` as the type, should the keys of the map still have a TypeScript type of `string`?

For example this line:
https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mobx-state-tree/src/types/complex-types/map.ts#L64

Shouldn't the type be `string | number`?

**Comment by xaviergonz** [comment]
The keys of a map are always strings and not related to the identifier. You can even have a map of objects that don't have an identifier at all. Identifiers sole purpose is for reference handling
