### ISSUE TITLE
Better assertAlive error (show name of invoked action or accessed field)

### ISSUE THREAD

**Issue by Amareis** [mobxjs/mobx-state-tree#1142]
**_Feature request_**

**Is your feature request related to a problem? Please describe.**
When actions are invoked at destoyed node, there is no action name in error description, which can be helpful for debug. Currently I should use breakpoint on error throwing inside mst code to see stacktrace and look at action name.

**Describe the solution you'd like**
Show action name in assertAlive error if possible, or, in general, name of accessed field.

**Are you willing to (attempt) a PR?**
* [ ] Yes
* [ ] No

**Comment by xaviergonz** [comment]
I think if we console log an error then it should show the full stack trace even on warning mode (like it does in error mode), would that be good enough?

**Comment by xaviergonz** [comment]
PR merged, an stacktrace will show in the console in warn mode

**Comment by Amareis** [comment]
I'm used error mode, but even with it stacktrace sometimes is not really informative.

**Comment by xaviergonz** [comment]
Ah, feel free to reopen the issue then if you think the new addition is not enough

**Comment by Amareis** [comment]
![image](https://user-images.githubusercontent.com/4806617/51601520-6b3eb200-1f26-11e9-8982-191f83e00b74.png)
![image](https://user-images.githubusercontent.com/4806617/51601642-c1abf080-1f26-11e9-9df2-88f825cbaa08.png)

Simple example, I just cannot see full stacktrace at sentry and even actions, which i used as breadcrumbs, isn't very helpful. But if i'll see accessed property name, it be way more easier to debug this situation.

**Comment by xaviergonz** [comment]
Did you check in the actual browser console? It should show an arrow near the error line that allows you to see the full stack trace once expanded (at least in chrome)

**Comment by Amareis** [comment]
In browser stacktrace is available, of course. But there is situations, when in stacktrace there is no any my source files - for example, if you add some arrow function callback, which is reading some field from mst, stacktrace just don't showing any meaningful strings in stacktrace, because it contains only call string of this callback, but not define's string.

**Comment by xaviergonz** [comment]
I thought sentry could be configured to use source maps and browse stack traces.
Either way reopening.

**Comment by Amareis** [comment]
In our sentry sourcemaps are enabled, of course. But, as I said, even stacktraces isn't helpful sometimes, so name of acessed property should simplify debug in some cases.

**Comment by xaviergonz** [comment]
@Amareis would this pr fix your issue?
https://github.com/mobxjs/mobx-state-tree/pull/1147

**Comment by Amareis** [comment]
Error displays wrong action path. There is should be `/.setData()` path (this is action at tree root, which is replace whole subtree).

Error: [mobx-state-tree] You are trying to read or write to an object that is no longer part of a state tree. (Object type: 'Chat', Path upon death: '/data/chats/items/4cd66e4b-09be-4c21-8153-1fa37f69758b', Subpath: 'id', Action: **'/data/chats/items/4cd66e4b-09be-4c21-8153-1fa37f69758b.setData()'**). Either detach nodes first, or don't use objects after removing / replacing them in the
