### ISSUE TITLE
0.5.0 | 0.5.1 breaking issue

### ISSUE THREAD

**Issue by RainerAtSpirit** [mobxjs/mobx-state-tree#115]
In 0.4.0 the below code updates `this.data` within the `read` action correctly.
My assumption is that by the breaking change `protection is now enabled by default` this no longer works with 0.5.x. However the system doesn't throw any error so that I'm a bit clueless what needs to be updated.
Is there anything obvious that won't work with 0.5.x?

```javascript
export const createCollectionFactory = (appId: string, Model, options: OdataOptions = {}) => {
	return types.model(Model.name + 's', {
		appId: appId,
		endpoint: modelEndPointMap[Model.name],
		data: types.array(Model),
		// utility function
		at(index: number) {
			if (index < this.data.length) {
				return this.data[index]
			}
			return null
		}
	},
		// action
		{
			read() {
				const tl = getEnv(this).tl
				return tl.read(this.endpoint, options)
					.then(action((data: any) => {
						const values = data.hasOwnProperty('value') ? data.value : data
						this.data = values.map((item: any) => {
                                                        // shortenend ...
							return item
						})
					}).bind(this))
			}
		})
}
```

**Comment by mweststrate** [comment]
interesting, that shouldn't work indeed :) Will try to reproduce

**Comment by RainerAtSpirit** [comment]
Here's a passing test in the v0.4 branch https://github.com/RainerAtSpirit/mstStore/blob/v0.4/test/createEndPointStore.ts

And here the failing test in the 0.5.1 branch. I  couldn't get ava t.throws work correctly with the rejected promise, but I see the err.message.
`"[mobx-state-tree] Cannot modify \'AnonymousModel@/lists\', the object is protected and can only be modified by using an action."​​`

https://github.com/RainerAtSpirit/mstStore/blob/v0.5.1/test/createEndPointStore.ts

Error mesage thrown in the promise is 
```javascript
test('it should update lists.data on lists.read() ', (t) => {
		return appStore.lists.read().then(data => {
			const s: any = getSnapshot(data)
			t.deepEqual(s, result)
		}, err => {
			console.log('err', err)
			t.is(err.message, "[mobx-state-tree] Cannot modify \'AnonymousModel@/lists\', the object is protected and can only be modified by using an action."​​)
		})
})
```

**Comment by RainerAtSpirit** [comment]
@mweststrate Added test cases.

**Comment by RainerAtSpirit** [comment]
@mweststrate updated the failing test in v0.5.1 to use async/await syntax to allow `yarn test` run sucessfully
```javascript
test('it should update lists.data on lists.read() ', async t => {
  const error = await t.throws(appStore.lists.read());
  t.is(error.message, "[mobx-state-tree] Cannot modify \'AnonymousModel@/lists\', the object is protected and can only be modified by using an action."​​);
})
```

Here's the relevant part from `createEndPointStore` where read is an action and the then block is capsuled in an action as well.

https://github.com/RainerAtSpirit/mstStore/blob/v0.5.1/src/mst/createEndPointStore.ts

```javascript
export const createEndPointStore = (endpoint: string, Model) => {
	return types.model({
		endpoint: endpoint,
		data: types.array(Model)
	}, {
		read() {
			const tl = getEnv(this).tl
			return tl.read(this.endpoint)
					.then(action((data: any) => {
					const values = data.hasOwnProperty('value') ? data.value : data
					this.data = values.map((item) => {
							return Model.create(item)
						}
					)
					return this.data
				}).bind(this))
		}
	})
}
```

**Comment by RainerAtSpirit** [comment]
@mweststrate. After refactoring the above example to use two dedicated actions, one for read and one for updating the system starts working as expected. Lesson learned: avoid using mobx `action` directly when using MST.

https://github.com/RainerAtSpirit/mstStore/blob/0.6.1/test/createEndPointStore.ts

```javascript
export const createEndPointStore = (endpoint: string, Model) => {
	return types.model(Model.name + 's', {
		endpoint: endpoint,
		data: types.array(Model)
	}, {
		read() {
			const tl = getEnv(this).tl
			return tl.read(this.endpoint)
				.then((resp: any) => {
					return this.updateFromRespone(resp)
				})
		},
		updateFromRespone(resp) {
			const values = resp.hasOwnProperty('value') ? resp.value : resp
			this.data = values.map((item) => {
				return item
			})
			return toJS(this.data)
		}
	})
}
```
