### ISSUE TITLE
Loading references on demand

### ISSUE THREAD

**Issue by carlosagsmendes** [mobxjs/mobx-state-tree#1155]
**How to load references on demand?**

* [X] I've checked documentation and searched for existing issues
* [X] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

Hi, I need to load references on demand to support collaborative editing where multiple users data is being synchronized with patches. 

For example, I'm synchronizing Tasks between different users and synchronizing changes with patches. But Tasks have a reference to Users that may not be available when the Tasks patches are applied.  

I've found the following code on a test, but it relies on setImmediate which is only available on IE:
```
.views(self => ({
            // Important: a view so that the reference will automatically react to the reference being changed!
            getOrLoadUser(name: string) {
                const user = self.users.find(u => u.name === name) || null
                if (!user) {
                    /*
                    TODO: this is ugly, but workaround the idea that views should be side effect free.
                    We need a more elegant solution..
                */
                    setImmediate(() => self.loadUser(name))
                }
                return user
            }
        }))
```

Any suggestions for an alternative pattern avoiding the setImmediate approach?

Thanks in advance

**Comment by mattruby** [comment]
The docs cover this. Here's a code example :
https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mobx-state-tree/__tests__/core/reference-custom.test.ts#L148

n Sun, Jan 27, 2019, 5:13 PM carlosagsmendes <notifications@github.com>
wrote:

**Comment by carlosagsmendes** [comment]
Thank you @mattruby , that's where I got the code I shared above. 

I cannot rely on `setImmediate` and that's why I'm looking for an alternative solution

**Comment by xaviergonz** [comment]
settimeout with 0 as delay maybe should get close

**Comment by carlosagsmendes** [comment]
Thank you @xaviergonz. I'll try it.
