### ISSUE TITLE
Dynamic models 

### ISSUE THREAD

**Issue by vitomax** [mobxjs/mobx-state-tree#1162]
**_Question_**

* [ ] I've checked documentation and searched for existing issues

reference

What is the best way to define model for below object? Dynamic reference and each object in the array is a separate model?

```
array: [
    {
      id: "num1",
      type: "type1",
      sum: ""
    },
    {
      id: "num2",
      type: "type1",
      sum: ""
    },
    {
      id: "num3",
      type: "type2",
      data: "",
      array: []
    }
  ]
```

**Comment by xaviergonz** [comment]
Depends on what you are trying to model. 
Could you provide a typescript definition of what you are trying to achieve?

**Comment by mattruby** [comment]
At a glance, you may want to look at unions

**Comment by vitomax** [comment]
I will try to explain this. There are models with a set of their actions.

`const model1 = types.model({
  id: types.identifier,
  type: types.string,
  sum: types.string
}).actions(...);

const model2 = types.model({
  id: types.identifier,
  type: types.string,
  data: types.string,
  lox: types.string
}).actions(...);

const Skus = types.model({
  // here it is necessary to describe an array in which there would be 
  // references to models model1, model2, model3, etc. depending on 
  // the value of the type field.
}).actions(...);

const output = Skus.create({
  arr: [
    {
      id: "num1",
      type: "type1",
      sum: ""
    },
    {
      id: "num2",
      type: "type1",
      sum: ""
    },
    {
      id: "num3",
      type: "type2",
      data: "",
      lox: ""
    }
  ]
});`

It turns out an analogue of normalization in the database, but with references to different tables. What are your thoughts on the description of such a structure so as not to spoil the performance?

**Comment by xaviergonz** [comment]
https://github.com/mobxjs/mobx-state-tree#utility-types

a types.reference with a types.union with a dispatcher ( a function that given a snapshot will decide which type it is)

```
const anyModel = types.union({
  dispatcher(snapshot) {
    switch (snapshot.type) {
      case "type1": return model1;
      case "type2": return model2;
      default: throw new Error();
    }
  },
  model1, model2
});
```

**Comment by vitomax** [comment]
Great solution! Thanks a lot! I did not know about such features controller.

And how to specify references to these model (model1, model2, etc.) so that you can refer to them?

const Skus = types.model({
  arr: types.array(anyModel),
  selected: // ???  types.reference(anyModel) ???
});

const output = Skus.create({
  selected: "num1",
  arr: [
    {
      id: "num1",
      type: "type1",
      sum: ""
    },
    {
      id: "num2",
      type: "type1",
      sum: ""
    },
    {
      id: "num3",
      type: "type2",
      text: "text"
    }
  ]
});

**Comment by vitomax** [comment]
Another option, but using `find` to search for an identifier is irrational, it seems to me. It’s pointless to search the entire array every time, especially if the array is large. Then it's easier to use `types.map`

```
const Reference = types.reference(anyModel, {
  get(identifier, parent) {
    return parent.arr.find(item => item.id === identifier);
  },
  set(value) {
    return value;
  }
});

const Skus = types.model({
  arr: types.array(anyModel),
  selected: Reference
});
```

And how is the reference mechanics inside the library `mobx-state-tree`?

**Comment by xaviergonz** [comment]
Basically there's a reference registry per root store, which is a map like `Map<type, id>`.
That's why each root store cannot have more than one id per type.

When `resolveIdentifier(type, target, identifier)` is used, it will actually go to the root node of the target node to find that map and then do a `getRoot(target)->identifierMap.get(type, identifier)`

There's more to it,, but that's kind of how it works.

**Comment by xaviergonz** [comment]
Btw, I just wrote this unit test that passed, so as long as the union items use a different ID then the reference will work
´´´ts

test("#1162 - reference to union", () => {
    const M1 = types.model({ id: types.identifier, type: types.string, sum: types.string })
    const M2 = types.model({
        id: types.identifier,
        type: types.string,
        data: types.string
    })
    const AnyModel = types.union(
        {
            dispatcher(snapshot) {
                switch (snapshot.type) {
                    case "type1":
                        return M1
                    case "type2":
                        return M2
                    default:
                        throw new Error()
                }
            }
        },
        M1,
        M2
    )

    const Store = types.model({
        arr: types.array(AnyModel),
        selected: types.reference(AnyModel)
    })

    const s = Store.create({
        selected: "num1",
        arr: [
            { id: "num1", type: "type1", sum: "1" },
            { id: "num2", type: "type1", sum: "2" },
            { id: "num3", type: "type2", data: "3" }
        ]
    })
    unprotect(s)

    expect(s.selected.id).toBe("num1")
    expect(s.selected.type).toBe("type1")
    expect((s.selected as Instance<typeof M1>).sum).toBe("1")

    s.selected = "num2" as any
    expect(s.selected.id).toBe("num2")
    expect(s.selected.type).toBe("type1")
    expect((s.selected as Instance<typeof M1>).sum).toBe("2")

    s.selected = "num3" as any
    expect(s.selected.id).toBe("num3")
    expect(s.selected.type).toBe("type2")
    expect((s.selected as Instance<typeof M2>).data).toBe("3")
})
´´´
