### ISSUE TITLE
Handle Errors

### ISSUE THREAD

**Issue by tgensol** [mobxjs/mobx-state-tree#1163]
**_Question_**

Hi there,

I am looking for a way to handle the `YellowBox.js:67 Possible Unhandled Promise Rejection (id: 0):
Error: [mobx-state-tree] Error while converting`, every time I got an `...is not assignable to type...`

I tried to read the docs, search for previous questions, to use middlewares, but I didn't find an easy way to throw the error to my errors handler (like bugsnag or Sentry).

Thanks !

* [X] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

**Comment by xaviergonz** [comment]
I'm afraid you'll need to provide more info

**Comment by xaviergonz** [comment]
https://github.com/mobxjs/mobx-state-tree/blob/master/docs/API/README.md#typecheck

With that function you can run a typecheck of a type against a json and catch the exception it will throw

**Comment by tgensol** [comment]
I see, I will try with the typecheck thanks :) 

Could be cool to have .catch(), on a Store, for handling every errors which happens in the store

**Comment by xaviergonz** [comment]
Feel free to open an issue with any proposal about catch or to reopen this one if you need more help :)
For now closing this one
