### ISSUE TITLE
resolveIdentifier in onInvalidated reference hook always returns invalidTarget itself

### ISSUE THREAD

**Issue by Amareis** [mobxjs/mobx-state-tree#1166]
**_Bug report_**

* [X] I've checked documentation and searched for existing issues
* [X] I've made sure my project is based on the latest MST version
* [X] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/20mr1kj10p

I was trying to make simple custom reference which check at invalidation if we just replaced whole subtree and new subtree have such identifier.
```ts
function retryReference<IT extends IAnyComplexType>(subType: IT): IMaybe<IReferenceType<IT>> {
    return types.maybe(types.reference(subType, {
        onInvalidated(e) {
            e.replaceRef(resolveIdentifier(subType, e.parent, e.invalidId))
        }
    }))
}
```
It works (in sandbox, click todo and then "Reload" button, last todo reference will be saved in store), but if delete target from tree (or after subtree replacing with new identifiers, button "Reload2"), all is broken - because `resolveIdentifier` returns `e.invalidTarget`, which will be destroyed at the moment! 

**Describe the expected behavior**
`resolveIdentifier` inside of `onInvalidated` hook returns `undefined` after deleting node from tree or new node after correct subtree replacing.

**Describe the observed behavior**
`resolveIdentifier` inside hook returns *old* node, which will be destroyed just now.

**Comment by Amareis** [comment]
BTW, maybe such behaviour should be used in default `safeReference`?

**Comment by xaviergonz** [comment]
It kind of make sense since invalitation is triggered right before the node is destroyed or detached (and therefore still registered and still valid until the function ends), but I guess it could be changed so the ID gets unregistered earlier

**Comment by xaviergonz** [comment]
No promises though about resolve reference not returning undefined since I think invalidation would trigger before the new node has a chance to attach

**Comment by xaviergonz** [comment]
Btw, in this case a plain reference should work OK I think, since it will just reference the new node once the other is gone

**Comment by Amareis** [comment]
>Btw, in this case a plain reference should work OK I think, since it will just reference the new node once the other is gone

Yep, it will, but it's not an option if node can be deleted completely.

**Comment by xaviergonz** [comment]
There's actually an easier way to get it working
https://codesandbox.io/s/4zp7pmoknw

basically, if you use a safeReference and instead of usting Todo.create you just assing the snapshot then the reconciliation algorithm will trigger and no new nodes for the same id will be created, their data will just mutate instead

**Comment by xaviergonz** [comment]
I mean, if not done that way, even if resolveIdentifier is fixed to return undefined you still won't have a way to get the new node since it will be added -after- the current one is destroyed (which is at the end of onInvalidated)

**Comment by xaviergonz** [comment]
well, right now by assigning a new node you are implicitly hinting MST that you *don't* want to make reconciliation

so if MST were to do reconciliation automatically when new nodes were assigned (which I guess could be done by converting the node to a snapshot before assignation) you would still end up with the same problem, where the volatile state would not be re-created, but in this case with no escape hatch
