### ISSUE TITLE
Question: Is there any model creation completed hook

### ISSUE THREAD

**Issue by fbeaulieu** [mobxjs/mobx-state-tree#1167]
Here's some code to illustrate my case:

```
const BaseModel = types
  .model({
    code: types.number,
    description: types.string,
  })
  .actions(self => {
    let anyInternalValue = 0;

    const internalComputing = () => {
      ++anyInternalValue;
    }

    return {
      afterCreate: () => {
        console.log('afterCreate called...');
        internalComputing(); // ERROR Failed to resolve...
      },
      afterAttach: () => {
        console.log('afterAttach called...');
        internalComputing();
      }
    }
  })
  ;

const RootModel = types
  .model({
    baseInstance: types.maybe(BaseModel)
  })
  .actions(self => {
    return {
      createBaseInstance: (code, description) => {
        self.baseInstance = BaseModel.create({ code, description });
      }
    }
  })
  ;

aModel = RootModel.create();
```

**Now, if I run the following:**

`aModel.createBaseInstance(100, 'baseModel instance');`

**console looks like:** 
_afterCreate called...
afterAttach called..._
_>> anyInternalValue === 2 (expected 1)_

**Then, if I create an instance of BaseModel, but standalone (no parent):**

`let bModel = BaseModel.create( { code: 100, description: 'baseModel instance' })`

**console looks like:** 
afterCreate called...
_>> anyInternalValue === 1 (expectation ok)_

Since I don't know if the user of my model will ever use BaseModel standalone (rely on afterCreate) or within a parent (rely on afterAttach), is there any hook I'm not aware of that I could use for that purpose like "afterCreationCompletedSortOf" ?

thanx !

**Comment by xaviergonz** [comment]
Internally there's a afterCreationFinalization hook (which I named finalize on the proposal here https://github.com/mobxjs/mobx-state-tree/issues/1151), but it's not currently exposed right now

**Comment by fbeaulieu** [comment]
> Internally there's a afterCreationFinalization hook (which I named finalize on the proposal here #1151), but it's not currently exposed right now

Is there any way I could detect if my current model instance (self) is being attached to a parent, I tried using getParent, hasParentOfType, getRoot, hasParent, but within afterCreate hook, it seems self has no clue about it's current parent. I'm just looking for a workaround until we get the finalize hook...

thanx!

**Comment by xaviergonz** [comment]
Not until that hook is added I'm afraid, since afterCreate runs when the node has been created but not yet attached to a parent, and afterAttach only runs if it actually has a parent.

Just wondering, what are you trying to achieve?

**Comment by fbeaulieu** [comment]
> Not until that hook is added I'm afraid, since afterCreate runs when the node has been created but not yet attached to a parent, and afterAttach only runs if it actually has a parent.
> 
> Just wondering, what are you trying to achieve?

Actually, I need to compute some code on creation of a model instance to which a reference is attached. I use the value of that reference inside the "initialization code", but since references are not resolved until attachment, I cannot rely on afterCreate. I have to wait within afterAttach instead. But at runtime, I cannot know if my model instance will be standalone or attached to a parent and I cannot put the initialization code into both afterCreate or afterAttach. I'm facing the chicken or the egg dilema. The initialization code is made from a "base model" that I compose with the user model.

But I finally work around this by providing the "base model" with a specific property _standaloneInstance that I set to false by defaut. So if my user wants to use his model standalone, he must set the _standaloneInstance = true. So from inside my "base model" I know from where to call the initialization code (_standaloneInstance = true ? call from afterCreate, _standaloneInstance = false ? call from afterAttach)

Once I get your new finalize hook, I will simply get rid of the _standaloneInstance property from my baseModel and I will call the initialization code from within finalize hook.

**Comment by mweststrate** [comment]
@xaviergonz doesn't a finalizeHook have exactly the same limitation? Unless `.create` is never called internally anymore, and `.create` is called only from userland; in that case that hook could be run on a full depth traversal of the created tree

**Comment by xaviergonz** [comment]
a finalize hook would be kind of like an attach hook, except that it would run also when there's no parent, so it would run once after the node is created and the whole tree is ready. combined with a "eager" creation mode (from the proposal) it would mean that it would always trigger no matter if the node is accessed or not (unless I'm missing something which I might :) )
