### ISSUE TITLE
getNodeId - A way to get a unique id for a node

### ISSUE THREAD

**Issue by faassen** [mobxjs/mobx-state-tree#1168]
**_Feature request_**

I'd like there to be a way to uniquely identify a node no matter whether it has an identifier and independent of its type.

I found a $treenode.nodeId which seems to do what I need, but it's not exposed officially. Would it make sense to expose a getNodeId function and support it?

**Is your feature request related to a problem? Please describe.**

I find myself in the position with mstform to want to be able to uniquely identify a node no matter whether it has an identifier and independent of its type, so I can use that identifier as a key in a Map.

Let me describe the use case:

A mstform FormState object gets created for a MST instance. The FormState sits between the UI and the underlying instance. It's responsible for validating and converting user input into underlying MST values and the other way around. To this end FormState installs a few things that observe the underlying object. In particular, onPatch, but also a few derived functions.

But we didn't deal properly with the disposers and as a result, in cases where an old FormState lingered around for the same object it would lead to weird bugs.

It's kind of tricky to reliably call dispose when the form is unrendered. It would be easiest to call dispose of any previous form state as soon as an attempt is made to attach *another* form state to the same MST node. But in order to do this I need to be able to associate some information with the MST node, and since mstform works with arbitrary MST model instances, I can't modify the model type to retain the disposer information.

If I could obtain a unique id for the node, no matter what its type or its identifier, I could look up a disposer in a map and this would take care of this problem. I just implemented this with $treenode.nodeId and it appears to work.

**Describe the solution you'd like**

A `getNodeId` that gives back a unique identifier so I can recognize a node again later.

**Describe alternatives you've considered**

* As I mentioned above, when you make the MST type cooperate then it's possible to solve it another way, but it's a fundamental design decision of mstform to work with arbitrary MST model types.

* I thought about a map that contains the node type (getType) and identifier (getIdentifier) but this won't work for nodes that don't have an identifier.

* I thought about using the node path, but that's not necessarily stable.

**Additional context**

https://github.com/isprojects/mstform

**Are you willing to (attempt) a PR?**

Yes.

**Comment by faassen** [comment]
That's a good idea. I hadn't considered using a Map with object keys, due to my uncertainty with that construct (I'm used to Python's hashing behavior), but it looks like that ought to work as it matches with ```===``` and I assume MST guarantees object identity.

I hadn't thought to use a weak map either, so thanks. It's not a problem that this only works for model instance nodes - that's what I use it for.

I will try this out in my code and see whether I run into any unexpected problems.

**Comment by faassen** [comment]
I have this now:

```ts
let nodeId = 0;
const nodeMap = new WeakMap<any, number>();

export function getNodeId(node: any): number {
  // XXX we should have a sanity check to determine whether node is a state tree
  // node
  let id = nodeMap.get(node);
  if (id === undefined) {
    id = nodeId++;
    nodeMap.set(node, id);
  }
  return id;
}
```

Getting the type correct for the node argument turns out to be surprisingly difficult. I tried Instance<IAnyModelType> but that resolves to ```any``` so that's not very useful.

I then tried to implement your suggested sanity check. I tried to use ```isModelType``` for this, but the type for it was rather odd (it would only accept a model type which is kind of useless). But I just now went through the source and I see you fixed that december 3. I will need to update to a new version of mobx-state-tree to get that fix.

**Comment by xaviergonz** [comment]
try 
```ts
export function getNodeId(node: IStateTreeNode): number {
  if (!isStateTreeNode(node) { throw Error("not a node") }

  let id = nodeMap.get(node);
  if (id === undefined) {
    id = nodeId++;
    nodeMap.set(node, id);
  }
  return id;
}
```

**Comment by mweststrate** [comment]
@xaviergonz I don't feel bad about exposing a utility for `getNodeId`, mostly because it can also used to explain or debug how reconciliation works, it makes that process a bit more transparent

**Comment by xaviergonz** [comment]
Sounds good to me then, I didn't want to decide on that :)
