### ISSUE TITLE
IDisposer type not exposed

### ISSUE THREAD

**Issue by faassen** [mobxjs/mobx-state-tree#1169]
**_Bug report_**

I'd like to be able to use `IDisposer` in my own code. It's described in the documentation but I cannot import it.

* [X] I've checked documentation and searched for existing issues
* [X] I've made sure my project is based on the latest MST version
* [ ] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

I also looked at the mobx-state-tree index.ts

**Sandbox link or minimal reproduction code**

```import {IDisposer} from 'mobx-state-tree';```

**Describe the expected behavior**

The ability to import the `IDisposer` type so I can use it in my code.

**Describe the observed behavior**

Module '"../node_modules/mobx-state-tree/dist"' has no exported member 'IDisposer'. [2305]

**Comment by xaviergonz** [comment]
IDisposer is just
`export type IDisposer = () => void`

do you need it for some specific use case?

**Comment by faassen** [comment]
I realize it's very simple, but I need to store disposers in a Map and I want to declare the type of that Map. I just experimented and if I redeclare it in my own code and use that I can make it work without type errors but nonetheless I don't see a reason why I should have to - IDisposer is mentioned in the API docs of MST, after all.

**Comment by xaviergonz** [comment]
will be available on the next version
