### ISSUE TITLE
Is revertPatch not available?

### ISSUE THREAD

**Issue by ygnoh** [mobxjs/mobx-state-tree#1172]
**_Question_**
Is `revertPatch` no longer available?

* [x] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

[The docs](https://github.com/mobxjs/mobx-state-tree#patches) introduces `revertPatch`, but [the change log](https://github.com/mobxjs/mobx-state-tree/blob/42906163752dcf9ee60dddbc587e8345dc19866a/changelog.md#0110) says `revertPatch` is no longer available. Which one is correct?

If the change log is correct, how can I undo(revert) some patches? Is there any other ways?

Thanks,

**Comment by luisherranz** [comment]
> Is `revertPatch` no longer available?

It's not. Use `reversePatch` instead:
https://github.com/mobxjs/mobx-state-tree/blob/1899fb6adbe8c309f6fa78507e0243a4ceb02daf/docs/API/README.md#onpatch

```js
const store = AppModel.create({ value: { a: { b: { c: 10 } } } })

onPatch(store, (patch, reversePatch) => {
        expect(patch).toEqual({ op: "remove", path: "/value/a" })
        expect(reversePatch).toEqual({ op: "add", path: "/value/a", value: { b: { c: 10 } } })
    })

store.remove("a")
```

Feel free to reopen if you have more doubts.

**Comment by ygnoh** [comment]
Thank you for your reply. But when the `onPatch` callback is invoked, `reversePatch` is `undefined`. 
Could you check it [here](https://codesandbox.io/s/10jz9j20zj)?

**Comment by ygnoh** [comment]
Sorry, It was my fault. In the link, MST version is outdated.

**Comment by luisherranz** [comment]
Glad you got it :)
