### ISSUE TITLE
Detaching an array eliminates all of it's children

### ISSUE THREAD

**Issue by k-g-a** [mobxjs/mobx-state-tree#1173]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

```detach```'ing array from ```model``` effectively eliminates all the children
```js
const Model = types.model(items: types.array(SomeModel));
const model = Model.create(items: [{}, {}, {}, ...])
const detachedItems = detach(model.items);
detachedItems[0] // is undefined
model.items = detachedItems // does nothing, as there are no items
```

**Sandbox link or minimal reproduction code**
[Reproduction](https://codesandbox.io/s/3v530zoz76)

**Describe the expected behavior**
Whole array with it's contents whould be detached, so it can be reused later on.

**Describe the observed behavior**
The array is detached and preserved, but it looses own content making its quite useless.

**Comment by k-g-a** [comment]
Code steps, jsut a quick glance: 
user code: ```detach(model.array)```
ObjectNode$$1.prototype.detach: ```this.parent.removeChild(this.subpath);```
ObjectNode$$1.prototype.removeChild: ```this.type.removeChild(this, subpath);```
ModelType$$1.prototype.removeChild: ```node.storedValue[subpath] = undefined;```
mobx's stuff about changes interception
ModelType$$1.prototype.willChange: ```change.newValue = type.reconcile(node.getChildNode(change.name), change.newValue);```
some steps about reconcilation
ObjectNode$$1.prototype.applySnapshot: ```this._applySnapshot(snapshot);``` - ```snapshot``` is ```undefined``` at this point
bunch of steps about action invokation
ArrayType$$1.prototype.applySnapshot: ```target.replace(snapshot);``` - ```snapshot``` is empty array at this point
ObservableArray$$1.prototype.replace: ```return this.$mobx.spliceWithArray(0, this.$mobx.values.length, newItems);``` // returns array's children nodes
ObservableArrayAdministration.prototype.dehanceValues: ```values$$1.map(this.dehancer);```
ObjectNode$$1._unbox: ```return childNode.value``` => ``` this.type.getValue(this)``` => ```isAlive === false``` => ```return undefined```

So we get array of ```undefined```'s instead of values. I had no time to nail down the place at which child nodes die, but hope this helps.

**Comment by k-g-a** [comment]
@mweststrate could you please confirm, that it's a bug and not expected behaviour? 
It seems like child nodes die during reconcilation, meaning this have been happening for a long time.

**Comment by mweststrate** [comment]
@k-g-a it sounds like a bug to me indeed, a detached tree should entirely be kept alive. I don't have the impression the detach functionality is really ever used. Only initial attaches.
Which probably explains why the bug is around for so long. But it might be broken for array / maps only, and not for objects.

**Comment by xaviergonz** [comment]
The funny thing is that even after detaching model.items === detachedItems
Just wondering, if an array is detached from a model what should happen to the model array, should it become an empty array?

**Comment by xaviergonz** [comment]
Also, wouldn't it make more sense than when detaching it would do something like this?
```
// detach(model.items); {
  const oldNode = model.items;
  model.items = getSnapshot(model.items); // replace by a node which is a exact copy of the detached node
  return oldNode
// }
```
since undefined is not always a valid value

**Comment by xaviergonz** [comment]
Nevermind, just saw that undefined is asserted to be an ok value before detaching

**Comment by xaviergonz** [comment]
unit test
```ts
test("#1173 - detaching an array should not eliminate its children", () => {
    const M = types.model({})
    const AM = types.array(M)
    const Store = types.model({ items: AM })
    const s = Store.create({ items: [{}, {}, {}] })
    const n0 = s.items[0]

    unprotect(s)

    const detachedItems = detach(s.items)
    expect(s.items).not.toBe(detachedItems)
    expect(s.items.length).toBe(0)
    expect(detachedItems[0]).toBe(n0)
})
```

**Comment by xaviergonz** [comment]
I think I found it

**Comment by xaviergonz** [comment]
PR done, that being said I think it might be cool to be able to give a snapshot/node as second optional parameter to detach to be able to "swap" them to a value other than undefined if desired
shouldn't be too hard to implement
