### ISSUE TITLE
Question: TypeScript type error while using types.maybe in generic function 

### ISSUE THREAD

**Issue by calebdelnay** [mobxjs/mobx-state-tree#1177]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

Hello, I'm new to TypeScript and MST. I'm trying to create a generic function to create models around primitives with some extra functionality. I'm running into an issue where using `types.maybe` doesn't interop with TypeScript how I'd expect. I assume I'm missing something obvious, but I'm not sure what (still learning).

The following code fails to compile with TypeScript (I'm using strict compiler options). The code below is pared down to illustrate my confusion.

Using TypeScript 3.3.3 and MST 3.10.2.

```
import { types, ISimpleType } from "mobx-state-tree";

function ValueField<T>(valueType: ISimpleType<T>) {
  return types.model("ValueField", {
    value: valueType,
    maybeValue: types.maybe(valueType),
  }).actions(self => {

    function setValue(value: T) {
      self.value = value;
    }

    function setMaybeValue(value?: T) {
      self.maybeValue = value;
    }

    return {
      setValue,
      setMaybeValue,
    };
  });
}

export default ValueField;
```

Use example:
```
const MyModel = types.model({
  numberPrimitive: ValueField(types.number),
  stringPrimitive: ValueField(types.string),
});
```

The compile error is:
```
src/lib/test.ts:14:7 - error TS2322: Type 'T | undefined' is not assignable to type 'RedefineIStateTreeNode<T, IStateTreeNode<T | undefined, T | undefined>> | undefined'.
  Type 'T' is not assignable to type 'RedefineIStateTreeNode<T, IStateTreeNode<T | undefined, T | undefined>> | undefined'.
    Type 'T' is not assignable to type 'RedefineIStateTreeNode<T, IStateTreeNode<T | undefined, T | undefined>>'.

14       self.maybeValue = value;
         ~~~~~~~~~~~~~~~
```

In the above example, the type of `self.value` is `T` while the type of `self.maybeValue` is `RedefineIStateTreeNode<T, IStateTreeNode<T | undefined, T | undefined>> | undefined`.

My question is: why is the type of `self.maybeValue` not just `T | undefined`?

I feel like I'm definitely missing something obvious, either in defining the model or in the action code to set the value. A cast somewhere?

Appreciate any insights. Thanks!

**Comment by xaviergonz** [comment]
Types from mst are more complex than they seem to be.

Use this instead 
```ts
function ValueField<IT extends IAnyType>(valueType: IT) {
    return types.model("ValueField", {
        value: valueType,
        maybeValue: types.maybe(valueType),
    }).actions(self => {

        function setValue(value: typeof self.value) {
            self.value = value;
        }

        function setMaybeValue(value: typeof self.maybeValue) {
            self.maybeValue = value;
        }

        return {
            setValue,
            setMaybeValue,
        };
    });
}

const MyModel = types.model({
    numberPrimitive: ValueField(types.number),
    stringPrimitive: ValueField(types.string),
});
```

That way it will work for any kind of type, not just simple types

**Comment by calebdelnay** [comment]
Yes, that worked. Thank you for the insight!
