### ISSUE TITLE
Question: initialize class instance with prop validation

### ISSUE THREAD

**Issue by Elminday** [mobxjs/mobx-state-tree#1179]
**_Question_**

(Is it possible / what is the smartest way) Using **mst** to construct ES6 class instance with prop validation?

Example of desired functionality:

```
const TodoModel = types.model({
  name: types.string,
});
class TodoClass {
  get name() {
    return this.name;
  }
  set name(name) {
      this.name = name;
  }
}

// Desired result is constructed TodoClass instance with validated name prop.
// TodoClass { name: 'test' }

**Comment by xaviergonz** [comment]
Check out types.refinement

**Comment by Elminday** [comment]
@xaviergonz if I understand correctly types.refinement is used for refining **name** string field.
But how does it help me solve problem with initializing CLASS instance with applied model?

**Comment by xaviergonz** [comment]
It is also used to do validation over the input snapshot with the method it takes as argument

**Comment by xaviergonz** [comment]
Or maybe I misunderstood what you want

**Comment by Elminday** [comment]
I want to initialize TodoClass with name property validation like this:


```
TodoClass {
  function printName() { 
    console.log(this.name);
  }
}
const valid = new TodoModel.create({ name: 'validString' }); //valid name type
const invalid = new TodoModel.create({ name: false }); //mst error can not apply bool to string
valid.printName(); // 'validString'
```

**Comment by xaviergonz** [comment]
```ts
const TodoModel = types.model({
  name: types.string
}).views(self => ({
  printName() { console.log(self.name); }
}))

const valid = TodoModel.create({ name: 'validString' }); //valid name type
const invalid = TodoModel.create({ name: false }); //mst error can not apply bool to string
valid.printName(); // 'validString'
```
that?

**Comment by Elminday** [comment]
Yes! I think i misunderstood how views work at first.

Is there a way to extend views with Base views? Like classes.

For example I have BaseTodoView with printBase() { console.log(`print base ${this.name}` } method.

**Comment by Elminday** [comment]
@xaviergonz maybe you have experience with **classy-mst**. I tried achieving inheritance of views with provided example but it seems not to work:

https://github.com/charto/classy-mst/issues/16
