### ISSUE TITLE
reference with a late type

### ISSUE THREAD

**Issue by robinfehr** [mobxjs/mobx-state-tree#118]
`input: types.reference(types.late(() => BoxModel), '../../boxes'),`
that is currently not working.

seems that on
https://github.com/mobxjs/mobx-state-tree/blob/master/src/types/complex-types/object.ts#L267
for the late types the `factory.definition` must be called to get the identifierAttribute  - will provide a PR (needs to be reviewed carefully since i'm not having the full picture here)

**Comment by mattiamanzati** [comment]
Should be fixed by the PR, @robinfehr feel free to reopen if an issue appears.
