### ISSUE TITLE
types.union with array and primitive types

### ISSUE THREAD

**Issue by aMahdaoui** [mobxjs/mobx-state-tree#1181]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

Hello, 

Is there any possibility to combine two primitive type, an **_array_** of strings and  a **_string_**, by using **_union_** for example
what i'm trying to do is something ike this : 
```
const Variable = types.model("Variable", {  
    id : types.string,  
    name : types.string,    
    // value : types.union(types.array(types.string), types.string) ,  
    value : types.union( (snapshot) => {  
        if (snapshot.type === 'string') {   
            return types.string;  
        } else    
            return types.array(types.string);  
    }) ,  
  })  
```
but i got this error : 
```
Error: [mobx-state-tree] First argument to types.union should either be a type, or an objects object of the form: { eager?: boolean, dispatcher?: Function }
```

Thanks ;)

**Comment by xaviergonz** [comment]
This worked for me
```
test("", () => {
    const Variable = types.union(types.array(types.string), types.string)

    const variable1 = Variable.create("hi")
    const variable2 = Variable.create(["hi", "ho"])
    expect(variable1).toBe("hi") // no getSnapshot since it is a simple property
    expect(getSnapshot(variable2 as any)).toEqual(["hi", "ho"])
})
```

**Comment by mweststrate** [comment]
@aMahdaoui, your invocation of `types.union` is incorrect, first you should specify the types to choose between, then, optionally, an object with the dispatcher function in the shape as defined in the error message.

Note that in your specific example a dispatcher function is not needed at all, as @xaviergonz demonstrated, MST can figure this example out on it's own.

**Comment by aMahdaoui** [comment]
You right guys, 
Thanks @xaviergonz  @mweststrate
