### ISSUE TITLE
Extending a model

### ISSUE THREAD

**Issue by Maaartinus** [mobxjs/mobx-state-tree#1183]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

One week ago I posted a [question on SO][q], but got no answer, so I hope, I'm right here. The question there says it all, I'm trying to recap:

These are my stores:
```
const EntityStore = types.model(....)....
const userStore = EntityStore.create(....)
const orderStore = EntityStore.views(....).create(....)
```
This does not work:
```
const EntityStoreManager = types
.model('....',
    map: types.map(EntityStore)
)
...
    map.set('orderStore', orderStore) ` //// Error while converting...
```
I'd need something like `types.map(? extends EntityStore)` (Java-like syntax) or a different way to organize the manager.

[q]: https://stackoverflow.com/q/54566567/581205

**Comment by xaviergonz** [comment]
if they are snapshot-equivalent I'd try to pass into map the snapshot (be it the actual plain object or via getSnapshot).
basically models *instances*, even when structurally equivalent are not the same, but their snapshots might be.

**Comment by Maaartinus** [comment]
@xaviergonz Currently, they're snapshot-equivalent, but this may change. The bigger problem is that I need to preserve the identity as I'm using the models like objects with methods like `fetchAllItems()`. So when I'd re-create the model from the snapshot, the in-the-meantime finishing fetch would update a different instance.

**Comment by Maaartinus** [comment]
Anyone any other idea? In the meantime, I circumvented the problem by using some helpers and it's not entirely bad, but I could use something better.

**Comment by Maaartinus** [comment]
I guess, the [answer on SO](https://stackoverflow.com/a/54956326/581205) is fine.
