### ISSUE TITLE
Why I can`t get nested default values on create

### ISSUE THREAD

**Issue by geneoes** [mobxjs/mobx-state-tree#1184]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

```
const PersonalInfo = types
  .model({
    name: 'default_name',
    lastname: 'default_lastname',
  })
  
const Person = types
  .model({
    id: 'default_id',
    personalInfo: PersonalInfo
  });
```

Lets suppose I have a Person model that uses PersonalInfo model. I want to create an instance of the first one with all the default values but

```
const personalInfo = PersonalInfo.create(); // this works
const person = Person.create(); // this not, it ask for arguments and throws
``` 

```(at path "/personalInfo" value `undefined` is not assignable to type: `AnonymousModel` (Value is not a plain object).)```

Supposing I have defined all default values, shouldn't it create the instance without passing any arguments?

**Comment by Maaartinus** [comment]
This is something I ran recently into, so this might help (though I'm a noob here):
- Either call `Person.create({personalInfo: {}})`
- or use `personalInfo: types.optional(PersonalInfo, {})` in the definition.

Anyway, I'm joining you with the question: "shouldn't it just work"?

**Comment by xaviergonz** [comment]
Because a type is required until told otherwise by optional. For example, without optional is used when model a person HAS to have personal info

**Comment by lake2** [comment]
I  have the same problem. How to initialize a reference model when create the root model?

**Comment by mattruby** [comment]
Make a codesandbox.io example and I'll demo types.optional for you.

**Comment by lake2** [comment]
@mattruby   https://codesandbox.io/s/z25y14128l?codemirror=1&fontsize=14
something like this. Thanks

**Comment by mattruby** [comment]
Here's one way : https://codesandbox.io/s/91844y51xo

**Comment by mattruby** [comment]
In your example, you're not really using references. In order to use references, we'll need to use types.identifier on the model you want to refer to. Based on your example, it doesn't really look like you need references.

**Comment by lake2** [comment]
@mattruby  thanks

**Comment by mattruby** [comment]
I think we're good.  Feel free to open another ticket.  And remember, create a codesandbox.io example.  It saves so much time.
