### ISSUE TITLE
Question: simple inheritance of views do not seem to work

### ISSUE THREAD

**Issue by Elminday** [mobxjs/mobx-state-tree#1187]
**_Question_**

This may not be directly linked but it is underlying MST functionality and because after a whole week of no response I decided to seek for help here.

https://github.com/charto/classy-mst/issues/16

The issue described above seems not to work when trying to use inheritance with MST views.

**Comment by mweststrate** [comment]
Did you double check that action is imported from MST, not MobX?

Beyond that, classy MST is not something we support. You'll find some issues in this repo where there is explicitly asked for class support in MST, and where these kind of issues are brought up as reasons not to support it :). Mst doesn't offer a classical class / inheritance model, but a model composition / extension model, which doesn't map 1 on 1 how classes normally behave.

**Comment by Elminday** [comment]
Action is imported from `classy-mst` not from MST or Mobx.

Understood about class support. Should I close this then?

**Comment by mweststrate** [comment]
Yeah I guess, not sure if more people using classy-mst are around here

**Comment by jjrv** [comment]
@mweststrate `classy-mst` requires some massaging when `mobx-state-tree` updates. The changes are small but annoying to figure out. To me it seems inheritance works just fine and there isn't really any reason not to support this officially, but YMMV.
