### ISSUE TITLE
bootstrap command should be removed from package.json

### ISSUE THREAD

**Issue by ghost23** [mobxjs/mobx-state-tree#1189]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [ ] I've made sure my project is based on the latest MST version
* [ ] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

I am using node v8.11.1 , npm v5.6.0, yarn v1.12.3 on Windows 10.
I had cloned the mobx-state-tree repository. Then I ran `yarn bootstrap`.

**Describe the expected behavior**
 I expect all dependencies to be installed.

**Describe the observed behavior**
I get an error message:

```C:\Users\<user>\projects\mobx-state-tree> yarn bootstrap
yarn run v1.12.3
$ npx lerna@3.3.0 bootstrap --hoist
npx: installed 637 in 33.875s
lerna notice cli v3.3.0
lerna ERR! EWORKSPACES --hoist is not supported with --npm-client=yarn, use yarn workspaces instead
lerna ERR! EWORKSPACES A guide is available at https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/
error Command failed with exit code 1.
```

**Comment by xaviergonz** [comment]
don't use bootstrap, use plain yarn install
(actually the bootstrap command should be removed)
