### ISSUE TITLE
Reaction doesn't converge to a stable state after 100 iterations.

### ISSUE THREAD

**Issue by pioh** [mobxjs/mobx-state-tree#12]
When i try to reuse my code on the java server under NashornScriptEngine i get this error:
```
javax.script.ScriptException: Error: Reaction doesn't converge to a stable state after 100 iterations.
```
```javascript
import {createFactory} from 'mobx-state-tree'
import {useStrict} from 'mobx'
useStrict(true)

let TaskError = createFactory({
  message: null,
})

class Validator {
  taskDoneErrors (json) {
    let taskError = TaskError({message: 'OK'})

    return [{message: taskError.message}]
  }
}
global.validator = new Validator()
```
When i use only mobx threre are no errors.

**Comment by mweststrate** [comment]
is NashornScriptEngine fully ES5 compliant?

**Comment by pioh** [comment]
> Nashorn javascript is based on ECMAScript 5.1 but future versions of nashorn will include support for ECMAScript 6

> Until Java SE 7, JDKs shipped with a JavaScript scripting engine based on Mozilla Rhino. Java SE 8 instead ship with a new engine called Oracle Nashorn, which is based on JSR 292 and invoke dynamic.

Nashorn seems to be better than a rhino. But then this error. Now I use rhino and everything works fine. I do not know, maybe a bug in nashorn.
