### ISSUE TITLE
Introduce `applyPartialSnapshot`

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#120]
like applySnapshot, but leaves unmentioned fields as is (so a bit like Object.assign, etc). Second argument, defaulting to `true`, to indicate whether non-represented items from old collections should be removed? (`false` would make the method only additative)

**Comment by DyingAlbatross** [comment]
I'm going to take a stab at this one if that's alright

**Comment by DyingAlbatross** [comment]
Hey @mweststrate & @mattiamanzati 
I think I'm getting close for this... but to be sure I'm in line with what you're thinking, could you provide some example situations with your expected input / output?

**Comment by mweststrate** [comment]
The thing I am unsure about is how to handle maps / arrays. Should we
assume applyPartialSnapshot is incremental only and cannot be used to drop
items? Also I think that it is important that for objects that have an
identifier, the identifier is included in the snapshot to make sure
reconciliation works as expected

Op di 17 okt. 2017 om 02:34 schreef Albatross <notifications@github.com>:

**Comment by ConneXNL** [comment]
Am I correct that the a current way to do this is to get a snapshot, deepmerge it with the changes into an empty object?

So something like this?

```
import * as deepmerge from "deepmerge";

applySnapshot(todoStore, deepmerge.all([
        {},
        getSnapshot(todoStore), { 
            todos: {
                "2" : {
                    id: 2,
                    title: "Get coffee"
                }
            },
            selectedTodo: 2
    }])))
```

If so, an example in the docs could be helpful until `applyPartialSnapshot` is ready.

**Comment by ashconnell** [comment]
Based on the usage stated above by @mweststrate i'm wondering if this should actually be called mergeSnapshot?

**Comment by mrahhal** [comment]
No updates on this? This would be a really valuable feature!

**Comment by holgersindbaek** [comment]
+1 for this feature.

**Comment by maccman** [comment]
+1 !

**Comment by coolsoftwaretyler** [comment]
Hey folks,

This MobX-State-Tree issue is pretty old and hasn't had movement for a while.

I'm gonna close it out as unplanned, but it's a great idea and we're always happy to review PRs. Personally, I prioritize PR review over my own work, so if anyone wants to build this out, please submit a PR and we will get to it in a timely manner!

Thanks for your time.
