### ISSUE TITLE
Derived state in separate trees, references across trees

### ISSUE THREAD

**Issue by zxti** [mobxjs/mobx-state-tree#1202]
**_Feature request_**

**Is your feature request related to a problem? Please describe.**
AFAIK, derived state can currently exist either as:

- a view attached to a model.
- a raw MobX computed(), which can be anything, such as an MST tree.

The former means that all possible derived state throughout your app must ultimately go into the type's views(), which is a loss for modularity.  You can't have reselect-style decentralized derived state.

The latter can generate an entirely separate tree without changing the original types, but you can no longer reference things in the original tree transparently (an MST feature), and must resort to working with IDs and passing the original tree everywhere you pass the derived state (to allow dereferencing).

**Describe the solution you'd like**
I don't know what the best design solution is. Some ideas:

- Maybe this just boils down to having references across trees? Smells to me like something's missing, or maybe this is too broad/intractable.
- Or, maybe MST needs its own `computed()` primitive for deriving separate trees ("derived trees)", which can then either just exist as separate trees, or even be inserted back into the original tree (ooh I like this.)

**Describe alternatives you've considered**
Really, a MobX reaction() that listens to the original tree, generates a snapshot for the derived state, and then applies that snapshot to a separate stable tree instance, is I believe as close as one can get today, but - again - you don't have references.

You can't just compose-extend a type with new views; the rest of the codebase is still speaking the original type.

**Are you willing to (attempt) a PR?**
I think this needs a design.  Also, I could well have just not thought of an existing workable solution.

**Comment by xaviergonz** [comment]
Can't you do the same by having a "root store of stores" with views that just reference all inner children store models?

**Comment by zxti** [comment]
You can shoehorn derived state into stores, but I want to first point out a different solution:

- Reselect selectors don't live in the store, and instead are owned by consumers (connected components).
- MobX `computed`s don't live in the store, and instead are owned by consumers.

What are the trade-offs?  When we tried putting all derived state into the store, we were faced with the following considerations:

- Modularity: Your root store must now know about all possible views used throughout the app - all developers must be registering their views into one central location. In our experience, as our app scales, the majority of components have some form of derived state, so this is equivalent to registering every component with the store.
- Encapsulation: Your derived state is no longer private, but globally accessible and furthermore encrusted in the API of the store.
- Lifecycle management: You now need to explicitly create and garbage collect these view objects.  Your derived state doesn't automatically appear just because your component was created and disappear just because your component was unmounted.
- Dependency management: Your store and derived state are cyclic dependencies.  You cannot have the store in a root project and your derived state in a dependent project.

**Comment by xaviergonz** [comment]
Care to put some pseudo-code as an example? I'm really bad at understanding concepts without examples :(

**Comment by zxti** [comment]
Sure thing, here's a stab, is this what you're thinking?  Let me know if this helps:

```
// I'll define these out of order.  First consider the store of stores:
const Store = types.model({
  primary: PrimaryData,
  derived: DerivedData
});

// Our PrimaryData has whatever it has:
const PrimaryData = types.model({
  users: types.array(User),
  files: types.array(File),
  syntaxTrees: types.array(SyntaxTree)
});
const User = ...
const File = ...
const SyntaxTree = ...

// What does DerivedData contain? Any component can have its own derived state, so we'll need to make room for all of them here.
// This demonstrates the points about modularity (store needs to have awareness of all possible derived state used throughout the application), encapsulation (any component's derived state is visible to everyone), cyclic dependencies, etc.
const DerivedData = types.model({
  component1DerivedState: types.map(Component1DerivedState),
  component2DerivedState: types.map(Component2DerivedState),
  component3DerivedState: types.map(Component3DerivedState),
  ...
  component999DerivedState: types.map(Component999DerivedState),
});

// An individual component's derived state can be whatever it wants, defined as a view.  But first we need to specify the dependencies.
const Component1DerivedState = types.model({
  file: File,
  syntaxTree: SyntaxTree,
  user: User
}).views(self => ({
  get highlights() { return getHighlightsVisibleToUser(self.file, self.syntaxTree, self.user); }
}));

// Use from the component.  Note the explicit lifecycle management.
class Component1 {
  constructor(props) {
    super(props);
    const derived = Component1DerivedState.create({
      file: props.file,
      syntaxTree: props.syntaxTree,
      user: props.user,
    });
    props.store.derived.component1DerivedState.put(derived);
    this.state = { derived };
  }
  componentWillUnmount() {
    this.props.store.derived.component1DerivedState.remove(
      this.state.derived
    );
  }
}
```

**Comment by mweststrate** [comment]
Not sure if I understand the question correctly(didn't read everything),
but just want to point out MST and Mobx are fully compatible, so you can
create plain mobx boxed computeds anywhere you want and they'll work.

Op do 7 mrt. 2019 21:59 schreef zxti <notifications@github.com>:

**Comment by xaviergonz** [comment]
yeah, something like

```
export const myComputed = computed(() => someStore.something);
...
const x = myComputed.get()

// or

class MyComputeds {
  @computed
  get myComputed() {
    return someStore.whatever;
  }
}
export myComputeds = new MyComputeds()
...
const x = myComputeds.myComputed
```
or add them to the components, up to you

**Comment by zxti** [comment]
@mweststrate @xaviergonz Yeah, I did call out using MobX computed in my first post (see the second bullet).  The problem with that is that various MST features don't work:

> can no longer reference things in the original tree transparently (an MST feature), and must resort to working with IDs and passing the original tree everywhere you pass the derived state (to allow dereferencing).

This is why I was suggesting that this may just boil down to making references and identifiers work across separate trees.

Another (more distant) motivation for separate trees: React team has harped on moving away from global state and to in-tree local state, and further breaking apart the local state into disparate pieces to accommodate the scheduler priorities.

**Comment by xaviergonz** [comment]
Actually references and identifiers work across separate trees as long as you use custom references
https://github.com/mobxjs/mobx-state-tree#customizable-references

The rule of refrences only working across the same tree only applies to "vanilla" references

**Comment by zxti** [comment]
Thanks for that suggestion, I didn't think of that.  I'm now trying to figure out how to use this for maintaining a computed MST tree derived from a separate tree.

Say I have a primary store (state tree), and then a derived store (state tree) based on the primary store, and now I want to write another derived state tree of DerivedLeaf objects based on data from these two other stores.

Would it look like this?  Do you have any suggestions on how to improve this?  I'm hoping I'm making it way more cumbersome that it needs to be.

```ts
const StoreRef = (type, storeKey) =>
  types.reference(type, {
    get(ident, parent) {
      return resolveIdentifier(type, parent[storeKey], ident);
    },
    set(value) {
      return value.id;
    }
  });

// Any time you reference data from another store, you also have to explicitly have that store root available for StoreRef to access.
const DerivedLeaf = types.model({
  store: volatile,
  anotherDerivedStore: volatile,
  user: StoreRef(User, 'store'),
  derivedStuff: StoreRef(, 'anotherDerivedStore'),
  subleafs: ...
}).views(self => ({
  get derived() {
    return computeDerived(self.user);
  }
});

const DerivedLeaves = types.model({
  rootLeaf: DerivedLeaf
});

// Now we want to write a helper that generates derived trees, such as the tree of DerivedLeafs.
// I guess we just have to express the computed as snapshots.
function computedTree(type, snapshotGenerator) {
  let tree;
  autorun(() => {
    if (!tree) {
      tree = type.create(snapshotGenerator());
    } else {
      applySnapshot(tree, snapshotGenerator());
    }
  });
  return tree;
}

...
function MyComponent({store, anotherDerivedStore}) {
  // derived should be recomputed when store.currentUser changes
  const derived = useRef(deriveTree(() => ({rootLeaf: {store, anotherDerivedStore, user: store.currentUser.id}}))); // TODO clean up the autorun?
  ...
}
```

**Comment by xaviergonz** [comment]
As for the store ref, if what you want is just a reference that works across all trees I'd make it like this (note that in this case the IDs of each object have to be unique across your -whole- app though.

```ts
    // global obj map that maps id to an object
    const objMap = new Map<string | number, any>();

    const StoreRef = <IT extends IAnyType>(type: IT, idKey: string = "id") => 
     types.reference(type, {
        get(ident) {
            // read it from our global map of ids
            return objMap.get(ident);
        },
        set(value) {
            // save it into our global map of ids
            objMap.set(value[idKey], value);
            return value[idKey];
        }
    });
```

**Comment by xaviergonz** [comment]
That way you don't need to add fancy keys into the models and you can keep using the standard types.identifier

**Comment by coolsoftwaretyler** [comment]
Hey folks, this MobX-State-Tree issue is pretty old, and it seems like y'all were able to resolve it without any code changes necessary. I'm going to close it out.

Thanks!
