### ISSUE TITLE
How can I reset all volatiles to defaults

### ISSUE THREAD

**Issue by agolovenkin** [mobxjs/mobx-state-tree#1204]
In my model I have fields such as errors, loading etc. as volatiles. Fields keep his values when it's not needed. 

For example we have two pages: with list and with form. We try to add some record and some error occurs. We go back to list and click "add" again. And we see our old error.

So I want to reset all model volatiles to defaults.
I know that I can do it manually by models.setErrors(null); models.setLoading(false); etc.. but it is too much code. Can I set all volatiles to default by one action? For example:

```JavaScript
for (let name in model.volatiles.defaults) {
   self[name] = model.volatiles.defaults[name];
}
```

**Comment by xaviergonz** [comment]
You could put all your volatile stuff into an object
```
const defaultData = {
  a: 1,
  b: 2
}

.volatile(self => ({
  someObj: { ...defaultData }
}).
action(self => ({
  reset() {
    this.someData = { ...defaultData };
  }
}))
```
or something similar
