### ISSUE TITLE
Change Coveralls Coverage Decrease Failure Threshold

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx-state-tree#1206]
Since coveralls was fixed, PRs are being marked red for small changes in coverage.

This is even more annoying when you submit on a same PR a first commit that actually increases it by +3% globally but then the PR is marked as red because the second commit reduces it to +2.9%, marking it as red (-0.1% delta) :-/

Let's change the difference in coverage required to be within 1% of existing coverage.

See https://github.com/deepchem/deepchem/issues/648 for example for a how to

**Comment by mweststrate** [comment]
Afaik it is also possible to ignore certain branches in coverage, for example for internal variants we don't want to bother testing. Just never figured out how to do that. (But I suspect that is how all 100% coverage projects get to their 100% :-P).

**Comment by xaviergonz** [comment]
Thanks, just set it up to 2% for starters, with that I'm happy again :D
