### ISSUE TITLE
Task list of breaking changes for next major version

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx-state-tree#1207]
A task list of breaking changes to be done on a next release:

* Make returned items from pop/shift/splice on arrays return snapshots rather than dead nodes (see https://github.com/mobxjs/mobx-state-tree/pull/1205)
* Throw error when env not found (see https://github.com/mobxjs/mobx-state-tree/pull/938) - https://github.com/mobxjs/mobx-state-tree/issues/820
* Deprecate `preProcessSnapshot` / `postProcessSnapshot` from models in favor of `types.snapshotProcessor` (to be confirmed)
* Maps should have consistent behavior for non string keys / drop number identifiers - https://github.com/mobxjs/mobx-state-tree/issues/884

To be continued...

**Comment by coolsoftwaretyler** [comment]
Closing this out since it's quite old and we are a few major versions ahead now. Thanks!
