### ISSUE TITLE
Using types.optional(Model, {}) with typescript will throw an error

### ISSUE THREAD

**Issue by bdwenxi** [mobxjs/mobx-state-tree#1208]
**_Question_**

* [] I've checked documentation and searched for existing issues
* [] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

I have a parent store. This parent store contains two child stores. I use types.optional(Model, {}) to set two child stores. Typescript will throw an error, as shown below.
![image](https://user-images.githubusercontent.com/33823489/54104557-4eddd280-440b-11e9-9741-eae5ea2d8a58.png)
![image](https://user-images.githubusercontent.com/33823489/54104577-5f8e4880-440b-11e9-8479-c0f62921fb94.png)

**Version**
mobx: "4.9.2"
mobx-react: "5.4.3"
mobx-state-tree: "3.11.0"
typescript: "3.3.3333"

I use "cast" method or "castToSnapshot" method has no effect, the same will throw an  #error.

**Comment by ksjogo** [comment]
{} isn't a CustomSkillsModel, so you need a constructor for CustomSkillsModel there (or have actual static one. The solution you are likely looking for is `() => CustomSkillsModel.create({})`, but I don't know the rest of your codebase.

**Comment by simmons8616** [comment]
@ksjogo 
The same problem, as shown below
![image](https://user-images.githubusercontent.com/33823489/54106048-ea714200-440f-11e9-98c9-0d322ed40926.png)

The following picture is the details of the child store
![image](https://user-images.githubusercontent.com/33823489/54106212-67042080-4410-11e9-96c6-f5651338f662.png)

**Comment by xaviergonz** [comment]
and what is PagerModel

**Comment by simmons8616** [comment]
The following picture is the PagerModel
![image](https://user-images.githubusercontent.com/33823489/54112348-ebf73600-4420-11e9-8770-feda8ad24870.png)

**Comment by xaviergonz** [comment]
![image](https://user-images.githubusercontent.com/6306796/54159286-f6c7c000-444c-11e9-823f-e9f036fee417.png)

no errors for me
do you have all strict checks enabled in your tsconfig.json?

**Comment by xaviergonz** [comment]
This worked for me:
```ts
test("", () => {
    const CustomSkillsModel = types.compose(
        types.model({
            pageNo: 1,
            pageSize: 15,
            totalCount: 0,            
        }), 
        types.model({
            skills: types.array(types.null)
        })
    )
    const MySkillModel = types.model({
        customSkill: types.optional(CustomSkillsModel, {})
    }).views(self => ({
        get isCustomAndPreEmtpy() {
            return self.customSkill.skills.length <= 0; // no errors here
        }
    }))
})
```

**Comment by marcofugaro** [comment]
I am having the same problem, this bug was introduced in `v3.11.0`.

```js
const State = t
  .model('State', {
    ui: t.optional(UI, {}),
  })

const state = State.create({})
```

It says

> Property 'ui' is missing in type '{}' but required in type 

![image](https://user-images.githubusercontent.com/7217420/54747165-6c125e00-4bce-11e9-8ef3-85282a9bbcd7.png)

**Comment by gamliela** [comment]
Same here, mobx-state-tree version 3.12.1.
```typescript
const MyDiagram = types
  .model('MyDiagram', {
    zoomFactor: types.optional(types.number, 50)
  });
MyDiagram.create({});  // <--- TS2345: ... Property 'zoomFactor' is missing in type '{}' ...
```

**Comment by kresli** [comment]
```
    "mobx": "^5.9.0",
    "mobx-state-tree": "^3.12.0",
    "typescript": "^3.3.3333"
```
<img width="592" alt="image" src="https://user-images.githubusercontent.com/3826097/54975849-5915da00-4f90-11e9-92a7-183f73fc10e1.png">

and 
<img width="723" alt="image" src="https://user-images.githubusercontent.com/3826097/54975865-64690580-4f90-11e9-9ca8-157043314828.png">

**Previous version**
```
    "mobx": "^5.8.0",
    "mobx-state-tree": "^3.9.0",
    "typescript": "3.3.3"
```
<img width="560" alt="image" src="https://user-images.githubusercontent.com/3826097/54975971-be69cb00-4f90-11e9-9ab7-180ebe8cf9ee.png">
<img width="460" alt="image" src="https://user-images.githubusercontent.com/3826097/54975985-c88bc980-4f90-11e9-848e-d1a87ba28c99.png">

**Comment by simmons8616** [comment]
Upgrade to version 3.12.2 just fine. great!

**Comment by ConneXNL** [comment]
> Upgrade to version 3.12.2 just fine. great!

Not so sure. I still have the same issue.

**Comment by xaviergonz** [comment]
I'd enable strict null checks

**Comment by marcofugaro** [comment]
bug is still present! stale bot is way too strict

**Comment by dtabuenc** [comment]
I have the same problem. Very simple repro:

```ts

const Foo  = types.model({
    foo: types.maybe(types.string)
});

Foo.create({});
```

```
react/router/Router.tsx:154:12 - error TS2345: Argument of type '{}' is not assignable to parameter of type 'ExtractCFromProps<Pick<ModelPropertiesDeclarationToProperties<{ foo: IMaybe<ISimpleType<string>>; }>, "foo"> & Partial<Pick<ModelPropertiesDeclarationToProperties<{ foo: IMaybe<ISimpleType<string>>; }>, never>>>'.
  Property 'foo' is missing in type '{}' but required in type 'ExtractCFromProps<Pick<ModelPropertiesDeclarationToProperties<{ foo: IMaybe<ISimpleType<string>>; }>, "foo"> & Partial<Pick<ModelPropertiesDeclarationToProperties<{ foo: IMaybe<ISimpleType<string>>; }>, never>>>'.

154 Foo.create({});
               ~~

  react/router/Router.tsx:151:5
    151     foo: types.maybe(types.string)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'foo' is declared here.
```

**Comment by xaviergonz** [comment]
It will be fixed after this pr is merged
https://github.com/mobxjs/mobx-state-tree/pull/1251

**Comment by xaviergonz** [comment]
Well actually it depends on the tsconfig you have

**Comment by marcofugaro** [comment]
@xaviergonz which compiler option breaks it?

**Comment by xaviergonz** [comment]
Most probably strict null checks being disabled
Anyway try v3.14.0, it removed `create` trying to be too smart to guess if the snapshot parameter should be present or not

**Comment by kresli** [comment]
Still seeing this in 3.14.0 with strict true and no other strict option specified.

**Comment by xaviergonz** [comment]
Can you upload some repo project to github?

**Comment by kresli** [comment]
To be more specific, the type throw an error please check `src/index.ts`
https://codesandbox.io/s/ppqj7rmn37 
<img width="630" alt="image" src="https://user-images.githubusercontent.com/3826097/55827691-a94d7a00-5b02-11e9-86cc-b689c85e364d.png">

**Comment by xaviergonz** [comment]
That particular error is because IOptional now takes an array of values that are turned into the default value (usually [undefined])

**Comment by kresli** [comment]
@xaviergonz  yes, fixed by adding `[undefined]` eg: `IOptionalIType<ISimpleType<string>>, [undefined]>` Not much an issue. Just wonder if second param should be optional?

**Comment by ConneXNL** [comment]
Tried 3.14.0 one more round, still failing.  strictNullChecks = false. Enabling that breaks a lot of other stuff in the project so cannot enable it.

**Comment by marcofugaro** [comment]
Same for me, I don't think MST should depend on the user's compilerOptions to work correctly.

**Comment by marcofugaro** [comment]
not again stale bot

**Comment by dgeorgiev06** [comment]
this works for me in typescript:

accountStore: types.optional(AccountStoreModel, {} as typeof AccountStoreModel.Type),

note the "as typeof AccountStoreModel.Type" after {}

**Comment by PMExtra** [comment]
> This worked for me:
> 
> ```ts
> test("", () => {
>     const CustomSkillsModel = types.compose(
>         types.model({
>             pageNo: 1,
>             pageSize: 15,
>             totalCount: 0,            
>         }), 
>         types.model({
>             skills: types.array(types.null)
>         })
>     )
>     const MySkillModel = types.model({
>         customSkill: types.optional(CustomSkillsModel, {})
>     }).views(self => ({
>         get isCustomAndPreEmtpy() {
>             return self.customSkill.skills.length <= 0; // no errors here
>         }
>     }))
> })
> ```
> 
> the (maybe) relevant part of my tsconfig.json
> 
> ```
>         "strict": true,
>         "strictNullChecks": true,
>         "strictFunctionTypes": true,
>         "noImplicitAny": true,
>         "noImplicitReturns": true,
>         "noImplicitThis": true,
> ```

I solved it after change the `tsconfig.json`. It worked!

**Comment by coolsoftwaretyler** [comment]
Hey folks,

This issue is quite stale. I know there were some hasty bot closes in the past, but using @PMExtra's code in CodeSandbox, I no longer see these errors on current MST: https://codesandbox.io/p/sandbox/fervent-einstein-kny997?file=%2Fsrc%2Findex.ts%3A13%2C27

I'm going to close this, assuming we have fixed the issue. Please feel free to comment and send a reproduction if I'm mistaken. I know it's frustrating when open source issues like this get closed/opened/closed/opened/closed and all that, but with the years of inactivity, I think that's appropriate in this case.
