### ISSUE TITLE
getReferenceRelativePath

### ISSUE THREAD

**Issue by davidosomething** [mobxjs/mobx-state-tree#1212]
**_Feature request_**

**Is your feature request related to a problem? Please describe.**
When using `clone = models.create(getSnapshot(model))`, where model has an array of references, you lose the references since the created model is not in the tree.
I have implemented a reference copier:
- append the `clone` to the tree somewhere so it can resolve references
- look at each leaf, check if the snapshot contains an id where the model has a node. This loosely implies an identifier where a reference should be.
- store the object path in the snapshot where that leaf is
- check the parent type
    - if it is an array, push the reference into the parent
    - else if it is a map, put the ref into the parent
    - else just set the ref at the object path

In order to `check the parent type` you have to use the path in the snapshot, since getRelativePath and getPath will resolve the path to the dereferenced node. I.e. with ```
{ root: 
  { models:
    { model1: { ref1: model2 }
    { model2 }
  }
}
```
the getRelativePath(model1, ref1) will be `'../'` (child of `models`) instead of `''` (child of model1)

**Describe the solution you'd like**
I'd like built-in way to determine that the ref:model2 is in model1

**Are you willing to (attempt) a PR?**
* [x] Yes in the far far future
* [ ] No

**Comment by xaviergonz** [comment]
Doesn't [getRelativePath](https://github.com/mobxjs/mobx-state-tree/blob/master/docs/API/README.md#getrelativepath) work?
If you use it with a reference it as target it will give you the relative path from the base to the referenced object (not the reference itself)

By the way, when you say that references are lost upon cloning, are you talking about references or safeReferences? I see safeReferences dissapearing, but if you use plain references I think they should stay

Another option is to use custom references too https://github.com/mobxjs/mobx-state-tree#customizable-references

**Comment by davidosomething** [comment]
I am using safeReferences so maybe that's the issue with cloning, will investigate that further, but the docs do say references can't be resolved for a node outside of the tree the references are pointing to.

But to your first question, no, getRelativePath returns path to the original item instead of the path to the pointer (i left an example in the first comment)

**Comment by xaviergonz** [comment]
> the docs do say references can't be resolved for a node outside of the tree the references are pointing to

that only applies to non custom references, with custom references you can change the default behaviour to whichever resolution logic you may want

> But to your first question, no, getRelativePath returns path to the original item instead of the path to the pointer (i left an example in the first comment)

ahh, so you want the path to the actual reference node

**Comment by xaviergonz** [comment]
I think it is a good idea, but might be hard to pull off since the reference is already dereferenced (pointing to the original object) as soon as you do store.ref.

For it to work references would need to be dereferenced in a second step (say ref.current like in react), where ref would be the ref node itself and ref.current would be the dereferenced (actual) value.

@mweststrate would changing references to work like this make sense in a next major? or perhaps add a new types.reference2 ?

**Comment by davidosomething** [comment]
still useful to have these features, but i did solve my use-case by just doing:

```
        const selfType = getType(self);
        const draft = selfType.create(); // create blank model with new types.identifier (model generates using `uuid/v1`)

        const snapshot = getSnapshot(self);
        const reidSnapshot = reidentify(snapshot, { withId: draft.id }); // basically replace snaphot.id with draft.id and create new IDs for non-reference child nodes
        reidSnapshot.isDraft = true;

        // Must add the draft node to tree so it can resolve references
        self.draft = draft;
        applySnapshot(draft, reidSnapshot);
```

vs previously where i did `const draft = selfType.create(reidentify(snapshot)); self.draft = draft; // appended new instance to tree too late to resolve refs!`

**Comment by coolsoftwaretyler** [comment]
Hey folks,

This MobX-State-Tree issue is quite old, and it looks like @davidosomething has a suitable workaround. Since there hasn't been further interest, I'm going to close this out.

If anyone wants to implement this, we are always accepting PRs, and I prioritize PR review over my own planned work in the repo, so I promise to help move it forward.

Thanks!
