### ISSUE TITLE
ApplyPatch cannot read property split of undefined

### ISSUE THREAD

**Issue by zek** [mobxjs/mobx-state-tree#1216]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/y64pzxj01

**Describe the expected behavior**
No errors

**Describe the observed behavior**
I cant call applyPatch on root store

Cannot read property 'split' of undefined
splitJsonPath
https://y64pzxj01.codesandbox.io/node_modules/mobx-state-tree/dist/mobx-state-tree.js:3345:22
eval
https://y64pzxj01.codesandbox.io/node_modules/mobx-state-tree/dist/mobx-state-tree.js:1565:29
eval
https://y64pzxj01.codesandbox.io/node_modules/mobx-state-tree/dist/mobx-state-tree.js:1564:21
executeAction$$1
https://y64pzxj01.codesandbox.io/node_modules/mobx/lib/mobx.js:604:22
res
https://y64pzxj01.codesandbox.io/node_modules/mobx/lib/mobx.js:595:16
runMiddleWares
https://y64pzxj01.codesandbox.io/node_modules/mobx-state-tree/dist/mobx-state-tree.js:2342:40
runWithActionContext
https://y64pzxj01.codesandbox.io/node_modules/mobx-state-tree/dist/mobx-state-tree.js:2239:16
ObjectNode.res [as _applyPatches]
https://y64pzxj01.codesandbox.io/node_modules/mobx-state-tree/dist/mobx-state-tree.js:2262:16
ObjectNode.applyPatches
https://y64pzxj01.codesandbox.io/node_modules/mobx-state-tree/dist/mobx-state-tree.js:1298:14
applyPatch
https://y64pzxj01.codesandbox.io/node_modules/mobx-state-tree/dist/mobx-state-tree.js:194:30
evaluate
/index.js:12:11

**Comment by xaviergonz** [comment]
The provided sandbox link just points to the original sandbox...

**Comment by xaviergonz** [comment]
@zek did you find the cause?
