### ISSUE TITLE
Migrating from 2.x.x to 3.x.x

### ISSUE THREAD

**Issue by ssteuteville** [mobxjs/mobx-state-tree#1217]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

Is there a migration guide from 2.x.x to 3.x.x?? Readme seems off because it seems to imply that types.identifier(types.number) still works.

Sorry if I just missed a link to breaking changes somewhere.

**Comment by xaviergonz** [comment]
https://github.com/mobxjs/mobx-state-tree/blob/master/changelog.md#300

**Comment by coolsoftwaretyler** [comment]
I'm gonna close this issue out since it's a few major versions behind and hasn't had activity in years.
