### ISSUE TITLE
[Symbol.iterator], [Symbol.unscopables] missing

### ISSUE THREAD

**Issue by Skyien** [mobxjs/mobx-state-tree#1218]
**_Question_**

* [ ] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

1. I have model "TaskModel" and `export interface ITask extends Instance<typeof TaskModel> {} `
2. Store `tasks: types.optional(types.array(TaskModel), [])`
3. Component UnassignedTasksContainer with props
```
export interface IUnassignedTasksContainerProps {
  tasks: Array<ITask>;
} 
```
4.  `<UnassignedTasksContainer tasks={store.tasks} />`
Type error: Type 'Pick<IMSTArray<IReferenceType<IModelType<ModelPropertiesDeclarationToProperties<{ id: ISimpleType<string>; createdAt: IMaybeNull<IType<number | Date, number, Date>>; updatedAt: IMaybeNull<IType<number | Date, number, Date>>; startedAt: IMaybeNull<...>; ... 22 more ...; customer: IMaybeNull<...>; }>, { ...; }, Extrac...' is missing the following properties from type 'ITask[]': [Symbol.iterator], [Symbol.unscopables]  TS2739

3.11.0 VERSION ONLY

**Comment by xaviergonz** [comment]
What typescript version? 
What's your tsconfig.json like?

I just tried this and it is ok:
```ts
test("MST array type should be assignable to plain array", () => {
    const Todo = types.model({
        done: false,
        name: types.string
    }).actions(self => ({
        toggleDone() {
            self.done = !self.done;
        }
    }))
    const TodoArray = types.array(Todo)
    const todoArray = TodoArray.create([{done: true, name: "todo1"}, {name: "todo2"}]);
    const otherTodoArray: Array<Instance<typeof Todo>> = todoArray;
    otherTodoArray.push(cast({done: false, name: "todo2"}))
})
```

**Comment by jgarces-tw** [comment]
```
export const T = types
  .model({
    a1: types.optional(types.array(types.number), []) // if optional is removed then it works
  })
  .views(self => ({
    get a2(): Array<number> { // if array type casting is removed then it works
      return self.a1;
    },
  }));
```

**Comment by jgarces-tw** [comment]
tsconfig (ts 3.3.3333)
```
{
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es5",
    "lib": ["es2017", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strict": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "baseUrl": ".",
    "downlevelIteration": true
  },
  "include": ["src"]
}

```
