### ISSUE TITLE
Executing actions from views

### ISSUE THREAD

**Issue by Maaartinus** [mobxjs/mobx-state-tree#1227]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

There are a few places, where when computing a view, I find out that some change should be done. My question is simply:

- Should I call `window.timeout(() => doSomeAction(....))`, so that I don't get an error complaining about modifying values already used in a the computation?
- Or should I try hard to detect the condition in the action which causes it?

A related side question: Is there something like `autorun` for MST? I know I can use `mobx.autorun`, but packing it in MST would feel cleaner.

### A lengthy example

Consider this simplified real code
```
.views(self => ({
	get allAsList() {
		const result = {}
		for (let e of self.baseMap.values()) {
			result[e.id] = e
		}
		for (let e of self.overridesMap.values()) {
			const old = result[e.id]
			result[e.id] = e

			// 1. This is what I want
			if (someCondition(old, e)) self.overridesMap.delete(e.id)
			// 2. This is what I tried first (enclosed in an action)
			if (someCondition(old, e)) self.deleteFromOverridesMap(e.id)
			// 3. This is what works
			if (someCondition(old, e)) window.timeout(() => self.deleteFromOverridesMap(e.id))
		}
		return Object.values(result)
	}
)}}
```
- There's the `baseMap` containing entities from the server and the `overridesMap` containing edits by the user.
- When the server returns the edited entity, then it can be removed from the overrides.
- I only detect this in the view as it's the only place, where I use both maps.

**Comment by xaviergonz** [comment]
to be honest, if a view is changing something it is not really a view, so I'd either:
a) change it to an action that returns a value (if the returned value does not need to be observable)
b) separate it into a first action that does the changes then a view that returns the results and make sure to call the first then the other

**Comment by xaviergonz** [comment]
oh, and feel free to use mobx autorun :) mst is totally compatible with mobx

**Comment by Maaartinus** [comment]
@xaviergonz Thanks a lot for your answer, but I've got a much better example now:

In a view, I read a list obtained from the server. Because of the list being in use, I want to refresh it when older than a threshold. This is obviously an action. I guess, something like this
```
.views(self => ({
	get allAsList() {
		if (self.lastFetched < Date.now() - THRESHOLD) {
			window.setTimeout(() => self.doRefresh())
		}
		return list;
	}
}))
```
is broken because of caching as changes of the current time do not get reflected, right?

This looks to me like a common pattern, what's the best way to implement it?

**Comment by xaviergonz** [comment]
Why not
```
// action (probably flow action if async)
refreshIfNeeded() {
  if (self.lastFetched < Date.now() - THRESHOLD) {
    self.doRefresh())
  }
},

// view
get allAsList() { return self.list } // not needed really if all it does is return self.list without any transformations though

// view, but view function (which is not a computed, but accesses an observable)
getUpdatedList() {
  self.refreshIfNeeded()
  return self.allAsList // or self.list if the computed does no transformations
}

// usage
const list = model.getUpdatedList()
```

**Comment by xaviergonz** [comment]
You can even make refreshIfAsync / doRefresh / getUpdatedList asyncs if needed

**Comment by Maaartinus** [comment]
@xaviergonz Thank you. So I simply use a function rather than a property as a view in order to avoid caching (which is still possible in `allAsList` which actually does some work) and I'm done.

Concerning "flow", I'm rather lost. I used it once and found out that I understand nothing of the code the debugger shows. But that's a different story.
