### ISSUE TITLE
Typescript: interface from Instance<typeof Model> format

### ISSUE THREAD

**Issue by random1911** [mobxjs/mobx-state-tree#1228]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

Hi folks!
We have recently started our new project with TS.
We out strategy is having dumb components wrapped in controllers connected to store.
So props in dumb components have to have a similar interface.
I've encountered with a problem: while using interface made from a model with "maybe" types I can't just omit that maybe keys and have to pass key with undefined value with a prop.

So the question: **Is any way to get an interface from the model with optional properties?**

Here is a sample code:
```
import React, {FC} from 'react'
import {types, Instance} from 'mobx-state-tree'

const Model = types.model('myModel', {
  foo: types.string,
  bar: types.maybe(types.string),
})

interface IModel extends Instance<typeof Model> {}

interface IProps {
  myProps: IModel
}

const MyComponent: FC<IProps> = ({myProps}) => {
  const {foo, bar} = myProps
  return (
    <div>
      My foo: {foo}
      {bar && <span>and bar: {bar}</span>}
    </div>
  )
}

const sampleData = {
  foo: 'hello',
  // bar: undefined, // will be fine with that line
}

const MyComponentContext: FC = () => <MyComponent myProps={sampleData} />
// Error:(35, 51) TS2741: Property 'bar' is missing in type '{ foo: string; }' but required in type 'IModel'.
```
Seems like interface looks like
```
interface IGot {
  foo: string,
  bar: string | undefined
}
```
And here is what I want:
```
interface IExpected {
  foo: string,
  bar?: string
}
```

**Comment by xaviergonz** [comment]
Try SnapshotIn<typeof Model> instead

**Comment by random1911** [comment]
`SnapshotIn` is fine for this case, thanks!
