### ISSUE TITLE
Factory pattern with MST

### ISSUE THREAD

**Issue by dfee** [mobxjs/mobx-state-tree#1230]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [x] I tried the [spectrum channel](https://spectrum.chat/mobx-state-tree/general/factory-pattern-with-mst~b3754903-51cc-4232-8cdc-edf33240cb06)

I have a factory pattern that's working... but it requires some unusual type-casting. https://gist.github.com/dfee/6ab59ed0e454f51422a4f0b4e46e9c29

For example:
- it seems impossible to extend IModelType<{ id: SimpleType<string> }, any> with a type that has more properties.
- ReturnType<IMapArray<M>['push']> is ExtractCST<M>... which is peculiar
- ReturnType<IAnyModelType['create']> seems to return ExtractT<M>... which is peculiar

I'm working around these with castings (as documented in the snippet), but i'm curious as to the expected usage here.

**Comment by xaviergonz** [comment]
> it seems impossible to extend IModelType<{ id: SimpleType }, any> with a type that has more properties.

```
const M1 = types.model(....)
// m1 with more props, actions, views...
const M2 = M1.props(....).actions(....).views(...)
```

factory pattern (not sure if you want this though)
```
const Vehicle = types.model(....)...
const Plane = Vehicle.props(...)...
const Car = Vehicle.props(....)...

function factory<T extends "car" | "plane">(type: "car" | "plane"):
T extends "car" ? typeof Car  // or Instance<typeof Car> if returning actual instances
: T extends "plane" ? typeof Plane 
: never {
  if (type === "car") return Car;
  if (type === "plane") return Plane;
}

// alternatively you can just return `typeof Vehicle` or `Instance<typeof Vehicle>` it you don't want it strongly typed from the input arg
```

**Comment by xaviergonz** [comment]
oh, also check the recently released `TypeOfValue<typeof variable>` from 3.12 to get the original type of some variable holding a complex object (array, model, etc)

**Comment by dfee** [comment]
I think you're understanding factory in terms of retrieving a value from a discriminated union of types.

My problem however is creating new ModelTypes in a factory method. psuedo:

```
makeNewModel(additionalModelProperties) => {
  return types.model({ ...standardModalProperties, ...additionalModalProperties});
}
```

At first glance of the problem, it seems like your first solution could be the trick – but it's not. I'm talking about the TypeScript statement `extends` not the JS inheritance pattern provided by  MST – (i.e. `M1.props(...)`).

Here's a basic goal: allow a function to accept any model that has these properties:
```ts
import { types } from 'mobx-state-tree';

const BaseModel = types.model({
  id: types.identifier,
  createdAt: types.Date,
  updatedAt: types.maybe(types.Date),
});

const FooModel = BaseModel.props({
  bar: types.boolean,
})

const acceptsAllBaseModels = <M extends typeof BaseModel>(Model: M) => {
  return Model;
}

// FooModel is invalid!
acceptsAllBaseModels(FooModel);
```

**Comment by dfee** [comment]
@xaviergonz just pinging you again on this. It came up in a discussion again over the weekend on Spectrum (but on a different issue, that I probably ought to file a question here for).

My goal is to produce models: `Foo`, `FooQuery` and `FooCollection` through a factory. In addition, I'd like to produce `Bar` and friends, `Baz` and friends, etc.

The challenge I ran into (and am working around via casts), is with functions that accept one of these factory generated models. My functions are generic, but I need to limit them to (via `myFunction<T extends ...>`) to extend from an object that has a base set of methods (i.e. `id`, `createdAt`).

Of course I could just duplicate code 50x, but that's not an approach I'd like to take :).

**Comment by kresli** [comment]
> I'm talking about the TypeScript statement extends not the JS inheritance pattern provided by MST – (i.e. M1.props(...)).

Its not possible to use inheritance because there is none. However you can cheat but I wouldn't :D This is more for fun then actual usage but here we go
```typescript
const A = types.model({}).volatile(self => ({
  __A: true
}));

const B = A.props({}).volatile(self => ({
  __B: true
}));

const C = B.props({}).volatile(self => ({
  __C: true
}));

const acceptsAllBaseModels = <M extends IAnyModelType>(
  Model: ExtractOthers<M> extends { __A: boolean } ? M : never
) => {
  return Model;
};

acceptsAllBaseModels(B) // <-- pass
acceptsAllBaseModels(types.model({})) // <-- fail
```

**Comment by dfee** [comment]
@kresli interesting. I see it as being for actual usage, though. (despite the fact that I'm interested in `ExtractProps` which ccomes from `mobx-state-tree/dist/internal`.

The big challenge I'm seeing with MST is that there aren't any conventions for generating code (i.e. factories). Well, we can generate code, but it's impossible to describe generics of this code elsewhere as important types like `ExtractProps` and `ExtractOthers` are hidden as internal types (and undocumented).

**Comment by dfee** [comment]
@kresli here is an example of how i'm failing:

```ts
export const modelFactory = <P extends ModelPropertiesDeclaration>(
  name: string,
  props: P,
) =>
  types.model(name, {
    id: types.identifier,
    createdAt: types.Date,
    updatedAt: types.maybe(types.Date),
    ...props,
  });

export type BaseModelType<T extends IAnyModelType> = ExtractProps<T> extends {
  id: ISimpleType<string>;
  createdAt: typeof types.Date;
  updatedAt: IMaybe<typeof types.Date>;
}
  ? T
  : never;

const acceptsAllBaseInstances = <M extends IAnyModelType>(
  model: M extends BaseModelType<M> ? Instance<M> : never,
) => {
  return model.id; // infers`id` as type: any...
};

const Bad = types.model("Y", { uid: types.identifier });
const bad = Bad.create({ uid: "0" });

const Good = modelFactory("Z", {});
const good = Good.create({ id: "0", createdAt: 0 });

// ... cannot infer the type from the parameter `model`.
const badId = acceptsAllBaseInstances<typeof Bad>(bad); // <-- fail
const goodId = acceptsAllBaseInstances<typeof Good>(good); // <-- pass, but type is: any.

```

**Comment by kresli** [comment]
@dfee that's only because you missing return type on `acceptsAllBaseInstances`.

**Comment by dfee** [comment]
@kresli well sure, I could manually type `id` as having a return type of `string`, but the problem is that I'm having to type something that could / should be inferred. The consequence being that I'm losing type safety (TypeScript infers it as `any`).

**Comment by kresli** [comment]
```typescript 
export const modelFactory = <P extends ModelPropertiesDeclaration>(
  name: string,
  props: P
) =>
  types.model(name, {
    id: types.identifier,
    createdAt: types.Date,
    updatedAt: types.maybe(types.Date),
    ...props
  });

const acceptsAllBaseInstances = <
  M extends Instance<ReturnType<typeof modelFactory>>
>(
  model: M
) => {
  return model.id; // infers`id` as type: any...
};

const Bad = types.model("Y", { uid: types.identifier });
const bad = Bad.create({ uid: "0" });

const Good = modelFactory("Z", {});
const good = Good.create({ id: "0", createdAt: 0 });

// ... cannot infer the type from the parameter `model`.
const badId = acceptsAllBaseInstances(bad); // <-- fail
const goodId = acceptsAllBaseInstances(good); // <-- string
```

**Comment by dfee** [comment]
Alright, @kresli sorry for changing the goalpost on you. But getting back to your original implementation, that code actually fails – when the code is further modified.

in the example below i've:
1) added User (which is created via `modelFactory()`)
2) has extra props (`firstName` and `lastName`)
3) has a view (`displayName`).

The `acceptsAllInstances` still passes, but `acceptsAllBases` now fails (due to the addition of `displayName` as a view).

```ts
import { Instance, ModelPropertiesDeclaration, types } from "mobx-state-tree";

export const modelFactory = <P extends ModelPropertiesDeclaration>(
  name: string,
  props: P,
) =>
  types.model(name, {
    id: types.identifier,
    createdAt: types.Date,
    updatedAt: types.maybe(types.Date),
    ...props,
  });

const acceptsAllBaseTypes = <
  M extends ReturnType<typeof modelFactory>
>(
  Model: M,
) => {
  return Model
};

const acceptsAllBaseInstances = <
  M extends Instance<ReturnType<typeof modelFactory>>
>(
  model: M,
) => {
  return model.id;
};

const Bad = types.model("Bad", { uid: types.identifier });
const bad = Bad.create({ uid: "bad-0" });

const Good = modelFactory("Good", {});
const good = Good.create({ id: "good-0", createdAt: 0 });

const User = modelFactory("User", {
  firstName: types.string,
  lastName: types.string,
}).views(self => ({
  get displayName() {
    return `${self.firstName} ${self.lastName}`;
  },
}));
const user = User.create({
  id: "user-0",
  createdAt: 0,
  firstName: "Steve",
  lastName: "Irwin",
});

const isBad = acceptsAllBaseTypes(Bad); // <-- fail
const isGood = acceptsAllBaseTypes(Good); // <-- string
const isUser = acceptsAllBaseTypes(User); // <-- string

// const badId = acceptsAllBaseInstances(bad); // <-- fail
const goodId = acceptsAllBaseInstances(good); // <-- string
const userId = acceptsAllBaseInstances(user); // <-- string
```

**Comment by kresli** [comment]
No worries, happy to help. However I think we should move to spectrum with further discussion. Its not really an issue on MST side but approach to make it work. Link the spectrum link here just in case others would have similar question

**Comment by dfee** [comment]
Here's a link to the chat: https://spectrum.chat/mobx-state-tree/general/factory-pattern-with-mst~0496904e-d779-4096-9e88-a8ed642015e2

**Comment by xaviergonz** [comment]
I just want to add that if you think some types should be publicly exposed (e.g. ExtractProps) feel free to say so and they can be made public (probably with other name though :) )
