### ISSUE TITLE
getEnv broken since 3.12.0 when using container store

### ISSUE THREAD

**Issue by IngoValente** [mobxjs/mobx-state-tree#1231]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/pwyyz765qm

**Describe the expected behavior**
Using a slightly modified version of the dependency injection (https://github.com/mobxjs/mobx-state-tree#dependency-injection) example code from readme, I expect to see the changed title logged to console.

**Describe the observed behavior**
When running the code with MST version 3.12.0, the stores don't get the parent's stores environment, and it throws an error ```TypeError: _mobxStateTree.getEnv(...).logger is undefined```, because getEnv(self) return an empty object instead of an object containing the passed logger function.
When downgrading to 3.11.0, everything works as expected.
This only happens when using a 'container' store, using a single store works as expected.

**Comment by xaviergonz** [comment]
Will check it out later, thanks!

**Comment by ssteuteville** [comment]
Also happening to me. I debugged the tree and I'm noticing that the environment is not on all tree nodes.

store -> ui store -> ui model 1 -> ui model 2 -> array -> ui model 3

The environment is undefined at depth 3 and down.

**Comment by xaviergonz** [comment]
fixed in 3.12.1
