### ISSUE TITLE
volatile properties behave differently to "normal" properties

### ISSUE THREAD

**Issue by stoefln** [mobxjs/mobx-state-tree#1232]
**_Question_**
* [x] I've checked documentation and searched for existing issues
* [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

Hi there,

recently I figured that when I move a property from the `model` section to the `volatile` section of a type definition, the type of the property changes.
searching the web I figured that people tend to not use MST types for volatile properties, even though it would be great to have them (type safety, observability).
I wonder that I didn't find anything related to this restriction in the official docs. 

Or to rephrase the question: Is there a way to avoid persisting, but get all the benefits of MST model properties?

**Comment by xaviergonz** [comment]
> recently I figured that when I move a property from the model section to the volatile section of a type definition, the type of the property changes.

do you mind posting in code what you mean? I don't quite follow

**Comment by stoefln** [comment]
> do you mind posting in code what you mean? I don't quite follow

```
RecordingPlayer = types
  .model('RecordingPlayer', {
    actionGhosts: types.array(ActionGhost),
  })
  .volatile(self => ({
    
  }))
```
results in `recordingPlayer.actionGhosts` being of type `IMSTArray<IModelType<...`


```
RecordingPlayer = types
  .model('RecordingPlayer', {
    // some props here
  })
  .volatile(self => ({
    actionGhosts: types.array(ActionGhost),
  }))
```
results in `recordingPlayer.actionGhosts` being of type `IArrayType<IModelType<...`

**Comment by xaviergonz** [comment]
Why not
```
RecordingPlayer = types
  .model('RecordingPlayer', {
    // some props here
  })
  .volatile(self => ({
    // this will be a MST array, but hidden from the parent, you forgot the create()
    actionGhosts: types.array(ActionGhost).create(),
  }))
```

**Comment by xaviergonz** [comment]
Alternatively you can use `types.snapshotProcessor`

```
const RecordingPlayer = types.snapshotProcessor(types
  .model('RecordingPlayer', {
    // some props here
    actionGhosts: types.array(ActionGhost),
  }), {
    // from snapshot to instance
    preProcessor(sn) {
        return {
            ...sn,
            actionGhosts: undefined
        }
    },
    // from instance to snapshot
    postProcessor(sn) {
        return {
            ...sn,
            actionGhosts: undefined
        }
    });
```

**Comment by stoefln** [comment]
@xaviergonz and why do I need to call create() for volatile properties and not when the property is defined inside `model`?
Is this documented somewhere?

**Comment by xaviergonz** [comment]
no, I think you were the first to do that :)

basically volatile expects real variables, (a real string, a real array, etc), so the way to create a "real variable" out of a type is to call create on the type.

**Comment by stoefln** [comment]
Thanks a lot @xaviergonz. Is there another way to create observable non-persisting array-props in my model or is this the way to go?

**Comment by stoefln** [comment]
Because I tried creating an array via `actionGhosts: []` and it wasn't observable.

**Comment by xaviergonz** [comment]
you can alwasy do actionGhosts: observable([]) if all you want is to make the array observable without any MST enhanced stuff

**Comment by xaviergonz** [comment]
That being said, volatile should make anything you pass to it observable

**Comment by stoefln** [comment]
@xaviergonz then I wonder why I don't get any reactions (react render calls) from 
```
RecordingPlayer = types
  .model('RecordingPlayer', {
    // some props here
  })
  .volatile(self => ({
    actionGhosts: []
  }))```

**Comment by stoefln** [comment]
BTW: 
I am using mobx 4.9.1 and MST 3.10.1

**Comment by xaviergonz** [comment]
hmm, it should, can you make a minimal reproduction on the sandbox?
