### ISSUE TITLE
types.maybe vs types.maybeNull

### ISSUE THREAD

**Issue by Maaartinus** [mobxjs/mobx-state-tree#1242]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

According to https://mobx-state-tree.gitbook.io/docs/api#types-maybe,
```
types.maybe(types.string)
```
should be the same as
```
types.optional(types.union(types.string, types.literal(null)), null),
```
but it is not as I got an exception like "null is not assignable to string" with the former, while the latter works. I guess, there's a version mismatch or such a triviality. I'm using `"mobx-state-tree": {"version": "3.10.2", ....` with javascript.

Anyway, it'd nice if the information about the version were obvious from the documentation. I've really tried to find it.

**Comment by kresli** [comment]
Actually types.maybe resolve to `types.optional(types.union(type, types.literal(undefined)), undefined)` as per docs https://github.com/mobxjs/mobx-state-tree#utility-types

**Comment by kresli** [comment]
there is difference between `types.maybe` and `types.maybeNull`

**Comment by Maaartinus** [comment]
Thank you both. I'm leaving this open for someone capable of updating the gitbook.
