### ISSUE TITLE
TypeScript error: Type instantiation is excessively deep and possibly infinite. TS2589

### ISSUE THREAD

**Issue by benkuly** [mobxjs/mobx-state-tree#1247]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x]  I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction.

**Sandbox link or minimal reproduction code**

https://github.com/benkuly/mst-issue-ts2589

**Describe the expected behavior**

I defined the mst-model in a seperate/shared project (in the example it is named "common").
Now I want to use it in another project (in the example it is named "client").

This already works, if I define the mst-model in the same project.

**Describe the observed behavior**

The "common" project compiles without errors, but I get `TypeScript error: Type instantiation is excessively deep and possibly infinite. TS2589` when I want to compile the "client" project.
It seems to be related with the generated declaration files in the "common" project

Thanks for your help!

**Comment by xaviergonz** [comment]
Should be fixed in v3.14.0

**Comment by benkuly** [comment]
Very cool! Thank you! :-)
