### ISSUE TITLE
Identifier inside optional is generating the same id for multiple instances

### ISSUE THREAD

**Issue by juanmiret** [mobxjs/mobx-state-tree#1248]
**_Bug report_**

* [ x ] I've checked documentation and searched for existing issues
* [ x ] I've made sure my project is based on the latest MST version
* [ x  ] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/l44wxqkxzq?fontsize=14

I have a model like this:

const Box = types.model("Box", {
  id: types.optional(types.identifier, uuid()),
  name: types.string
})

When I create two different instances of that model, the same uuid() is being applied to both, you can see that in the Codesandbox

const box1 = Box.create({ name: "Box 1" })
const box2 = Box.create({ name: "Box 2" })

**Describe the expected behavior**
As I didn't provide any id value at the creation of the instance, I expect that each time I create a model it calls uuid() in the optional type and generate a new value.

**Describe the observed behavior**
box1.id // 123456
box2.id // 123456, same as box1

**Comment by xaviergonz** [comment]
Use an arrow function if you want a changing default ` types.optional(types.identifier, () => uuid())`

**Comment by juanmiret** [comment]
That did it! Thanks @xaviergonz 

Do you think I should submit a PR to the docs?

**Comment by xaviergonz** [comment]
Feel free to send a PR to improve them :) It is mentioned however

> types.optional(type, defaultValue, optionalValues?) marks an value as being optional (in e.g. a model). If a value is not provided/undefined (or set to any of the primitive values passed as an optional optionalValues array) the defaultValue will be used instead. If defaultValue is a function, it will be evaluated. This can be used to generate, for example, IDs or timestamps upon creation.
