### ISSUE TITLE
Update a model in multiple arrays

### ISSUE THREAD

**Issue by ataravati** [mobxjs/mobx-state-tree#1249]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

I have a model that has multiple arrays of the same type. 

```javascript
export const Product = types
  .model("Product", {
    product_id: types.string,
    product_name: types.string,
    category: types.string,
    selected: types.boolean,
  }));

const ProductStoreModel = types
  .model("ProductStore", {
    isLoading: types.boolean,
    categoryProducts: types.array(Product),
    selectedProducts: types.array(Product),
    searchResult: types.array(Product),
  })
  .actions(self => ({
    fetchCategoryProducts: flow(function*(category: string) {
      self.isLoading = true;
      self.categoryProducts = yield database.getProductsByCategory(category);
      self.isLoading = false;
    }),
    fetchSelectedProducts: flow(function*() {
      self.isLoading = true;
      self.selectedProducts = yield database.getSelectedProducts();
      self.isLoading = false;
    }),
    search: flow(function*(text: string) {
      self.isLoading = true;
      self.searchResult = yield database.searchProducts(text);
      self.isLoading = false;
    }),
  }));
```

How do I make sure when I updated a Product it gets updated in all these arrays? Let's say a Product is selected. I need to make sure that the Product is added to the `selectedProducts`, and also its `selected` property is set to `true` on all the other arrays, in case the Product already exists in any of those arrays.

**Comment by xaviergonz** [comment]
I'd make a single array of products, then an array of safe references for selected products and another one for search

Another alternative (if you want to keep a selected and insideSearch attribute inside product) is to have an array of products and then one view for selected that filters through products with selected set to true and another for search that filters by insideSearch set to true

**Comment by ataravati** [comment]
@xaviergonz I can’t do that, because the single `products` will be too big. I can’t fetch all products from the database at once.

**Comment by kresli** [comment]
> @xaviergonz I can’t do that, because the single products array will be too big. I can’t fetch all products from the database at once.

then don't fetch all at once. Its not really about what you fetch but where you'll save the payload. As @xaviergonz suggested, use single products array. Well, actually change array to map so you can easily add new products by id.

**Comment by ataravati** [comment]
OK, got it. Thank you, both! @xaviergonz @kresli
