### ISSUE TITLE
types.object

### ISSUE THREAD

**Issue by alexvcasillas** [mobxjs/mobx-state-tree#125]
Hello, @mweststrate 
I open this issue because I've found something interesting that might be useful when working with **mob-state-tree**. That, is the `types.object` type.

As we where talking at Twitter, you said that I could use a `types.frozen` to create an observable object that might change the amount of keys that could contain (sometimes, depending on the API response, I could get 10, 12 or even an very different number). But using the `types.frozen` name for this purpose it's a little bit confusing because I (at least myself) tend to associate the word *frozen* with other stuff but an object, for example, when running some immutability test and you "froze" your data. That's why I don't find very intuitive this word, I think we should think in adding some `types.object` type to make this approach of observable objects more clear and intuitive.

I also share with you a link to a Gist where I made the migration of my #3RMXi Github Asyncrhonous Fetch demo from mobx to mobx-state-tree so you can see this in a more clear way.

[https://gist.github.com/alexvcasillas/5c312088a76dfa9023cb749c34cc1ce7](https://gist.github.com/alexvcasillas/5c312088a76dfa9023cb749c34cc1ce7)

Plus another question I don't have very clear is: can I use runInAction with mobx-state-tree as I did in the first place with the mobx regular style of asynchronous fetching? I'm not sure the mobx-state-tree of creating `async fetchFunction(){}` will work...

Hope you find this useful and could make mobx-state-tree even better.

Thanks!

**Comment by mattiamanzati** [comment]
Hello @alexvcasillas!
Frozen is named so due to how the provided value will be frozen. In your example, user gets never changed, and that's why it's frozen. It works exactly how Object.freeze does :)

```javascript
// plain javascript
const store = { user: null }
const user = Object.freeze({ name: 'Mattia' })
store.user = user // this is legal, and that's what MST does
user.name = 'Michel' // illegal! 
// the same happens on mobx-state-tree
const Store = t.model({ user: t.frozen })
const User = t.mode({ name: t.string })

const gitStore = Store.create()
gitStore.user = User.create({name: 'mattia' }) // this is legal!
gitStore.user.name = 'Michel' // illegal!
```
That's exacly why frozen accepts any kind of value, with any kind of keys. That's basically because if a value is provided, MST won't be able to track inner changes (e.g.cname property changed) but only reference changes (e.g. gitStore.user changed from null to something).

**Comment by alexvcasillas** [comment]
Oh, thanks for the answer @mattiamanzati : )

So, if I want that object to change in some point of the state of the app, should I create a model just to achieve this or triggering an action to modify the `gitStore.user.name` will just work fine? Because in the example, the user won't be modified but, in many other cases I'll have values that could be present or not, like in plan mobx the fields/keys you add after creating an object without `extendObservable` but with `observable` wont be observed. Does the `type.frozen` will work as an `extendObservable` like in mobx?

Just wondering : )

Thanks again for the answer!

**Comment by mattiamanzati** [comment]
If you want to change that user.name field you can drop that object and create a new modified one (like redux does with reducers).
You could also use `types.extend` to create a new user type with the additional fields, then getSnapshot from the old user and applySnapshot to the new user type.

```
const OldUser = t.model({ name: t.string })
const user = OldUser.create({ name: 'Mattia' })
const NewUser = t.extend(OldUser, t.model({ surname: t.string })
const newUser = NewUser.create(getSnapshot(user))
```

Notice that this will change the User type as well. So if you have a list of User, for example, you need to change that as well to a list of NewUser.

**Comment by alexvcasillas** [comment]
Ok, got it!

Thanks again @mattiamanzati :)
