### ISSUE TITLE
Typescript: property not recognized.

### ISSUE THREAD

**Issue by danfma** [mobxjs/mobx-state-tree#1252]
I tried to use `mobx-state-tree` with TypeScript and I`m receiving an error:

```
Property 'name' does not exist on type 'IStateTreeNode<IModelType<ModelPropertiesDeclarationToProperties<{ name: string; surname: string; email: string; emailConfirmation: string; password: string; passwordConfirmation: string; gender: "Male" | "Female"; }>, {}, _NotCustomized, _NotCustomized>>'.ts(2339)
```

![image](https://user-images.githubusercontent.com/101121/55675005-82890c80-5892-11e9-8091-7859e5700b0a.png)

**_Bug report_**

* [x] I've checked the documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [ ] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
* https://stackblitz.com/edit/typescript-wuzjvc

**Describe the expected behavior**
* I should be able to use the defined properties in the model.

**Describe the observed behavior**
* There is a typing error which doesn't allow the defined properties to be recognized by methods like `actions` and `views`.

**Comment by xaviergonz** [comment]
Not sure what's wrong with stackblitz, the very same code works ok on vscode

Using this tsconfig.json btw, if it helps
```
{
    "compilerOptions": {
        "target": "es5",
        "sourceMap": false,
        "declaration": true,
        "module": "es2015",
        "removeComments": false,
        "moduleResolution": "node",
        "experimentalDecorators": true,
        "strict": true,
        "strictNullChecks": true,
        "strictFunctionTypes": true,
        "noImplicitAny": true,
        "noFallthroughCasesInSwitch": true,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "downlevelIteration": true,
        "lib": ["es6"]
    }
}

```

**Comment by danfma** [comment]
Yeah, I just realized that my code is using an old typescript version. I will close the issue.
