### ISSUE TITLE
Inferring intersected IModelType results with the first provided type

### ISSUE THREAD

**Issue by kresli** [mobxjs/mobx-state-tree#1255]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [ ] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

```typescript
type M = IModelType<
  {},
  {
    $controller: boolean;
  }
> &
  IModelType<
    {},
    {
      $controller: number;
    }
  >;

type N = M extends IModelType<any, infer U, any, any> ? U : never;
```
**Describe the expected behavior**

```typescript
type N = {
    $controller: boolean;
} & {
    $controller: number;
}
```

**Describe the observed behavior**

```
type N = {
    $controller: number;
}
```

**Comment by xaviergonz** [comment]
you could just do the and over the inner generic
```
type M = IModelType<
    {},
    {
        $controller: boolean;
    } & {
        $controller: number;
    }
> 
type N = M extends IModelType<any, infer U, any, any> ? U : never;
// that ^ is the expected one
```

**Comment by kresli** [comment]
Thanks, not sure what you mean but I just updated to 3.14.0 and all works as expected. Thanks
