### ISSUE TITLE
"Invalid action path" error with precompiled typescript module

### ISSUE THREAD

**Issue by benkuly** [mobxjs/mobx-state-tree#1257]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**

https://github.com/benkuly/mst-issue-1257

**Describe the expected behavior**

When I extract a very simple action with onAction and apply this action with applyAction I should not get an error.

**Describe the observed behavior**

I think due to [this issue of typescript](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work) [that line](https://github.com/mobxjs/mobx-state-tree/blob/dbd37ca2aff483ac7f632dc4d2f89a94a0cffaec/packages/mobx-state-tree/src/core/node/node-utils.ts#L186) returns false instead of true and I get "Invalid action path:" error.
This only appears, if e.g. a common repo, which contains the store definition is precompiled to commonjs and used in another repo. It works, when it is not precompiled and used directly.

**Comment by xaviergonz** [comment]
Could you post some code that exhibits the error?

**Comment by benkuly** [comment]
I updated the first post with a link to minimal repo.

**Comment by xaviergonz** [comment]
It seems to be because the common bundle.js is bundling its own version of mobx-state-tree, while the server one is bundling its own one as well.

Try adding this to your common webpack config
```
  externals: {
    "mobx-state-tree": {
      commonjs: "mobx-state-tree"
    },
    "mobx": {
      commonjs: "mobx"
    }
  },
```

that way the common bundle will keep the "require" for both libraries and therefore use the ones bundled in mobx-state-tree

**Comment by xaviergonz** [comment]
That being said, there could be changed made to warn/give an error when two or more mst instances are found I guess...

**Comment by benkuly** [comment]
Thanks! Added this lines to webpack config, but nothing changed - same error :/

**Comment by xaviergonz** [comment]
That's strange, it worked for me. 
Does your webpack.config.js in packages/common look like this?
```js
module.exports = {
  mode: "development",
  devtool: "inline-source-map",
  entry: "./src/index.ts",
  externals: ["mobx-state-tree"],
  output: {
    filename: "bundle.js",
    libraryTarget: "commonjs"
  },
  resolve: {
    extensions: [".ts", ".js"]
  },
  module: {
    rules: [
      // all files with a `.ts` extension will be handled by `ts-loader`
      { test: /\.ts?$/, loader: "ts-loader" }
    ]
  }
};
```

**Comment by benkuly** [comment]
Exactly. Also commited to the repo from the first post.

**Comment by benkuly** [comment]
Sorry, works now after I removed node_modules directories.
Thank you very much :-)
