### ISSUE TITLE
I cannot assign the value to the store when my statements are more than 7? 

### ISSUE THREAD

**Issue by yanlee26** [mobxjs/mobx-state-tree#1258]
`
self.isEmpty = false; 
        self.details.register_time = res.register_time; 
        self.details.nickname = res.nickname; 
        self.details.login = res.login; 
        self.details.avatar = res.avatar;
        self.details.mobile = res.mobile;
        console.log(res);//it prints well
        self.details.weChat_nickname = res.weChat_nickname;
`
While...
`
self.isEmpty = false; 
        self.details.register_time = res.register_time; 
        self.details.nickname = res.nickname; 
        self.details.login = res.login; 
        self.details.avatar = res.avatar;
        self.details.mobile = res.mobile;
        self.details.weChat_nickname = res.weChat_nickname;
        console.log(res);//it doesnot work !!!
`

**Comment by xaviergonz** [comment]
I'm sorry, but I don't get what you mean...
