### ISSUE TITLE
remove dead references before getSnapshot

### ISSUE THREAD

**Issue by davidosomething** [mobxjs/mobx-state-tree#1259]
I think there were plans for a `safeReferenceArray` type? What happened to that?

Right now in a model:

```js
a = types.model({
  items: types.array(types.safeReference(item))
})
```

If you `x = item; destroy(x)` for an item referenced in `items`, it is only marked as dead.

`getSnapshot` intentionally gets the last created snapshot so it will still have `items.filter((i) => i === x.id)` in it

The way to get around it is to 

```
          walk(self, (node) => {
            if (!isAlive(node)) {
              destroy(node);
            }
          });
```

right before you do a `getSnapshot`... unless there's something I'm missing

**Comment by xaviergonz** [comment]
just got merged, will be released eventually

https://github.com/mobxjs/mobx-state-tree/pull/1245

However I'm not sure if that would fix it and that might be a different bug, could you post a minimal code reproduction?

**Comment by davidosomething** [comment]
turns out it was because i had a stale `useMemo` hook -- a memoized model is not the same as the original
