### ISSUE TITLE
optimistic actions

### ISSUE THREAD

**Issue by robinfehr** [mobxjs/mobx-state-tree#126]
quickly started scanning the code base since  i want to / have to implement something like redux-optimistic which means that i want to reduce snapshots for example to have a final state that does not contain all actions and therefore previous states that led to the final state: e.g. moving the box around (i'd invoke actions marked with an optimistic flag) and at the moment of stopping to drag all previous actions marked as optimistic would get reverted and only the last action would be applied. like this we could make the time traveling if exposed to the end user more natural.

and yes of course i could do that with the internal state of the react component but if I want to add a middleware to onAction for example to log all movements in between and have the above described behaviour - i kind of see not another way around. 

in redux this would be a wrapper around a reducer but i guess within the state-tree we could make this action based.

so now the question before i start digging into the code with false assumptions: 
is there something like that planned / implemented already?

**Comment by mweststrate** [comment]
Not something planned specifically, but I think I would just clone a relevant part of the tree (`clone` can, like all other operations, be invoked on any node in the tree), start a action recorder on that clone, and in the end apply the changes back. Does that make sense? Something like:

```javascript
import { clone, recordActions } from "mobx-state-tree"

const tempStore = clone(store)
const recorder = recordActions(tempStore)

//...pass the tempStore to your components instead of the real store (or the relevant part of the tree)
// And upon commit...

recorder.replay(store)
```

**Comment by mattiamanzati** [comment]
I did that a while ago using patches, this is a small gist using the old MST syntax, you can fallow down the lines what it does. Patches are stored in a proper array, and you can play with that to obtain optimistic trees :)
https://gist.github.com/mattiamanzati/b4e6c469045d9bb5d67c2b01cabc1fbe#file-index-ts-L48

**Comment by robinfehr** [comment]
@mweststrate , @mattiamanzati thanks - i'll go have a look at it :)

**Comment by robinfehr** [comment]
as far as i've seen u kept track of the patches but never had to reduce them. what i'm looking for is a property on the patch that would indicate whether the patch is optimistic or not - whether i have to save them or not to later be able to build a snapshot for the time traveling from the saved patches.

since i dont know the code in its full beauty maybe u know a workaround?

adding a property to the model would help solving that but i actually don't want it (the optimistic prop) when serializing. maybe a type wrapper like types.maybe could help?
