### ISSUE TITLE
How to remove a reference from an array of refferences from another model?

### ISSUE THREAD

**Issue by Relaxe111** [mobxjs/mobx-state-tree#1261]
Question. 
How can i remove a reference of a model from an array of references like is shown in example above?
model: 
```
types.model("some_model",{
     ....
    participants: types.array(types.reference(User))
}).actions(self=>({
     removeParticipant(i){
        destroy(self.participants[i]) // is not working
       //or
       delete self.participants[i] // is not working

    }
}))
```
in my removeParticipant i pass position of the reference in the array but i can pass whole referenced model either.
Any help is highly apreciated.

**Comment by xaviergonz** [comment]
If you mean to remove the reference without removing the original then self.participants.splice(i, 1) should do
