### ISSUE TITLE
Type mismatch when using “types.reference” with Typescript

### ISSUE THREAD

**Issue by vladlavrik** [mobxjs/mobx-state-tree#1268]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/09q10597w

**Minimal reproduction code:**
```js
import { types } from "mobx-state-tree";

export const Book = types.model({
  id: types.identifier
});

export const BooksStore = types.model({
  // Exception only if uses "types.reference"
  books: types.array(types.reference(Book))
});

export const RootStore = types.model({
  booksStore: BooksStore
});

const booksStore = BooksStore.create({ books: [] });

// TS Exception here
const rootStore = RootStore.create({ booksStore });
```

Looks like a closed issue: https://github.com/mobxjs/mobx-state-tree/issues/994

**Comment by xaviergonz** [comment]
Thanks, should be fixed once the PR is merged and released as a new version

**Comment by xaviergonz** [comment]
Actually upon further investigation you have to use "castToSnapshot" when using instances as snapshots

e.g.

```ts
test("#1268", () => {
    const Book = types.model({
        id: types.identifier
    })

    const BooksStore = types.model({
        books: types.array(types.reference(Book))
    })

    const RootStore = types.model({
        booksStore: BooksStore
    })

    const booksStore = BooksStore.create({ books: [] })

    const rootStore = RootStore.create({ booksStore: castToSnapshot(booksStore) })
})
```

another option (recommended actually) is to not use instances when instantiating snapshots if possible
```
    const booksStoreSn: SnapshotIn<typeof BooksStore> = {books: []}
    const rootStore = RootStore.create({ booksStore: booksStoreSn })

    // or
    const rootStore = RootStore.create({ booksStore: { books: [] } })

```

**Comment by xaviergonz** [comment]
As a rule of thumb, when trying to use an snapshot where an instance would be required use `cast`
When trying to use an instance when an snapshot would be required use `castToSnapshot`

**Comment by vladlavrik** [comment]
Thanks so much for the solution.🙏
You are right it is only a wrong usage.
I think I can close the issue.
