### ISSUE TITLE
Logo contest!  🌳]v[🌳

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#127]
Until may 17th ;-)

**Comment by mweststrate** [comment]
First attempt
![logo_idea](https://cloud.githubusercontent.com/assets/1820292/26018900/1a492828-3772-11e7-96bb-631f52270c4b.png)

**Comment by rossipedia** [comment]
]🌳[ 

🤷‍♂️

j/k... I'll see if I can't whip up something a bit more serious

**Comment by ndelangen** [comment]
Definitely needs more colour!

Maybe some combo of this:
![](https://mobx.js.org/docs/mobx.png)
![](https://s-media-cache-ak0.pinimg.com/originals/c7/a5/c9/c7a5c9e9f82aca48826d9a5e0ad5f604.jpg)

**Comment by d4rky-pl** [comment]
![mobx-state-tree](https://cloud.githubusercontent.com/assets/284395/26023395/cf50eed4-37ba-11e7-9700-5e38e4af8ed6.png)

**Comment by mweststrate** [comment]
For source files of the mobx logo: https://github.com/mobxjs/mobx/tree/gh-pages/images

**Comment by robinfehr** [comment]
![fir_logo_white](https://cloud.githubusercontent.com/assets/6340698/26024402/2954e520-37d9-11e7-942f-15e09e0ed085.png)

**Comment by steve8708** [comment]
Couple quick ideas, open to feedback if anyone finds this direction appealing!

![mobx logo](https://cloud.githubusercontent.com/assets/844291/26080146/14642aca-397a-11e7-93c9-1708a493d187.png)

Big fan of this project, glad I found this issue before the 17th!

**Comment by hampusohlsson** [comment]
Took a stab at it!

![mobx-state-tree](https://cloud.githubusercontent.com/assets/675092/26089303/a09ea682-39ca-11e7-8278-472c26b51e18.png)

**Comment by rossipedia** [comment]
@steve8708's version with the integrated `mobx` logo is 🔥

**Comment by RainerAtSpirit** [comment]
@steve8708 love the core idea, but currently that reminds me more of a flower than a tree. Unfortunately I have no graphical talent whatsoever to spin that idea forward :)

**Comment by steve8708** [comment]
@RainerAtSpirit totally fair point, thank you for the feedback!

Just made one more variation that I think should help with the tree vs flower distinction, added to the bottom of my original post

**Comment by mattiamanzati** [comment]
@steve8708 I literally love the last variation!!

**Comment by steve8708** [comment]
@mweststrate if you want to move forward with the logo that I put in here I'm happy to make a PR with the source files (ai or sketch) and rendered png. 

Looks like we may be going with @robinfehr 's logo though judging by recent commits? But perhaps I didn't follow up here as maybe I should have, if that is the case just lmk!

**Comment by mweststrate** [comment]
Argh, posted comment yesterday but got lost somehow. 

Anyway, the gist of it; in this issue yours was more popular, on twitter the orange one. So still had to "random" pick one before the talk. Although yours is more recognizable, the orange logo felt more modern to me personally. So that is why I picked that one.

But since there is no 1.0 yet, it should have not too much impact to change it if the community feels strongly about a different outcome :)

**Comment by steve8708** [comment]
I see, no worries

**Comment by sagar-vashishta** [comment]
@mweststrate sorry, but the logo you picked sucks. it looks like a low-end snowboard company pretending to be airbnb and i'd personally go out of my way to avoid using any open source code which proudly boasts that as their logo.

**Comment by mweststrate** [comment]
@sagar-vashishta If your decision for a package is based on its logo, then the best advice I can give you is: Don't use MST. Use bower instead, it has a pretty great logo :). 

Beyond that, as said, it was based on a draw and hasty decision 1 hour before a talk; so I have no problem changing it if people feel strongly about it. No legal implications afaik ;-)

**Comment by RainerAtSpirit** [comment]
First of all it's great to see that multiple people took their time and effort to contribute to the logo contest. Now that we had the luxury to pick one let's move on and concentrate on the making the documentation better.

**Comment by luisherranz** [comment]
I really like @robinfehr logo. It looks professional. If something, I'd change the colours and add the trunk so it looks more like a real tree (but a very distinctive one).
![mst](https://cloud.githubusercontent.com/assets/3305402/26446035/ca5bdc86-4142-11e7-901f-be1221e048d2.png)

**Comment by rossipedia** [comment]
another take on @steve8708 's version, although it might be a bit too busy:

![state-tree](https://cloud.githubusercontent.com/assets/96213/26460486/0487ea82-4137-11e7-817a-c81f5e555181.png)

**Comment by stephenlaughton** [comment]
I think @steve8708 's looks the best and makes the most sense! Especially with the mobx logo integrated. I instantly associate with mobx and the tree part looks friendly!

**Comment by mweststrate** [comment]
I concur with @luisherranz. Really like the cleanness, and professional look. But some trunk shape (in the style of the rest) would make it more clear indeed (my first association with the logo was a mountain). Would you be interested in taking a step at that @robinfehr? 

Orange color is fine imho, mobx-family-color :smile:  (national pride might play a role as well :grin:).

**Comment by caesarsol** [comment]
I like @steve8708 but I would't stretch the "M" MobX logo!

**Comment by mweststrate** [comment]
Closing, issue has been open long enough :)

**Comment by caesarsol** [comment]
😢
