### ISSUE TITLE
This object has died and is no longer part of a state tree. It cannot be used anymore. 

### ISSUE THREAD

**Issue by Rain120** [mobxjs/mobx-state-tree#1272]
version:
![image](https://user-images.githubusercontent.com/20939839/56956492-eb546380-6b76-11e9-86e7-3b64e4b83077.png)

Error:
![image](https://user-images.githubusercontent.com/20939839/56956477-db3c8400-6b76-11e9-823a-510c9127481a.png)

How to solve this error？

It didn't work after closed the react developer

**Comment by xaviergonz** [comment]
I've seen that when using react dev tools (and only when using them). It seems like for some reason react devtools try to deeply read props of dead components and therefore triggers that error. Your best bet right now is to just turn it into a warning.

**Comment by Rain120** [comment]
Do you mean React Developer Tools?

![image](https://user-images.githubusercontent.com/20939839/56975853-3d5fae00-6ba4-11e9-831e-06877a54acd8.png)

I had to try it but it didn't work.

**Comment by xaviergonz** [comment]
Then maybe some component is trying to access the property of an object that is no longer in the tree?
According to that message some component named "ConfigItems" is using something in "permission.list[54]" when that item is already dead.

**Comment by xaviergonz** [comment]
Ah wait, I just saw you are using mst 2.x

**Comment by Rain120** [comment]
yup， the project used the mst 2.0.5.
I found the error accur with one function execute, and the model store don't set 1 property named children, and the api return it, but I try set the property at  store, it's useless

**Comment by xaviergonz** [comment]
I'm afraid mst 2.x is not mantained anymore :-/
Can you reproduce it with the latest 3.x?

**Comment by Rain120** [comment]
srr, I can't do that, bcs this is a big project.
