### ISSUE TITLE
Dead ids in getSnapshot()

### ISSUE THREAD

**Issue by davidosomething** [mobxjs/mobx-state-tree#1275]
When you have an array of safeReferences
And you destroy an item that is referenced in the array
`getSnapshot()` will return a snapshot with ids to dead nodes.

E.g.

```
Item = types.model({
  id: types.identifier(),
});

Root = types.model({
  items: types.map(Items),
  refs: types.array(types.safeReference(Item)),
});

thing = Root.create({
  items: { a: {}, b: {}, c: {} },
  refs: [ 'a', 'b', 'c' ],
})

destroy(thing.items.b);
getSnapshot(thing.refs); // === [ 'a', 'b', 'c' ]
```

Is there a way to invalidate them? The onInvalidated() doesn't run on applySnapshot and the pre/post processors don't have access to the instance afaik

**Comment by xaviergonz** [comment]
I just wrote this unit tests and it seems to be passing:
```
test("#1275 - removing an object from a map should result in the snapshot of references being modified", () => {
    const Item = types.model({
        id: types.identifier
    })

    const Root = types.model({
        items: types.map(Item),
        refs: types.array(types.safeReference(Item))
    })

    const thing = Root.create({
        items: { aa: { id: "a" }, bb: { id: "b" }, cc: { id: "c" } },
        refs: ["a", "b", "c"]
    })
    unprotect(thing)

    destroy(thing.items.get("bb")!)
    expect(getSnapshot(thing.refs)).toEqual(["a", "c"])
})
```

**Comment by davidosomething** [comment]
It was a little tough to recreate, but I've pared down my app with an example here:
https://github.com/davidosomething/mst-dead-ref-2

### steps to reproduce

#### init app
1. `npm install && npm start`
1. Hit the import test data button
1. click the sync button  ![image](https://user-images.githubusercontent.com/609213/57122002-f19a3980-6d48-11e9-9676-7d743ac8353f.png)

#### run app

1. hard refresh
1. page will load snapshot from indexedDB
1. click on any person (don't click on the household)
1. delete the person from the three dots menu  ![image](https://user-images.githubusercontent.com/609213/57122036-17274300-6d49-11e9-95be-c1236a26dd92.png)
1. click on a household -- MST will fail to resolve a safeReference in an array

If you don't do the `run app` steps in order,
- e.g. visit a household first, then delete person, then go back to the household
- or import test data, then delete person, then go to household
 it will resolve fine.

Some info:

The pages render drafts (snapshot copies): https://github.com/davidosomething/mst-dead-ref-2/blob/master/src/models/Entity.js#L109

Delete happens here:
1. https://github.com/davidosomething/mst-dead-ref-2/blob/master/src/models/Entity.js#L55
2. https://github.com/davidosomething/mst-dead-ref-2/blob/master/src/models/Root.js#L31
