### ISSUE TITLE
SnapshotOrInstance does not allow map on the underlying collection

### ISSUE THREAD

**Issue by gamliela** [mobxjs/mobx-state-tree#1277]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

Hey, good work and thanks for making all of this happening!

I wonder why this code doesn't work, and if it relates to how `SnapshotOrInstance` is implemented.

```javascript
const Element = types.model();
const List = types.array(Element);
const listSnapshot = [{}];
const list = List.create(listSnapshot);

// this is working fine
const list2 : SnapshotOrInstance<typeof List> = listSnapshot;
list2.map(e => e);

// but this throws TS2349: Cannot invoke an expression whose type lacks a call signature.
const list3 : SnapshotOrInstance<typeof List> = list;
list3.map(e => e);  // TS2349
```

It seems that because `SnapshotOrInstance` is a simple `|` operator, it is not possible to invoke array methods such as `map` (and possibly other methods) on the underlying model structure.

As mentioned in [PR 965](https://github.com/mobxjs/mobx-state-tree/pull/965) `SnapshotOrInstance` is useful when you want to declare an input parameter that is able consume both types. But I think that this TS problem actually defeats this capability.

Can `cast` help to solve this problem? I'm not sure I understand how and if it possible to use it here, and I couldn't understand that from docs either.

**Comment by xaviergonz** [comment]
That's the limitation of TS

```{x: number; y: string} | {x: number; z: string} = {x: number}``` only shared props (the intersection) remains

Like you mention, it is made for input params that end up in being a plain assignation.

If you expect to operate over the input param and you know it is an instance then only use Instance

If you expect to operate over the input param and you know it is a snapshot then only use SnapshotIn

If your input param can be either and you want to operate over it as if it were an instance then either:
```
something(x: SnapshotOrInstance) {
  // either first convert to an instance, operate over it, and then assign (if applicable)
  const instX = XType.create(castToSnapshot(x));
  instX.whatever();
  self.x = instX;

  // or even better, assign then operate
  self.x = cast(instX);
  self.x.whatever();
}
```

What's your use case?

**Comment by gamliela** [comment]
My original intent was to make the function generic (option 3), so I tried similar approaches to your snippet. In your code, both approaches require `XType.create(castToSnapshot(x))` - isn't any other way without suffering the performance hit?

Still, both ways are too verbose, to my opinion. I was hoping it is possible to write the TS code in a way that will "simply works", because I think my use case is very common. However, totally understood if that's too complicated.
