### ISSUE TITLE
How to use types.snapshotProcessor in a transparent way

### ISSUE THREAD

**Issue by pfurini** [mobxjs/mobx-state-tree#1278]
**_Is there a way to use types.snapshotProcessor as transparently as old hooks?_**

* [x] I've checked documentation and searched for existing issues
* [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

I see in your test cases that the expected usage pattern for a snapshot processor is like the following:
```
const Model = types.model({
  m: types.snapshotProcessor(M, {
      preProcessor(sn: { x: number }) {
          return {
              ...sn,
              x: String(sn.x)
          }
      }
  })
})
const model = Model.create({ m: { x: 5 } })
```

So let's say I have a `User` model that now has a `preProcessSnapshot` hook, that I can instantiate with:
```
const user = User.create(responseFromAPI);
```

while with a new snapshot processor I need to do:
```
const user = User.create(someArtificialModelProp: responseFromAPI);
```

and that's as ugly as hell...
Is there an (idomatic) way to auto-apply a chain of processors to a given model type, without that indirection?

Thanks!
P.

**Comment by xaviergonz** [comment]
```
const ModelWithoutSnProc = types.model({
  someProp: types.string
})

const Model = types.snapshotProcessor(ModelWithoutSnProc, {
  preProcessor(sn: ApiModel) {
          return {
              someProp: sn.whateverApiProp,
              // likewise for other props
          }
      }
});

const myModel = Model.create(apiObject);
```

You mean that?

**Comment by Bnaya** [comment]
Take a look on:
https://github.com/Bnaya/mst-error-boundaries/blob/master/src/mst.ts#L3-L42
Might be helpful
