### ISSUE TITLE
Non observable objects in the state tree for performance reasons

### ISSUE THREAD

**Issue by tomitrescak** [mobxjs/mobx-state-tree#128]
Hi, first, sorry for writing this here as it is rather question then issue, is there any forum you have for this guys? Second, thank for making my devx best since invention of oop;)

I was wondering whether all properties in model are observables. We have a very large app with quite complex models which we are thinking of moving to MST, yet we fear of the performance. Moreover, we do not need to have all fields in model as observables (or ate least the whole deep structure). In mobx you have a notion of shallow observables.

So, how does it work with MST? How do set the "observability level" of model field? 

Good bye and thanks for all the fish.

**Comment by mattiamanzati** [comment]
By default, in MST every model becames an observable object. If you want to use immutable object as a shallowBox property, you can use t.frozen, which basically is the same of having a shallowRef property on an object. You won't be able to change that property value, but each time you have to change it you must replace the entire property value.

See #125 for more details.

**Comment by tomitrescak** [comment]
That makes sense concerning MST assures the possibility of time travel ... all clear now. Thanks for your explanation.
