### ISSUE TITLE
How to have types.number to be less strict or take in string numbers

### ISSUE THREAD

**Issue by jennypho** [mobxjs/mobx-state-tree#1281]
Error: [mobx-state-tree] Error while converting `"1"` to `number`:
    value `"1"` is not assignable to type: `number` (Value is not a number).

Is there a way I can make it less strict when taking numbers?

**Comment by Bnaya** [comment]
The best practice would be: fix the data that you get, on the source side
The second option would be: use types.snapshotProcessor and fix the snapshot.

And the third option :)
you can try to use the code i'm proposing here:
https://github.com/mobxjs/mobx-state-tree/issues/1280
Take a look on that specific example:
https://github.com/Bnaya/mst-error-boundaries/blob/master/src/mst.test.ts#L137

**Comment by jennypho** [comment]
> The best practice would be: fix the data that you get, on the source side
> The second option would be: use types.snapshotProcessor and fix the snapshot.
> 
> And the third option :)
> you can try to use the code i'm proposing here:
> #1280
> Take a look on that specific example:
> https://github.com/Bnaya/mst-error-boundaries/blob/master/src/mst.test.ts#L137

Thank you! This was very helpful!
