### ISSUE TITLE
strictNullChecks: false does not get along well with types.optional in Typescript

### ISSUE THREAD

**Issue by marcofugaro** [mobxjs/mobx-state-tree#1286]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/zn8262jl0l

**Describe the expected behavior**
There should be no errors in typescript

**Describe the observed behavior**
This not helpful error appears 
![image](https://user-images.githubusercontent.com/7217420/57685676-b5b07f80-7638-11e9-8773-7a676dba2888.png)

This happens since version [v3.11.0](https://github.com/mobxjs/mobx-state-tree/blob/master/changelog.md#3110) where the optional type was revisited adding a third argument.

However typescript gets angry when that default `[undefined]` value is not explicitly specified, making your life impossible when using primitive types (which are syntactic sugar to `t.optional`).

E.g. `isModalOpen: false` in a model.

This is probably related to #1208

**Comment by xaviergonz** [comment]
Could you post your tsconfig.json?

**Comment by marcofugaro** [comment]
Yes, this is my tsconfig.json, I have strict null checks disabled, however I don't think MST must depend on my personal typescript configuration. 

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["esnext", "dom", "dom.iterable"],
    "module": "esnext",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "jsx": "react",
    "strict": true,
    "strictNullChecks": false,
    "noImplicitReturns": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": false,
    "forceConsistentCasingInFileNames": true,
    "experimentalDecorators": true
  },
  "include": ["src"]
}
```

**Comment by thegedge** [comment]
I'm no longer able to reproduce (on `master`).
![CleanShot 2024-07-07 at 13 28 08@2x](https://github.com/mobxjs/mobx-state-tree/assets/833576/aa3c58f6-4287-46bc-9991-51cf70459f3f)

**Comment by coolsoftwaretyler** [comment]
Yup, looks like the reproduction Sandbox has it resolved on `mobx-state-tree@latest`: https://codesandbox.io/p/sandbox/zn8262jl0l?file=%2FState.tsx%3A7%2C4.

Closin' out. Thanks for the follow up on this @thegedge, and sorry to everyone else that it took a while to fix and close.
