### ISSUE TITLE
Idea: Support `Symbol.observable`

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#13]
Calling subscribe could return a stream of snapshots for interoperability with Symbol.observable / RxJs etc

**Comment by mweststrate** [comment]
Closing for now, will probably pop up again if someone needs it

**Comment by loganpowell** [comment]
I'm sorry for asking this here, but couldn't find a straight answer elsewhere:

If we'd like to have middleware that can subscribe to some external data source (e.g., a streaming API/websocket or `@live` graphql endpoint (TBD)), how might we do that? I.e., is this kind of observable data injection something that should be handled in the actions or in some middleware and - in either case - how would you recommend it be accomplished?
