### ISSUE TITLE
getParent in flow

### ISSUE THREAD

**Issue by RWOverdijk** [mobxjs/mobx-state-tree#1305]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**

_RootStore.ts_

```ts
export const RootStore = types
  .model('RootStore', {
    venueStore: types.optional(VenueStore, {}),
    spaceStore: types.optional(SpaceStore, {}),
  });
```

_VenueStore.ts_

```ts
export const VenueStore = types
  .model('VenueStore', {
    // Irrelevant
  })
  .actions(self => ({
    someAction: flow(function* someAction() {
      const rootStore = getParent<typeof RootStore>(self);
      // TypeScript doesn't like this ^
    }),
  }));
```

**Describe the expected behavior**

A typed reference to the RootStore.

**Describe the observed behavior**

I'm making Typescript sad:

> TS7022: 'rootStore' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

Important to note is that this **only** happens when using `flow()`. Outside of flow using `getParent<typeof RootStore>(self)` works fine and the RootStore is typed and everyone is happy.

**Comment by terrysahaidak** [comment]
@RWOverdijk could you please create a sandbox with an error?

Couldn't reproduce it:
https://codesandbox.io/s/awesome-perlman-7qdl6

**Comment by RWOverdijk** [comment]
@terrysahaidak https://codesandbox.io/s/boring-leaf-pjl4i

**Comment by RWOverdijk** [comment]
@terrysahaidak fyi all I did was yield rootStore (could be anything, but error 1 hides error 2) and enable strict in tsconfig.

**Comment by terrysahaidak** [comment]
I think @xaviergonz can help

**Comment by xaviergonz** [comment]
Does it work if you declare the return type of the flow directly? e.g.

```ts
export const VenueStore = types
  .model('VenueStore', {
    // Irrelevant
  })
  .actions(self => ({
    someAction: flow(function* someAction() {
      const rootStore = getParent<typeof RootStore>(self);
      // TypeScript doesn't like this ^
    }) as (() => Promise<void>),
  }));
```

**Comment by xaviergonz** [comment]
nevermind, I think it is related to the circular dependency, try using this
```
const RootStore = types
  .model('RootStore', {
    venueStore: types.optional(types.late(() => VenueStore), {}),
    spaceStore: types.optional(types.late(() => SpaceStore), {}),
  });
```

**Comment by terrysahaidak** [comment]
@xaviergonz I didn't get why @RWOverdijk [codesandobx](codesandbox.io/s/boring-leaf-pjl4i) has errors by [my](codesandbox.io/s/awesome-perlman-7qdl6) is not. Could you please help me understand that?

**Comment by RWOverdijk** [comment]
@xaviergonz I tried that before opening this issue. It doesn't work and the same issue persists. You can see that in the sandbox too if you want.

**Comment by RWOverdijk** [comment]
@terrysahaidak Because you didn't enable strict mode. Also to see the error you need to both yield and use rootStore so add `yield rootStore` in someAction.

https://github.com/mobxjs/mobx-state-tree/issues/1305#issuecomment-498227120

**Comment by RWOverdijk** [comment]
This has a reproduction. The label is wrong.

**Comment by RWOverdijk** [comment]
I don't remember. I don't even use mst anymore lol. Sorry
