### ISSUE TITLE
Optional default gets a Typescript complaint

### ISSUE THREAD

**Issue by bryanstearns** [mobxjs/mobx-state-tree#1308]
**_Bug report_**

When declaring an optional default for a model with entirely defaultable properties, I get a typescript error that I haven't been able to figure out.

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/optionaldefaultproblem-qx08w
```
import { types } from "mobx-state-tree";

export const ChildModel = types.model("Child").props({
  flag: types.maybe(types.boolean)
});

export const StoreModel = types.model("Store").props({
  child: types.optional(ChildModel, {}) // red squiggly under `{}` with error below
});
```

**Describe the expected behavior**
Before I discovered this problem when upgrading a project from much older mobx (4.2.1) & mobx-state-tree (2.0.5) versions, this worked: I could initialize MST models with naked-object snapshots and leave out `maybe` or `optional` properties if I wanted.

**Describe the observed behavior**
If I don't specify values for all the properties when building the snapshot object to use as the default, Typescript complains:
```
Argument of type '{}' is not assignable to parameter of type 'OptionalDefaultValueOrFunction<IModelType<{ flag: IMaybe<ISimpleType<boolean>>; }, {}, _NotCustomized, _NotCustomized>>'.
  Type '{}' is not assignable to type '() => ExtractCSTWithSTN<IModelType<{ flag: IMaybe<ISimpleType<boolean>>; }, {}, _NotCustomized, _NotCustomized>>'.
    Type '{}' provides no match for the signature '(): ExtractCSTWithSTN<IModelType<{ flag: IMaybe<ISimpleType<boolean>>; }, {}, _NotCustomized, _NotCustomized>>'.ts(2345)
```

I get essentially the same error if I define ChildModel's `flag` as `types.optional(types.boolean, false)` (or just `false`, which is the same thing, right?).
If I do `child: types.optional(ChildModel, { aProp: false })` instead (with either declaration, `optional` or `maybe`), the error goes away.

**Comment by xaviergonz** [comment]
Might be related to this?
https://github.com/mobxjs/mobx-state-tree/pull/1269

**Comment by kresli** [comment]
I think its related to #1307

**Comment by mweststrate** [comment]
@bryanstearns, please check your `tsconfig`. The compiler flags should be like:

```json
{
    "strict": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "noImplicitAny": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noImplicitThis": true
}
```

**Comment by mweststrate** [comment]
(please note that sandbox might not pick up compiler flag changes from my experience, so best test it locally or on stackblitz)

**Comment by alex-shamshurin** [comment]
Any update on this ?

**Comment by thegedge** [comment]
I'm not seeing this locally

![CleanShot 2024-07-06 at 14 19 42@2x](https://github.com/mobxjs/mobx-state-tree/assets/833576/db4512c2-b5a4-4842-8a38-46c281d4c282)

A lot has changed in the TS definitions for MST lately, along with TS upgrades. Let me know if anyone is still seeing this and, if so, the full set of relevant configs.

**Comment by coolsoftwaretyler** [comment]
Thanks for the follow up @thegedge! I [do not see this error on v6 either](https://codesandbox.io/p/sandbox/optional-default-problem-forked-y2hxhz?file=%2Fpackage.json%3A8%2C22), so I'm going to close it out.

For everyone else in the thread, sorry this has stayed open for so long, although we have definitely had a fix out for a little while.

If y'all need anything else, we can always reopen. Have a great day!
