### ISSUE TITLE
How to define an object type in the model?

### ISSUE THREAD

**Issue by THPubs** [mobxjs/mobx-state-tree#1309]
Hi, I need to define an object in my model like this:

    const App = types
      .model({
        token: '',
        loading: false,
        user: {
          firstName: ''
        }
      })

When I do this, I get an error saying: `Object literal may only specify known properties and 'firstName' does not exist in type 'Date | IAnyType'`

**Comment by xaviergonz** [comment]
```
const App = types
  .model({
    token: '',
    loading: false,
    user: types.model({ // types.model here
      firstName: ''
    })
  })
```

**Comment by coolsoftwaretyler** [comment]
Thanks for the good response here @xaviergonz! I think we can close this out since the answer is somewhat straightforward and we haven't seen activity on this issue in years.
