### ISSUE TITLE
types.union doesn't support multiple types

### ISSUE THREAD

**Issue by abruzzihraig** [mobxjs/mobx-state-tree#131]
When I was trying to implement something like the following code, I got a compiler error from my editor.
```
{ objects: types.array(types.union(Text, Button, Image, Video)) }
```
That's because the `types.array` doesn't support the function signature like above.

Then I found the declaration of the `types.array` only includes the two types like below:
```
export declare function union<SA, SB, TA, TB>(dispatch: ITypeDispatcher, A: IType<SA, TA>, B: IType<SB, TB>): IType<SA | SB, TA | TB>;
export declare function union<SA, SB, TA, TB>(A: IType<SA, TA>, B: IType<SB, TB>): IType<SA | SB, TA | TB>;
```

But actually in the source code I found there is an exported function it supports more types than two:
```
export function union(dispatchOrType: ITypeDispatcher | IType<any, any>, ...otherTypes: IType<any, any>[]): IType<any, any> {
    const dispatcher = isType(dispatchOrType) ? null : dispatchOrType
    const types = isType(dispatchOrType) ? otherTypes.concat(dispatchOrType) : otherTypes
    const name = types.map(type => type.name).join(" | ")
    return new Union(name, types, dispatcher)
}
```

So my question is, How should I handle the situation like what I mentioned above – to use the union types but more than two:
```
{ objects: types.array(types.union(Text, Button, Image, Video)) }
```
Is there any proper way to do it? Or could you add the declaration for supporting multiple types in `types.union`?

**Comment by mattiamanzati** [comment]
@abruzzihraig Thanks for your issue! Is support up to 10 types enough? :)

**Comment by RainerAtSpirit** [comment]
@mattiamanzati Is there a reason to restrict to a specific number like 10? Can we go without restriction?

**Comment by abruzzihraig** [comment]
@mattiamanzati Not sure if it is enough... I'm developing a website builder so I need to store all kinds of components(models in mobx-state-tree) to one array(for order reason). Currently, it might be 8 - 10 models I need to store but I'm not sure if someday the amount increase.

Same question with @RainerAtSpirit

**Comment by mattiamanzati** [comment]
@RainerAtSpirit Typescript does'nt support variadic types atm, so the only way to explicitely type that function is to provide all combinations for any amount of number of parameters.
That thing by the way can become very large (as redux one https://github.com/reactjs/redux/blob/master/index.d.ts#L375-L426).
If you provide more types, you can explicitely declare it using "as IType<any, Button | Text | String | Etc>".

**Comment by mattiamanzati** [comment]
Should be fixed by #82c145ee251a1c3d8cbac6251d2e25271cedc476, will be merged soon! Thanks for reporting! :)

**Comment by estill01** [comment]
Hey! Just ran into this same issue -- is commit 82c145ee251a1c3d8cbac6251d2e25271cedc476 scheduled to be merged? Thanks!

**Comment by abruzzihraig** [comment]
@estill01 It has already been merged.
