### ISSUE TITLE
How should I approach React application structure/architecture?

### ISSUE THREAD

**Issue by notbogdan** [mobxjs/mobx-state-tree#1313]
* [x] I've checked documentation and searched for existing issues
* [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

Coming from a Redux background, I really liked the [re-ducks](https://github.com/alexnm/re-ducks) setup where a single directory would contain all of the presentational/container components, unit tests, actions and reducers for a specific bit of UI. 
In addition to being easy to follow, this was great for testing and encapsulation, where dependencies on other parts of the UI were minimised and updates could be made safely without fear of breaking UI or tests elsewhere.

I am finding it hard to come up with a pattern that has similar benefits with MST because:

* Stores in an MST tree are expected to reference and operate on parent and child stores, meaning it is impossible to render a presentational component that only makes use of a certain store deep in the tree without instantiating the rest of that store's tree as well. 

* Individual store unit tests are fragile as changes to a store can impact stores elsewhere in the tree.

Does anyone have any suggestions on how to resolve these issues? I general, am very interested in hearing how people have structured their apps in a scalable, testable and modular manner. Any insight welcome!

**Comment by mweststrate** [comment]
This is not really a question for an issue tracker. But in general, in principle substores should be largely testable independently. As MST in itself is a completely fractal architecture. If you build logic yourself that depends on something that happens in a parent, then yes, like with any architecture, you are introducing coupling between child and parent. You are free to pick your own solution to that: always instantiate the whole tree (should be cheap anyway), or stub certain actions in your tests, leverage `getEnv`, etc.
