### ISSUE TITLE
Offload everything to web workers as MST at core is not an UI library

### ISSUE THREAD

**Issue by andraz** [mobxjs/mobx-state-tree#1318]
**_Feature request_**

**Is your feature request related to a problem? Please describe.**

Our way of using the mobile resources is compatible only with the WealthyWesternWeb.

The number of users in emerging markets will soon balloon exponentially and outgrow the existing web population as internet-capable mobile devices get sold for under 20$ everywhere. This could happen as soon as the next 1 or 2 years. There will be a growing need for a library, which can work on mobile devices from ~2012 era, while staying responsive (without blowing the 16ms frame budget).

source: https://dassur.ma/things/when-workers/

**Describe the solution you'd like**

Offload everything to a web worker while retaining the MobX core functionality of the `observer(` HOC wrapping React functional components in the UI thread.

The solution could be on the MST level, on the MobX core level, or on the HOC level affecting only `mobx-react-lite`

The [actor model architecture](https://www.youtube.com/watch?v=Vg60lf92EkM) could be a great way of shifting our mental model to achieve it.

**Describe alternatives you've considered**

[comlink](https://github.com/GoogleChromeLabs/comlink) + MST in a web worker
Failed because I could not find a simple way to link them to the UI side without big overhead on the UI thread of recreating all observables again one more time to autorun changes to them (which beats the point of moving everything to another thread).

**Additional context**

**Are you willing to (attempt) a PR?**
* [ ] Yes
* [x] No

**Comment by Bnaya** [comment]
It's an super interesting topic,

The main issue with this kind of changes is the async nature of web workers compare to the sync-by-design nature of mobx.

Back at the time, i was thinking about async apply snapshot: #725 
As MST is react but for state, we can use make similar mechanism to not block the UI while *some* of state update work is happening.
(React BTW are working on exposing a scheduler)

I think introducing such mechanism is possible, but MST will be less simple to use.
In react you can throw away invalidated views in middle of rendering, but what do you do when it's app state that in middle of being applied?

**Comment by andraz** [comment]
We can have multiple levels of web worker parent/child relationships:

1. top level: UI thread / React / observer
2. level: MST sync thread / observable (core can stay sync & nonblocking as it is not on the same worker as the UI thread)
3. level: MST async workers

The top level thread could have only UI updates passed from the MST main thread.

MST main thread could contain only the "glue" which needs to stay 100% sync to work correctly.

Everything else gets passed to child threads below it. Results get synced back with messages to the main MST thread which also takes care of the message passing to recalculate views etc...

**Comment by Bnaya** [comment]
* If you don't handle updates priorities, and ability to "cancel" some on-going updates, you won't benefit much.

* you can't share js plain objects/arrays in memory between workers, so you will need to hold a copy of the data on each worker,
And to keep them sync, you will still need to apply almost the same action on all of the copies, that is expensive (If I'm not mistaken).

Sidenode:
I was playing with it in my mind for a while, and i think the only want to really get parallelism performance benefits (put aside just not blocking the main thread using time slicing) is to work with data structs that fit in a shared array buffer.

And i want to point-out again that the way React choose to tackle this issue is by yielding execution, and not parallelism (Yet).

**Comment by mweststrate** [comment]
I think it is a cool idea @andraz :)

However I don't think there is much value in keeping this open as an _issue_, until someone champions an actual implementation. Feel free to build something, and PR the docs with a reference to some extension, or PR middleware that takes care of this etc. 

For now closing this issue until someone has an actual need and is willing to invest time in the solution :)
