### ISSUE TITLE
.is always returns false when used with snapshotProcessor

### ISSUE THREAD

**Issue by Tucker-Eric** [mobxjs/mobx-state-tree#1321]
The documentation leads me to believe that `types.snapshotProcessor` works similar to `types.compose` but using it that way causes `.is` to fail on the subtype as well as mutates the subtype to fail `myModel.is` without using the model returned from `snapshotProcessor`

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/mobx-state-tree-todolist-cgw7x
```javascript
const todo = Todo.create({
  title: "Get Coffee"
});

// True on first load but updates to false when sandbox refreshes
console.log(Todo.is(todo)); 

const Todo2 = types.snapshotProcessor(Todo, {
  preProcessor: snapshot => ({ title: `PREPROCESS: ${snapshot.title}` })
});

const todo2 = Todo2.create({
  title: "Get Coffee"
});

console.log(Todo2.is(todo2), Todo.is(todo)); // false, false
```

**Describe the expected behavior**
`console.log(Todo2.is(todo2), Todo.is(todo));` should return `true` and `true`.

**Describe the observed behavior**
Not sure if `snapshotProcessor` mutating the original model is intended behavior but the model returned from `snapshotProcessor` fails `.is()`.

**Comment by xaviergonz** [comment]
sounds like a bug indeed
