### ISSUE TITLE
How should I edit undoManager history?

### ISSUE THREAD

**Issue by notbogdan** [mobxjs/mobx-state-tree#1324]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

Hi, we've encountered a use case in our application that requires us to be able to programatically remove items from the `UndoManager` middleware history. What would be the best way to go about doing this? We are currently exploring the following:

* Another middleware around UndoManager. Not entirely sure how we would be able to intercept UndoManager actions in a way that would allow us to shape the history at will, however
* Store composition to "extend" the UndoManager and add `pop()`/`add()` methods

Alternatively the logic for a simple UndoManager history `pop()` method should be pretty straightforward, I would be happy to fork the repo and implement it myself.
Let me know any thoughts and ideas you may have, thanks!

**Comment by notbogdan** [comment]
This is the solution we've come up with so far:
```
import { UndoManager } from "mst-middlewares";

const GrabyoUndoManager = UndoManager
    .actions(self => ({
        pop() {
            self.withoutUndo(() => {
                self.history.pop();
                self.undoIdx = self.history.length;
            });
        }
    }));

export default GrabyoUndoManager;
```

**Comment by mweststrate** [comment]
`self.withoutUndo` is indeed created for this purpose. Why don't you wrap that around the original action, where you don't want undo, rather than try to change the history afterwards?

**Comment by notbogdan** [comment]
I'll try my best to describe the issue we faced with this hypothetical: 
Imagine we have a top level store, ParentStore. This is where the undoManager is set. 

This store has 2 child stores, ChildA and ChildB. 

ChildA can exist without ChildB being defined. However ChildB has dependencies on ChildA. 
 
Whenever ChildA is deleted, we also delete ChildB - this action is wrapped in a `withoutUndo` method.

Whenever we delete ChildB the action is recorded normally.

With these rules in mind, if we:
1. Delete ChildB
2. Delete ChildA
3. Undo

We try and apply patches that would add back ChildB without ChildA being in place. This will break our application. With this case in mind I don't see many options outside of 

- Rethinking our requirements for actions that can be undone/redone and refactoring our logic to support them, or 
- Selectively pruning the undoManager history to make sure we never undo/redo the application into an invalid state. 

We've had some conversations around this and while the second option initially seemed like a good idea, in our particular case the type of dependencies we have between our stores would mean the logic to figure out which patches/history entries we need to remove would be unreasonably complex. Nonetheless, with stores being able to depend on each other I can imagine simpler use cases where undoing history on a tree that has had state updated with `withoutUndo` would put the application into an invalid state. With this in mind I think being able to edit the undoManager history to some extend would be a good idea.
