### ISSUE TITLE
Observable Maps: .values().map is not a function

### ISSUE THREAD

**Issue by taime** [mobxjs/mobx-state-tree#1331]
**_Bug report_**
I follow the documentation here https://mobx.js.org/refguide/map.html

Here is part of my store:

````
@observable articlesRegistry = observable.map()
@computed get articles() {
    return this.articlesRegistry.values();
  };
````

In the component I'm trying to render this articles (use ES6 syntax as said in documentation) :
````
articles.map((article) => <Article article={article} />)
````

And get an error 
**TypeError: articles.map is not a function**

If it's not a but, may be we should give the usage example in documentation?

P.S. I use the example of code here https://github.com/gothinkster/react-mobx-realworld-example-app/blob/master/src/stores/articlesStore.js
(It's  in official recommendation list or real apps - https://github.com/mobxjs/awesome-mobx#examples)

**Comment by Maaartinus** [comment]
You need no mobx to reproduce the problem:
```
let articlesRegistry = new Map()
articlesRegistry.values().map(a => a)
```
AFAIK it's just like https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/values, i.e., all you get is an `Iterable`. You can convert it to an array e.g. via the spread operator
```
[...articlesRegistry.values()].map(a => a)
```
or you can iterate it using `for (... of ...)`.

**Comment by taime** [comment]
@Maaartinus I got it. My bad (it works as you said)... Thank you for help!
