### ISSUE TITLE
Wrong error message about missing value in MST create.

### ISSUE THREAD

**Issue by Maaartinus** [mobxjs/mobx-state-tree#1342]
After upgrading all the packages, the below error occurs in vscode. I couldreproduce it in sandbox. Nonetheless the project compiles and runs.

The culprit might be mixing `mobx-react` and `mobx-react-lite`, but I'm about to switch to hooks, so I guess, I need them both ATM.

**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/mst-ts-errors-ehtoj

**Describe the expected behavior**
No error message.

**Describe the observed behavior**
I'm getting
> Argument of type '{ id: string; }' is not assignable to parameter of type 'ModelCreationType<ExtractCFromProps<{ id: ISimpleType<string>; etag: IType<string, string, string>; }>>'.
  Property 'etag' is missing in type '{ id: string; }' but required in type '{ id: string; etag: string; }'.ts(2345)

**Comment by mweststrate** [comment]
The `strict` flag was not enabled in your `tsconfig`. MST requires the TS `strict` option to be set to work correctly.
