### ISSUE TITLE
How to create a typesafe back-reference?

### ISSUE THREAD

**Issue by sisp** [mobxjs/mobx-state-tree#1344]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

I have the following scenario: `B` has a reference to `A` and I'd like to create a back-reference so that `A` knows by which `B` it is being referenced. I've created a [sandbox](https://codesandbox.io/s/youthful-leftpad-8g00b) with a simplified example that shows the type error I get. The type error is caused by the fact that `self` in `self.a.setB(self);` does not yet implement the interface `IB` (`backref` is not defined at this point).

Is there a typesafe solution to this problem with MST?

**Comment by mweststrate** [comment]
You can declare the actions block as `.actions((self: IB) => ({`

**Comment by mweststrate** [comment]
Never mind, that makes it `any`. In that case I recommend to upcast `self as IB` in the implementation.

**Comment by sisp** [comment]
Okay, that works. Thanks for the suggestion.
