### ISSUE TITLE
Dynamic table of objects with a foolproof API

### ISSUE THREAD

**Issue by andraz** [mobxjs/mobx-state-tree#1345]
live example: https://codesandbox.io/s/mobx-state-tree-map-reference-pattern-7l0um

I am trying to polish and simplify this pattern as much as possible to not lose juniors completely when onboarding.

`stores.map` is a map of sub-stores (the "table" of objects)

`stores.active` is the currently active sub-store from map
* in SQL terms === `cursor`
* in DOM terms === `:focus`

Point of this pattern is to have an automated "table of records" which "just works" without any initializing (from the external API viewpoint). Table gets built dynamically as the user is using it.

Additional features can be autoloading from database onCreate, autosaving with debounced observer to localstorage/db, etc..., but I did not want to overcomplicate this example.

Do you have any suggestions how to simplify this pattern and are there any obvious edge cases which could cause long term problems?

**Comment by mweststrate** [comment]
The general pattern should work fine, and is exactly what references are for. Note that one of your views contain side effects, I would be careful with that.

**Comment by coolsoftwaretyler** [comment]
Hey folks,

This MobX-State-Tree question is pretty old and hasn't had much additional information added. I'm gonna close it out since the initial question was answered.

Thanks!
