### ISSUE TITLE
ModelType.name check seems too strict

### ISSUE THREAD

**Issue by k-g-a** [mobxjs/mobx-state-tree#1349]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

There is a suspicious check for model name at ModelType:
```ts
// TODO: this test still needed?
if (!/^\w[\w\d_]*$/.test(name))
  throw fail$1("Typename should be a valid identifier: " + name);
```

We're trying to use scoped model names, i.e. ```MyModel@82d92470-d05e-4dab-92cc-25b45f7fa2e4```, which do not pass the check mentioned above, but is valid for most operations in js (can be used as a key for object or as identifier attribute for dom elements). I can't think of any reason for such a strict check.

I propose either loose the check or remove it completely. Can make a PR.

**Comment by xaviergonz** [comment]
if the tests pass I don't see why not
