### ISSUE TITLE
Cerebral and Mobx-State-Tree on a blind date :-)

### ISSUE THREAD

**Issue by christianalfoni** [mobxjs/mobx-state-tree#135]
Hi there,

I have been looking into mobx-state-tree and hooking it up to [Cerebral](http://www.cerebraljs.com), great work! :-)

Cerebral currently has its own state-tree implementation, though it does not have the restrictions of mobx-state-tree that many developers want. At the same time Cerebral is focused on the business logic and composable state changes and side effects, which could be a good mix with mobx-state-tree. Here is a [video of the debugger](https://youtu.be/uhuLxs8-zP4?t=17m45s)

I basically have it working, though I have two questions, which I would suggest is a general challenge with external debuggers:

1. When I make a state change to relational data, is there any way to know what parts of the state tree updated? I understand this functionality is restricted, but not completely?

2. When I make a state change that affects a `getter`, is there any way to know that? 

The reason I ask this is because Cerebral has an Electron app as a debugger, which requires serializable data to be passed over and the state changes are reproduced. But currently it only knows about the exact state update you do, not any `getters` updating or relational nodes updating because of it :-)

Thanks and keep up with the state innovation :-D

**Comment by mattiamanzati** [comment]
Uhm, no at the moment the only way to know that is by watching snapshot. Do you really need to send to the debugger computed values? Like actions they should not be present in snapshot, so they are considered some sort of "views" that changes over time :)

**Comment by christianalfoni** [comment]
@mattiamanzati Thanks for the answer :)

You know... the computed is not necessary, I see they are already ignored by stringifying, so that is not an issue :)

So it is rather one question then, 1. 

From docs: "Data graphs are not supported, only data trees
This means that each object needs to uniquely contained
Only containment relations are allowed. Associations need to be expressed with 'foreign keys'; strings identifying other objects."

You have an example of this restriction? Like in what way do you express a "containment relations"? And is there any way to know if such a thing occurs related to a state change?

**Comment by mattiamanzati** [comment]
@christianalfoni That basically means you cannot have the same object in two places in MST, each object should live only in one place in the tree. (like real leaf in real trees, they are solid object and they can't be in 2 place at the same time). Speaking by examples, this will fail.

```
const BoxStore = types.model({
    id: types.identifier(types.string)
})
const Store = types.model({
   boxes: types.optional(types.array(Box), []),
   selected: types.maybe(Box)
})

const store = BoxStore.create()
unprotect(store)

const boxA = Box.create({id: "A"}) 
store.boxes[0] = boxA // => BoxA now lives at /boxes/0
store.selected = boxA // => FAILURE! BoxA already lives at /boxes/0
```

But you can use references! Instead of storing the value, it will create a setter that will store the identifier, and a getter that will resolve the referenced object.

```
const BoxStore = types.model({
    id: types.identifier(types.string)
})
const Store = types.model({
   boxes: types.optional(types.array(Box), []),
   selected: types.reference(Box)
})

const store = BoxStore.create()
unprotect(store)

const boxA = Box.create({id: "A"}) 
store.boxes[0] = boxA // => BoxA now lives at /boxes/0
store.selected = boxA // => It works! BoxA still lives at /boxes/0, but here we get a reference to it.
```

**Comment by christianalfoni** [comment]
@mattiamanzati Thanks for taking the time to explain! :) 

Aha! Though what does `store.selected` serialize to? Is it some special string or something? Or does it serialize to the object it references?

**Comment by mattiamanzati** [comment]
@christianalfoni It depends on how reference is configured.
If you use `types.reference(Box)` it will accept any Box instance, and serialize to {$ref: "../boxes/0"} (the relative path). If you use `types.reference(Box, "/boxes")` (basically provide a reference to the collection mount point) it will resolve to the identifier property!
Sorry for lacks of docs atm!

**Comment by christianalfoni** [comment]
@mattiamanzati I see, cool! But this is great, cause then I do not have to worry about a state change to the actual box needs to be updated somewhere else in the visualization of the tree :)

I got all my answers, will produce a little video for you to see mobx-state-tree runs in the Cerebral environment, I think it will be pretty cool :)

**Comment by mattiamanzati** [comment]
@christianalfoni If you need to listen to all the changes of an action, for example, you can start a patch recorder over the root node of the store ;)

```
// start listening
const recorder = recordPatches(getRoot(store))

store.myAction() // perform the changes

// stop listening
recorder.stop()

// get the changes
let patches = recorder.patches
```
