### ISSUE TITLE
`applySnapshot` seems to preprocess the snapshot twice

### ISSUE THREAD

**Issue by rgehan** [mobxjs/mobx-state-tree#1354]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/flamboyant-fire-4qoxr

**Describe the expected behavior**
I have a model with both a `preProcessSnapshot` and `postProcessSnapshot`.

I want to make some changes on it, but rollback the changes if something fails, so here's my process:
- Backup the model using `getSnapshot`
- Perform some modifications on the instance
- Oops, something fails...
- Rollback using `applySnapshot(self, backupSnapshot)`

**Describe the observed behavior**
I get at "Error while converting..." error, that seems to indicate the preProcessor ran twice.

My model is defined like this:
```js
const Model = types
  .model({
    id: types.string,
    realId: types.number,
    foo: types.string
  })
  .preProcessSnapshot(snapshot => ({
    ...snapshot,
    realId: snapshot.id,
    id: "some-hash"
  }))
  .postProcessSnapshot(snapshot => ({
    ...snapshot,
    realId: undefined,
    id: snapshot.realId
  }));
```

`getSnapshot` returns:
```js
{
  id: 123,
  realId: undefined,
  foo: 'bar',
}
```

Yet, applying that snapshot fails:
```
at path "/realId" value `"some-hash"` is not assignable to type: `number`
```

The only way for such an error to happen, would be for `preProcessSnapshot` to have run twice.

```js
// Snapshot
{
  id: 123,
  realId: undefined,
  foo: 'bar',
}

// After one preProcess
{
  id: 'some-hash',
  realId: 123,
  foo: 'bar',
}

// After two preProcess
{
  id: 'some-hash',
  realId: 'some-hash',
  foo: 'bar',
}
```

**Comment by jamonholmgren** [comment]
Fixed in v5.1.8: https://github.com/mobxjs/mobx-state-tree/releases/tag/v5.1.8
