### ISSUE TITLE
Problems onAction with async(flow) function

### ISSUE THREAD

**Issue by VitamineC** [mobxjs/mobx-state-tree#1358]
**_Feature request_**

**Is your feature request related to a problem? Please describe.**
I try to use onAction for work with side effects.  I'm having a problem, when I try to detected the success end of async action. 
I see "finish" action, that pushed after end of async, but if I have few started async action it's no simple way to detect which one is over.

![image](https://user-images.githubusercontent.com/22227310/62196033-f0979900-b385-11e9-86ef-7982cd742628.png)

Which one of the action is end?

**Describe the solution you'd like**
I suggest to expand the action model. You can add 'reason' property to action, that will be start\success\error. It will help detect which of action is detected and why it happenes. 
![Screenshot from 2019-07-31 11-32-10](https://user-images.githubusercontent.com/22227310/62196694-2721e380-b387-11e9-8b2f-0738f4601b86.png)
![Screenshot from 2019-07-31 11-34-48](https://user-images.githubusercontent.com/22227310/62196771-4a4c9300-b387-11e9-9a8b-fe5dbae7e205.png)

**Describe alternatives you've considered**
Any option that can help detect which action is ended.

**Additional context**

**Are you willing to (attempt) a PR?**
* [x] Yes
* [ ] No

**Comment by mweststrate** [comment]
Instead of `onAction`, use the more low level `addMiddleware` function, which reveals more details. You might also look into `onAction`'s implementation itself to get some inspiration in that direction.

**Comment by coolsoftwaretyler** [comment]
Hey @VitamineC - I know it's been a while since you last checked in on this MST thread. Do you recall if @mweststrate's answer was useful to you? Let me know! Happy to chat more if this idea is still relevant and you'd like to propose a change.

If I don't hear back in about two weeks, I'll close this out.

**Comment by coolsoftwaretyler** [comment]
No response since then - closin' out!
