### ISSUE TITLE
TS-Bug: computed property is after spread-oeprator-copy part of the copys type

### ISSUE THREAD

**Issue by pixelkritzel** [mobxjs/mobx-state-tree#1362]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/wizardly-hill-6esmm?fontsize=14&module=%2Fsrc%2Findex.ts

**Describe the expected behavior**
The inferred type of the spread-copied `mdlCopy` should not include the property `bar`

**Describe the observed behavior**
The inferred type of the spread-copied `mdlCopy` includes the property `bar`

Funny side note: Typescript somehow manages to spread copy the getter.

**Comment by xaviergonz** [comment]
You should not spread copy node instances, use `clone` if you want to clone an instance or spread copy its snapshot (you can get it via `getSnapshot`) if you want a plain javascript object

**Comment by coolsoftwaretyler** [comment]
Hey all,

This MobX-State-Tree issue is very old and looks to be answered. I'm gonna close it. Thanks!
