### ISSUE TITLE
Is it possible to specify interface of snapshot but work with real prop type in MST methods

### ISSUE THREAD

**Issue by vitalymatyushik** [mobxjs/mobx-state-tree#1379]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

Is it possible somehow to keep MST-model in sync with Json-interface and implementation of fields in MST model description? 
To be precise how it is possible to avoid casting in `setFirstChildName` method
```
import { types } from 'mobx-state-tree'

// 2 interfaces describe response from Backend
interface IChild {
    name?: string
}

interface IParent {
    name?: string
    children: IChild[]
}

// MST models used by different components
const Child = types.model<IChild>('Child', {
    name: types.optional(types.string, '')
}).actions(self => ({
    setName(newName) {
        self.name = newName
    }
}))
type TChild = typeof Child.Type

const Parent = types.model<IParent>('Parent', {
    name: types.optional(types.string, ''),
    children: types.array(Child)
}).actions(self => ({
    setName(newName) {
        self.name = newName
    },
    setFirstChildName(newName) {
        if(self.children && self.children.length){
            // even if children specified as array of Child MST - it will be typed based on interface
            (self.children[0] as TChild).setName(newName)
        }
    }
}))
```

**Comment by lorefnon** [comment]
You can use the [SnapshotIn and SnapshotOut types](https://github.com/mobxjs/mobx-state-tree/blob/d687833fd13d7b068e2792213a2c6296781775a6/packages/mobx-state-tree/src/core/type/type.ts#L229-L245).

**Comment by coolsoftwaretyler** [comment]
Hey folks,

This MobX-State-Tree issue is old and looks to be answered. I'm gonna close it. Thanks!
