### ISSUE TITLE
Observe values inside HOC's?

### ISSUE THREAD

**Issue by JonasGroenbek** [mobxjs/mobx-state-tree#1389]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

I want to rerender my navigation bar based on the users role in my react-native application. I am using react-navigations HOC ``createBottomTabNavigator``. I am unable to pass anything down from the top-level container (seems cluttered as well), or wrap the function in a class and use the mst decorators inject or observe.

Is it possible to cause a rerender on store change in this scenario?

**Comment by terrysahaidak** [comment]
createBottomTabNavigator isn't a HOC. It's just a function which will create a tab navigator for you. You can't call it twice nor change somehow it. It's a known limitation of the current version of react-navigation:
https://reactnavigation.org/docs/en/limitations.html#dynamic-routes

As a workaround, you can define several bottom navigators and navigate the user to a specific one when you want to. But it isn't related to mobx-state-tree.

Check out this issue https://github.com/react-navigation/react-navigation/issues/6257 or search for similar on the react-navigation repo (there are a bunch of them)

**Comment by JonasGroenbek** [comment]
Woulf you not call it a HOC since it takes stacknavigators? 
Thanks for your answer, ill look inti it
