### ISSUE TITLE
types.union type inference is wrong

### ISSUE THREAD

**Issue by skeate** [mobxjs/mobx-state-tree#1391]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/cool-neumann-gd521

**Describe the expected behavior**
When creating `instance`, the property `item` should accept string, number, or null.

**Describe the observed behavior**
TS error, `item` only accepts `null`.

**Comment by xaviergonz** [comment]
Might be related to https://github.com/mobxjs/mobx-state-tree/issues/1371

**Comment by mweststrate** [comment]
This is conceptually correct, for reasons explained here: https://github.com/mobxjs/mobx-state-tree/issues/1403#issuecomment-547118869. In other words, never redeclare property types, except if you can subtime them
