### ISSUE TITLE
deleted

### ISSUE THREAD

**Issue by Unique111** [mobxjs/mobx-state-tree#1393]
deleted

**Comment by Unique111** [comment]
@mweststrate

**Comment by mweststrate** [comment]
Please don't ping individuals , especially not within a couple of days, for something that isn't critical. But here is your answer:
 
To quote: https://github.com/mobxjs/mobx-state-tree/blob/master/docs/middleware.md

> rootid is the id of the action that spawned this action. If an action was not spawned by another action, but something external (user event etc), id and rootId will be equal (and parentid 0)

But please disappear with that answer immediately, but take a look of some of the other questions that are open and check which one you can answer in turn :)
