### ISSUE TITLE
Type of a store is lost when actions are extracted to a separate function

### ISSUE THREAD

**Issue by Uncleseneca** [mobxjs/mobx-state-tree#1400]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/mst-issue-d2hye

**Describe the expected behavior**
I expect a type of a store to be infered

**Describe the observed behavior**
Type of a store with actions extracted infers to any

**Comment by Uncleseneca** [comment]
![image](https://user-images.githubusercontent.com/26726281/66252809-ac9b8880-e768-11e9-97e7-803b10d84e5d.png)

**Comment by val-samonte** [comment]
i think this happens if there are existing ts issues in the tree. checking your code sandbox:

![image](https://user-images.githubusercontent.com/767060/67476383-8774a880-f68a-11e9-81c9-96d29ca961ce.png)

in my case, the children were dependent on the root state (type dependency issue)

**Comment by Bnaya** [comment]
you need to create an intimidate type of the store before the actions,
and use that type in the actions,
see:
https://codesandbox.io/s/mst-issue-fk366

**Comment by coolsoftwaretyler** [comment]
Hey folks - based on the reacts to @Bnaya's comment, it seems this issue is resolved. I'll mark it to be closed unless I hear otherwise in the next two weeks or so.

**Comment by coolsoftwaretyler** [comment]
No response since then - gonna close it out.
