### ISSUE TITLE
Individual stores that reference other stores are not unit testable

### ISSUE THREAD

**Issue by notbogdan** [mobxjs/mobx-state-tree#1404]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

Imagine a store like the following:
```
types.model(`MiddleStore`, {
    childStore: ChildStore,
    storeFarAway: types.reference(FarawayStore)
})
.views(self => ({
    get fromParent() {
        return getParentOfType(ParentStore).parentValue;
    },
    get fromChild() {
        return self.childStore.childValue
    },
    get sumStoreValues() {
        return self.fromParent + self.fromChild + self.storeFarAway.value;
    }
}));
```
How would you go about unit testing this store? It has dependencies on a child node, a parent node, and a reference to a node elsewhere in the tree. Instantiating it alone will require the instantiation of the whole tree. Testing the logic within it seems to be toeing the line of an integration test. Am I just approaching unit testing MST stores incorrectly?

**Comment by k-g-a** [comment]
If `FarawayStore` is within the same tree - you should supply the whole three to the test. Perhaps, mocking some parts of it with custom predictable snapshots.
If it's a separate tree - you should use custom reference (which is not present at you example). Within this custome reference you could either use MST environemnt and provide [real tree]/[mock for the test] or use any non-MST technique to separate and mock the `FarawayStore`.

**Comment by notbogdan** [comment]
Mocking dependant stores using snapshots would not be enough if the integration goes as far as using another store's views/actions...

**Comment by k-g-a** [comment]
Unfortunatelly I can't get the point of the original question. Could you please provide an extended example with the `FarawayStore` present?

**Comment by mweststrate** [comment]
Personally I love to avoid the problem by just always instantiating a complete store for the entire test. Since stores are never singletons that works really well imho as long as you don't automatically kick of side effects such as data testing, and it keeps things stupidly simple and predictable at the cost of some coupling.

**Comment by k-g-a** [comment]
Totally agree with mweststrate. We use one store per ModelType (not every model type, but only the basic ones - those which have API endpoint; nested `type.model`'s just live within basic ones) and use custom references to automatically fetch linked basic models at runtime. 
To manage those stores we have DI-container, which is injected as the part of the `environment` to every root store. After trying several ways we ended up with just creating and filling the whole container one time before all tests - and it works great.

**Comment by notbogdan** [comment]
> Personally I love to avoid the problem by just always instantiating a complete store for the entire test. Since stores are never singletons that works really well imho as long as you don't automatically kick of side effects such as data fetching, and it keeps things stupidly simple and predictable at the cost of some coupling.

Fair enough. How do you handle stores that have data fetching as a side effect? Is it just a matter of mocking the API responses or is it better to avoid stores that work with remote data upon initialisation altogether?

**Comment by mweststrate** [comment]
Environments are meant to provide your data fetching layer (and any other
thing that is environment specific) to the models, rather than hard
coupling them. That makes it easy to swap out their implementation in
tests. See https://github.com/mobxjs/mobx-state-tree/#dependency-injection,
from top of my head in one of the examples 'fetch' is injected in a similar
way.

**Comment by mweststrate** [comment]
Oh and yeah, I indeed avoid fetching upon initialization. Creating model
instance first, than call `.loadInitialData()` action explicitly gives you
a lot of additional control for little additional effort
