### ISSUE TITLE
Cannot resolve a reference with multiple candidates (two model instances with same identifier AND PATHS!)

### ISSUE THREAD

**Issue by Carduelis** [mobxjs/mobx-state-tree#1407]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] I've debugged and did some research on the issue via Chrome Dev Tools
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Describe the observed behavior**
Once upon a time, I got a well-known issue (resolving references) with unexpected content.
Both references had the **same paths**. I checked it's not a typo. Moreover, it is not an abandoned model in the part of an unconnected tree.

I used a debugger to override the error and inspected both models.
```javascript
switch (matches.length) {
            case 0:
                return null;
            case 1:
                return matches[0];
            default:
            console.log('resolved reference models', matches); // <-- here
                throw fail$1("Cannot resolve a reference to type '" + type.name + "' with id: '" + identifier + "' unambigously, there are multiple candidates: " + matches
                    .map(function (n) { return n.path; })
                    .join(", "));
```
First, I checked, `matches[0] !== matches[1]`. Ok, they are different.

Then, I checked root and parent objects of these models. They are the same. Literally:
 `matches[0].parent === matches[1].parent` // true
 `matches[0].root=== matches[1].root` // true

Then I decided to check *only different* properties and wrote
```javascript
for (var key in matches[0]) {
 if (matches[0][key] !== matches[1][key]) {
  console.log(key, matches[0][key], matches[1][key])
 }
}
```

So, `nodeId`'s are different. 
`unbox`, `_applyPatches`, `_applySnapshot` are functions and they are different too.
`identifierCache`, `storedValue`, `_internalEvents`, `pathAtom`, `aliveAtom`, `value` are different too
**the rest keys are === the same**

**What I found interesting?**

1. one `pathAtom` has `isPendingUnobservation: true`, `isBeingObserved: false`and zero observers in the Set, another `isPendingUnobservation: false`, `isBeingObserved: true` and one observer in the Set
2. `aliveAtom`'s look the same unless `pathAtom`. 
3. `_initialSnapshot` are differerent. This is caused by my code, cause there are multiple entry points for this model. But every time before putting model to a Map, i do check `if (map.has(id))`, so this is strange.

Unfortunately, I can't reproduce the whole issue. Do you have any suggestions on where to dig?
And, definitely, there is should be a special error case to help to understand why did it happen

**Comment by mweststrate** [comment]
Sorry, but as you guessed already, it is really impossible to say anything sensible about this without a minimal reproduction.

**Comment by Carduelis** [comment]
@mweststrate thanks for the response. I thought it could be like "A-ha!" and the answer is simple. The strange thing that I'm not able to reproduce this issue anymore on a different machine. Or maybe I miss something, cause there were a lot of commits afterward and the broken commit does not reproduce the issue on another machine.

But before I close the issue, could you help with the example of resolving identifiers?

There is an example in the documentation of References of how to create a reference type that loads entity if it's not found.

You put there a comment that `setimmediate` is a temp hacky solution. 

I tried to reproduce the same behavior but I chose `setTimeout` instead of `setImmediate` and have to have put it twice: in the view and in the action 
https://codesandbox.io/s/mobx-state-tree-todolist-u9hry

When I tried to avoid setTimeouts using `allowStateChangesInsideComputed` or `allowStateChanges`, but it breaks the production build.

What is the best way to write such Reference that returns the existed model or returns a mocked-model that will be populated when data come?

Right now I have models, that have `data` property that represents data from the server.
So, when I create a model with just an id, it creates an empty model.

This `GetOrFetchReference` should return a model, or put the model with given `id` to the map, then the model will update itself automatically. The main question is how to make this side-effect of creating a new model in the map inside a `view`. 

**I think this is a source of the whole issue of the same identifiers and paths: current Custom Reference creates the second model while the existing one is not being discovered yet.** -- And we have two models: one has been added when it's loaded from one Custom Reference, the another model has been added by another Custom Reference. 

The thing that I have multiple Custom References for User model in different places. All of them look for User model in the specific `map` and add a missing one if needed. But this "if needed", I think, somehow broken because of views-side-effect.

Thank you

**Comment by mweststrate** [comment]
I think it is solvable as I can vaguely remember seeing similar things in the past. Some solution directions you could consinder is using two different types at different paths, one with the temp items. Or making consumers defensive against the objects not being present yet, rather than generating stub objects on the fly. 

I would love to be able to answer the question, but to be frank, at this moment I don't have the time to dive into questions that requires me to understand a few hunderd LoC first. 

If less people that would use this lib, would pass by to ask some questions, and then leave without ever answering those they know the answer to, that would maybe viable. But as it stands, in-depth support can't be scaled :)

**Comment by Carduelis** [comment]
@mweststrate thank you anyway. Right now this is not a blocker for our project, but if I get some updates, I will populate this thread.

**Comment by coolsoftwaretyler** [comment]
Hey @Carduelis - since it's been a few years, I'm going to guess you never got updates on this. It seems like the issue is ready to be closed, so I'll mark it to be closed, but keep it open for the next two weeks in case you wanted to add anything or get additional help/thoughts here.

Thanks!

**Comment by coolsoftwaretyler** [comment]
It's been about two weeks - closin' it out!
