### ISSUE TITLE
applyPatch will not replace root of store

### ISSUE THREAD

**Issue by skokenes** [mobxjs/mobx-state-tree#1411]
* [x] I've checked documentation and searched for existing issues
* [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

Is there anyway to use applyPatch to update a snapshot in the same way you might do an applySnapshot? With JSON patching, I'd expect to be able to replace a store using a patch like:
{
  op: "replace",
  path: "",
  value: {} // new store snapshot 
}
However, patches like this never work for me in MST. See this example code showing it in action with a simple model:
https://codesandbox.io/embed/lively-shape-lmjgo

**Comment by mweststrate** [comment]
It is not possible to replace a thing itself, as that would require all
javascript pointer that point to that object to be updated, which is
impossible. Either create patches that replace all fields of the root
object, or wrap another object around the root so that there is an entry
point.

**Comment by mweststrate** [comment]
A Test + PR that will make MST error on such cases is welcome (condition: node is root, path is empty)

**Comment by skokenes** [comment]
I see. How does that differ from applying a snapshot? Don't they
conceptually do the same thing? Ie, replace the entire structure

**Comment by mweststrate** [comment]
Yeah, thinking longer about, I think it is a bug and it should behave is
one would expect :)

**Comment by Bnaya** [comment]
I don't know if its directly related but,
I have a WTF feeling earlier this year when after using MST for a while,
when this code didn't work on sub property and not the root
```
   const MyModel = types.model("MyModel", {
      arr1: types.array(types.string)
    });

    const model = MyModel.create({
      arr1: ["c"]
    });

    unprotect(model);

    const fn = jest.fn();
    reaction(() => model.arr1, fn);

    // not passing also with that
    // applySnapshot(model.arr1, ["a", "b"]);
    // @ts-ignore
    model.arr1 = ["a", "b"];
```
Full example:
https://codesandbox.io/s/mobx-state-tree-arrays-wtf-zonww?fontsize=14&previewwindow=tests

**Comment by epodgaetskiy** [comment]
@Bnaya You can use ```toJS``` https://codesandbox.io/s/mobx-state-tree-arrays-wtf-pji90
