### ISSUE TITLE
Referencing nodes in uninitialised parts of the tree causes them to be evaluated incorrectly in afterCreate()

### ISSUE THREAD

**Issue by notbogdan** [mobxjs/mobx-state-tree#1412]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/crazy-merkle-k770l

**Describe the expected behavior**
Logic in afterCreate() should be able to reference created store nodes correctly

**Describe the observed behavior**
If referencing a node in an uninitialised store through a `types.reference` property, that node will be unavailable during that store's afterCreate() call.

Check the console.logs in the Codesandbox - despite being initialised with data the leaf being referenced by a reference prop elsewhere in the tree is being returned as `undefined` in BranchA's afterCreate call. Referencing any other property first will cause the afterCreate to behave as expected.

**Comment by mweststrate** [comment]
Sorry, I didn't see any `undefined`s being logged in the example. But any functionality that requires accessing the parent, such as resolving references, is generally speaking only available after `afterAttach` has fired, and not in `afterCreate`.

**Comment by notbogdan** [comment]
> Sorry, I didn't see any `undefined`s being logged in the example. But any functionality that requires accessing the parent, such as resolving references, is generally speaking only available after `afterAttach` has fired, and not in `afterCreate`.

Apologies, the code example was updated unintentionally. You can now see the very strange interaction in the afterCreate, where the `getSnapshot` call returns the expected data while the `console.log` in the `forEach` logs one leaf, the one that was being referenced, as undefined.
