### ISSUE TITLE
React.StrictMode breaks observer for async actions

### ISSUE THREAD

**Issue by impulse** [mobxjs/mobx-state-tree#1418]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/embed/mst-async-bug-6kul3

**Describe the expected behavior**
When clicking "set async" the text should be updated in the UI.

**Describe the observed behavior**
When the App is wrapped in `React.StrictMode` the action will be called but the UI won't update. Sometimes the console will give the following warning:

> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
>     in wrappedComponent (at src/index.tsx:27)
>     in Route (at src/index.tsx:26)
>     in Switch (at src/index.tsx:25)
>     in Router (created by BrowserRouter)
>     in BrowserRouter (at src/index.tsx:24)
>     in div (at src/index.tsx:23)
>     in StrictMode (at src/index.tsx:21)
>     in App (at src/index.tsx:38)

MobX DevTools show the following:
![mobx](https://user-images.githubusercontent.com/8146736/68464607-2c59be80-0211-11ea-991f-a6ea55538b18.png)

Removing the `React.StrictMode` tags will result in the App working again.

**Comment by mweststrate** [comment]
can you try with mobx-react-lite@next ? The 2.0 version will add official
concurrent mode support

**Comment by impulse** [comment]
Seems to work fine when using @next. Will not be using StrictMode until 2.0 arrives in the meanwhile. Thanks!
