### ISSUE TITLE
[Question] How to move a node from a tree branch to another?

### ISSUE THREAD

**Issue by fabiosussetto** [mobxjs/mobx-state-tree#142]
Hi guys, thanks for this library, it looks very promising, looking forward to version 1.0 :)

Question about moving nodes from different "branches" of the tree:

I have a "Taskboard" model with contains an array of "Lane" models:

```
const Taskboard = types.model('Taskboard', {
  id: types.identifier(),
  lanes: types.array(Lane),
})

export const Lane = types.model('Lane', {
  id: types.identifier(),
  title: types.string,
  tasks: types.optional(types.array(Task), []),
}, {
  pushTask (task) {
    this.tasks.push(task)
  },
  moveToColumn (dragTask, dragLane, hoverLane) {
    if (dragLane === hoverLane) {
      return
    }

    if (hoverLane.tasks.find(t => t.id === dragTask.id)) {
      console.log('HoverTask already in this lane, skipping!')
      return
    }
  
    const clonedTask = clone(dragTask)
    // Moving task to different lane now
    hoverLane.pushTask(clonedTask)
    dragLane.tasks.remove(dragTask)

  }
})
```
For some reason though I get this error:

```
This object has died and is no longer part of a state tree. It cannot be used anymore. The object (of type 'Task') used to live at '/taskboards/entries/e8be04dc-45e3-420a-846d-aa08fc7bdc1d/lanes/0/tasks/0'. It is possible to access the last snapshot of this object using 'getSnapshot', or to create a fresh copy using 'clone'
```

I guess it's because I'm trying to use somewhere else the Task node I just removed?
Should I use ```detach``` as well to avoid this problem? If so, how?

I also tried not to use ```clone``` in the code above, like this:
```
dragLane.tasks.remove(dragTask)
hoverLane.pushTask(dragTask)
````
But if I do so, I get this other error:
```
Cannot add an object to a state tree if it is already part of the same or another state tree. Tried to assign an object to '/taskboards/entries/e8be04dc-45e3-420a-846d-aa08fc7bdc1d/lanes/1/tasks/0', but it lives already at '/taskboards/entries/e8be04dc-45e3-420a-846d-aa08fc7bdc1d/lanes/0/tasks/0'
```

@mattiamanzati @mweststrate  could you please help me with this use case?

Thanks!

**Comment by mweststrate** [comment]
You might try detach(dragTask), pushTask (dragTask). Detach will remove the
node from the parent automatically. But keep it alive

Op ma 22 mei 2017 12:45 schreef Fabio Sussetto <notifications@github.com>:

**Comment by fabiosussetto** [comment]
Thanks @mweststrate that seems to work fine, I quickly tried this seems to work fine:

```
const currIndex = dragLane.tasks.findIndex(t => t === dragTask)
const taskToMove = detach(dragLane.tasks[currIndex])
hoverLane.pushTask(taskToMove)
```

Btw I was using redux before and the out-of-the-box performance I get for the same use case using mobx-state-tree is pretty amazing in comparison (it's a drag-and-drop UX so it can get quite tricky to implement properly). 
Compared to redux, there's also a lot, a lot less code to do the same thing. Nice stuff!

**Comment by mweststrate** [comment]
I'm pretty sure you can skip the whole find / index thing and just pass
dragtask directly to detach to make it even faster 😉

Op ma 22 mei 2017 15:17 schreef Fabio Sussetto <notifications@github.com>:

**Comment by fabiosussetto** [comment]
@mweststrate indeed, now it's just 

```
hoverLane.pushTask(detach(dragTask))
```

Perfect, thanks a lot.
