### ISSUE TITLE
How do we use undoManager.startGroup for frequently called actions post v3.13.0?

### ISSUE THREAD

**Issue by notbogdan** [mobxjs/mobx-state-tree#1423]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

Before v.3.13.0 the following was valid when using the undoManager's `startGroup` method for creating an entry of a single group of patches in the undoManager history:
```
undoManager.startGroup(() => store.callAction());
undoManager.startGroup(() => store.callAction());
undoManager.startGroup(() => store.callAction());
undoManager.stopGroup();
```
This was great because it allowed us to make separate, frequently called actions, such as those called as a result of an input `onChange` all add patches belonging to the same group:

```
class Input extends React.Component {
    onChange = ({ target: { value } }) => {
        undoManager.startGroup(() => this.props.store.onChange(value))
    }

    onBlur = () => {
        undoManager.stopGroup();
    }

    render() {
        <input type="text" value={this.props.store.value} onBlur={this.onBlur} onChange={this.onChange} />
    }
}
```
 
Since v3.13.0 this behaviour has changed, and the above code will now throw because the `startGroup` method now looks like this:
```
startGroup<T>(fn: () => T): T {
    if (groupRecorders.length >= 1) {
        throw new Error(
            "a previous startGroup is still running, did you forget to call stopGroup?"
        )
    }
    groupRecorders.push({
        patches: [],
        inversePatches: []
    })
    return fn()
},
```
It now looks like there can only ever be 1 group active, and only the actions called in the context of the `startGroup`'s callback will be recorded for that group. This makes the above use case (and any other requiring the recording of multiple, separately called actions be recorded into one group) seem quite tricky to implement. I'm not sure if this is how `startGroup` was initially intended to be used, but it seems like a regression in terms of flexibility and ease of use.

I am now looking at ways of extending the undoManager to make the use case described above easier. I am wondering if the design choice of v3.13.0 is the right one and if I should be looking at potentially reverting this behaviour rather than designing new functionality around it.

**Comment by mweststrate** [comment]
I think this change was intended, as your original approach would
accidentally capture concurrently happening events; for example the
handling an incoming message from the server. So in general I'd recommend
to pull startGroup up as for as possibly to capture all logic inside
it. For example call it direclty from the event handler.

If the process you try to group is async, IIRC the startGroup will track
all intermediate steps properly as long as it is a process that is written
using MST's `flow`

**Comment by notbogdan** [comment]
@mweststrate there is an inherent issue with using `flow` to add actions to the group. Normally you would add a set of actions to a group with an execution order that looks like:

startGroup()
action()
action()
...
stopGroup()

With flow, the actions are asynchronous meaning the execution order above is not guaranteed, and you may have actions being executed after the `stopGroup`. We will look into ways to remedy this, any suggestions welcome otherwise

**Comment by twobit** [comment]
@notbogdan were you able to resolve this? Dealing with the same issue

**Comment by notbogdan** [comment]
@twobit In the end we ended up tweaking our logic to only run `startGroup()` on the first invocation of long running actions. To enable this we extended the undo manager so that we can check whether a group is active:
```
const UndoManagerWithGroupState = types.compose(
	UndoManager,
	types.model(`UndoManagerWithGroupState`, {
		groupActive: false
	}).actions(self => {
		const startGroup = self.startGroup;
		const stopGroup = self.stopGroup;
		return {
			startGroup(fn) {
				startGroup(fn);
				self.groupActive = true;
			},
			stopGroup() {
				stopGroup();
				self.groupActive = false;
			}
		};
	})
);
```
So now in our callbacks, such as the input `onChange` in the example we can do:
```
onChange = ({ target: { value } }) => {
        if (!undoManager.groupActive) {
            undoManager.startGroup(() => {})
        }
        this.props.store.onChange(value)
}

**Comment by twobit** [comment]
@notbogdan thanks for sharing the snippet, I ended up taking a slightly different approach using a React hook:

```
function useUndoGroup<T extends any[], R>(callback: (...args: T) => R) {
  const group = useRef<typeof callback>();

  return {
    start: function (...args: T): R {
      if (!group.current) {
        group.current = undoManager.startGroup(() => callback);
      }
      return group.current(...args);
    },
    end: () => {
      if (group.current) {
        undoManager.stopGroup();
        group.current = undefined;
      }
    }
  };
}
```

Used like this:
```
const group = useUndoGroup((value: string) => store.rename(value));

return (
  <Input value={store.name} onChange={(e: ChangeEvent) => group.start(e.currentTarget.value)} onBlur={group.end} />
);
```

**Comment by justin-hackin** [comment]
I also got hung up on this issue.  The documentation at the end of https://www.npmjs.com/package/mst-middlewares#undomanager is thus misleading.  Should the readme reflect the bug?  Another approach is to save the diff of an operation such as drag in a separate part of the state that skips the undo history and then when the drag ends, apply the diff to the base value (inside the history tracking), using a view to compute the dragged position.  This can be a useful shape for data in cases where one needs to revert the diff instead of applying it to the base value (e.g. return to the position where the drag started on esc pressed during mouse down).
