### ISSUE TITLE
Extending models imported from other packages with new flows

### ISSUE THREAD

**Issue by skokenes** [mobxjs/mobx-state-tree#1427]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

I have a monorepo with multiple services that need to leverage the same base MST models. I have a package in that monorepo that creates and exports MST models.

When my other services import those models, if I try to extend the models with new actions that involve flows, I get the following error:
`[mobx-state-tree] a mst flow must always have a parent context`

See this example git repo showing the problem in action:
https://github.com/skokenes/mst-flow-error

EDIT: Moving my mobx/mobx-state-tree installs out of the individual packages and having just one version of mobx/mobx-state-tree installed at the root of the monorepo seems to resolve the issue. So my question is, is this expected behavior? What if I wasn't using a monorepo and wanted to export models for another package to consume that might have its own version of MST loaded?

**Comment by Bnaya** [comment]
It's a `peerDependencies` issue.
Each one of your packages has its own `node_modules/mobx-state-tree"
With yarn workspace it will be simple to setup, not sure about that npm setup you have there
I will try to play with it later

**Comment by Bnaya** [comment]
See the following branch:
https://github.com/Bnaya/mst-typescript-dec-test/tree/packages-issue
`npm install && npm start`

You want that all of the packages to share the same `mobx` & `mobx-state-tree`,  there are several ways to do so, the one i used not necessarily the best one, but works as demonstration.

**Comment by skokenes** [comment]
Makes sense, thank you!
