### ISSUE TITLE
Video is not availabe

### ISSUE THREAD

**Issue by comerc** [mobxjs/mobx-state-tree#143]
> mobx-state-tree "immutable trees" and "graph model" features talk, "[Next Generation State Management](https://www.youtube.com/watch?v=nhNiKel6U9Y&feature=youtu.be&t=1h8m34s)" at React Europe 2017.

**Comment by barbarosso** [comment]
I think it's this one
https://www.youtube.com/watch?v=Ql8KUUUOHNc

**Comment by luisherranz** [comment]
His slides are from React Europe 2017, not 2016: http://tree.surge.sh/

It looks like they took the video down and are adding properly edited videos to the channel:
https://www.youtube.com/channel/UCorlLn2oZfgOJ-FUcF2eZ1A/videos?flow=list&live_view=500&sort=dd&view=0

**Comment by mattiamanzati** [comment]
Thanks for reporting! New video link has been added! :D
