### ISSUE TITLE
is possible to use MST with Sveltejs?

### ISSUE THREAD

**Issue by Relaxe111** [mobxjs/mobx-state-tree#1432]
**_Question_**

yes - I've checked the documentation and searched for existing issues
yes - I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

Hello, we use MST for all our web applications. Now we have some discussions to switch over seveltejs. My question:  Is there any possibility to use MST with svelte? If no is there any plan in the future to do so?

**Comment by Bnaya** [comment]
Sveltejs have a completely different model of "reactivity"
Sveltejs detects possible updates on compile time and inject updates call.
mobx(/mst) detect updates on runtime and can call your side effects.

I'm sure you can find a way to plug them together (setting svelte state updates inside autorun or so) but i have a feeling you will end-up with the limitations of both of the worlds and not the benefits of them.

**Comment by Relaxe111** [comment]
I see ). thank you for the reply.
