### ISSUE TITLE
Using mobx-state-tree inside a mobx-store

### ISSUE THREAD

**Issue by stiofand** [mobxjs/mobx-state-tree#1437]
I'm trying to use a MST model in a Mobx Store, however it appears this cant be done, due to some restriction on exporting the store as an observer?

Assuming all is set up and  MST is working fine in the React components. I have a UI model which is my MST (this is example code as actual code is private for a client)

```
import { observer } from 'mobx-react'
import { UI } from './models/UI'
const UIState = UI.create()

class MyStore {
... do things which include UIState.
}
export default observer(MyStore) 
```
`const store = new MyStore() //  --> "Object is not Constructor..."`

If I remove the observer wrapper all is well, except the state tree is no longer updated.

**Comment by Bnaya** [comment]
it's kind hard to understand what you are doing there,
Can you create a minimal repro in codesandbox?

**Comment by stevematdavies** [comment]
@Bnaya I could indeed, but Im fairly sure the example above is clear enough without scaffolding an entire app to illustrate it,  are you really that confused as to what I'm trying to do?

**Comment by Bnaya** [comment]
Well, i guess i am 🥱 
good luck

**Comment by stevematdavies** [comment]
OK, well I get on to it once I have some time. Thanks.

**Comment by Bnaya** [comment]
BTW `observer` is for wrapping react components, not other things.
to intersect stores (mobx, MST, doesn't matter) use computed that reference values from them both, or less recommend - sync them with auto runs

**Comment by xaviergonz** [comment]
observer is for react components, maybe you meant to wrap the class with observable?

**Comment by xaviergonz** [comment]
And actually observable is for properties, so just export the store class directly

**Comment by stevematdavies** [comment]
@Bnaya I'm not quite following what you mean, I use readable values from MST to determine some values and computed values in my MobxStore

**Comment by stevematdavies** [comment]
@xaviergonz if I export it as such (without the observer wrapper), it appears that the tree isn't being updated. Perhaps it's my code, I will look deeper. 

Thanks

**Comment by Bnaya** [comment]
You are using the apis wrong,
It has nothing to do with mobx state tree
https://github.com/mobxjs/mobx#core-concepts
Simple example of how it could work
```js
class MobxStore {
  @observable filterText = "";

  constructor(mstModel) {
    this.mstModel = mstModel;
  }
  @computed() get filteredPosts() {
    return this.mstModel.posts.filter(s => this.filterText === "" || s.includes(this.filterText))
  }
}

const MstModel = types.model({
  posts: types.array(types.string)
})

new MobxStore(MstModel.create(["postA", "PostB"]));
```

**Comment by stevematdavies** [comment]
@Bnaya Nice example! Looks as if it may solved my issue! Im new to this MST thing!
You're a star, many thanks indeed

**Comment by coolsoftwaretyler** [comment]
Hey folks, thanks for the good discussion here. Looks like things are all resolved and have been for quite some time.

I'm gonna close this out.
