### ISSUE TITLE
Can't understand about this issue

### ISSUE THREAD

**Issue by Preyash** [mobxjs/mobx-state-tree#1447]
[mobx-state-tree] A map of objects containing an identifier should always store the object under their own identifier. Trying to store key '1', but expected: 'undefined'

https://drive.google.com/file/d/1tEvWfjRIEpur4Kn7WZ31s-S0w9mZbzGX/view?usp=sharing

**Comment by mweststrate** [comment]
It means that, if you have an object, which has an identifier, and you try to put it in a map, it must be stored under it's own identifier. In other words

```typescript
const Todo = types.model({
  id: types.identifier,
  title: types.tring
})

const MapOfTodos = types.map(Todo)

const t1 = new Todo({ id: "abc1234", title: "test")
const map = MapOfTodos.create()
map.set("abc1234", t1) // OK
map.set("test", t1) // Not ok, map looks should always lead to objects with the same key
```

If you need a map with a lookup based on something else, you typically need to use a reference and have a map as well in which the todos are stored. These restrictions make sure that the data is properly normalized and tree semantics are preserved.

**Comment by sbussard** [comment]
> If you need a map with a lookup based on something else, you typically need to use a reference and have a map as well in which the todos are stored

@mweststrate can you please give an example?

**Comment by mweststrate** [comment]
The general idea would be

```typescript
const User = types.model({
  id: types.identifier,
  name: types.string
}).actions((self) => {
   afterAttach() {
      getRoot(self).usersByName.put(self.name, self)
   },
   setName(newName) {
      self.name = newName
       getRoot(self).usersByName.put(self.name, self) // TODO: also remove the entry from the old name
   }
}

const Store = types.model({
   users: types.map(User) // stores by ID
   usersByName: types.map(types.reference(User))
})
```

**Comment by sbussard** [comment]
Thanks!
