### ISSUE TITLE
How to access root store or other stores from injected dependencies?

### ISSUE THREAD

**Issue by umutozdemir97** [mobxjs/mobx-state-tree#1448]
I'm trying to migrate to MST because I want to use references. I currently use `Mobx` and I have a `transport layer` that reads the `token` from `userStore`, some other configs from `commonStore` etc. As far as I understood by reading the documentation, I can inject `transport layer` as a `dependency`. But I can't find a way to read store data from dependencies.

> This is useful to inject environment or test-specific utilities like a transport layer, loggers, etc. 
https://mobx-state-tree.js.org/concepts/dependency-injection

Can I access root store or a different store from a dependency? In the example here, how can I access `todos` from `logger`?

With Mobx, my transport layer (`client` in `RootStore`) was a store like this: 

```js
class RootStore {
  constructor(initialData = {
    userStore: {},
    commonStore: {},
    bookStore: {},
  }) {
    this.userStore = new UserStore(initialData.userStore, this);
    this.commonStore = new CommonStore(initialData.commonStore, this);
    this.bookStore = new BookStore(initialData.bookStore, this);
    this.client = new Client(this); // let the root store have a reference to client
  }
}
```

Here's the example of `logger` from the documentation: 

```js
import { types, getEnv } from "mobx-state-tree"

const Todo = types
    .model({
        title: ""
    })
    .actions(self => ({
        setTitle(newTitle) {
            // grab injected logger and log
            getEnv(self).logger.log("Changed title to: " + newTitle)
            self.title = newTitle
        }
    }))

const Store = types.model({
    todos: types.array(Todo)
})

// setup logger and inject it when the store is created
const logger = {
    log(msg) {
        console.log(msg)
    }
}

const store = Store.create(
    {
        todos: [{ title: "Grab tea" }]
    },
    {
        logger: logger // inject logger to the tree
    }
)

store.todos[0].setTitle("Grab coffee")
// prints: Changed title to: Grab coffee
```

**Comment by fruitraccoon** [comment]
I've run into this in the past - the challenge is that to create the store, you need to pass the dependencies, but to create the dependencies, you want the store.

A way that I've handled this in the past is to pass a closure containing the store variable to the dependency, rather the store itself.  For example (inspired by your `Client` mobx code):

```
function getDefaultStore() {
  let store;
  const storeEnv = {
    client: new Client(() => store),
  };
  store = RootStoreModel.create({}, storeEnv);
  return store;
}
```

The constructor parameter for `Client` might be called `getStore` and you can execute it when you need the store reference (eg: `const store = getStore();`)

So now, anywhere in the store you can use `getEnv` to get the Client dependency, and within the client dependency, you can use `getStore` to access the store state.

**Comment by Bnaya** [comment]
You can mimic refs in plain mobx using dependency injection
