### ISSUE TITLE
actions usage inside reaction/setInterval and more outside functions

### ISSUE THREAD

**Issue by stolenng** [mobxjs/mobx-state-tree#1449]
**_Question_**

* [V ] I've checked documentation and searched for existing issues
* [ V] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3) (looking for answer, not posting there)

I've seperated my actions to another file and then i load it when creating the model: `.actions(someActions)`.

now everytime i try to use `reaction` or `setInterval` inside `afterCreate`, i call action from inside or pass the action as callback i always get i cannot modifiy the state from outside :/ 
`the object is protected and can only be modified by using an action.`

any idea ??

**Comment by stolenng** [comment]
managed to solve it by calling `self.callAction` instead of just `callAction` inside, a lot of weird behavior around this area :S

**Comment by mweststrate** [comment]
This is working as intended, by default MST defends against direct
mutations that don't go through the model's api. If you want to disable
that behavior, use `unprotect`.

**Comment by stolenng** [comment]
@mweststrate 
But I wasn't trying to a direct modification, I was calling an action

**Comment by stolenng** [comment]
here is an example: 
```
const actions = self => {
	const fetchData = () => {
		//fetch some data
	}


	afterCreate() {
		setInterval(() => fetchData(), 10000);
	}

	return {
		afterCreate,
		fetchData
	};
};

export { actions };

```
it's not explicit that I had to do this to make it work:
`setInterval(() => self.fetchData(), 10000);`

**Comment by mweststrate** [comment]
See first sentence here: https://mobx-state-tree.js.org/concepts/actions. Note that the methods you pass to `actions` are not the same as the actions themselves, as the actions you are providing will be wrapped by MST, for example to make sure middleware is triggered. By trying to bypass the actions of the model itself, you would be accidentally not triggering middleware you might have etc.  So model instances really provide a single point of interaction, which allows us to to guarantee a lot of things.

**Comment by stolenng** [comment]
thanks for the detailed answer ! :)
