### ISSUE TITLE
MST DevTools Error

### ISSUE THREAD

**Issue by alexvcasillas** [mobxjs/mobx-state-tree#145]
Hi, @mattiamanzati and @mweststrate 

I'm opening this issue because I encountered an error while using MST with MobX's DevTools.
You can check this error and the Store that generates it in the following Gist: [https://gist.github.com/alexvcasillas/83a96cc5feec2de9e761185d9f7011f6](https://gist.github.com/alexvcasillas/83a96cc5feec2de9e761185d9f7011f6)

This error happens only when I add the MobX DevTools to see the actions that has been fired and related stuff because I wanted to explain how MST works to a co-worker and then I found that it was throwing the error described in the Gist when an action that changes one of the observables (the array one) that had a default value of [ ] (empty) with the fetched data from the Github's API was fired.

Hope we can solve this together and thanks for your efforts! : )

**Comment by mweststrate** [comment]
Could you set up a fiddle / demo project demonstrating this issue?

**Comment by alexvcasillas** [comment]
Sure @mweststrate !
This repo has a demo of async fetching with MST : [https://github.com/alexvcasillas/react-mobx-router/tree/master/examples/mobx-state-tree-github-repos-demo](https://github.com/alexvcasillas/react-mobx-router/tree/master/examples/mobx-state-tree-github-repos-demo)
Just clone it, use yarn (I use yarn) and enable DevTools at `/src/containers/app.jsx` add them above `Header` component for example, that's where I have them.

After that try to fetch some user and the Store will crash and the App will stop working 😅 You'll only see the skeleton UI of the output that will come.

You can check also that here [https://react-git-app.firebaseapp.com/](https://react-git-app.firebaseapp.com/) Without DevTools is working fine (I'm not controling the NOT FOUND exception that throws github... still)

Thanks @mweststrate !

**Comment by chemitaxis** [comment]
Yes, I can reproduce this bug too ;)

**Comment by mweststrate** [comment]
Not entirely sure how this should be fixed. The problem is basically that with the devtools you are looking at data which is no longer part of a store, and hence considered 'dead'. This is basically a feature of MST, as it will fail fast if you hold on to data (often unintentionally) that is no longer part of your app. Rather then looking at stale data, MST will warn you. 

However, in this case that might be what you want. The only proper solution I can think of is adding support for MST to the react devtools; if an MST object is logged, log is snapshot of the instance instead of the instance (snapshots never die as they are immutable).

CC: @andykog @mattiamanzati

**Comment by mattiamanzati** [comment]
@mweststrate Seems the only reasonable way. So the devtools can also warn you by putting some sort of suffix in the name, like [stale] or [dead]

**Comment by andykog** [comment]
@mweststrate, the current problem can be fixed as simple as replacing this function https://github.com/mobxjs/mobx-react-devtools/blob/8de7b25/src/consoleLogChange.js#L198-L209 with something like:
```js
function getNameForThis(who) {
    if (who === null || who === undefined) {
        return "";
    } else if (who && typeof who === "object") {
      if (who && '$mobx' in who) {
        try {
          return who.$mobx.name;
        } catch (e) {
          return '[Dead?]';
        }
      } else if (who.constructor) {
        return who.constructor.name || "object";
      }
  }
  return `${typeof who}`;
}
```

But then the same error may still be discovered later (for example, if we decide to show changed object's content somewhere). 

@mattiamanzati, @mweststrate, I'm not familiar with `mobx-state-tree` enough, but I thought, maybe we could freeze & allow using 'dead' objects outside of derivations and actions? Pseudocode:
```js
kill(object) {
  const $prevMobx = object.$mobx;
  let frozen = false;
  Object.defineProperty(object, '$mobx', {
    get() {
      if (mobx.extras.isComputingDerivation() || mobx.extras.getGlobalState().inBatch > 0)
        throw new Error('Oops, tried to use dead object in transition');
      if (!frozen) {
         frozen = true;
         deepFreeze($prevMobx);
      }
      return $prevMobx;
    }
  })
}
```

**Comment by andykog** [comment]
> if an MST object is logged, log is snapshot of the instance instead of the instance


Won't it tear CPU apart on heavy logging?

**Comment by mweststrate** [comment]
MST is now first class supported (thanks @andykog!), so this is no longer an issue afaik?

**Comment by alexvcasillas** [comment]
It’s no longer an issue for me!!
Also thanks @andykog !!
