### ISSUE TITLE
mst-middlewares - converting circular structure to JSON fails on item removal

### ISSUE THREAD

**Issue by impulse** [mobxjs/mobx-state-tree#1452]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/inspiring-haze-joox0

**Describe the expected behavior**
Should not throw an error / handle the error

**Describe the observed behavior**
Removing added cart items results in:
```
0.chunk.js:20315 Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'FiberNode'
    |     property 'stateNode' -> object with constructor 'HTMLSpanElement'
    --- property '__reactInternalInstance$mt3m58hemec' closes the circle
```

**Comment by mweststrate** [comment]
Your sandbox is too big to dive into, but given the exception, it looks like you are trying to store HTML elements or React components or something alike in your MST tree. Please note that you can only store serializable data in normal MST properties. For anything else, make sure to use `.volatile` properties (note that those won't be serialized).

**Comment by impulse** [comment]
@mweststrate I stripped down the example sandbox a bit more but basically what I do is to remove `CartItems` from the `Cart` (similar to your wishlist course on egghead). Only storing strings and numbers. The errors happens when calling `remove()` on the CartItem and only when the middleware is being used.

```ts
export const CartItem = types
  .model({
    name: types.string,
    price: types.number,
    tags: types.optional(types.array(Tag), [])
  })
  .actions(self => ({
    // ...
    remove() {
      getParent<typeof Cart>(self, 2).remove(self);
    }
  }));
```

```ts
export const Cart = types
  .model({
    items: types.optional(types.array(CartItem), [])
  })
  .actions(self => ({
    addCartItem(
      cartItem: SnapshotIn<typeof CartItem> | Instance<typeof CartItem>
    ) {
      self.items.push(cartItem);
    },
    remove(item: SnapshotIn<typeof CartItem>) {
      destroy(item);
    }
  }))
```

**Comment by mweststrate** [comment]
Probably the culprit is using `        onClick={item.remove}` vs.
`onClick={() => item.remove)}`. The first one sends the event handler data
as first argument to the `remove` action, and if the middleware tries to
serialize the arguments you might run into that exception.

**Comment by impulse** [comment]
Yeah I can confirm this is causing the problem. Do you think this is easily fixable? Could try for a PR then.

**Comment by mweststrate** [comment]
Yes, `{onClick={() => item.remove()}` should be a valid fix

**Comment by impulse** [comment]
Sorry my question was not precise. I meant a fix for the middleware to handle `onClick={item.remove}` properly.
