### ISSUE TITLE
make an updateFiled function which will update fields in a type safe manner for a mst model in .ts file

### ISSUE THREAD

**Issue by Relaxe111** [mobxjs/mobx-state-tree#1453]
**_Question_**

* [ yes] I've checked the documentation and searched for existing issues
* [ yes] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

Im apolorgize if it is a stupid question :)
I have a model  with ts like this:
```
//file: sms_store.ts
const NewSMS =  types.model("NewSMS",{
    type: 200,
    sentDate: types.maybeNull(types.Date),
    content: "",
    sms_template_id: 0
})
.preProcessSnapshot(snapshot =>{
    if(!snapshot) return snapshot

    return snapshot
})
.actions(self =>({
    updateField(value,name){
        self[name] = value;
    }
}))

export const SMSStore = types.model("SMSStore",{
    sms_send:     types.optional(types.array(SMS),[]),
    new_sms: types.optional(NewSMS,{})   
})
```
how I can mske update filed such as compiler not to complain?
I've tried something like this:
```
...
.actions(self =>({
    updateField<T, Key extends  keyof T>(value:T[Key],name:Key){
        self[name] = value;
    }
}))
...
```
Also I've tried:
 to use self istead of T use self, no not working
I also extracted type of the NewSMS like:
`type TNewSMS = Instance<typeof NewSMS> `
and added instead of T not working

**Comment by mweststrate** [comment]
You will have to create an interface first for your type (as described on this page: https://mobx-state-tree.js.org/tips/typescript), and then I'd expect you should be able to use `updateField<Key extends keyof ThatInterface>(value: ThatInterface[Key], name: Key)` (p.s. I'd swap the arguments)

**Comment by Relaxe111** [comment]
Thank you for answer. I will try tomorrow this solution )

**Comment by Relaxe111** [comment]
I've tried suggested solution but got two errors:
1.: 'NewSMS' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
1.: Type parameter 'Key' has a circular constraint
2.:Type 'Key' cannot be used to index type 'INewSMS'
what I did:
I created a interface type according to rules sugested in the link below.
```

import {Instance} from 'mobx-state-tree'
import {NewSMS} from '../sms_store'

export interface INewSMS extends Instance<typeof NewSMS> {}
```
after I imported in my file INewSMS

and used in the updateField method like this:
![image](https://user-images.githubusercontent.com/40892030/72600150-616e4580-3913-11ea-9f8f-cbd4bba4c05a.png)

I'm doing something wrong?

**Comment by mweststrate** [comment]
looks ok to me. In that case I'm not sure if it can be expressed in TS +
MST.

In general, if you want people to look into issues, make sure you set up a
super simple code sandbox project that demonstrates the issue, so that
others can play with it. Screenshots are quite uninteractive :)

**Comment by Relaxe111** [comment]
hello again here I have Supersimple sandbox example:)
[https://codesandbox.io/s/bold-pine-3sw6u?fontsize=14&hidenavigation=1&theme=dark]

**Comment by Relaxe111** [comment]
I got a solution for that! it is less elegant and, one need to manually define an extra interface. But at least no error ). If someone has a better solution please share)
[https://codesandbox.io/s/bold-pine-3sw6u?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/bold-pine-3sw6u?fontsize=14&hidenavigation=1&theme=dark)

**Comment by calvellido** [comment]
Hi!  In case it helps, I had problems using a previously declared interface (through `SnapshotIn` or `SnapshotOut`) to properly type `self` inside an action, as then I receive:

> 'UI' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

But in the end, I get TypeScript compiler happy with:

```typescript
import { types, Instance } from "mobx-state-tree";

export const UI = types
  .model("UI", {
    videoOpen: types.optional(types.boolean, false),
  })
  .actions((self) => ({
    setField<Key extends keyof typeof self>(
      field: Key,
      value: typeof self[Key]
    ): void {
      self[field] = value;
    },
  }));

export const UIStore = UI.create();

export type UIType = Instance<typeof UI>;
```

I'm using TypeScript `3.8.3` and this is my `tsconfig.json`

<details>
  <summary>Show content</summary>
 
```json
{
  "compilerOptions": {
    "baseUrl": "./src",
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "noImplicitReturns": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react"
  },
  "include": [
    "src"
  ]
}
```
</details>

**Comment by Relaxe111** [comment]
just tried your solution it seems to work perfectly to my project as well. :)

**Comment by Relaxe111** [comment]
I think solution proposed by @calvellido is best so far at it works in all my scenarios. I close issue. If someone has other solution please don't hesitate to write here.
