### ISSUE TITLE
Print what changed to trigger "onSnapshot"

### ISSUE THREAD

**Issue by garrett-gottlieb** [mobxjs/mobx-state-tree#1454]
**_Question_**

* [X] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

How can I see exactly what changes were made to my model? I'm debugging but can't pinpoint the model change that triggered the `onSnapshot`.

**Comment by mweststrate** [comment]
Use onPatch?

Op do 16 jan. 2020 07:46 schreef Garrett Gottlieb <notifications@github.com

**Comment by garrett-gottlieb** [comment]
Yes, actually I ended up using:
```js
import { actionLogger } from 'mst-middlewares'
const store = Store.create()
addMiddleware(store, actionLogger)
```
