### ISSUE TITLE
How should identifier be used when saving a new model?

### ISSUE THREAD

**Issue by garrett-gottlieb** [mobxjs/mobx-state-tree#1456]
**_Question_**

* [X] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

When I try to instantiate a model with `id: types.maybe(types.identifierNumber)` I get:
```
[mobx-state-tree] instance identifier 'id' for type 'mymodel' must be a string or a number
```
Knowing that new models don't have ids until they are persisted to the server, what is the approach for this?

Here is an example `save` action which updates the model with its id after saving:
```js
    save: flow(function* save() {
      const { ...data } = self
      const response = yield fetch(url, { body: data })
      const data = yield response.json()
      self.id = data.id
    })
```

**Comment by Tybi** [comment]
The type identifier can't be updated after model creation. It's used for resolving reference. In your case if your model need to be used as reference in other you need to have something like id of type  identifier for reference and serverId of type string (if your id is string) for your server object id. Or if your model doesn't need to be used as reference just use id of type string.

Somebody correct me if i'am wrong.

**Comment by garrett-gottlieb** [comment]
Thanks for the idea, @tmocellin. I thought of using a different approach, since `id` and `serverId` is confusing. What if there are two different base model types: `NewModel` and `ExistingModel`. Something like:
```js
const NewModel = types.model({
  // default model properties, if any
  createdAt: types.Date,
  updatedAt: types.Date,,
})
const ExistingModel = types.compose(
  types.model({
    id: types.identifier
  }),
  NewModel
)
```
An example for this could be a User:
```js
const NewUser = types.compose(
  types.model(...).actions(self => ({
    save: flow(function* save() {
      const { id } = yield self.genericSave()
      self = ExistingUser.create({ id, ...self })
    })
  })),
  NewModel
)
const ExistingUser = types.compose(..., ExistingModel)
const Store = types.model({
  currentUser: types.union(NewUser, ExistingUser)
})
```
In the above example, the `currentUser` can start out as a `NewUser` without an id and then become an `ExistingUser` with an id.

Is this a wrong approach?

**Comment by tmocellin** [comment]
I don't really know if it's wrong approach. But it seems complicated for me. But I don't have answer for you sorry.

**Comment by garrett-gottlieb** [comment]
I'm going to close this for now but open to more ideas. I'm using the type composition to compose two different models, `NewModel` and `ExistingModel`, as shown above.
