### ISSUE TITLE
Can't remove item from array.

### ISSUE THREAD

**Issue by victorvarenic** [mobxjs/mobx-state-tree#1457]
When I'm trying to remove item from array I got this error

`Error: [mobx-state-tree] Cannot modify 'BudgetCategory[]@/budgets/0/outcomes [dead]', the object is protected and can only be modified by using an action.

fail$1
    mobx-state-tree.module.js:3101:21
ObjectNode.prototype.assertWritable
    mobx-state-tree.module.js:1539:25
ArrayType.prototype.willChange
    mobx-state-tree.module.js:4251:28
interceptChange
    mobx.module.js:2988:37
ObservableArrayAdministration.prototype.spliceWithArray
    mobx.module.js:3157:41
arrayExtensions.splice
    mobx.module.js:3284:43
arrayExtensions.remove
    mobx.module.js:3339:24
deleteOutcome
    budget.ts:95:27
deleteOutcome
    [native code]:0
executeAction
    mobx.module.js:907:24
res
    mobx.module.js:899:29
runMiddleWares
    mobx-state-tree.module.js:2562:40
runWithActionContext
    mobx-state-tree.module.js:2425:30
res
    mobx-state-tree.module.js:2452:36
onPress
    BudgetPageOutcomes.tsx:76:31
RCTAlertManager.alertWithArgs$argument_1
    Alert.js:169:19
invokeCallbackAndReturnFlushedQueue
    [native code]:0`

But used to it works. I've tried splice also and got the same error. 

There some code 

<img width="482" alt="Снимок экрана 2020-01-17 в 12 50 21" src="https://user-images.githubusercontent.com/45688357/72607285-0b0c0180-3929-11ea-8e94-ae31efcdce5d.png">

<img width="631" alt="Снимок экрана 2020-01-17 в 12 51 08" src="https://user-images.githubusercontent.com/45688357/72607271-ff203f80-3928-11ea-80e3-3def84b271f8.png">

**Comment by mweststrate** [comment]
> budgets/0/outcomes [dead]'

From the error it looks like the budge instance you are interacting with,
is no longer part of your state tree.

**Comment by victorvarenic** [comment]
I can't remove it because it doesn't already exist? But how

**Comment by mweststrate** [comment]
I cannot tell you that from two screenshot. Please provide a minimal reproduction, or check what you changed in your sources if it used to work before.

**Comment by victorvarenic** [comment]
Bug reproducing on android only, there no anything special. Almost all that I have I've added to this report. Maybe I should send something concrete?

**Comment by mweststrate** [comment]
Sorry, I don't do that kind of things. There are to many devs using
packages for that. But you can do some checking in your app, like seeing if
isAlive (https://mobx-state-tree.js.org/API/#isalive) and getRoot return
what you expect them to return? MST is platform agnostic, so probably there
is some time issue / async code involved and this event handler might run
at a different time or on a different tree than you are expecting so far
(for example it might hold on to a tree that existed before hot reloading
your component or something like that, did you try to disable fast refresh
for example?)

**Comment by victorvarenic** [comment]
Ok, thank you. IsAlive helps. I don't know why but seems like android called my handler more that one time.
