### ISSUE TITLE
Reusing actions in extend with other actions defined through .actions

### ISSUE THREAD

**Issue by Aryk** [mobxjs/mobx-state-tree#1460]
This does not work even though I'm using +this+.

```ts
const resetStoreExtension = self => {
  actions: {
    resetStore() {}
}
};
types.model("Model").extend(resetStoreExtension).actions(self => {
  this.resetToDefault() { this.resetStore() }
})

```

**Comment by mweststrate** [comment]
You should us self. Syntactical your code doesn't make really sense to me.
I think you forgot a return?

Op do 23 jan. 2020 08:51 schreef Aryk Grosz <notifications@github.com>:

**Comment by Aryk** [comment]
oh, that's right, I should use +self+. I just wrote it up here in the ticket to demonstrate the example. Ok I will use +self+. Thanks for your help!
