### ISSUE TITLE
Add search functionality to the documentation

### ISSUE THREAD

**Issue by ivandotv** [mobxjs/mobx-state-tree#1462]
**_Feature request_**

Add search functionality to the documentation site.

**Is your feature request related to a problem? Please describe.**

It would be great if we could implement the search for the site, basically, I always need at least three clicks and then `ctrl+f` to find what I'm looking for on the site.

**Describe the solution you'd like**

I believe that the documentation site is made via *docusaurus.io*, and they have a way of [integrating algolia search](https://docusaurus.io/docs/en/search#__docusaurus) (which is great) for full site search.

**Are you willing to (attempt) a PR?**
* [x] Yes
* [ ] No

**Comment by coolsoftwaretyler** [comment]
Hey @ivandotv - sorry no one got back to you on this, but I do think the MST site is searchable these days, so I'm going to close this out.
