### ISSUE TITLE
کیرم تو mobx-state-tree

### ISSUE THREAD

**Issue by arman94** [mobxjs/mobx-state-tree#1465]

**Comment by jaythomas** [comment]
Can anyone translate?

**Comment by mweststrate** [comment]
From Google Translate:

> I'm in the mobx-state-tree
> 
> Cream in the package you wrote
> Karam from the width of the egg concept that you cut the package

Depending on your culinary taste that sounds either really good or really bad.

@arman94  would you mind translating the issue? Otherwise it will be closed. Thanks!

**Comment by creativefctr** [comment]
@mweststrate
Please close this issue and report the user. It contains swear words and strong language in Persian. And insults for @mweststrate
