### ISSUE TITLE
Error: [mobx-state-tree] No matching type for union (string | null?)

### ISSUE THREAD

**Issue by chemitaxis** [mobxjs/mobx-state-tree#1467]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

Hi @mweststrate @mattiamanzati  @xaviergonz we are having some problem with a bug, that we can't understand very well. I have read all the docs, and read the code, but I don't know why this error can happens:

> Error: [mobx-state-tree] No matching type for union (string | null?)

This is the action where fail:

```
    const setDelaySelected = value => {
      self.delaySelected = value;
    };
```

And this is my store:

```
const AnimationStore = types
  .model('AnimationStore', {
    typeSelected: types.maybeNull(types.string),
    directionSelected: types.maybeNull(types.string),
    effectSelected: types.maybeNull(types.string),
    delaySelected: types.maybeNull(types.string),
    durationSelected: types.maybeNull(types.number),
    buffer: types.optional(Buffer, {}),
    isPreviewing: false
  })
```

Can you please tell me how can I debug this? Thanks.

**Comment by mweststrate** [comment]
the most likely explanation is that `value` is neither a string or `null`. I'd just put a debugger statement or watch expression above that assignment, and see what value you get there (note that `undefined` is not `null` and MST won't coerce it to it)

**Comment by chemitaxis** [comment]
Thanks @mweststrate I will close the issue, have a great day!
