### ISSUE TITLE
Small broken link in docs

### ISSUE THREAD

**Issue by cmdcolin** [mobxjs/mobx-state-tree#1468]
From https://mobx-state-tree.js.org/overview/api

Links to https://mobx-state-tree.js.org/overview/docs/middleware.md should probably be https://mobx-state-tree.js.org/concepts/middleware

**Comment by mweststrate** [comment]
PR welcome!

Op wo 12 feb. 2020 20:15 schreef Colin Diesh <notifications@github.com>:

**Comment by cmdcolin** [comment]
Close, if interested see #1470
