### ISSUE TITLE
Issue determining union type

### ISSUE THREAD

**Issue by garrettg123** [mobxjs/mobx-state-tree#1475]
**_Bug report_**

I'm trying to cache navigation from react-navigation but the model being cached as a param isn't being parsed as such.

* [X] I've checked documentation and searched for existing issues
* [X] I've made sure my project is based on the latest MST version
* [ ] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**

```js
const getParamTypeFromJson = json => {
  const identifier = json.id
  console.log({
    isMyModel: MyModel.is(json),
  })
  return MyModel
}

export default types
  .compose(
    types
      .model({
        params: types.maybe(
          types.map(
            types.union(
              { dispatcher: getParamTypeFromJson },
              MyModel
            )
          )
        ),
      })
      .actions(self => ({
        setParams(params) {
          self.params = params
        },
```

**Describe the expected behavior**

`params` should be set without throwing an error if `MyModel.is(json) === true`

**Describe the observed behavior**

`Error while converting { paramName: { id: 1, ... } } to (map<string, MyModel> | undefined)`: snapshot { paramName: { id: 1, ... } } is not assignable to type: (map<string, MyModel> | undefined)

**Comment by coolsoftwaretyler** [comment]
Hey @garrettg123 - sorry it's been so long without a reply here. I totally understand if you've moved past the issue, but if this is still relevant to you, could you please post a reproduction of the issue? Without seeing the Model, it's tough for me to get started troubleshooting for you. It would be great if you could fork https://codesandbox.io/s/y64pzxj01 and demonstrate what's going on.

If you figured it out, we'd also love to have you post the solution here for other folks in the future. If it is a bug, we can tackle it.

I'll close this out in about two weeks if I don't hear back.

Thanks!

**Comment by coolsoftwaretyler** [comment]
Been about two weeks - I'm gonna close this one out. Sorry we couldn't help more!
