### ISSUE TITLE
Don't rely on setImmediate

### ISSUE THREAD

**Issue by KevinSjoberg** [mobxjs/mobx-state-tree#1477]
**_Bug report_**

* [X] I've checked documentation and searched for existing issues
* [X] I've made sure my project is based on the latest MST version
* [X] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**

https://github.com/KevinSjoberg/mobx-state-tree-reproduction

**Describe the expected behavior**

I expect the minimal reproduction to run without throwing an error.

**Describe the observed behavior**

The minimal reproduction throws an error about `setImmediate` not being defined.

    Unhandled Promise Rejection: ReferenceError: Can't find variable: setImmediate

Given that the [installation instructions](https://mobx-state-tree.js.org/intro/installation) state it's compatible with **any ES5 environment** I would expect it not to rely on [setImmediate](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate) which requires a polyfill for all browsers except recent builds of Internet Explorer and Node.js 0.10+.

I know the [flow](https://mobx-state-tree.js.org/API/#flow) function require both [Generator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator) and [setImmediate](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate). Generators I can accept given the [adoption](https://caniuse.com/#search=generators) but `setImmediate` isn't likely to be adopted.

Relevant statements taken directly from the MDN above.

> This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

> This method is not expected to become standard, and is only implemented by recent builds of Internet Explorer and Node.js 0.10+. It meets resistance both from Gecko (Firefox) and Webkit (Google/Apple).

**Comment by isaachinman** [comment]
@mweststrate Wondering if there's any official response to this? I just noticed errors in my console after pulling in `flow`.

**Comment by mweststrate** [comment]
Sorry didn't look into it, currently too busy working on MobX 6, but feel
free to open a PR.

Op za 11 apr. 2020 20:02 schreef Isaac Hinman <notifications@github.com>:

**Comment by isaachinman** [comment]
@mweststrate Sure, would like you like to see complete removal of `setImmediate`, or simply pull in something like [this](https://github.com/YuzuJS/setImmediate)? There only seem to be four occurrences of `setImmediate` this in repo, one of which is in a test.

**Comment by mweststrate** [comment]
I think a simple fallback to setTimeout(fn, 1) would suffice in our case

**Comment by isaachinman** [comment]
Fixed by #1501.

**Comment by xaviergonz** [comment]
What about using queueMicrotask where available before falling back? (modern node and browsers) 

https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/queueMicrotask

**Comment by isaachinman** [comment]
@xaviergonz Is the perf on `queueMicrotask` better than `setTimeout`?

**Comment by xaviergonz** [comment]
Yes, they are micro tasks rather than full blown tasks, so they are higher priority and also they are not throttled sometimes by the browser

**Comment by isaachinman** [comment]
Sure, I can add that to the fallback sequence if @mweststrate agrees.

**Comment by xaviergonz** [comment]
Btw, in theory when available it is an even better alternative than setImmediate itself, since setImmediate also creates a full task

**Comment by mweststrate** [comment]
sounds fine, you can check on MDN first if there any circumstance in which
setImmediate is not available but microqueues are?

**Comment by xaviergonz** [comment]
Older versions of node come to mind

**Comment by xaviergonz** [comment]
Ah sorry, read it backwards. QueueMicrotask is available in modern browsers but setImmediate is not for example

**Comment by isaachinman** [comment]
@xaviergonz Done, mind reviewing?

**Comment by KevinSjoberg** [comment]
I guess we can close this now since the pull request is merged?
