### ISSUE TITLE
can't getParent in `.volatile()` - Failed to find the parent of AnonymousModel

### ISSUE THREAD

**Issue by wildeyes** [mobxjs/mobx-state-tree#1478]
**_Bug report_**
`[mobx-state-tree] Failed to find the parent of AnonymousModel@<root> at depth 1`

* [X] I've checked documentation and searched for existing issues
* [X] I've made sure my project is based on the latest MST version
* [X] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/failed-to-find-the-parent-of-anonymousmodel-10s8w

**Describe the expected behavior**
I'll get TodoStore

**Describe the observed behavior**
runtime error

**Comment by Romanior** [comment]
Volatile is not meant to store  persistable state, the short answer: you creating MST outside of the tree, so there is no parent (you can verify it by calling `isRoot`);

If you need for some reasons alone(detached) MST you should not try to get its parent.
But it seems you need it, so the best solution would be to move property to `model` of your TodoStore, e.g. `subTodo: types.maybe(SubTodo)` and create it with some action on this MST e.g. `createBlankSubTodo` so it would be the part of root MST.

**Comment by wildeyes** [comment]
Gotcha.
