### ISSUE TITLE
[mst-middlewares][asReduxStore] Actions do not propagated to sub models

### ISSUE THREAD

**Issue by DQvsRA** [mobxjs/mobx-state-tree#1480]
**_Bug report_**
Using MST with asReduxStoer actions registered in subsequent models do not called when dispatch is called, error instead - `Action 'ACTION_TYPE' does not exist in ''`

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/mobx-state-tree-todolist-efnvp

**Describe the expected behavior**
1. Action propagated to subsequent models
2. `dispatch` method available from store for all models (self.dispatch)

**Describe the observed behavior**
Error when dispatch action registered in sub-models

What I want to achieve is to be able to send "messages" (call actions) from different models without referencing to the root (not using `getRoot(self)`) - something like pub/sub mechanism, but inside the state tree.

**Comment by DQvsRA** [comment]
Hey MST team, any response to my question?

**Comment by mweststrate** [comment]
the middleware only supports actions that are exposed at the root of the
store, as Redux has no concepts of paths

**Comment by DQvsRA** [comment]
@mweststrate thanks for your answer.
