### ISSUE TITLE
Cannot find module 'mobx-state-tree'

### ISSUE THREAD

**Issue by brikou** [mobxjs/mobx-state-tree#149]
**TS Compilation is OK**

```sh
cd $(mktemp -d)

yarn add mobx mobx-state-tree typescript

cat << EOF > tsconfig.json
{
    "compilerOptions": {
        "module": "commonjs"
    }
}
EOF

cat << EOF > hello.ts
import { types } from "mobx-state-tree";

const Foo = types.model({ id: types.identifier() });

console.log(Foo);
EOF

yarn tsc -- --pretty
```

**TS Compilation is KO when not using commonjs**

```sh
cat << EOF > tsconfig.json
{
    "compilerOptions": {
        "module": "es2015"
    }
}
EOF

yarn tsc -- --pretty
```

> hello.ts(1,23): error TS2307: Cannot find module 'mobx-state-tree'.

**Comment by EricForgy** [comment]
Any workaround? 😅

**Comment by EricForgy** [comment]
`"include": [ "**/*.ts" ],`

That seemed to fix my problem. Is that "ok"?

**Comment by mweststrate** [comment]
Does `yarn tsc -- hello.ts` make a difference?

**Comment by mweststrate** [comment]
Ah module resolution needs to be set to `node`, it is not the default when using es2015 modules. Which makes sense, see: https://www.typescriptlang.org/docs/handbook/module-resolution.html, module resolution strategies.

**Comment by EricForgy** [comment]
Ah ha! Thanks. That seems to do the trick for me :)

Maybe worth adding a bit to the README? If so, I can maybe take a shot at a PR (but I'm a newb and not sure I understand very well) 😅
