### ISSUE TITLE
NextJS example with Static Optimization

### ISSUE THREAD

**Issue by kiwicopple** [mobxjs/mobx-state-tree#1492]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

Hey, I see that you previously created a [NextJS example](https://github.com/mobxjs/mobx-state-tree/issues/27#issuecomment-347496795) which is working great.

The way it is set up uses `getInitialProps` in the `_app.js` file: https://github.com/zeit/next.js/blob/9730be67340d16e2e0c4a936c483326c48be7b1a/examples/with-mobx-state-tree/pages/_app.js#L8

This actually disables Automatic Static Optimization though: 
![image](https://user-images.githubusercontent.com/10214025/77752075-d2438380-7061-11ea-8df9-0c1a06935108.png)

Is there a way to use this `mobx-state-tree` without using `getInitialProps` in _app.js`?

Thanks in advance for the help / pointers

**Comment by chriswolmarans** [comment]
@kiwicopple I've made an example using NextJS using React.Context and `useMst` hook (without using `getInitialProps`) - https://github.com/chriswolmarans/next-starter

I'm still experimenting and haven't used it in a real app/site so use with caution.

**Comment by coolsoftwaretyler** [comment]
Thanks @kiwicopple and @chriswolmarans!

Looks like this is all sorted out and has been inactive for a while, so I'm gonna close out the issue.
