### ISSUE TITLE
how to define model with existing interface?

### ISSUE THREAD

**Issue by rainmanhhh** [mobxjs/mobx-state-tree#1493]
**_Question_**

* [x ] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

There are many interfaces auto generated by swagger(open-api) like this:
```ts
export interface UniUser {
    id?: string;
    idCard?: string;
    perms?: Array<string>;
    phone?: string;
    realName?: string;
    roles?: Array<string>;
    treatCard?: string;
    type?: UniUserTypeEnum;
}
export enum UniUserTypeEnum {
    Staff = 'Staff',
    AuthUser = 'AuthUser',
    PubUser = 'PubUser'
}
```
Is it possible to define a model with a field like `users: UniUser[]`?
```ts
types.model('MyStore', {
  foo: 'bar',
  users: types.array(...) // don't know how to implement UniUser[]
})
```

**Comment by mweststrate** [comment]
You have to create / generate a model for UniUser. MST can't reason about
interfaces as they don't exist at runtime. There are tools to generate MST
models from JSON that you could use. I can imagine that generating from
swagger spec wouldn't be too hard either.

Op ma 30 mrt. 2020 10:42 schreef rainmanhhh <notifications@github.com>:

**Comment by jvaclavik** [comment]
Mapping itself is maybe slow but I think it doesn't have to be the biggest problem here.

If you have the following types:
`Instance<typeof MyStore>` and `UniUser`, they are not identical and you have to re-type everything to `Instance<typeof MyStore>` which is almost impossible if you get `UniUser` interface and other utils from another repo.

Or is there a way how to do it properly with mobx-state-tree?

**Comment by jonbnewman** [comment]
I believe what you want is a command line tool which reads the AST of the generated swagger interface and translates that into a mobx-state-tree `model`...I don't think such a tool exists at the moment.

**Comment by coolsoftwaretyler** [comment]
Hey folks - I'm going to close this out. I don't think this is an issue in MST, but definitely sounds like a useful idea or utility.

If anyone has a good tool for this, I definitely encourage you to post about it in the [discussions](https://github.com/mobxjs/mobx-state-tree/discussions).
