### ISSUE TITLE
snapshotProcessor.is does not handle state tree nodes

### ISSUE THREAD

**Issue by KevinSjoberg** [mobxjs/mobx-state-tree#1494]
**_Bug report_**

* [X] I've checked documentation and searched for existing issues
* [X] I've made sure my project is based on the latest MST version
* [X] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**

https://codesandbox.io/s/pedantic-gagarin-fhkfv

**Describe the expected behavior**

The `snapshotProcessor` type should correctly identify state tree nodes when using `.is()`.

**Describe the observed behavior**

It does not work. In https://github.com/mobxjs/mobx-state-tree/pull/1323, `is` was introduced on the snapshotProcessor itself. However, there is a subtle bug. If `thing` is a state tree node (`isStateTreeNode(thing)`), it gets run through the `preProcessor` step again (we should assume that state tree nodes have already been processed).

In the original pull request this wasn't a problem because the `preProcess` step is simple. When we're calling `ProcessedModel.is(processedModel)` it calls the `preProcess` step with the state tree node and `x` is already an number so it will effectively just return a new snapshot. However, in a more complicated example such as my reproduction it does not work due to the fact that we're renaming attributes. When the `preProcess` step is called with the state tree node, the expected attributes are no longer present.

**Comment by KevinSjoberg** [comment]
I'm not sure what the "right" approach here is, but here is an attempt to solve the problem, https://github.com/mobxjs/mobx-state-tree/pull/1495. Feel free to give pointers if this isn't the right approach. 🙂

**Comment by mweststrate** [comment]
Fixed in 3.16.0
