### ISSUE TITLE
`number[]` cannot be assigned to number[]

### ISSUE THREAD

**Issue by PabloGracia** [mobxjs/mobx-state-tree#1496]
**_Bug report_**

* [X] I've checked documentation and searched for existing issues
* [X] I've made sure my project is based on the latest MST version
* [X] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**

https://codesandbox.io/s/floral-leaf-ybo1y

**Describe the expected behavior**

I have two variables in the store, defined as: 
``` javascript
data_1: types.array(types.number);
data_2: types.array(types.number);
```
One of these variables, **data_1** will have a constant value, and **data_2** can be equal to **data_1** or to another variable, depending on some conditional. Both variables have *the same type* as per Mobx-State-Tree specifications. To implement this functionality, I include an action, **action_1** in the store to assign **data_1** to **data_2**:
```javascript
export const Data = types
  .model({
    data_1: types.array(types.number),
    data_2: types.array(types.number)
  })
  .actions(self => ({
    action_1() {
      self.data_2 = self.data_1;
    }
  }));
```

I then create the root store, and initialize it with some values:
```javascript
const RootModel = types.model({
  mstData: Data
});

export const rootStore = RootModel.create({
  mstData: {
    data_1: [-1, -2, -3, -4, -5, -6],
    data_2: []
  }
});
```
And include a button, that once triggered will fire the action included in the store. Once this button is clicked, what I expect is to see a log in the console with a snapshot of the store, stating (something similar to):
```javascript
{
  data_1: [-1, -2, -3, -4, -5, -6],
  data_2: [-1, -2, -3, -4, -5, -6]
}
```

**Describe the observed behavior**

However, what I get is the following error:
```
Error
[mobx-state-tree] Error while converting <-1,-2,-3,-4,-5,-6> to `number[]`:

    value of type number[]: <-1,-2,-3,-4,-5,-6> is not assignable to type: `number[]`, expected an instance of `number[]` or a snapshot like `number[]?` instead. (Note that a snapshot of the provided value is compatible with the targeted type)
```

As both variables had their types defined in the mst model, I would expect this to function flawlessly. What's the reason behind one of the variables being `number[]` and the other `'number[]'`? I assume this behavior is not intended and it's a bug.

P.D. I was using the latest version of mobx-state-tree: ```"mobx-state-tree": "^3.15.0"```

**Comment by RainerAtSpirit** [comment]
If `data_1` and `data_2` should use the same type then you have to define the number array type upfront and reuse it.

```javascript
const numberArray = types.array(types.number)

export const Data = types
  .model({
    data_1: numberArray,
    data_2: numberArray
  })
  .actions(self => ({
    action_1() {
      self.data_2 = self.data_1
    }
  }))
```

https://codesandbox.io/s/modest-fast-tv29h

**Comment by PabloGracia** [comment]
Hmm, I'm not sure I understand why that solution works... Eventually, it is just adding an extra step and both `data_1` and `data_2` are equal to the same type as before, `types.array(types.number)`, aren't they? Shouldn't it work (theoretically speaking) directly without the middle `numberArray` variable? Or said in a different way, is this the intended behavior or is it a not-optimal solution?

**Comment by RainerAtSpirit** [comment]
The action retries to assign self.data_1 = self.data_2, which throws as they are not of the same type. 
If you want to reuse types then yes, this is the recommended approach.

```
// defining two types
const numberArray = types.array(types.number)
const numberArray2 = types.array(types.number)

console.log(numberArray === numberArray2)

export const Data = types
  .model({
    data_1: numberArray,
    data_2: numberArray2
  })
```


```
// reusing types
const numberArray = types.array(types.number)

console.log(numberArray === numberArray)

export const Data = types
  .model({
    data_1: numberArray,
    data_2: numberArray
  })```

**Comment by Romanior** [comment]
@PabloGracia When declaring complex types yes, think about this as creating instance, to moke it more obvious, you won't expect this to work neither.

```javascript
const Todo = types.model({
   task: types.string
})
const OtherTodo = types.model({
   task: types.string
})

export const Data = types
  .model({
    data_1: Todo,
    data_2: OtherTodo
  })
  .actions(self => ({
    action_1() {
      self.data_2 = self.data_1;
    }
  }));

 ```

**Comment by PabloGracia** [comment]
Okay, I think I understand now the reason behind it. It seems it's not a bug, but an intended behavior, so I'll be closing this issue. Thanks for your answers @RainerAtSpirit @Romanior !
