### ISSUE TITLE
Replacing entire state of model doesn't work

### ISSUE THREAD

**Issue by isaachinman** [mobxjs/mobx-state-tree#1499]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/react-typescript-vq29d?file=/src/store.ts

**Describe the expected behavior**
There are cases where it makes good sense to want to replace a model's entire state at once - eg after an API request, etc. I would expect the TS types to support this use case.

**Describe the observed behavior**
If I attempt to reassign `self` in an action, I get the `'self' is declared but its value is never read` warning from TS. I assume this is down to some overly tricky typing that has gone on behind the scenes.

## Update:

It's more than TS typings - it simply doesn't work.

This, however, will work:

```jsx
setUser: (user) =>
      Object.entries(user).forEach(([key, value]) => (self[key] = value))
```

I feel as though I'm missing something here, but there must be an easy way to replace an entire model, surely?

**Comment by mweststrate** [comment]
The issue here is unrelated to MST, but how javascript works; you are
reassigning the function local variable self, but you are doing nothing
with the object that self originally pointed to, so the typescript warning
is entirely correct. Try Object.assign(self, newData) instead (or use
applySnapshot which is the MST way of doing the same)

**Comment by isaachinman** [comment]
Excellent explanation - thanks!
