### ISSUE TITLE
Selector pattern in MST

### ISSUE THREAD

**Issue by jasonlimantoro** [mobxjs/mobx-state-tree#1500]
First of all, this library is a superb library! It is one of few libraries that scratch a lot of itches. Kudos to every maintainer (and the author as well)!

**_Question_**
I have used redux a lot in the past. One underrated pattern from Redux that I really like is the **selector pattern** because it just makes the UI unaware of the state structure (A big game changer).

However in MST, AFAIK, there is no suggested pattern with regards to accessing store from the UI.
Essentially, we might end up doing this

```jsx
function UI(){
  const {
     auth: { token, username }
     posts: { items, postCount, .....}
  } = useMst(); // this is a hook for accessing root store
 return observer(() => (
    // your observer react component
 ))
}
```
It works surprisingly well though. However, the UI now is tightly coupled to the root store structure.
And as you imagine, we can have a lot of those components who expect the store to be in this shape.

```
{
      auth: {
         token
         username
      }
      posts: {
         items
         postCount
     }
}
```
Any change to the store shape will destroy your whole entire app, almost immediately.

I've found some pattern to mitigate this issue, by using, well, **selectors**.
For example,
```ts
// auth.selector.ts

// standard selector
const selectToken = (store: RootStore) => store.auth.token;
const selectUsername = (store: RootStore) => store.auth.username;
// etc. (you get the idea)

// this is the real power
const useComposeStore = (...selectors) => {
  const store = useMst();
  return selectors.reduce((data, select) => {
    return [...data, select(store)];
  }, []);
};

```
And so, in your component you can use it like so
```jsx
function UI(){
  const [token, username] = useComposeStore(selectToken, selectUsername);
  return observer(() => (
    // your observer react component
 ))
}
```
Now the component is completely agnostic of the state structure.
If there is any change to the store shape, of course, your app will still crash, but now you have a centralized selector, that can be changed very easily and very quickly (remember these selectors should be put near the store in your folder structure).

I've implemented this pattern and really love it. No issues, the rendering is still as efficient as before.

I just want to know whether there are any pitfalls that I'm currently missing about this pattern.
Cheers!

* [x] I've checked documentation and searched for existing issues
* [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

**Comment by jasonlimantoro** [comment]
Of course you can even group selectors into a more generic selector if that makes sense for your application.

```js
const selectLoginData = (store: RootStore) => ({
  loginStatus: selectLoginStatus(store),
  login: selectLogin(store), // even action can also be included
  logoutReason: selectLogoutReason(store),
});
```
For example here is how to use it in your component
```jsx
function UI(){
  const [{ loginStatus, login, logoutReason }] = useComposeAuth(selectLoginData);
  return observer(() => (
    // your observer react component
 ))
}
```

**Comment by mweststrate** [comment]
See `computed` in MobX. They achieve the same but a bit smarter 😊

Op zo 12 apr. 2020 06:26 schreef Jason Gunawan Limantoro <
notifications@github.com>:

**Comment by jasonlimantoro** [comment]
Hi @mweststrate thanks for stopping by!


Do you mean the `views` in MST?
Yes I am aware of that.
However, even using the views still exposes the state structure to the component.

For example
```jsx
const AuthModel = types.model({
   token: types.optional(types.string, "")
}).views((self) => ({
   get SignedToken(){
        return sign(self.token)
   }
   })
})

const RootStore = types.model({
    auth: types.optional(AuthModel, {})
})

```

In your component you still need to know that the root store shape is as follows:

```
{
    auth: {
        signedToken
    }

}
```
Am I right to say that?

**Comment by terrysahaidak** [comment]
You don't need any selectors in Mobx/MST.
The biggest problem with this code isn't a dependency on the root store, but subscribing to the stuff you aren't using in the 
```

**Comment by terrysahaidak** [comment]
Also, for accessing different parts of the MST store, I used to have lots of `useStore` hooks.

For example, I have the root store like this:

```js
const RootModel = types.model({
  auth: types.optional(AuthModel, {}),
  ui: types.optional(UiModel, {}),

  entities: types.optional(EntitiesModel, {}),
});
```

Then I have the `useRootModel` hook which returns that root model from the React.createContext.

But also I have `useAuthModel`, `useUiModel` and  `useEntitiesModel` if I wish to access some parts of the root tree. They all use `useRootModel` under the hood.

The Entities model is a model which represents lots of collections - some observable maps of my entities - I store them all here but use references in other places.

So you can even create a hook for it:

```js
function useUserById(id) {
  const entitiesModel = useEntitiesModel();

  return entitiesModel.users.get(id);
}
```

**Comment by jasonlimantoro** [comment]
@terrysahaidak thanks for your input.

> The biggest problem with this code isn't a dependency on the root store, but subscribing to the stuff you may not using in the component

Of course, you only use selector for the piece of data that is needed by that component. I mean that's the whole idea of selector, to select relevant data, not all data.

Your example is completely valid. I am also thinking of using those kinds of hooks for selecting different tree (or subtree) from the whole mobx store. Hooks kinda does the selection.

**Comment by terrysahaidak** [comment]
If you're coming from Redux, the main point of the MST you should keep in mind – it's OOP programming and, I think, you should use all the benefits it gives you.
Just use `views` for most of the stuff as well as use all the `getParent` and etc to access different parts of the tree.

Also, views (computed values) are computed and they do really smart memoization for you out of box!

Just take a look at the talk I sent you above.

I mean in most of the cases you don't really need those `useSelector` stuff. Need a viewer username?

```js

const Avatar = observer(({ user }) => {
  return <img sr={user.avatarUrl} />
});

const UserInfo = observer(({ user }) => {
  return (
    <p>@{user.username}<p>
  );
});

// somewhere in the "UserPrifle"
const { viewer } = userViewerModel(); // viewer is the UserModel

return (
  <div>
    <Avatar user={viewer} />
    <UserInfo user={viewer} />
  </div>
);

```

Using this approach you'll have the best performance possible. Because if you change the viewer's username, only the UserInfo component is going to be rendered. Because you have accessed the `username` getter only there.

**Comment by jasonlimantoro** [comment]
@terrysahaidak Yes I understand your point.

Thank you very much for the valuable input.

**Comment by farwayer** [comment]
I like selector pattern too :smile_cat: 
So I made small library [mobx-select](https://github.com/farwayer/mobx-select) that uses `mobx-react-lite` under hood. Tested on many production projects.
But I prefer to use HOCs overs hooks for accessing data because of component re-usability. `app` is our mst store in example:

**avatar.js (external UI library component)**
```js
function Avatar({src}) {
  return <img src={src}/>
}

export default memo(Avatar)
```

**user-avatar.js (our app component)**
```js
export default select(Avatar, (app, props) => {
  const src = app.users.get(props.id)?.avatar
  return {src}
})
```
Of course you can create selector function (even with fetch logic):
```js
function userSelector(app, props) {
  const user = app.users.get(props.id)
  if (!user) {
    app.fetchUser(props.id)
  }
  return {user}
}

select(User, userSelector)
```

**Comment by coolsoftwaretyler** [comment]
Hey folks!

Thanks for all the great discussion here. Special thanks to everyone championing the MST approach to this and dropping examples and resources.

I'm going to close this issue out. But please feel free to open up discussions if y'all wanna talk more about this kind of stuff.
