### ISSUE TITLE
Internal calls to a model action does not trigger onAction event

### ISSUE THREAD

**Issue by FabriceReynolds** [mobxjs/mobx-state-tree#1508]
**_Bug report_**

* [*] I've checked documentation and searched for existing issues
* [*] I've made sure my project is based on the latest MST version

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/sweet-blackwell-bfbc7?file=/src/index.js

**Describe the expected behavior**
I'm not sure if this is by design but I was expecting that when calling an action from inside or outside of a model, it would trigger an onAction event.

**Describe the observed behavior**
No onAction event is triggered when an action is called from inside of the model (self.anAction()) This is observed whether the model is declared through composition or through model.types.

**Comment by Romanior** [comment]
@FabriceReynolds The sandbox you provided shows correct behavior. I see correct console.log output, Is something else you are looking for?

<img width="916" alt="Screen Shot 2020-04-17 at 08 26 53" src="https://user-images.githubusercontent.com/490365/79535160-4e3f5300-8085-11ea-94dd-0d31a60340d0.png">

**Comment by FabriceReynolds** [comment]
I was expecting another log when the testStore.updateOne() calls the setOne() internally so three logs in total

**Comment by Romanior** [comment]
@FabriceReynolds Ouch, so the `onAction` is a "build-in" middleware which just created this way.
https://github.com/mobxjs/mobx-state-tree/blob/ef5f4cbf4733265cdf9b59b543ee9b786a022cf5/packages/mobx-state-tree/src/middlewares/on-action.ts#L243
check the condition about `rootId`;

If you need your code to work you would have to add your custom middleware, something like.
https://codesandbox.io/s/hopeful-kirch-gw3n4?file=/src/index.js

**Comment by FabriceReynolds** [comment]
I see, thanks for the quick and insightful answer. This works for me, in fact better as I can target the particular store I need with middleware whereas onAction has to target the root of the tree. 

I can go ahead and close this ticket.
