### ISSUE TITLE
How to use volatile with typescript

### ISSUE THREAD

**Issue by Ridermansb** [mobxjs/mobx-state-tree#1512]
Using `volatile` how can I add type ?

```
    .volatile(() => ({
        isRemoving: false, // should be boolean with false as defaut
        ref: undefined, /// Should be firebase.firestore.DocumentReference with undefined as default
    })
```
* [x] I've checked documentation and searched for existing issues
* [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

**Comment by mweststrate** [comment]
Use `undefined as X` etc

**Comment by Ridermansb** [comment]
Something like this?

`ref: undefined as undefined | firebase.firestore.DocumentReference,`

I tried but I received a error..

```
ESLint: 
Parsing error: Unexpected token, expected ","

  26 |         savingError: undefined,
  27 |         originalSnapshotJSON: '',
> 28 |         ref: undefined as undefined | firebase.firestore.DocumentReference,
     |                        ^
  29 |     }))
  30 |     .views((self) => ({
```

**Comment by mweststrate** [comment]
You probably need parens around that union. Or you might need to upgrade
eslint / enable typescript for eslint, since that is the one complaining

**Comment by richchurcher** [comment]
Replying to this because it took me a long time to realise that one can do this sort of thing:
```
  .volatile<{ isRemoving: boolean }>((self) => ({
    isRemoving: false
  })
```
So you can define interfaces for your volatile types. Hopefully this saves someone else some time!
