### ISSUE TITLE
UndoManager middleware not firing for targetStore actions

### ISSUE THREAD

**Issue by sis-dk** [mobxjs/mobx-state-tree#1514]
**_Bug report_**

* [✓] I've checked documentation and searched for existing issues
* [✓] I've made sure my project is based on the latest MST version
* [✓] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction.

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/bitter-water-0mruf?file=/src/index.js

**Describe the expected behavior**
Undo manager undo redo should work after an action modifies the tree

**Describe the observed behavior**
When history is placed within the tree, UndoManager's on action middleware is not fired for the targetStore (not even the afterCreate of UndoManager is called on root store creation). Having UndoManager as a separate tree works.

**Comment by goranmandiccrs** [comment]
Hi, @sis-dk , I've updated your codesandbox:
https://codesandbox.io/s/peaceful-dewdney-8z71k?file=/src/index.js
You should be good to go :)

**Comment by coolsoftwaretyler** [comment]
Hey @sis-dk - this MST issue has been open for a while. If it's still relevant to you and @goranmandiccrs's solution didn't help you, will you let us know and we can try to give additional help?

If that did fix things for you, let me know and I can close this out.

If I don't hear back in about two weeks, I'll close this issue out. Thanks, all!

**Comment by coolsoftwaretyler** [comment]
I'm gonna close this one out, although I've added the middleware label because we are evaluating where the middleware package fits into the overall strategy here.
