### ISSUE TITLE
type inferrence issue in mobx-state-tree

### ISSUE THREAD

**Issue by e-krebs** [mobxjs/mobx-state-tree#1515]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/mobx-state-tree-todolist-38rm0?file=/models/index.js

**Describe the expected behavior**
The issue happens when using an `index` file to re-export types from a folder.
In the example above, it's in the `models` folder.
What happens is:
- `TodoStore` imports `Todo` (and uses it in its model)
- `Todo` imports `Something` (and uses it in its model)

When, in `models/index.js`, `Todo` is exported with the following syntax:
```ts
export * from "./Todo";
```
we get the following error:
```text
[mobx-state-tree] The default value of an attribute cannot be null or undefined as the type cannot be inferred. Did you mean `types.maybe(someType)`?
```

When instead, you use the following syntax (commented in the sandbox `models/index.js`), it works:
```ts
import { Todo } from "./Todo";
export { Todo };
```

**Describe the observed behavior**
Both syntax should work.

And in fact, the first syntax causes a problem with the `Todo` type but perfectly work with the `Something` type.

Also, when using Typescript, the first syntax compiles with no problem, works as expected in vscode, but causes the same issue at execution time.

**Comment by mweststrate** [comment]
This is most likely a circular module import issue, where the import from
models isn't yet available when it is used in the declaration. This is not
really a MST problem, but a fundamental issue with JS modules :). As work
around `types.late` can be used at the place of the usage of the type. For
some background read
https://medium.com/visual-development/how-to-fix-nasty-circular-dependency-issues-once-and-for-all-in-javascript-typescript-a04c987cf0de

**Comment by e-krebs** [comment]
I did'nt know `types.late` and it indeed seems to fix the problem here ^^

Maybe it would be a good Idea to mention it in the error when there's an inference issue ?
