### ISSUE TITLE
having property and view with same name should be a type or runtime error

### ISSUE THREAD

**Issue by safareli** [mobxjs/mobx-state-tree#1537]
**_Feature request_**

**Is your feature request related to a problem? Please describe.**
if you have having property and view with same name it should be a type or runtime error as otherwise you will get this strange error: `TypeError: Object(...)(...).reportObserved is not a function`. also see: https://spectrum.chat/mobx-state-tree/general/help-with-error-typeerror-object-reportobserved-is-not-a-function~e92e6347-9a9c-4988-be2d-7a5fea653375?authed=true

**Describe the solution you'd like**
type should be changed such that compilation fails if you declare view with same name as prop, or at list guard against it in the lib and throw error in runtime

**Comment by zacharygriffee** [comment]
I agree with this. It is very difficult to infer the problem from the error shown. This issue helped me resolve my issue, but it would have been nice if there was a verbose error for this. Thanks safareli.

**Comment by coolsoftwaretyler** [comment]
Hey @safareli - I'm of the same opinion. I'm sorry it took so long for folks to get back to you here, but I'm going to toss some labels on this and see if we can get it on the todo list.

Would definitely accept a PR if you or anyone else is interested!

**Comment by BrianHung** [comment]
https://github.com/mobxjs/mobx-state-tree/blob/a1188ec3ab165d437ff16e0708df0214c2f8d694/packages/mobx-state-tree/src/types/complex-types/model.ts#L486-L508

Could probably check if the property is already defined in `self` before overriding in it views, and throw error if that's the case.

**Comment by coolsoftwaretyler** [comment]
We've got a PR for this one now! https://github.com/mobxjs/mobx-state-tree/pull/2057

Should be merged this weekend or next week.
