### ISSUE TITLE
talk-transcripts

### ISSUE THREAD

**Issue by comerc** [mobxjs/mobx-state-tree#154]
It is autosubtitres. PR's welcome.

1) [video](https://www.youtube.com/watch?v=ta8QKmNRXZM) - [text](https://github.com/comerc/about-mobx-state-tree/blob/master/TEXT.md)

2) [video](https://www.youtube.com/watch?v=rwqwwn_46kA) - [text](https://github.com/comerc/about-mobx-state-tree-2/blob/master/TEXT.md)

**Comment by mweststrate** [comment]
Thanks :) Not sure where they should be linked in the current state. But if somebody wants to dive into them and clean them up let me know :)
