### ISSUE TITLE
getParentOfType inside flow gives Typescript error

### ISSUE THREAD

**Issue by ErnoW** [mobxjs/mobx-state-tree#1542]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
Link to reproduction: https://codesandbox.io/s/zealous-field-hq5ck

```ts
const Child = types.model({}).actions(self => ({
  fetchName: flow(function* fetchName() {
    // As soon as url is used in a yield,
    // it will throws an error: "... because it does not have a type annotation and is referenced directly or indirectly in its own initializer"
    const url = getParentOfType(self, Parent);
    yield fetch(url);
  })
}));
```
```ts
const Parent = types.model({
  url: types.maybe(types.string),
  child: types.optional(types.late(() => Child), {})
});
```

tsconfig needs to have: 
```
"compilerOptions": {
  "strict": true,
}
```

**Describe the expected behavior**
When I get the data from `getParentOfType`, and use it inside a yield of a flow, I would like to not getting a typescript error.

**Describe the observed behavior**
The Parent and Child both get an error:
```
implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
```
This only happens when I use data from `getParentOfType` inside the `yield` of a `flow`, and strict mode is enabled in `tsconfig`. The functionality behaves correctly though. 

--- 
Related issue: https://github.com/mobxjs/mobx-state-tree/issues/1305 (closed but not solved)
Same issue referenced in a comment: https://github.com/mobxjs/mobx-state-tree/issues/1157#issuecomment-483624512

**Comment by antondomratchev** [comment]
@ErnoW Based on your example its hard to know what your expected behavior should be. The current code example doesn't really show the error nor does the referenced code annotate any TS types. Can you update the example to show the described error?

**Comment by miguelhrocha** [comment]
@ErnoW did you find a solution for this?
