### ISSUE TITLE
Github not showing proper release on homepage

### ISSUE THREAD

**Issue by cmdcolin** [mobxjs/mobx-state-tree#1548]
Github (new redesigned pages) says the "latest release" of this project is 0.6.3 released in 2017

![github com_mobxjs_mobx-state-tree](https://user-images.githubusercontent.com/6511937/87094688-4f5bc880-c20d-11ea-9e1a-8a7639175e2e.png)

Might be worth updating that somehow, looks stale to see it like that :)!

**Comment by taylorcjohnson** [comment]
Hi @cmdcolin - thanks for bringing this up! It looks like the "Release" section is showing the last version now - are you still seeing any problems?

**Comment by cmdcolin** [comment]
looks great, thanks!
