### ISSUE TITLE
snapshotProcessor and maybe not working as expected

### ISSUE THREAD

**Issue by mikecann** [mobxjs/mobx-state-tree#1550]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**

```typescript
const Model1 = types.model("Model1", {
  foo: types.string,
});

const Model1WithPreProcessor = types.snapshotProcessor(Model1, {
  preProcessor(snap: SnapshotIn<typeof Model1>) {
    // Snap should never be undefined here?
    expect(snap).toBeTruthy();

    return snap;
  },
});

const Model2 = types.model("Model2", {
  model1: types.maybe(Model1WithPreProcessor),
});

Model2.create({});
```

**Describe the expected behavior**

I shouldnt expect the `snap` variable in the preProcessor to ever be undefined according to the docs: https://mobx-state-tree.js.org/API/#snapshotprocessor

**Describe the observed behavior**

It is undefined in the above example

**Comment by mikecann** [comment]
Or is this expected behaviour? Should be docs be changed? Is the expected input type to `preProcessor` actually `any` ?

**Comment by mweststrate** [comment]
Yes this is expected; snapshot processors are applied before the union
chooses which kind of thing it is looking at, so in case of Maybe it can
indeed be called with undefined

**Comment by mikecann** [comment]
@mweststrate okay, do you want me to leave this issue open to remind that the docs should be changed because its really not obvious that this is expected behaviour when you look at the docs?

**Comment by mweststrate** [comment]
Please rather submit a pull request with updates to the docs or otherwise
just close the issue.
