### ISSUE TITLE
Updating from old mobx version

### ISSUE THREAD

**Issue by nrcaz** [mobxjs/mobx-state-tree#1552]
Hi,

I m having trouble updating an old project in mobx state tree `3.2.2` to `3.17.2`

I get this error 
```
[mobx-state-tree] Error while converting `{"key":"champ_de_saisie1","type":"text","value":""}` to `AnonymousModel`:

    at path "/key" value `undefined` is not assignable to type: `identifier` (Value is not a valid identifier, expected a string).
    at path "/type" value `undefined` is not assignable to type: `"text"` (Value is not a literal "text")
```
Which doesn't make any sense since key and type are clearly not undefined.

I m using a types.union with a dispatcher to assign the correct model according to `type`.

The model is a types.compose
```
const CommonPending = types
  .model('Pending', {
    key: types.identifier,
    lastEdit: types.maybeNull(types.Date),
    geoloc: types.maybe(GeolocItem),
    pushedData: false,
  })

const TextPending = types.compose(
  CommonPending,
  types
    .model('TextPending', {
      type: types.literal('text'),
     ...
```

ModelType.is method always return false for the old data ( from before the update ), so i m suspecting a change in the data format or something.

I tried to find documentation on updating mobx to latest versions but didn't really found anything.

I would really appreciate some advices or a link to any documentation to solve my problem.

Regards.

**Comment by mweststrate** [comment]
Please create a small codesandbox reproduction when filing issues.

**Comment by nrcaz** [comment]
It works fine in codesandbox, sorry if i wasn t clear enough.

The code itself works fine in every version, the problem comes from when migrating from one version to another.

**Comment by nrcaz** [comment]
It worked fine on code sandbox,

I finally found the problem in some preProcessSnapshot badly written x)

I close the issue
