### ISSUE TITLE
types.reference not resolving the reference?

### ISSUE THREAD

**Issue by special-character** [mobxjs/mobx-state-tree#1556]
I am writing a search function that returns an array of `ModelA` or `ModelB` but when I use the references in my component, the reference is still a string. From the docs, I was expecting this to be the actual `ModelA` or `ModelB` so I feel like I am doing something wrong.

In my root store I create an array of references like this:

```
searchResults: types.array(
      types.union(
        types.late(() => types.reference(ModelA)),
        types.late(() => types.reference(ModelB)),
      ),
),
```

When I get them back from the request they are loaded into the store (I check by doing `store.modelBs.get(<one of the ids>)` but the component still gets the array of strings:

<img width="342" alt="Screen Shot 2020-07-24 at 14 13 47" src="https://user-images.githubusercontent.com/5407471/88435998-3845da80-cdb8-11ea-9aa8-54546f29d57d.png">

Does anyone know if this is valid/what I am doing wrong here? It feels like this should work but not sure why it doesn't. Thanks!

**Comment by terrysahaidak** [comment]
Hi. try to use late for the actual model instead.

**Comment by special-character** [comment]
Hey @terrysahaidak thanks for the suggestion. This got me an actual error message which led me to understand it better.

After using just the model (instead of reference), I got an error message like: `error resolving <some id> to AnonymousModel`. After making using the type `types.late` and array just ***one*** of the types, it worked just fine. I think mst might not know how to resolve an array of two types because it just has the id (and not a typename).

**Comment by terrysahaidak** [comment]
Would be cool to have minimal reproducing example on codesandbox in order to help you.

I use mst in few production apps and it's great. So there is a bug somewhere in your code :)

**Comment by special-character** [comment]
@terrysahaidak I don't think there is a bug in my code. I literally just set some ids. 

References to `ModelA` ***or*** `ModelB` work just fine individually.

If I change the following:
```
types.union(
        types.late(() => ModelA),
        types.late(() => ModelB),
      ),
```

to this:

```
types.union(
        types.late(() => ModelA),
      ),
```

`ModelA` is referenced correctly without code changes

**Comment by special-character** [comment]
For posterity, the way to build an array like this is using a union with an explicit dispatcher like in this comment: https://github.com/mobxjs/mobx-state-tree/issues/1162#issuecomment-459742443
