### ISSUE TITLE
types.computed request

### ISSUE THREAD

**Issue by aap82** [mobxjs/mobx-state-tree#156]
Is it possible to have types.computed work similar to the way mobx.computed works? 
I ask because I CoffeeScript doesn't allow getters.  Right now, i'm using computed properties by doings something akin to:

```
userProps =
  firstName: types.string
  lastName: types.string
  fullName: types.computed
  
Object.defineProperty userProps, 'fullName', ->
  get: -> @firstName + ' ' + @lastName
```
This works perfectly fine, but as you can imagine, becomes quite verbose when using many computed props.

**Comment by mattiamanzati** [comment]
Should be easy to implement once #152 gets implemented, thanks for suggestion! :D

**Comment by mweststrate** [comment]
Closing this issue, since there is a workaround and coffee script is nowadays rare enough to not make it a core target.

**Comment by aap82** [comment]
😔 c'est la vie.
