### ISSUE TITLE
How to store map of references?

### ISSUE THREAD

**Issue by ji-1** [mobxjs/mobx-state-tree#1566]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

Hello. Does anyone know how to use a map of references to sibling? I have a **rootStore** that have **goalStore**, **tagStore**
and each store have a map of goals, tags respectively.
```
const RootStore = types
  .model('RootStore', {
    id: types.optional(types.identifier, 'RootStore'),
    goalStore: types.optional(GoalStore, () => GoalStore.create({goals: {}})),
    tagStore: types.optional(TagStore, () => TagStore.create({tags: {}})),
  });
const GoalStore = types
  .model('GoalStore', {
    id: types.optional(types.identifier, 'GoalStore'),
    goals: types.map(Goal),
  });
const TagStore = types
  .model('TagStore', {
    id: types.optional(types.identifier, 'TagStore'),
    tags: types.map(Tag),
  })
const Goal = types
  .model('Goal', {
    id: types.identifier,
    tags: types.map(
      types.reference(
        types.late(() => Tag),
        {
          onInvalidated(ev) {
            console.warn(this.tags);
            console.warn(ev);
            ev.removeRef();
          },
        },
      ),
    ),
});
const Tag = types
  .model('Tag', {
    id: types.identifier,
    name: types.string,
    color: types.string,
  });
```

So I'm trying to save **tag** references to **goal** model in **goalStore**.
```
goals.forEach((goal) => {
        var tags = {};
        goal_tag_map[goal.id].forEach((tag) => {
          var id = `Tag_${tag}`;
          tags[id] = self.tagStore.get(id);
        });
        var goalNode = Goal.create({
          id: `Goal_${goal.id}`,
          title: goal.title,
          tags: tags,
          createdAt: goal.create_at,
          startDate: goal.created_at,
        });
        self.goalStore.goals.put(goalNode);
      });
```
and I got an error
`{"cause": "invalidSnapshotReference", "invalidId": "Tag_1", "invalidTarget": undefined, "parent": {"Tag_1": "Tag_1"}, "removeRef": [Function removeRef], "replaceRef": [Function replaceRef]}`
If I just insert references by fetching a tag from **tagStore** by using `getParent(self)` in **goalStore**, it does get stored in the **goal** model and above error doesn't happen but If I delete the **tag** model later, then I get an above error again.

**Comment by airhorns** [comment]
Why do you want a map of references and not an array? Also, for what it's worth, when you're building your input snapshot to pass to a `.create` call, references should be specified as the string identifiers for the things you want to reference, not the actual instances of the nodes you want to reference. `tags[id] = id` would be closer to what mobx-state-tree wants.

**Comment by BrianHung** [comment]
> Why do you want a map of references and not an array?

Array doesn't enforce uniqueness; for example an unordered map of children nodes.

**Comment by coolsoftwaretyler** [comment]
Hey @ji-1 - it's been a while since we heard back from you in this MST issue.

I'm trying to phrase a good solution for ya here, but I'm having trouble getting an example that makes sense. If you're still interested in some help, would you mind [making a CodeSandbox](https://codesandbox.io/s/y64pzxj01?file=/index.js) for me so I can take a closer look?

If you moved on/moved past this issue, no worries. Just lemme know. If I don't hear back from you in about two weeks, I'll probably close this out.

**Comment by coolsoftwaretyler** [comment]
I'm gonna close this out - been about two weeks without activity here.
