### ISSUE TITLE
Error with reference types after updating to latest version

### ISSUE THREAD

**Issue by peejayess** [mobxjs/mobx-state-tree#1568]
**_Bug report_**

* [x ] I've checked documentation and searched for existing issues
* [x ] I've made sure my project is based on the latest MST version
* [ x] Fork [this](https://codesandbox.io/s/mobx-state-tree-todolist-forked-3060p?file=/index.ts) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/mobx-state-tree-todolist-forked-3060p?file=/index.ts
Note:  You will have to wait for a few seconds for the error to be highlighted in the index.ts file

**Describe the expected behavior**
I have a working application where  I have the following code:

```
export const ProjectStore = types.model("ProjectStore", {
  projects: types.array(Project),
  currentProject: types.maybeNull(types.reference(Project))
});
```

```
export const RootStore = types.model("RootStore", {
  projectStore: ProjectStore
});
```

```
const rootStore = RootStore.create({
  projectStore: ProjectStore.create()
});
```

**Describe the observed behavior**
After upgrading to the latest version of MST (3.17.2) I now have a type checking error at:

` projectStore: ProjectStore.create()`

which is caused by line:

`currentProject: types.maybeNull(types.reference(Project))`

The error message is:

`Types of property 'currentProject' are incompatible.       Type '({ id: number; name: string; imageUrl: string | null; } & NonEmptyObject & IStateTreeNode<IMaybeNull<IReferenceType<IModelType<{ id: IOptionalIType<ISimpleType<number>, [undefined]>; name: IType<...>; imageUrl: IMaybeNull<...>; }, {}, _NotCustomized, _NotCustomized>>>>) | null' is not assignable to type 'string | number | null | undefined'.         Type '{ id: number; name: string; imageUrl: string | null; } & NonEmptyObject & IStateTreeNode<IMaybeNull<IReferenceType<IModelType<{ id: IOptionalIType<ISimpleType<number>, [undefined]>; name: IType<...>; imageUrl: IMaybeNull<...>; }, {}, _NotCustomized, _NotCustomized>>>>' is not assignable to type 'string | number | null | undefined'.           Type '{ id: number; name: string; imageUrl: string | null; } & NonEmptyObject & IStateTreeNode<IMaybeNull<IReferenceType<IModelType<{ id: IOptionalIType<ISimpleType<number>, [undefined]>; name: IType<...>; imageUrl: IMaybeNull<...>; }, {}, _NotCustomized, _NotCustomized>>>>' is not assignable to type 'number'.`

**Comment by coolsoftwaretyler** [comment]
Hey @peejayess - sorry it's been a while since there was activity here. Are you still using MST? Have you upgraded to v5 yet? If so, is this still an issue for you? 

We are gathering some info to try and improve our TypeScript usage here. I'm going to label this as a TypeScript issue so we can get it prioritized for improvement.

Thanks!

**Comment by thegedge** [comment]
So this is a tricky one, and would potentially mean pretty significant changes to MST.

In many (maybe most?) cases, passing in an instance to `create` will work. Lots of types instantiate themselves to either be those instances, or those instances look exactly like the `SnapshotIn` type.

The specific problem for the above is that the types `ProjectStore["currentProject"]`  and `SnapshotIn<ProjectStore>["currentProject"]` aren't compatible (the former being an instance and the latter being a reference identifier, which is `string | number`).

@coolsoftwaretyler do you know if the contract of `create` should support instances? Here's the situation now:

* `create(value?: C)`
* `instantiate(..., value: C | T)`

I'm just wondering if we just change `create` to `create(value?: C | T)` and call it a day? If you're not sure, I can survey the land and make sure all creates are happy with an instance.

**Comment by coolsoftwaretyler** [comment]
Hey @thegedge - I think the contract of `create` is fine to receive instances. A few months ago, I [stepped through a full call to the `create` function](https://github.com/mobxjs/mobx-state-tree/discussions/2126#discussioncomment-7736158) and on step 8:

>  If the initialValue is already a state tree node, we use that. If not, we apply the preProcessor

So I'm mostly satisfied to allow either a `SnapshotIn` OR `Instance` here, but it's worth it to note that pre processing steps won't run in this scenario. Maybe in the PR where we make this change, we add a note in the JSDoc about that. It's the sort of "bug" that could be very frustrating to find later on when someone's preProcessor isn't working and we have to step through that code again, haha.

I would also want to see a good amount of test code in `__tests__/core/model.test.ts` exercising different types of `create` calls with all snapshots, all instances, and a mixture, just to make sure we've got our bases covered. But it seems that MST is already set up to work like this at runtime, and we really just want to update the types to reflect that.

**Comment by thegedge** [comment]
🙇 Great! I'll see if I can get to that on the weekend.

**Comment by thegedge** [comment]
Looks like the next release will resolve this issue 🎉 

![CleanShot 2024-08-04 at 10 44 28@2x](https://github.com/user-attachments/assets/1a6e0d95-3ee4-4d49-b7f0-dd6c56180aa3)
