### ISSUE TITLE
Can't mock action invoked by another action

### ISSUE THREAD

**Issue by garrettg123** [mobxjs/mobx-state-tree#1571]
**_Bug report_**

* [X] I've checked documentation and searched for existing issues
* [X] I've made sure my project is based on the latest MST version
* [X] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**

https://codesandbox.io/s/mobx-state-tree-todolist-forked-00045?file=/__tests__/index.test.js:0-260

**Describe the expected behavior**

The mocked action should be invoked by the parent action in the test.

**Describe the observed behavior**

The mocked action isn't invoked.

**Comment by coolsoftwaretyler** [comment]
Hey @garrettg123 - I'm sorry it took so long for folks to get back to you here. If this is still relevant to you, I think I've figured out the problem.

The way you've defined your function, in the inner part of `.actions`, makes it hard for Jest to keep track of the reference it's mocking. 

But if you return an object from `.actions` with the `toggle` function in this format, it works:

```
  .actions((self) => ({
    toggle() {
      self.finished = true;
    },
    triggerToggle() {
      self.toggle();
    }
  }))
```

Here's a CodeSandbox that's working: https://codesandbox.io/s/mobx-state-tree-todolist-forked-3xzfqd.

I'm going to close this out, but feel free to file a new issue if this isn't exactly what ya needed there. And again, sorry to take so long!
