### ISSUE TITLE
Convert Class to Tree Node

### ISSUE THREAD

**Issue by doc987** [mobxjs/mobx-state-tree#1573]
Suppose that there is a large existing code base.  Is there a way to convert classes (or equivalent functions) to MobX State Tree nodes without rewriting the code in terms of MobX State Tree?  For example, given the class (```C```) shown below, how can the node (```MSTNode```) shown below be automatically generated (e.g. ```MSTNode = makeNodeFromClass(C)```)?

```js
import * as mst from "./mobx-state-tree.module.js";

class C {
	prop1 = 0;
	prop2 = "";
	prop3 = false;
	get get1(){ /* ... */ }
	get get2(){ /* ... */ }
	action1(){ /* ... */ }
	action2(){ /* ... */ }
}

const MSTNode = mst.types
	.model({
		prop1: 0,
		prop2: "",
		prop3: false,
	})
	.views( self => ({
		get get1(){ /* ... */ },
		get get2(){ /* ... */ },
	}))
	.actions( self => ({
		action1(){ /* ... */ },
		action2(){ /* ... */ },
	}))
;
```

**Comment by terrysahaidak** [comment]
I have a project where we do something similar. 

https://github.com/terrysahaidak/mst-collection

the only different from regular classes is that you need to specify the model props - which properties of your class should be serialized and how. All the other class properties are volatile.

```ts
const MSTModel = types.model("MyModel", {
  prop1: types.string,
})
.volatile(() => ({
  prop2: 1
}))
.views(() => ((
  get thisIsView () {}
}))
.actions(() => ((
  action () {}
}))

class _MSTModel extends Model({
  prop1: types.string,
}) {
  prop2 = 1;

  get thisIsView () {}

  action() {}
}
const MSTModel = model(_MSTModel)
````

It might be not perfect from the typings perspective, I'm still migrating my current project from regular models to this. But should work for like 99% cases I guess.

**Comment by coolsoftwaretyler** [comment]
Hey @doc987, I'm going to label this issue for closing since it looks like @terrysahaidak had a pretty good option for ya here and there hasn't been much movement.

I'll come back in a week or two and close it out if no one objects. Thanks!

**Comment by coolsoftwaretyler** [comment]
No response for about two weeks or so - gonna close this one out!
