### ISSUE TITLE
Sharing action function causes TS circular reference?

### ISSUE THREAD

**Issue by special-character** [mobxjs/mobx-state-tree#1578]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

I am trying to share an action function in my project but I get the error 

```
implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
```

I have seen this before when I used a recursive reference on a model and was able to fix it with explicit typing using interfaces (like suggested in docs and other issues). For this use case, I can't figure out a way to type the circular reference which makes sharing an action difficult.

example codesandbox: https://codesandbox.io/s/crazy-liskov-if7se?file=/src/TestStore.ts

<img width="540" alt="Screen Shot 2020-09-08 at 12 00 49" src="https://user-images.githubusercontent.com/5407471/92517763-166bb000-f1cc-11ea-805c-b176642c79a2.png">

It seems like sharing an action like this should be fairly common. I understand a bit about why TS throws this error but not sure how to break the cycle in this case. Some questions I had:

I am wondering if this is because `ITestStore` is dynamically typed and action block ordering would matter? Has anyone else ran into this? Am I totally missing something with TS? 

Thanks!

**Comment by CmplxStack** [comment]
The `somethingElse` function is expecting an argument of type `ITestStore` representing `self` when passed in on line 20 -> <code>.actions(somethingElse)</code> as an action block. With `ITestStore` being the Instance type of TestStore, when the `ITestStore` type is being created, TypeScript is essentially walking down the `TestStore` model, building the type along the way, and all is fine until it hits  <code>.actions(somethingElse)</code> (Or:  <code>.actions((self) => somethingElse(self))</code>). The `self`arg is again expected to be `ITestStore` the very type that we are in the middle of evaluating. This will send us back to the beginning, again walking down and evaluating `TestStore` until we hit  <code>.actions(somethingElse)</code> and the cycle repeats.

A solution (In sandbox below) would be to split the model into two pieces (TestStoreBase and TestStore), generate the Instance type without the `somethingElse` action (`ITestStoreBase`), update `somethingElse`'s arg type, and then extend the model with the action block. (Each action/view/etc block creates a new type)

[![Edit musing-wiles-zxppt](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/musing-wiles-zxppt?fontsize=14&hidenavigation=1&theme=dark)

**Comment by special-character** [comment]
Thanks for the example, I think that splitting them up is probably the best way forward for this.
