### ISSUE TITLE
 Error: [mobx-state-tree] expected mobx-state-tree type as argument 1, got DrugStore@<root>

### ISSUE THREAD

**Issue by Abhishek12345679** [mobxjs/mobx-state-tree#1582]
**_Question_**

* [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)
* [x] I've checked documentation and searched for existing issues

I am trying to create a root store with two stores but the got the above mentioned error and variations of the same error.
I am using it in a RN 62 project with expo and react-navigation

> Reproduction - 

[ Link to sandbox.io ](https://codesandbox.io/s/react-mst-rootstore-demo-rf2bc)

> Full error log -

```
Error: [mobx-state-tree] expected mobx-state-tree type as argument 1, got DrugStore@<root> instead
<global>
    mobx-state-tree.module.js:3129:1
assertArg
    mobx-state-tree.module.js:3453:9
<global>
    mobx-state-tree.module.js:2017:1
checkOptionalPreconditions
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:161517:16
optional
    mobx-state-tree.module.js:5649:29
loadModuleImplementation
    require.js:321:11
guardedLoadModule
    require.js:201:44
runUpdatedModule
    require.js:705:16
metroHotUpdateModule
    require.js:539:39
define
    require.js:53:8
eval
    [native code]:0
inject
    HMRClient.js:81:8
forEach
    [native code]:0
injectUpdate
    HMRClient.js:87:2
on$argument_1
    HMRClient.js:155:20
emit
    index.js:202:16
_ws.onmessage
    HMRClient.js:134:10
EventTarget.prototype.dispatchEvent
    event-target-shim.js:818:20
_eventEmitter.addListener$argument_1
    WebSocket.js:232:8
emit
    EventEmitter.js:189:10
__callFunction
    MessageQueue.js:425:19
__guard$argument_0
    MessageQueue.js:112:6
__guard
    MessageQueue.js:373:10
callFunctionReturnFlushedQueue
    MessageQueue.js:111:4
callFunctionReturnFlushedQueue
    [native code]:0
```

**Comment by dhdemerson** [comment]
* The code is calling `.create` immediately on your  `DrugStore` and `SettingsStore`  model, so you're exporting an *instance* of a those models and not the *model* the `types.optional` expects. It looks like you're trying to use `create` to default model values? That is what `types.optional` is generally used for.
* `types.optional` generally takes two arguments see https://mobx-state-tree.js.org/API/#optional
* The code exports `DrugStore` and `SettingsStore` as `default` but they are imported as named imports

**Comment by Abhishek12345679** [comment]
@dhdemerson i'll check after i wake up. thank you :3

**Comment by Abhishek12345679** [comment]
@dhdemerson Hello! I am really new to mst. can you tell me what is the approach i should be taking to get a root store from two models (Stores), looking at my sandbox repro ?

**Comment by dhdemerson** [comment]
Addressing the points I mentioned should get your sandbox to work. More broadly I think your conceptual question is pretty directly answered in the documentation with examples here: https://mobx-state-tree.js.org/concepts/trees#tree-type-state

Those examples could be modified to fit what you are trying to accomplish in the sandbox.

Note: there is no "store" type in MST, models that function as "stores" are still just models and are not special in any way.

**Comment by Abhishek12345679** [comment]
yeah i used what you said in the last comment.

1. replaced default exports for named ones 

2. removed the .create({}) function from the model and put it in the types.optional in the rootStore file.

I did not get any error in the sandbox after this but i am yet to check this in my application.

Will keep you updated!

**Comment by Abhishek12345679** [comment]
I console logged the rootstore in app.js

i got an object but i cannot access the actual models and data inside of it.

[Link to sandbox](https://codesandbox.io/s/react-mst-rootstore-demo-rf2bc?file=/src/App.js)
