### ISSUE TITLE
Child model preProcessor being called with undefined snapshot

### ISSUE THREAD

**Issue by dhdemerson** [mobxjs/mobx-state-tree#1587]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**

https://codesandbox.io/s/react-typescript-forked-4kofj?file=/index.ts
```typescript
import { SnapshotIn, types } from "mobx-state-tree";

const BaseDog = types.model("Dog", {
  name: types.string
});

const Dog = types.snapshotProcessor(BaseDog, {
  preProcessor(snapshot: SnapshotIn<typeof BaseDog>) {
    console.log(snapshot) // undefined 

    // Type checks (with the annotation above not accounting for undefined)
    return snapshot;

    // Does not type check
    // return undefined;

    // .is check below will return true
    // return {name: 'Tex'}
  }
});

const DogOwner = types.model("DogOwner", {
  dog: Dog
});

console.log("DogOwner is cat", DogOwner.is({ cat: "felix" })); // false
```

**Describe the expected behavior**

I would expect either:
- The snapshot `preProcessor` for `Dog` not to execute because there is no `dog` key in the input for `DogOwner.is`
- Returning `undefined` should type check for cases like these, if `undefined` is a valid input for `preProcessor`

**Describe the observed behavior**

The snapshot `preProcessor` code for `Dog` runs with `undefined` as the value for the input snapshot. Attempting to return undefined does not type check, and returning a valid snapshot will result in the `.is` call returning true.

**Comment by bibin96** [comment]
I've been using this in my react native project. Please have a look at this code.

  >  "mobx": "6.0.4", 
"mobx-react": "7.0.5", 
"mobx-state-tree": "5.0.0",

```js
const SampleStoreWithoutSnapshotProcessor = types
  .model("SampleStore")
  .props({
    mentionKeyword: types.optional(types.string, ""),
  })

export const SampleStoreModel = types.snapshotProcessor(SampleStoreWithoutSnapshotProcessor, {
  // from snapshot to instance
  preProcessor(sn) {
       console.log(sn) output --> // { mentionKeyword: "" }
       return sn
   },
  // from instance to snapshot
  postProcessor(sn) {
    return sn
  }
})
```

**Comment by dhdemerson** [comment]
For anyone else running into this you likely want a check like this in your preProcessor:
```ts
if (snapshot === undefined || snapshot === null) {
    return snapshot;
}
```

A `snapshotPreprocessor` will be called even when its key is not present or a key has a value of null, This includes when the model with the preProcessor is wrapped in `types.maybe` and `types.maybeNull`. Explicitly returning null or undefined likely won't type check for those using TypeScript, but the above is fine. Be aware that changing the type signature of the preProcessor to explicitly allow null/undefined might allow things to type check that shouldn't.
