### ISSUE TITLE
Nullable identifier

### ISSUE THREAD

**Issue by daimeng** [mobxjs/mobx-state-tree#159]
I have some objects with { id: null, ... }, because they have not been persisted yet. Is there a way to have maybe or optional identifier type currently? Or is this a bad pattern?

**Comment by mattiamanzati** [comment]
Identifiers are used also for reconciliation, like React does. So you can't make them null, because reconciliation will fail! :) You can btw use an internal random identifier and use another property as the remotely saved ID :)

**Comment by mweststrate** [comment]
Note that the branch is released now, as 0.7

Op ma 12 jun. 2017 om 09:37 schreef Mattia Manzati <notifications@github.com

**Comment by creativefctr** [comment]
@mweststrate what happened at last? I still can not get it to work

**Comment by mweststrate** [comment]
@creativefctr It is hard remember details from what happened a year ago when merging hundreds of PRs per year :). If you run into trouble, just open a new issue and someone will look into it.

**Comment by mweststrate** [comment]
Make that 2 years :-P
