### ISSUE TITLE
`types.array` will create LegacyObservableArray with mobx-state-tree@4.0.1-rc.1

### ISSUE THREAD

**Issue by HeskeyBaozi** [mobxjs/mobx-state-tree#1598]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**

https://codesandbox.io/s/mobx-state-tree-4xx-rc-u4x6q

**Describe the expected behavior**

use `Proxy` instead of `LegacyObservableArray`

**Describe the observed behavior**

`types.array` created an array with type `LegacyObservableArray`, so that the value of the assert `Array.isArray(array)` is `false`

**Comment by AndrewMorsillo** [comment]
I'm also seeing this behavior after upgrade to 4.0.2

**Comment by pustovalov** [comment]
same behavior, mobx-state-tree: 4.0.2
