### ISSUE TITLE
Error: mobx-react-lite@3 requires mobx at least version 6 to be available

### ISSUE THREAD

**Issue by thareekanvar** [mobxjs/mobx-state-tree#1612]
HI

I am using Mobx-state-tree in My react native project ( using Expo ) . I got an error while using the observer .. so i dont know what was the problem or not 

Error is 

```Error: mobx-react-lite@3 requires mobx at least version 6 to be available```

Versions:

```
    "mobx": "5.15.7",
    "mobx-react": "^7.0.5",
    "mobx-state-tree": "^3.17.2",
    "mobx-react-lite": ">=2.2.0 <3.0.0",``` 

any one can help me please advance thanks

**Comment by karianpour** [comment]
I guess you do not need "mobx-react", just use "mobx-react-lite". Here is my setting which works:

```
    "mobx": "^5.15.7",
    "mobx-react-lite": "^2.2.2",
    "mobx-state-tree": "^3.17.3",
```

**Comment by thareekanvar** [comment]
> I guess you do not need "mobx-react", just use "mobx-react-lite". Here is my setting which works:
> 
> ```
>     "mobx": "^5.15.7",
>     "mobx-react-lite": "^2.2.2",
>     "mobx-state-tree": "^3.17.3",
> ```

Then How u use Observer .... i cant get data on time why ?? ..how u doing that

**Comment by karianpour** [comment]
Observer component and observer function both are available on mobx-react-lite. Import them from mobx- react-lite:

import { observer , Observer } from "mobx-react-lite"

**Comment by thareekanvar** [comment]
> Observer component and observer function both are available on mobx-react-lite. Import them from mobx- react-lite:
> 
> import { observer , Observer } from "mobx-react-lite"

Thanks Dude .. problem fixed i am closing this issue
