### ISSUE TITLE
Action should include namespace.

### ISSUE THREAD

**Issue by yuluyi** [mobxjs/mobx-state-tree#162]
In the callback of onAction, we can only get the action name. I think it's better to also include the model name as namespace.

**Comment by mattiamanzati** [comment]
The model path is already included as namespace, you can easily resolve also the model type by using getType and resolve from the MST package, here's an example! :)

https://mattiamanzati.github.io/mobx-state-tree-playground/build/index.html#src=import%20%7B%20types%2C%20onAction%2C%20getType%2C%20resolve%20%7D%20from%20%22mobx-state-tree%22%0Aimport%20%7B%20inspect%20%7D%20from%20%22mobx-state-tree-playground%22%0A%0Aconst%20AppModel%20%3D%20types.model('ChuckNorris'%2C%20%7B%0A%20%20%20%20count%3A%20types.optional(types.number%2C%200)%0A%7D%2C%20%7B%0A%20%20%20%20increment()%7B%0A%20%20%20%20%20%20%20%20this.count%2B%2B%0A%20%20%20%20%7D%2C%0A%09decrement()%20%7B%0A%09%09this.count--%0A%09%7D%0A%7D)%0A%0Aconst%20store%20%3D%20AppModel.create()%0Ainspect(store)%0A%0AonAction(store%2C%20data%20%3D%3E%20%7B%0A%20%20%20%20console.log(data.name%20%2B%20%22%20performed%20over%20%22%20%2B%20data.path%20%2B%20%22%20on%20type%20%22%20%2B%20getType(resolve(store%2C%20data.path)).name)%0A%7D)%0A%0Astore.increment()%0Astore.decrement()%0Astore.increment()%0A
