### ISSUE TITLE
Devtools that allow me to see MST state?

### ISSUE THREAD

**Issue by adamerose** [mobxjs/mobx-state-tree#1625]
I would like to be able to see my MST state in devtools and time travel through it like in Redux or Vuex: https://vueschool.io/lessons/vuex-mutation-history-and-vue-devtools

However all I can find is the `mobxjs/mobx-devtools` repo which is looking for maintainers and has been [broken on MST](https://github.com/mobxjs/mobx-devtools/issues/30) for over 2 years. I've been debugging my MST project by storing the store in a global variable and manually logging it in the Chrome console which is a UX almost as bad as going back to Redux... what is everyone else doing?

**Comment by philllies** [comment]
Give [Redux Dev Tools ](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd) with MST a shot:
https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mst-example-redux-todomvc/src/index.js

**Comment by mattruby** [comment]
Another option is reactotron: https://github.com/infinitered/reactotron/blob/master/docs/plugin-mst.md

**Comment by publicJorn** [comment]
Whoever ends up here, I didn't have any success with the above tools. I did get it to work with 
mobx-devtools and the `mobx-devtools-mst` package.

https://github.com/mobxjs/mobx-devtools/blob/master/README.md#mobx-state-tree

**Comment by Adlopez2016** [comment]
Hello we are trying to integrate pandasgui to a project in Django, however it generates the following error "Plotly Express canont process wide-form data with columns of different type. Please could you help me

**Comment by AaronPorts** [comment]
It's still an issue for me. What do others use as devtools?
