### ISSUE TITLE
Union dispatcher snapshot undefined

### ISSUE THREAD

**Issue by vallode** [mobxjs/mobx-state-tree#1627]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

In our MST/Typescript project we like to use `Model.is(...)` quite a bit, this sometimes results in errors like these popping up:

```
Cannot read property 'exampleProperty' of undefined
```
```js
1 |  dispatcher: (snapshot) => snapshot.exampleProperty || types.null,
  |                                    ^
```

This is _usually_ caused by not enforcing the passed model to be non-nullable via an extra check like:  
```js
exampleObject && Model.is(exampleObject)
```
It's easily fixed but not always caught by people due to the rather "mysterious" error thrown and no typing error.

Is there a way to enforce `Model.is` to throw type errors with undefined values? Would this be something that MST would have to change in their typings or maybe the inference is already there but I am not using it correctly. (I'd be happy to create an PR).

**Comment by coolsoftwaretyler** [comment]
Hey @vallode - sorry it took anyone so long to get back to you here in the MST project.

Unfortunately I don't have an answer for you at the moment, but I will add some labels to help us as we clean up the maintenance overall, and hopefully we can get this slated for a fix.

I know it's been literally years, so I understand if you aren't interested/have moved on, but did you ever find a fix on your own? Are you still interested in submitting a PR? We're definitely open to improvements in the typing system.

**Comment by vallode** [comment]
Hey, no worries. I'd have to try and dig out the codebase this was a part of in order to look back into it, I remember the issue being quite simple.

Changing:
```ts
dispatcher: (snapshot) => snapshot.exampleProperty || types.null,
```

To:
```
dispatcher: (snapshot) => snapshot?.exampleProperty ?? types.null,
```

Would likely resolve this, happy to open a PR and play around with it but give me a little time ;)
