### ISSUE TITLE
How to describe model with dynamic keys and Array of objects as value

### ISSUE THREAD

**Issue by hariks789** [mobxjs/mobx-state-tree#1630]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

My data format is as follows

```
{
 [id]: [{ name: "Event Name" ,  date: "string" }, { name: "Event Name" , date: "string" }],
 [id]: [{ name: "Event Name" ,  date: "string" }, { name: "Event Name" ,  date: "string" }],
 }
```
I went through other issues [#1306 ](https://github.com/mobxjs/mobx-state-tree/issues/1306) and resolved the type errors by defining my model as

```
const Event = types.model({
  name: types.string,
  date: types.string,
})

```
```
.props({
  // userEvents: types.frozen({})
  userEvents: types.map(types.array(Event))
})
```

But when I try to set update value

`self.userEvents = { "2020-12-27": [{ name: "Test Event", date: "2020-12-30" }] };
`

There are no errors but when log userEvents it shows

`{"2020-12-27": [[Object]]} 
`
How do I resolve this other than by using types.frozen.

**Comment by tunm1228** [comment]
Have you solved this problem please help me?

**Comment by hariks789** [comment]
@tunm1228 You can use the same syntax. It's working for me. 
`userEvents: types.map(types.array(Event))`

**Comment by tunm1228** [comment]
it's like new Map() Javascript?
