### ISSUE TITLE
V4 version sample applications

### ISSUE THREAD

**Issue by MakeSAPGreatAgain** [mobxjs/mobx-state-tree#1638]
The sample applications all are in v3 , I can't find any sample for V4 verison. Now there is V5 out.
Am i missing something?

**Comment by iChenLei** [comment]
### Please read the <em>Release</em> changelog !
MST V5: https://github.com/mobxjs/mobx-state-tree/releases/tag/v5.0.0
MST V4: https://github.com/mobxjs/mobx-state-tree/releases/tag/v4.0.2

### Summary: 
MobX-State-Tree <strong>v4</strong> will only work with MobX 6, so if you need to stay on MobX 4 or 5, you'll need to also stay on MST 3.
MobX-State-Tree <strong>v5</strong> includes bugfixes that may in rare cases cause breaking changes if relying on undocumented behavior.

### Conclusion
If you don't need support proxy-non-support browser, just upgrade MST to V4(no api breaking change), but for V5 you should test your APP to assurance everything work fine. (also no api breaking change).

@MakeSAPGreatAgain

**Comment by MakeSAPGreatAgain** [comment]
Thank you.
