### ISSUE TITLE
`in` operator regression for actions

### ISSUE THREAD

**Issue by getkey** [mobxjs/mobx-state-tree#1639]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [ ] ~~I've made sure my project is based on the latest MST version~~ not applicable
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**

https://stackblitz.com/edit/in-regression-mobx-state-tree?file=index.html

```ts
import { types } from "mobx-state-tree";

const User = types
  .model({
    name: ""
  })
  .actions(self => ({
    setName(name) {
      self.name = name;
    }
  }));

const john = User.create();
console.log("This should be true:", "setName" in john);
```

**Describe the expected behavior**

The `in` operator should detect actions. I've observed that the regression appeared somewhere between version 4.0.2 and 4.0.3.

**Describe the observed behavior**

The `in` operator doesn't detect actions on instances of the model.

**Comment by iChenLei** [comment]
### Diff v4.0.2 with v4.0.3
[Github code diff link](https://github.com/mobxjs/mobx-state-tree/compare/v4.0.2...v4.0.3)
The main code change in **packages/mobx-state-tree/src/utils.ts**
```diff
- import { isObservableArray, $mobx, getAtom } from "mobx"
+ import { isObservableArray, _getGlobalState, getAtom } from "mobx"

- export const mobxShallow =
-     typeof $mobx === "string" ? { deep: false } : { deep: false, proxy: false }
+ export const mobxShallow = _getGlobalState().useProxies
+    ? { deep: false }
+     : { deep: false, proxy: false }
```
The $mobx in mobx6 is a Symbol
```ts
  export const $mobx = Symbol("mobx administration")
```
### 🔥  When we use modern browser which support ***Proxy***  🔥 
**typeof $mobx === "string"** is ***false*** in v4.0.2
**_getGlobalState().useProxies** is ***true*** in v4.0.3
#### v4.0.2 mobxShallow = { deep: false, proxy: false }
#### v4.0.3 mobxShallow = { deep: false }

### Reproduction Example
v4.0.2 The <strong>john</strong> object is a plain object

<div style="display:flex;justify-content:center;width=600px;">
		<p><img src="https://user-images.githubusercontent.com/14012511/104832114-9831bf80-58c9-11eb-8df4-c981ab7fa722.png" width="600px" />
	    </p>
</div>

v4.0.3 The <strong>john</strong> object is a **Proxy** object [Proxy MDN doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy)

<div style="display:flex;justify-content:center;width=600px;">
		<p><img src="https://user-images.githubusercontent.com/14012511/104832148-ec3ca400-58c9-11eb-94bf-b2e18f634164.png" width="600px" />
	    </p>
</div>

Mobx Proxy process code: **mobx/packages/mobx/src/types/dynamicobject.ts**
```ts
    has(target: IIsObservableObject, name: PropertyKey) {
        if (name === $mobx || name === "constructor") return true
        if (__DEV__ && globalState.trackingDerivation)
            warnAboutProxyRequirement(
                "detect new properties using the 'in' operator. Use 'has' from 'mobx' instead."
            )
        const adm = getAdm(target)
        // MWE: should `in` operator be reactive? 
        // If not, below code path will be faster / more memory efficient
        // check performance stats!
        // if (adm.values.get(name as string)) return true
        if (isStringish(name)) return adm.has_(name)
        return (name as any) in target
    }
```
So when we use v4.0.3 **console.log('setName' in john);** will print <strong>false</strong> in console....
Hope my analysis is helpful.  @jamonholmgren @getkey

**Comment by airhorns** [comment]
I think this is an issue for views too, not just actions. I can confirm it only happens for me when proxies are used. Is this maybe a plain `mobx` bug?

**Comment by iChenLei** [comment]
@airhorns @getkey It's existing Mobx6 [issue](https://github.com/mobxjs/mobx/issues/2629)
Mobx Github [discussions](https://github.com/mobxjs/mobx/discussions/2586)

**Comment by urugator** [comment]
It has nothing to do with enumerability, but should be fixed by:
https://github.com/mobxjs/mobx/pull/2641

**Comment by urugator** [comment]
Should work with MobX **6.1.*** (MST > **5.0.1**)

**Comment by iChenLei** [comment]
> https://stackblitz.com/edit/in-regression-mobx-state-tree-lng8z9

![2021-02-02 19 16 58](https://user-images.githubusercontent.com/14012511/106593028-3d67bb80-658b-11eb-8cc5-8cdee49c7707.png)

Yes, fixed by PR 2641!

**Comment by getkey** [comment]
Awesome, thanks @urugator! Closing this issue.
