### ISSUE TITLE
MST actions don't work with Typescript

### ISSUE THREAD

**Issue by pustovalov** [mobxjs/mobx-state-tree#1649]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [ ] I've made sure my project is based on the latest MST version

**Sandbox link or minimal reproduction code**

```
import { types, applySnapshot } from 'mobx-state-tree'

export const CurrentUser = types
  .model('CurrentUser', {
    id: types.number,
    account_id: types.number,
    email: '',
  })
  .views(self => ({
  }))
  .actions(self => ({
    update: data => {
      applySnapshot(self, data)
    },
    fetch: () => {
      self.update({})
    },
  }))
```

https://github.com/pustovalov/ts-mst-demo/blob/main/src/stores/current_user.ts#L20

**Describe the expected behavior**

TS should work with MST actions

**Describe the observed behavior**

```
Property 'update' does not exist on type '{ id: number; account_id: number; email: string; } & NonEmptyObject & IStateTreeNode<IModelType<{ id: ISimpleType<number>; account_id: ISimpleType<number>; email: IType<...>; }, {}, _NotCustomized, _NotCustomized>>'
```

**Dependencies**
MST: 3.17.3, same behavior with `5.0.0`
TS: 4.1.3

**TS config**
https://mobx-state-tree.js.org/tips/typescript
as the documentation says, contain these options:

```
{
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true
}
```
https://github.com/pustovalov/ts-mst-demo/blob/main/tsconfig.json#L9

**Comment by pustovalov** [comment]
Looks like there was such a problem in the past:
https://github.com/mobxjs/mobx-state-tree/issues/1307

**Comment by pustovalov** [comment]
Found one workaround:
```
export const CurrentUser = types
  .model('CurrentUser', {
    id: types.number,
    account_id: types.number,
    email: '',
  })
  .views(self => ({
  }))
  .actions(self => ({
    update(data: string) {
      applySnapshot(self, data)
    },
    fetch() {
      this.update({})
    },
  }))
```

But this one will not work with `flow`, to make it work together with `flow` need to do something like this:

```
import { types, applySnapshot, flow } from 'mobx-state-tree'

export const CurrentUser = types
  .model('CurrentUser', {
    id: types.number,
    account_id: types.number,
    email: '',
  })
  .views(self => ({
  }))
  .actions(self => ({
    update(data: string) {
      applySnapshot(self, data)
    },
    fetch() {
      this.update({})
    },
  }))
  .actions(self => ({
    fetchWithFlow: flow(function* fetchWithFlow() {
      self.update({})
    }),
  }))
```

it looks worse with these two `.actions(`, is there another way?

**Comment by KislyakovDS** [comment]
How about this?

```
import { types, applySnapshot } from "mobx-state-tree";

export const CurrentUser = types
  .model("CurrentUser", {
    id: types.number,
    account_id: types.number,
    email: ""
  })
  .actions((self) => {
    const update = (data: any) => {
      applySnapshot(self, data);
    };

    const fetch = () => {
      update({});
    };

    return { update, fetch };
  });
```

**Comment by airhorns** [comment]
Have you read through the docs here https://mobx-state-tree.js.org/tips/typescript ? Specifically, the part about declaring multiple blocks so that subsequent blocks can depend on the prior ones? That solves this issue, I think this can be closed.
