### ISSUE TITLE
Typescript error with reference types

### ISSUE THREAD

**Issue by ataravati** [mobxjs/mobx-state-tree#1655]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [ ] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
```
import { types } from "mobx-state-tree";

const Product = types.model("Product", {
   id: types.identifier,
   name: types.string
})

const ProductStore = types
  .model("ProductStore", {
    products: types.array(Product),
    selectedProduct: types.safeReference(Product),
  })
  .actions((self) => ({
      // actions here
  }));

export const productStore = ProductStore.create({
  products: [],
  selectedProduct: undefined // the type here is different from the type in the actual model
});

const RootStore = types.model('RootStore', {    
  productStore: ProductStore 
})

export const rootStore = RootStore.create({
    productStore: productStore // Here is where I get the typescript error.
});

```

**Describe the expected behavior**
When using `safeReference` the type in `ProductStore.create()` is different from the type in `ProductStore`, so Typescript will always gives me an error in the `rootStore`.

**Describe the observed behavior**
The type of the `reference` properties should remain the same in the instance type.

**Comment by ataravati** [comment]
Another way of reproducing this issue is by trying to create a custom reference. The getter will complain about `null` not being assignable to type {...}. 

```
const ProductByIdReference = types.maybeNull(
  types.reference(Product, {
      get(id: number, parent: Instance<typeof ProductStore>) {
          return parent.products.find(p => p.id === id) || null
      },
      set(value: Instance<typeof Product>) {
          return value.id
      }
  })
)
```

**Comment by EmilTholin** [comment]
Hi @ataravati!

We have to help TypeScript manually when we are using a node instance where a snapshot is typically used by using [`castToSnapshot`](https://mobx-state-tree.js.org/API/#casttosnapshot):

```ts
export const rootStore = RootStore.create({
  productStore: castToSnapshot(productStore)
});
```
