### ISSUE TITLE
afterAttach doesnt work as expected

### ISSUE THREAD

**Issue by wildeyes** [mobxjs/mobx-state-tree#1657]
**_Bug report_**

* [X] I've checked documentation and searched for existing issues
* [X] I've made sure my project is based on the latest MST version
* [X] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/afterattach-doesnt-play-well-with-env-p2xm7?file=/src/App.tsx

**Describe the expected behavior**
I expect afterAttach to run after I `.push` my instance into the tree.

**Describe the observed behavior**
afterAttach runs immediately after `Model.create({})`.

**Comment by makarov-roman** [comment]
This is expected and correct behavior. 
You want to use [cast](https://mobx-state-tree.js.org/API/index#cast)
If you are trying to add new instance to existing tree you should pass snapshotIn instead of creating new instance manually.
e.g. instead of 
```javascript
self.items.push(ItemModel.create({}));
```
do 
```javascript
self.items.push({})
```
or if you have type error
```javascript
self.items.push(cast({}))
```
