### ISSUE TITLE
Cached Async actions with flow

### ISSUE THREAD

**Issue by Balderscape** [mobxjs/mobx-state-tree#1659]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

Is there any established pattern for preventing an async action from being called more than once if there is a previous one already in flight, i.e. returning the current unresolved promise?

I have a situation where I have a sections of the tree that will be fetched by different pages and I end up with the multiple calls going out to the server as the same action to fetch can be called more than once from various pieces of code. I am using a getOrFetch view that just calls a fetch action if the data is missing.

**Comment by karianpour** [comment]
What I do in this conditions is to have local variable to check :

```
...
types.model("MyModel", {
  data: types.array(DataType), // some type
})
.actions(self => {
  let fetching = false;
  return {
    fetchGuarded: flow(function* () {
      if(fetching) return;
      try{
        fetching = true;
        const data = yield fetchData();
        self.data.push(...data); //let's assume that the data is an array to be added to the end of the array
      }catch(err){
        // should be handled
      } finally{
        fetching = false;
      }
    }),
  }
});
```

then I will be notified by the observer when the observable `data` is updated. So no matter how may time I call the `fetchGuarded` action. You might make the `fetching` also an observable in the `MyModel` to show the loading stuff.

**Comment by EmilTholin** [comment]
The solution outlined by @karianpour is great. As an alternative you could store the promise in a volatile state variable and return that if a request is already in flight.

```javascript
types
  .model("MyModel", {
    data: types.array(DataType)
  })
  .actions((self) => {
    let prom = null;

    return {
      fetchGuarded: flow(function* () {
        if (prom) return prom;

        try {
          prom = fetchData();
          const data = yield prom;
          self.data.push(...data);
        } catch (err) {
          // should be handled
        } finally {
          prom = null;
        }
      }),
    };
  });
```
