### ISSUE TITLE
How to declare an Object property?

### ISSUE THREAD

**Issue by cpunion** [mobxjs/mobx-state-tree#166]
I want to declare a property to save some plain fields, likes a JSON object, how to do it?

**Comment by mattiamanzati** [comment]
Hi! Can you please provide more background information? What do you mean by object property? Have you checked out #125 or #161 ?

**Comment by cpunion** [comment]
Thanks! I think types.frozen is useful.

**Comment by cpunion** [comment]
Seems types.frozen is not observable, which type equals to mobx's observable.map?

**Comment by mweststrate** [comment]
types.map

Op ma 5 jun. 2017 08:03 schreef Li Jie <notifications@github.com>:

**Comment by mattiamanzati** [comment]
@cpunion What do you mean by "can't handle deep structure"? Please provide more background information about what you want to do so we can help you :)

**Comment by cpunion** [comment]
Thanks @mweststrate, @mattiamanzati 

I did some tests, so seems types.map(types.frozen) completely equals observable.map.

I used mobx likes a big tree with multi levels observable.map, I guess types.map can be nested too?

**Comment by cpunion** [comment]
My code likes this:
```js
const store = observable.map()
store.set('foo', observable.map())
store.set('bar', 1)
store.get('foo').set('hello', 'world')
```

Its structure:
```js
{
  foo: {
    hello: 'world'
  },
  bar: 1
}

**Comment by cpunion** [comment]
## Another problem:

I'm trying to migrate a mobx state to MTS:

```
const BaseProperties = {
  title: types.string,
}

const Todo = types.model("Todo", {
  ...BaseProperties,

  data: types.map(types.frozen),

  get a() {
    return this.data.get('a')
  }
})
```

This will raise an error: TypeError: this.data.get is not a function

Same error when using `types.extend`. If I remove `...BaseProperties`, it works fine. Is there a way to implements an **inherits** feature with getter property?

**Comment by mattiamanzati** [comment]
@cpunion Does this satisfy the requests? :)
https://mattiamanzati.github.io/mobx-state-tree-playground/build/index.html#src=import%20%7B%20types%2C%20unprotect%20%7D%20from%20%22mobx-state-tree%22%0Aimport%20%7B%20inspect%20%7D%20from%20%22mobx-state-tree-playground%22%0A%0Aconst%20TreeNode%20%3D%20types.map(%0A%20%20%20%20types.union(%0A%20%20%20%20%20%20%20%20types.late(()%20%3D%3E%20TreeNode)%2C%0A%20%20%20%20%20%20%20%20types.frozen%0A%20%20%20%20)%0A)%0A%0Aconst%20store%20%3D%20TreeNode.create(%7B%7D)%0Ainspect(store)%0Aunprotect(store)%0A%0Astore.set(%22foo%22%2C%20TreeNode.create())%0Astore.set(%22bar%22%2C%201)%0Astore.get(%22foo%22).set(%22hello%22%2C%20%22world%22)

**Comment by cpunion** [comment]
@mattiamanzati Great! And your playground is awesome. Please add it to README.md, I feel it's better than JSBin.

**Comment by mattiamanzati** [comment]
Bug in computed should be fixed by your PR and available on 0.6.3, closing the issue. Feel free to open if necessary! :)

**Comment by chenyong** [comment]
Link's changed... https://mattiamanzati.github.io/mobx-state-tree-playground/index.html#src=import%20%7B%20types%2C%20unprotect%20%7D%20from%20%22mobx-state-tree%22%0Aimport%20%7B%20inspect%20%7D%20from%20%22mobx-state-tree-playground%22%0A%0Aconst%20TreeNode%20%3D%20types.map(%0A%20%20%20%20types.union(%0A%20%20%20%20%20%20%20%20types.late(()%20%3D%3E%20TreeNode)%2C%0A%20%20%20%20%20%20%20%20types.frozen%0A%20%20%20%20)%0A)%0A%0Aconst%20store%20%3D%20TreeNode.create(%7B%7D)%0Ainspect(store)%0Aunprotect(store)%0A%0Astore.set(%22foo%22%2C%20TreeNode.create())%0Astore.set(%22bar%22%2C%201)%0Astore.get(%22foo%22).set(%22hello%22%2C%20%22world%22)

any more details on frozen in docs?

**Comment by ThaJay** [comment]
Can I read anywhere on why Object is not supported and we have to use map?

Also, (probably because I'm new to mst) I don't fully understand the example @chenyong posted, is every entry in that store observable? because the content `types.frozen` is nor observable right?

I save my items by id so I can do direct lookup like `products[productId]`. I dislike using explicit `get` and `set` because it's just calling functions while a core language feature already supports this. It would also mean changing those calls everywhere in the code while I would like the components te not konw about these details. I just want them to access data. I they are wrapped in an observer hoc they observe observables but other than that they should remain generic.

**Comment by tahv0** [comment]
> Seems types.frozen is not observable, which type equals to mobx's observable.map?
> 
> ** UPDATED: **
> Just use types.map(types.frozen) instead, but can't handle deep structure.

This gives me error `TypeError: _this.subType.validate is not a function`

**Comment by xaviergonz** [comment]
@tahv0 could you open an issue with that? might be a bug

**Comment by tahv0** [comment]
> @tahv0 could you open an issue with that? might be a bug

ok
