### ISSUE TITLE
Lifecycle methods not called if we create a store with a snapshot

### ISSUE THREAD

**Issue by special-character** [mobxjs/mobx-state-tree#1665]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction (provided below). 

[Sandbox link](https://codesandbox.io/s/mobx-state-tree-afterattach-qt9xj?file=/src/index.ts)

**Describe the expected behavior**
`afterAttach` and `afterCreate` should be called even if a connected model was created with a snapshot.

**Describe the observed behavior**
In my example, I have a `RootStore` like:
```
const RootStore = types
  .model("RootStore", {
    testStore: types.optional(TestStore, () => TestStore.create({}))
  })
```

If I create the root store like `RootStore.create({ testStore: {} })`, `TaskStore.afterAttach` and `TaskStore.afterCreate` are never called. If I create the root store like `RootStore.create({})`, the connected model's `afterAttach` and `afterCreate` are called like I expect.

I feel like the behavior I am expecting *should* be correct based on the [afterAttach docs](https://mobx-state-tree.js.org/overview/hooks).

**Comment by makarov-roman** [comment]
@special-character 
Seems like mst do lazy initializing. If you try to access the model you will get expected behavior. 
Look at this [example](https://codesandbox.io/s/mobx-state-tree-afterattach-forked-r802e?file=/src/index.ts) 
But I can imaging how people can get nasty bug here. For example if we want to do some kind of side effects in the hooks (e.g. WS connection or something)

**Comment by special-character** [comment]
@makarov-roman Good find, I didn't notice that. Doing the access right after is a better solution than what I was doing before to get around this.

**Comment by jamonholmgren** [comment]
Might be an opportunity to document this somewhere.
