### ISSUE TITLE
ation funtion not reciving variable

### ISSUE THREAD

**Issue by d7p** [mobxjs/mobx-state-tree#1669]
I have:
* [x] I think something is not working as it should.
  * [x] I've checked documentation and searched for existing issues
  * [x] I've made sure your project is based on the latest MST version 
      I am using version 5.0.1
  * [x] Describe expected behavior
     Model action function is called with input parameters and the action function is passed the input parameter 
  * [x] Describe observed behavior
    Model action function is called with a string input but the function receives the input param as null.
   
```
export const Root = types.model("Root", {
  // Other models .....
  user: types.maybeNull(User),
})
  .actions(self => ({
    getUser (u) {
      // u is always null
      // fetchUser is an action method on the user child model 
      self.user.fetchUser(u);
    }
  }));

  otherStuff.then(credential => {
    ///credetials.userId provides a GUID string that i can get the other user details like user name with
    rootStoreInstance.getUser(credential.userId);
}

```
I can't see why the call to getUser always recives null as the `u` paramiter

Thank you for any help in advance.

**Comment by Romanior** [comment]
Could you please format you code with block code formatting, 
"\```js code ```"

**Comment by BATCOH** [comment]
I put slightly modified example to https://codesandbox.io/s/hardcore-pond-vydf2?file=/src/index.js
And `getUser` receives userId in `u` parameter as expected, you can check it.
Maybe there is a problem with some other part of your code?

**Comment by d7p** [comment]
Thank you @BATCOH 
Your examples works. After looking at it an comparing it to my code it turns out that this was an issue with FireBase Auth. it logged to the console the correct value, but provided an `undefined` value when passed into the action. Not sure why this would be the case but I was able to sort out this issue by setting it to a var before passing it to the action function.

Thank you for your help and sorry for wasting your time.
