### ISSUE TITLE
Constructor semantic

### ISSUE THREAD

**Issue by cpunion** [mobxjs/mobx-state-tree#167]
Commonly I use many models, some fields should assign on create, to reduces code, I rewrite `create` function like this:

```js
const Tree = types.model('Tree', {
  children: types.array(types.late(() => Tree)),
  data: types.frozen
})

const oldTreeCreate = Tree.create.bind(Tree)
Tree.create = function(attrs) {
  const tree = oldTreeCreate({
    children: [],
    ...attrs
  })
  return tree
}
```

So just call `Tree.create()`  to create Tree model, don't need pass `{children: []}`. This likes a constructor semantic, is there a same way in MST?

**Comment by mattiamanzati** [comment]
You can use `types.optional` to provide default static or dynamic values for attributes.

https://mattiamanzati.github.io/mobx-state-tree-playground/build/index.html#src=import%20%7B%20types%2C%20unprotect%20%7D%20from%20%22mobx-state-tree%22%0Aimport%20%7B%20inspect%20%7D%20from%20%22mobx-state-tree-playground%22%0A%0Alet%20nextId%20%3D%200%0Aconst%20Tree%20%3D%20types.model('Tree'%2C%20%7B%0A%20%20id%3A%20types.optional(types.number%2C%20()%20%3D%3E%20nextId%2B%2B)%2C%0A%20%20children%3A%20types.optional(types.array(types.late(()%20%3D%3E%20Tree))%2C%20%5B%5D)%2C%0A%20%20data%3A%20types.frozen%0A%7D)%0A%0ATree.create()%0ATree.create()%0Aconst%20store%20%3D%20Tree.create()%0Ainspect(store)

**Comment by cpunion** [comment]
Thanks.
