### ISSUE TITLE
Array type cannot be instantiated with a read-only array

### ISSUE THREAD

**Issue by adamkovalsky** [mobxjs/mobx-state-tree#1676]
For example, see the following simple test:
```ts
const ArrayType = types.array(types.string);
const data = ["foo", "bar"] as const;
ArrayType.create(data);
```

This fails with the error: `The type 'readonly ["foo", "bar"]' is 'readonly' and cannot be assigned to the mutable type 'string[]'.ts(2345)`

_Originally posted by @mbest in https://github.com/mobxjs/mobx-state-tree/issues/1314#issuecomment-617906533_

**Comment by jamonholmgren** [comment]
Fixed in 5.1.6.

https://github.com/mobxjs/mobx-state-tree/releases/tag/v5.1.6
