### ISSUE TITLE
Introduce `types.localState` to be able to handle non-serializable, temporarily state

### ISSUE THREAD

**Issue by drcmda** [mobxjs/mobx-state-tree#168]
The problem i face is that i see no place for local data, this also has been the single biggest problem i've had with Redux. 

1. If i have a model for instance that represents a connection, where to put the actual socket object, be it a websocket, socket.io, etc? 
2. And how can that model respond to changes to itself, for instance if "endpoint" is changed it should disconnect the old socket and connect to a new one.

I saw that MST is called React for state. In React i can create a component by extending `React.Component` which offers lifecycles and local scope. Is there something like this that's already possible or planned?

**Comment by mattiamanzati** [comment]
Lifecycles are already a think, and local objects can be easily achieved by using javascript scope functionalities :)

https://mattiamanzati.github.io/mobx-state-tree-playground/build/index.html#src=import%20%7B%20types%20%7D%20from%20%22mobx-state-tree%22%0Aimport%20%7B%20inspect%20%7D%20from%20%22mobx-state-tree-playground%22%0A%0A%2F%2F%20just%20faking%20some%20connection%0Alet%20createFakeConnection%20%3D%20()%20%3D%3E%20(%7B%0A%20%20%20%20events%3A%20%7B%7D%2C%0A%20%20%20%20on(name%2C%20fn)%7B%0A%20%20%20%20%20%20%20%20this.events%5Bname%5D%20%3D%20fn%0A%20%20%20%20%7D%2C%0A%20%20%20%20start()%7B%0A%20%20%20%20%20%20%20%20this.events.open(this)%0A%20%20%20%20%20%20%20%20setTimeout(()%20%3D%3E%20this.events.data(this%2C%20Math.random())%2C%201000)%0A%20%20%20%20%20%20%20%20setTimeout(()%20%3D%3E%20this.events.data(this%2C%20Math.random())%2C%202000)%0A%20%20%20%20%20%20%20%20setTimeout(()%20%3D%3E%20this.events.data(this%2C%20Math.random())%2C%203000)%0A%20%20%20%20%20%20%20%20setTimeout(()%20%3D%3E%20this.events.data(this%2C%20Math.random())%2C%204000)%0A%20%20%20%20%20%20%20%20setTimeout(()%20%3D%3E%20this.events.close(this)%2C%205000)%0A%20%20%20%20%7D%0A%7D)%0A%0A%2F%2F%20real%20code%0Alet%20openedConnections%20%3D%20%7B%7D%0Alet%20nextId%20%3D%200%0Aconst%20getId%20%3D%20()%20%3D%3E%20nextId%2B%2B%0A%0Aconst%20AppStore%20%3D%20types.model(%7B%0A%20%20%20%20isConnected%3A%20types.optional(types.boolean%2C%20false)%2C%0A%20%20%20%20numbers%3A%20types.optional(types.array(types.number)%2C%20%5B%5D)%0A%7D%2C%20%7B%0A%20%20%20%20setConnected(isConnected)%7B%0A%20%20%20%20%20%20%20%20this.isConnected%20%3D%20isConnected%0A%20%20%20%20%7D%2C%0A%20%20%20%20addNumber(n)%20%7B%0A%20%20%20%20%20%20%20%20this.numbers.push(n)%0A%20%20%20%20%7D%2C%0A%0A%20%20%20%20%2F%2F%20tree%20lifecylcle%0A%20%20%20%20afterCreate()%7B%0A%20%20%20%20%20%20%20%20let%20id%20%3D%20getId()%0A%20%20%20%20%20%20%20%20openedConnections%5Bid%5D%20%3D%20createFakeConnection()%0A%20%20%20%20%20%20%20%20openedConnections%5Bid%5D.on('open'%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20this.setConnected(true)%0A%20%20%20%20%20%20%20%20%7D)%0A%20%20%20%20%20%20%20%20openedConnections%5Bid%5D.on('data'%2C%20(c%2C%20data)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20this.addNumber(data)%0A%20%20%20%20%20%20%20%20%7D)%0A%20%20%20%20%20%20%20%20openedConnections%5Bid%5D.on('close'%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20this.setConnected(false)%0A%20%20%20%20%20%20%20%20%20%20%20%20delete%20openedConnections%5Bid%5D%0A%20%20%20%20%20%20%20%20%7D)%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%2F%2F%20start%20the%20connection%0A%20%20%20%20%20%20%20%20openedConnections%5Bid%5D.start()%0A%20%20%20%20%7D%0A%7D)%20%0A%0Ainspect(AppStore.create())

**Comment by drcmda** [comment]
@mattiamanzati lifecycles, ... awesome! That would go a long way already. Though about storing the connection globally. If it would one day be possible to have an extend for a model class that would allow us to componentize state with real scope and class methods, it would be very helpful.

**Comment by mweststrate** [comment]
@drcmda, in principle it is quite easy to support local data; simply unfreezing the object is enough to support this, especially in the 0.8 release where the reconciliation system is improved and object instances are pretty much always reused if possible (comparable with how React reconciles components)

Ideally, a tree node should always be serializable in such a way that it's entire state is captured, so that it can be easily transmitted etc etc. But indeed, lifecycle hooks allow already to "pull" in state. So there are different solutions to this problem

1. Use an external (weak)(hash)map based on the id or path of an object
2. Same as 1, but inject this map in the environment of the store when the tree is created. The advantage of this is that you don't need global variables to store data. Injecting looks like: `Appstore.create({}, { connections: new Map() })`, and then in the life cycle hooks you can use `getEnv(this).connections.set(...)`
3. We could as mentioned just unfreeze models, at which point it becomes an 'at own risk' feature to just store arbitrary data on the instances. At own risk because one has to be aware of the lifecycle of an instance, which might not be too hard to grasp for React users.

Personally, I would go for 2 at this moment, 3 looks like an easy way out, but it might hinder future features of the library? Hard to say at this point :)

**Comment by drcmda** [comment]
@mweststrate interesting, i will check this out. But just one last question, maybe something like the following somewhere in the future? Just like in React, it's ideal to manage local stuff.  It would allow us to create real-world models that have their state portion for serializable data, while still being able to maintain complex, inner state. I'm using the hashmap approach you lined out in redux, too, but we're searching for something that makes this stuff easier.

    import { types, Model } from 'mobx-state-tree'
    class connection extends Model {
        state = { endpoint: types.string }
        actions = { setEndpoint: url => this.endpoint = url }
        constructor() {
            this.socket = undefined;
            this.???onLocalSnapshot???(store, state => this.socket = new io(this.endpoint))
        }
    }

**Comment by mweststrate** [comment]
@drcmda / @mattiamanzati here is another idea:

Introduce a separate type for this; one that is not serializable but is allowed to contain anything you want, like an invisible frozen; 

`socket: types.localState`. Ignored by snapshot, patches etc, but will survive as long as the instance lives

Or maybe generalize reference to a reference that can store any value, but you have to specify how to (de)serialize a reference (basically, by providing a getter and setter)

`socket: types.reference(socketId => socketsMap.get(socketId), socket => socketsMap.set(socket.id, socket)`

**Comment by mondaychen** [comment]
Local data was also the biggest problem my team had with Redux. We invented our own "state tree" system based on Redux. In our models, we have a concept called "model service" (I know it's not a good name). Each service has its own state data space / lifecycles, and behaves differently during (de)serialization.

````         
 Model         
 |             
 |-state (serialized)
 |             
 |-lifecycles (not triggered when deserialized)
 |             
 +-service     
   |           
   |-state (not serialized)  
   |           
   +-lifecycles (triggered when deserialized)
````

Hope this helps.

**Comment by drcmda** [comment]
@mondaychen @mweststrate 

Yep, we also rolled our own in redux. Our models are basically classes that connect to the state tree and channel their changes through setters/getters. 

 I just wish there'd be something easy that takes this problem into account. Everything that's forcing me to bleed into global scope and manage hash maps is going to be complex again at some point. That's pretty much also the reason i'd prefer React over Vue, because React has real classes with scope and local access. I'm waiting a little how MST turns out, i love the concept, but right now it would force us to do the same tedious grunt work outside the model.

**Comment by mweststrate** [comment]
@drcmda I agree, I think MST should address this. It actually can do that very nicely since it has lifecycles and mutability anyway. Updated the issue title to introduce `types.localState(any)`

**Comment by drcmda** [comment]
@mweststrate thanks so much! That means a model then can declare non-observable, local data that all actions have access to? That would solve it. 😊 

Could you also take a quick look over a local onSnapshot method? A model should be able to know when a new snapshot of itself is available in order to react to it, notify the localState, etc. That's the last puzzle piece.

**Comment by mweststrate** [comment]
@drcmda see : https://github.com/mobxjs/mobx-state-tree/tree/localstate#volatile-state

**Comment by mweststrate** [comment]
once this is merged, could you play with this and open a new issue if you need an additonal hook for snapshots? I'm not sure if that fits nicely, because you would then probably also need a hook for patches, or for a specific field to be changed. In which caes it is probably just better to setup a reaction: `addDisposer(this, reaction(() => this.myField, () => { abortCurrentRequestAndFireNewOne }))`

**Comment by mweststrate** [comment]
Released, hence cloded
