### ISSUE TITLE
Compatibility with MobX 6 useProxies: "ifavailable" option

### ISSUE THREAD

**Issue by BATCOH** [mobxjs/mobx-state-tree#1702]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/mobx-state-tree-todolist-ifavailable-t9w2z?file=/index.js

**Describe the expected behavior**
MST should work with `useProxies: "ifavailable"` option from `mobx`.

**Describe the observed behavior**
MST uses `Object.defineProperty` internally in [`addHiddenFinalProp`/`addHiddenWritableProp` utils](https://github.com/mobxjs/mobx-state-tree/blob/8ce9992ff5480e1e7c66803b6692354a1121d801/packages/mobx-state-tree/src/utils.ts#L207-L227) that lead to crash in `ifavailable` mode.
See also [#2876@mobx](https://github.com/mobxjs/mobx/issues/2876)
Since `mobx@6.3.0` released with a convenient `defineProperty` from `object-api`, it seems to be a good idea to use it in MST.

I'm actually working on PR right now and will add it as soon as I can.

**Comment by jamonholmgren** [comment]
5.0.2 is released: https://github.com/mobxjs/mobx-state-tree/releases/tag/v5.0.2

Please test it on your project and report issues.

Thanks again @BATCOH !
