### ISSUE TITLE
How do I make types.array required?

### ISSUE THREAD

**Issue by janva255** [mobxjs/mobx-state-tree#1704]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [x] I tried [GitHub Discussions](https://github.com/mobxjs/mobx-state-tree/discussions)

According to docs it's doing this now:

```
Since v3, maps and arrays are optional by default, this is:

types.array(OtherType)
// is the same as
types.optional(types.array(OtherType), [])
```

But what if I want to remove the optional case? and forcing to input the array?

**Comment by EmilTholin** [comment]
Hi @janva255!

I'm not sure that's possible. What is you use case?

You could use [`types.refinement`](https://mobx-state-tree.js.org/API/#refinement), but that will not be picked up by TypeScript, and feels a bit forced:

```js
types.refinement(types.array(OtherType), (value) => Array.isArray(value))
```

If you want to differentiate between if the model was instantiated with an array or not, you could use [`types.maybe`](https://mobx-state-tree.js.org/API/#maybe) or [`types.maybeNull`](https://mobx-state-tree.js.org/API/#maybeNull):

```js
const OtherType = types.model({
  foo: types.string
});

const SomeType = types.model({
  arr: types.maybe(types.array(OtherType))
});

const someType1 = SomeType.create({});
console.log(someType1.arr); // undefined

const someType2 = SomeType.create({ arr: [] });
console.log(someType2.arr); // []
```
