### ISSUE TITLE
404 links in API.md

### ISSUE THREAD

**Issue by mondaychen** [mobxjs/mobx-state-tree#173]
Many links on https://github.com/mobxjs/mobx-state-tree/blob/master/API.md are 404

**Comment by vonovak** [comment]
how exactly can one help fix these 404s?

**Comment by mattiamanzati** [comment]
The issue is on how documentjs generates the docs. It generates that out of the test-lib folder, so Thats why links are wrong. It needs either to be reconfigured correctly or postprocess the generated api to repass the link.

**Comment by mondaychen** [comment]
@mattiamanzati maybe we switch to some other tool? such as http://typedoc.org/

**Comment by mattiamanzati** [comment]
Yeah, I am completely open to that :) @mondaychen

**Comment by mweststrate** [comment]
Fixed the 404's and therefor closing the issue. I'm fine with another tool, although I am not too fond of typedoc (generates a lot of noise in my experience, and needs hosting)

**Comment by mweststrate** [comment]
Dropped the code links. After fixing them, figured that they will be pointing to the wrong line number any, as it are the js line numbers, not ts. And the links are ugly anyway :wink:

**Comment by vonovak** [comment]
nice, can't wait for 1.0
