### ISSUE TITLE
Read-only error thrown when using both views and actions

### ISSUE THREAD

**Issue by lucasjohnston** [mobxjs/mobx-state-tree#1737]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
```
const initials = {
  hello: 'world'
}
export const TestModel = types
  .model()
  .props({
    hello: types.string,
  })
  .views(self => ({
    get hello(): string {
      return self.hello
    }
  }))
  .actions(self => ({
    clear: () => {
      self.hello = initials.hello
      return self
    }
  }))
```

**Describe the expected behavior**
Compiles without error.

**Describe the observed behavior**
An error is thrown within the action: `Cannot assign to 'hello' because it is a read-only property. TS(2540)`
When the order of the functions are changed (i.e. `views()` is moved below `actions()`) the error disappears.

**Comment by mattruby** [comment]
In my experience, your view names must be different than your field names.

**Comment by jamonholmgren** [comment]
@mattruby is correct -- you need to name your view differently than a property.

https://codesandbox.io/s/frosty-mahavira-rhfin?file=/src/index.js

We could probably provide a better error for this situation.
