### ISSUE TITLE
Memoized getter doesn't execute after creation of object

### ISSUE THREAD

**Issue by RubenGijbels** [mobxjs/mobx-state-tree#174]
I have a simple store like this:

```

const Page = types.model("Example", {
	name: types.string,
	get displayName() {
		return `${this.name}'s Page`
	}
})

const Store = types.model("Store", {
	pages: types.array(Page)
},
{
	addPage(name) {
		this.pages.push(Page.create({
			name
		}))
	}
})
```

But when I display the displayName in my react application, I see following: "[object Object]'s Page".

I put a console.log(this.name) in the getter and apparantly it only fires on creation of the model. 
this.name is then the following object:
![image](https://user-images.githubusercontent.com/10114451/26921784-5c1a13fe-4c3d-11e7-8563-fefb8a5616b8.png)

It doesn't fire again when I create a new object in the addPage()-method

**Comment by mattiamanzati** [comment]
Can you please share how you pass the store to your React Component? :)

**Comment by RubenGijbels** [comment]
As a prop to my root component and then again as a prop to my observer component.

**Comment by mattiamanzati** [comment]
Can you please share that so I can reproduce the bug? :)

**Comment by mattiamanzati** [comment]
https://mattiamanzati.github.io/mobx-state-tree-playground/build/index.html#src=import%20React%20from%20%22react%22%0Aimport%20%7B%20types%20%7D%20from%20%22mobx-state-tree%22%0Aimport%20%7B%20observer%20%7D%20from%20%22mobx-react%22%0Aimport%20%7B%20inspect%2C%20render%20%7D%20from%20%22mobx-state-tree-playground%22%0A%0Aconst%20Page%20%3D%20types.model(%22Example%22%2C%20%7B%0A%09name%3A%20types.string%2C%0A%09get%20displayName()%20%7B%0A%09%09return%20%60%24%7Bthis.name%7D's%20Page%60%0A%09%7D%0A%7D)%0A%0Aconst%20Store%20%3D%20types.model(%22Store%22%2C%20%7B%0A%09pages%3A%20types.optional(types.array(Page)%2C%20%5B%5D)%0A%7D%2C%0A%7B%0A%09addPage(name)%20%7B%0A%09%09this.pages.push(Page.create(%7B%0A%09%09%09name%0A%09%09%7D))%0A%09%7D%0A%7D)%0Aconst%20store%20%3D%20Store.create()%0Ainspect(store)%0A%0Aconst%20PageList%20%3D%20observer(%0A%20%20%20%20props%20%3D%3E%20%0A%20%20%20%20%20%20%20%20%3Cul%3E%0A%20%20%20%20%20%20%20%20%7Bprops.store.map(page%20%3D%3E%20%3Cli%3E%7Bpage.name%7D%3C%2Fli%3E)%7D%0A%20%20%20%20%20%20%20%20%3C%2Ful%3E%20%0A)%0A%0Aconst%20App%20%3D%20observer(%0A%20%20%20%20props%20%3D%3E%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20onClick%3D%7B()%20%3D%3E%20props.store.addPage('new%20page')%7D%3EAdd%20page%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3CPageList%20store%3D%7Bprops.store.pages%7D%20%2F%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A)%0A%0Arender(%3CApp%20store%3D%7Bstore%7D%20%2F%3E)%0A

**Comment by RubenGijbels** [comment]
Ok, I've been testing a bit and I think I found the cause. Weird as it may be. 

The code I provided was somewhat more simplified than what I had in my application.
I wanted to store different kinds of pages in the pages array. For this I wanted to simulate inheritance (because all pages have some common properties), I used the object rest spread operator for this, as recommended in the docs. Like this:

`const PageProperties = {
	id: types.identifier(types.number),
	active: types.boolean
}

const PageSearch = types.model("PageSearch", {
	...PageProperties,
	type: types.literal("SEARCH"),
	displayName: "Search",
	filter: types.string
})

const PagePerson = types.model("PagePerson", {
	...PageProperties,
	type: types.literal("PERSON"),
	name: types.string,
	get displayName() {
		return `${this.name}'s mission`
	}
})`

When I removed the object spread and just copy pasted the properties in the object, all worked as expected.

**Comment by mattiamanzati** [comment]
Yeah, that's because using spread mess up with getters/setter. That's how spread works. You also may have a look at types.extend :)

**Comment by RubenGijbels** [comment]
The docs state this might be removed in the future though. Is it safe to use?

**Comment by mattiamanzati** [comment]
For production no, you might end up cloning how it works internally for now :)

**Comment by mweststrate** [comment]
@mattiamanzati maybe we should add support for explicit `computed` to make model manipulation easier?
