### ISSUE TITLE
Type issue when assigning a store with a reference

### ISSUE THREAD

**Issue by RickLucassen** [mobxjs/mobx-state-tree#1764]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/mobx-state-tree-todolist-forked-o9yj3

**Describe the expected behavior**
In the example we're defining a root store with another store as a property. That store has a property of type array of a model.
When that model doesn't have a types.reference present everything is fine. However, when the model does have a types.reference present typescript complains about an incorrect type.

Typescript should resolve these types correctly.

**Describe the observed behavior**
As seen in the `rootStore`, where there is a version with and without the reference, the one with the reference generates a typescript error about the `someModel` type not matching.

**Comment by RickLucassen** [comment]
It seems that wrapping the `createTodoStoreWithReference` with `castToSnapshot` does make it work. Would this be the proposed solution?

Still strange that without the `castToSnapshot` there is a difference in behavior between the two stores (with and without a reference).

**Comment by coolsoftwaretyler** [comment]
Hey @RickLucassen - sorry it took so long for anyone to get back to you here. We are trying to give some more care and attention here to MobX-State-Tree

I don't know for 100% sure that `castToSnapshot` is the best case solve, but if it did help your issue, that makes sense. There are some known issues with the TypeScript inferences in MST, and we're highly interested in fixing that.

If you're still having the problem, or if you solved it elsewise, I'd love to hear what worked for you. Or if you moved on, no worries.

For now, I'll leave this issue and label with with TS and help/PR welcome. Hopefully we can find some ways to improve this moving forward.

**Comment by thegedge** [comment]
Curious: is this still an issue? I'm not able to see any type errors:

![CleanShot 2024-07-06 at 13 51 45@2x](https://github.com/mobxjs/mobx-state-tree/assets/833576/8a920b1e-08db-46e8-b9f0-b07bc2bc8058)

**Comment by coolsoftwaretyler** [comment]
@thegedge - I see this in the reproduction CodeSandbox:

<img width="408" alt="Screenshot 2024-07-07 at 12 59 03 PM" src="https://github.com/mobxjs/mobx-state-tree/assets/29899554/64e065fe-c482-4ee8-be3c-0f3f89323f43">

Here's the full error (it's quite long)

<details>


```sh
Type 'ModelInstanceTypeProps<{ todos: IArrayType<IModelType<{ id: IOptionalIType<ISimpleType<number>, [undefined]>; title: ISimpleType<string>; finished: IType<boolean | undefined, boolean, boolean>; someModel: IMaybeNull<...>; }, {}, _NotCustomized, _NotCustomized>>; }> & { ...; } & IStateTreeNode<...>' is not assignable to type '{} & Partial<ExtractCFromProps<{ todos: IArrayType<IModelType<{ id: IOptionalIType<ISimpleType<number>, [undefined]>; title: ISimpleType<string>; finished: IType<boolean | undefined, boolean, boolean>; someModel: IMaybeNull<...>; }, {}, _NotCustomized, _NotCustomized>>; }>>'.
  Type 'ModelInstanceTypeProps<{ todos: IArrayType<IModelType<{ id: IOptionalIType<ISimpleType<number>, [undefined]>; title: ISimpleType<string>; finished: IType<boolean | undefined, boolean, boolean>; someModel: IMaybeNull<...>; }, {}, _NotCustomized, _NotCustomized>>; }> & { ...; } & IStateTreeNode<...>' is not assignable to type 'Partial<ExtractCFromProps<{ todos: IArrayType<IModelType<{ id: IOptionalIType<ISimpleType<number>, [undefined]>; title: ISimpleType<string>; finished: IType<boolean | undefined, boolean, boolean>; someModel: IMaybeNull<...>; }, {}, _NotCustomized, _NotCustomized>>; }>>'.
    Types of property 'todos' are incompatible.
      Type 'IMSTArray<IModelType<{ id: IOptionalIType<ISimpleType<number>, [undefined]>; title: ISimpleType<string>; finished: IType<boolean | undefined, boolean, boolean>; someModel: IMaybeNull<...>; }, {}, _NotCustomized, _NotCustomized>> & IStateTreeNode<...>' is not assignable to type 'readonly ModelCreationType<ExtractCFromProps<{ id: IOptionalIType<ISimpleType<number>, [undefined]>; title: ISimpleType<string>; finished: IType<boolean | undefined, boolean, boolean>; someModel: IMaybeNull<...>; }>>[] | undefined'.
        Type 'IMSTArray<IModelType<{ id: IOptionalIType<ISimpleType<number>, [undefined]>; title: ISimpleType<string>; finished: IType<boolean | undefined, boolean, boolean>; someModel: IMaybeNull<...>; }, {}, _NotCustomized, _NotCustomized>> & IStateTreeNode<...>' is not assignable to type 'readonly ModelCreationType<ExtractCFromProps<{ id: IOptionalIType<ISimpleType<number>, [undefined]>; title: ISimpleType<string>; finished: IType<boolean | undefined, boolean, boolean>; someModel: IMaybeNull<...>; }>>[]'.
          Types of property 'concat' are incompatible.
            Type '{ (...items: ConcatArray<ModelInstanceTypeProps<{ id: IOptionalIType<ISimpleType<number>, [undefined]>; title: ISimpleType<string>; finished: IType<boolean | undefined, boolean, boolean>; someModel: IMaybeNull<...>; }> & IStateTreeNode<...>>[]): (ModelInstanceTypeProps<...> & IStateTreeNode<...>)[]; (...items: Conca...' is not assignable to type '{ (...items: ConcatArray<ModelCreationType<ExtractCFromProps<{ id: IOptionalIType<ISimpleType<number>, [undefined]>; title: ISimpleType<string>; finished: IType<boolean | undefined, boolean, boolean>; someModel: IMaybeNull<...>; }>>>[]): ModelCreationType<...>[]; (...items: (ModelCreationType<...> | ConcatArray<...>...'.
              Types of parameters 'items' and 'items' are incompatible.
                Type 'ConcatArray<ModelCreationType<ExtractCFromProps<{ id: IOptionalIType<ISimpleType<number>, [undefined]>; title: ISimpleType<string>; finished: IType<boolean | undefined, boolean, boolean>; someModel: IMaybeNull<...>; }>>>' is not assignable to type 'ConcatArray<ModelInstanceTypeProps<{ id: IOptionalIType<ISimpleType<number>, [undefined]>; title: ISimpleType<string>; finished: IType<boolean | undefined, boolean, boolean>; someModel: IMaybeNull<...>; }> & IStateTreeNode<...>>'.
                  Type 'ModelCreationType<ExtractCFromProps<{ id: IOptionalIType<ISimpleType<number>, [undefined]>; title: ISimpleType<string>; finished: IType<boolean | undefined, boolean, boolean>; someModel: IMaybeNull<...>; }>>' is not assignable to type 'ModelInstanceTypeProps<{ id: IOptionalIType<ISimpleType<number>, [undefined]>; title: ISimpleType<string>; finished: IType<boolean | undefined, boolean, boolean>; someModel: IMaybeNull<...>; }> & IStateTreeNode<...>'.
                    Type 'ModelCreationType<ExtractCFromProps<{ id: IOptionalIType<ISimpleType<number>, [undefined]>; title: ISimpleType<string>; finished: IType<boolean | undefined, boolean, boolean>; someModel: IMaybeNull<...>; }>>' is not assignable to type 'ModelInstanceTypeProps<{ id: IOptionalIType<ISimpleType<number>, [undefined]>; title: ISimpleType<string>; finished: IType<boolean | undefined, boolean, boolean>; someModel: IMaybeNull<...>; }>'.
                      Types of property 'id' are incompatible.
                        Type 'number | undefined' is not assignable to type 'number'.
                          Type 'undefined' is not assignable to type 'number'.typescript(2322)
```

</details>

The CodeSandbox has MobX and MST on latest, but I got the same error when I upgraded the TypeScript version to `5.3.3`.

**Comment by thegedge** [comment]
Ahh, I missed the root store bit. I wonder if https://github.com/mobxjs/mobx-state-tree/issues/1568 is related 🤔 

I'll 👀 again whenever I have some time. Thanks, @coolsoftwaretyler!

**Comment by thegedge** [comment]
Looks like the next release will resolve this issue 🎉 

![CleanShot 2024-08-04 at 10 29 41@2x](https://github.com/user-attachments/assets/264d2089-a28d-46ff-81e9-94b0ebe0e603)

(the error on the function is because it's unused)
