### ISSUE TITLE
mst-middlewares has a ^ peer dependency on mobx-state-tree

### ISSUE THREAD

**Issue by FreeFrags** [mobxjs/mobx-state-tree#1779]
**_Bug report_**

* [X] I've checked documentation and searched for existing issues
* [X] I've made sure my project is based on the latest MST version

**Describe the expected behavior**
mst-middlewares has a ^ peer dependency on mobx-state-tree shouldn't this be >= 

https://github.com/mobxjs/mobx-state-tree/blob/e6025cc3d62094fc2b4272ff53607c862efd1975/packages/mst-middlewares/package.json#L52

**Comment by jamonholmgren** [comment]
Hm, good question. @mweststrate, do you know?

**Comment by FreeFrags** [comment]
The reason for asking is i get the following when installing with: 

- node v16.7.0
- npm 7.20.3

in my package.json:
"mobx-state-tree": "^5.0.1",
"mst-middlewares": "^5.0.1",

https://github.com/mobxjs/mobx-state-tree/blob/e6025cc3d62094fc2b4272ff53607c862efd1975/packages/mst-middlewares/package.json#L52

`npm ERR! Invalid Version: ^5.0.1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Raymond\AppData\Local\npm-cache\_logs\2021-09-01T06_56_29_442Z-debug.log
PS C:\Source\MyApp\ClientApp> npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: msg.cartographer.web@0.1.0
npm ERR! Found: mobx-state-tree@5.0.2
npm ERR! node_modules/mobx-state-tree
npm ERR!   mobx-state-tree@"^5.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer mobx-state-tree@"^3.11.0" from mst-middlewares@5.0.2
npm ERR! node_modules/mst-middlewares
npm ERR!   mst-middlewares@"^5.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!`

**Comment by mweststrate** [comment]
Yeah probably just needs bumping. Might be a lerna misconfiguration.

**Comment by jeremy-coleman** [comment]
Another option is  "mobx-state-tree": "*". The "*" will just yield to whatever version the user has specified and otherwise install "mobx-state-tree": "latest" , which really should never happen because people using this will have mst installed.

**Comment by mweststrate** [comment]
`^` is the correct config for the peer, as compatibility cross majors is not supported nor guaranteed nor likely. If mst-middlewares is not up to date it probably needs republishing.

**Comment by jeremy-coleman** [comment]
I completely agree, but npm owners have too many good ideas

**Comment by coolsoftwaretyler** [comment]
Hey folks, looks like this was resolved with https://github.com/mobxjs/mobx-state-tree/pull/1838, so I'm going to close this out. 

Thank you!
