### ISSUE TITLE
Use prettier

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#178]
After #152 is merged.

Preferrably: no-semi :)

**Comment by mattiamanzati** [comment]
:+1: For no-semi :)

**Comment by adonis-work** [comment]
:+1: btw, you can automate this:

A suggestion from our internal styleguide, add this to package.json scripts and call it before each commit:

`prettier-standard src/*.js; standard --fix src/*.js`

This forces all code to be formated in exactly the same way, even adds/removes newlines to optimally fit any function/array/object etc... into 80 chars width while removing any unneeded white space.

On the input side you can newline and double space each word of your code, use semicolons or tabs, write everything in a one-liner, align arrays with spaces as ASCII art and simply don't care about the code style, as it leaves no space for bike shedding. It works with any code and always gives the same output for the same command sequence.

**Comment by mweststrate** [comment]
Done!
