### ISSUE TITLE
Issue with Jest >= 27

### ISSUE THREAD

**Issue by JSteunou** [mobxjs/mobx-state-tree#1781]
**_Bug report_**

Not sure were is the issue exactly but upgrade Jest from 26 to 27 on our large code base using mobx & MST we have seen some errors in our tests

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [ ] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**

**Describe the expected behavior**

All tests passed with Jest 26 on our codebase

**Describe the observed behavior**

Now we have this error where there are some arrays comparison 

```
    -   "objects": Array [
    +   "objects": LegacyObservableArray [
```

Our setup did not change, and always enforce the use of proxies so we are quite surprise to see this error.

Jest made some change on the runner, that might be linked, it is uses a node runner by default, and we have to setup it on jsdom, but that is not a big change, just flipping some default as they say.

I frankly dont know if the error is on your side or Jest side or our side... all we did was upgrading Jest.

**Comment by aviral-clarifai** [comment]
Hey! This is because for some reason there are no proxies available in the environment.
This happens when you use `configure` function from mobx with useProxies: false

https://mobx.js.org/configuration.html

**Comment by JSteunou** [comment]
I can assure you useProxies is set on `true` otherwise our base code wouldnot work on IE11 or Jest 26. The issue is only with Jest 27 :(

**Comment by coolsoftwaretyler** [comment]
Hey @JSteunou - I'm sorry it took so long for you to get an answer. I've got a MobX-State-Tree test suite that's been on Jest 29 for the last month, and was Jest 27 for about six months before that with no issue. In that time we migrated from MST 3 -> MST 5.

So a few questions for you:

1. Is this still a problem for you? Or did you resolve it/move on from the issue overall?
2. If this is still a problem, can you send some sample code that fails, maybe a sample repository?

Totally understand if this is too little too late. But happy to help. If I don't hear back in about two weeks, I'll probably close out this issue.

**Comment by JSteunou** [comment]
I couldnot tell, I'm not working on the related project anymore.
