### ISSUE TITLE
Switch from webpack to rollup for bundling

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#179]
Does rollup support peer deps properly? Rollup will make the build smaller and faster, support tree shaking and more debugger friendly code

**Comment by jbrantly** [comment]
Out of curiosity, doesn't webpack2 support tree shaking? Is there a difference between the tree shaking support in webpack2 vs rollup?

**Comment by mweststrate** [comment]
Afaik webpack 2 was quite limited in this regard. Anyway rollup bundles are much cleaner; they inline all the sources, rather than webpack that tries to preserve the original source modules, which is totally not interesting for a library like this, and hampers the opportunities for minification

**Comment by mweststrate** [comment]
@rossipedia, interested to roll up this one as well? No legacy default exports here ;-)

**Comment by rossipedia** [comment]
sure, why not :)

**Comment by rossipedia** [comment]
62.7KB with Webpack
44.5KB with Rollup

I think just for the heck of it I'm going to try webpack@3 with scope hoisting, see what that ends up looking like

**Comment by rossipedia** [comment]
Roughly the same with webpack 3 and scope hoisting. Rollup definitely the clear winner re: size.

**Comment by mweststrate** [comment]
Released in 0.8.0. The standard export is now rolled-up as well :)

**Comment by mweststrate** [comment]
And added es6 module for the fancyness of it :
