### ISSUE TITLE
Introduce optional generic argument in types.frozen (and types.localState) to make it easily strong typeable

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#181]

**Comment by mattiamanzati** [comment]
New plan: Support types.immutable(Type) which basically froze the node and throw if childs or node  is changing

**Comment by xaviergonz** [comment]
really nice idea, I've got some nodes that are supposed to be immutable once attached to a type but there's no way to enforce it (e.g points, colors...)

**Comment by mweststrate** [comment]
This can now be expressed using `types.custom` as well (which just returns the value in the from/to snapshot functions without further transformation)
