### ISSUE TITLE
Clone is resetting volatile state

### ISSUE THREAD

**Issue by kidroca** [mobxjs/mobx-state-tree#1811]
When a node with volatile state is cloned, the created clone does not have the same volatile state as the source

**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**

https://codesandbox.io/s/mobx-state-tree-todolist-forked-3xxej?file=/models/TodoStore.js

Steps:
1. Change the volatile state of an object by changing input.
2. Press [Clone] to create a clone
3. Observe that the newly added clone does not carry the change of the volatile state

---

**Describe the expected behavior**

Cloning a node should clone current volatile state

**Describe the observed behavior**

Cloning a uses the default/initial volatile state (from the model definition) of the cloned node

**Comment by coolsoftwaretyler** [comment]
Hey folks, thanks for the issue and discussion here. It's been a while since we had any movement on this, and I agree that this is by-design. I'm going to close out this issue for now because I think this response is spot-on.
