### ISSUE TITLE
How to build a tree with reference

### ISSUE THREAD

**Issue by cpunion** [mobxjs/mobx-state-tree#182]
I just try to build a tree, put all entries into `tree.objects`, and reference in `tree.children`, but failed. When I don't use `reference`, and just put `id` into a field, it works fine. Below is the demo code, please inspire me.

https://mattiamanzati.github.io/mobx-state-tree-playground/build/index.html#src=import%20React%20from%20%22react%22%0Aimport%20%7B%20types%20%7D%20from%20%22mobx-state-tree%22%0Aimport%20%7B%20observer%20%7D%20from%20%22mobx-react%22%0Aimport%20%7B%20inspect%2C%20render%20%7D%20from%20%22mobx-state-tree-playground%22%0A%0Aconst%20Folder%20%3D%20types.model('Folder'%2C%20%7B%0A%20%20%20%20id%3A%20types.identifier()%2C%0A%20%20%20%20name%3A%20types.string%2C%0A%20%20%20%20files%3A%20types.array(types.string)%0A%7D)%0A%0Aconst%20Tree%20%3D%20types.model('Tree'%2C%20%7B%0A%20%20%20%20children%3A%20types.array(types.late(()%20%3D%3E%20Tree))%2C%0A%20%20%20%20data%3A%20types.reference(types.maybe(Folder))%0A%7D)%0A%0Aconst%20Storage%20%3D%20types.model('Storage'%2C%20%7B%0A%20%20%20%20objects%3A%20types.map(Folder)%2C%0A%20%20%20%20tree%3A%20Tree%0A%7D%2C%20%7B%0A%20%20%20%20addFolder(data)%20%7B%0A%20%20%20%20%20%20%20%20const%20folder%20%3D%20Folder.create(data)%0A%20%20%20%20%20%20%20%20this.objects.put(folder)%0A%20%20%20%20%20%20%20%20this.tree.children.push(Tree.create(%7Bdata%3A%20folder%2C%20children%3A%20%5B%5D%7D))%0A%20%20%20%20%7D%0A%7D)%0A%0Aconst%20store%20%3D%20Storage.create(%7Bobjects%3A%20%7B%7D%2C%20tree%3A%20%7Bchildren%3A%20%5B%5D%2C%20data%3A%20null%7D%7D)%0Ainspect(store)%0A%0Aconst%20folder%20%3D%20%7Bid%3A%20'1'%2C%20name%3A%20'Folder%201'%2C%20files%3A%20%5B'a.jpg'%2C%20'b.jpg'%5D%7D%0Astore.addFolder(folder)%0A

Always see:
```
Error: [mobx-state-tree] Failed to assign a value to a reference; the value should already be part of the same model tree
```

**Comment by mattiamanzati** [comment]
Thats a known issue, should be fixed in #152 where references behaves a little differently :)

**Comment by cpunion** [comment]
Sounds great! How is that progress? :)

**Comment by mattiamanzati** [comment]
Should be live soon I think, I added a test for your use case and passes, can you please check that the assertions are right? :) 
https://github.com/mobxjs/mobx-state-tree/pull/152/commits/ed7df2df4410142b613ef1972a94864ea7275b93#diff-4f5616b5de5a2cbc9fdc4673ea91d15cR535

**Comment by cpunion** [comment]
Yes, it's right.

But I feel using `getRoot` in a `Tree` model is not reusable, I want use it in other place without `objects`, is `getRoot` the only way to do that?

**Comment by mattiamanzati** [comment]
It depends on your data structure, you can also store subsets of objects alongside the "children", but this way you wont have a centralized store point for your objects, so before adding a new one onto the tree you need to check manually if not already present. Otherways it will throw because the same object already exists somewhere in the tree :)

**Comment by cpunion** [comment]
Thanks! Can't wait :)

**Comment by mattiamanzati** [comment]
0.7.0 is out and should fix this! :)

**Comment by cpunion** [comment]
After a hard work, I converted my project to use new release of MST! Some fields like `folderIds: types.array[types.string]` be converted to `folders: [types.references(Folder)]`, so clear.

And it has a break change in new release, `types.map().get(key)` will raise error when key not exists, maybe should record in CHANGELOG.

Didn't meet other problems. Thanks again!

**Comment by mweststrate** [comment]
That was an unintended change :) Will open a new issue, thanks for
reporting!

Op ma 12 jun. 2017 om 14:19 schreef Li Jie <notifications@github.com>:

**Comment by cpunion** [comment]
And another problem in `applyPatch`, this is smallest patch serial:
```
{"op"=>"add", "path"=>"/folders/c8c66935-84f6-4b4e-94c2-ef539e58500a/hovers/0", "value"=>"280e62ef-be67-4224-b66c-4823a5f7b176"}
{"op"=>"remove", "path"=>"/folders/c8c66935-84f6-4b4e-94c2-ef539e58500a/hovers/0"}
```

My model likes this:
```js
// App model
{
  folders: types.map(Folder)
}

// Folder model
{
  objects: types.map(ObjectItem),
  hovers: types.array(types.references(ObjectItem))
}

```

`folder.hovers` reference objects in `folder.hovers`.

Error info:
![image](https://user-images.githubusercontent.com/8459/27035477-0cb77ee4-4fb4-11e7-9039-6428b62cedfc.png)

**Comment by cpunion** [comment]
Added `console.log(node)` in `reference.js`, `node.root.identifierCache` is undefined.

**Comment by mweststrate** [comment]
@cpunion would you mind creating a small repro in the playground (https://mattiamanzati.github.io/mobx-state-tree-playground/build/index.html#), a code sandbox / fiddle or as PR with unit test? (@mattiamanzati is the playground up to date with 0.7.1?)

Please note that you are commenting on a closed issue, best open a new issue for new issues.

**Comment by cpunion** [comment]
Thanks for reminding me. I will try to create a test case later.

Michel Weststrate <notifications@github.com>于2017年6月12日 周一21:24写道：

**Comment by mattiamanzati** [comment]
@cpunion @mweststrate Just updated to 0.7.1! :)
