### ISSUE TITLE
importing flow from mobx-state-tree instead of mobx breaks gestures in react native

### ISSUE THREAD

**Issue by 1mike12** [mobxjs/mobx-state-tree#1820]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [ ] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**

I was reading the docs at https://mobx-state-tree.js.org/concepts/async-actions and noticed the part about 
> Warning: don't import flow from "mobx", but from "mobx-state-tree" instead!
And realized I had done the wrong thing. But as soon as I replace the import for some reason all the gestures like pressing and scrolling are broken in my app. 

I've recreated it in both a windows and microsoft dev environment

Repro steps:
1. setup a project with react-native 0.66.1 and mobx-state-tree 5.0.1
2. create a button with some kind of action
3. click button and see that it works
4. import flow (don't need to use it at all)
5. click button and see that it breaks

**Describe the expected behavior**

gestures work and are unaffected by something random like importing flow

**Describe the observed behavior**

gestures broken

**Comment by coolsoftwaretyler** [comment]
Hey @1mike12 - I'm sorry that no one ever got back to you on this issue. 

Is this still a problem for you? I've got a React Native application on `0.71` which uses `flow` from MST without issue, but I'm also not building for Windows.

If this is still a problem for you, I'd love to see an updated repro. If it's fixed, would also love to hear that it's been resolved.

If I don't hear back from you in two weeks or so, I'll probably close this out. Apologies again for how long it took for a reply!

**Comment by coolsoftwaretyler** [comment]
Closing out now. Sorry we didn't get to you quicker!
