### ISSUE TITLE
How to make nested keys in a model observable?

### ISSUE THREAD

**Issue by 10000multiplier** [mobxjs/mobx-state-tree#1839]
My `UsersStore` looks like this:

```jsx
import { types, flow } from 'mobx-state-tree'
import { editUserInDb } from '../utils/editUserInDb'
import { fetchUserFromDb } from '../utils/fetchUserFromDb'

export const UserModel = types.model('User', {
  id: types.identifier,
  avatar_url: types.maybeNull(types.string),
  bio: types.maybeNull(types.string),
  email: types.maybeNull(types.string),
  firstName: types.maybeNull(types.string),
  lastName: types.maybeNull(types.string),
  phone: types.maybeNull(types.string),
  tag: types.maybeNull(types.string),
  website: types.maybeNull(types.string),
  signup_done: types.boolean,
  password: types.maybeNull(types.string)
})

const UsersModel = types.model('Users', {
  users: types.array(UserModel),
})

export const UsersStore = UsersModel.actions((self) => {
  const setUsers = (users) => {
    self.users.replace(users)
  }
  const addUser = (newUser) => {
    let userExists = self.users.find((user) => user.id === newUser.id)
    if (userExists) {
      userExists = {
        ...userExists,
        ...newUser
      }
    } else {
      self.users.push(newUser)
    }
  }
  const addUsers = (users) => {
    self.users.concat(users)
  }
  const deleteUser = (id) => {
    const userToDelete = self.users.find((user) => user.id === id)
    if (userToDelete) self.users.remove(userToDelete)
  }

  const editUser = flow(function* (id, newData) {
    let userToEdit = self.users.find((user) => user.id === id)
    if (userToEdit) {
      userToEdit = {
        ...userToEdit,
        ...newData,
      }
    }
    let result = yield editUserInDb(id, newData)
    return result
  })

  const getUser = flow(function* (id) {
    let user = self.users.find((userToFind) => userToFind.id === id)
    try {
      const fetchedUser = yield fetchUserFromDb(id)
      user = fetchedUser
      if (!user) {
        self.users.push(fetchedUser)
      }
    } catch (err) {
      console.error('[getUser]', err)
    }
    return user
  })

  return {
    addUsers,
    getUser,
    setUsers,
    addUser,
    deleteUser,
    editUser,
  }
}).views((self) => ({
  lookupUser(id) {
    if (!id) return null
    return self.users.find((userToFind) => userToFind.id === id) || []
  }
}))

```
I've discovered that an instance of the `userModel` object

```jsx
const user = UsersStore.lookupUser(id)
```
is observable, but the nested key `signupDone` of the `userModel` object:

```jsx
const signupDone = UsersStore.lookupUser(id).signup_done
```
is not.

How can I trigger a re-render when only the key `signup_done` changes?

Or am I doing something completely wrong?

Any insights are greatly appreciated.

**Comment by jamonholmgren** [comment]
It looks fine to me and should be observable, @10000multiplier. Can you try making a CodeSandbox that exhibits this behavior?

**Comment by the-mike** [comment]
> 

I think it should not be observable. Only user model instance attributes are actually observable, once you dereference it into separate variable - it not gonna be. Thats due to fact that MobX ( and MST) is using JS proxies behind the scene to archive observability.
@10000multiplier try passing whole user model to place where you need it. If you are using React and want dereferencing, try using useEffect hook with MobX autorun function and signup_done as part of local state. Here's a nice article about this subject https://mobx.js.org/understanding-reactivity.html

**Comment by 10000multiplier** [comment]
@jamonholmgren @the-mike thank you for explaining.

I have the `signupDone` variable set up like this, and console log is returning `true` 😄 :

```jsx
const signupDone = useLocalObservable(() => (usersStore.lookupUser(user?.id).signup_done))

useEffect(() =>
  autorun(() => {
  usersStore.lookupUser(user?.id).signup_done
}), [])

console.log(isObservable(signupDone))
```

Am I doing it correctly?

**Comment by the-mike** [comment]
> @jamonholmgren @the-mike thank you for explaining.
> 
> I have the `signupDone` variable set up like this, and console log is returning `true` 😄 :
> 
> ```js
> const signupDone = useLocalObservable(() => (usersStore.lookupUser(user?.id).signup_done))
> 
> useEffect(() =>
>   autorun(() => {
>   usersStore.lookupUser(user?.id).signup_done
> }), [])
> 
> console.log(isObservable(signupDone))
> ```
> 
> Am I doing it correctly?

I think that `useLocalObservable` expects initialiser function that returns observable object. You should not dereference, but include `console.log` call inside autorun. This way:
```js
useEffect(() => {
  autorun(() => {
    console.log(usersStore.lookupUser(user?.id).signup_done)
  }
}, [])
```
Or (in case you really need to have separate variable for signupDone):
```js
const [signupDone, setSignupDone] = useState(false)
useEffect(() => {
  autorun(() => {
    setSignupDone(usersStore.lookupUser(user?.id).signup_done)
  }
}, [])
console.log(signupDone)
```
In that case component will react in right way (you don't have MobX observable, rather you have simple piece of state). It's totally OK to mix react state with observables.

**Comment by 10000multiplier** [comment]
Thanks. I thought it would work for sure, but

```jsx
useEffect(() => {
  autorun(() => {
    console.log(isObservable(usersStore.lookupUser(user?.id).signup_done))
  }
}, [])
```
still returns false. 

Very strange. 

I'm using react native.

**Comment by the-mike** [comment]
It sould. MobX tracks object key access to to reactive stuff. Once you get into primitive value - it would not be an observable. It is clearly stated in docs. You should pass object reference into observable component and access it via key. In your case 
‘’’js
useEffect(() => {
  autorun(() => {
    console.log(isObservable(usersStore.lookupUser(user?.id)))
  }
}, [])
‘’’

Should return true (you are accessing object field there). And, you can pass user model reference (not signup_done value) to your child component to do updates properly.
Anyway, post here react code where you’re having trouble using observables. It might help figuring out exact nature of your problem.

**Comment by 10000multiplier** [comment]
@the-mike it did end up working, so thank you!

In the `UsersModel` I also added an extra section `user` where I store the active user, so I don't have to go searching `users` every time, that simplified things a little.
