### ISSUE TITLE
Typescript error when I use types.map

### ISSUE THREAD

**Issue by Ridermansb** [mobxjs/mobx-state-tree#1840]
**_Question_**

I'm trying to use `snapshotProcessor` with `types.compose` model but I'm getting typescript error when I use `types.map`

* [x] I've checked documentation and searched for existing issues
* [x] I tried [GitHub Discussions](https://github.com/mobxjs/mobx-state-tree/discussions)

## It's pretty simple idea:

**I have basic Model**

```
const FirebaseDocumentModel = types
  .model({
    id: types.identifier,
    reference: types.frozen()
  })
  .actions((self) => ({
    setReference(reference: DocumentReference) {
      self.reference = reference;
    }
  }));
```

**With a generic `snapshotProcessor` function**

```
function processor<TModel extends typeof FirebaseDocumentModel>(
  Model: TModel
): ISnapshotProcessors<
  ReturnType<typeof Model.create>,
  SnapshotIn<typeof Model>,
  SnapshotOut<typeof Model>,
  Omit<SnapshotOut<TModel>, "id" | "reference">
> {
  return {
    // from snapshot to instance
    preProcessor(
      snapshot: SnapshotIn<typeof Model>
    ): ReturnType<typeof Model.create> {
      return Model.create(castToSnapshot(snapshot));
    },
    // from instance to snapshot
    postProcessor(
      snapshot: SnapshotOut<typeof Model>
    ): Omit<SnapshotOut<TModel>, "id" | "reference"> {
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      const { id, reference, ...data } = snapshot;
      return data;
    }
  };
}
```

**And basic model**

```
const Todo = types.model("Todo", {
  id: types.identifier,
  title: types.string,
  description: types.map(types.string)
});

const TodoModel = types.compose(FirebaseDocumentModel, Todo).named("TodoModel");
```

**With a simple processor**

```
const todoProcessor = processor(TodoModel);

export default types.snapshotProcessor(TodoModel, todoProcessor);
```

## Error

But I'm getting typescript error on `todoProcessor`

> ypes of property 'description' are incompatible.
        Type 'IMSTMap<ISimpleType<string>> & IStateTreeNode<IMapType<ISimpleType<string>>>' is not assignable to type 'IKeyValueMap<string>'.
          Index signature for type 'string' is missing in type 'IMSTMap<ISimpleType<string>> & IStateTreeNode<IMapType

You can check the error on [Code Sandbox](https://codesandbox.io/s/mobx-state-tree-todolist-ts-types-map-error-l4cpy?file=/models/Todo.ts) line 57

**Comment by hurrytospring** [comment]
typescript error when types.model nest types.map, a simplest case here: https://codesandbox.io/s/mobx-state-tree-todolist-ts-types-map-error-forked-fxfbi?file=/models/Todo.ts

**Comment by geoff-mytra** [comment]
Any reason why this issue was closed? I'm seeing the same TypeScript error as mentioned by @hurrytospring.
