### ISSUE TITLE
Allow numbers as keys in maps

### ISSUE THREAD

**Issue by Yamo93** [mobxjs/mobx-state-tree#1845]
> The keys of a map are always strings and not related to the identifier. You can even have a map of objects that don't have an identifier at all. Identifiers sole purpose is for reference handling

_Originally posted by @xaviergonz in https://github.com/mobxjs/mobx-state-tree/issues/1141#issuecomment-454763668_

I find this a bit strange. It is very common that maps have numbers as keys. I should be able to call `myMap.get(123)` and get a matching entry where 123 (a number) is the key.

What's funnier is that the documentation demonstrates how you can do just that, i.e. call `s.todos.get(17)`, and it actually works. But TypeScript is throwing the error: 

`Argument of type 'number' is not assignable to parameter of type 'string'.`

This is to me a clear error in the type definition.

**Comment by dantaylor** [comment]
Did you get an answer on this? I am having the same issue.

**Comment by coolsoftwaretyler** [comment]
Hey @Yamo93 - thanks for the details here. I am also using numbers as keys in a map, but not using any of the TS typings in my project, so I think you're right that this is a type definition issue.

I'm going to label this as such, and we'd welcome PRs to fix it up if you're still interested. Since it's been years, no worries if you're no longer interested.

**Comment by a-hassanzadeh-h** [comment]
Hey @coolsoftwaretyler 
I just made a pull request for this issue, This is my first PR in mobx-state-tree. I study the documentation of mobx-state-tree for the contribution. I don't know if I made a mistake in the process of PR or not, so I will say sorry if I made a mistake unwanted. I would be happy to you  review my PR and let me know the next step

**Comment by coolsoftwaretyler** [comment]
Thanks, @a-hassanzadeh-h! I'll review sometime this weekend or next week.

**Comment by coolsoftwaretyler** [comment]
Hey @chakrihacker - would you actually be interested in reviewing this? I had some unexpected things come up this weekend and I won't be available.

If not, I will still get to you, @a-hassanzadeh-h - just a bit delayed.

**Comment by chakrihacker** [comment]
Sure will do
