### ISSUE TITLE
Documentation for volatile does't mention that volatile expects real variables

### ISSUE THREAD

**Issue by selvan** [mobxjs/mobx-state-tree#1846]
While wrting code, moving a variable inside ```model``` worked, not when moved to ```volatile```.  After spending good chunk of time stumbed upon [the comment](https://github.com/mobxjs/mobx-state-tree/issues/1232#issuecomment-475750805) that says  ```basically volatile expects real variables, (a real string, a real array, etc), so the way to create a "real variable" out of a type is to call create on the type.```

Adding this important piece of information to the [documentation](https://mobx-state-tree.js.org/concepts/volatiles) would help others in the same situation.

**Comment by coolsoftwaretyler** [comment]
Oh interesting, this issue never got closed out when the PR was merged. Closing now. Thanks, @selvan!
