### ISSUE TITLE
applyPatch in 0.7.1: TypeError: Cannot read property 'resolve' of undefined

### ISSUE THREAD

**Issue by cpunion** [mobxjs/mobx-state-tree#185]
Reproduce code:

```js
import React from "react"
import { types, getSnapshot, applySnapshot, onPatch, applyPatch } from "mobx-state-tree"
import { observer } from "mobx-react"
import { inspect, render } from "mobx-state-tree-playground"

const Item = types.model('Item', {
    id: types.identifier(),
    name: types.string
})

const Folder = types.model('Folder', {
    id: types.identifier(),
    objects: types.map(Item),
    hovers: types.array(types.reference(Item))
}, {
    addObject(item) {
        this.objects.put(item)
    },
    addHover(item) {
        this.hovers.push(item)
    },
    removeHover(item) {
        this.hovers = this.hovers.filter(i => i.id === item.id)
    }
})

const folder = Folder.create({id: 'folder 1', objects: {}, hovers: []})
folder.addObject({id: 'item 1', name: 'item 1'})
const item = folder.objects.get('item 1')

const snapshot = getSnapshot(folder)
const newStore = Folder.create(snapshot)
inspect(newStore)

onPatch(folder, (data) => {
    console.log('onPatch', JSON.stringify(data))
    applyPatch(newStore, data)
})

folder.addHover(item)
folder.removeHover(item)
```

https://mattiamanzati.github.io/mobx-state-tree-playground/build/index.html#src=import%20React%20from%20%22react%22%0Aimport%20%7B%20types%2C%20getSnapshot%2C%20applySnapshot%2C%20onPatch%2C%20applyPatch%20%7D%20from%20%22mobx-state-tree%22%0Aimport%20%7B%20observer%20%7D%20from%20%22mobx-react%22%0Aimport%20%7B%20inspect%2C%20render%20%7D%20from%20%22mobx-state-tree-playground%22%0A%0Aconst%20Item%20%3D%20types.model('Item'%2C%20%7B%0A%20%20%20%20id%3A%20types.identifier()%2C%0A%20%20%20%20name%3A%20types.string%0A%7D)%0A%0Aconst%20Folder%20%3D%20types.model('Folder'%2C%20%7B%0A%20%20%20%20id%3A%20types.identifier()%2C%0A%20%20%20%20objects%3A%20types.map(Item)%2C%0A%20%20%20%20hovers%3A%20types.array(types.reference(Item))%0A%7D%2C%20%7B%0A%20%20%20%20addObject(item)%20%7B%0A%20%20%20%20%20%20%20%20this.objects.put(item)%0A%20%20%20%20%7D%2C%0A%20%20%20%20addHover(item)%20%7B%0A%20%20%20%20%20%20%20%20this.hovers.push(item)%0A%20%20%20%20%7D%2C%0A%20%20%20%20removeHover(item)%20%7B%0A%20%20%20%20%20%20%20%20this.hovers%20%3D%20this.hovers.filter(i%20%3D%3E%20i.id%20%3D%3D%3D%20item.id)%0A%20%20%20%20%7D%0A%7D)%0A%0Aconst%20folder%20%3D%20Folder.create(%7Bid%3A%20'folder%201'%2C%20objects%3A%20%7B%7D%2C%20hovers%3A%20%5B%5D%7D)%0Afolder.addObject(%7Bid%3A%20'item%201'%2C%20name%3A%20'item%201'%7D)%0Aconst%20item%20%3D%20folder.objects.get('item%201')%0A%0Aconst%20snapshot%20%3D%20getSnapshot(folder)%0Aconst%20newStore%20%3D%20Folder.create(snapshot)%0Ainspect(newStore)%0A%0AonPatch(folder%2C%20(data)%20%3D%3E%20%7B%0A%20%20%20%20console.log('onPatch'%2C%20JSON.stringify(data))%0A%20%20%20%20applyPatch(newStore%2C%20data)%0A%7D)%0A%0Afolder.addHover(item)%0Afolder.removeHover(item)%0A

See also: https://github.com/mobxjs/mobx-state-tree/issues/182#issuecomment-307785530

**Comment by cpunion** [comment]
UPDATE: Code is simplified.

**Comment by mattiamanzati** [comment]
Will be fixed with next release! :)
