### ISSUE TITLE
Boxes Example isn't Working 

### ISSUE THREAD

**Issue by seflless** [mobxjs/mobx-state-tree#1863]
From a fresh clone the boxes example, fails on `yarn start`. I'm following the `yarn; yarn start` instructions from the README: https://github.com/mobxjs/mobx-state-tree/tree/master/packages/mst-example-boxes#readme

**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
 1. `git clone`
 2. `cd packages/mst-example-boxes`
 3. `yarn`
 4. `yarn start`
 5. You'll get the following huge log out of the error, I'm only copy/pasting the start of the error, that looks the most relevant:
 ```
yarn run v1.22.10
$ node server.js
/Users/francoislaberge/dev/mobx-state-tree/packages/mst-example-boxes/node_modules/webpack-dev-server/node_modules/schema-utils/dist/validate.js:115
    throw new _ValidationError.default(errors, schema, configuration);
    ^

ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'publicPath'. These properties are valid:
   object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, setupMiddlewares?, static?, watchFiles?, webSocketServer? }
    at validate (/Users/francoislaberge/dev/mobx-state-tree/packages/mst-example-boxes/node_modules/webpack-dev-server/node_modules/schema-utils/dist/validate.js:115:11)
    at new Server (/Users/francoislaberge/dev/mobx-state-tree/packages/mst-example-boxes/node_modules/webpack-dev-server/lib/Server.js:231:5)
    at Object.<anonymous> (/Users/francoislaberge/dev/mobx-state-tree/packages/mst-example-boxes/server.js:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {

   ...
```

**Describe the expected behavior**
I'm following the instructions in the [README.md](https://github.com/mobxjs/mobx-state-tree/tree/master/packages/mst-example-boxes#readme) and it's not working.

**Describe the observed behavior**
It throws and error on `yarn start`

**Comment by coolsoftwaretyler** [comment]
Hey @seflless - thanks for letting us know. I'm sorry it took so long to get back to you.

When we get around to https://github.com/mobxjs/mobx-state-tree/issues/2018, we'll fix up the basics with this example so that it has baseline functionality. Hoping to get around to it in the next couple of weeks/months here.

**Comment by coolsoftwaretyler** [comment]
Hey @seflless - I just migrated that example over to a separate repository at https://github.com/coolsoftwaretyler/mst-example-boxes. I fixed up some dependencies and Webpack config, so it should be working over there. 

I'm gonna close this out.
