### ISSUE TITLE
recursive types broken

### ISSUE THREAD

**Issue by amir-arad** [mobxjs/mobx-state-tree#187]
this code:
```javascript
const {types} = require("mobx-state-tree");
const MstNode = types.model("MstNode", {
	value: types.number,
	next: types.maybe(types.late(() => MstNode)),
});
```
throws ```ReferenceError: MstNode is not defined``` from
```
at Late.get [as subType] (.../mst-benchmark/node_modules/mobx-state-tree/lib/types/utility-types/late.js:35:38)
at Late.get [as flags] (.../mst-benchmark/node_modules/mobx-state-tree/lib/types/utility-types/late.js:27:24)
```
after upgrading to 0.7.1.

love your work!

**Comment by cpunion** [comment]
Reproduced at https://mattiamanzati.github.io/mobx-state-tree-playground/build/index.html#src=import%20React%20from%20%22react%22%0Aimport%20%7B%20types%2C%20getSnapshot%2C%20applySnapshot%2C%20onPatch%2C%20applyPatch%20%7D%20from%20%22mobx-state-tree%22%0Aimport%20%7B%20observer%20%7D%20from%20%22mobx-react%22%0Aimport%20%7B%20inspect%2C%20render%20%7D%20from%20%22mobx-state-tree-playground%22%0A%0Aconst%20MstNode%20%3D%20types.model(%22MstNode%22%2C%20%7B%0A%09value%3A%20types.number%2C%0A%09next%3A%20types.maybe(types.late(()%20%3D%3E%20MstNode))%2C%0A%7D)%3B%0A%0Aconst%20store%20%3D%20MstNode.create(%7Bvalue%3A%201%2C%20next%3A%20null%7D)%0Ainspect(store)%0A

```js
import React from "react"
import { types, getSnapshot, applySnapshot, onPatch, applyPatch } from "mobx-state-tree"
import { observer } from "mobx-react"
import { inspect, render } from "mobx-state-tree-playground"

const MstNode = types.model("MstNode", {
	value: types.number,
	next: types.maybe(types.late(() => MstNode)),
});

const store = MstNode.create({value: 1, next: null})
inspect(store)
```

**Comment by mattiamanzati** [comment]
Uhm, yeah, seems to be due to https://github.com/mobxjs/mobx-state-tree/blob/master/src/types/complex-types/object.ts#L113-L117 checks in constructor :/ @mweststrate Do you think it's better to move modelConstructor initialization in first initialize call (and may break extend()) or introduce a flag to determine if type is an identifier?

**Comment by mattiamanzati** [comment]
New idea: drop completely IdentifierProperty, perform the work on the Identifier type initialize. Will give it a shot later.
