### ISSUE TITLE
Snapshot issue for Literal type on react-native

### ISSUE THREAD

**Issue by ds300** [mobxjs/mobx-state-tree#189]
Here's an odd one. I have only managed to observe it when running in react-native on Android, but not in debug mode.

The error occurs here: https://github.com/mobxjs/mobx-state-tree/blob/1bbd9742f4f6ca833ad08c5bcc6aab5b17d4699d/src/core/node.ts#L191

The error message is "Object.freeze can only be called on Objects". Through `console.error`-driven debugging I discovered that, at the point where this happens, `this.type` is a `Literal` that looks like this: 
![image](https://user-images.githubusercontent.com/1242537/27096502-32c1779c-5069-11e7-92f6-25a61e90a837.png)

Steps to reproduce (Nexus 6P, Android 7.1.1, Both on simulator and device):

1. Create a new react-native app

       react-native init MyApp
       cd MyApp
       yarn add mobx mobx-state-tree
    
2. Change the index.android.js to this:

    ```
    import React from "react"

    import { AppRegistry } from "react-native"
    import { types } from "mobx-state-tree"

    types.model("Name", { foo: types.string}) // this line throws deep in the call stack

    class App extends React.Component<{}, {}> {
      render() {
        return null
      }
    }
    AppRegistry.registerComponent("App", () => App)

    export default App
    ```

3. run the app on android

       react-native run-android

Call stack looks like this:
![image](https://user-images.githubusercontent.com/1242537/27096376-c285bf2e-5068-11e7-841c-f9cdaa04f042.png)
![image](https://user-images.githubusercontent.com/1242537/27096392-cd73afd6-5068-11e7-9d24-1ce1eecefce8.png)
![image](https://user-images.githubusercontent.com/1242537/27096403-d654ed18-5068-11e7-8161-a0c242cdcee7.png)

Any idea why this might behave differently in different environments?

**Comment by mattiamanzati** [comment]
Hello! Thanks for reporting!
Are you able to clone the git repository, build and install from it? The latest commit should fix, have'nt got a RN setup right now :)

**Comment by ds300** [comment]
Hi, thanks for the quick response!

I tried building from master and got a couple of type errors related to your changes:

```
➜  mobx-state-tree git:(master) yarn run build
yarn run v0.24.5
$ npm run quick-build && npm run webpack 

> mobx-state-tree@0.7.1 quick-build /Users/dshe/code/mobx-state-tree
> tsc

src/utils.ts(78,34): error TS7017: Element implicitly has an 'any' type because type '{}' has no index signature.
src/utils.ts(79,28): error TS7017: Element implicitly has an 'any' type because type '{}' has no index signature.
```

After I fixed those this issue was gone. Thanks again!

**Comment by mattiamanzati** [comment]
Yay, 0.7.3 is out and should fix it :) Thanks for your error reporting! :)
