### ISSUE TITLE
Intellisense not working with .named() models

### ISSUE THREAD

**Issue by gregbrinker** [mobxjs/mobx-state-tree#1901]
**_Question_**

* [✔️ ] I've checked documentation and searched for existing issues
* [✔️ ] I tried [GitHub Discussions](https://github.com/mobxjs/mobx-state-tree/discussions)

Hello! Relatively new to MST (<6 months). I have a type, let's call it TypeA. I also have a TypeB, which is a clone of TypeA with a few extra actions:
```
const TypeAModel = types.model("TypeA").props({
   prop1: types.string
})
.actions(
   action1()
)

const TypeBModel = TypeAModel.named("TypeB")
.actions(
   action2()
)
```

Let's say I have a functional component that has a prop called `bModel: TypeBModel`. In the component, hovering over `bModel` says it's of type `any`. When I type `bModel.`, there aren't any autocomplete suggestions - `action1()`, `action2()`, or any of the props. The code runs fine, `bModel.action1()` calls the correct action as expected. But the autocomplete not working is just really annoying 😢 This doesn't happen to `TypeAModel` though, Intellisense can pick up on those just fine.

If anyone knows how to solve this, it would be much appreciated!

**Comment by coolsoftwaretyler** [comment]
Hey @gregbrinker - I'm really sorry it took so long for anyone to get back to you here. I'm curious if you're still having this problem. If so, can you provide more information about your Intellisense setup? My VS Code seems to autofill things correctly with the code snippet you wrote:

<img width="522" alt="Screenshot 2023-06-25 at 10 34 34 PM" src="https://github.com/mobxjs/mobx-state-tree/assets/29899554/c7c88295-c464-410b-ae9b-732c9f9f44ee">

I'm going to tag this as needs more info for now, and again, sorry it took so long!

**Comment by coolsoftwaretyler** [comment]
Closin' out. Sorry we didn't help ya when it was more relevant!
