### ISSUE TITLE
Introduce `compose`, remove `extend`

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#192]
Replaces `extend`, which is to be removed.

Proposed api:
`const NewModel = types.compose(BaseModel, newProps, newActions)`

1. Note that this does not establish an inheritance relationship; it just takes the defiinition on BaseModels and constructs a new model form it. 
2. reconfiguring props is not allowed
3. reconfiguring actions is allowed. 
4. "Supercalls" can be made by using `BaseModel.actions.actionName.call(this, args)`
5. `baseModel.isAssignableFrom(NewModel)` will yield false. If you need a place where both types are allowed, use `union(NewModel, BaseModel)`

**Comment by RainerAtSpirit** [comment]
How would `computeds` be handled in with this proposed API?

**Comment by mweststrate** [comment]
Good question. I think `newProps` should allopw overriding computeds from `BaseModel`

**Comment by mweststrate** [comment]
reusing computed from "super" if overriding will probably be tricky though, that requires a helper function

**Comment by mweststrate** [comment]
Released as 0.8.0
