### ISSUE TITLE
Introduce `types.lazy`

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#193]
I think it should be possible to define a lazy loading type, and use that to fetch data on demand (especially since we could even generate a schema from the type meta data), integrate with graphQL / firebase etc:

```
const Store = types.model({
  todos: types.lazy(
     types.array(Todo), // The type that will be produced
     (parent) => new Promise(....) // something that will start fetching the data
})
```

the type of `types.lazy(X, f)`  is `types.union(PromiseState, X)` where `PromiseState` is built-in and defined as `types.union(types.model({ state: types.literal("pending") }), types.model({ state: state.literal("error"), error: types.frozen })))`

Note that this is quite similar to mobxUtils.fromPromise

**Comment by mattiamanzati** [comment]
Will the promise be called and instantiated immediately? This should be possible to implement in userland :)

**Comment by krosk93** [comment]
I just began using mobx-state-tree so I don't understand it very well yet, so correct me if it's wrong but I'm using this as a kind of "replacement" to fromPromise from mobx
```
import { types as t, flow } from 'mobx-state-tree'

export default (promise, initial = undefined) => {
  const model = t.model({
    value: t.frozen,
    state: t.optional(t.enumeration('Status', ['pending', 'fulfilled', 'rejected']), 'pending'),
  })
  .actions(self => ({
    afterCreate: flow(function* afterCreate() {
      try {
        self.value = yield promise
        self.state = 'fulfilled'
      } catch (e) {
        self.value = e
        self.state = 'rejected'
      }
    }),
  }))
  return t.optional(model, {
    value: initial,
  })
}
```

**Comment by schabluk** [comment]
@krosk93 just wondering, any particular reason why you are passing promise as an module argument?

Why not having 'promise' as a model property?
```
  const model = t.model({
    promise: t.frozen,
    value: t.frozen,
    state: t.optional(t.enumeration('Status', ['pending', 'fulfilled', 'rejected']), 'pending'),
  })
```

**Comment by mattiamanzati** [comment]
t.frozen accept only immutable AND serializable values, promise is'nt serializable :)

**Comment by mweststrate** [comment]
Gonna add that more clearly to the readme. Many run into that :)

Op di 7 nov. 2017 om 13:14 schreef Mattia Manzati <notifications@github.com

**Comment by schabluk** [comment]
@krosk93 how would you use this module, as a part of a model? Wouldn't you have to initialize the promise before the store is created? Maybe something like this?

```
const ApplicationStore = types
  .model('ApplicationStore', {
    applications: types.array(Application),
    request: Request(/* no arguments */)
  })
   .views(self => ({
     get isLoading () {
       return self.request.state === 'pending'
     }
   }))
  .actions(self => ({
    load () {
      self.request = new Request(fetch(/* url */)).create()
    }
  }))
```

**Comment by sheerun** [comment]
I think we need also something a little different, not necessarily promise based. Here's what I mean.

Taking the example from mobx-state-tree [presentation](https://immer-mutable-state.surge.sh/#30):

--- 

```es6
class Person {
    firstName = "Michel"
    lastName = "Weststrate"
    get fullName() {
        console.log("calculating!")
        return [this.firstName, this.lastName]
    }
}
```

```es6
person.firstName = "John"
console.log(person.fullName)
// calculating!
console.log(person.fullName)
// calculating!
```

Pros:
- fullName is calculated only when we need it

Cons:
- fullName is recalculated each time, even if its dependencies didn't change

--- 

```es6
class Person {
    @observable firstName = "Michel"
    @observable lastName = "Weststrate"
    @computed get fullName() {
        console.log("calculating!")
        return [this.firstName, this.lastName]
    }
}
```

```es6
person.firstName = "John"
// calculating!
console.log(person.fullName)
console.log(person.fullName)
```

Pros:
- fullName is calculated just once each time any of its dependencies change

Cons:
- fullName is calculated even if we don't need it after one of its dependencies changed

---

What we need it solution with following property:

- fullName is re-calculated only once if one of its dependencies changed
- fullName is re-calculated we try to access it, not before

```es6
class Person {
    @observable firstName = "Michel"
    @observable lastName = "Weststrate"
    @lazy get fullName() {
        console.log("calculating!")
        return [this.firstName, this.lastName]
    }
}
```

```es6
person.firstName = "John"
console.log(person.fullName)
// calculating!
console.log(person.fullName)
```

**Comment by sheerun** [comment]
With the definition of `@lazy`, lazy-loading of promises is easy to achieve:

```es6
class Person {
    @observable firstName = "Michel"
    @observable lastName = "Weststrate"
    @observable currency = "USD"
    @lazy async currencyDetails() {
        const result = await fetch("http://example.com/get-currency/" + this.currency)
        return result.json()
    }
    @lazy async currencyValue() {
        return (await this.currencyDetails).currentValue
    }
}
```

```es6
// The @lazy created a getter that returns a promise
console.log(await person.currencyValue()) // promise is created and executed
console.log(await person.currencyValue()) // re-uses cached promise
person.currency = "EUR"
console.log(await person.currencyValue()) // cancels old promise, creates new promise because dependency changes
```

There's no need for "state"  substate as we can read it directly with `await model.FIELD` that either returns something or throws. The `model.FIELD` is synchronous and returns promise.

**Comment by ericclemmons** [comment]
I started trying to implement @mweststrate's suggestion above, but I don't know how to go about _kicking off the Promise_.  Does this need to be a proper `class` (like the other types), or is @krosk93's suggestion about right?

(The problem I'm having with a custom `types.model` with `afterCreate` is avoiding a sub-property of `.value` after the promise completes)

**Comment by lidermanrony** [comment]
any planned work on this feature?

**Comment by mbest** [comment]
@mweststrate I've been trying to implement something like this. I see you have `error: types.frozen` in the model. If I save the caught error there, how can I read it back out?

**Comment by airhorns** [comment]
Anyone have a snippet we could use to implement this in userland?

**Comment by coolsoftwaretyler** [comment]
Hey folks, this MobX-State-Tree issue is pretty stale.

We're open to adding more types, but lean towards keeping the API from growing larger than it already is.

If anyone has code snippets to share or more free form thoughts on this, I encourage you to hop in the discussions: https://github.com/mobxjs/mobx-state-tree/discussions

If you'd like to see this in MST, I'd also be happy to review a PR. I usually prioritize code review over my own endeavors, so please don't be shy!

That said, I'm gonna close this out. Thanks for your time!
