### ISSUE TITLE
lifecycle hooks cannot always access their children

### ISSUE THREAD

**Issue by scytacki** [mobxjs/mobx-state-tree#1951]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
```javascript
test.only("lifecycle hooks can access their children", () => {
    const events: string[] = []
    function listener(e: string) { events.push(e) }

    const Child = types
        .model("Todo", {
            title: ""
        })
        .actions(self => ({
            afterCreate() {
                listener("new child: " + self.title)
            }
        }))

    const Parent = types
        .model("Parent", {
            child: Child
        })
        .actions(self => ({
            afterCreate() {
                // **This the key line**: it is trying to access the child
                listener("new parent, child.title: " + self.child?.title)
            }
        }))

    const Store = types.model("Store", {
        parent: types.maybe(Parent)
    })

    const store = Store.create({
        parent: {
            child: { title: "Junior" }
        }
    });
    // As expected no hooks are called.
    // The `parent` is not accessed it is just loaded.
    events.push("-")

    // Simple access does a sensible thing
    const parent = store.parent;
    expect(events).toEqual([
        "-",
        "new child: Junior",
        "new parent, child.title: Junior",
    ])

    // Clear the events and make a new store
    events.length = 0;
    const store2 = Store.create({
        parent: {
            child: { title: "Junior" }
        }
    });
    events.push("-")

    // Using resolvePath fails to do the right thing. 
    const child = resolvePath(store2, "/parent/child");
    expect(events).toEqual([
        "-",
        "new parent, child.title: Junior", // <-- fails with "new parent, child.title: undefined"
        "new child: Junior"
    ])
})
```

**Describe the expected behavior**
Parents should be able to access their children in afterCreate. This should be the case regardless of how the model is created or accessed.

**Describe the observed behavior**
In some cases, for example `resolvePath` and `applyPatch` the children are undefined in afterCreate. This happens when the parent and child are created using a snapshot, and then the child is accessed or modified with a path before the parent is accessed

I believe this is a simplified version of what was reported in #1680

The issue has to do with how `ObjectNode#createObservableInstance` finishes creating the parent first and calls the parent's lifecycle methods before the child has been fully created. I think the right solution is to wait to call the lifecycle hooks until both the parent and child are fully created.

**Comment by antondomratchev** [comment]
Please make a note of this part of the documentation:
https://mobx-state-tree.js.org/overview/hooks

The nodes are first created and then attached starting with children first. You should *NOT* have an expectation to access children in `afterCreate` hook but rather in `afterAttach`

**Comment by scytacki** [comment]
@antondomratchev That text on that page for `afterCreate` says:
> Children will fire this event before parents. You can't make assumptions about the parent safely, use afterAttach if you need to.

That is referring to accessing parents not children. Reading that line, it seems reasonable to me that a node should be able to access its children in `afterCreate`. Looking at it another way, if a node is the root of a tree (does not have a parent), `afterCreate` is the only hook that will be called, so in order to support basic initialization code, it seem necessary to me that `afterCreate` can access the current node's children.

Rereading my comment above:
> I think the right solution is to wait to call the lifecycle hooks until both the parent and child are fully created.

I can see how it could be mis-interpreted. In that statement I am referring to the current node (the one with the hook) as the "parent". I'm not suggesting the parent of the current node be fully created before calling the `afterCreate` hook. What I am suggesting (and have a PR implementing) is that the children of the current node be fully created before calling the `afterCreate` hook. In the current codebase the children are being fully created at this point anyhow it is just that the `afterCreate` hook is called beforehand.

**Comment by coolsoftwaretyler** [comment]
Tossing a label on here because there's an open PR in https://github.com/mobxjs/mobx-state-tree/pull/1952.
