### ISSUE TITLE
How to store Buffer type in state

### ISSUE THREAD

**Issue by msaraac** [mobxjs/mobx-state-tree#1964]
**_Question_**
I would like to store Buffer in the state but I could not find any solution. I tried frozen with default sized buffer. But when I try to change this frozen property I'm getting errors.  Is there a way to store buffers ? 

```
.props({
    type: types.optional(types.number, 0),
    fc: types.optional(types.number, 0),
    seq: types.optional(types.number, 0),
    len: types.optional(types.number, 0),
    data: types.optional(types.frozen<Buffer>(), Buffer.alloc(5)),
  })
```

* [x] I've checked documentation and searched for existing issues
* [x] I tried [GitHub Discussions](https://github.com/mobxjs/mobx-state-tree/discussions)

**Comment by BATCOH** [comment]
Frozen type accepts values that **immutable** and JSON-**serializable**. Buffer afaik is mutable and not serializable.

You can create your own [custom type](https://mobx-state-tree.js.org/API/#custom) for Buffer if you need some advanced features (like snapshots/patches), or just use [volatile state](https://mobx-state-tree.js.org/concepts/volatiles#modelvolatile).
