### ISSUE TITLE
BigInt serialization error using connectReduxDevtools

### ISSUE THREAD

**Issue by AaronPorts** [mobxjs/mobx-state-tree#1977]
Getting the next error in console: `"Do not know how to serialize a BigInt"`. The reason in my case is that `logContext.callArgs` array from `connectReduxDevtools` includes `HTMLElement` and it can't be serialized. Guess we need to add some `instanceof HTMLElement` check.

**Comment by coolsoftwaretyler** [comment]
Hey @AaronPorts - would you mind writing up a minimal reproduction for this that demonstrates the issue?

**Comment by coolsoftwaretyler** [comment]
Hey @AaronPorts - just a reminder here. I will probably close this issue out if we don't see a reproduction from you in the next two weeks or so. I know it's been a while, so apologies for the wait time. Hope you were able to maybe figure it out?

**Comment by coolsoftwaretyler** [comment]
Closin' out. Sorry we didn't help ya when it was more relevant!
