### ISSUE TITLE
More/Better documentation on Environments

### ISSUE THREAD

**Issue by estill01** [mobxjs/mobx-state-tree#198]
'Environments' are referenced in the documentation for `getEnv()`, and used as a parameter in `types.model.create()` (and perhaps elsewhere), but are not themselves documented.

The documentation for `getEnv()` references an 'environment' section in the documentation that does not exist. The only documentation on 'environments' is that they are a 'context-like mechanism'. As a new user of Mobx/MST, this lack of documentation was confusing / complicated my adoption/use MST.

Further, the use of environments by `types.model.create()` is also not documented outside of the source code (/as far as I can tell). Since `types.model.create()` is such a centrally important function for using MST it would be helpful to more directly document its parameterization.

**Comment by mweststrate** [comment]
Documented. Thanks for reporting!

https://github.com/mobxjs/mobx-state-tree#dependency-injection
