### ISSUE TITLE
How to describe model for Array<Record<string, string>> TS type?

### ISSUE THREAD

**Issue by KyryloSWAN** [mobxjs/mobx-state-tree#2004]
**_How to describe model for Array<Record<string, string>> TS type?_**

* [x] I've checked documentation and searched for existing issues
* [x] I tried [GitHub Discussions](https://github.com/mobxjs/mobx-state-tree/discussions)

I have the following data for which I need to create a model:
```
{
  "some": [
    {"a": "b"},
    {"c": "d"},
    {"e": "f"}
  ]
}
```
The key of object in array item can be any string.
I can use `Array<Record<string, string>>`  to describe my data as TypeScript type.
But I can't figure out how I can describe the mst model for my data.

**Comment by coolsoftwaretyler** [comment]
Hey @KyryloSWAN - since we discussed this over in https://github.com/mobxjs/mobx-state-tree/discussions/2003, what do you think about closing out this issue? Seems to have been resolved.

**Comment by KyryloSWAN** [comment]
@coolsoftwaretyler sure!
Thank you for your help!

**Comment by coolsoftwaretyler** [comment]
Closing this out - I've got full maintainer permissions now so I can do that for ya!
