### ISSUE TITLE
Spin off a new project for `mst-middlewares`

### ISSUE THREAD

**Issue by coolsoftwaretyler** [mobxjs/mobx-state-tree#2027]
The `mst-middlewares` package in this repository has been the source of many issues and confusion. In the June 2023 maintainers' meeting, we hypothesized that part of it is because the middlewares as provided are framed as a "nice-to-have" inside the MobX-State-Tree monorepo.

[As we work to move away from a monorepo](https://github.com/mobxjs/mobx-state-tree/milestone/4), the goal is to find a clearer path forward for `mst-middlewares`. By splitting it to its own project, we can more clearly define the scope of the middlewares, the level of maintenance of those projects, and delineate issues about MobX-State-Tree from issues about those middlewares.

Since users reasonably expect the MST middlewares package to live here, I want to leave this issue open for some discussion and thorough consideration before we decide where those projects ought to end up, and how we'll remove them from this repository in a responsible way.

Open to feedback, thoughts, volunteers, etc!

**Comment by chakrihacker** [comment]
What's the plan here?? 
Can I just create a new repo and move the middleware parts? Then define the scope, and import middleware issues there??

**Comment by coolsoftwaretyler** [comment]
Hey @chakrihacker - I don't think we've got a clear plan yet. @jamonholmgren and I are going to have a meeting this coming Friday, August 4th, 2023 to discuss.

But yes, I think the overall plan is to create a new repo (potentially within the MobX organization - but I don't know), and then make sure it's wired up to publish the separate npm package. Once we verify that's all working as expected, we can remove the nested codebase from MST itself, and probably transfer the issues over there.

For now, I think we should hold off until Jamon and I get a chance to talk it out and get aligned, but I would guess it's going to look something like that in the end state.

**Comment by coolsoftwaretyler** [comment]
I have just duplicated `mst-middlewares` from [this commit](https://github.com/mobxjs/mobx-state-tree/tree/9f30ab82df47d49200f512aee4839892473e407a/packages/mst-middlewares) into the GitHub repository at https://github.com/coolsoftwaretyler/mst-middlewares. 

Up next I need to:

1. Get access to `mst-middlewares` npm package
2. Make sure I can deploy a version to that package
3. Remove `mst-middlewares` package from this repo

Then we can remove a lot of the lerna config from this repo and close out the milestone.

**Comment by chakrihacker** [comment]
Hey, we could have kept this under mobxjs org only right, any issues over there??

**Comment by coolsoftwaretyler** [comment]
@chakrihacker - when Jamon and I planned out the migration, we considered it and he suggested we keep these things out of that organization. I'm not even sure if we have access.

I'm happy to transfer them over there, but we'd have to get access to do so.

In the meantime, I can get you access to the new repos. Jamon and I are both maintainers there.

**Comment by chakrihacker** [comment]
Ok
