### ISSUE TITLE
Fix rollup + cyclic dependencies

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#205]
Rollup rolls up the files in the wrong order, making a lot of `class X extends Y`  clauses fail. 

Simply verifyable by running

https://github.com/mobxjs/mobx-state-tree/blob/b4df3d6893ffb38faed604f244b3518150e61ac5/package.json#L15

**Comment by mweststrate** [comment]
@rossipedia any ideas on this? How dit you fix circular deps in mobx?

**Comment by mweststrate** [comment]
Background

https://stackoverflow.com/questions/38841469/how-to-fix-this-es6-module-circular-dependency
https://esdiscuss.org/topic/how-to-solve-this-basic-es6-module-circular-dependency-problem or https://github.com/rollup/rollup/issues/995

**Comment by mweststrate** [comment]
The closes I got to use initializer funcs and have that strongly typed is:

```
export let X = initX()

function initX() {
    export class stuff {
        boe() {}
    }
    X = stuff as any
    return stuff
}

new X().boe()
```
But TS still won't allow it

**Comment by rossipedia** [comment]
ugh... I had to move imports around in the main file to get things to work correctly in `mobx`
I can juggle some things in `mobx-state-tree` to see if I can get it working, but I wouldn't blame you if you wanted to bail on `rollup` altogether :(

**Comment by mattiamanzati** [comment]
@rossipedia I think we may have solved it :)

**Comment by mattiamanzati** [comment]
Ok, the issues was with primitives.ts and type-checker.ts referencing circularry (is that even a word?) isPrimitiveType was the issue, introduced a new file named type-flags with all isXXXType checks.

**Comment by rossipedia** [comment]
`circularly` I believe 👍

**Comment by mattiamanzati** [comment]
Thanks @rossipedia :)
