### ISSUE TITLE
Updating store failing with conversion error

### ISSUE THREAD

**Issue by SgSridhar** [mobxjs/mobx-state-tree#206]
```
const TestModel = types.model('TestModel', {
value: t.optional(t.array(t.string), , () => ([]))
})

const TestModelList = types.model('TestModelList', {
values: t.optional(t.array(TestModel), () => ([])),
}, {
setTestModel(index, val) {
this.values[index] = val
}
})
```
Consider,
@observable val = {value: ['VAL1', 'VAL2']}

When I try to set the value by calling setTestModel(val),
`Fails with conversion error`

If I do,
this.values[0] = val.toJS()
It works as expected.

**Comment by mattiamanzati** [comment]
Hi! Thanks for reporting! I can't reproduce the error, can you please setup a small reproduction in the playground? :)

https://mattiamanzati.github.io/mobx-state-tree-playground/

**Comment by SgSridhar** [comment]
Will do it and post the link! Thanks for immediate response. :)

**Comment by alexvcasillas** [comment]
I just tried your code in MST Playground and with a few modifications (some comas added and replaced the type import) it just works  🤔 

```
import {
    types
} from "mobx-state-tree"


const TestModel = types.model('TestModel', {
    value: types.optional(types.array(types.string), () => ([]))
})

const TestModelList = types.model('TestModelList', {
    values: types.optional(types.array(TestModel), () => ([])),
}, {
    setTestModel(index, val) {
        this.values[index] = val
    }
})

const TMStore = TestModelList.create();

TMStore.setTestModel(
    0,
    {
        'Alex':'Casillas'
    }
);

TMStore.setTestModel(
    0,
    {
        'Michel':'Weststrate'
    }
);
```

I'll wait for your Playground MST Demo : )

**Comment by SgSridhar** [comment]
Sorry for the delayed reply, stuck with work :) . I was not able to replicate the same thing in the playground. Will try to replicate over the weekend and update.

Thanks for the support :)

**Comment by SgSridhar** [comment]
Was not able to replicate it. Thanks for the response.
