### ISSUE TITLE
types.compose is useful, but cant overwrite

### ISSUE THREAD

**Issue by homura** [mobxjs/mobx-state-tree#209]
I was trying to overwrite something like this

```javascript
const Parent = types.model({
  name: '',
  alias: '',
  get displayName() { return this.alias || this.name; }
})

const child = types.compose(Parent, {
  type: '',
  get displayName() { return this.alias || this.name + type; }
})
```

```
Cannot redefine property: displayName
```

I has changed mobx-state-tree(0.8.2) source to 

```javascript
descriptor.configurable = true; // line of 100
```
and it works

How can i resolve this error? Or configurable will be true in next version?

Sorry for my poor English.

**Comment by mweststrate** [comment]
This should be possible indeed. Feel free to open a PR. Can you include a
test?

Op ma 26 jun. 2017 om 13:32 schreef homura <notifications@github.com>:

**Comment by homura** [comment]
#210
