### ISSUE TITLE
Error compiling Cannot find name 'ThisType'.

### ISSUE THREAD

**Issue by webmutation** [mobxjs/mobx-state-tree#212]
While compiling with Angular CLI it returns an issue in the typing

angular/node_modules/mobx-state-tree/dist/types/complex-types/object.d.ts (56,68): Cannot find name 'ThisType'.

**Comment by mweststrate** [comment]
Which typescript version? From top of my head 2.3 is minimum supported
version

Op ma 26 jun. 2017 om 15:44 schreef Dan Mendes <notifications@github.com>:

**Comment by webmutation** [comment]
ah it was on 2.2, will retest with 2,3 thanks for the quick reply
