### ISSUE TITLE
Only getting updates in componentWillReceiveProps when directly using action.

### ISSUE THREAD

**Issue by mhaagens** [mobxjs/mobx-state-tree#215]
Eg. if an action runs another action, componentWillReceiveProps will not receive an update for anything but the first initiator action. Is this by design?
I've resorted to listening to patches in componentWillMount to get updates as of now.

**Comment by mattiamanzati** [comment]
Yes, this is intended, the first (or outermost) action will be triggered to ensure correct replayability :)

**Comment by mhaagens** [comment]
So, let's say I have a Posts component, which renders a list of posts and a subroute for a single post. I click on a link to a post, which sets a reference to that post in the store. In my subroute I need to know when the reference has been set, but I will never receive that update in a lifecycle method. Should I listen to patches then?

**Comment by mattiamanzati** [comment]
Uhm, If I understand correctly you could set up a mobx reaction on afterCreate and dispose it in beforeDestroy that listens for the id of your reference field. Do you need to know if that update happens to perform state logic or ui-rendering logic? :)

**Comment by mhaagens** [comment]
The problem is that when I do a hard refresh, the Posts component loads all the posts and then in the subcomponent I need to know when the posts have actually been loaded.
Action-wise it goes like this;

**Posts.js**
Actions: getPosts (->setLoading(true)) -> parsePosts -> setPosts (->setLoading(false))

**Post.js**
```
componentWillReceiveProps(nextProps) {
   if (nextProps.PostStore.posts.length) {
      this.props.PostStore.setPost(this.props.match.params.id)
   }
}
```

So now I need to know when isLoading is false in the subcomponent, but that update isn't sent to componentWillReceiveProps since it's initiated by another action (getPosts()).

**Comment by mweststrate** [comment]
Just always call getPosts in your receive props, and make it do nothing if
loading is already progress. The loading state should only be relevant for
the rendering result, which will automatically responded to if your
component is `@observer`

Op wo 28 jun. 2017 om 12:05 schreef Martin <notifications@github.com>:

**Comment by mattiamanzati** [comment]
You need to setup a reaction that listens to the isLoading, to subscribe to that property changes. But I think that there is an easier way. Why don't you put a computed property over the post that resolves to null or undefined when isLoading is true and returns the reference value when isLoading is false? 

(setup a reaction example)
https://mattiamanzati.github.io/mobx-state-tree-playground/#src=import%20React%20from%20%22react%22%0Aimport%20%7B%20types%20%7D%20from%20%22mobx-state-tree%22%0Aimport%20%7B%20observer%20%7D%20from%20%22mobx-react%22%0Aimport%20%7B%20inspect%2C%20render%20%7D%20from%20%22mobx-state-tree-playground%22%0Aimport%20%7B%20reaction%20%7D%20from%20%22mobx%22%0A%0Aconst%20Post%20%3D%20types.model(%7B%0A%20%20%20%20id%3A%20types.identifier(types.string)%2C%0A%20%20%20%20name%3A%20types.string%2C%0A%20%20%20%20body%3A%20types.string%0A%7D)%0A%0Aconst%20AppModel%20%3D%20types.model(%7B%0A%20%20%20%20posts%3A%20types.optional(types.map(Post)%2C%20%7B%7D)%2C%0A%20%20%20%20current%3A%20types.maybe(types.reference(Post))%0A%7D%2C%20%7B%0A%20%20%20%20reaction%3A%20null%0A%7D%2C%20%7B%0A%20%20%20%20setCurrent(post)%20%7B%0A%09%09this.current%20%3D%20post%0A%09%7D%2C%0A%20%20%20%20addPost(id%2C%20name%2C%20body)%7B%0A%20%20%20%20%20%20%20%20this.posts.put(Post.create(%7Bid%2C%20name%2C%20body%7D))%0A%20%20%20%20%7D%2C%0A%20%20%20%20afterCreate()%20%7B%0A%20%20%20%20%20%20%20%20this.reaction%20%3D%20reaction(()%20%3D%3E%20this.current%2C%20()%20%3D%3E%20alert(%22Changed%20current%20to%20%22%20%2B%20(this.current%20%3F%20this.current.id%20%3A%20%22null%22)))%0A%20%20%20%20%7D%2C%0A%20%20%20%20beforeDestroy()%20%7B%0A%20%20%20%20%20%20%20%20this.reaction()%0A%20%20%20%20%7D%0A%7D)%0A%0Aconst%20store%20%3D%20AppModel.create()%0Ainspect(store)%0Astore.addPost(%221%22%2C%20%22Hello%22%2C%20%22heodkejdidwjdishdl%22)%0Astore.addPost(%222%22%2C%20%22World%22%2C%20%22hdsdahdsuhadudadhsouha%22)%0A%0Aconst%20PostListView%20%3D%20observer(%0A%20%20%20%20props%20%3D%3E%20%3Cul%3E%0A%20%20%20%20%20%20%20%20%7Bprops.store.posts.values().map(post%20%3D%3E%20%3Cli%3E%3Ca%20href%3D%22%23%22%20onClick%3D%7Be%20%3D%3E%20props.store.setCurrent(post)%7D%3E%7Bpost.name%7D%3C%2Fa%3E%3C%2Fli%3E)%7D%0A%20%20%20%20%3C%2Ful%3E%0A)%0Aconst%20PostSingleView%20%3D%20observer(%0A%20%20%20%20props%20%3D%3E%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20%3Ca%20href%3D%22%23%22%20onClick%3D%7Be%20%3D%3E%20props.store.setCurrent(null)%7D%3EGo%20Back%3C%2Fa%3E%0A%20%20%20%20%20%20%20%20%3Ch2%3E%7Bprops.store.current.name%7D%3C%2Fh2%3E%0A%20%20%20%20%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%7Bprops.store.current.body%7D%0A%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A)%0Aconst%20App%20%3D%20observer(%0A%20%20%20%20props%20%3D%3E%20props.store.current%20!%3D%3D%20null%20%3F%20%3CPostSingleView%20%7B...props%7D%20%2F%3E%20%3A%20%3CPostListView%20%7B...props%7D%20%2F%3E%0A)%0A%0Arender(%3CApp%20store%3D%7Bstore%7D%20%2F%3E)%0A

**Comment by mhaagens** [comment]
I'm sorry, trying to understand, but I don't think I'm getting it.
All I want is to be able to get the value of "loaded" inside a React component.
I need that value so that I know that the array of posts is loaded before I try to pass in the id value (which I'm getting from React Router). The only way to do this is by setting up a reaction inside the store? How will that reaction know the id? Really sorry for pestering you guys about this, but I love MST, I just feel like I'm not understanding this part correctly.

**Comment by mhaagens** [comment]
Ended up with this in my top level component;

```
	componentDidMount() {
		let pattern = new UrlPattern('/office/:id');
		let match = pattern.match(this.props.location.pathname);
		onSnapshot(this.props.RootStore.OfficeStore, snapshot => {
			if (
				snapshot.isLoading === false &&
				!snapshot.selectedOffice
				&& match
			) {
				this.props.RootStore.OfficeStore.selectOffice(match.id);
			}
		})
		this.props.RootStore.OfficeStore.getOffices();
	}
```

**Comment by mattiamanzati** [comment]
"I need that value so that I know that the array of posts is loaded before I try to pass in the id value"

You could avoid that, you can store the match.id in the store e.g. "currentId" (even if posts has'nt loaded yet) and put on your store a computed prop named "currentPost".

Unfortunately I can't help much because I don't have enough information of the background of your app, if you can set up a small repro of the current behaviour and what you want to achiveve, I'll have it a look :)

https://mattiamanzati.github.io/mobx-state-tree-playground/
