### ISSUE TITLE
Access `this` inside `pre/postProcessSnapshot`

### ISSUE THREAD

**Issue by SimonDegraeve** [mobxjs/mobx-state-tree#218]
My use case:

```js
class MyUser {
  // ...
  authenticate(password) {
    // ...
  }
}

const AuthStore = types.model(
  {
    user: types.optional(types.model({
      username: types.string,
      status: types.string
    }), {
      username: '', 
      status: 'LOGGED_OUT' 
    })
  },
  {
    myUser: null
  },
  {
    onPreProcessSnapshot (snapshot) {
      const self = this // currently set to null
      self.myUser = new MyUser(snapshot.username) 
      return snapshot
    },

    authenticate(password) {
      const self = this
      self.myUser.authenticate(password).then(() => {
        self.user.username = 'Me'
        self.user.status = 'LOGGED_IN'
      })
    }
  }
)
```

**Comment by mattiamanzati** [comment]
Uhm, onPreprocess we cant guarantee that "this" exists because the preprocessing is done before passing the snapshot. On postprocess could be available though.
Why dont you setup a onPatch listener or observe this.user on afterCreate and dispose it in befreDestroy instead?

**Comment by SimonDegraeve** [comment]
I don't do it on `afterCreate` because I want to keep the instance of User object sync with the observed `username`.
So I guess I should use `onPatch` and filter by the `username` path, right? (I am new to mobx and mobx-state-tree)

**Comment by mattiamanzati** [comment]
Yeah, you should setup the onPatch listener in the afterCreate and dispose that listener on beforeDestroy :)
