### ISSUE TITLE
is<TypeIdentifier> functions mark argument as `never` when they returns `false`.

### ISSUE THREAD

**Issue by coolsoftwaretyler** [mobxjs/mobx-state-tree#2184]
**_Bug report_**

-   [x] I've checked documentation and searched for existing issues [and discussions](https://github.com/mobxjs/mobx-state-tree/discussions)
-   [x] I've made sure my project is based on the latest MST version
-   [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction.

**Sandbox link or minimal reproduction code**

https://codesandbox.io/p/sandbox/isoptional-type-bug-repro-9h8cqg?file=%2Fsrc%2Findex.ts%3A11%2C6-12%2C1

**Describe the expected behavior**

`x` shouldn't be type `never`.  Should be `ISimpleType<number>`

**Describe the observed behavior**

TypeScript thinks `x` is of type `never`:

![Screenshot 2024-06-07 at 8 11 16 AM](https://github.com/mobxjs/mobx-state-tree/assets/29899554/5d3ddc54-94f6-44dd-a691-fd51293657a3)

**Comment by coolsoftwaretyler** [comment]
Updated the title to reflect that (pun intended). Thank you!

**Comment by thegedge** [comment]
I can grab this one

**Comment by coolsoftwaretyler** [comment]
This'll be out as a patch release soon!
