### ISSUE TITLE
applySnapshot does not accept MobX array

### ISSUE THREAD

**Issue by ssured** [mobxjs/mobx-state-tree#221]
0.9 removed `applySnapshots` and merged its functionality with `applySnapshot`

Sadly when your patches are wrapped in a MobX array, then `asArray` (https://github.com/mobxjs/mobx-state-tree/blob/master/src/utils.ts#L21-L25) fails, as it checks with `Array.isArray()`

From the docs on the mobx website: `Bear in mind however that Array.isArray(observable([])) will yield false, so whenever you need to pass an observable array to an external library, it is a good idea to create a shallow copy before passing it to other libraries or built-in functions (which is good practice anyway) by using array.slice(). In other words, Array.isArray(observable([]).slice()) will yield true.`

Passing the patches as `patches.slice()` is nice, but a userland solution. I'd prefer to make `asArray` smarter and handle MobX array object as arrays too.

**Comment by mattiamanzati** [comment]
@alessioscalici do you feel giving a shoot to fix also this and applyPatches/actions? :)

**Comment by alessioscalici** [comment]
@mattiamanzati I will at my first ;)

**Comment by mattiamanzati** [comment]
Merged, will be out with next release! :)

**Comment by alessioscalici** [comment]
Great, thanks!
