### ISSUE TITLE
Incompatible with new React Navigation v7 Release "Error: [MobX] Dynamic observable objects cannot be frozen"

### ISSUE THREAD

**Issue by ChristopherGabba** [mobxjs/mobx-state-tree#2210]
**_Bug report_**

-   [X] I've checked documentation and searched for existing issues [and discussions](https://github.com/mobxjs/mobx-state-tree/discussions)
-   [X] I've made sure my project is based on the latest MST version

**Sandbox link or minimal reproduction code**

I submitted an issue with the Infinite Red Ignite Boilerplate, but follow these instructions in the issue.
https://github.com/infinitered/ignite/issues/2753 

**Describe the expected behavior**

The app should not crash when passing an MST observable value as a parameter as a navigation parameter.

**Describe the observed behavior**

The app crashes with the above error: `Error: [MobX] Dynamic observable objects cannot be frozen`

**Comment by coolsoftwaretyler** [comment]
Hey @ChristopherGabba - thanks for filing this! I dropped an answer over in https://github.com/infinitered/ignite/issues/2753#issuecomment-2305848330. I don't think this is actually a bug with MobX-State-Tree, but it's coming from MobX itself.

And even then, I don't think this is necessarily a *bug*, but rather, React Navigation has changed its own API in such a way that broke compatibility with using observable objects from MobX, which React Navigation wants to discourage anyway.

I'm going to close this for now, but if you find that this answer and my recommendations in the Ignite issue are insufficient, I'd be happy to keep the conversation going and see what we can do for you!
