### ISSUE TITLE
Asynchronous actions generator yield stuck

### ISSUE THREAD

**Issue by rose4096** [mobxjs/mobx-state-tree#2213]
**_Bug report_**

-   [X] I've checked documentation and searched for existing issues [and discussions](https://github.com/mobxjs/mobx-state-tree/discussions)
-   [X] I've made sure my project is based on the latest MST version
-   [X] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction.

**Sandbox link or minimal reproduction code**

https://github.com/rose4096/mobx-state-tree-issue

**Describe the expected behavior**

The list of clients appears within the store when the promise is consumed by the generator

**Describe the observed behavior**

It stops on the yield and never continues even though the promise completes

**Additional notes**

When doing a next.js quick refresh (editing/saving the project) the clients render, but when doing a full refresh the clients do not render although the network request happens / the promise completes.

**Comment by rose4096** [comment]
This issue was actually user error. My upper level component wasn't set to observable, apologies.

**Comment by coolsoftwaretyler** [comment]
Glad ya figured it out. That one still gets me from time to time haha.
