### ISSUE TITLE
Add formatting rules

### ISSUE THREAD

**Issue by coolsoftwaretyler** [mobxjs/mobx-state-tree#2219]
Just a small issue to capture [this comment](https://github.com/mobxjs/mobx-state-tree/pull/2218#discussion_r1835440649): we need to add auto-formatting to this repository so that all PRs are consistent and to reduce some of the noisy formatting diffs we tend to get.

**Comment by coolsoftwaretyler** [comment]
Here's the plan:

1. Let's merge this PR (I am still reviewing but it looks good so far)
2. I will actually release the next major version, including this
3. Once we've released that version, let's do a big formatting PR. I have no strong opinions about formatting other than it should be automatic, checked before merge, and consistent. So we can just use whatever settings you have if you want the PR, or I can put the PR together and use whatever settings I have lol.
4. We can merge that PR right behind the major version, which should keep future patches/minors/majors easy to check berfore/after the big formatting PR. Basically making it easy to see what happened between v6 and v7, and then changes inside of 7 itself.

@thegedge - I can handle this to coordinate with the major version release, unless you want to get that sweet commit credit.

**Comment by thegedge** [comment]
> I have no strong opinions about formatting other than it should be automatic, checked before merge, and consistent.

💯 I have no strong opinions either (I have my preferences, of course!), but agreed that it just needs to be automatic to not waste anyone's time.

Prettier is of course the go-to tool these days, but I know not everyone is behind its prescriptiveness. I'm not as deep into the ecosystem, so perhaps you have some other suggestions, @coolsoftwaretyler?

If not, I say we use prettier and call it a day. My recommendations:

1. I'd be for switching tot he user of semi-colons. Prettier will add them for us, and we avoid the dreaded (or at least I think it's dreaded) `;(a as xyz).vaue = expression` syntax (used to avoid accidentally making a function call).
2.

**Comment by thegedge** [comment]
Actually, ignore my recommendations. I think we should respect the choices of the organization, which is in disagreement with (1) but not (2).

Let's just copy the prettier settings from https://github.com/mobxjs/mobx

**Comment by coolsoftwaretyler** [comment]
Great find, I agree!

**Comment by coolsoftwaretyler** [comment]
Alrighty, [v7.0.0 is out](https://github.com/mobxjs/mobx-state-tree/releases/tag/v7.0.0), so I'll tackle this sometime soon.
