### ISSUE TITLE
Frozen type includes `null` and `undefined`

### ISSUE THREAD

**Issue by caesarsol** [mobxjs/mobx-state-tree#224]
I think it's a design choice, but it should be made more explicit IMHO.

At least I'd put a warning to prevent the use of `types.maybe(types.frozen)` which obvoiusly causes the error:

```
value `undefined` is not assignable to type: `frozen | null` 
(Multiple types are applicable and no dispatch method is defined for the union),
```

**Comment by mattiamanzati** [comment]
Thanks for your suggestion! A warning has been added and will be out with next release! :)

**Comment by caesarsol** [comment]
That's a fair solution 👍  
Thanks!

**Comment by mattiamanzati** [comment]
@caesarsol You're welcome! Looking forward your validation error proposal ;)
