### ISSUE TITLE
Object.isFrozen can only be called on Objects (android/react-native)

### ISSUE THREAD

**Issue by skellock** [mobxjs/mobx-state-tree#225]
Quick sanity check here.  

I think there's an issue with calling `Object.isFrozen()` on a `number` on Android (`react-native@0.45.1` on Android 6 on an `LG-G4`).

`Object.isFrozen can only be called on Objects.`

![image](https://user-images.githubusercontent.com/68273/27753102-4ab62284-5db2-11e7-934e-fcdc6f6e704f.png)

The [line that's dying](https://github.com/mobxjs/mobx-state-tree/blob/48567d7ccdd3894da348f1a07e6a80f6b230bf1a/src/utils.ts#L94) is in the `deepFreeze()` function.  I'm feeding it an object with a property that is a number.

I noticed in [`freeze()`](https://github.com/mobxjs/mobx-state-tree/blob/48567d7ccdd3894da348f1a07e6a80f6b230bf1a/src/utils.ts#L86) you're checking for a [`isPrimitive`](https://github.com/mobxjs/mobx-state-tree/blob/48567d7ccdd3894da348f1a07e6a80f6b230bf1a/src/utils.ts#L73) and not freezing anyway, so I tried adding this extra guard:

```
           if (!isPrimitive(value[propKey]) && ... 
```

... and it fixes it.

I guess on older JS environments, you can't ask if you're frozen on a primitive... or something.

Is there a `types.frozen` alternative that was based on the honour system?  😆 

I can PR this if you think it would be useful.

**Comment by mattiamanzati** [comment]
Uhm, whats the honour system? :P
Feel free to PR the added guard, seems legit :)
Thanks for your time! :)

**Comment by skellock** [comment]
The honour system would be:  `types.freestyle`.  You put a serializable, immutable object in... and  promise to never mutate it.  If I do, then any cryptic error that may happen is on me, not `mst`.  😛 

You don't need to freeze anything because I told `mst` I was a trustworthy kind-a-guy.

**Comment by mattiamanzati** [comment]
Uhm, I'd name it types.iSolemnSwearIAmUpToNoGood :P
Not sure about it, the fun thing about mst iit ensures good types of the state :)
