### ISSUE TITLE
Complex action arguments should be (de)serialized

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#23]
If the argument of an action is a Model object, it should be serialized as just the relative path to that model element. E.g.: `{ $path: "../todos/7"}`

Note that only model elements belong to the same tree (same root) should be acceptable. Note that the arguments might be complex, so this process should be done by some traverse that clones all the plain data and replaces the models with references

**Comment by mattiamanzati** [comment]
Also we should separate the applying snapshot pass in two phases. First, applying the regular snapshot, second, resolving the references $path.

**Comment by mweststrate** [comment]
In that case we could maybe even do 3 phases (using some option arguments
to applySnapshot?) so that we can first check & determine the factory types
that should be applied. But I actually think for the existing ref system
this already works correctly when applying snapshots; because they are
computed values they will be postponed to the end of the mobx transaction

Op do 5 jan. 2017 om 09:42 schreef Mattia Manzati <notifications@github.com

**Comment by mattiamanzati** [comment]
Yeah, the 3-phase work could be neat and avoid unnecessary type-checks! I like it!

**Comment by mweststrate** [comment]
Hmm... question: what should be serialized?

* a path
* a snapshot
* a path if the source object is in the state tree, a snapshot if it isn't part of the state tree?

**Comment by mattiamanzati** [comment]
Uhm, I think the last one is the better? Btw the first one will be the more predictable one, unsure about that.

**Comment by mweststrate** [comment]
Released as part of 0.2.0. Relative path is used indeed
