### ISSUE TITLE
types.Date cannot be rehydrated

### ISSUE THREAD

**Issue by KatSick** [mobxjs/mobx-state-tree#233]
TL;DR https://codesandbox.io/s/Nw18kKn2

Issue is next. I create types.Date in my model. perform `getSnaphot` and i see that it is unix timestamp. i save this model to storage, retrieve it, and try to apply.

Than i got an error that unix timestamp cannot be assigned to `types.Date`.

Why it happens ?

**Comment by mattiamanzati** [comment]
Uh, you're right, that's definetely a bug not covered by tests! Gonna fix it and release 0.9.1 :)

**Comment by KatSick** [comment]
@mattiamanzati looks like it is still not fixed. https://codesandbox.io/s/qY5xpQn1y

**Comment by mattiamanzati** [comment]
Uhm, sure that is'nt any cache issue? Does not throws anymore for me :) https://codesandbox.io/s/Jqk7y8jyD
