### ISSUE TITLE
Introduce `optimistic`, for defining optimistic actions

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#237]
Requires #231 

Idea: provide built-in support for optimistic actions, that automatically unapply there changes if they fail to succeed. 

Example:

```typescript
import {types, optimistic} from "mobx-state-tree"

const Todo = types.model({
   title: "test",
}, {
   setTitle: optimistic(function(newTitle) {
       // optimistic update
       this.title = newTitle; 
       // we need to return a promise from this action
       // if it resolves: all is fine
       // if it fails: all changes made during this action are automatically rolled back!
       return someRequestLib.put("someUrl", this.toJSON())
   })
}
```

Gotcha: use `function`, not `() =>` for correct `this`

---

Untested implementation:

```typescript
import {patchRecorder} from "mobx-state-tree"

export function optimistic<T extends Function>(action: T): T {
   return function() {
     const recorder = patchRecorder(this) // let's keep track of anything this action modifies
     const promise = action.apply(this, arguments)
     // TODO: finally would be in order here:
     recorder.stop() // only record the changes made during the synchronous part of the fn, the optimistic updates
     promise.catch(
        e => {
          recorder.undo() // inverse apply any recorded patches  
        }
     )
     return promise // caller might be interested in this promise as well
   }
}
```

**Comment by mweststrate** [comment]
Could also create `atomic`, which allows you to apparently update an object (this might be too fusy), but does not really update it until the promise returned from the action has completed

```typescript
import {patchRecorder, clone} from "mobx-state-tree"

export function atomic<T extends Function>(action: T): T {
   return function() {
     const tmpInstance = clone(this)
     const recorder = patchRecorder(tmpInstance)
     const promise = action.apply(tmpInstance, [].concat(arguments, this)) // if you need the original for whatever reason
     promise.then(
        () => {
           recorder.stop()
           recorder.replay(this) // replay recorded patches on the original
        },
        e => {
           recorder.stop()
           // no replay
        }
     )
     return promise // caller might be interested in this promise as well
   }
}
```

**Comment by mattiamanzati** [comment]
Yeah, I just PVT you on gitter asking for the same thing! :D 
I was thinking about having a "transaction", where the implementation is similar to the atomic one, but I think there should be some gotchas:

1. Transaction accepts a function as parameter
2. The function as parameter should either return a promise or be async
3. "this" in the function is either the store or a copy of it unprotected, allowing changes to the state even if there are async/await
4. Changes should be applied either while setting them on "this", or at the end the execution.
5. If the function/promise throws, everything is rolled back, if no error is returned, changes are applied/not reverted.

**Comment by mattiamanzati** [comment]
Gotchas:
1. Since the function is async, changes to the store would be applyied asynchronusly, so during an update in a transaction, other updates outside or in another transactions may happen.
2. The best would be to apply patches to the original store as they happen, for example you could implement something like this.isLoading = true and be sure that if the commit action fails, this.isLoading will revert back to false automatically.
3. Maybe the transaction manager needs to be stored at root, because a transaction may access/call other actions through getRoot(this) etc.. How can we intercept those cases?

**Comment by mattiamanzati** [comment]
Small sample that does'nt work yet properly due to missing revertable snapshots, but here's the deal: https://codesandbox.io/s/m6wW6q9R

**Comment by mattiamanzati** [comment]
This has been replaced with the middleware concept of "atomic", closing for now.
