### ISSUE TITLE
Computed property does not compute when it relys on different path of the tree?

### ISSUE THREAD

**Issue by marszhou** [mobxjs/mobx-state-tree#238]
ex: I have a rootStore, and two kinds of collection stores: categoryStore and itemStore, code is like this:

RootStore

  ```
const RootStore = types.model('RootStore', {
    categoryStore: types.optional(CategoryStore, {
        categories: []
    }),
    itemStore: types.optional(ItemStore, {
        items: []
    })
})
```

CategoryStore

```
const CategoryStore = types.model(
  'CategoryStore', {
    categories: types.array(CategoryNode)
  }
)
```

CategoryNode

```
const CategoryNode = types.model('CategoryNode', {
  id: types.identifier(),
  get items() {
        return getRoot(this).itemStore.items.filter(item => item.categoryId === this.id)
  }
})
```

ItemStore

```
const ItemStore = types.model(
  'ItemStore', {
    Items: types.array(ItemNode)
  }
)
```

ItemNode
```
const ItemNode = types.model('ItemNode', {
  id: types.identifier(),
  categoryId: types.string
})
```

When itemStore.items add new ItemNode, CategoryNode.items should be changed, but it does not cause observed react component rerender. I understand that I should use types.reference to define CategoryNode.items instead of using computed prop, but why computed not work? I have 
 used bunch of times computed props between different objects and it works in mobx, but this is not working with mst?

**Comment by mattiamanzati** [comment]
Hi! Thanks for reporting!
Unfortunately I am not able to reproduce this, can you please setup a demo on the playground or on codebox? :)

https://codesandbox.io/s/nZ26kGMD
https://mattiamanzati.github.io/mobx-state-tree-playground/

**Comment by marszhou** [comment]
sorry, it seems worked, I will check my work again..

https://mattiamanzati.github.io/mobx-state-tree-playground/#src=import%20React%20from%20%22react%22%0Aimport%20%7B%20types%2C%20getRoot%20%7D%20from%20%22mobx-state-tree%22%0Aimport%20%7B%20observer%20%7D%20from%20%22mobx-react%22%0Aimport%20%7B%20inspect%2C%20render%20%7D%20from%20%22mobx-state-tree-playground%22%0A%0Alet%20C%20%3D%200%0Alet%20I%20%3D%200%0Aconst%20ItemNode%20%3D%20types.model('ItemNode'%2C%20%7B%0A%20%20id%3A%20types.identifier(types.number)%2C%0A%20%20categoryId%3A%20types.number%0A%7D)%0A%0Aconst%20ItemStore%20%3D%20types.model(%0A%20%20'ItemStore'%2C%20%7B%0A%20%20%20%20items%3A%20types.array(ItemNode)%0A%20%20%7D%2C%20%7B%0A%20%20%20%20addItem(categoryId)%20%7B%0A%20%20%20%20%20%20%20%20let%20item%20%3D%20ItemNode.create(%7Bid%3A%20%2B%2BI%2C%20categoryId%7D)%0A%20%20%20%20%20%20%20%20this.items.push(item)%0A%20%20%20%20%7D%0A%20%20%7D%0A)%0A%0Aconst%20CategoryNode%20%3D%20types.model('CategoryNode'%2C%20%7B%0A%20%20id%3A%20types.identifier(types.number)%2C%0A%20%20get%20items()%20%7B%0A%20%20%20%20return%20getRoot(this).itemStore.items.filter(item%20%3D%3E%20item.categoryId%20%3D%3D%3D%20this.id)%0A%20%20%7D%0A%7D)%0A%0Aconst%20CategoryStore%20%3D%20types.model(%0A%20%20'CategoryStore'%2C%20%7B%0A%20%20%20%20categories%3A%20types.array(CategoryNode)%0A%20%20%7D%2C%20%7B%0A%20%20%20%20afterAttach()%20%7B%0A%20%20%20%20%20%20%20%20this.addCategory()%0A%20%20%20%20%7D%2C%0A%20%20%20%20addCategory()%20%7B%0A%20%20%20%20%20%20%20%20let%20category%20%3D%20CategoryNode.create(%7Bid%3A%20%2B%2BC%7D)%0A%20%20%20%20%20%20%20%20console.log(this)%0A%20%20%20%20%20%20%20%20this.categories.push(category)%0A%20%20%20%20%7D%0A%20%20%7D%0A)%0A%0Aconst%20RootStore%20%3D%20types.model('RootStore'%2C%20%7B%0A%20%20categoryStore%3A%20types.optional(CategoryStore%2C%20%7B%0A%20%20%20%20%20%20categories%3A%20%5B%5D%0A%20%20%7D)%2C%0A%20%20itemStore%3A%20types.optional(ItemStore%2C%20%7B%0A%20%20%20%20%20%20items%3A%20%5B%5D%0A%20%20%7D)%0A%7D%2C%20%7B%0A%20%20%20%20%0A%7D)%0A%0Aconst%20store%20%3D%20RootStore.create()%0Ainspect(store)%0A%0Aconst%20App%20%3D%20observer(%0A%20%20%20%20props%20%3D%3E%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20onClick%3D%7B()%20%3D%3E%20props.store.categoryStore.addCategory()%7D%3Eadd%20category%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20onClick%3D%7B()%20%3D%3E%20props.store.itemStore.addItem(1)%7D%3Eadd%20item%20to%20category%201%3C%2Fbutton%3E%0A%0A%20%20%20%20%20%20%20%20%3Cfieldset%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Clegend%3ECategories%3C%2Flegend%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Cul%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20props.store.categoryStore.categories.map(c%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20let%20category%20%3D%20(%3Cli%20key%3D%7Bc.id%7D%3Ecategory_%7Bc.id%7D%3C%2Fli%3E)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20let%20items%20%3D%20(%3Cul%20key%3D%7Bc.id%20%2B%20'_items'%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20c.items.map(i%20%3D%3E%20(%3Cli%20key%3D%7Bi.id%7D%3Eitem_%7Bi.id%7D%3C%2Fli%3E))%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Ful%3E)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20%5Bcategory%2C%20items%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Ful%3E%0A%20%20%20%20%20%20%20%20%3C%2Ffieldset%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A)%0A%0Arender(%3CApp%20store%3D%7Bstore%7D%20%2F%3E)%0A

**Comment by marszhou** [comment]
check this please, toggle line 31/32 uncomment to see the difference

line 31 works well.
when line 32 is uncommented, error occured :
Uncaught Error: [mobx] Invariant failed: Computed values are not allowed to cause side effects by changing observables that are already being observed. Tried to modify: ObservableArray@87

I don't understand what it describes, nothing is changed in itemStore.getItemsByCategory. Even if I return [1,2,3] directly in itemStore.getItemsByCategory, still got the same error. why?

https://mattiamanzati.github.io/mobx-state-tree-playground/#src=import%20React%20from%20%22react%22%0Aimport%20%7B%20types%2C%20getRoot%20%7D%20from%20%22mobx-state-tree%22%0Aimport%20%7B%20observer%20%7D%20from%20%22mobx-react%22%0Aimport%20%7B%20inspect%2C%20render%20%7D%20from%20%22mobx-state-tree-playground%22%0A%0Alet%20C%20%3D%200%0Alet%20I%20%3D%200%0Aconst%20ItemNode%20%3D%20types.model('ItemNode'%2C%20%7B%0A%20%20id%3A%20types.identifier(types.number)%2C%0A%20%20categoryId%3A%20types.number%0A%7D)%0A%0Aconst%20ItemStore%20%3D%20types.model(%0A%20%20'ItemStore'%2C%20%7B%0A%20%20%20%20items%3A%20types.array(ItemNode)%0A%20%20%7D%2C%20%7B%0A%20%20%20%20addItem(categoryId)%20%7B%0A%20%20%20%20%20%20%20%20let%20item%20%3D%20ItemNode.create(%7Bid%3A%20%2B%2BI%2C%20categoryId%7D)%0A%20%20%20%20%20%20%20%20this.items.push(item)%0A%20%20%20%20%7D%2C%0A%20%20%20%20getItemsByCategory(cId)%20%7B%0A%20%20%20%20%20%20%20%20return%20this.items.filter(item%20%3D%3E%20item.categoryId%20%3D%3D%3D%20cId)%0A%20%20%20%20%20%20%20%20%2F%2F%20return%20%5B1%2C2%2C3%5D%0A%20%20%20%20%7D%0A%20%20%7D%0A)%0A%0Aconst%20CategoryNode%20%3D%20types.model('CategoryNode'%2C%20%7B%0A%20%20id%3A%20types.identifier(types.number)%2C%0A%20%20get%20items()%20%7B%0A%20%20%20%20%2F%2F%20return%20getRoot(this).itemStore.items.filter(item%20%3D%3E%20item.categoryId%20%3D%3D%3D%20this.id)%0A%20%20%20%20return%20getRoot(this).itemStore.getItemsByCategory(this.id)%0A%20%20%7D%0A%7D)%0A%0Aconst%20CategoryStore%20%3D%20types.model(%0A%20%20'CategoryStore'%2C%20%7B%0A%20%20%20%20categories%3A%20types.array(CategoryNode)%0A%20%20%7D%2C%20%7B%0A%20%20%20%20afterAttach()%20%7B%0A%20%20%20%20%20%20%20%20this.addCategory()%0A%20%20%20%20%7D%2C%0A%20%20%20%20addCategory()%20%7B%0A%20%20%20%20%20%20%20%20let%20category%20%3D%20CategoryNode.create(%7Bid%3A%20%2B%2BC%7D)%0A%20%20%20%20%20%20%20%20console.log(this)%0A%20%20%20%20%20%20%20%20this.categories.push(category)%0A%20%20%20%20%7D%0A%20%20%7D%0A)%0A%0Aconst%20RootStore%20%3D%20types.model('RootStore'%2C%20%7B%0A%20%20categoryStore%3A%20types.optional(CategoryStore%2C%20%7B%0A%20%20%20%20%20%20categories%3A%20%5B%5D%0A%20%20%7D)%2C%0A%20%20itemStore%3A%20types.optional(ItemStore%2C%20%7B%0A%20%20%20%20%20%20items%3A%20%5B%5D%0A%20%20%7D)%0A%7D%2C%20%7B%0A%20%20%20%20%0A%7D)%0A%0Aconst%20store%20%3D%20RootStore.create()%0Ainspect(store)%0A%0Aconst%20App%20%3D%20observer(%0A%20%20%20%20props%20%3D%3E%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20onClick%3D%7B()%20%3D%3E%20props.store.categoryStore.addCategory()%7D%3Eadd%20category%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20onClick%3D%7B()%20%3D%3E%20props.store.itemStore.addItem(1)%7D%3Eadd%20item%20to%20category%201%3C%2Fbutton%3E%0A%0A%20%20%20%20%20%20%20%20%3Cfieldset%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Clegend%3ECategories%3C%2Flegend%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Cul%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20props.store.categoryStore.categories.map(c%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.log(props.store.itemStore.getItemsByCategory(1))%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20let%20category%20%3D%20(%3Cli%20key%3D%7Bc.id%7D%3Ecategory_%7Bc.id%7D%3C%2Fli%3E)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20let%20items%20%3D%20(%3Cul%20key%3D%7Bc.id%20%2B%20'_items'%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20c.items.map(i%20%3D%3E%20(%3Cli%20key%3D%7Bi.id%7D%3Eitem_%7Bi.id%7D%3C%2Fli%3E))%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Ful%3E)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20%5Bcategory%2C%20items%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Ful%3E%0A%20%20%20%20%20%20%20%20%3C%2Ffieldset%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A)%0A%0Arender(%3CApp%20store%3D%7Bstore%7D%20%2F%3E)%0A

**Comment by mattiamanzati** [comment]
Uhm, can you please check your mobx&mobx-react version? On codebox it seems all fine :)
https://codesandbox.io/s/W63LBNoBo

**Comment by mattiamanzati** [comment]
Uh, also a tip, getItemsByCategory should be moved in the properties object, not in the actions one because it's a view of your state :)
Does it modify the state? Yes => actions object, No => Views object

**Comment by marszhou** [comment]
after move the find function to view section, it works, thx.
