### ISSUE TITLE
A snapshot of 'type.Date' returns a number.

### ISSUE THREAD

**Issue by uufish** [mobxjs/mobx-state-tree#242]
A snapshot of 'type.Date' returns a Number. I can not read Typescript, but is probably this part?

https://github.com/mobxjs/mobx-state-tree/blob/master/src/types/primitives.ts#L66

```ts
;(DatePrimitive as any).getSnapshot = function(node: Node) {
  return node.storedValue.getTime()
}
```

This function will return a Number, but can this return an 'Date Object'?
When saving snapshot to MongoDB, it becomes a number, inconvenience occurs.

```ts
return new Date(node.storedValue)
```

**Comment by mattiamanzati** [comment]
It has been discussed over the past, the problem with a Date Object is "how we correctly serialize it?" It may be serialized using .toJSON over  date, but most backend uses unix timestamps, so we opted for unix timestamps.
You could use postProcessSnapshot over the owning model to convert it back to a Date :)

**Comment by mweststrate** [comment]
Since this issue has been closed, best open a new one. If you are
encountering errors you should demonstrate how they can be reproduced,
otherwise you are making it hard for others to understand your actual
problem

Op do 28 jun. 2018 16:11 schreef Ivanthadev <notifications@github.com>:
