### ISSUE TITLE
Is there a typescript example to look at ?

### ISSUE THREAD

**Issue by Raathigesh** [mobxjs/mobx-state-tree#243]
Is there a typescript example to use as a reference?

I have a store as follows.

```
import { types, getParent } from "mobx-state-tree";
import Endpoint from "./endpoint/Endpoint";

const AppStore = types.model("AppStore", {
  endpoints: types.map(Endpoint)
});

export default AppStore;

```

And i'm trying to import it as follows but typescript is complaining saying 'Cannot find name "AppStore"'

![image](https://user-images.githubusercontent.com/3108160/28066155-3307f4a2-667f-11e7-8404-1474a8cd56ec.png)

I'm using Typescript 2.4.1!

**Comment by mweststrate** [comment]
`AppStore` is `const`, a real thing, not a type, but you can refer to it in a type position by using : `state?: typeof AppStore.Type` instead. (You could first define `type IAppStore = typeof AppStore.Type` for convenience purposes

**Comment by Raathigesh** [comment]
Awesome! It works! Thanks for the quick reply!

**Comment by DrakeXiang** [comment]
> `AppStore` is `const`, a real thing, not a type, but you can refer to it in a type position by using : `state?: typeof AppStore.Type` instead. (You could first define `type IAppStore = typeof AppStore.Type` for convenience purposes

For anyone looking for solution, this form is outdated as stated in doc here https://github.com/mobxjs/mobx-state-tree#using-a-mst-type-at-design-time
