### ISSUE TITLE
types.late define recursive type does not work now?

### ISSUE THREAD

**Issue by marszhou** [mobxjs/mobx-state-tree#245]
This script run well in playground, I dont know what mst version playground is using. I will try it in my env again.

example:

https://mattiamanzati.github.io/mobx-state-tree-playground/#src=import%20React%20from%20%22react%22%0Aimport%20%7B%20types%20%7D%20from%20%22mobx-state-tree%22%0Aimport%20%7B%20observer%20%7D%20from%20%22mobx-react%22%0Aimport%20%7B%20inspect%2C%20render%20%7D%20from%20%22mobx-state-tree-playground%22%0A%0Aconst%20Node%20%3D%20types.union(%0A%20%20types.map(types.late(()%20%3D%3E%20Node))%2C%0A%20%20types.array(types.late(()%20%3D%3E%20Node))%2C%0A%20%20types.string%2C%0A%20%20types.number%2C%0A%20%20types.boolean%2C%0A%20%20types.Date%2C%0A%20%20types.literal(null)%0A)%0A%0Aconst%20Item%20%3D%20types.model('Item'%2C%20%7B%0A%20%20%20%20id%3A%20types.identifier(types.number)%2C%0A%20%20%20%20raw%3A%20Node%0A%7D)%0A%0Aconst%20Store%20%3D%20types.model('AppModel'%2C%20%7B%0A%20%20%20%20items%3A%20types.optional(types.array(Item)%2C%20%5B%5D)%0A%7D%2C%20%7B%0A%20%20%20%20addItem(data)%20%7B%0A%20%20%20%20%20%20%20%20let%20item%20%3D%20Item.create(%7Bid%3A%20data.id%2C%20raw%3A%20%7Ba%3A%201%2Cb%3A2%2Cc%3A%7Bx%3A%5B'd'%2C%20%7Be%3A5%7D%5D%7D%7D%7D)%0A%20%20%20%20%20%20%20%20this.items.push(item)%0A%20%20%20%20%7D%0A%7D)%0A%0Aconst%20store%20%3D%20Store.create()%0Ainspect(store)%0A%0Alet%20i%20%3D%200%0Aconst%20App%20%3D%20observer(%0A%20%20%20%20props%20%3D%3E%20(%3Cdiv%3E%0A%20%20%20%20%3Cbutton%20onClick%3D%7B()%20%3D%3E%20props.store.addItem(%7Bid%3A%20%2B%2Bi%7D)%7D%3Eadd%3C%2Fbutton%3E%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20props.store.items.map(item%20%3D%3E%20(%3Cdiv%20key%3D%7Bitem.id%7D%3E%7Bitem.id%7D%3C%2Fdiv%3E))%0A%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%3C%2Fdiv%3E)%0A)%0A%0Arender(%3CApp%20store%3D%7Bstore%7D%20%2F%3E)

I defined this type of data:

```
const Node = types.union(
  types.map(types.late(() => Node)),
  types.array(types.late(() => Node)),
  types.string,
  types.number,
  types.boolean,
  types.Date,
  types.literal(null)
)
```

Report error:

```
mobx-state-tree.module.js:78 Uncaught Error: [mobx-state-tree] Error while converting `{"id":1,"raw":{"id":1}}` to `Item`:
at path "/raw" snapshot `{"id":1}` is not assignable to type: `map<string, late(function () {
    return Node;
})> | string | number | boolean | Date | null | map<string, late(function () {
    return Node;
})>` (Multiple types are applicable and no dispatch method is defined for the union).
```

this code is working in v0.9.0, but when upgrade mst to 0.9.1/2, it throws exception.

How to do the same thing with the new version api?

**Comment by marszhou** [comment]
I figure it out, it is caused by types.Date

```
const Node = types.union(
  types.map(types.late(() => Node)),
  types.array(types.late(() => Node)),
  types.string,
  types.number,
  types.boolean,
  types.literal(null)
)
```

**Comment by mattiamanzati** [comment]
Yep, types.Date accepts either a Date or a Number :)
