### ISSUE TITLE
Improve readme

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#25]

**Comment by tjbo** [comment]
Loving the mobx state tree!

What would be great is if there was more information on working with references.

**Comment by dmackerman** [comment]
Yep, this seems really powerful and something the mobx community can standardize around! Looking forward to it.

**Comment by ochervak** [comment]
Me too. Also i noticed that Example from README is not working since mapOf is not in package now

**Comment by mweststrate** [comment]
PR #59 adds support for references, see the test for some examples: https://github.com/mobxjs/mobx-state-tree/pull/59/files#diff-4f5616b5de5a2cbc9fdc4673ea91d15cR10

**Comment by warpech** [comment]
Please update the README example, seems that `action` is not in the package either.

**Comment by mweststrate** [comment]
@warpech yep sorry, `action` is not needed to anymore. Will walk through the docs carefully before 1.0. Keep an eye on the changelog in the mean time, I'll very briefly write down breaking changes there in the mean time

**Comment by mattiamanzati** [comment]
Now there's also a "Getting Started" guide that will introduce yourself to the basics of MST by building a Todo app :)
https://github.com/mobxjs/mobx-state-tree/blob/master/docs/getting-started.md
