### ISSUE TITLE
[Possible feature] make environment / getEnv typesafe

### ISSUE THREAD

**Issue by Bnaya** [mobxjs/mobx-state-tree#250]
It will be useful to have the getEnv to return a defined typescript interface 
It can be typescript generic to be passed to types.model

**Comment by mattiamanzati** [comment]
Unfortunately this can't be done, that's because environment is'nt defined by the model itself, but by the root model. So typings of environment will change based on the owning node.
I'm open to suggestions but I see this hard to implement, because it behaves like the React context :/

**Comment by Bnaya** [comment]
What about something like:
```ts
getEnv<T>: () => T;
```

might be nicer to use than 
```ts
const env = <IMyApi>getEnv(this);
```

**Comment by mattiamanzati** [comment]
Yeah, that could be indeed :)
