### ISSUE TITLE
Deleting a non-existent entry from a map throws an error

### ISSUE THREAD

**Issue by JakeCoxon** [mobxjs/mobx-state-tree#255]
```javascript
import React from "react"
import { types } from "mobx-state-tree"
import { observer } from "mobx-react"

const AppModel = types.model({
    myMap: types.optional(types.map(types.number), {})
}, {
    something(){
        this.myMap.delete(1020);
    },
})

const store = AppModel.create()

store.something();
```
[playground](https://mattiamanzati.github.io/mobx-state-tree-playground/#src=import%20React%20from%20%22react%22%0Aimport%20%7B%20types%20%7D%20from%20%22mobx-state-tree%22%0Aimport%20%7B%20observer%20%7D%20from%20%22mobx-react%22%0A%0Aconst%20AppModel%20%3D%20types.model(%7B%0A%20%20%20%20myMap%3A%20types.optional(types.map(types.number)%2C%20%7B%7D)%0A%7D%2C%20%7B%0A%20%20%20%20something()%7B%0A%20%20%20%20%20%20%20%20this.myMap.delete(1020)%3B%0A%20%20%20%20%7D%2C%0A%7D)%0A%0Aconst%20store%20%3D%20AppModel.create()%0A%0Astore.something()%3B)

Above code throws `Error: [mobx-state-tree] Not a child 1020`. A workaround is to check that the entry exists in the map before you try and delete

**Comment by mattiamanzati** [comment]
Thanks for reporting!
This has been fixed and example code has been added to the test suite, fix will be out soon with next release!
Thanks for reporting and for your time! :)

**Comment by JakeCoxon** [comment]
Thanks for the quick fix and the work you are putting in!
