### ISSUE TITLE
Make IModelType exported to avoid TS Errors

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx-state-tree#256]
While trying a simple test with TS 2.4.1:
```js
import { types } from 'mobx-state-tree';

export const AreaProperties = types.model('AreaProperties', {
}, {});
```

I got a typescript error saying:

```TS4023: Exported variable 'AreaProperties' has or is using name 'IModelType' from external module "....../node_modules/mobx-state-tree/dist/types/complex-types/object" but cannot be named.```

The fix is easy (but right now kind of ugly), I need to add an import like this:

```import { IModelType } from 'mobx-state-tree/dist/types/complex-types/object';```

and then the error will disappear, but I'd rather import it from 'mobx-state-tree' directly.

**Comment by xaviergonz** [comment]
Same with ISimpleType actually

**Comment by mattiamanzati** [comment]
Hi, thanks for reporting! They are now exported as well on the main package and should be out with next release! :)
Can you please check if its ok by cloning the repository locally, building and npm install from local folder?
Thanks for your time! :)

**Comment by xaviergonz** [comment]
seems to work :) the only annoying thing is WebStorm trying to optimize out the "unused" imports, but I guess that's a WebStorm problem (and using // noinspection ES6UnusedImports fixes it)

**Comment by xaviergonz** [comment]
Ok actually another one when using types.map

import { IExtendedObservableMap } from 'mobx-state-tree/dist/types/complex-types/map'

**Comment by mattiamanzati** [comment]
I updated the master branch, please check if its ok so I will cut a minor release :)

They only support strings as now due to a mobx limitation to support IE. 
It will be supported on MobX 4, so keep tuned. :)
Most likely will be implemented in MST after as a separate type that will (most likely types.kvp = key value pair) that will be an observable map and serialized as an array of object with key and value properties.

**Comment by xaviergonz** [comment]
Looking good!

Damned IE :) Am I right that the json serialization (snapshot) of a map then is a plain object?

**Comment by mattiamanzati** [comment]
@xaviergonz Yep, it is!

**Comment by mweststrate** [comment]
@xaviergonz Please note to always import from `mobx-state-tree` never from a specific file inside the dist build. That will mess up packaging etc. Sadly there is a popular VSCode plugin that does that by default :(

**Comment by mweststrate** [comment]
@mattiamanzati btw, we could more often use `type` instead of `interface`, which don't have the constraint they need to be exported :)

**Comment by xaviergonz** [comment]
@mweststrate thanks, I wanted to, but I didn't have much of a choice :) I plan to fix the imports in my code as soon as the fix is out in npm
