### ISSUE TITLE
Modify model in async action

### ISSUE THREAD

**Issue by tomitrescak** [mobxjs/mobx-state-tree#257]
Thanks for the great work! I have a problem with async actions in model as they do not allow me to modify the model. The only way to do this is either extract async functionality from the store, or unprotect model. What is the best way?

Example:

```js
const accounts = types.model('Accounts', 
{
   acccounts: types.array(types.string)
},
{
deleteAccount(context, index) {
        context.Utils.Ui.confirmDialog(() => {
            this.accounts.splice(index, 1);
        });
    }
}
```

Calling `deleteAccount` and confirming the deletion will yield following:

```
Uncaught (in promise) Error: [mobx-state-tree] Cannot modify 'string[]@/accounts', the object is protected and can only be modified by using an action.
```

**Comment by tomitrescak** [comment]
OK, from your FAQ I assume following solution:

```js
const accounts = types.model('Accounts', 
{
   acccounts: types.array(types.string)
},
{
    confirmDeleteAccount(context, index) {
        context.Utils.Ui.confirmDialog(() => {
            this.deleteAccount(index);
        });
    },
    deleteAccount(context, index) {
        this.accounts.splice(index, 1);
    }
}
```

**Comment by samuelalvin** [comment]
I had the same problem today, and @tomitrescak solution solve the problem. The docs which explain this can be found [here](https://github.com/mobxjs/mobx-state-tree/blob/master/docs/async-actions.md#using-separate-actions).
