### ISSUE TITLE
middleware for patches

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx-state-tree#259]
I know this is most probably not possible, but then I thought that maybe using mobx intercept it is, so here's my question.

Basically my use case is a client and a server application. Both have a model tree in memory, and idea is:
1. the client tries to make a modification on the tree
2. a patch is generated (but not applied to the client model to avoid a desynchronization)
3. the patch is sent to the server
4. the server applies the patch to its model copy
5. the server sends the patch back to all connected clients
6. all the clients apply such change to their model copies

I know this is doable using an action middleware, but at first I was planning to use an unprotected tree to save me from implementing setters and getters. So my question is, is this doable with patches somehow? or are actions actually the best way to do it?

**Comment by mattiamanzati** [comment]
Uhm, preventing is kinda tricky, I did something similar back in time, using the old MST api, and client was optimistic about the api. Here's the link, if I have spare time I will try to update and implement it.

https://gist.github.com/mattiamanzati/b4e6c469045d9bb5d67c2b01cabc1fbe

Uhm, whats the issue with actions? :)

**Comment by xaviergonz** [comment]
Thanks for the answer. Doesn't that code duplicate the whole state?

And there's nothing wrong with actions :) Just that it is boring and error prone to make setters all the time. Now that I think about it maybe I could make a function that makes automatic action setters given the model types...

**Comment by mattiamanzati** [comment]
Yes, it actually does. :)

I'd recommend you defining a "_set" action on the model taking as parameter the attribute and the value to set. On the view you can use it like onChangeText={props.model._set.bind(null, "username")} :)

**Comment by xaviergonz** [comment]
That's a nice idea! though I wonder if I can do something more typescript friendly

**Comment by mattiamanzati** [comment]
TypeScript has support for "keyof this" as parameter type for the _set name, but unfortunately works only inside classes :/

**Comment by mattiamanzati** [comment]
I would consider this static utility function :)

```typescript
const Model = types.model({
    user: types.string,
    pin: types.number
}, {
    _set(property, value) {
        this[property] = value
    }
})

// declare an utility function
function updater<T, K extends keyof T>(
    model: IStateTreeNode & T & {_set: (property: any, value: any) => void},
    property: K
): (value: T[K]) => void {
    return (value: T[K]) => {
        unprotect(model)
        model._set(property, value)
        protect(model)
    }
}
// for better perf, consider this
const updater = memoize(updater)

// on your React view, onChangeText={updater(props.user, "name")}
updater(Model.create(), "user") // returns (value: string) => void
updater(Model.create(), "pin") // returns (value: number) => void
updater(Model.create(), "avatar") // throws in TS, avatar does not exists! :D
```

**Comment by xaviergonz** [comment]
nice :) just curious, why does the model need to be unprotected if it's being changed via an action?

**Comment by mattiamanzati** [comment]
Uh, just a type error, tested it with unprotected mode and then forgot to remove it! I updated the post! :)

**Comment by mweststrate** [comment]
@xaviergonz did you see: https://github.com/mobxjs/mobx-state-tree/issues/237#issue-241404347? It implements optimistic updates, but I think the example can easily be adjusted for creating pessimistic updates. The advantage is that you don't need to work on a shadow copy. 

If you get stuck ping me, then I'll try to put some stuff in a fiddle

**Comment by xaviergonz** [comment]
@mweststrate I was just thinking of an action middleware on the client that serializes the action and just ignores it in order to get automatic pessimistic updates and later applies any actions coming via the websocket with the server. Wouldn't that work?

**Comment by mweststrate** [comment]
@xaviergonz yeah that would probably be even easier :) Good thinking

**Comment by mweststrate** [comment]
Closing issue for now, feel free to reopen if there are more questions
