### ISSUE TITLE
onAction not trigger when invoke from parent store

### ISSUE THREAD

**Issue by AlexanderChen1989** [mobxjs/mobx-state-tree#260]
```javascript
const Store = t.model({
  owner: t.model({}, {
    hello() {
      console.log('Hello')
    }
  }),
}, {
  doIt() {
    this.owner.hello()
  }
})

const store = Store.create({owner: {}})

onAction(store.owner, action => {
  console.log(action)
})

window.store = store 
```

![image](https://user-images.githubusercontent.com/2957936/28448902-4cff4860-6e0e-11e7-8529-1361e7f8ad0c.png)

**Comment by mattiamanzati** [comment]
By design only the outermost action will trigger action events, and refers to action owned by that model you subscribe to, so Thats intended. @mweststrate may be more precise than me here :)

**Comment by AlexanderChen1989** [comment]
I know, thanks

**Comment by mweststrate** [comment]
Actually I think we have run here in a potential issue with the middle ware model, e.g. given this:

```javascript
const Todo = types.model({
  done: types.boolean,
}, {
  toggle() {
    this.done = !this.done
  }
})

const Store = types.model({
  todos: types.array(Todo)
}, {
  toggleAll() {
    this.todos.forEach(t => t.toggle())
  }
}
```

If you now add some middleware to a store instance, everything will work as expected. However, if you add middleware to a specific todo (e.g. `addMiddleWare(store.todos[0], someHandler)`), it will trigger on `store.todos[0].toggle()`, but not(!) on `toggleAll`

I think there are 3 potential fixes for this:
1 . make middleware smarter, and somehow detect that the middleware on todo should be triggered as well
2. forbid attaching middleware on a non-root
3. trigger middleware always, also if an action is called from another action

---

For 3: the reason why indirectly called actions don't call middleware is that it ensures replayability, indirectly called actions don't have to be replayed, as they should be the deterministic result of calling the 'wrapping' action. 

Note that this is currently not entirely true; async handlers need to be actions currently, but are in fact also the result of calling another action. Still tinkering on how this can be handled more elegantly

For 2: this is the easiest and conceptually most simple solution, but makes MST less composable

For 1: This can be achieved by keeping track of whether listeners have already fired.

So I think either 1 or 2 should be implemented to fix this properly

**Comment by olivoil** [comment]
Hi! Is there a way to receive actions called from another action in a middleware at all?

I'm adding collaborative features to an application. I have actions that are local to a client, and am extracting the logic that should be replicated to other clients in separate actions. My hope was to call a "replicated" action from a local action, and have a middleware pick it up and handle the replication. Currently the middleware receives the local action, but not the inner call to the replicated action. Is there a workaround to support such a use case? Or a better way to architect it on my end?
