### ISSUE TITLE
docs for types.refinement is wrong

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx-state-tree#264]
types.refinement has a first arg of "name", but it is missing on the main readme docs

**Comment by xaviergonz** [comment]
Also I'm not sure how I'm supposed to use it with types.optional, is it
1. ```types.optional(types.refinement(types.number, () => ...), 100)```
or
2. ```types.refinement(types.optional(types.number, 100), () => ...)```

**Comment by mattiamanzati** [comment]
Both are valid, as types are composable :)

**Comment by xaviergonz** [comment]
nice, thanks :)

**Comment by mweststrate** [comment]
Updated the docs, thanks for noticing

**Comment by daimeng** [comment]
on more thing on this. name is marked optional in the docs (for refinement), but i think it isn't optional.
