### ISSUE TITLE
Add nextjs example

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#27]
because SSR and such should be trivial with mobx-state-tree :)

**Comment by finneganh** [comment]
I'd be interested in helping out with this, as someone currently developing a Next.js app that uses MobX.

**Comment by mweststrate** [comment]
@finneganh I think 0.3.3's api is stable enough to try such a thing. Would you be interested in creating such an example?

**Comment by mydearxym** [comment]
Hi @finneganh @mweststrate @mattiamanzati @cpunion @chrisvariety 

i setup a [boilerplate](https://github.com/mydearxym/mastani/tree/boilerplate) with MST and next.js with SSR, themes, i18n etc ...

Hope to help !

**Comment by dargue3** [comment]
Just made a PR over at [next.js](https://github.com/zeit/next.js/pull/3179)!

@mweststrate you mind giving it a look to make sure I have it right?

**Comment by mweststrate** [comment]
Available here: https://github.com/zeit/next.js/tree/master/examples/with-mobx-state-tree

**Comment by kauly** [comment]
A example with mobx-react-lite will be nice.
