### ISSUE TITLE
Example of MobX State Tree

### ISSUE THREAD

**Issue by alexvcasillas** [mobxjs/mobx-state-tree#271]
Hey @mweststrate !

Here I drop the links to working demos of MobX State Tree + Link to the repo where it's holded : )

Working demo currently built for production : )
[https://alexvcasillas.com](https://alexvcasillas.com)
Repository with the Source Code:
[https://github.com/alexvcasillas/react-mobx-state-tree](https://github.com/alexvcasillas/react-mobx-state-tree)

It combines MobX State Tree with also GraphQL : )

Cheers, mate!

**Comment by mattiamanzati** [comment]
Closing, but Would be nice to have a gql demo in the mst-examples though :)
