### ISSUE TITLE
Typescript issue

### ISSUE THREAD

**Issue by tomitrescak** [mobxjs/mobx-state-tree#272]
Hi, can you please check out following code and let me know what is wrong there?

```typescript
const Foo = types.model({
  foo: 1
})
type FooType = typeof Foo.Type;

let bar: IType<FooType, FooType> = Foo; // explodes saying that the two are not compatible
```

**Comment by mweststrate** [comment]
I think you need: let bar: IType<typeof Foo.SnapshotType, FooType> = Foo;


Op do 27 jul. 2017 om 12:47 schreef Tomas Trescak <notifications@github.com

**Comment by tomitrescak** [comment]
Awesome. Thanks!
