### ISSUE TITLE
[RFC] Improve first class support for async actions / processes

### ISSUE THREAD

**Issue by mattiamanzati** [mobxjs/mobx-state-tree#273]
Extracted from #267 

Ok, here's the proposal for an API that would allow either safe time-travelling, and nice and fine TS typings.

Given the following piece of code as example which is taken from a currently working app.
```typescript
t.model({}).actions(self => {
            const recoverFromStorage = async(self, "recoverFromStorage")(function*(userId) {
                    // read user data from async storage
                    const userData = yield () => AsyncStorage.getItem("user_data")

                    // if no user data found, parse the remote api
                    if (!userData) {
                        yield () => fetch("http://localhost:4000/"+userId)
                    }
                })
            }

   return {recoverFromServer}
})
```

Instead of allowing generators as members of actions, we introduce a new function "async" which takes as only argument the self of the model and a name to store the generator into.
It returns a function that accepts the generator and returns a function with same parameters as the generator but with return type Promise<T>, where T can be optionally be specified when calling async<T>(this, "recoverFromStorage").

The action log of "recoverFromStorage" will be exactly as is now, except the addition of a id field.
`{name: "recoverFromStorage", path: "/auth", args: [1], id: 1, mode: "return"}`
This way, middleware can handle it with no problem as happens currently with sync actions.

After that, the async execution will eventually start, and a spawn event will be emitted. (could be avoided, but its nice to have).
`{name: "recoverFromStorage", path: "/auth", args: [], id: 2, mode: "spawn", spawnedBy: 1}` (spawnedBy could eventually be stored in args)

When the action will end, a throw or return could eventually be emitted.
`{name: "recoverFromStorage", path: "/auth", args: [undefined], id: 3, mode: "return", spawnedBy: 1}`
`{name: "recoverFromStorage", path: "/auth", args: ["ERROR!"], id: 3, mode: "throw", spawnedBy: 1}`

We basically have 3 modes: return | throw | spawn. The later one could be even be avoided as said before.

Now we can have 2 options:

1. Serialize as top level call:
We could now treat the code inside the generator as it would be global code executed by the user. The only difference is that spawnedBy will be present in any of the emitted actions. So in the given example code the following actions will be emitted:
`{name: "recoverFromStorage", path: "/user", args: [], id: 3, mode: "return", spawnedBy: 2}`
...and eventually applyied patches without actions can be serialized as applyPatches invoke
`{name: "@APPLY_PATCHES", path: "/auth", args: [{op: "replace", path: "/userId", value: 1}], id: 4, mode: "invoke"}`
This also ensures composability, because as we can see in action #3 another spawn action event could be triggered.
This way of handling is nice because it emits nicely replayable actions, but while replaying won't actually re-run the generator. It will instead perform the state changes the generator did. We could even assume that everything we do in the generator is impure (e.g. http calls, storage reads, etc...), but will be actually converted onto pure actions/patches calls.

2. Serialize as yields happens
The other option involves serializing the value emitted/read by the generator. This will re-run the generator while replaying, but notice that it will also perform any promise code. So if we were for examply replaying some fetch/post to an endpoint it will actually perform it even if the generator will actually .next the replay log value, resulting in some issues in the database.

**Comment by mattiamanzati** [comment]
Extracted from #267 

Ok, here's the proposal for an API that would allow either safe time-travelling, and nice and fine TS typings.

Given the following piece of code as example which is taken from a currently working app.
```typescript
{
            const recoverFromStorage = async(self, "recoverFromStorage")(function*() {
                    // read user id from async storage
                    const userId = yield () => AsyncStorage.getItem("user_id")

                    // if has one, restore it
                    yield () => getUserService(this).recoverFromStorage()
                    if (userId && getUserService(this).get(parseInt(userId, 10))) {
                        this.userId = parseInt(userId, 10)
                    }
                })
            }
}
```

Instead of allowing generators as members of actions, we introduce a new function "async" which takes as only argument the self of the model and a name to store the generator into.
It returns a function that accepts the generator and returns a function with same parameters as the generator but with return type Promise<T>, where T can be optionally be specified when calling async<T>(this, "recoverFromStorage").

The action log of "recoverFromStorage" will be exactly as is now, except the addition of a id field.
`{name: "recoverFromStorage", path: "/auth", args: [], id: 1, mode: "return"}`
This way, middleware can handle it with no problem as happens currently with sync actions.

After that, the async execution will eventually start, and a spawn event will be emitted. (could be avoided, but its nice to have).
`{name: "recoverFromStorage", path: "/auth", args: [], id: 2, mode: "spawn", spawnedBy: 1}` (spawnedBy could eventually be stored in args)

When the action will end, a throw or return could eventually be emitted.
`{name: "recoverFromStorage", path: "/auth", args: [undefined], id: 3, mode: "return", spawnedBy: 1}`
`{name: "recoverFromStorage", path: "/auth", args: ["ERROR!"], id: 3, mode: "throw", spawnedBy: 1}`

We basically have 3 modes: return | throw | spawn. The later one could be even be avoided as said before.

**Comment by mattiamanzati** [comment]
Here's a full code sample
```typescript
declare function async<T>(lock: T, name: string, gen: () => Generator): () => Promise<any>
declare function async<T, A>(lock: T, name: string, gen: (a: A) => Generator): (a: A) => Promise<any>
declare function async<T, A, B>(lock: T, name: string, gen: (a: A, b: B) => Generator): (a: A, b: B) => Promise<any>
declare function async<T, A, B, C>(lock: T, name: string, gen: (a: A, b: B, c: C) => Generator): (a: A, b: B, c: C) => Promise<any>
declare function task<R>(fn: () => R | Promise<R>): R

const Todo = t.model({
    id: t.identifier(t.string),
    name: t.string,
    done: t.optional(t.boolean, false)
}).actions(self => {
    function toggle() {
        self.done != self.done
    }

    const sync = async(self, "sync", function* () {
        yield task(() => fetch("http://localhost:4000/" + self.id, { method: "POST", body: JSON.stringify(getSnapshot(self)) }))
    })

    return { toggle, sync }
})


function createStore<S, T extends { sync: () => Promise<any> }>(model: IModelType<S, T>) {
    return t.model({
        data: t.map(model)
    }).actions(self => {

        const sync = async(self, "sync", function* (serverUrl: string) {
            // get the current items in the store
            const items = self.data.values()
            for (let i = 0; i < items.length; i++) {
                // patch the remote server
                yield items[0].sync()
            }
        })

        const restore = async(self, "restore", function* () {
            // revive the content from the localstorage
            const localData = yield task(() => window.localStorage.getItem(model.name + "Store"))
            // if there is local data, then restore it
            if (localData) {
                applySnapshot(self, JSON.parse(localData))
            }
        })

        return { sync, restore }
    })
}

const TodoStore = createStore(Todo)
```
## The call signature
We'll introduce a new function, called async, that takes 3 required parameters.
The first one is the "**self**" object. async will use that to ensure that its being called while the object is in initialization phase
(initializers.reduce is being looped and called). 
The second one will be the **generator name** that is an internal name that will be used as action name when the generator steps; notice that async will keep in memory a reference to the original generator
stored with the given name under a hidden place in the object type. Inside the same type, there could'nt be more that one async with the same name (basically the name is unique).
The third one is the **generator** which may have multiple parameters.
This async function will return function with the same arguments of the generator (same call signature) but that will instead return a Promise<any> (or eventually any generic type provided to async<number>(self, generatorName) instead of the iterator object.
This way the return type of async is already a correct typed function so there is no need of more magic tricks inside of actions definition to make it correct.

## The generator body
The generator could be used as it would be an async/await function. This means that any yielded promise will be awaited and once it resolves/rejects its result will be .next or .throw in the running generator. This behaviour is mostly the same as the "co" library, but will support only yielding promise.

## Yielding tasks
Other than promises, the generator could yield tasks. What are tasks?
Tasks are side effects with the outside-MST world. Tasks include data fetching, posting, reading/saving to storage, websockets, etc... basically any I/O operation that produces an effect. To ensure that, the thunk provided to task will be executed in "non-action"; meaning that it could read the MST, but not modify it. The value yielded should be also serializable.

## Actions stream
Action stream will be mostly the same as we did before. Action will have 2 additional fields, id and mode. Id will be a progressive (numeric or random string) to represent the current "transaction number" and mode will be the calling mode. 
If the action is synchronus, the mode will be "return" which means that the function gets called and returns immediately.
```
{name: "toggle", path: "/data/1", args: [], id: 3, mode: "return"}
```
If the action is asynchronus, the previous mode will be emitted, and an additional row with mode "spawn" will be emitted.
```
{name: "sync", path: "/", args: ["http://localhost"], id: 4, spawnedBy: 3, mode: "spawn"}
```
When the promise resolves/rejects, a line with the same id and mode either resolve or reject will be emitted if the promise either resolve or reject. The args will contain the promise resolved/rejection value.
```
{name: "sync", path: "/", args: [resolve], id: 5, spawnedBy: 3, mode: "resolve"}
{name: "sync", path: "/", args: [false], id: 5, spawnedBy: 3, mode: "reject"}
```
In addition to that, whenever a task() is yielded, a mode "task" and "taskError" will be emitted whenever the task resolves or rejects. In the args object well find as first parameter the resut of the task.

As said task and taskError will be triggered only when a task is yielded. In the given example it wont be triggered when yield items[0].sync() is called.

# Async methods time travelling
Beyond classical snapshot-based time travelling, task allows a pure replay of async actions. Beyond a global flag, yielding tasks wont run, but will instead wait for an "applyAction" of an action with mode: task or taskError and the value in the serialized action will be yielded back to the generator via either throw or next.
This allows usage scenarios where for example the API endpoint returned a value on the client, and when time travelling we want to replay that without triggering the endpoint again. We can change the code and fix our bug and see which step the code would have followed if everything was ok since the first time. This is heavily inspired on how cycle.js implements time travel by replaying sinks input.

**Comment by mweststrate** [comment]
Counter proposal:


```javascript
const Todo = t.model({
}).actions(self => {

    const syncTodo = process(function* syncTodo() {
        this.state = "syncing"
        yield syncTodo(this.id, getSnapshot(this))
        this.state = "done"
    })
    
    return { sync }
})

const postTodoData = task(function postTodoData(id, json) {
    return fetch("http://localhost:4000/" + self.id, { method: "POST", body: JSON.stringify(getSnapshot(self))
})
```

## process

Process works the same as the old `async`  method, except that yield now can also return a task invocation

In contrast to tasks, process can modify the object from which action they were spawned

## tasks

Tasks are superficially speaking similar to yielding a promise directly. However, they have a few typical properties:

1. They cannot modify models
2. They emit specific middleware events (see below)
3. They can only be invoked by yielding from a process
4. Since they are supossed pure, they can be (or must?) be defined outside models
5. any non-promise value returned will automatically be promisified

The purpose of tasks is to model side effects like making network request at a specific place. The goal of this is to easily stub them out, which can be done as follows

```javascript
interceptTasks(
    // block to execute
    () => {
        // need to return promise
        return task.sync()
    },
    [
        // for each task encountered, the next interceptor will be run:
        (name, args, next) => {
            return next() // proceed with original implemetation
        },
        (name, args, next) => {
            assert.equal(name, "syncTodo") // make some assertions, useful for testing..
            // don't execute task, instead, return some stub data
            return Promise.resolve({ data: true })
        }
    ]
)
```

InterceptTasks will throw if the block finishes before all interceptors where run, or if all interceptors where run, but another tasks is spawned.

Maybe there should be a more generic form as well?

## middleware

current `mode` field is replaced with an enumeration like this:

* `action` (currently `none`)
* `process_spawn` (currently `invoke`), `process_(yield|yieldError|return|throw)`
* `task_spawn`

actions and process have id's which are mentioned in process and task events

**Comment by mattiamanzati** [comment]
I think I fully agree on this counter proposal, only thing is that I'd change the process signature from
`process(function* syncTodo() {` to `process(self, "syncTodo", function* syncTodo() {` as was before, to support ES5 generator transpilation :)
I really like the idea of being able to intercept tasks (which will by default do "next") so things like dev tools can use that to hook into it to show visually the progress of the process.
Maybe `interceptTasks(` could be `addTaskMiddleware` and accept a model instance instead of executing a code block? That would make easier to hook into them :)

**Comment by mattiamanzati** [comment]
Uh, I also just noticed the this in the generator, could we skip the generator bounding and make the user use self instead so it will be consistent with the rest of the API? :)
Can you please write down a sample of the action stream that will be produced? :)
I am unsure, but maybe tasks should not appear in actions stream and have their own separate stream/listeners.

**Comment by luisherranz** [comment]
Quick question. What's the advantage of using this:
```javascript
const Todo = t.model({
   ...
}).actions(self => {
    const syncTodo = process(self, "syncTodo", function* syncTodo() {
        self.state = "syncing"
        yield postTodoData(this.id, getSnapshot(this))
        self.state = "done"
    })
    return { syncTodo }
})

const postTodoData = task(function postTodoData(id, json) {
    return fetch("http://localhost:4000/" + id, { method: "POST", body: json })
})
```

Over using external logic like this?
```javascript
const Todo = t.model({
   ...
}).actions(self => ({
  startSync() { self.state = 'syncing' },
  stopSync() { self.state = 'done' },
})

const syncTodo = async todo => {
  todo.startSync()
  await fetch(`http://localhost:4000/${todo.id}`, { method: "POST", body: getSnapshot(todo) })
  todo.stopSync()
}
```

**Comment by mattiamanzati** [comment]
Simply that you'll need n-functions were n is the number of your await key count + 1. Using process you don't need that, the "async/await" function will be one and correctly wrapped. Also as explained before there will be additional hooks for async function execution :)

**Comment by luisherranz** [comment]
Ok, thanks for the answer @mattiamanzati!

**Comment by mweststrate** [comment]
@mattiamanzati 

> I think I fully agree on this counter proposal, only thing is that I'd change the process signature from
process(function* syncTodo() { to process(self, "syncTodo", function* syncTodo() { as was before, to support ES5 generator transpilation :)

`self` is not needed anymore, by saving / restoring the action context. See the changes in `core/action.ts`

> I really like the idea of being able to intercept tasks (which will by default do "next") so thing> s like dev tools can use that to hook into it to show visually the progress of the process.
Maybe interceptTasks( could be addTaskMiddleware and accept a model instance instead of executing a code block? That would make easier to hook into them :)

Yep, might be better, not entirely cristalized out yet :)

> Uh, I also just noticed the this in the generator, could we skip the generator bounding and make the user use self instead so it will be consistent with the rest of the API? :)

Oops, indeed, was to much focused on making it work again

> Can you please write down a sample of the action stream that will be produced? :)

See: https://github.com/mobxjs/mobx-state-tree/blob/no-more-this/test/async.ts#L273

> I am unsure, but maybe tasks should not appear in actions stream and have their own separate stream/listeners.

Thought about this, but coordinating joining streams (if you need both), is most probably harder then filtering out relevant stuff from a single stream. (A syntax like `addMiddleWare(filter, handler)`  might make this syntactically easier btw

**Comment by mweststrate** [comment]
Released quite a while ago :)
