### ISSUE TITLE
Type refinement not checked on action (but checked on applySnapshot)

### ISSUE THREAD

**Issue by fabienjuif** [mobxjs/mobx-state-tree#275]
Hi everybody :)

## Summary
We have some weird behaviour about `identifier` checking : 
 - it works well with `applySnapshot`
 - it seems bypassed with an action.

## Context
We have this helper to declare identifiers :
```es6
export default (name: string) => types.identifier(
  types.refinement(
    'id',
    types.string, identifier => identifier.indexOf(`${name}_`) === 0,
  ),
)
```

We have this model (Author): 
```es6
import { types } from 'mobx-state-tree'
import { getIdType } from './helpers'

const name: string = 'Author'

export default types.model(
  name,
  {
    id: getIdType(name),
    name: types.string,
    image: 'https://cdn.pixabay.com/photo/2016/11/18/23/38/child-1837375_1280.png',
  },
)
```

## Error
Using an action to set our store: the `Author` identifier is not checked. 😢 
Using `applySnapshot`: the `Author` identifier is checked. 👍 

----

## With an action
![image](https://user-images.githubusercontent.com/17828231/28769752-09507d10-75dd-11e7-99ab-cbfd72f22162.png)

## With `applySnapshot`
PR: https://github.com/fabienjuif/gni-mst/pull/4/files
```es6
`AnonymousModel`:
at path "/recipes/0/author/id" value `"char_1"` is not assignable to type: `identifier(id)`, expected an instance of `identifier(id)` or a snapshot like `identifier(id)` instead.
```

## With `applySnapshot` fix
PR: https://github.com/fabienjuif/gni-mst/pull/5/files
![image](https://user-images.githubusercontent.com/17828231/28769833-5e894064-75dd-11e7-9c43-aa2d31489ce1.png)

**Comment by mattiamanzati** [comment]
Hello!
Thanks for reporting! :)
Can you please share a minimal repro where the identifier is not checked when using in action? :) So we can also add it to the test suite to avoid creating a regression in the future :)
