### ISSUE TITLE
Typescript / Nested model / Array type checking error on action

### ISSUE THREAD

**Issue by fabienjuif** [mobxjs/mobx-state-tree#276]
Hi :)

## Summary
Nested models and arrays seem to not work well with typescript.

## Context
We have a model this form : 
```
store
  - recipes: Recipe[]
    - beer: Beer
    - author: Author
    - ingredients: Ingredient[]
```

## Issue
When we try to set a Recipe with empty ingredients (empty array) via `addRecipe` action (on our store), we got a Typescript build error: 
```
./src/App.tsx
(5,17): error TS2345: Argument of type '{ id: string; name: string; beer: { id: string; name: string; alcool: number; type: "Malt"; color...' is not assignable to parameter of type '{ id: string; name: string; beer: { id: string; name: string; alcool: number; type: "Ale" | "Lage...'.
  Type '{ id: string; name: string; beer: { id: string; name: string; alcool: number; type: "Malt"; color...' is not assignable to type '{ id: string; name: string; beer: { id: string; name: string; alcool: number; type: "Ale" | "Lage...'.
    Types of property 'ingredients' are incompatible.
      Type 'never[]' is not assignable to type 'IObservableArray<{ id: string; name: string; description: string; image: string; } & { readonly $...'.
        Type 'never[]' is not assignable to type 'IObservableArray<{ id: string; name: string; description: string; image: string; } & { readonly $...'.
          Property 'spliceWithArray' is missing in type 'never[]'.
```

## Questions
Is it a misunderstanding we have on `mobx-state-tree` / typescript ?
Or is it a type error into `mobx-state-tree` ?
Note that it works well with `applySnapshot` (https://github.com/fabienjuif/gni-mst/pull/3/files)

This is a compile time error, on runtime it works well: 
![image](https://user-images.githubusercontent.com/17828231/28770869-0e01626c-75e1-11e7-813e-b4a7550ecff9.png)

**Comment by mattiamanzati** [comment]
Unfortunately this is a known issue with TS. TS does'nt support different types on getting/setting properties. So it reads as IObservableArray and also expects an IObservableArray when setting, but an array is not an IObservableArray! :)
Fix is to either use applySnapshot or cast as any :)

**Comment by fabienjuif** [comment]
Thank you @mattiamanzati 👍

**Comment by fabienjuif** [comment]
@mattiamanzati we also have issues with optionals and actions. Do you know if this is the same type of issue ?
I would considerer switching back to plain JS.

**Comment by mattiamanzati** [comment]
Uhm, you mean as action parameters? There is SnapshotType :)
Can you please provide a sample of issues with optionals? :)
