### ISSUE TITLE
References to Unloaded Models

### ISSUE THREAD

**Issue by adamsanderson** [mobxjs/mobx-state-tree#280]
Hi, I'm just starting to explore MST, so I very well might be missing something obvious, but is there a way to use references with a partial tree?  

For instance, using the models form the getting started guide:

```
const Todo = types.model({
    name: types.optional(types.string, ""),
    done: types.optional(types.boolean, false),
    user: types.maybe(types.reference(types.late(() => User)))
}

const User = types.model({
    id: types.identifier(types.number),
    name: types.optional(types.string, "")
})
```

If you load your `Todo`s first, is it possible to defer referencing the `User`?  Or perhaps possibly return a null object like `{id: 0, name: "Loading..."}`?  

Given the shape and size of my data, it would simplify things greatly if I could defer loading references until they're actively used.

**Comment by mweststrate** [comment]
There is no clear cut pattern for this yet, but I think you could start with something like:

```
const Todo = types.model({
     _userId: types.string,
     get user() {
        return this.fetchUser(this._userId)
      }
}, {
    cachedUser: null // volatile state
}, {
    fetchUser(id) {
      if (this.cachedUser) return this.cachedUser
      this.fetchuserSomewhere(id).then(this.completeFetchUser)
      return null
    },
    completeFetchUser(user) {
       this.cachedUser = user
    }
})
```

A bit cumbersome, and I am pretty sure we will have first class for these patterns in the future, for example by allowing to customize the reference type, but this could be a start :)

**Comment by razetdinov** [comment]
I came up with a similar approach, but there are two downsides in it:
1. cachedUser is out of main tree and won't notify snapshot listeners.
2. if I want to track progress, I have to set up a pendingRequest volatile state in fetchUser. And now we come to a strange situation where a computed property (which is supposed to be pure) calls an action and modifies model's state.

**Comment by adamsanderson** [comment]
Thanks I'll have to ponder this a bit more.  Is the current `types` api fairly stable?  Would it make sense for me to implement a new custom type for my app that wraps this up?

Maybe once I've played with it more, I could make a pull request for a more generic solution.
