### ISSUE TITLE
<model.toJSON> Prompt error in vscode.

### ISSUE THREAD

**Issue by FishOrBear** [mobxjs/mobx-state-tree#283]
The code is:

```
const Data = mst.types.model(
    "Data",
    {
        n: 1
    },
    {

    }
)

let d = Data.create();
console.log(d.toJSON()); //message: 'Property 'toJSON' does not exist on type
```

**Comment by mattiamanzati** [comment]
I assume the error is a TypeScript error right? :)

**Comment by rafales** [comment]
`toJSON` is only for debugging (it's there to help you when you are working from devtools console). use `getSnapshot()` instead. More info:

https://github.com/mobxjs/mobx-state-tree/blob/master/README.md#tojson-for-debugging
https://github.com/mobxjs/mobx-state-tree/blob/master/README.md#snapshots

**Comment by FishOrBear** [comment]
@mattiamanzati  
Yes, there is no error in vscode that defines d.ts

**Comment by FishOrBear** [comment]
@rafales  thank you
