### ISSUE TITLE
npm run build-docs completely overrides API.md

### ISSUE THREAD

**Issue by elektronik2k5** [mobxjs/mobx-state-tree#285]
I want to fix the various quirks in the generated docs ([like the double `javascript javascript`](https://github.com/mobxjs/mobx-state-tree/blame/master/API.md#L19])), so I checked out master and ran `npm i && npm run build-docs`. The result is on my fork: https://github.com/mobxjs/mobx-state-tree/compare/master...elektronik2k5:feature/fix-docs?expand=1

The diff doesn't make any sense :(. Has `API.md` been updated manually or did `build-docs` break? I lack the required knowledge of `documentation.js` to troubleshoot in order to do these small fixes.

@mweststrate please help me fix the docs :)

**Comment by mweststrate** [comment]
What happens if you use yarn install ?

**Comment by elektronik2k5** [comment]
Well I didn't try yarn, since my current default is node 8 / npm 5. But I also don't see how it can be related. Everything works, just the result is a huge diff. I'll try yarn tomorrow just to rule it out though.
