### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by mkozhukharenko** [mobxjs/mobx-state-tree#29]
It seems that `mobx-state-tree` is a way behind the pure Mobx + mobx-react in the terms of performance.

100000 to-do list example shows next results:
![image](https://cloud.githubusercontent.com/assets/9365923/21753309/65f7492a-d5f3-11e6-9d2f-ea82877224ce.png)
see [this slides](http://www.slideshare.net/fwdays/treasure-hunt-in-the-land-of-reactive-frameworks) for more info

How the Performance can be improved? Any ideas?

**Comment by mattiamanzati** [comment]
Mobx state tree is not production ready yet as said in the readme. Lots of API and functions are being designed right now, and lots of performance improvements are planned, so the comparison is unfair right now! :)
Also it provides out of the box more functionalities than other state management libraries, so it involves obviusly a cost! :)

**Comment by mweststrate** [comment]
Performance should be improved signficantly in 0.3.2. @A-gambit could you verify that? (Probably still will be the worst of all though, it is not really optimized yet, and anyhow has more overhead) :)

**Comment by mweststrate** [comment]
closing, as most urgent issues have been addressed in #87.
