### ISSUE TITLE
A question about the meaning of the term

### ISSUE THREAD

**Issue by Eclatant** [mobxjs/mobx-state-tree#291]
`Opinionated, transactional, MobX powered state container combining the best features of the immutable and mutable world for an optimal DX`

What does DX mean?

---

https://github.com/mobxjs/mobx-state-tree/blob/master/API.md#typesarray

What does S and T mean in IType, S and T?

**Comment by mattiamanzati** [comment]
DX stands for Developer Experience, S is for SnapshotType, T is the Real instance type :)
