### ISSUE TITLE
Generator example

### ISSUE THREAD

**Issue by OverseePublic** [mobxjs/mobx-state-tree#296]
Hi, the generator example here. My results are different.
https://github.com/mobxjs/mobx-state-tree/blob/master/docs/async-actions.md#asynchronous-actions-and-middleware

    * sendRequest() {
      try {
        yield window.fetch(url);
      } catch (err) {
        return;
      }
    }

if I do store.sendRequest().then(res => console.log(res))
Then I get a.then is not a function which is different than what's in example.
What am I missing

**Comment by mattiamanzati** [comment]
Are you transpiling your code? If so #279 is being it, and we are working on it with a new syntax #273 !

**Comment by mattiamanzati** [comment]
version 0.10 is out which introduces a new model declaration syntax (checkout the codemod to migrate) and a new async API that fixes this issue.
