### ISSUE TITLE
Make utilities less selfish 

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#298]
Since actions / processes will save an action context soon, many api calls could infer the `self` from that, like getEnv, addDisposer, etc etc

**Comment by mattiamanzati** [comment]
Uhm, I don't think so, what kind of view functions you were thinking about?

**Comment by mattiamanzati** [comment]
Oh, I see. Yeah, makes sense for consistency.

**Comment by mweststrate** [comment]
Closing, as it will introduce probably just more magic
