### ISSUE TITLE
Support for unstructured nested MobX observable objects

### ISSUE THREAD

**Issue by sanketsahusoft** [mobxjs/mobx-state-tree#299]
Thanks a lot for this library! [We](http://GeekyAnts.com) are considering to use `mobx-state-tree` for a massive project.

This is perfect for us. Though, I would like to hear your thoughts on this use case. Consider a part of the sub-tree is being received from a third-party library which is an instance of a custom ES6 class.

In the following example, the `ast` property is actually an instance of [Node class from Babel's Babylon parser](https://github.com/babel/babylon/blob/master/ast/spec.md#node-objects)

```
const Store = types.model("Store", {
    appState: types.array(AppState),
    ast: Node   <---
})
```

How can MST handle this if I would like to use all the goodness of it?

We are using MobX at the moment where we convert the Node to plain JS and then compose it as an observable object, which works well but we don't get snapshot and immutability of MST in that case.

**Comment by sanketsahusoft** [comment]
Also, I can contribute and send you a pull-request for the same.

I would appreciate if you can let me know the approach if it is not available at the moment.

**Comment by mattiamanzati** [comment]
If your node is a plain serializable object/value, you can use types.frozen indeed :) We discussed about types.reference with custom getter and setter function that would allow to store as serializable value, but read and write as Node class instance, check it out in the open issues :)

**Comment by sanketsahusoft** [comment]
Woah! Thanks a ton! That should work!

Loads of love to you, Michel and the Mendix team!

- from the entire team at GeekyAnts

**Comment by sanketsahusoft** [comment]
A bit of more clarification would help, so re-opening:

Consider I want to track this MobX observable object within MST for redo / undo / immutability.

```
var myData = observable({
    first: {
        second: {
            third: "Value"
        }
    }
});
```

How can we do it?

**Comment by mattiamanzati** [comment]
Can you create that observable from MST or its already being created externally and you want to use it in MST?

**Comment by sanketsahusoft** [comment]
Thanks for the help. I solved it. It was an external observable object from MobX. It works fine as a frozen element for now.
