### ISSUE TITLE
Support for Deferred IDs?

### ISSUE THREAD

**Issue by adamsanderson** [mobxjs/mobx-state-tree#301]
We've been working on building up some stores for dealing with our API.  Ideally we would use the same models to build a pending or temporary object and then post it to the server, but some values must come from the server, like the ID of the newly created model.  

My first approach was to use `types.maybe(type.indentifier)` and set the ID with the result from the server.  Unfortunately this raises an exception.  I think preventing an object from changing its ID makes sense when an ID is present, but perhaps not so much when it's nullable.

Would you be open to a pull request to change that, or is there a better pattern or approach we should look into?

**Comment by adamsanderson** [comment]
... or would it make more sense to find the model's path and replace it with a newly created model?

**Comment by mattiamanzati** [comment]
Please see #159 
I'd recommend to have a separate field (non-identifier) for the remote id.
You can then user preprocesssnapshot to auto-fill the identifier field from the remote id field if present.

**Comment by razetdinov** [comment]
It seems that calculating object's identifier in its preProcessSnapshot won't work. For some (performance?) reason reconciliation doesn't run preProcessSnapshot before comparing identifiers. Moving the calculation to object's parent preProcessSnapshot works as expected.

**Comment by livfwd** [comment]
@adamsanderson if you don't mind me asking, what was the solution your team ended up using for this?
