### ISSUE TITLE
Introduce `invariant`

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#302]
requires #298, roughtly:

```javascript
function invariant(node?, guard: () => vool, message) {
   node |= getSelf()
   addDisposer(node, reaction(() => !guard(), throw message)
}

const Todo = types
  .model({ done: true })
  .actions(self => {
     invariant(() => self.done === false, "Todo's should never be completed!")

      return  {
        toggle() { this.done != this.done)
      }
  })

Todo.create().toggle() // throws invariant
```

**Comment by mattiamanzati** [comment]
It is basically a way to make the node throw if an illegal state is encountered, right?

**Comment by mweststrate** [comment]
no, it is really an invariant, not just create, but if it is in any future
brought into an inconsistent state, it will throw

Op do 17 aug. 2017 om 12:56 schreef Mattia Manzati <notifications@github.com

**Comment by mweststrate** [comment]
eh sorry, so yes. Misread

Op do 17 aug. 2017 om 13:04 schreef Michel Weststrate <mweststrate@gmail.com

**Comment by mattiamanzati** [comment]
Nice! :)

**Comment by xaviergonz** [comment]
Wouldn't that be an assertion?

**Comment by farwayer** [comment]
It can be usefull. IMO invariant should be called only if accesed props changed. For ex. for `done` but not for `title` change.

**Comment by mweststrate** [comment]
Closing for now. It's nice, but doesn't really something needed in the core
