### ISSUE TITLE
Error installing mobx-state-tree 0.10

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx-state-tree#305]
npm i mobx-state-tree@latest

npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules\mobx-state-tree\codemod" as it does not contain a package.json file.

Note that I currently have mobx-state-tree 0.9.5 installed

**Comment by mattiamanzati** [comment]
Yeah, was my fault! Sorry, we are fixing it!

git blame --myself :P

**Comment by xaviergonz** [comment]
No worries :)

**Comment by xaviergonz** [comment]
Works now :D
