### ISSUE TITLE
New syntax for types.compose ?

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx-state-tree#307]
What's the new syntax for types.compose?

The docs say

types.compose(name?, baseType, props, volatileState?, actions?), creates a new model type by taking an existing type and introducing additional properties, state and actions

But I guess that's not valid anymore?

**Comment by mattiamanzati** [comment]
Compose now accepts a list of types to compose.
If you have the actions/views/properties to add, you can just call .actions/views/props over the old type and a new type with that props/views/actions added will be created! :)

**Comment by xaviergonz** [comment]
Ah cool! how can I rename the new type based on the old type now?
e.g. I have an ImmutablePoint type with just x,y properties and then a MutablePoint type based on the first one that just add actions over it, but I'd like it to also get a new name.

**Comment by xaviergonz** [comment]
nevermind, just found about .named :)

**Comment by xaviergonz** [comment]
https://github.com/mobxjs/mobx-state-tree/pull/308

**Comment by mattiamanzati** [comment]
Just use ".named('MutablePoint')"! :)
