### ISSUE TITLE
Inferred type of getSnapshot

### ISSUE THREAD

**Issue by djres88** [mobxjs/mobx-state-tree#310]
Working with the latest mst (0.10.0) and liking it a lot, but we're experiencing some trouble with inferring the return type of getSnapshot, specifically when the model is instantiated in another scope. Say we have a model:

```
export const MyModel = types
    .model({ testing: types.string})
```

If we create an instance and get a snapshot in the same scope, it's able to infer that getSnapshot returns an object that includes the property "testing":

```
const myInstance = MyModel.create({ testing: "1,2,3" });
const mySnapshot = getSnapshot(myInstance).testing //ok --testing is a known property
```

However, if we're creating/assigning the instance at a later time (for example, in tests):

```
describe("test", function() {
  let myInstance: typeof MyModel.Type
  before(function() {
    myInstance = MyModel.create({ testing: "1,2,3" });
  })

  it("ts compile error", function() {
    const mySnapshot = getSnapshot(myInstance).testing //not ok -- inferred type of mySnapshot is {}
  })
});
```
There's an easy solution, ie by explicitly telling it the return type (`getSnapshot<typeof MyModel.Type>...`), but I'd assumed it would be able to infer the type in this case.

**Comment by djres88** [comment]
Found it. ISnapshottable<typeof MyModel.Type>;

**Comment by mattiamanzati** [comment]
Each model has two properties: Type and SnapshotType; due to TS lack of mapped conditional type we can't do much and always infer correctly, waiting for #117 :)

**Comment by djres88** [comment]
Sounds great, will keep an eye out
