### ISSUE TITLE
types.immutable idea

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx-state-tree#311]
so far I'm finding myself writing stuff like this to have both immutable and mutable versions of a type

```js
import { types } from 'mobx-state-tree';

export const Point = types.model(
  'Point',
  {
    x: types.number,
    y: types.number,
  });

export const MutablePoint = Point.named('MutablePoint')
  .actions((self) => (
  {
    setX(val: number) {
      self.x = val;
    },
    setY(val: number) {
      self.y = val;
    },
  }));
```

would it be possible to have a ```types.immutable(name?: string, type)``` that would basically strip all actions from the type and sub-types? (or at the very least throw an exception if calling an action is attempted)

**Comment by mattiamanzati** [comment]
Yep, that was discussed, #181 will track progress of that :)
Closing as duplicate, feel free to add your suggestions there! :)
