### ISSUE TITLE
Support for decorators?

### ISSUE THREAD

**Issue by mihe** [mobxjs/mobx-state-tree#312]
Are there any plans to support specifying models/views/actions with the help of decorators? I'm a big fan of [Serializr](https://github.com/mobxjs/serializr) and the decorators there made things a lot more idiomatic when using it together with TypeScript. Right now with all the factory patterns there's no way for views and actions to infer the type of 'self', meaning there's a lot of 'any' types going on everywhere.

**Comment by mattiamanzati** [comment]
There isnt any planned support for class as described in #3 
Uhm, can you please share an example of an usage case where the self type is'nt inferred?
It's strange because the self change were introduced to support better typings with TypeScript :)

**Comment by mihe** [comment]
So it seems there was a problem with my project not picking up the typings for mobx-state-tree for some reason, which resulted in everything becoming 'any'. The example projects works just fine and infers everything from `.model(...)` correctly as you said.

**Comment by mattiamanzati** [comment]
Glad to hear that! :)

**Comment by farwayer** [comment]
Hi! I just released the [mst-decorators](https://www.npmjs.com/package/mst-decorators) library to define class-based models. I used this library for 1.5 years for dozens of projects but it may still contain some bugs. And there is no TS defs yet. Feel free to open issues/PRs.

Some features:
- simple syntax without need to use extra helpers etc, just decorators
- es6 extending
- access to instance via `this`
- `@view`, `@action`, `@flow`, `@volatile` decorators
- model class is decorator so it can be used in another model (`@Location`)
- late definition for recursive models (`@late(() => ref(Category)) topCategory`)
- `preProcessSnapshot`/`postProcessSnapshot` as static class methods
- can specify `onPatch`/`onSnapshot`/`onAction` just in class
- lifecycle hook actions, composing and `getEnv()` works as well
- several extra decorators: `@jsonDate`, `@setter`
- result of decorator function is decorator. Feel power in constructing types!
```js
@model class User {}
const Author = maybe(ref(User))

@model class Message {
  @Author author
}
```
Several examples:
```js
import {
  model, view, action, flow, ref, bool, array, map, maybe, id, str, jsonDate,
} from 'mst-decorators'

@model class BaseUser {
  @id id
  @str username
  @str password
}

@model class User extends BaseUser {
  @maybe(str) phone
  @maybe(str) firstName
  @maybe(str) lastName
  
  @view get fullName() {
    if (!this.firstName && !this.lastName) return
    if (!this.lastName) return this.firstName
    if (!this.firstName) return this.lastName
    return `${this.firstName} ${this.lastName}`
  }

  @action setPhone(phone) {
    this.phone = phone
  }
}

@model class Location {
  @num long
  @num lat
}

@model class Message {
  @id id
  @ref(User) sender
  @str text
  @jsonDate date
  @bool unread
  @Location location

  static preProcessSnapshot(snap) {
    //...
  }
  static postProcessSnapshot(snap) {
    //...
  }
  
  onPatch(patch, reversePatch) {
    //...
  }
  onSnapshot(snapshot) {
    //...
  }
  onAction(call) {
    //...
  }
}

@model class Chat {
  @id id
  @array(Message) messages
  @map(User) users

  @action afterCreate() {
    this.fetchMessages()
  }

  @flow fetchMessages = function* () {
    this.messages = yield Api.fetchMessages()
  }
}

const chat = Chat.create({
  id: '1',
})
```
