### ISSUE TITLE
New syntax for model is awesome.But breaking change is unfriendly

### ISSUE THREAD

**Issue by homura** [mobxjs/mobx-state-tree#314]
0.10 has new syntax for creating model. 
Could MST release a version to make migration from 0.9.x smoothly?
The version support new syntax for model but warning for old syntax.

**Comment by NgoKnows** [comment]
You should be able to use the code mod https://github.com/mobxjs/mobx-state-tree/blob/master/changelog.md

**Comment by mattiamanzati** [comment]
We opted out to provided a codemod; it covers 90% of the cases; on a codebase of about 2300 loc it took about 5 minutes to convert, about 400 lines changed, about 20 changed manually :)
