### ISSUE TITLE
Readonly property change not allowed in strict mode

### ISSUE THREAD

**Issue by offerijns** [mobxjs/mobx-state-tree#316]
I recently set up mobx-state-tree in a React web application, which worked perfectly. However, I just tried to use the same state model in a React Native application and it does not work anymore. I keep getting the following error:

> Attempting to change value of a readonly property

The stacktrace ends on this line: https://github.com/mobxjs/mobx-state-tree/blob/4b13f0557e41259582c55943b9d73559e0fa4826/src/types/complex-types/object.ts#L104

The line it refers to seems to have been added in the last major version (0.10.0)

Now, it seems that this error is only thrown when Javascript is compiled in strict mode, which is the case for the RN app I'm working on. .

Any thoughts whether or not this is a bug in mobx-state-tree, or an implementation error on my side?

**Comment by offerijns** [comment]
And for the sake of being complete, here is the code where the error occurs, on the second line:

```
export const RootStore = types
    .model("RootStore", {
        // view: types.optional(ViewStore, {})
    })
    .views(self => ({
        get fetch() {
            return getEnv(self).fetch
        },
        get alert() {
            return getEnv(self).alert
        }
    }))
    .actions(self => ({
        afterCreate() {
            // self.itemStore.loadItems()
        }
    }))
```

(I removed/commented many lines, to see whether that had any effect)

**Comment by mweststrate** [comment]
Can you try if something like this does throw an error in RN with strict mode? It might be an issue in the JS engine (if so we can conditionally disable, it is just for debugging purposes):

```javascript
 Object.defineProperty(function() {}, "name", {
            value: "test",
            writable: 
})
```

**Comment by offerijns** [comment]
That particular code still throws the error, but the code from #319 does fix it! Thanks for the quick turn-around on those modifications.
