### ISSUE TITLE
Documentation typo ?

### ISSUE THREAD

**Issue by the-noob** [mobxjs/mobx-state-tree#323]
[Getting started - creating our first model](https://github.com/mobxjs/mobx-state-tree/blob/master/docs/getting-started.md#creating-our-first-model), second paragraph, 'automatically generate all those **bounties**' is that a typo for __boundries__ ?

**Comment by mattiamanzati** [comment]
I am not a naive english user, but should be a synonym for this https://en.wikipedia.org/wiki/Bounty_(reward)

**Comment by the-noob** [comment]
Neither am I but I don't understand the sense of using **bounty** in that context ? 
The sentence continues with __and help us avoiding silly mistakes, like putting strings in price fields or booleans where an array is expected__ which suggests an enforcement, a **boundary** (to me).

Maybe I'm missing something, what 'goodies' are we talking about that MST generates ?

**Comment by mattruby** [comment]
It should be boundaries.

**Comment by mattiamanzati** [comment]
Oh, right, sorry was referring to another line! :)

**Comment by the-noob** [comment]
Can create a PR if you like, just wanted to make sure I'm not missing anything first :)

**Comment by mattiamanzati** [comment]
Thanks for your PR! :)
