### ISSUE TITLE
Question about new volatile state syntax

### ISSUE THREAD

**Issue by evanblack** [mobxjs/mobx-state-tree#325]
We have been using volatile state for any props on the object that I didn't want to be serialized when snapshotting. Now, it seems the preferred usage is to create private variables inside the views/actions closures, but what if I still want access to prop values on the object via `obj.someVolatileProp` instead of just access within actions?

Currently doing it this way, which works, but just doesn't feel right:
```
.actions(self => {
  self.someVolatileProp = ''
  self.someOtherVolatileProp = false
  return {}
})
```

**Comment by mweststrate** [comment]
use `let someVolatileProp = ''` instead

Op di 22 aug. 2017 om 15:51 schreef Evan Black <notifications@github.com>:

**Comment by evanblack** [comment]
And that would still be accessible via `obj.someVolatileProp` outside of the model?

**Comment by mattiamanzati** [comment]
@evanblack Nope, it won't. Properties are the contract to access data from the outside, volatile is mostly internal state :)

**Comment by evanblack** [comment]
Hmmm. So there's no support for my use-case any more? I don't really want to serialize this stuff and was really happy with volatile state before...

**Comment by mattiamanzati** [comment]
Uhm, can you please re-share your use case?
The issue with that is that exporting it really breaks time travelling, if there is really no escape way we can figure this out how to solve it :)

**Comment by evanblack** [comment]
Here is my old model definition. We don't really need to serialize the volatile state here because it's all based off the `string` prop. But other areas of our app(s) access those props from the object.

```
const model = types.model('Expression', {
  Type: 'Expression',
  objectId: types.identifier(),
  string: types.string
}, {
  fn: null,
  compiled: false,
  compiledString: '',
  compileError: '',
  valid: false,
  validationError: ''
}, {
  afterCreate() {
    // This is a legacy/3rd-party function that basically sets the value of  
    // fn, compiled, compiledString, compileError, valid, and validationError
    // based off of this.string
    Expression.compile(this)
  }
})
```

**Comment by evanblack** [comment]
Here's another example where we're keeping track of event handlers in volatile state of our objects.
```
const model = types.model('Button', {
  Type: 'Button',
  objectId: types.identifier(),
  name: types.string,
  title:    types.string,
  disabled: types.boolean,
  text: types.string,
  ...Layerable,
  ...Fill,
  ...Stroke,
  ...Typography,
  ...Shadow,
  ...Rectangle,
  ...Visible,
  ...Transformable,
  ...UI
}, {
  // This array is accessed and has functions added to it at runtime
  // and so obviously can't/shouldn't be serialized.
  onClick: () => []
}, {
  ...assetActions
})
```

**Comment by mattiamanzati** [comment]
Ok, I thought this out.
Honestly I am not a fan of volatile state being readable from outside, but I see that's handy and some patterns would be hard without it :)
So here's my proposal, if @mweststrate agreeds. What about adding a "init" method on the model type which accepts a self => newSelf function?
E.g.
```
const model = types.model('Expression', {
  Type: 'Expression',
  objectId: types.identifier(),
  string: types.string
}).init(self => Object.assign(self, {
  fn: null,
  compiled: false,
  compiledString: '',
  compileError: '',
  valid: false,
  validationError: ''
}).actions(self => ({
  afterCreate() {
    // This is a legacy/3rd-party function that basically sets the value of  
    // fn, compiled, compiledString, compileError, valid, and validationError
    // based off of this.string
    Expression.compile(this)
  }
}))
```
Not sure about the naming, but the basic gist is that it will take the current "self" type and replace it with the returning one. Signature will look like .init<J extends T>((self: T) => J).
In this method you will be able to declare state-like behaviours, and get them typed correctly from outside.
What do you think @evanblack ? :)

**Comment by evanblack** [comment]
It looks good to me! Similar enough to my workaround, but having a more formal way of doing it is obviously much better. I hate to suggest unwanted or unnecessary  features, but I don't see a lot of other options for props/state you don't want to serialize. Thanks for looking at it! Love MST!

**Comment by mattiamanzati** [comment]
Yeah, the actual problem is'nt unwanted props in serialization, because you could easily use post/preProcessSnapshot to remove them, but mainly the unserializable attribute (the function) being read/written :)

**Comment by mweststrate** [comment]
I kinda dislike exposing volatile state to the outside world. It feels we losing some future flexibility and might raise questions like "why doesn't this emit a patch". Why not:

```
const model = types.model('Expression', {
  Type: 'Expression',
  objectId: types.identifier(),
  string: types.string
}).actions(self => ({
  let compiledString: ""
  return {
     setCompiledString(v) {
        compiledString = v
     },
     getCompiledString() {
         return compiledString
     }
  }
})
```

Or slightly better: allow a `get` /`set` part to be defined in the actions section. It keeps the external api the same, but semantically it is more self-explanatory how this behaves with regards to reconciliation, cloning etc (obviously the volatile state will be lost, in contrast to confusingly it will be lost)

```javascript
actions(self => ({
  let compiledString: ""
  return {
     set compiledString(v) {
        compiledString = v
     },
     get compiledString() {
         return compiledString
     }
  }
})
```

**Comment by evanblack** [comment]
I think that 2nd option there would work for me. I just need a way for the object model to have an observable prop that is not serialized and is not snapshotted/tracked. Maybe I shouldn't have been using volatile state for this before, but it worked perfectly. Seems to me like this would be a common scenario.

Another use case would be if I'm dragging an object (let's say a box in the boxes example), and only want the change in position snapshotted/tracked when I'm finished dragging. I could store an `offset` while dragging as an observable in the view component, but what if I have multiple views of that same object?

**Comment by stgolem** [comment]
Another approach is to have explicit private builder:

```
const model = types.model('Expression', {
  Type: 'Expression',
  objectId: types.identifier(),
  string: types.string
}).private(self => ({
  return {
    compiledString: '',
    onCompilation: EventEmitter
  }
})
```

So that in further usages we can use it like:

```
const expr = Expression.create();
expr.private.compiledString = 'xyz';
expr.private.onCompilation.add(myOnCompileFunc);
```

and similarly use it in actions as `self.private`.

Or even we can name it as we like `private`, `volatile`, `extra`, you name it.

**Comment by luisherranz** [comment]
What about a volatile type? Something like:

```javascript
  compiledString: types.volatile(""),
```

**Comment by stgolem** [comment]
Currently i have done workaround using `.views`, with this approach:

```js
  .views(self => {
    let selfComponent;
    return {
      get Props() {
        return selfComponent.props;
      },
      setupViewComponent(cmp) {
        if (selfComponent) {
          throw `Cannot setup twice. Already defined component = ${selfComponent}`;
        }
        selfComponent = cmp;
      }
    };
  })
```

Works fine. And no extra actions needed.
For now the only downside, is that i have to hide `setupViewComponent` from public type definition.

**Comment by ticruz38** [comment]
```
let compiledString: ""
  return {
     setCompiledString(v) {
        compiledString = v
     },
     getCompiledString() {
         return compiledString
     }
  }
```
this seems like a good option to define volatile state that way, 
maybe we should define a decorator that may be used inside actions(self => or extends(self => functions and would wrap the same implementation as it is done with @observable in mobx

**Comment by mattiamanzati** [comment]
1.2.0 introduced new .volatile syntax to add volatile properties
