### ISSUE TITLE
Dynamically append/amend types

### ISSUE THREAD

**Issue by s-panferov** [mobxjs/mobx-state-tree#326]
Hello. I have some dynamically-loaded parts of my codebase, and because of that, I cannot build the entire store model at startup.

Is there any way to append properties to existed types after they are created?

Example:

```ts
const Document = types.model('Document', {})

// Only document type is known at startup
const Block = types.union(Document)

import('./other').then(otherType => {
  Block.append(otherType) // ??
})
```

**Comment by mattiamanzati** [comment]
There is no included solution yet, please see https://github.com/mobxjs/mobx-state-tree/pull/247 for proposal and please give feedback on what do you expect to be able to do there :)
If you are injecting your store using mobx-react Provider, you could btw achieve this. Basically use types.frozen as placeholder type until the type is actually loaded, trigger the type loading, and one you have loaded it, replace the store definition with a new one with the loaded types and re-create the store on root using NewStoreType.create(getSnapshot(oldStoreInstance)).
Yeah, sounds difficult, but we will work on that soon :)

**Comment by s-panferov** [comment]
@mattiamanzati sorry, haven't seen the PR. Ok, thanks, moving to #247

**Comment by mattiamanzati** [comment]
No problem! :)

**Comment by ThaJay** [comment]
I would like to migrate my custom orm solution to mst for our react-native app. We don't use typescript and we dynamically load data from our rest api. I do not want to document every detail of the data in our code. I hoped it would be as easy as starting with an empty model like so https://codesandbox.io/s/kkw1o3ory7 and then define actions on it. but mst only seems to accept entries that are defined on the model.

I would love to use this for the observable data, actions and patches. My current solution is not observable (I have to keep a version number per collection to decide what to rerender) but I do have actions and patches. It would be awesome if I could throw away all that code and just use a simple api.
