### ISSUE TITLE
Accept self-function in .props

### ISSUE THREAD

**Issue by luisherranz** [mobxjs/mobx-state-tree#329]
Congrats on finally getting rid of `this` with an elegant API! I also love the dependency injector :)

But I'd like to be able to pass a *self-function* to props as well as an object. That would allow using injection on props too. And maybe other useful things like deleting props.

```javascript
const TodoStore = types.model('TodoStore', self => {
  const { models, libs } = getEnv(self); 
  return {
    todos: types.array(models.Todo), // Inject custom models
    id: types.identifier(types.optional(types.string, libs.generateCustomId())), // Inject libs
    loaded: false,
  };
});
// or delete props later
const CustomTodoStore = TodoStore.props(self => {
  delete self.loaded;
  return self;
};
```

What do you think?

**Comment by alexvcasillas** [comment]
```
const TodoStore = types.model('TodoStore', self => {
  const { models, libs } = getEnv(self); 
  return {
    todos: types.array(models.Todo), // Inject custom models
    id: types.optional(types.identifier(types.string, () =>libs.generateCustomId())), // Inject libs
    loaded: false,
  };
});
// or delete props later
const CustomTodoStore = TodoStore.props(self => {
  delete self.loaded;
  return self;
};

```

This should work : )

**Comment by mattiamanzati** [comment]
I think this makes sense, little scared of potential performance issues due to lack of performance checks we could potentially do :)

**Comment by mweststrate** [comment]
It can be a simple overload? (Maybe only supported on `.props` for simpler
base api?)

Op vr 25 aug. 2017 om 15:35 schreef Mattia Manzati <notifications@github.com

**Comment by mweststrate** [comment]
Eh wait, initializers run on instance instantiation, but props need to be
known before that (for snapshot type checking and such). In otherwords,
there is no `self` yet...


Op vr 25 aug. 2017 om 15:47 schreef Michel Weststrate <mweststrate@gmail.com

**Comment by luisherranz** [comment]
I see. What do you think? Is there an easy solution or workaround?

Maybe a new type, similar to lazy but with injections as props? Would that be possible?

```javascript
const TodoStore = types.model('TodoStore', {
  todos: types.injected(env => types.array(env.Todo),
});
```

**Comment by mattiamanzati** [comment]
> Eh wait, initializers run on instance instantiation, but props need to be
> known before that (for snapshot type checking and such). In otherwords,
> there is no `self` yet...
Yep, ideally props initializers should follow a separate step and be run before, after the empty object is create... Feels kinda weird though :/

**Comment by mweststrate** [comment]
@luisherranz yeah I think that could be expressed indeed, by leveraging `types.late`. I think typechecking will be pretty hard though. Curious about real life use cases for this

**Comment by luisherranz** [comment]
> Curious about real life use cases for this

In our case, we are building an extensible app made with plugins. Each activated plugin can export their own model to build the final store. But each plugin can also export other reusable models and those would get injected using the environment. It's not very important, we have plenty of ways to inject those. I also thought using the same self-function for `.props`, `.actions` and `.views` made sense and it may have other uses like deleting props :)

Anyway, as I said, it's not very important. I'll close this issue for now.
