### ISSUE TITLE
views initializer should return a plain object containing views

### ISSUE THREAD

**Issue by aretecode** [mobxjs/mobx-state-tree#333]
this breaks the ability to do this, for what reason??

```js
.views(self => new class {})
```

**Comment by mweststrate** [comment]
what would returning a class there mean? Views get mixed in so there is no
real semantic meaning of returning a class over there. You will not ever
encounter an instance of it. Should members on prototype be exposed as
well? And what about statics? What would the effect of `.views(self => new
class A{}).views(self => new class B{})` be, etc?

Op vr 25 aug. 2017 om 11:51 schreef James <notifications@github.com>:

**Comment by mweststrate** [comment]
Closed for now, based on gitter discussion.
