### ISSUE TITLE
make types.refinement accept an error message to show during validation

### ISSUE THREAD

**Issue by mattiamanzati** [mobxjs/mobx-state-tree#334]
To provide custom validation messages when predicate is not passed

**Comment by mattiamanzati** [comment]
It's already implemented! :)

**Comment by kresli** [comment]
amazing! Thank you!

**Comment by mattiamanzati** [comment]
https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mobx-state-tree/test/refinement.ts#L32 For an example
