### ISSUE TITLE
class like syntax?

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx-state-tree#338]
I bet you already though about it, but just in case :) did you think about a class alike syntax to make models? Something like this:

example 1
```js
@model('Todo') // maybe the name could be optional and taken from the class itself
class Todo {
  // a) basic support
  @prop(types.string)
  title: string;

  // b) with maybe an advanced syntax support
  @prop // the parameter is optional if we use design:type decorator metadata to find it
  title = 'hello world'; // a default value means it is optional, just create a new empty class with the default constructor to find out the default values

  // c) or maybe something like this
  @prop
  title: Optional<string> = optional('hello world')

  @action
  toggle() {
    this.done = !this.done;
  }
}

@model('Store')
class Store {
  @prop(types.array(Todo))
  todos: Todo[]
}

const store = fromSnapshot(Store, {...});

store.todos[0].toggle();
```

example 2
```js
@model('TodoStore')
class TodoStore {
  @prop(types.boolean) // or empty to auto detect
  loaded: boolean;

  @prop(types.string)
  endpoint = 'http://localhost';

  @prop(types.array(Todo))
  todos: Todo[]
. 
  @prop(types.reference(Todo))
  selectedTodo: Reference<Todo> // not sure if reference would be required, probably could be used for type auto detection though

  @computed / @view
  get completedTodos() { ... }

  @action
  addTodo(title) {
    this.todos.push({ ... });
  }
}
```

how to extend types? just use extends I guess

**Comment by aretecode** [comment]
I played with this same syntax but found it was a little longer, and came up with a hybrid that I'll push sometime

**Comment by chengjianhua** [comment]
I prefer the class syntax personally too ~

@aretecode as you said, it'll come up some day in future ?

**Comment by aretecode** [comment]
@chengjianhua @xaviergonz https://github.com/aretecode/thisless example using classes AS actions and views, easy to add decorators to do similar for action selectors, I have a different pkg for types

**Comment by mweststrate** [comment]
For now we want to stick to "one way to do things" as much as possible. Also by not supporting classes we have a smaller semantic scope as there are no questions about the meaning or interpretation of:

* this
* prototypes
* inherited members
* enumerable members
* non-enumerable members
* getters
* static members

The current approach keeps the MST code base much simpler, allowing us to evolve more quickly, as we can adhere to two much more simple rules:

* `this` is always `null`
* we only consider own, enumerable properties

So although I can see why people would value using classes, for me it is a no, at least in this stage of the project. I think adding these possibilities through an external package like done by @aretecode makes perfect sense, and makes it also easier to do target specific transformations (e.g. things that only work in ES6, or with TS, with Babel etc).

@aretecode feel free to mention the package in the `Tips` section of the readme :)

**Comment by farwayer** [comment]
Hi! I just released the [mst-decorators](https://www.npmjs.com/package/mst-decorators) library to define class-based models. I used this library for 1.5 years for dozens of projects but it may still contain some bugs. And there is no TS defs yet. Feel free to open issues/PRs.

Some features:
- simple syntax without need to use extra helpers etc, just decorators
- es6 extending
- access to instance via `this`
- `@view`, `@action`, `@flow`, `@volatile` decorators
- model class is decorator so it can be used in another model (`@Location`)
- late definition for recursive models (`@late(() => ref(Category)) topCategory`)
- `preProcessSnapshot`/`postProcessSnapshot` as static class methods
- can specify `onPatch`/`onSnapshot`/`onAction` just in class
- lifecycle hook actions, composing and `getEnv()` works as well
- several extra decorators: `@jsonDate`, `@setter`
- result of decorator function is decorator. Feel power in constructing types!
```js
@model class User {}
const Author = maybe(ref(User))

@model class Message {
  @Author author
}
```
Several examples:
```js
import {
  model, view, action, flow, ref, bool, array, map, maybe, id, str, jsonDate,
} from 'mst-decorators'

@model class BaseUser {
  @id id
  @str username
  @str password
}

@model class User extends BaseUser {
  @maybe(str) phone
  @maybe(str) firstName
  @maybe(str) lastName
  
  @view get fullName() {
    if (!this.firstName && !this.lastName) return
    if (!this.lastName) return this.firstName
    if (!this.firstName) return this.lastName
    return `${this.firstName} ${this.lastName}`
  }

  @action setPhone(phone) {
    this.phone = phone
  }
}

@model class Location {
  @num long
  @num lat
}

@model class Message {
  @id id
  @ref(User) sender
  @str text
  @jsonDate date
  @bool unread
  @Location location

  static preProcessSnapshot(snap) {
    //...
  }
  static postProcessSnapshot(snap) {
    //...
  }
  
  onPatch(patch, reversePatch) {
    //...
  }
  onSnapshot(snapshot) {
    //...
  }
  onAction(call) {
    //...
  }
}

@model class Chat {
  @id id
  @array(Message) messages
  @map(User) users

  @action afterCreate() {
    this.fetchMessages()
  }

  @flow fetchMessages = function* () {
    this.messages = yield Api.fetchMessages()
  }
}

const chat = Chat.create({
  id: '1',
})
```
