### ISSUE TITLE
Cannot invoke async action from a normal action

### ISSUE THREAD

**Issue by abruzzihraig** [mobxjs/mobx-state-tree#339]
**version: mobx-state-tree 0.10.2**

Hi, recently I updated the MST I used to 0.10.2, then I tried to use the new feature async action but I got an issue.

As document said, the `process` from MST will return a promise. It might be true in the demo example that you showed. However, if I tried to invoke such async action by `process` from another normal action, it won't return a promise so that I would get an error like `Cannot read property 'then' of undefined`.

The snippet like below:
```
        fetchVideoInfo: process(function* fetchVideoInfo(url: string) {
            let embeddedId: string = null;
            let thumbnailUrl: string = null;
            let provider: VideoProviders = null;

            if (self.isValidEmbeddedYoutubeUrl(url)) {
                provider = 'youtube';
                embeddedId = url.split('/').pop();
                thumbnailUrl = `https://img.youtube.com/vi/${embeddedId}/0.jpg`;
            } else if (self.isValidEmbeddedVimeoUrl(url)) {
                provider = 'vimeo';
                embeddedId = url.split('/').pop();
                thumbnailUrl = yield fetch(`http://vimeo.com/api/v2/video/${embeddedId}.json`)
                    .then(res => res.json())
                    .then(res => {
                        return (res && res[0]) ? res[0].thumbnail_large : '';
                    });
            } else {
                throw new Error(`The embedded video URL ${provider} is invalid`);
            }

            return {
                embeddedId,
                thumbnailUrl,
                provider
            };
        }),

        loadEmbeddedVideo() {
            this.fetchVideoInfo(self.embeddedUrl).then((videoInfo: VideoInfo) => {
                this.setIsEmbeddedUrlLoaded(true);
                this.setVideoInfo(videoInfo);
            });
        }
``` 

The normal action `loadEmbeddedVideo` invokes the async action `fetchVideoInfo`, but `this.fetchVideoInfo(self.embeddedUrl)` returns `undefined`. I tried to output the method `this.fetchVideoInfo` within `loadEmbeddedVideo`, then I got 
```
function () {
        return executeAction(actionName, fn, this, arguments);
}
```

So I'm guessing if I was wrong with the way I use the async action? Can't it be invoked from a normal action directly?

**Comment by mattiamanzati** [comment]
Hi! Can you please create a small codesandbox or a complete snippet to reproduce the bug? Can't get it to throw locally :)

**Comment by mweststrate** [comment]
The code looks correct to me indeed. Might relate to generator compilation
not being set up properly? (CRA and TS do it correct ootb, but when using
babel manually it might need some setup)

Op di 29 aug. 2017 om 09:11 schreef Mattia Manzati <notifications@github.com

**Comment by skellock** [comment]
I’ve had similar issues when passing parameters to `process`.  You can wrap that `process` call in another function that does accept arguments though.

**Comment by abruzzihraig** [comment]
Thanks for you guys looking at this issue. I've solved it. It is not a bug but it is definitely a trap that catches some people just like me.

As @mattiamanzati 's recommendation, I tried to create a small codesandbox with the simplified code like I posted, but it works fine like all we expected – https://codesandbox.io/s/725qxzm50j

Then I tested my broken code again and again but every time I still got the same issue. And at the meantime, I found that it is not only about async action, it occurs on each action in that returned plain object from `.actions(self => { ...actions })`. If one action is invoked in another action, its return value will disappear as `undefined`.

So I looked through the MST code the part `complex-types/object.ts` and `core/actions.ts`, then I finally figured out when the return value was lost - https://github.com/mobxjs/mobx-state-tree/blob/9d0507cb980796ff0dd7dca8830506b67b77f2e0/src/core/action.ts#L99

which means, if anyone like me wrote a middleware handler without explicitly `return` the `next(call)`, the return value in any action will lose if it is invoked in another action.
```
addMiddleware(video, (call, next) => {
    return next(call); // I didn't give it a explicit `return` so that I got this issue
});
```

I don't think it is a bug but it is quite easy to confuse people like me, and it's hard to target the problem to middleware if developers get the same issue in action scope. It would be fine if you could add a note or warning in the document for middleware users.
