### ISSUE TITLE
Updating a model using applyPatch

### ISSUE THREAD

**Issue by OverseePublic** [mobxjs/mobx-state-tree#341]
Quick question about applyPatch :)

1. Can I use this to update the model?
1. When should I not use applyPatch?
1. Let's say a model has maybeArr: types.maybe(types.array(types.string))) and maybeArr field is initialized with null. How should I update (replace) this field with new JSON from promise? Would this be an appropriate place for applyPatch?

Thanks for your time always.
Your MobX fan.

**Comment by mattiamanzati** [comment]
1. Sure :)
2. Cant think of any use case 
3. You could use applyPatch on the model that has that field with apatch that should look Like {op: Replace, path: /maybeArr, value: [1,2,3]}
