### ISSUE TITLE
TS question on new model syntax

### ISSUE THREAD

**Issue by ssured** [mobxjs/mobx-state-tree#343]
```typescript
const Example = types.model('Example', { prop: types.string }).views(self => ({
  get upperProp(): string {
    return self.prop.toUpperCase();
  },
  get twiceUpperProp(): string {
    return self.upperProp + self.upperProp;
  },
}));
```

The upper code will warn in twiceUpperProp that `self.upperProp` is not available

One solution could be to make the function external:

```typescript
const Example = types.model('Example', { prop: types.string }).views(self => ({
  get upperProp(): string {
    return self.prop.toUpperCase();
  },
  get twiceUpperProp(): string {
    return twice(self);
  },
}));

function twice(example: typeof Example.Type): string {
  return example.upperProp + example.upperProp;
}
```

Except that here `self` in `twiceUpperProp` is not of type `Example.Type`...

Any thoughts / help! Thanks!

**Comment by mattiamanzati** [comment]
Try this :)

```
const Example = types.model('Example', { prop: types.string }).views(self => {
function upperProp(){
return self.prop.toUpperCase();
}

function twiceUpperProp(){
return upperProp() + upperProp();
}
return {
  get upperProp(): string {
    return upperProp()
  },
  get twiceUpperProp(): string {
    return twiceUpperProp()
  },
}});
```

**Comment by ssured** [comment]
Thanks, that's much better!

**Comment by mweststrate** [comment]
Note that the return in the example above can be just `return { upperProp,
twiceUpperProp }`


Op wo 30 aug. 2017 om 15:18 schreef Sjoerd de Jong <notifications@github.com

**Comment by ssured** [comment]
@mweststrate: you mean the object returned by `views` does not need the ES5 `get`?

**Comment by mweststrate** [comment]
@ssured oh sorry, completely overlooked the `get` :-)

**Comment by mweststrate** [comment]
We should provide a utility `getters` which does `getters({ a, b })` => `{ get a, get b }` :-P

**Comment by ssured** [comment]
what is possible is to count the number of arguments, if 0 it's a property, if more, it's a view function.
easily done by checking `function.length`

Something along these lines (not tested)
```javascript
function getters(views) {
  return Object.keys(views).reduce((getters, propName) => {
    const fn = getters[propName];
    if (fn.length === 0) {
      Object.defineProperty(getters, propName, { get: fn });
    }
    else {
      getters[propName] = fn;
    }
    return getters;
  }, {});
}
```

**Comment by mweststrate** [comment]
Yep that could work, but it might be that people don't want computeds or keep the `()` syntax. Getting the typings right might be hard as well :).

**Comment by ssured** [comment]
thanks, nice idea but too much sugar indeed
