### ISSUE TITLE
[Question] Get one snapshot

### ISSUE THREAD

**Issue by chemitaxis** [mobxjs/mobx-state-tree#346]
Hi we are having one problem to get a snapshot, this is a question, more than a bug...

We have two models like this:

```
const ItemUI = types.model(
  'ItemUI',
  {
    id: types.identifier(),
    position: types.optional(types.frozen, { x: 0, y: 0 }),
    text: types.string,
    width: types.string,
    height: types.string,
    backgroundColor: types.string,
    selected: types.optional(types.boolean, false),
    type: types.optional(types.literal('text'), 'text')
  },
  {
    setPosition(x, y) {
      this.position = { x: x, y: y };
    },
    setSelected(selected) {
      this.selected = selected;
    }
  }
);
```

```
const ItemStoreUI = types.model(
  'ItemStoreUI',
  {
    items: types.array(ItemUI)), []),
    get selectedItems() {
      return this.items.filter(item => item.selected);
    }
  },
  {
    addItem(item) {
      this.items.push(item);
    },
    unselectAll() {
      this.items.map(item => (item.selected = false));      
    }
  }
);
```

We are listening to patchs events, 
```
const store = ItemStoreUI.create();
onPatch(store, patch => {
    console.log('Patch ocurred');
    console.log(patch);
  });
```

When we call to **action** _unselectAll_ and we have 4 items with selected value to true, the onPatch is triggered 4 times.

Can I have only one patch with all the patches together like a [transaction](https://mobx.js.org/refguide/transaction.html)? I think it could be amazing if I could get all the patches generated in an single action at once.

What do you think @mweststrate & @mattiamanzati?  😄

cc: @alexvcasillas  

Thanks!

**Comment by alexvcasillas** [comment]
I think we could create a HOF to wrap an action so it keeps tracks of all the patches that had been generated during the execution of itself, and after the action is done, we only need to return an array of patches or something like that.

Could this be affordable or considered as a possible implementation for this cases?

**Comment by mattiamanzati** [comment]
Yep, it is indeed affordable! that is a great use case for a middleware.

**Comment by alexvcasillas** [comment]
Awesome, @mattiamanzati ! I think I will try to create it for MST : )
