### ISSUE TITLE
[Question] Exporting domain models as separate package?

### ISSUE THREAD

**Issue by the-noob** [mobxjs/mobx-state-tree#350]
Hi, I've asked this on SO as I thought it is a more appropriate place but I would like to 'ping' it here, for the people that use this on a daily basis for a long time.

https://stackoverflow.com/questions/45944405/mobx-state-tree-exporting-the-model-validation/45972101#45972101

**Comment by mattiamanzati** [comment]
I definetely agree with the SO answer, closing for now :)
