### ISSUE TITLE
[Question] Whats is a correct way of accessing one part of the tree from another (or subscribe to actions)

### ISSUE THREAD

**Issue by dmitry-zaets** [mobxjs/mobx-state-tree#351]
I've searched and haven't found it in the documentation, nor in issues or stackoverflow (sorry if I've missed it).

So the case looks like this: User enters login and password, we need to perform log in, as a result, we are getting a token, and if we've got logged in successfully we need to fetch user data.

Here is an example:
```js

const AuthStore = types
  .model('AuthStore', {
    token: types.optional(types.string, ''),
    // ... other fields
  })
  .actions(self => ({
    login(login, password) {
     // .. perform log in, revice a token
      self.token = token;
    },
    // ... other acitons
  }));

const UserStore = types
  .model('UserStore', {
    userName: types.optional(types.string, ''),
    // ... other fields
  })
  .actions(self => ({
    fetchUser() {
      // ..  fetch user data, using the token,
      self.userName = userName;
    },
    // ... other acitons
  }));

const Store = types
  .model('Store', {
    auth: types.optional(authStore, {}),
    user: types.optional(UserStore, {})
  })
```

What is the proper way to access parallel levels of store nodes (from UserStore access AuthStore) or calling/subscribing to their actions actions?

Comparing to redux architecture, most likely you'll dispatch multiple actions conditionally in one action creator (also you'll have access to the whole store in the action creator).

I would be more than happy to send the PR with an update of the documentation (or the FAQ part) with the description of that type of issue (since based on redux experience, that type of question are really common) as soon as it will be clear to me.

**Comment by mattiamanzati** [comment]
You can use getParent() and getRoot to traverse your state tree. I find nice to define global functions like getAuthService(model) which are mostly like
const getAuthService = (model) => getRoot(model).services.auth
