### ISSUE TITLE
Do not throw if given environment is the same as the target one

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx-state-tree#354]
Is there any reason why I can't do something like this if the two environments passed on create are the same ones?

```js
const env = whatever;
const parent = Parent.create({}, env);
const child = Child.create({}, env);
parent.children.set('asdf', child); // exception
parent.children.set('asdf', getSnapshot(child)); // ugly workaround, but works
```

I'd understand the error if the two envs were not the same, but when they are?

**Comment by xaviergonz** [comment]
Just edited the code, it actually happened to me when using a map, I didn't try setting it as parent.child = child; (which might happen or not, I'm not sure)

**Comment by mattiamanzati** [comment]
Yeah, make it not throw if env is exaclty the same makes sense, we need to fix this check and assert that envs are different by reference :)

https://github.com/mobxjs/mobx-state-tree/blob/master/src/core/node.ts#L312

**Comment by xaviergonz** [comment]
cool, is there a way to get the env an instance was created with so I don't have to have the env all around when doing that kind of stuff?

**Comment by mattiamanzati** [comment]
Doesnt getEnv(instance) work for you? :)

**Comment by xaviergonz** [comment]
thanks, totally missed that that one could be used outside of actions and the like
