### ISSUE TITLE
model props DI

### ISSUE THREAD

**Issue by mattiamanzati** [mobxjs/mobx-state-tree#357]
This weekend I gave a quick shot at trying to implement DI for prop types in MST models.
After a quick talk with @mweststrate I realized that the simples way would be to leaverage the use of types.late to perform DI of types.
My first attempt went to change a bit the signature of the function given to late from `types.late(() => IType)` to `types.late((environement: any) => IType)`.
Checking late implementation, the type resolver predicate is called in 2 contexts: type checking and type initialization. Getting context in type initialization is pretty easy because it could be resolved either from given new environment or from parent one. For the typechecking it becomes hard, because atm environment is'nt passed along while performing typechecks.
So my first attempt went to pass the enviromnent only if available, if not, it will be undefined.
So with a sample test it was now possible to perform tasks like `todo: types.late((env) => env ? env.resolve(Todo) : Todo)` where if an env is not present (type-checking) Todo type will be resolved, if present env.resolve will point to NewTodo type which basically extends the Todo one.
It worked, but unfortunately model instance assignments were broken, because when I do self.todo = NewTodo.create() it will first call the predicate without env, so it will return Todo, and it will check if the NewTodo instance is assignable to a Todo instance. And it obviously failed, but if I used snapshot all was fine because it will correctly check against Todo (interface type) but then resolve to NewTodo (concrete type).

Now I am put into a choice between two possible fixes.
* The first one would be to simply fix how isAssignableFrom of model is implemented, and make it more a "structural" check rather then a exact type check. It would basically check if the given type (NewTodo) has all props assignable to the interface type (Todo) and if all initializers of the interface type are present in NewTodo.
This is a basic gist of how it behaves after the change:
```javascript
test("extended type should be assignable to the base one", t => {
    const Todo = types.model("Todo", {
        id: types.number,
        name: types.string
    })

    const NewTodo = Todo.props({
        done: types.boolean
    }).named("NewTodo")

    const OtherTodo = types.model("Todo", { id: types.number, name: types.string })
    const DifferentTodo = types.model("Todo", { id: types.string })
    const TodoWithAction = Todo.actions(self => ({ a: () => 1 }))

    t.is(Todo.isAssignableFrom(NewTodo), true)
    t.is(Todo.isAssignableFrom(OtherTodo), true)
    t.is(Todo.isAssignableFrom(DifferentTodo), false)

    t.is(TodoWithAction.isAssignableFrom(Todo), false)
    t.is(TodoWithAction.isAssignableFrom(NewTodo), false)
    t.is(TodoWithAction.isAssignableFrom(OtherTodo), false)
    t.is(TodoWithAction.isAssignableFrom(DifferentTodo), false)

    const ExtendedTodo = TodoWithAction.actions(self => ({ b: () => 2 }))

    t.is(TodoWithAction.isAssignableFrom(ExtendedTodo), true)
    t.is(ExtendedTodo.isAssignableFrom(TodoWithAction), false)
})
```
After some minutes I realized that this change would introduce some sort of flexibility I would'nt like,  basically because it would break time travelling. Basically how would it know, given a snapshot, know if you meant a Todo or a TodoWithAction? So I thought that maybe there was another way to fix the issue...
* The second way I thought that would fix the issues of the first one would be to pass environment also when typechecking the instance. This means a change also in the signature of lots of internal methods, like typecheck(type, value) to accept also the env and so on for isValidSnapshot, validate, is, etc... This would be nicer than the first solution because it leaves the DI layer in the environment, and becames a dev job to ensure that when time travelling it will be exactly the same as it would be when recording the time travel. This way then the late resolver is called in typecheck, it will resolve the DI type (NewTodo) instead of the interface type (Todo).

@mweststrate Would like to have your opinion on this to implement it :)

**Comment by mweststrate** [comment]
I have some doubts about some of the things mentioned above:

1. A type is more then it's props. Actions and view (implementations) s should also be the same to make two types equal. If you want to check if just the props could be used to assign stuff, `Todo.isAssignableFrom(getSnapshot(NewTodo))` will return true (unlike `Todo.isAssignableFrom(newTodo))`, which cannot be assigned without cloning first. (that is true for a snapshot of course as well, but that is a safe operation as nothing (like internal state, actions etc) will be lost in the process.

2. For me it feels that all those super dynamic types become hard to reason about. TypeScript will probably not be able to make sense of it. `typecheck` becomes unpredictable, behaving different with different environments etc? What does the fact that the types live in the environment precisely add, as they are not supposed (as you indicated) over time anyway. Isn't it simpler then to await all types first, and then instantiate them? Sorry for being pessimistic about it. This one feels like introducing a super generic / bug sensitive mechanism for a very rare use case? The second approach does feel more viable then the first

**Comment by luisherranz** [comment]
> Isn't it simpler then to await all types first, and then instantiate them?
I'm afraid I'm the cause of this issue because of https://github.com/mobxjs/mobx-state-tree/issues/329
so I want to say we can totally await for the models. I just thought it'd be nice to use the same DI method to inject models and I also thought that having the same "self-function" syntax in props made kind of sense, API-wise.

**Comment by mattiamanzati** [comment]
No problem @luisherranz , I encountered the same :)
Yeah, in the end I'll DI a function that composes the given store, so I can totally await for them all to load, or eventually reload the app if something changes! :)
