### ISSUE TITLE
[Question] Use a serializer/deserializer

### ISSUE THREAD

**Issue by DCKT** [mobxjs/mobx-state-tree#359]
Hello,

I'm quite new to mobx-state-tree and I would like to know which kind of approach I should take to use serializer/deserializer like this : one https://github.com/mobxjs/serializr

I could write some callbacks for each request call but it wouldn't be memoized. Any idea about this ? 

Thanks for your help :)

**Comment by mweststrate** [comment]
mobx-state-tree basically combines mobx and serialzr into one package. So
when using MST, there should be hardly any need to use serializr

Op ma 4 sep. 2017 om 10:49 schreef Thomas Deconinck <
notifications@github.com>:
