### ISSUE TITLE
Bug: Typings lost after preProcessSnaphot

### ISSUE THREAD

**Issue by ssured** [mobxjs/mobx-state-tree#362]
```typescript
const Test = t
  .model('Test', {
    id: t.identifier,
  })
  .preProcessSnapshot(snapshot => snapshot);  // LINE B

const test = Test.create({ id: 'test' });

console.log(test.id); // LINE A
```

Typescript will throw: `property id does not exist` on line A

If you comment line B, all izz well.

**Comment by mattiamanzati** [comment]
Uhm, on which mst version are you running on? Should be already fixed in latest one :)

**Comment by ssured** [comment]
You guys rock, it's indeed fixed. New releases are coming out so fast I didn't know I was using an old one...
