### ISSUE TITLE
Use devtools in React Native with Mobx State Tree

### ISSUE THREAD

**Issue by alexlevy0** [mobxjs/mobx-state-tree#367]
Hello,

I'm trying to use mobx-remotedev with React Native and MobX-State-Tree but I don't know how to do. 
I tried with ```export default remotedev(AppStore, { global: true, remote: true })``` in my rootStore but I get an error ```Unhandled JS Exception: Cannot read property 'create' of undefined``` cause I create the tree with ```const appStore = AppStore.create({ users: {} }, { logger: logger })``` 

Can you orient me?

Thanks for readding

**Comment by mattiamanzati** [comment]
As mobx-remotedev docs says, it expects first parameter to be either a mobx observable value or a class. MST does not use classes, so instead of passing AppStore to remotedev you need to pass appStore (the AppStore model instance).
Let me know if it works! :)

**Comment by HaveF** [comment]
@mattiamanzati 
I try to using model instance, it seems not work.

>TypeError: Cannot read property 'getDebugName' of undefined
init
```
./node_modules/mobx-remotedev/lib/spy.js:47
  44 | }
  45 | 
  46 | function init(store, config) {
> 47 |   var name = mobx.extras.getDebugName(store);
  48 |   configure(name, config);
  49 |   stores[name] = store;
  50 | 
```

**Comment by mweststrate** [comment]
Seems mobx-remoteDev is using the old Mobx 3 api's. Are you sure you have
the latest version? Otherwise best file an issue at mbox-remotedev. In MobX
4 / 5 all `extras` functions have been moved to top level

Op di 24 jul. 2018 om 05:57 schreef HaveF <notifications@github.com>:

**Comment by HaveF** [comment]
Yes, it is the newest version.  [mobx-remotedev/spy.js at master · zalmoxisus/mobx-remotedev](https://github.com/zalmoxisus/mobx-remotedev/blob/master/src/spy.js#L29)

It seems mobx-remoteDev is not maintained...

 [Mobx 4 support · Issue #32 · zalmoxisus/mobx-remotedev](https://github.com/zalmoxisus/mobx-remotedev/issues/32)
 [Upgrade compatibility to mobx 4 by SimeonC · Pull Request #33 · zalmoxisus/mobx-remotedev](https://github.com/zalmoxisus/mobx-remotedev/pull/33)
