### ISSUE TITLE
TypeError: this.type.validate is not a function

### ISSUE THREAD

**Issue by the-noob** [mobxjs/mobx-state-tree#368]
> "version": "0.10.1"

```JavaScript
const KNOWN_VERSIONS = [1];

const Screen = types.model('Screen', {
  id: types.identifier(),
  name: types.string,
  version: types.refinement(types.number, value => _.indexOf(KNOWN_VERSIONS, value) > -1),
});

Store.create({id: "4e02f304-85c1-4097-8bb1-0e8b7a7d3e85", name: "asdsa", version: 1});
```
This fails with __TypeError: this.type.validate is not a function__

The following works
>  version: types.optional(types.number, 1),

What am I missing ?
I've actually tried `  version: types.refinement(types.number, value => true)` and still fails.

**Comment by mattiamanzati** [comment]
Its throwing because in versions < 0.11 refinement type required a string as first parameter being the type name. Is fixed in latest versions.

**Comment by the-noob** [comment]
I just can't describe how happy I am when it's not my fault !
