### ISSUE TITLE
How to find node in deep nested tree

### ISSUE THREAD

**Issue by nadzic** [mobxjs/mobx-state-tree#370]
Hi,

I am just curious if MST has already function which allows you to find the deeply nested node (object inside object, even array) by id, name or whatever? I mean that you give this node (store), the id and you can then find it from the root store deeper (I know I can find by myself with recursion or whatever algorithms (DFS,BFS)).... 

That would be really useful if you are planning to use reusable components in React with MST and they are linked to the different parts of the tree.

Thanks

**Comment by mweststrate** [comment]
There are several resolve methods available. See the docs. Like resolving a
path or identifier. And otherwise you can create one using 'walk'

**Comment by nadzic** [comment]
Thank you for answer. Actually, I am not sure about your answer (sure I checked before tha available methods in the MST). 

In methods like getPath and similar, you have to always give node as parameter to get the path of the node. 

But what I want actually achieve:
-> I inject store in my component (which is root store), this component also receives prop 'wantedStore' (wanted store is store inside of root store) - maybe as string for example?
-> Then inside of root store I want to find this wantedStore regarding the string that I pass to this component.

Currently we are passing down some stores and observing them, but we have a bit complex stuff (because we have deeply nested components with atomic design) and we want to get rid of nesting and selecting stores directly in low level components regarding the passed string from parent component. 

Or what do you think is the best solution for solving that ? 

Thank you

**Comment by evoye** [comment]
@nadzic you can use the resolveIdentifier method
https://github.com/mobxjs/mobx-state-tree/blob/master/API.md#resolveidentifier

**Comment by mweststrate** [comment]
..or views  + dependency injection (environments). Many things are possible here.

Closing for inactive or until the question becomes a little more tangible
