### ISSUE TITLE
HMR not  support ?

### ISSUE THREAD

**Issue by mydearxym** [mobxjs/mobx-state-tree#372]
i am surprisely found that  hot-reload is not supported in mobx/MST world .  everytime ,even a little changes on the store ,i need  to reload the entire  page .  thats really  a big  pain in the  ass ..

is there any solutions so far  ?

**Comment by mattruby** [comment]
Try the very latest hot loader beta. Does that help?

**Comment by mydearxym** [comment]
no luck ..

i use the next.js and the hot-loader is the [latest beta version](https://github.com/zeit/next.js/blob/master/package.json#L89)

**Comment by Bnaya** [comment]
It won't work unless you make it so
you need use 
https://webpack.js.org/api/hot-module-replacement/

**Comment by mweststrate** [comment]
...which is basically as simple as shown here: https://twitter.com/mhaagens/status/911587350429491200

**Comment by mweststrate** [comment]
For future readers, here is an example to set up HMR for both React components and MST models (and also store the state in local storage, stripping that would simplify the example a bit): https://github.com/mobxjs/mobx-state-tree/blob/a0916791768637665a56bc2720ec0a081d4d148f/packages/mst-example-todomvc/src/index.js#L60

**Comment by simonbleier** [comment]
Is it possible to achieve this without passing store as a prop? (i.e exporting store variable and using directly in react components)
