### ISSUE TITLE
View results are cached ?

### ISSUE THREAD

**Issue by the-noob** [mobxjs/mobx-state-tree#374]
Not sure if I'm doing something stupid or this is a bug. Perhaps.

(L.E. I know, I know... I should push sessionStorage as a Map through environment)

I have this model
```JavaScript
export default types.model("App", {
    authenticatedUser: types.maybe(User),
  })
  .views(self => ({
    get isAuthenticated() {
      return self.currentUser !== null;
    },
    get currentUser() {
      const user = sessionStorage.getItem('authenticatedUser');
      if (user) {
        return user;
      }
      return self.authenticatedUser;
    }
  }))
  .actions(self => ({
    setAuthenticatedUser(user) {
      sessionStorage.setItem('authenticatedUser', user);
      self.authenticatedUser = user;
    },
    logout() {
      sessionStorage.removeItem('authenticatedUser');
      self.authenticatedUser = null;
    },
```
Then I have a component like 
```JavaScript
  render() {
    if (this.props.appStore.isAuthenticated) {
      return this.props.children;
    } else {
      return <Redirect to="/login"/>
    }
  }
```
Doing something like
```
store.setAuthenticatedUser({valid_user});
store.isAuthenticated === true;
store.logout();
store.isAuthenticated === true; // :(
```
Adding `console.log` everywhere shows that `isAuthenticated` only gets called once and then always returns true ?

**Comment by mattiamanzati** [comment]
Uhm, should'nt
`return self.currentUser !== null;`
be
`return self.authenticatedUser !== null;` ?

**Comment by mattiamanzati** [comment]
Not sure of what you are trying to achieve, but I'll set up the reading of the local storage in an `afterCreate` hook, and set authenticatedUser there :)

**Comment by mattiamanzati** [comment]
views declared as get are cached and update only if observed data are updated. They works exactly how mobx's computed works :)
