### ISSUE TITLE
Parent's view items are not undefined in child's hooks

### ISSUE THREAD

**Issue by KevinOrtman** [mobxjs/mobx-state-tree#377]
After updating to v0.11.0 of MST, references to a parent's view items are not resolved (null) in the child's afterCreate() and afterAttach() hooks.  

This did work in v0.9.5. 

This can be reproduced with the code snippet below (modified bookstore example) and this sandbox:  
https://codesandbox.io/s/6yzz6kj7jw
(NOTE: you will need to open the codesandbox preview pane in it's own window for the alert to be visible)

```
.actions(self => ({        
        afterCreate() {
          alert(`After create - Fetch is undefined: ${typeof self.shop.fetch === "undefined"}`);
          alert(`After create - isLoading is undefined: ${typeof self.shop.isLoading === "undefined"}`);
        },
        afterAttach() {
            alert(`After attach - Fetch is undefined: ${typeof self.shop.fetch === "undefined"}`);
            alert(`After attach - isLoading is undefined: ${typeof self.shop.isLoading === "undefined"}`);
        },
```

**Comment by mweststrate** [comment]
@KevinOrtman thanks for reporting! Are you interested in creating a PR for a unit test to reproduce this behavior?

**Comment by KevinOrtman** [comment]
Certainly.

**Comment by maxgallo** [comment]
I run into the same bug.
I've got a workaround, even if you're not going to like it.

**Not working**
```
.actions(self => ({
    afterCreate() {
        console.log(getParent(self).anyViewProperty); // this is undefined
    }
}))
```

**Working**
```
.actions(self => ({
    afterCreate() {
        setTimeout(() => {
            console.log(getParent(self).anyViewProperty); // this has a value
        }, 0);
    }
}))
```

**Comment by mweststrate** [comment]
Will be fixed in next MST release; where `afterAttach` can be used to make assumptions about parent. `afterCreate` hook will run depth-first, `afterAttach` breadth first
