### ISSUE TITLE
applySnapshot: Error converting x to y

### ISSUE THREAD

**Issue by paul-veevers** [mobxjs/mobx-state-tree#379]
**The problem**
```javascript
// persist snapshots
onSnapshot(self, s => localStorage.setItem('key', JSON.stringify(s)));

// restore on next page load
applySnapshot(self, JSON.parse(localStorage.getItem('key')));
```
That works fine if you never change any types anywhere in the tree. If you do change a type, then you get an error similar to `Error converting x to y`. The error throws even if you wrapped the `applySnapshot` in a `try/catch`; it must be on next tick?

**A solution**
One solution is to version the snapshots that are persisted so that on next page load you can tell whether it's an 'old' snapshot, and then not apply it. You could do that easily with a `git_commit_sha`, but then all snapshots will be invalidated for every little change.

Instead I've tried to get a canonical hash of the entire type tree - so that if any type in the tree changes then the hash will change. This is my code (it seems to be working):

```javascript
function getDeepTypeOfType(type) {
  if (!type) return '';
  return type.name
    + getDeepTypeOfType(type.type)
    + getDeepTypeOfType(type.subType)
    + reduce(type.types, (acc, v) => (acc += getDeepTypeOfType(v)), '')
    + reduce(type.properties, (acc, v) => (acc += getDeepTypeOfType(v)), '');
}

export default function typeHash(type) {
  return hash(getDeepTypeOfType(type));
}
```

And then use it like this:
```javascript
const version = typeHash(getType(self));
```

I'm assuming the above is not supported :)

What is the recommended approach? Or is it worth considering creating an API for this in MST?

**Comment by mattiamanzati** [comment]
Uhm, should'nt be on next tick, it is checked synchronusly in tests too.
Btw the approch is perfectly fine, just be aware that we are reasoning about type introspection API, so current way based on name may break; you could consider using type.describe() that does the same job :)

**Comment by paul-veevers** [comment]
Amazing, you guys have thought of everything :)

1. You're right `applySnapshot` is sync, it was my fault.
2. Using `type.describe()` my code snippet above becomes:
```javascript
import { getType } from "mobx-state-tree";
import hash from "./hash";

export default function typeHashOfNode(node) {
  return hash(getType(node).describe());
}
```
And then use it like this:
```javascript
const version = typeHashOfNode(self);
```

Thanks for your help.
