### ISSUE TITLE
Pushed 1.0.0 by accident?

### ISSUE THREAD

**Issue by ssured** [mobxjs/mobx-state-tree#392]
NPM reports MST to be in 1.0.0: 
![image](https://user-images.githubusercontent.com/2558804/30531524-3bda5600-9c4f-11e7-97cb-9ff4b56fa40d.png)

It seems you have pushed 0.12:
![image](https://user-images.githubusercontent.com/2558804/30531538-50faa896-9c4f-11e7-8b16-50b52a1402ce.png)

Awesome that MST is 1.0, but my gut feeling is something went wrong here. Otherwise let's throw a launch party!

**Comment by mattiamanzati** [comment]
https://twitter.com/chibicode/status/906843912052117504

Lauch party! 🎉

**Comment by ssured** [comment]
Too bad I missed that one! Congrats! :1st_place_medal:
