### ISSUE TITLE
example for integrating with react-navigation

### ISSUE THREAD

**Issue by peta15** [mobxjs/mobx-state-tree#397]
Are there any good examples for integrating react navigation with MST in a react-native application?

I have found a doc on how to integrate navigation with mobx: https://github.com/react-community/react-navigation/blob/8e8d3d562c9e80616f145f97ffb02dcf2048e67e/docs/guides/Mobx-Integration.md

I would love to ultimately find an example with MST rather than redux for a more real world example like https://medium.com/@parkerdan/react-navigation-with-complete-redux-state-management-tab-bar-and-multiple-navigators-ed30a69d9a4d

**Comment by peta15** [comment]
actually integration with ignite cli as a boilerplate (https://github.com/infinitered/ignite) or a full featured boilerplate like https://github.com/aksonov/react-native-starter-app would be amazing!

**Comment by skellock** [comment]
Heyo, Ignite Contributor here.

So, this isn't an ignite specific solution, but here's how I've done this integration before in one of my projects.

> `warning`: this is typescript. and by `warning`, i mean `awesome`. You may have to convert to JS or FlowType if that's how you roll.

#### MST Their State Object

You end up wrapping `react-navigation`'s state in an `mst` model.  But instead of modeling the tree from `react-navigation`, just jam it all into a `types.frozen` like this:

<details>
In `navigation-state.ts` file:

```ts
import { types } from 'mobx-state-tree'
import { MainNavigator } from './main-navigator' // <-- this your own root-level router
import { NavigationActions } from 'react-navigation'

const { getStateForAction } = MainNavigator.router

const defaultState = getStateForAction(NavigationActions.init(), null)

/**
 * Tracks the navigation state for `react-navigation` as well as providers
 * the actions for changing that state.
 */
export const NavigationState = types
  .model('NavigationState')
  .props({
    /** the navigation state tree (Frozen here means it is immutable.) */
    state: types.optional(types.frozen, defaultState),
  })
  .actions(self => ({
    /**
     * Perform this navigation action.
     * 
     * @param action The new navigation action to perform
     * @param shouldPush Should we push or replace the whole stack?
     */
    navigate(action: {}, shouldPush: boolean = true) {
      const previousNavState = shouldPush ? self.state : null
      self.state = getStateForAction(action, previousNavState) || self.state
      return true
    },

    /**
     * Resets the navigation back to the start.
     */
    reset() {
      self.state = defaultState
    },
  }))

export type NavigationStateType = typeof NavigationState.Type
```

As noted above in the comment, you bring in the router from your root stack.  I called mine `MainNavigation` because I lack imagination.  `Root` is a good name.

</details>

#### Inject Into Provider

Next, `.create()` one of those models and slap it on your mobx `Provider` way at the top of your app.

If you're interested, I could post some code on how to `load` and `save` from AsyncStorage, but it's really easy.  The trick to saving is to just use `onSnapshot()` from `mobx-state-tree`. :tada:

#### Wrap Navigation

Next step is to wrap the main navigation component.  This is optional, although I like doing this.

<details>
I made a `stateful-navigator.tsx` component file.

```ts
import * as React from 'react'
import { inject, observer } from 'mobx-react'
import { addNavigationHelpers } from 'react-navigation'
import { MainNavigator } from './main-navigator'
import { NavigationStateType } from './navigation-state'

interface StatefulNavigatorProps {
  navigation?: NavigationStateType
}

@inject('navigation')
@observer
export class StatefulNavigator extends React.Component<StatefulNavigatorProps, {}> {
  render() {
    const navigation = addNavigationHelpers({
      dispatch: this.props.navigation.navigate,
      state: this.props.navigation.state,
    })

    return <MainNavigator navigation={navigation} />
  }
}
```
</details>

Instead of rendering your component in your app at the top, render this one.  This is just a `hoc`-like component that injects your own version of `navigation` down into `react-navigation`.

It's really simple but super powerful how they let you swap out the entire state.

Downside:  you're going to need to handle the `back` button on android and any `deep` links yourself.

#### That's It

I've got this working in a few different projects, but I haven't cleaned it up just yet.  I think it might be a good candidate for a library.  `mobx-state-tree-for-react-navigation-in-react-native` is what I'm thinking.  or `mst4rninrn`.  Rolls off the tongue.

**Comment by mattiamanzati** [comment]
Sure, that approach apply for almost any navigation lib! :)
If you publish the package, please name it with starting mst-* :) Exporting both the navigation type and wrapper component if needed :)

**Comment by yordis** [comment]
@skellock I tried your solution and so far it is pushing into the state but the UI is not updating.

**Comment by nadzic** [comment]
Hi,

Is there already existing this package for navigation?

**Comment by yordis** [comment]
@nadzic `main-navigator` it is a navigation component from `react-navigation` like

```
// main-navigator.js
export default StackNavigator({
  Home: {
    screen: HomeScreen,
  },
});
```

**Comment by skellock** [comment]
I don't have anything packaged or polished yet, but you can see some of it in action here:

https://github.com/infinitered/ignite-ir-boilerplate/tree/ignite_bowser/boilerplate/src/navigation

We've done our last 5 projects with `mst` and `react-navigation` and it's pretty great (imo).

**Comment by nadzic** [comment]
Thank you very much!

**Comment by skellock** [comment]
`react-navigation` is a bit of a moving target, and it'll be difficult for `mst` to keep up with everything that **could** use it.

With the examples I've posted above, I say we close this issue to lighten the load a bit on the `mst` team.

**Comment by robinfehr** [comment]
@skellock thanks. would be cool to hear about updates - feel free to add them here.

**Comment by lishine** [comment]
@skellock correct me if I am wrong, your example is for one navigator.
By any chance do you have an example of stacked navigator, like tabbed inside stack ?
The react navigation with redux , the only way of implementating it that I know - is by creating reducer of every navigator.
I for the meantime solve by not replacing the navigation state, but just saving the navigation state into the store, each time component of each navigator gets mounted. I just take it's navigaton props and put it in the stor...

**Comment by skellock** [comment]
You only need to track your root navigator.  `react-navigation` embeds its state under the root.  And that rolls up into a single `mst` store with a `types.frozen()`  🎉

**Comment by IndianAg0711** [comment]
@skellock I've successfully implemented mst with react navigation using your code examples. Thanks a ton for sharing it with us, I'm a big fan of all the open source work you guys are doing! I do have a question though: There seems to be a bit of delay in the navigation store that results in a delay when attempting to use `navigation.goBack()` in a react-navigation header. The screen and header render, but there is a 2 second delay before that action will work correctly when called. Is this a problem you have run into in your experimenting/use?

**Comment by skellock** [comment]
@IndianAg0711: No prob!

Ya, I have.  That seems to be related with `react-navigation` not `mst`.

Search for `delay` on their issues and there's a few people reporting this.  I'm currently using a custom header component on my project, so I haven't had to dig into why just yet.  😅

**Comment by IndianAg0711** [comment]
Thanks for the point in the right direction!

**Comment by Entryist** [comment]
Came here from Google after an error with the above setup using mobx-state-tree v3.5.0:

`[mobx-state-tree] expected a mobx-state-tree type as first argument, got function frozen$$1(arg)`

Solved it by changing types.frozen to types.frozen().

**Comment by tmaly1980** [comment]
@skellock How would this example work for react-navigation v5? I'm wanting to call navigate() from within my state tree actions. I don't see anything in ignite-bowser that lets us do that.

**Comment by terrysahaidak** [comment]
> @skellock How would this example work for react-navigation v5? I'm wanting to call navigate() from within my state tree actions. I don't see anything in ignite-bowser that lets us do that.

Hi. Please check out react-navigstion docs: section "navigate without navigation prop".
