### ISSUE TITLE
Does all types and its properties need to be statically provided ? 

### ISSUE THREAD

**Issue by agenthunt** [mobxjs/mobx-state-tree#398]
Is something like this possible ? The data property can be any javascript object with arbitrary properties.
```javascript
 types
  .model({
    type: types.string,
    url: types.optional(types.string, ""),
    data: types.object or type.any ?? 
  })
```

**Comment by mweststrate** [comment]
yes, see frozen type. But note that it should be immutable as MST cannot
reason about types it doesn't know anything about

Op vr 22 sep. 2017 om 16:13 schreef Shailesh Kumar <notifications@github.com

**Comment by agenthunt** [comment]
Thanks.

**Comment by mattiamanzati** [comment]
...immutable and serializable as well :)

**Comment by MehdiSaffar** [comment]
Can someone please clarify to me why MST cannot reason about "any" types?
Maybe we can allow `types.any` where any change in that object will be tracked but warn the user that behavior that can results out of that (for example with circular objects) might be dangerous?
