### ISSUE TITLE
consider using WeakMap

### ISSUE THREAD

**Issue by mattiamanzati** [mobxjs/mobx-state-tree#4]
I know that they are not full supported yet, but great polyfills exists, so are there problems with using something like WeakMap<object, Node>() to store the "nodes" and easily retrieve them?

**Comment by mweststrate** [comment]
Ideally I try to avoid that. So far I didn't really need them, and for support it is much easier if everything run's on any ES5 env. Polyfill's are often slow or leaking introducing havoc when scaling up

**Comment by mattiamanzati** [comment]
Makes sense! Thanks for the explanation!
