### ISSUE TITLE
Polymorphic collections

### ISSUE THREAD

**Issue by danielearwicker** [mobxjs/mobx-state-tree#40]
I'm building an editor that supports putting "widgets" on a drawing surface. The widget types are not known to the editor (it will be reused in various contexts with different sets of domain-specific widgets).

So each widget is represented by a wrapper model that stores certain things common to all widget instances (coordinates, title). And then the widget-specific stuff is implemented by a separate object.

So the widget instance is serialised like:

```ts
{
    left: 3,
    top: 2,
    width: 8,
    height: 6,
    title: "My widget",
    type: "funWidget",
    settings: {
        // could be anything, depends on type
    }
}
```

For deserialisation, a widget factory is injected into the editor and supports creation of a specific implementation given a type name, and then the `settings` can be serialised into the implementation.

Is this kind of OO polymorphism something already supported by -state-tree, or is it something you are considering?

**Comment by mweststrate** [comment]
For polymorphism there are two concepts available: `composeFactory` that takes a list of existing factories, and combines it into a new factory, and `union` types, that indicates that a value should be one type of a given set of typings, which seems the most applicable in your situation. For `union` types mobx-state-tree will pick the best matching type given json, or you can provide a custom `dispatcher` function that, given some json, should return the type that shoud be applied. See `union.ts`

**Comment by danielearwicker** [comment]
Sounds perfect, will take a look.

**Comment by mattiamanzati** [comment]
@danielearwicker You may also have a look at "literal" which matches exactly a string. You can use that in your type field to avoid writing the union dispatch!

**Comment by mweststrate** [comment]
@mattiamanzati you're a genius. If you are at React-Europe, I'll hand the stage over to you :)

**Comment by mattiamanzati** [comment]
@mweststrate Hahaha unfortunately not :P See you in Italy if it will be a thing! ;)
@danielearwicker You could load all settings types at bootup and do something like this:

```javascript
function createWidgetType(widgetSettingsTypes){
    return unionOf(
        ...Object.keys(widgetSettingsTypes).map(typeKey => 
            createFactory({
                left: 0,
                top: 0,
                width: 0,
                height: 0,
                title: "",
                type: literal(typeKey),
                settings: widgetSettingsTypes[typeKey]
            })
        )
    )
}

const FunWidgetSettings = createFactory({
    num: 0
})
const AnotherWidgetSettings = createFactory({
    string: ""
})

const WidgetType = createWidgetType({
    funWidget: FunWidgetSettings,
    anotherWidget: AnotherWidgetSettings
})
```

**Comment by danielearwicker** [comment]
@mattiamanzati this looks about right. I like the idea of the set of widget types being a union, so an editor for that set of types will be strongly typed to the maximum extent.

So far I've been doing it [this way](https://github.com/danielearwicker/json-mobx) - far less ambitious than `tree-state` but good enough for me at the moment and simple enough to be very short and unsurprising. It has the same computed `json` property concept mentioned in @mweststrate's talk.

My widgets are "alive" objects in the same way that stateful React components can wire themselves up to external events or timers or whatever. So I am very keen on the idea that persistence can "load into" an existing object rather than generating a completely new one.

In one way, it achieves the same ends as VDOM. My alive objects are like the DOM, and their JSON representation is like VDOM. Loading JSON into the object tree is like rendering/reconciliation and makes only the minimal updates necessary.

This is amusing because I could (if I wanted) insist on taking the Redux approach within this system. I could keep the pure JSON representation in a Redux store and whenever it changes I load it into my live active objects and they update themselves appropriately. At which point I never need to save my active objects, and they become no different from React components (one-way reconciliation on being assigned some new JSON/VDOM, but no need to ever ask them for the JSON that would recreate their current state).

But this would just be a lot more inconvenient. When the user does something in the UI which requires an update I would then need to find the appropriate place in my JSON and create an updated clone to become the new current JSON and so trigger the update.

Far simpler to let the live-active objects store their own definitive current state, and ask them for the JSON representation in `autorun`, and let the `computed` nature of the `json` property take care of sharing unchanged pieces.

**Comment by danielearwicker** [comment]
Another way that my widgets resemble stateful React components is that they have a `render` method. So they essentially *are* React components except that the concepts of props and state have been unified, and the component tree can be told "here's your new state in some JSON" and it jumps into line, or it can be asked "what is your current state as JSON?" and it returns it. And everything is observable ultimately so the `Undo` class can track it automatically.
