### ISSUE TITLE
Any option for ES6/7 class based models with decorators instead of types.model()

### ISSUE THREAD

**Issue by sanketsahusoft** [mobxjs/mobx-state-tree#401]
This is not an issue but a feature request.

I love MST and I wanted to know if we have any option of adding ES6/7 class based model creation with the help of decorators like

```
types.model("MyModel", {
  ...
}
```

to
```
@model
class MyModel {
    ...
}
```

**Comment by mattiamanzati** [comment]
Please see #3 #338 #312 
As said before there are constructs in MST that makes typesystem screw up when using decorators.
We want to fix all the things and make codebase solid. This feature can be provided by an external package with no problems, and someone started something similar :)
Check this out by @aretecode https://github.com/aretecode/thisless

**Comment by farwayer** [comment]
Hi! I just released the [mst-decorators](https://www.npmjs.com/package/mst-decorators) library to define class-based models. I used this library for 1.5 years for dozens of projects but it may still contain some bugs. And there is no TS defs yet. Feel free to open issues/PRs.

Some features:
- simple syntax without need to use extra helpers etc, just decorators
- es6 extending
- access to instance via `this`
- `@view`, `@action`, `@flow`, `@volatile` decorators
- model class is decorator so it can be used in another model (`@Location`)
- late definition for recursive models (`@late(() => ref(Category)) topCategory`)
- `preProcessSnapshot`/`postProcessSnapshot` as static class methods
- can specify `onPatch`/`onSnapshot`/`onAction` just in class
- lifecycle hook actions, composing and `getEnv()` works as well
- several extra decorators: `@jsonDate`, `@setter`
- result of decorator function is decorator. Feel power in constructing types!
```js
@model class User {}
const Author = maybe(ref(User))

@model class Message {
  @Author author
}
```
Several examples:
```js
import {
  model, view, action, flow, ref, bool, array, map, maybe, id, str, jsonDate,
} from 'mst-decorators'

@model class BaseUser {
  @id id
  @str username
  @str password
}

@model class User extends BaseUser {
  @maybe(str) phone
  @maybe(str) firstName
  @maybe(str) lastName
  
  @view get fullName() {
    if (!this.firstName && !this.lastName) return
    if (!this.lastName) return this.firstName
    if (!this.firstName) return this.lastName
    return `${this.firstName} ${this.lastName}`
  }

  @action setPhone(phone) {
    this.phone = phone
  }
}

@model class Location {
  @num long
  @num lat
}

@model class Message {
  @id id
  @ref(User) sender
  @str text
  @jsonDate date
  @bool unread
  @Location location

  static preProcessSnapshot(snap) {
    //...
  }
  static postProcessSnapshot(snap) {
    //...
  }
  
  onPatch(patch, reversePatch) {
    //...
  }
  onSnapshot(snapshot) {
    //...
  }
  onAction(call) {
    //...
  }
}

@model class Chat {
  @id id
  @array(Message) messages
  @map(User) users

  @action afterCreate() {
    this.fetchMessages()
  }

  @flow fetchMessages = function* () {
    this.messages = yield Api.fetchMessages()
  }
}

const chat = Chat.create({
  id: '1',
})
```
