### ISSUE TITLE
Store snapshot into properties of store ?

### ISSUE THREAD

**Issue by pierrebiver** [mobxjs/mobx-state-tree#402]
I have some pain to understand how to use snapshot. So I have 2 questions:
- I want to store a snapshot, and apply it if a user cancels a change into a form, is that a good use of it ? or there is something else?
- I don't know where to store it, I wanted to store it into my properties of my Model, but there is no "type" snapshot.

**Comment by mattiamanzati** [comment]
1. Definetely yes :)
2. You can use types.frozen which is for storing serializable & immutable data, which is exactly... a snapshot! :)
Feel free to reopen for any question :)

**Comment by pierrebiver** [comment]
Thank you :) I'll try to make it work now, maybe it will be nice to add a bigger example of how to use snapshot ? If I have time I'll make a suggestion and try to contribute.
