### ISSUE TITLE
Two-way data binding in forms

### ISSUE THREAD

**Issue by mquandalle** [mobxjs/mobx-state-tree#41]
Hello,

Two-way data binding has a bad reputation in the React community, because it is easy to write code that will be hard to debug, and “unidirectional data flow” is recommended instead of that pattern. But with a library like `mobx-state-tree` we get use simple read and write expressions on a model field, `myModel.field = newValue`, and still get all the benefits in term of development experience (reproducibility, debugging, etc.) of a Flux/Redux architecture.

So with that, I'm wondering if a set of helper functions to help write the read and write binding between a from input and a mobx model field would be useful, and what would be a desirable API.

So for instance here we bind a Toggle component from [Material UI](http://www.material-ui.com/#/components/toggle) with the corresponding field on our app model:

```js
import Toggle from "material-ui/Toggle"
import { bindToggle } from "mobx-two-way-data-binding" // Theoric API
import { observer } from "mobx-react"
import { myModel } from "../models"

export default observer(() =>
  <Toggle label="Enable hyper mode" {...bindToggle(myModel, "isHyperModeEnabled")}/>,
)
```

In the above example the `bindToggle` helper function would be defined as follow:

```ts
function bindToggle<T, K extends keyof T>(model: T, field: K) {
  return {
    defaultToggled: model[field],
    onToggle: (event, value) => {
      model[field] = value
    },
  }
}
```

I'd like to have some feedback about this idea of helper functions for binding a mobx-state-tree field with a form input, and discuss APIs. For instance there are different way of binding an `input` element: we could use `onChange` which would update the model every time a key is pressed, or wait for some form submission event. Also here I'm using object destruction to feed the input component props, but maybe a higher order component would be better?

**Comment by mquandalle** [comment]
I just found out [linkedstate](https://preactjs.com/guide/linked-state) from the PreactJS team, and I think we could have almost identical API to link a MobX store instead of a component internal state.

**Comment by mweststrate** [comment]
Sorry for leaving this so long lingering around. Closing for now, feel free to reopen if it is an active question still.
