### ISSUE TITLE
Would a `snapshotWasApplied` lifecycle hook make sense, notifying after snapshot is applied?

### ISSUE THREAD

**Issue by danielearwicker** [mobxjs/mobx-state-tree#414]
e.g. If I have some private volatile data and when a snapshot is applied I want to fix the volatile data accordingly.

Or is there already some other way to do this?

**Comment by mattiamanzati** [comment]
Uhm, what do you mean by "fix"? Is the volatile calculated over the properties?
If so, you can use a reaction from the mobx package to automatically trigger that whenever it changes. You can setup the reaction inside afterCreate and dispose it in beforeDestroy :)

**Comment by danielearwicker** [comment]
Yes, that will do it!
