### ISSUE TITLE
Async process has "race condition"-like behaviour.

### ISSUE THREAD

**Issue by NickLuger** [mobxjs/mobx-state-tree#416]
I have a `ListStore` which manages a ` list: types.optional(types.array(typeToStore), []),`

It contains this action:

```
remove: process(function* remove(id) {
        try {
          self.markBeingRemoved(id); // set variable in store
          const element = yield getEnv(self).resource.remove(id); // async call
          self.removeFromList(element.id); // see below
          showSuccessNotification(); // some jQuery based notification library
        } catch (err) {
          showServerError();
        } finally {
          self.markBeingRemoved(null); // reset var in store
        }
      })
```
`removeFromList` is also an action which simply does:

```
const indexToRemove = self.list.findIndex(e => e.id === elementId);
        if (indexToRemove >= 0) {
          self.list.splice(indexToRemove, 1);
        }
```
i inject the list store `@inject('ListStore')` into a react component and pass the list as props:
```
 <SomeListComponent
          SomeListComponent={this.props.TemplateStore.list}
```
`<SomeListComponent/>` renders the list elements, and every element can call `ListStore.remove`, as i pass it as props to the list.

Now if I call it, the element **gets removed correctly from the list in the store.** Also, **the React component updates correctly and renders the list without the removed element.**

I still get  the following error on console:
```
mobx-state-tree.module.js?9486:50 Uncaught Error: [mobx-state-tree] This object has died and is no longer part of a state tree. It cannot be used anymore. The object (of type 'Template') used to live at '/list/1'. It is possible to access the last snapshot of this object using 'getSnapshot', or to create a fresh copy using 'clone'. If you want to remove an object from the tree without killing it, use 'detach' instead.
    at fail (webpack-internal:///467:92:11)
    at Object.get (webpack-internal:///467:1409:17)
    at Object.get [as id] (webpack-internal:///33:1682:28)
    at dehydrate (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:8154:38)
    at dehydrate (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:8154:24)
    at dehydrate (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:8154:24)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:7285:20
    at Array.map (native)
    at Bridge.flushBufferSlice (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:7280:33)
    at Bridge.flushBufferWhileIdle (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:7268:15)
```

The error is **not always shown,** it's behaviour is non-deterministic, and seems to depend on time (see below). I think it is shown 95% of the time, but can also suddenly disappear (worst of its kind...).

Also, the error is **not** shown if:

- The React-component is not rendered currently, e.g. I call `remove` from console at another route.
- I put the inner action `removeFromList` in a timeout, like: `setTimeout(() => {self.removeFromList(element.id)}, 1000);`

The second thing seems quite weird to me...

**Comment by mattiamanzati** [comment]
Uhm, that seems to be triggered by the react developer tools, can you please try if in a chrome instance without that extension the error does not trigger?
It seems that some react component still holds onto the died object.

**Comment by NickLuger** [comment]
Exactly, that solved it. Thank you
