### ISSUE TITLE
Recommendations for working with an immutable current user 

### ISSUE THREAD

**Issue by jole78** [mobxjs/mobx-state-tree#421]
Hi,

just started experimenting with MST and so far it seems very promising and intuitive to use, great work!

Got a question though. Say that I have a UserStore (or something) which is a model that can handle users (crazy right??). But I also want to store the current user (which is also a user model). You can set that once, like through an authorize action or something (haven't really decided yet), but not be allowed to change the value of the current user during your "session".

Any recommendations/ideas on how to implement that you can point me to?

**Comment by mweststrate** [comment]
All proporties are read only by default. Just don't expose an action to
change it 😊

**Comment by jole78** [comment]
👍yes of course...thanks for the clarification though. Closings the issue.
