### ISSUE TITLE
Question about optional vs maybe and patches

### ISSUE THREAD

**Issue by jole78** [mobxjs/mobx-state-tree#422]
Hi,

trying to create a model which may or may not have a date...something like this.

```javascript
const Incident = types
    .model("Incident", {
        id: types.identifier(),
        time_of_discovery: types.maybe(types.Date),
        ...etc
    })
```
so, that works but when I update the "time_of_discovery" date the patch is
`{"op":"replace","path":"/time_of_discovery","value":1506861193027}`
which I presumed would be **add** instead.

Tried to make the date optional instead but then it doesn't support null (yes I know null cannot be converted to null), it has to be a date or a number.

The question really comes down to how patches are treated when it comes to optional vs maybe I guess and if there are any "best practices" for this.

The "odd" thing here is that given that the model also has this property:
`categories: types.optional(types.map(Category), {})`

...and I add a category...then I see
`{"op":"add","path":"/categories/1","value":{"id":1}}`

**Comment by mattiamanzati** [comment]
optional does'nt "omit" a property, simply provides a default value if not provided in the snapshot
model will always be created with all properties declared;
maybe is basically types.optional(types.union(YourType, types.null), null), so it accepts either null (and use it as default) or the given type.
That's why model patches will always be replace.
The category one uses "add" because at path /categories there is a map, so properties aren't known at creation time, and each time a new one is added, "add" will be triggered.
Hope to be clear :)

**Comment by jole78** [comment]
OK, thanks for clearing that up @mattiamanzati. So if I understand you correctly, there's really no way of saying that a value can be added later on (and thus treated as an add operation patch) but initially it's basically "not set"...or??
I have a clear case of really knowing what got added and what changed in my model...really liking the patch thing for that btw, it fits my use case perfectly otherwise.

**Comment by mattiamanzati** [comment]
Exactly, in models properties always have a value (either null or a setted one).
So you can set every field with maybe, listen for patches, and determine on the patch listener if it was an add or an replace by seeing if value was null before

**Comment by jole78** [comment]
But a patch listener can’t change the type of patch right...so if I’m gonna create a patch recorder that does that I have to keep track of the history and handle that myself. To me this behavior seems a little odd, I say a little since I might not grasp the concept completely yet and how it’s meant to be used though. Gonna close the issue since I basically got the answers I was looking for. Thx
