### ISSUE TITLE
setImmediate is not defined

### ISSUE THREAD

**Issue by imranismail** [mobxjs/mobx-state-tree#427]
Happens when I try to use async generator function

**Comment by mattiamanzati** [comment]
Are you using a compiler like babel or typescript? Looks like more an issue with the polyfill of generators rather than a mobx-state-tree one :)

**Comment by imranismail** [comment]
You're right, I think this is somewhat unrelated to mobx

**Comment by jschill** [comment]
Clarification: The async flow function [depends on setImmediate](https://github.com/mobxjs/mobx-state-tree/blob/e32dfee5af7f10534c43f6c5b944e8a521838c5f/packages/mobx-state-tree/src/core/flow.ts#L99) so you need to [polyfill](https://github.com/YuzuJS/setImmediate) that until it's [implemented in your browser](https://caniuse.com/#search=setimmediate).
