### ISSUE TITLE
[Question] Is there any example using Angular?

### ISSUE THREAD

**Issue by faramos** [mobxjs/mobx-state-tree#430]
This library looks very impressive, but I'm actively working with Angular (4) and TypeScript 100%.
Thanks in advance.

**Comment by mattiamanzati** [comment]
Mobx-state-tree uses mobx under the hood.  There is no example yet, but you can just use the mobx-angular connector :)

**Comment by faramos** [comment]
I'll give it a try next week. Thanks :)

**Comment by jbadeau** [comment]
@faramos any update on your experience?

**Comment by aaronksaunders** [comment]
https://stackblitz.com/edit/ionic-mobx-example2-mst here is an example, but for some reason I am not getting all updates from the devtools
