### ISSUE TITLE
Optional types in Typescript arent optional

### ISSUE THREAD

**Issue by mikecann** [mobxjs/mobx-state-tree#432]
Given the following example:

```typescript
const Todo = types.model({
    text: types.optional(types.string, "")
});

type ITodo = typeof Todo.Type;

const TodoStore = types.model({
    todos: types.optional(types.array(Todo),[])
})
.actions(self => ({
    addTodo(todo:ITodo) {
        self.todos.push(todo)
    }
}))
```

I would expect to be able to do something like this:

```typescript
var store = TodoStore.create();
store.addTodo({});
```

Unfortunately you get an error: 

> Argument of type '{}' is not assignable to parameter of type '{ text: string; } & IStateTreeNode'.
  Type '{}' is not assignable to type '{ text: string; }'.
    Property 'text' is missing in type '{}'.'

Which is unexpected because I marked text as optional, plus MST allows you to do it in if you type it as any:

```
store.addTodo({} as any);
```

Is this a Typescript limitation?

**Comment by mattiamanzati** [comment]
You need to use the SnapshotType, not the Type for that :)

```
const Todo = types.model({
    text: types.optional(types.string, "")
});

type ITodo = typeof Todo.Type;
type ITodoSnapshot = typeof Todo.SnapshotType;

const TodoStore = types.model({
    todos: types.optional(types.array(Todo),[])
})
.actions(self => ({
    addTodo(todo: ITodo | ITodoSnapshot) {
        self.todos.push(todo)
    }
}))
```

**Comment by mikecann** [comment]
Awesome, thanks!

**Comment by mattiamanzati** [comment]
You're welcome! :D

**Comment by mikecann** [comment]
Actually your above code doesnt work..

> 'Argument of type '{ text?: any; } | ({ text: string; } & IStateTreeNode)' is not assignable to parameter of type '{ text: string; } & IStateTreeNode'.
  Type '{ text?: any; }' is not assignable to type '{ text: string; } & IStateTreeNode'.
    Type '{ text?: any; }' is not assignable to type '{ text: string; }'.
      Property 'text' is optional in type '{ text?: any; }' but required in type '{ text: string; }'.'

:(

**Comment by mattiamanzati** [comment]
Oh sorry! I missed that line.
Here there is a known TS limitation, at the moment you can use only the concrete type, not the snapshot one. Progress is tracked on #85 

self.todos.push(todo as any)

**Comment by mikecann** [comment]
Sweet! Thanks :)
