### ISSUE TITLE
Adding static methods in the base class and using in the derived class

### ISSUE THREAD

**Issue by sanketsahusoft** [mobxjs/mobx-state-tree#433]
First of all, I love MST. 🙌 

I am working on a FirebaseBaseModel which has save() function at the moment. I would like to add a static method in the FirebaseBaseModel so that any model can extend from it and use it like.

```
const Post = FirebaseBaseModel.named("Post").props({
  _path: "posts",
  title: types.string,
  description: types.string
});
```

So, the `save()` method works well.
```
const post = Post.create({
    ...
});

post.save();
```

Now, I want to build a `.fetch()` method on the class level. So that, I can do
```
const post = await Post.fetch("1231234");
```

Any help?

PS: I would obviously open-source the base FirebaseModel and write a blog post about it.

**Comment by mattiamanzati** [comment]
The problem with static actions/methods is that they can't trigger actions over a model, so they can't use time travelling. So not sure about that :/
My suggestion would be to have two types, as I doing currently, a model and a repository one.
You can create both with an utility function. e.g.

```javascript
const {Repository, Model} = createFirebaseModels({path: "posts"}) // parameters can be optionally stored here

const PostRepository = Repository.actions(/* ... user custom actions */
const Post = Model.views(/* ... user custom views */)

const repository = PostRepository.create() // (or on root model on "posts" property and then getRoot(this).posts
const thePost = await PostRepository.fetch(1)
await repository.save(thePost)
await repository.delete(thePost)
```

You could also potentially make all those methods sync and just have a `await repository.sync()` :)

**Comment by sanketsahusoft** [comment]
I have developed it with composition (`.named`) and a utility function for now which accepts the Model class.

Though I really like the idea of `Repository`! 👍 

Let me move forward with few more functions. I am also thinking of adding "references" to other models where a Post model can have a property like `owner: mapsToOne(User)`.

I will submit a rough draft version soon.

**Comment by mattiamanzati** [comment]
Yep, also Repository make testing easier, as you can just replace them with a mock implementation and the whole app will continue to work :)

**Comment by sanketsahusoft** [comment]
![image](https://user-images.githubusercontent.com/1733433/31307624-c627e3c8-ab85-11e7-8238-8f44935caa1a.png)

This works as of now!

**Comment by mattiamanzati** [comment]
Awesome! :D

**Comment by mattiamanzati** [comment]
Closing for now! :)
