### ISSUE TITLE
[Question] Migrate this model from MobX to mobx-state-tree

### ISSUE THREAD

**Issue by chemitaxis** [mobxjs/mobx-state-tree#438]
Hi @mattiamanzati & @mweststrate !!

We have a service for modal windows (show, hide and other stuff) like this:

```
import { observable, action } from 'mobx';

class ModalStore {
  @observable modalType = null;
  @observable modalProps = {};

  @action
  modalShow(newModalType, newModalProps) {
    this.modalType = newModalType;
    this.modalProps = newModalProps;
  }
  @action
  modalHide() {
    this.modalType = null;
    this.modalProps = {};
  }
}

const modalStore = new ModalStore();
export default modalStore;
```

The modalType is usually a string like DELETE_FOLDER, CREATE_FILE, etc., and he modalProps, is the props that will receive the modal (title, buttons, functions, etc.), in other words, an object with different properties.

How can I achieve that with mobx-state-tree? Thanks!

**Comment by mattiamanzati** [comment]
If those props are serializable, you can use types.frozen to achieve that! :)

**Comment by chemitaxis** [comment]
@mattiamanzati thanks... I will check again... 

The docs says:

> but assumes that the value itself is immutable.

How I can change it? Creating a new object and using _Object.assign_ for example? Best!

**Comment by mattiamanzati** [comment]
@chemitaxis Yes, exactly. Like you would do with redux, without modifying the existing object and creating a new one based on the old one :)

**Comment by chemitaxis** [comment]
Perfect, thanks, I will close ;)
