### ISSUE TITLE
backend connection question

### ISSUE THREAD

**Issue by vagyriag** [mobxjs/mobx-state-tree#441]
I don't know if I should ask this here...

I have a CarStore with a list of cars. 
I use an **onPatch** to save the new cars to the server when one is added to the store.
The problem is the **onPatch** is triggered when the app fetches the cars from the server on login, so it re-sends them every time.

Currently I'm using a boolean (carsLoaded) so the onPatch function is only triggered after it has loaded the initial data. 

**is there a better or recommended way to do this?**

Thanks in advance!

**Comment by mweststrate** [comment]
That is fine, or just attach the onPatch listener at a later moment in time
