### ISSUE TITLE
Guidance on type definition with dynamic values

### ISSUE THREAD

**Issue by tim-field** [mobxjs/mobx-state-tree#444]
I like the idea of stores looking after route state. 

In the bookstore example we have [`page` and `selectedBookId` properties ](https://github.com/mobxjs/mobx-state-tree/blob/adba1943af263898678fe148a80d3d2b9f8dbe63/examples/bookshop/src/stores/ViewStore.js#L6)
 of the `ViewStore` model.

I want to make a generic routing store that can take any params required

For example
`bookstore/:category/:id`

so I guess I want a general
```
page: ''
params: Map()
```

Obviously I don't want to pre define every url parameter that I might need.  At which point this becomes more of a general MST question, is MST suited to this job? what would a more generic ViewStore look like that could handle any routing params?

**Comment by mattiamanzati** [comment]
Yep. If you want a general map, you can use types.map(types.frozen), but since params cames only from routing, and so it's immutable, I'd recommend you using params: types.frozen :)

**Comment by tim-field** [comment]
But I would need to change the param, as in the bookstore example the `selectedBookId` can change...

**Comment by mattiamanzati** [comment]
I usually re-parse the entire route params object, but you can use a types.map of types.frozen if you dont want to rebuild it completely :)
