### ISSUE TITLE
ES6 in published middleware

### ISSUE THREAD

**Issue by paul-veevers** [mobxjs/mobx-state-tree#445]
I ran into an issue when using the new TimeTraveller middleware. Distributed `npm` code hasn't been fully transpiled to `es5`. It says [here](https://github.com/mobxjs/mobx-state-tree/blob/master/middleware/README.md#contributing) "The middlewares must be written in valid ES5. ES imports / exports are allowed."

I wouldn't have noticed, but uglifyjs complains :)

Why not run babel on each file with module transpilation disabled in the build step?

I'm happy to do a PR with whatever you think is best.

**Comment by mweststrate** [comment]
Feel free to PR! Preferably we do keep the ES imports / exports (I think it
depends on the uglify version whether that is supported or not), as without
ES modules mobx-state-tree cannot be tree-shaken anymore when using these
middlewares

Op di 10 okt. 2017 om 12:30 schreef Paul Veevers <notifications@github.com>:

**Comment by mattiamanzati** [comment]
I've encountered this issue while working on #446 , and I was thinking about moving middlewares to a separate package, have them written in TS and fully transpiled. Is fine for anyone?

**Comment by mweststrate** [comment]
+1

Op di 10 okt. 2017 om 19:13 schreef Mattia Manzati <notifications@github.com

**Comment by mattiamanzati** [comment]
Ok, just done in #446 , now create-react-app is also able to build and does'nt complain about missing full-es5 transpilation. This should fix your use-case @paul-veevers !

**Comment by mattiamanzati** [comment]
Fixed, will be out with next release
