### ISSUE TITLE
process() looses argument names in Typescript

### ISSUE THREAD

**Issue by mikecann** [mobxjs/mobx-state-tree#449]
![code_2017-10-09_19-30-08](https://user-images.githubusercontent.com/215033/31414761-1f268a6e-ae52-11e7-863f-6c55d9e2e499.png)

So when you try to use Login:

![image](https://user-images.githubusercontent.com/215033/31414804-43f51f5e-ae52-11e7-9fa9-7d0b34f6bd53.png)

Is there a way around this? Can it be done by using decorators? Or this this a fundamental limitation of generators?

**Comment by mikecann** [comment]
If we did something like:

```typescript
.asyncActions(self => ({

    login: function* login(email:string, password:string) 
    {
        self.id = yield getEnv<IUser2Env>(self).authService.login(email, password);
        self.email = email;
    }
    
}))
```

Then its up to the asyncActions to wrap all methods within it in `process()` then we could gain typesafety back again?

**Comment by mattiamanzati** [comment]
This is a problem with TypeScript not having yet Variadic Types, once we have them and conditional types, we can provide better typings.
Up to then, you can use as argument a keyed object, and use destructuring in function declaration :)
