### ISSUE TITLE
possible to inject unstructured JSON into the state-tree?

### ISSUE THREAD

**Issue by Kosta-Github** [mobxjs/mobx-state-tree#45]
I would like to inject unstructured (not modelled by a factory) JSON into my state tree (e.g., the JSON response from a web request).

Is that somehow possible? Or what would be the recommended way to store such kind of data (web requests being just one example)?

**Comment by mattiamanzati** [comment]
Do you mean the possibility to use any type and store it in the state tree? If so, it's in roadmap as frozen/any type. It will accept any serializable variable and Object.freeze it deeply to make it immutable. Mutable unstructured object will probably not be supported I think.
Anyway a real case scenario of your case could help :)

**Comment by Kosta-Github** [comment]
The `frozen` type would work for me...
