### ISSUE TITLE
[Question] null in snapshot

### ISSUE THREAD

**Issue by jiyinyiyong** [mobxjs/mobx-state-tree#450]
I got any error calling `applySnapshot`:

```
Uncaught (in promise) Error: [mobx-state-tree] Error while converting 
// my data... hidden
at path "/0/lowerTolerance" value `"-1"` is not assignable to type: `number`.
at path "/0/deleted" value `undefined` is not assignable to type: `boolean`.
```

and the traced down to:

```js
    ReferenceType.prototype.isValidSnapshot = function (value, context) {
        return typeof value === "string" || typeof value === "number"
            ? typeCheckSuccess()
            : typeCheckFailure(context, value, "Value '" + prettyPrintValue(value) + "' is not a valid reference. Expected a string or number.");
    };]]
```

I don't know about this failure, does it mean any data in a snapshot should be string or number? How about data specified with types.maybe(). I think it's null in a snapshot.

And it's MST `0.9.x`.

**Comment by mattiamanzati** [comment]
Only snapshot value of references should be a string or number, so you probably have a reference somewhere in your tree :)

**Comment by jiyinyiyong** [comment]
yeah, there's `types.reference` used:

```js
cC: types.maybe(types.reference(c))
```

But how do you deal with such cases? We tried to use `types.maybe` so it was supposed to have `null`.

**Comment by mattiamanzati** [comment]
Not sure, but this may be a but with older versions :/

**Comment by mweststrate** [comment]
Closing, assuming it is fixed since it was reported on quite an old version. Otherwise feel free to reopen
