### ISSUE TITLE
Complex type in base model

### ISSUE THREAD

**Issue by nadzic** [mobxjs/mobx-state-tree#452]
Hi,

I have one question. I would like to do the following: 

export const ThreeStore = types
  .model('ThreeStore', {
      cameraPosition: new THREE.Vector3(0, 0, 5)
  })

...

THREE.Vector3 looks as this if you print it out:

Vector3 {x: 0, y: 0, z: 5}

So store object as an cameraPosition. MST is complaining that base model cannot have complex types. 

What would be the best solution for this one?

Kinds,
Nik

**Comment by knoopx** [comment]
Store the vector argument primitives as mst observables and then define a
computed value that instanciates and returns the vector?

**Comment by mattiamanzati** [comment]
@nadzic MST does not support yet custom types, so you need to define them as @knoopx  suggested :)

**Comment by nadzic** [comment]
I know I can do that way, but that's a bit awkward, because then I will need to store and create many models instead of using created THREE.js stuff.

**Comment by mattiamanzati** [comment]
You can't use directly Three.js instances because MST instances have type-enriched informations. Unfortunately Three.js does'nt have that :)

**Comment by nadzic** [comment]
Yeah I was thinking it is smth like that... :) Then I would rather do state component and hold the state data for this component locally. 

One question.. In our apps we mostly use mobx + MST for production use - i would say we are very happy. We use only stateless components and hold the whole state in MST is that correct way? Or is anz benefit use also some state components and hold part of the state locally, which is needed only there?

Mattia, tnx for answer! :)

**Comment by mattiamanzati** [comment]
@nadzic I did have have use cases where I hold the state onto react setState, and that's basically things like dirty form values while in editing, and that makes sense IMHO, as said in FAQs is completely fine to do that :)

You're welcome! :)
