### ISSUE TITLE
[Question] how to operate a dynamic object

### ISSUE THREAD

**Issue by builden** [mobxjs/mobx-state-tree#453]
I want to operate a dynamic object, and hope to watch the object change, such as
```js
const initObj = {
  obj: {
    arr: [{ a: 1, b: 2 }],
  },
};
```

I have try
1. 
```js
const Store = t
  .model('Store', {
    frozen: t.frozen,
  })
  .actions(self => ({
    addProp(key, value) {
      self.frozen[key] = value;
    },
  }));

const store = Store.create({ frozen: initObj });
store.addProp('a', {});
// TypeError: Cannot add property a, object is not extensible
```

2.
```js
const Store = t
  .model('Store', {
    frozen: t.map(t.frozen),
  })
  .actions(self => ({
    addProp(key, value) {
      self.frozen.set(key, value);
    },

    pushArr(arrItem) {
      self.frozen.get('obj').arr.push(arrItem);
    },

    modifyProp(nodeRef, key, value) {
      nodeRef[key] = value;
    },
  }));

const store = Store.create({ frozen: initObj });
window.store = store;

onSnapshot(store, snapshot => {
  console.log('onSnapshot', snapshot);
});

store.addProp('a', {});
store.pushArr('xx');  // TypeError: Cannot add property 1, object is not extensible
store.modifyProp(store.frozen.get('a'), 'foo', 'bar'); // TypeError: Cannot add property foo, object is not extensible
```

how can I define the modal to get my expect, the initObj.obj keys are not sure, can dynamic create

**Comment by mattiamanzati** [comment]
types.frozen holds an IMMUTABLE (that's why it's called frozen) object, so you cannot modify its properties.
You need to create a new object each time and reassign it to self.frozen, or you can try with something like
```
const Mutable = types.union(types.string, types.boolean, types.number, types.map(types.late(() => Mutable)), types.array(types.late(() => Mutable)))

const Store = t
  .model('Store', {
    frozen: Mutable,
  })
  .actions(self => ({
    addProp(key, value) {
      self.frozen.set(key, value);
    },

    pushArr(arrItem) {
      self.frozen.get('obj').arr.push(arrItem);
    }
}))
```

**Comment by builden** [comment]
great, that is my want, thank you very much for your help :)

I have another question, create model have to add a extra key like above `frozen`
how can I create store like this:
const store = Store.create(initObj); // initObj also maybe an array

**Comment by mattiamanzati** [comment]
Mutable.create() would work, but you can't attach functions there :)

**Comment by builden** [comment]
find a new problem
```js
const store = Store.create({ frozen: initObj });
const undoMgr = UndoManager.create({}, { targetStore: store });
store.addProp('a', {});
```

the undoMgr.history.length = 2;  // expect 1

**Comment by mattiamanzati** [comment]
Please open a separate issue for that, try to console.log the undoMgr.history.length to see what it contains :)

**Comment by ashokkumar88** [comment]
how can i get the saved array? I am trying to retrieve the array by `store.frozen.get('obj')`. But it is not returning the array items.

**Comment by ashokkumar88** [comment]
Got it. `store.frozen.get('obj').peek()`
