### ISSUE TITLE
Better way of type-hinting self in actions

### ISSUE THREAD

**Issue by sanketsahusoft** [mobxjs/mobx-state-tree#458]
Is there a better way of type-hinting self inside the actions callback function?

Right now, I am doing like this --
![image](https://user-images.githubusercontent.com/1733433/31495382-12816634-af75-11e7-98b2-abbf0861a5ca.png)

**Comment by mattiamanzati** [comment]
Please see #456 and give some feedback about the idea, that should avoid any necessity of having "self" correctly typed to the last type :)

**Comment by mattiamanzati** [comment]
Closing for now, feel free to reopen or continue on #456
