### ISSUE TITLE
Deferred loading of references ?

### ISSUE THREAD

**Issue by the-noob** [mobxjs/mobx-state-tree#459]
With the following structure...

```JavaScript
import { types } from 'mobx-state-tree';

const Tag = types.model('Tag', {
  name: types.string,
});

const Article = types.model('Article', {
  id: types.identifier(),
  title: types.string,
  content: types.string,
  tags: types.optional(types.map(types.reference(Tag)), {}),
});

const Store = types.model('ArticleStore', {
  articles: types.optional(types.map(types.reference(Article)), {}),
})
  .actions(self => ({
    find(filter = '') {
      // async loading of articles but without fully loading tags ?
    }
  }));
```
Say I have a listing page for all the articles (just the `title`) and then `edit` where I want to load the tags also... how can I defer the actual `Tag` loading but still fulfil the reference?

Is it possible or I'm on a wrong path here?

**Comment by mattiamanzati** [comment]
That's a WIP, check out #172 :)

**Comment by the-noob** [comment]
Thanks, *I did* search but  for `deferred` and found only #301 :(
Will close this and monitor the other!
