### ISSUE TITLE
Devtools with mobx-state-tree - what's the advised path?

### ISSUE THREAD

**Issue by johnnyreilly** [mobxjs/mobx-state-tree#461]
Hello!

First of all - thanks for Mobx - it has improved my devlife!  :heart:  

I heard about mobx-state-tree this morning and I've been taking it for a quick tour.  It's lovely :sunflower: :wink: 

However, having read the docs it's not obvious to me what the advice is concerning devtools.  In my existing standard mobx project I make use of the [mobx-react-devtools](https://github.com/mobxjs/mobx-react-devtools) which is great.  However, much play is made of using the redux devtools with mobx-state-tree.  So the question is: what gives?

Should we still be using the existing devtools? Or just using the redux devtools?  Or both?  How would you characterise the purpose of each?  

It would be great to express this is the docs as well to help make things clearer to people coming to the project too.

Finally, if the advice is: use redux devtools perhaps it's worth having direct documentation explaining how to plug redux devtools into mobx-state-tree?  Bear in mind I'm only 2 hours into looking at this but it seems that the examples advise not using the Mobx Provider but always using the Redux provider?  Is that right?

Thanks again and much :heart:

**Comment by mattiamanzati** [comment]
You should use MobX <Provider> indeed, have you taken a look at the getting started guide which steps you through creating a todo application? It gives a great overall :)
Personally I use redux devtools, but depends on the scope of your application :)
You can find an example of how to connect them here: https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mst-example-redux-todomvc/src/index.js#L21

**Comment by johnnyreilly** [comment]
Hi @mattiamanzati,

I have indeed taken a look at the getting started guide!  (I'm working my way through it right now; just submitted a minor docs PR :smile:)

Thanks for the example - that's useful.  What I'm trying to get at it is answers to these questions really:

- If I'm using mobx-state-tree is it advised to use mobx-react-devtools *OR* redux devtools?
- OR both?  And if both, what's the overlap?

**Comment by johnnyreilly** [comment]
BTW part 2 of the tutorial appears to be missing?

**Comment by mattiamanzati** [comment]
@johnnyreilly Yeah, not much time to finish it yet :)

**Comment by andykog** [comment]
@johnnyreilly, you can also check the fresh https://github.com/andykog/mobx-devtools
