### ISSUE TITLE
Linkstate for mobx-state-tree

### ISSUE THREAD

**Issue by dsumer** [mobxjs/mobx-state-tree#467]
Hey guy's! Have you thought of adding a linkState equivalent for MST models? 

It would help avoiding the need  for setter-actions for each prop.

I've created an example implementation with an AbstractModel:
https://gist.github.com/dsumer/56c34cc5e7698d28a00cda4cc80b332f

The problem with this implementation: the tree must be unprotected because the linked function doesnt count as an action. It is also dependent on the $treenode.nodeId prop and I dont know if it is stable to use it.

**Comment by mattiamanzati** [comment]
TIP: You may be able to use applyPatch to update the model field from outside an action even in protected mode :)

**Comment by dsumer** [comment]
ah that would've been nice! 
but the problem is: i am caching those functions (basically on the first render when they are referenced e.g. in EditCarComponent.jsx:15). And if I use applyPatch, it applies them to the "self" instance which is in the old state.

This results in following behavior:
Editing the "name" field works fine, text changes, model gets updated.
But when I edit the "color" field afterwards, the name also gets resetted to the old state when I use applyPatch. And vice versa when I am editing the "name" field afterwards again.

**Comment by mweststrate** [comment]
Closing as this is not something that should belong to the core package
