### ISSUE TITLE
Are view functions supposed to be observable?

### ISSUE THREAD

**Issue by marbemac** [mobxjs/mobx-state-tree#470]
From the docs:

```
A view function can, unlike computed properties, take arbitrary arguments. It won't be memoized, but its value can be tracked by MobX nonetheless.
```

However, I've created a test to check to see if the response from a view function call is observable, and it doesn't seem to be?

```js
// the model
const BaseService = types
  .model({
    records: types.optional(types.array(types.frozen), []),
  })
  .views(self => {
    return {
      getRecord(index) {
        return self.records[index];
      },
    };
  });
```

```js
// the test
let changedResult = [];
let resultObserver = service.getRecord(0);

expect(resultObserver).to.deep.equal({id: 1, name: 'one'});
observe(resultObserver, changes => {
  changedResult = resultObserver;
});

service.records[0].name = 'two';
expect(changedResult.name).to.equal('two');
```

If I wrap the response of getRecord in a computed, like the below, I can setup the test to verify observing is working:

```
getRecord(index) {
  return computed(() => {
    return self.records[index];
  }
}
```

Am I doing something wrong? Any better way to do this (basically, react to changes in a view function)?

**Comment by mattiamanzati** [comment]
You are using the frozen type, which the docs says that it is immutable. (Thats strange that it doesnt throws an error, it should, are you running a prod build?). You need to define a record model with id as  number and name as text

**Comment by marbemac** [comment]
Hmm, well the array itself is not meant to be frozen, just the objects inside of it. But that is a good point, perhaps I setup the test itself incorrectly.

Theoretically, should the following work?

```
// the test
let changedResult = [];
let resultObserver = service.getRecord(0);

expect(resultObserver).to.deep.equal({id: 1, name: 'one'});
observe(resultObserver, changes => {
  changedResult = resultObserver;
});

service.records[0] = {id: 1, name: 'two'}; // <- this is changed
expect(changedResult.name).to.equal('two');
```

**Comment by mattiamanzati** [comment]
Yes, it should, but you may need to define the record model with the id as identifier, to make the reconciler reusethe existing instance

**Comment by marbemac** [comment]
Any ideas on the following? This is thrown when trying to observe the response from the view function, when it is not wrapped in a computed function:

```
Error: [mobx] Invariant failed: Cannot obtain administration from
```

**Comment by mattiamanzati** [comment]
Is that using the frozen type? If so Thats expexted, because the frozen is not observable

**Comment by marbemac** [comment]
Yeah it's using the store from the first snippet of code. Is there a way to make the array itself not frozen (that's what I was expecting). Basically, an array of frozen objects.

**Comment by marbemac** [comment]
Use case here is that we are creating a generic "domain" store that has all sorts of methods for fetching and managing a list of records, but it does not care what the shape of the record objects themselves are (which is why they can be frozen).

**Comment by mattiamanzati** [comment]
Unfortunatelly not, because things like snapshots, patches, etc... could not work if we don't know the shape of the object. That's why frozen "frozes" the object :)

**Comment by mattiamanzati** [comment]
Closing for now, feel free to reopen if needed :)

**Comment by marbemac** [comment]
Gotcha, I guess I would have expected frozen types to at be shallowly compared for the purposes of triggering updates. And for snapshotting, etc, if the shallow check returned false, just store the entire new object, etc.

Then, for the array (which is not frozen - it is an immutable js object I checked), observe changes to its length, as well as the shallow checks on its frozen elements.

Its just kind of odd that I can't observe the array at all, which is a non frozen immutable object.

Quick question - if I was to define the objects as a particular model (perhaps with just id and name defined), what happens when the object being stored in the model has more properties (that are not defined upfront)? Are they discarded or just ignored by the observe / snapshot process?
