### ISSUE TITLE
Inject or Props

### ISSUE THREAD

**Issue by OverseePublic** [mobxjs/mobx-state-tree#472]
Hi, I have a generic question about using @inject.

Since, MST is a tree, should we use @inject in all components or just pass as a prop?

I noticed that just passing as a prop is more simple than wrapping with inject, but I want to know the general pattern in MST.

Thanks for your time.

**Comment by mweststrate** [comment]
I recommend to go for prop, until it get's annoying :) or when you start
passing trees into components that totally don't need it themselves

Op ma 16 okt. 2017 om 17:07 schreef OverseePublic <notifications@github.com

**Comment by OverseePublic** [comment]
Thanks Mike, that's kinda how I imagined it as well :)
