### ISSUE TITLE
cannot access view property from another view

### ISSUE THREAD

**Issue by ahoyahoy** [mobxjs/mobx-state-tree#473]
In typescript I cannot access `view1` from `view2`. Plain javascript working ok

    const Test = types
      .model('Test', {
        prop1: types.string,
        prop2: types.string
      })
      .views(self => ({
        view1() {
          return self.prop1 + self.prop2
        },
        view2() {
          return self.view1 + self.prop1
        }
      }))

> [ts] Property 'view1' does not exist on type '{ prop1: string; prop2:
> string; } & IStateTreeNode'.

**Comment by mattiamanzati** [comment]
You need to extract the views into functions :)

```
const Test = types
  .model('Test', {
    prop1: types.string,
    prop2: types.string
  })
  .views(self => {
    function view1() {
      return self.prop1 + self.prop2
    }
    function view2() {
      return view1() + self.prop1
    }

   return {
      get view1(){ 
         return view1()
      },
      get view2(){
         return view2()
      }
  })
```

**Comment by PMExtra** [comment]
```
const Test = types
  .model('Test', {
    prop1: types.string,
    prop2: types.string
  })
  .views(self => ({
    view1() {
      return self.prop1 + self.prop2
    },
  .views(self => ({
    view2() {
      return self.view1 + self.prop1
    }
  }))
```
I think this is another way.

**Comment by JoshMoreno** [comment]
Is there a better way now with Typescript 3?

Can the mobx-state-tree typing be improved to support something simple like the original example (pasted below for reference)?

 Or is this just a typescript limitation?

Happy to help, though my typescript knowledge is pretty limited as I just started learning it.

```
.views(self => ({
    view1() {
      return self.prop1 + self.prop2
    },
    view2() {
      return self.view1 + self.prop1
    }
  }))
```

**Comment by xaviergonz** [comment]
Just use this.view1

**Comment by xaviergonz** [comment]
Same can be done for actions btw

**Comment by JoshMoreno** [comment]
@xaviergonz That works! Thanks! I'll report back if I come across any issues using it in the wild.

To clarify for anyone needing the same thing:
```diff
.views(self => ({
    view1() {
      return self.prop1 + self.prop2
    },
    view2() {
-      return self.view1 + self.prop1
+      return this.view1 + self.prop1
    }
}))
```
