### ISSUE TITLE
getParentOfType(node, parentType)

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx-state-tree#477]
Will try to get the first parent found of a given node that matches a given type, or undefined if none found.

Basically I'm using getParent with different depths to achieve the same effect at the moment, but I'm starting to loose track :) (plus that implementation would be more resiliant to model changes)

**Comment by mweststrate** [comment]
Sounds useful Interested in attempting a PR? `mst-operations.ts` should be
a fine place to add it to

Op do 19 okt. 2017 om 20:36 schreef Javier Gonzalez <
notifications@github.com>:

**Comment by xaviergonz** [comment]
Right now I'm using the following code:
```js
export function getParentOfType<S, M>(target: IStateTreeNode, type: IType<S, M>): M | undefined {
  let currentNode = target;
  while (hasParent(currentNode)) {
    currentNode = getParent(currentNode);
    if (getType(currentNode) === type) {
      return currentNode as M;
    }
  }
  return undefined;
}
```

But I have a few doubts. What does getParent do? the docs say:
 * Returns the immediate parent of this object, or null.
but then the actual method does:
 return fail(`Failed to find the parent of ${getStateTreeNode(target)} at depth ${depth}`)

so, should getParent be changed so it returns null? should its docs be changed?

should the new method return null if not found? undefined? throw?
if throw, should there be a "hasParentOfType" equivalent?

**Comment by the-noob** [comment]
Just hit this issue with something like 
```JavaScript
const Model = types.model('Model', {
  name: types.string,
})
  .view((self) => ({
    get builder() {
       // return getParent(self); - this returns the `models` Map
       return getParent(getParent(self)); // - returns the Builder model
    }
  ));

const Builder = types.model('Builder', {
  models: types.map(Model)
});
```
Indeed the Map is the first parent but not exactly what I've expected.

**Comment by xaviergonz** [comment]
```js
export function getParentOfType<S, M>(target: IStateTreeNode, type: IType<S, M>): M | undefined {
  let currentNode = target;
  while (hasParent(currentNode)) {
    currentNode = getParent(currentNode);
    if (getType(currentNode) === type) {
      return currentNode as M;
    }
  }
  return undefined;
}
```

returns undefined if not found or the node if found. I'm just waiting for @mweststrate or @mattiamanzati to get me a hint on the desired semantics to adapt it and make a pull request

**Comment by mweststrate** [comment]
@xaviergonz sorry for late response! PR is welcome, I would go for the two function api version (`has`  and `get`), so that the `get`  variant can be strict-null typechecked which is quite convienient :)

**Comment by xaviergonz** [comment]
so then get method will throw if there's no such parent right?

**Comment by mweststrate** [comment]
yep

Op ma 15 jan. 2018 om 19:22 schreef Javier Gonzalez <
notifications@github.com>:

**Comment by optimatex** [comment]
@mweststrate but this approach leads to harder tests implementations since in my tests files I always have to pass the top store of the entire tree, else it will break test run. I followed the bookshop implementation:
```
.views(self => ({
    get appStore() {
      return getParent(self);
    },
  }))
```
is there any workaround to prevent throwing error?

**Comment by mweststrate** [comment]
hasParent?

Op za 10 mrt. 2018 16:19 schreef Pavel Poberezhnyi <notifications@github.com

**Comment by optimatex** [comment]
oh, I didn't see this method. Thanks and sorry for this

**Comment by robinfehr** [comment]
closing in favour of #719

**Comment by robinfehr** [comment]
on the todo list now.

**Comment by mweststrate** [comment]
PR has been merged to master now, so will be released soon
