### ISSUE TITLE
Mutation events for custom JSON patch

### ISSUE THREAD

**Issue by miguelocarvajal** [mobxjs/mobx-state-tree#481]
Is there any way to fire an event every time there’s a mutation as it’s currently done for patches?

Would like to use another format other than JSON patches to stream changes.

**Comment by mweststrate** [comment]
I think you could transform the json patch in anything more suitable? Also
note that all mobx utilities like `observe` will work with MST, but note
that they don't have a bubble up notion, so you would need to establish a
listener on each instance (in afterCreate for example)

Op za 21 okt. 2017 om 04:06 schreef Miguel O. Carvajal <
notifications@github.com>:
