### ISSUE TITLE
Circular type definition

### ISSUE THREAD

**Issue by ticruz38** [mobxjs/mobx-state-tree#484]
I'm using MST in my app and use composition a lot.
I found myself in that situation where I created a base model with action used by all other model in my tree:
```
t.model('ChildModel').props({
   loading: false,
   ready: false 
}).views( self => {
   const views = {
      get root(): ILayout {
         return getRoot(self)
      }
   }
   return views 
} )
```
Here child model reference to ILayout, and imagine ILayout got ChildModel as a child. then we get an infite loop in our type definition.
That can sounds silly but it took me a day to figure out why VSCode tsserver kept on crashing without a proper error message.
Maybe we could add a warning in the docs or type the library as such type reference would trigger an error?
Thanks for that library, it's a must! ))

**Comment by mattiamanzati** [comment]
Yeah, I think we had somethink similar in previous readme, maybe it got deleted accidentally.

https://github.com/mobxjs/mobx-state-tree/issues/417

Would you mind open a PR with those information? :)

**Comment by ticruz38** [comment]
ok I will, You do have documentation about type.late in the readme, but no warning on what could happen in such case.
Also it seems that old MST version would throw a typescript error when doing such circular type definition.

**Comment by mweststrate** [comment]
Lost track, are the docs fine now or do they still need updating?

**Comment by mweststrate** [comment]
Closed for inactivity
