### ISSUE TITLE
Async actions: generators vs async/await

### ISSUE THREAD

**Issue by luisherranz** [mobxjs/mobx-state-tree#490]
It looks like transpiled generators are not very performant. Airbnb has decided not to use them at all and benchmarks show it can perform up to 10x worse in slow mobiles than other async/await solutions based in promises. Even native generators perform 2-3x times worse than native promises:
https://github.com/airbnb/babel-preset-airbnb
https://github.com/MatAtBread/fast-async

I've been taking a look at how generators are used in MST for async actions. If I'm not mistaken, the main reason they are used over async/await is to avoid calling the I/O methods again when replaying/undoing/redoing and so on. Am I right? For that reason, using generators you can record the input and output data of those yielded promises, and don't call them again when going back and forward.

My question is, could the same behaviour be mimicked by async/await promises?

I've taken a look at this test of nested async actions:
```javascript
const Todo = types
  .model({
    title: 'get coffee',
  })
  .actions(self => {
    const uppercase = flow(function* uppercase(value) {
      const res = yield delay(20, value.toUpperCase());
      return res;
    });
    return {
      startFetch: flow(function* fetchData(kind) {
        self.title = yield uppercase('drinking ' + kind);
        return self.title;
      }),
    };
  });

Todo.startFetch('black');
```

And it's output:
```javascript
[
  { type: 'action', name: 'startFetch', id: 21, args: ['black'], rootId: 21 },
  { name: 'fetchData', type: 'process_spawn', id: 22, args: ['black'], rootId: 21 },
  {
    name: 'uppercase',
    type: 'process_spawn',
    id: 23,
    args: ['drinking black'],
    rootId: 21,
  },
  {
    name: 'uppercase',
    type: 'process_yield',
    id: 23,
    args: ['DRINKING BLACK'],
    rootId: 21,
  },
  {
    name: 'uppercase',
    type: 'process_return',
    id: 23,
    args: ['DRINKING BLACK'],
    rootId: 21,
  },
  {
    name: 'fetchData',
    type: 'process_yield',
    id: 22,
    args: ['DRINKING BLACK'],
    rootId: 21,
  },
  {
    name: 'fetchData',
    type: 'process_return',
    id: 22,
    args: ['DRINKING BLACK'],
    rootId: 21,
  },
];
```

What if, instead of using `flow` for the whole generator, we use async/await and `flow` for each awaited promise? Something like this:
```javascript
const Todo = types
  .model({
    title: 'get coffee',
  })
  .actions(self => {
    const uppercase = async value => {
      const res = await flow(delay, 20, value.toUpperCase());
      return res;
    };
    return {
      fetchData: async kind => {
        self.title = await flow(uppercase, 'drinking ' + kind);
        return self.title;
      },
    };
  });

Todo.fetchData('black');
```

Maybe we could:
 -  detect `process_spawn`: when MST actions return a promise. Nothing special to do here, just use `async` functions.
 - detect `process_yield`: when `flow` is called. It will internally call the promise and wait until it resolves.
 - detect `process_return`: when the promise called in `flow` is resolved. `flow` could keep track of that value (even if it throws), and return it or throw when replaying/undoing/redoing without calling the real function again.

What do you think? Could that make sense? Is there anything missing?

**Comment by mweststrate** [comment]
That is what I tried first, the problem is that you cannot hook into the
resolve moment (the continuation). So anything that happens *after* the
await completes is something you cannot intercept automatically. In other
words, we cannot automatically wrap the `self.title = ` in an action.

Op do 26 okt. 2017 om 11:29 schreef Luis Herranz <notifications@github.com>:

**Comment by luisherranz** [comment]
Ok, thanks @mweststrate! I'll try to study the code to understand it better :)

**Comment by luisherranz** [comment]
Ok, I get it now. It's impossible to embed the async function with `runWithActionContext` on each yielded (awaited) step again:
https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mobx-state-tree/src/core/flow.ts#L96

I guess we'd have to keep using generators and regenerator runtime!
