### ISSUE TITLE
[Bug] Middleware SandBox example is actually not working

### ISSUE THREAD

**Issue by karluc** [mobxjs/mobx-state-tree#496]
The [SandBox example](https://codesandbox.io/s/mQrqy8j73) provided on the [Middleware page](https://github.com/mobxjs/mobx-state-tree/blob/feature/separate-middleware/docs/middleware.md) is not working properly. New Todos should be created with an uppercased title but they are not.
Even though arguments are modified before passing the call to the next middleware, 
'addTodo' action is still called with original arguments not the modified ones.

**Comment by robinfehr** [comment]
PR added.

**Comment by karluc** [comment]
Don't you expect that applying middleware would override original arguments?
Calling `store.addTodo("cool huh?");` I would expect see "COOL HUH?" one the list but it's not.
The 'addTodo' method is still called with original value of the argument not the uppercased one.
Modyfing line from:
`next({ ...call, args: [call.args[0].toUpperCase()] });`
to:
`next({ ...call, args: call.args = [call.args[0].toUpperCase()] });`
fixes the example but not sure why.

Please verify it.

Thanks for your great work with MobX and MST.

**Comment by robinfehr** [comment]
i guess your opening the old link you posted. 
to change a codesandbox it must be forked and therefore there is a new link in the middleware.md.

**Comment by karluc** [comment]
I opened the new one:
https://codesandbox.io/s/88jrqlzm1l
Check for yourself.

**Comment by robinfehr** [comment]
ah indeed. i see what you mean - the action gets the baseCalls arguments.
let's open an issue and fix it :) good catch! thank you.

**Comment by robinfehr** [comment]
#731
