### ISSUE TITLE
Is adding dangling to reference a good idea?

### ISSUE THREAD

**Issue by cpunion** [mobxjs/mobx-state-tree#497]
I have a scene need get data in a long progress, e.g. those steps:

1. Fetch chat sessions, it has a `toUserId` and `lastMessageId` field.
2. Fetch users referenced in sessions and relations.
3. Fetch messages references in sessions (Maybe sync with timestamp)

Sometimes I have many objects it references other objects that didn't fetched, but I need display first. I must build a complex structure to save those temporary reference relations, and update the reference after fetching completed.

If reference is dangle-able, it's very simple. e.g.:

```javascript
const Message = types.model('Message', {
  id: types.identifier(),
  content: types.string
})

const Session = types.model('Session', {
  id: types.identifier(),
  lastMessage: types.reference(Message, { dangling: true }) // Make it dangle-able
})

const Store = types.model('Store', {
  messages: types.map(Message),
  sessions: types.map(Session)
}).actions(self => ({
    addSession(session) {
        self.sessions.put(session)
    },
    addMessage(message) {
        self.messages.put(message)
    }
}))

const store = Store.create({
  messages: {},
  sessions: {}
})

store.addSession({
    id: 's1',
    lastMessage: 'm1'
})

console.log(store.sessions.get('s1').lastMessage) // Right now it raises error, can we let it return null? Or returns 'm1' to let us fetch it?

store.addMessage({
    id: 'm1',
    content: 'hello'
})

console.log(store.sessions.get('s1').lastMessage) // return correct Message object
```

Is it a good idea? or have you a good solution for this?

[Full demo code](https://mattiamanzati.github.io/mobx-state-tree-playground/#src=import%20React%20from%20%22react%22%0Aimport%20%7B%20types%20%7D%20from%20%22mobx-state-tree%22%0Aimport%20mobx%20from%20%22mobx%22%0Aimport%20%7B%20inspect%2C%20render%20%7D%20from%20%22mobx-state-tree-playground%22%0A%0A%0Aconst%20Message%20%3D%20types.model('Message'%2C%20%7B%0A%20%20id%3A%20types.identifier()%2C%0A%20%20content%3A%20types.string%0A%7D)%0A%0Aconst%20Session%20%3D%20types.model('Session'%2C%20%7B%0A%20%20id%3A%20types.identifier()%2C%0A%20%20lastMessage%3A%20types.reference(Message%2C%20%7B%20dangling%3A%20true%20%7D)%0A%7D)%0A%0Aconst%20Store%20%3D%20types.model('Store'%2C%20%7B%0A%20%20messages%3A%20types.map(Message)%2C%0A%20%20sessions%3A%20types.map(Session)%0A%7D).actions(self%20%3D%3E%20(%7B%0A%20%20%20%20addSession(session)%20%7B%0A%20%20%20%20%20%20%20%20self.sessions.put(session)%0A%20%20%20%20%7D%2C%0A%20%20%20%20addMessage(message)%20%7B%0A%20%20%20%20%20%20%20%20self.messages.put(message)%0A%20%20%20%20%7D%0A%7D))%0A%0Aconst%20store%20%3D%20Store.create(%7B%0A%20%20messages%3A%20%7B%7D%2C%0A%20%20sessions%3A%20%7B%7D%0A%7D)%0A%0Ainspect(store)%0A%0Astore.addSession(%7B%0A%20%20%20%20id%3A%20's1'%2C%0A%20%20%20%20lastMessage%3A%20'm1'%0A%7D)%0A%0Aconsole.log(store.sessions.get('s1').lastMessage)%0A%0Astore.addMessage(%7B%0A%20%20%20%20id%3A%20'm1'%2C%0A%20%20%20%20content%3A%20'hello'%0A%7D)%0A%0Aconsole.log(store.sessions.get('s1').lastMessage)%0A)

**Comment by mattiamanzati** [comment]
I'ts usually not a good idea, we have been discussing over #172 instead :)
