### ISSUE TITLE
Modifying a snapshot ?

### ISSUE THREAD

**Issue by geowarin** [mobxjs/mobx-state-tree#498]
Hello and thanks for MST!

Currently the `clone` docs state:

```
Tip: clone will create a literal copy, including the same identifiers. To modify identifiers etc during cloning, don't use clone but take a snapshot of the tree, modify it, and create new instance
```

The only problem is when you do `getSnapshot()` you get an immutable object.

Current workaround:

```ts
JSON.parse(JSON.stringify(tree))
```

Is there a better way ?

**Comment by mattiamanzati** [comment]
If your object is only 1 level deep, you can use Object.assign({}, getSnapshot(tree)), if it is more level deep, you could do that while editing only the identifiers that needs to be changed, to avoid spairing memory cloning objects :)

**Comment by geowarin** [comment]
Unfortunately, my tree is 3 levels deep and I need to modify attributes on the leaves :sweat:

**Comment by mweststrate** [comment]
In that case you can probably best use something like `lodash.deepClone`,
stringify / parse is a very expensive way to clone an object tree.

Op di 31 okt. 2017 om 12:45 schreef Geoffroy Warin <notifications@github.com

**Comment by geowarin** [comment]
Thanks @mweststrate, I'll keep that in mind.
Maybe we could add this tip in the documentation?
Would you like me to open a PR?

**Comment by mweststrate** [comment]
Not sure, depends on where it would fit :) As a tip with `getSnapshot`?

Op di 31 okt. 2017 om 15:24 schreef Geoffroy Warin <notifications@github.com

**Comment by geowarin** [comment]
Or with `clone`

**Comment by mweststrate** [comment]
@geowarin PR is welcome :)
