### ISSUE TITLE
Cerebral JS and Mobx-State-Tree are friends :)

### ISSUE THREAD

**Issue by christianalfoni** [mobxjs/mobx-state-tree#499]
Hi there!

So www.cerebraljs.com has bindings for mobx-state-tree and it is being used in a refactor of a project, will share more on that later.

I have a question related to how state changes instantly syncs with the components. I completely understand the promise of views to always be in sync with the mobx-state-tree, but in Cerebral it actually makes sense not to do so. Let me explain.

In Cerebral state changes are made through a generic state API, which is why mobx-state-tree can just be added.

```js
// Action
function changeThis ({ state }) {
  state.set('some.state', 'foo')
}
```

Now, this action is part of a sequence of actions usually, so:

```js
[
  changeThis,
  changeThat,
  thenThis
]
```

This is just Cerebrals composable nature. The thing is... Cerebral knows when you run sync and async logic. That means when the sequence above runs there is really no reason to do a new render until all the actions has been run, as all of them are sync. I have the following scenario now:

```js
// This is the same as actions, just using function factories called "operators" in cerebral
export default [
  set(state`preferences.currentTab`, props`tab`),
  equals(props`tab`), {
    paymentInfo: [
      set(state`preferences.paymentInfo.isLoading`, true),
     // etc.
    ],
    otherwise: []
  }
]
```

Now... the thing is that the `preferences.paymentInfo.isLoading` state is set to `false`. Which means that when I change the tab state there might be a flicker on the payment tab, because the `isLoading` state is not set until after it.

With default Cerebral model this is not the case, because it flushes out the changes made when it makes sense from a sync/async standpoint. My question now is:

Is it possible in `mobx-state-tree` to buffer up notifications to components about render? Something like `protect` and `unprotect`. That way Cerebral could use its execution events to manage when multiple sync actions are done. 

Again... I understand the promise of keeping it completely in sync, but as I hope to get through with this example is that it makes sense to do multiple sync state updates without notifying the components :)

Thanks for all the work on this, very awesome stuff!

**Comment by mattiamanzati** [comment]
Uhm, MST uses action to perform "batched" updates, are you wrapping all of your changes into an action or just applying them in unprotected mode? :)

**Comment by christianalfoni** [comment]
@mattiamanzati Aha! So mobx-state-tree does do this... great! :) The thing is that Cerebral is a state and side effects management tool, so it is not using the mobx-state-tree actions. Do you know how it batches this up "under the hood"? Is it the `protect/unprotect` that handles this batching? Cause now I do it for every cerebral action, but this could be done at the execution level instead... allowing multiple sync actions to do state changes before "unprotecting" again :)

**Comment by mweststrate** [comment]
`unprotect` makes sure you can change the model without using an action. `mobx.action` /  `mobx.runInAction` takes care of the batching. Note that using `unprotect` will bypass any middleware.

...But you could theoretically do something like this. Not sure if it is helpful or plain ugly :). It does trigger middleware, But not for all middlewares it will result in something useful (e.g. undo/ redo would handle this properly, but logging middleware will probably print useless stuff)

```javascript
const Batchable = types.model({}).actions(self => ({
   __runInBatch(f) {
       f()
   }
}

const User = types.compose(types.model(/* stuff */), Batchable)

User.__runInBatch(arbitrarilyFunction)
```

**Comment by mattiamanzati** [comment]
Yeah, should do the trick :)
https://github.com/cerebral/cerebral/pull/1178/files

**Comment by christianalfoni** [comment]
Great, let me explore this :) Thanks for your help!

**Comment by christianalfoni** [comment]
Closing it for now, will reopen if any questions
