### ISSUE TITLE
[Question] get JSON back from mst

### ISSUE THREAD

**Issue by jiyinyiyong** [mobxjs/mobx-state-tree#500]
Quite often we see warning like this when data is consumed by antd Table:

```
Warning: Failed prop type: Invalid prop `dataSource` of type `object` supplied to `Table`, expected `array`.
```

I tried `.toJSON()` but it's undefined. So I have to use `.concat()` somehow. But what's the right way to get JSON from it?

**Comment by mweststrate** [comment]
getSnapshot. Or if the component is observer;  change the prop type, mst
arrays are objects

**Comment by jiyinyiyong** [comment]
noticed there is actually a `.toJSON()` method in the runtime. but TypeScript tells me that no method called `.toJSON()`. Maybe it's because the type is `types.maybe`? Or a bug in types.

**Comment by mattiamanzati** [comment]
.toJSON is just an alias for getSnapshot, so you should use that instead :)

**Comment by jiyinyiyong** [comment]
BTW do you have any idea on dealing with null values in the tree? Currently I have to use:

```js
s.roles ? getSnapshot(s) : []
```

**Comment by mattiamanzati** [comment]
You could use isStateTreeNode(v) ?  GetSnapshot(v) : V :)

**Comment by jiyinyiyong** [comment]
Since we have data from both MobX and mobx-state-tree. Now we have a problem:

```js
export function toJSObject(obj: any) {
	if (!obj) {
		return obj;
	}

	if (obj.toJS) {
		return obj.toJS();
	} else if (obj.toJSON) {
		return obj.toJSON();
	} else {
		return obj;
	}
}
```

**Comment by mweststrate** [comment]
Didn't read previous messages, but why not `isStateTreenode(v) ?
getSnapshot(v) : isObservableObject(v) ? toJS(v) : etc...`

Op ma 6 nov. 2017 om 05:36 schreef jiyinyiyong <notifications@github.com>:

**Comment by jiyinyiyong** [comment]
Do `isStateTreenode` and `isObservableObject` handle `null` issues? I got errors when I was trying those functions. (Didn't go to details...)

**Comment by mweststrate** [comment]
They should return `false` on `null`

Op ma 6 nov. 2017 om 12:08 schreef jiyinyiyong <notifications@github.com>:

**Comment by jiyinyiyong** [comment]
not going to dig into the code yet. but it confused my why mobx and mox-state-tree has two different data types. plus I got an error:
![image](https://user-images.githubusercontent.com/449224/32529906-18c29ade-c476-11e7-9702-fe741b6501e4.png)

**Comment by chenyong** [comment]
I think it remains a problem on my side to convert data among mobx-state-tree, mobx, and plain JavaScript object(need to be extensible). Our app has grown to near 200 `.ts(x)` files with nearly 30 models defined. It made me think whether it's the right way to use all of them inside.

**Comment by chenyong** [comment]
Got an idea, since MST is using MobX, `toJS` method in MobX should work for MST data too...

https://github.com/mobxjs/mobx/blob/016b75f651839e0287a11b265a9b1ce964012c5f/src/api/tojs.ts#L13
