### ISSUE TITLE
IObservableArray.push cannot be used with TypeScript

### ISSUE THREAD

**Issue by asfernandes** [mobxjs/mobx-state-tree#501]
Note the necessary usage of ` as any`. Otherwise it requires the passed object to have the `remove` property.

```ts
const Database = types
	.model({
		alias: types.string,
		id: types.identifier(types.number)
	})
	.actions(self => ({
		remove() {
			getRoot(self).removeDatabase(self)
		}
	}));

const DatabaseStore = types
	.model({
		databases: types.array(Database)
	})
	.actions(self => ({
		test() {
			(getRoot(self) as IDatabaseStore).databases.push({ id: 3, alias: 'database 3' } as any);
		},

		removeDatabase(database: typeof Database.Type) {
			destroy(database)
		}
	}));
```

**Comment by mikecann** [comment]
Yep :( This has been pointed out quite a few times and is apparently a limitation of Typescript currently.

**Comment by mattiamanzati** [comment]
Map and ObservableArray type definition could be ideally be updated to support also snapshot type alongside the real type; you'd need to provide a extension over the IObservableArray with all methods like .push(snapshot: S)
Closing as it's being tracked on #85
