### ISSUE TITLE
Example middlewares not found

### ISSUE THREAD

**Issue by Hkmu** [mobxjs/mobx-state-tree#503]
[https://github.com/mobxjs/mobx-state-tree/blob/master/middleware/README.md](https://github.com/mobxjs/mobx-state-tree/blob/master/middleware/README.md) is 404

**Comment by mattiamanzati** [comment]
Uhm, can you please point out where that link is present so I can update accordingly? :)

**Comment by notnarb** [comment]
Looks like like something small overlooked when switching to a lerna directory structure

---

https://github.com/mobxjs/mobx-state-tree/blame/master/README.md#L45

as of right now this points to `middleware/README.md` when it appears to have moved to `packages/mst-middlewares/README.md`

`docs/middleware.md` also points to `../middleware/README.md` (different relative, but same absolute path) and should likely also be changed to `packages/mst-middlewares/README.md`
