### ISSUE TITLE
lazy reference/ lazy load type

### ISSUE THREAD

**Issue by robinfehr** [mobxjs/mobx-state-tree#509]
yesterday we had a little discussion on gitter about a new type, a lazy reference / lazy load type.
the problem was brought up by @ssured (I'm trying to write it down)
please correct me if I got something wrong.

_the purpose of this issue is to trigger some discussion around such a type, the examples aren't a proposal (not even sure if they'd work) but should help to understand the problem._

I'll add the description below since it's easier to understand when having read the examples.

**a lazy reference variant:**
```js

const AuthorModel = types.model('Author', {
    id: types.identifier(),
    name: types.string
})

const PostModel = types.model('Post', {
   id: types.identifier(),
   author: types.lazyReference(
      // would automatically add the author to the author array,
      // fetch would return a promise
      AuthorModel, (snapshot) => fetchAuthorFromAPI(snapshot.author) 
   )
})

const StoreModel = types.model('store', {
    posts: types.array(PostModel),
    authors: types.array(AuthorModel)
})

const postsStore = StoreModel.create({
    posts: [
       {
            id: '36de15ed-af0a-43b9-bbc2-7f32f6124b6b',
            author: 'f593b8a8-a829-44a3-8f96-85a34399a86b'
        }
    ]
})
```

**a lazy load variant:**
```js
const AuthorModel = types.model('Author', {
    id: types.identifier(),
    name: types.string
})

const PostModel = types.model('Post', {
   id: types.identifier(),
   author: types.lazyLoad(
       // could maybe lazy load any type
       types.reference(AuthorModel), function* () {
            const author = yield fetchAuthorFromAPI(snapshot.author);
            postsStore.authors.push(author);
            return author;
       }
   )
})

const StoreModel = types.model('store', {
    posts: types.array(PostModel),
    authors: types.array(AuthorModel)
})

const postsStore = StoreModel.create({
    posts: [
       {
            id: '36de15ed-af0a-43b9-bbc2-7f32f6124b6b',
            author: 'f593b8a8-a829-44a3-8f96-85a34399a86b'
        }
    ]
})
```

**the problem:**
we have a yet not filled store of e.g. posts and authors. while filling the store partially we have a reference which does yet not exists. we're trying to find a solution to load the reference of the author async and add it to the store so it can be resolved while adding posts.

**use case:** 
when we, for example, have a big bunch of posts and fetch them batch wise from an API, we'd so far have to write that using types.maybe(types.reference(AuthorModel)). using `@observer` the frontend would now react to the newly added posts and render them without an author.

**Comment by mattiamanzati** [comment]
Yes, please see #172  :)

**Comment by ssured** [comment]
I had some thoughts after the discussion. Loading data from an API belongs outside of MST, but we need the feedback of what's in the MST to know what to load. 

This is what I came up with https://gist.github.com/ssured/e1b89a2271dd783bcd2002615607d35f
Put some effort to explain what happens in the comments.

I'd like to hear your feedback

**Comment by robinfehr** [comment]
I like the idea of parsing the models and create the actions accordingly. for the actual use case, it fits well. 

where it gets more difficult is when we emit the fetch within a circular type. I guess there a type as in #172 discussed, would be handier since we'd have the context already and would know where to put/set the resolved value from the fetch within the tree. 

a bit trickier even when the to be fetched data is a circular type and therefore saved as such to the backend. we'd need the corresponding counterpart on the server that would be able to resolve just as much as needed for the currently emitted fetch.

smth like the custom type and a backend like
https://github.com/mattiamanzati/gendux from @mattiamanzati

**Comment by robinfehr** [comment]
i like the approach of parsing the models to then fetch the matching reference. it suits well for the above-described use case. 

as far as I've understood your gist -  we'd get the actions to fetch on the root level of the tree (context self). which would mean it would get tricky as soon we'd have to work with circular types. since the fetch does not work within deeper contexts but on the root.

with a custom type though as described within #172 we'd always be context-aware and would know where to put the fetched data.

it gets even more tricky if the to be fetched data is also circular since then the data would be saved as such also to the backend. there then we'd need the counterpart to the frontend which could resolve an ID within the tree and deliver as much as needed of the parental structure. 

I guess the https://github.com/mattiamanzati/gendux from @mattiamanzati  could then be a start of such a project.

as always - please correct if I'm wrong. :)

**Comment by ssured** [comment]
I have thought some more about this. The current way it's implemented is right; there is no need to change. What I'd like to suggest instead is to add an extra `action` on the root MST node. This action will be called if an unresolved reference is encountered. Doing it this way allows the user to add their own logic on what to do next.

Implemententation proposal:
- add optional `onUnresolvedReference(Type, reference, originatingPath) { ... }` on the root element
- trigger this action from this line https://github.com/mobxjs/mobx-state-tree/blob/99e092db6cdec8926022a55c01cdcd4bca133668/packages/mobx-state-tree/src/types/utility-types/reference.ts#L44
- if the optional action is defined, use the return value of the action as the value returned, instead of the `fail()` 

@robinfehr @mweststrate @mattiamanzati what do you think of this approach? I'm willing to dive into learning TypeScript to make a PR, but do want to know if this is the right / an acceptable direction. Thanks

**Comment by mweststrate** [comment]
Update: it should be possible to implement lazy references in user space now by using the custom references introduced in 1.2.1

**Comment by ssured** [comment]
@mweststrate thanks, that _is_ the way I expected references to work. Awesome, dankjewel!
