### ISSUE TITLE
Update docs to reflect breaking changes in #43

### ISSUE THREAD

**Issue by hampusohlsson** [mobxjs/mobx-state-tree#51]
Trying to get started with mobx-state-tree, but it looks like PR #43 introduced some changes that breaks the code examples in examples folder and README? 

`mapOf`, `arrayOf` etc is no longer working. I guess I should use something like
```
import { createFactory, types, action } from 'mobx-state-tree';
const { map, array, referenceTo } = types;
```

**Comment by mattiamanzati** [comment]
Yes, docs are WIP atm, so please refer to the tests atm :)

**Comment by mweststrate** [comment]
Updated the docs and examples in 0.2.0
