### ISSUE TITLE
.preProcessSnaphot gets called twice

### ISSUE THREAD

**Issue by ssured** [mobxjs/mobx-state-tree#510]
```javascript
import { types as t } from 'mobx-state-tree';

let callCount = 0;
const PreProcessCountTest = t
  .model('PreProcessCountTest', {
    callCount: t.number,
  })
  .preProcessSnapshot(snapshot => ({ ...snapshot, callCount: ++callCount }));
const preProcessCount = PreProcessCountTest.create({});
console.log(callCount); // = 2
console.log(preProcessCount.callCount); // = 2
```

Expected callCount to be 1

Hit something similar in production code too, but could not easily reproduce that case. My gut feeling is that it's related to the above. What I hit on production was `.preProcessSnapshot` triggering a Maximum call stack size exceeded error. Removing the `.preProcessSnapshot` code fixed that error in production code.

**Comment by mattiamanzati** [comment]
This was already raised as question; it is right, preprocess should be pure as mentioned in the docs.
It will be exectued twice; first pass for checking, second pass for actual value assignation :)
