### ISSUE TITLE
types.frozen fails to freeze non plain objects in development

### ISSUE THREAD

**Issue by elektronik2k5** [mobxjs/mobx-state-tree#511]
Hi guys and thanks for making MST! :)

I'm tackling an issue with ```types.frozen```, where [in development the value is ```deepFreeze```ed](https://github.com/mobxjs/mobx-state-tree/blob/981f7f7a832ea4aef2e97c4f2017e1e87ad17453/packages/mobx-state-tree/src/types/utility-types/frozen.ts#L20). This fails (only in development) for things like DOM elements.

Now, correct me if I'm wrong: ```types.frozen``` is an escape hatch for me to store whatever I want, as long as I promise it is immutable. Meaning, it is _assumed_ to be frozen, and is my responsibility as a user to not violate this contract/assumption.

**In that case, why is it deepFreeze applied?**

I don't think it's really relevant, but just in case: my use case is to keeping a reference to a DOM node, which I'm wrapping. Basically it's a facade for an HTML form. I used this ugly hack to lie to MST and managed to reference the form:
```ts
const FilterStore = model('FiltersStore', { filterFormElement: frozen, })
  .actions((self: any) => {
    function setFiltersFormElement(formEl: MaybeHTMLFormElement) {
      if (formEl) {
        // Ugly ugly ugly workaround for dev environment, where frozen values
        // are recursively frozen: freeze to bypass Object.isFrozen() check
        self.filterFormElement = { node: Object.freeze({ nest: formEl, }), }
      }
    }
    function beforeDestroy() {
      self.filterFormElement = null
    }
    return { setFiltersFormElement, beforeDestroy, }
  })
```
Then I access the form like so: ```filterStroreInstance.filterFormElement.node.nest```

I'm looking for a non hackish workaround.
Can we disable ```deepFreeze```ing and trust the user? Should we wrap deepFreeze's Object.freeze in try/catch and silently ignore failures?
If we don't want to trust the user, should we add another type, like 'immutable' - which would be the user's  responsibility (as opposed to frozen's current behaviour)?
Any other ideas?

**Comment by d4rky-pl** [comment]
I believe the `types.frozen` is an escape hatch that works only if you promise it's both _immutable_ and, more importantly, _serializable_ (to JSON). As far as I know DOM elements are neither.

I'd say things like Form element are actually volatile state because if you get a snapshot from your store, save it somewhere and then re-apply, the reference to the DOM object would have to be reattached by hand anyway.

This is how we usually solve it (apologies for lack of Typescript notation, not my language yet):

```javascript
.actions((self) => {
  let filterFormElement;
  return {
    setFiltersFormElement(form) {
      filterFormElement = form
    },
    beforeDestroy() {
      filterFormElement = null
    },
    andThenWhateverYouWantToDo() {
      // instead of self.filterFormElement use
      filterFormElement
    }
  }
})
```

**Comment by mattiamanzati** [comment]
Yep, @d4rky-pl got it right :)

**Comment by elektronik2k5** [comment]
Thanks guys! Perhaps it is worth mentioning in the documentation that frozen must be:

1. serializable 
2. ```Object.freeze()``` is recursively applied to it in development and skipped in production mode
