### ISSUE TITLE
reference to an union

### ISSUE THREAD

**Issue by robinfehr** [mobxjs/mobx-state-tree#514]
a common case I see is using types.compose for multiple abbreviations of a base model and then putting the abbreviations into a types.map using the types.union (which now needs dispatcher). 
if we now want to refer to this union - we have a problem  - or maybe it's just me experiencing this.

```js
const PersonModel = types.model('PersonModel', { id: types.identifier(), name: types.string });
const PersonWithChildModel = types.compose(
    PersonModel,
    types.mode('_PersonWithChildModel', {
        childName: types.string
    })
).named('PersonWithChildModel')

const StoreModel = types.model('StoreModel', {
    persons: types.map(
                       types.union(
                          (snapshot) =>{
                              if (snapshot.childName) return PersonWithChildModel
                              return PersonModel
                          } ,
                          PersonModel,
                          PersonWithChildModel
                     )
}
```

what we'd need to refer to them is something like that:

```js
types.late(() => 
    types.union(
        (snapshot) => {
            if (snapshot.childNamme) return types.reference(PersonWithChildModel)
            return types.reference(PersonModel)
        }
```
this all works fine as long as we're working with the observable objects but as soon as we try to resolve a serialized reference like an UUID, the snapshot does not contain any props anymore. since we can't determine the type of the model anymore we can't use just the id to resolve it, we'd need for example the path.

**Comment by mweststrate** [comment]
As long as id's are not colliding, it should all work fine if you take the following approach where you make sure you reuse the union type, instead of redeclaring it. Types are a first class concept, so that is why it is usually better to reuse them, rather than redefine them. Identifier resolving compares types by reference, not structurally. 

```
const PersonOrPersonWithChildModel = types.union(
                          (snapshot) =>{
                              if (snapshot.childName) return PersonWithChildModel
                              return PersonModel
                          } ,
                          PersonModel,
                          PersonWithChildModel
                     )

const StoreModel = types.model('StoreModel', {
    persons: types.map(PersonOrPersionWithChildModel)
})
```

and then later on just use:

`types.reference(PersonOrPersonWithChildModel)`

**Comment by robinfehr** [comment]
cool - thanks a lot!
