### ISSUE TITLE
[Question] Define a model with arbitrary extension properties

### ISSUE THREAD

**Issue by tylerlong** [mobxjs/mobx-state-tree#520]
Let's say I have the following data:

```json
{
    "name": "...",
    "count": 10,
    "x-hello": "...",
    "x-world": "...",
    "x-whatever": "...",
...
}
```
Properties **without** `x-` prefix are fixed and required.

Properties **with** `x-` prefix are arbitrary and optional.  A property is valid as long as it starts with `x-`.

I want to model it. And I tried the following:

```js
import * as R from 'ramda'

let MyModel = types.model({
name: types.string,
count: types.number
})

let Extension = types.map(types.string)
Extension = types.refinement(Extension, snapshot => {
  return R.all(R.startsWith('x-'), R.keys(snapshot)) // make sure all keys start with `x-`
})

MyModel = types.compose(MyModel, Extension)
```

However the last line throws exception:

```
Error: [mobx-state-tree] Typename should be a valid identifier: AnonymousModel_map<string, (undefined | string)>
    at fail (/Users/tyler.liu/src/react/swagger-data-entry-app/node_modules/mobx-state-tree/dist/mobx-state-tree.js:56:11)
    at new ModelType (/Users/tyler.liu/src/react/swagger-data-entry-app/node_modules/mobx-state-tree/dist/mobx-state-tree.js:2518:13)
    at ModelType.cloneAndEnhance (/Users/tyler.liu/src/react/swagger-data-entry-app/node_modules/mobx-state-tree/dist/mobx-state-tree.js:2527:16)
    at /Users/tyler.liu/src/react/swagger-data-entry-app/node_modules/mobx-state-tree/dist/mobx-state-tree.js:2782:21
    at Array.reduce (<anonymous>)
    at Object.compose (/Users/tyler.liu/src/react/swagger-data-entry-app/node_modules/mobx-state-tree/dist/mobx-state-tree.js:2781:10)
```

Any help is appreciate.

To be more specific:

- Can I compose a `model` with a `map`?
- If a `map` is not viable, what solution should I try?

**Comment by mweststrate** [comment]
Obviously the error is not very clear, but the second argument to `compose`
should be a `types.model` as well. if the set of possible keys is known
when generating the type, you can simply produce a props object with
optionals in it. Otherwise you need put either a map in the model, or a
frozen if your attributes can't be mutated directly

P.s. note types.optional exists for optional types.

Op di 14 nov. 2017 om 14:36 schreef Tyler Long <notifications@github.com>:

**Comment by tylerlong** [comment]
@mweststrate  Thank you for the response.

The set of possible keys is unknown, unfortunately. I only know that they start with `x-`.

What I want is something like regex for property name:

```js
types.model({
name: types.string,
count: types.number,
/x-[a-z]+/: types.string
})
```

I know a workaround:

```js
let Extension = types.map(types.string)
Extension = types.refinement(Extension, snapshot => {
  return R.all(R.startsWith('x-'), R.keys(snapshot)) // make sure all keys start with `x-`
})

types.model({
name: types.string,
count: types.number,
extensions: Extension
})
```

But I want `x-` properties to be on the same level as `name` and `count`.

Let me check `frozen` to see if it fit my needs.

Any more comments are welcome!

**Comment by tylerlong** [comment]
Nope, I confirm that `frozen` is not what I want.

For now I want to go with a workaround:

```json
{
    "name": "...",
    "count": 10,
    "x-extension-fields": {
        "x-hello": "...",
        "x-world": "...",
        "x-whatever": "...",
...
     } 
}
```

Then I can model `x-extension-fields` as a refined map.

Let me know if you know any better solutions.
