### ISSUE TITLE
[solved] Actions not triggering when using models imported via symlink.

### ISSUE THREAD

**Issue by ashemah** [mobxjs/mobx-state-tree#521]
Hi guys, I'm just gonna dump this here in case it helps anyone else in future. I don't have time to get together a simple test case unfortunately.

My scenario is I am writing a React app with MST as the core data structure. I wanted to share my models between my server (Firebase functions) and my frontend so I put my models in a directory in the server project and created a symlink to it in the frontend project.

The issue is when I did this everything compiled fine and I could use my models but triggering MST actions on the models would not trigger any @observer renders. This caused me to pull my hair out for a bit until I worked out what had caused this to fail. Moving my models to a directory in the frontend project and then symlinking that to one in the back end (reversing it basically) fixed the issue. Which is fine as I don't need the reactive stuff in the backed.

So yeah a weird issue. I wonder if it was due to MST or just a Babel/Webpack pathing issue when following the symlink. Anyone seen similar?

**Comment by mweststrate** [comment]
Yes, this issue is extensively described in the mobx repo, and you should have seen warnings in your logging that multiple mobx instances are active. For details see: https://github.com/mobxjs/mobx/issues/1082
