### ISSUE TITLE
How to use mst models as Generic Type for classes in Typescript

### ISSUE THREAD

**Issue by renganatha10** [mobxjs/mobx-state-tree#522]
HI Guys, I am trying to create Generic service class which uses the MST model as generic model

Use Case

I am creating a class which has following method
 *  findById(model: T, id: string) => Promise<IType> .

 * findAllWhere((model: T, id: string, condition: string) =>  Promise<IType[]>

T is IModelType from From MST

So I created a Interface
``` 
import { IType } from 'mobx-state-tree';
interface IAPIService<T> {
    findById(model: T, id: string) => Promise<typeof T.Type>
    findAllWhere((model: T, id: string, condition: string) =>  Promise<IType>
}
```

Throws ts error at Promise<IType> as `[ts] Generic type 'IType<S, T>' requires 2 type argument(s).`

In Similar fashion I created A Generic Class which implements the above function as 

```
import Worksheet from './../firebaseCollections/worksheet';
import IFirebaseService from './IFirebaseService';
import { findById } from './../../firebase/index';
import { IModelType } from 'mobx-state-tree';

class WorksheetService<T extends IModelType> implements IFirebaseService<T> {
  findById(model: T, id: string) {
    return findById(model, id);
  }
}

export default new WorksheetService<typeof Worksheet>();
```

Throws ts error at T extends IModelType as ` [ts] Generic type 'IModelType<S, T>' requires 2 type argument(s)`

Not sure how to use the IModelType and IType ?

**Comment by mweststrate** [comment]
Given the names of the method I would expect:

```
findAllWhere((model: T, id: string, condition: string) =>  Promise<(typeof T.Type)[]>
```

For the `IModelType` you can use `IModelType<any, any>` I think, I don't think it doesn't really matter. But for reference, in MST typeings, in general, `S` referes to the *S*napshot type, and `T` to the instance *T*ype. So, `S` is the raw json type, and `T` the type including all views actions etc.

For clarity, I would call `model` in your api `modelType`, and identify that `T extends IType<any, any>` in your definitions (if I understand them correctly :))
