### ISSUE TITLE
Detaching and replacing a child node without nulling field

### ISSUE THREAD

**Issue by EdonGashi** [mobxjs/mobx-state-tree#523]
Hi, I have a quick question. Given this scenario:

```
t.model('Parent', {
  child: t.model('Child', { ... someProps })
}
```

I have a parent model that holds a child model. In an action I need to replace the child with a new instance, yet keep the old child alive (detached).

I tried these two combinations:
```
detach(self.child) // Getting an exception: Cannot assign 'null' to property child ....
self.child = Child.create(...)
```

```
const child = self.child
self.child = Child.create(...)
detach(child) // Exception again: Node is no longer alive.
```

It would be desirable to not mark the prop as nullable. Have I missed something?

Thanks! Fantastic library btw, so many benefits since I started organizing my data this way!

**Comment by mweststrate** [comment]
@EdonGashi properties can be marked as nullable by using `types.maybe`
