### ISSUE TITLE
mst-example-boxes demo not working

### ISSUE THREAD

**Issue by carlosagsmendes** [mobxjs/mobx-state-tree#525]
Hi,

I'm trying the `mst-example-boxes` but it is not working.

When I run it I don't get any error, and the two initial boxes are rendered.

But the UI seems to be 'disconnected'. I cannot add new boxes, move boxes or use the `!` to generate boxes.

I tried it on Chrome, Canary and Firefox (all using MacOs).

I'm I missing something?

Thanks in advance.

**Comment by mweststrate** [comment]
Fixed by @SDSLeon. Thanks :)
