### ISSUE TITLE
how to define temporary, observable state.

### ISSUE THREAD

**Issue by jzlxiaohei** [mobxjs/mobx-state-tree#526]
some states like `loading` are meaningless for snapshot( json data ), it is just a side effect of fetch action, however are useful for UI display.

how to define a `volatile but observable`  state ?

**Comment by mattiamanzati** [comment]
Please note that you can also use "postProcessSnapshot" hook to remove unwanted properties :)

**Comment by grncdr** [comment]
I think you could use `.extend` and an unprotected observable. The pattern I'm trying out right now is query objects

```typescript
import { observable, unprotect } from 'mobx'

SomeModel
  .extend(self => {
    const loading = unprotect(observable(false))
    return {
      views: {
        get loading() {
          return loading.get()
        },
      },
      actions: {
        async fetchData() {
          loading.set(true)
          try {
            return (await fetch(...))
          } finally {
            loading.set(false)
          }
        },
      },
    }
  })
```

I have no idea if this will cause problems with the rest of MST though, I've only started using mobx yesterday 🙃

**Comment by jzlxiaohei** [comment]
@mattiamanzati thanks. I noticed that, but i think this kind state is common。Anyway, thanks,  I can accept it.
