### ISSUE TITLE
create a deep readonly clone/view of a node?

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx-state-tree#529]
Is there a way to create a deep-readonly clone of a node? this is, a node where all its actions (and actions of subnodes) basically throw when invoked, thus making the node immutable.

Basically I want to expose to some functions the node data, but I don't want them messing with it. It would be possible to create a readonly type without actions and then a write type that extends the other type with the missing actions, but doing that for 30 types (the subnodes) is no fun... (plus I'm not sure how I could declare a property that can be both of the readonly and of the read-write type at the same time, an union?)

Maybe the key here is to create a middleware that checks of some extra parameter of the root node is set to readonly and then throws upon attempting to run an action?

Would be great if there was some way out of the box to do this though. Something like:
`immutableNodeView(node) // creates an immutable view of the given node + subnodes`

**Comment by mweststrate** [comment]
I think something like this should do exactly what you want:

``` 
function immutableNodeView(node) {
    const result = clone(node)
    addMiddleware(result, (call, next) => {
       console.warn("tried to invoke action " + call.name)
        // don't call next
    })
    return result
}
```

If it does, feel free to contribute a readonly middleware to the the middlewares package :)

**Comment by xaviergonz** [comment]
Thanks, that should do it. Is there a way to avoid the cloning though? Something like creating a node reference so they share the same data yet the middlewares applied to them are different.

**Comment by mweststrate** [comment]
Nope, it is a *tree*. So no node can have two parents. Also, how could the
rest of it be readonly and not readonly at the same time :)

Op wo 29 nov. 2017 om 21:04 schreef Javier Gonzalez <
notifications@github.com>:

**Comment by xaviergonz** [comment]
a view wrapper that substitutes all actions of the node by methods that
throw and returns wrapped properties using getters ? dunno 😀

**Comment by mweststrate** [comment]
yes, but how do you then invoke hte original actions?

**Comment by xaviergonz** [comment]
using the original read-write unwrapped node instead of the read-only wrapped one I guess

**Comment by mweststrate** [comment]
Ehh... but without cloning there is no such thing as "original" and "not-original" ;-). Anyway, I think the solution provided above is sufficient until proven otherwise :)

**Comment by xaviergonz** [comment]
I mean something like this (pseudo-ish code which probably would use a proxy really)

```js
function createReadonlyNode<NodeInstanceT>(nodeInstance: NodeInstanceT): NodeInstanceT {
  // for each property or view of nodeInstance
  // getter of this[propName] = () => 
  // if a immutable basic value (string, number): return it as is
  // if a map: return an readonly map view of the original map
  // if an array: return a readonly array view of the original array
  // if a node return createReadonlyNode(nodeInstance[propName]);

  // for each action of nodeInstance, choose either a or b.
  // getter of this[actionName] = () => { throw new Error() };
}

const myBook = Book.create({....});
myBook.setTitle('hello world'); // ok
const myReadonlyBook = createReadonlyNode(myBook);
myReadonlyBook.setTitle('hello again'); // fails with an exception
```

**Comment by mweststrate** [comment]
Ah. Yeas that is kinda out of scope of this library. And something solvable
with typings as well if you want, (just create a readonly interface of the
involved types, and the compiler will make sure you can only use it
readonly).
Op do 30 nov. 2017 om 19:41 schreef Javier Gonzalez <
notifications@github.com>:
