### ISSUE TITLE
it should not be possible to change state outside an action

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#53]
question: does that also hold for applySnapshot etc?

**Comment by mweststrate** [comment]
update relevant tests in `test/action.ts`

**Comment by mattiamanzati** [comment]
question: does that also hold for applySnapshot etc?
@mweststrate IMHO it should'nt, applySnapshot is implicitely an action

**Comment by mweststrate** [comment]
See #68 for a proposal, using `protect`

The goal to achieve is that actions are transactional; e.g. replaying actions brings us best to the same state. To ensure that if a tree is protected, not even `applySnapshot` can update it (unless of course applySnapshot is called from inside an action of the model)

**Comment by mweststrate** [comment]
Fixed in 0.2.2
