### ISSUE TITLE
Identifier cache 'undefined' in production mode

### ISSUE THREAD

**Issue by dargue3** [mobxjs/mobx-state-tree#531]
>Note: This was working perfectly fine in development, only after putting my `create-react-app` in production mode does this error occur.

Here's the error I'm seeing:
![image](https://user-images.githubusercontent.com/13652794/33103679-901a0560-ced8-11e7-9227-5cb369c66309.png)

It is referencing an error caused on this line: https://github.com/mobxjs/mobx-state-tree/blob/cc0211ffa3d6dbf9ef14c6a72365e7ccea2700b0/packages/mobx-state-tree/src/core/identifier-cache.ts#L25

I'm taking a snapshot of a model and storing it in the parent. The two models look like the following:

```javascript
const Child = t
  .model({
    id: t.identifier(t.string),
    name: t.string,
  });

const Parent = t
  .model({
    original: t.frozen,
    children: t.map(Child),
  })
  .actions((self) => {
    function makeCopy(child) {
      self.original = getSnapshot(child);
    }
  }); 
```

The first time I run `parent.makeCopy(child)` everything works fine, but any later attempts to store a snapshot of that child will result in this error.

Could be something to do with how caching works in production builds of React or Create React App?

**Comment by mattiamanzati** [comment]
Hi! Are you running on 1.1.0? If so, can you please try on a previous version? I think in 1.0 worked and this issue is related to another one :)

**Comment by dargue3** [comment]
Yep, downgraded to `1.0.0` and the problem is gone.
