### ISSUE TITLE
Dynamically replace action with Jest's mock function

### ISSUE THREAD

**Issue by sunkibaek** [mobxjs/mobx-state-tree#532]
When I test MST model with Jest, I sometimes need to replace an action with a mock function dynamically.

Are there any ways to achieve this?

**Comment by mweststrate** [comment]
You can literally replace it on the instance under test (each instance stores it's own actions in MST). Of if you want to go fancy you could inject function implementations through the environments mechanism. But that is probably overkill in most cases.

**Comment by andrusek** [comment]
Howdy,
   I was wondering if you could provide and example of how one would replace an action with a jest mock function by replacing the action on the instance of the store directly.  I tried this and was getting errors:

TypeError: Cannot assign to read only property '...funciton name.....' of object '[object Object]'


So for example if I had a store like this:

testStore = types.model('testStore', {
    name: types.string
}).actions((self) => {
	function setName(aName) {
		self.name = aName;
	}


	return {
		setName
	};
});


And say I had a jest test something like this:

it('testSomething', () => {
      let aStore = TestStore.create({name: 'fred'});
     aStore.setName = jest.fn()
         :
})
	
this code would give me the  error noted above.  What would be the way to replace the method would it be in the when doing the create?

**Comment by sunkibaek** [comment]
This issue has been resolved at https://github.com/mobxjs/mobx-state-tree/pull/690
