### ISSUE TITLE
Various errors only occur in production

### ISSUE THREAD

**Issue by marbemac** [mobxjs/mobx-state-tree#536]
We have noticed several errors (both handled and unhandled) that only manifest themselves in production mode. Because behavior in production mode differs from development, mobx-state-tree becomes difficult to debug and ship with confidence.

1. https://github.com/mobxjs/mobx-state-tree/issues/531

I understand the issue itself might fixed, but the underlying issue probably is not (why did this occur in production and not development, and how can this sort of discrepancy be prevented in the future or elsewhere in the codebase?).

2. "Cannot add an object to a state tree if it is already part of the same or another state tree"

I have created a simple example repository with reproduction instructions here: https://github.com/marbemac/mobx-state-tree-playground. This unhandled exception only occurs in production mode, which makes it difficult to debug and track.

There were a couple more examples that I will try to add to that repository over the next couple of days.

**Comment by homura** [comment]
looks like same as #513

**Comment by mattiamanzati** [comment]
Yep, in that issue there's a great explanation of why the error occurred; we are now setting up tests to be run both in dev and production mode to ensure they behave the same way :)

**Comment by marbemac** [comment]
Ah I missed it, sorry! Closing, will follow that issue and try out master - running the tests in both environments sounds like a great idea :).
