### ISSUE TITLE
Change in volatile state attribute doens't result in computed value getting updated?

### ISSUE THREAD

**Issue by w-** [mobxjs/mobx-state-tree#539]
So i have something akin to the following:

```js
const MasterThingModel = types.model('MasterThing', {
	blah: 0,
	foo: 0,
	things: types.array(Thing)
})
.actions( self => {
	function onCreate(){
		onAction(self, self.handleUpdate, true)
	},
	function handleUpdate(){
		/*
		code that basically sets  blah and or foo on all child things
		*/
	}
});

const ThingModel = types.model('Thing', {
	bar: 100,
})
.extend( self=> {
	let localBar = 0;
	let localFoo = 0;
	return {
		views: {
			get newCalc(){
				return self.bar * localBar - localFoo;
			}
		},
		actions: {
			function set(key, val){
				// setter logic here
			}
		}
	}
})
```

1. a master thing which has some local attributes including one which is an array of things
2. the child thing has some variables representing volatile state
3. whenever a parent attribute is updated it will update the volatile state of the child object

The issue i have is that the view/ computed value newCalc() on Thing is never updated if only the volatile state variables are updated.

The way I'm seeing this is because I have them wired up to react components and the values in the components aren't updating.

Is this expected?

If not what am I doing wrong?

If yes, what can I do to get the computed  value to update if one of the volatile state variables updates?

I'm also open to other approaches to what I'm trying to do here.

cheers

**Comment by mattiamanzati** [comment]
Yes, that's expected because your local state is'nt observable :)
You need to import observable from the mobx package and then use the .get or .set methods over the observable value :)

```
const ThingModel = types.model('Thing', {
	bar: 100,
})
.extend( self=> {
	let localBar = observable(0);
	let localFoo = observable(0);
	return {
		views: {
			get newCalc(){
				return self.bar * localBar.get() - localFoo.get();
			}
		},
		actions: {
			function set(key, val){
				localBar.set(val)
			}
		}
	}
})
```

**Comment by w-** [comment]
thanks for the reply. I did attempt this but forgot to use the `.get()` method on the observable value. As a result it did not work.

The approach I ended up taking was to set attributes directly on the type and then remove them using `postProcessSnapshot()`
