### ISSUE TITLE
Redux dev tools doesn't show subsequent calls to async generator actions

### ISSUE THREAD

**Issue by will-stone** [mobxjs/mobx-state-tree#541]
Firstly, thanks for the great work on this project. I'm only just getting into MST but I'm loving the structure over standard MobX, especially as decorators aren't allowed when using MobX and Create-React-App and so stores usually end-up looking a mess; MST seems to be the cure for that.

Anyway, I degress..

I've connected MST to Redux Devtools using

```js
connectReduxDevtools(require('remotedev'), store)
```

One of my sub-stores uses an async action to get some data (not much different to the example):

```js
const Dashboards = types
  .model({
    data: types.optional(types.array(Dashboard), []),
    state: types.optional(
      types.enumeration('State', ['idle', 'fetching', 'done', 'error']),
      'idle'
    )
  })
  .actions(self => ({
    fetchDashboards: flow(function*() {
      self.state = 'fetching'
      try {
        const response = yield getDashboards()
        yield wait(1000) // to give time to show loaders
        self.data = response
        self.state = 'done'
      } catch (error) {
        console.error('Failed to fetch dashboards', error)
        self.state = 'error'
      }
      return self.data.length
    })
  }))
```

Redux devtools is working for the `fetchDashboards` action, however it only shows the state going from "idle" to "fetching" but doesn't show any subsequent changes in this function. I don't think I'm doing anything incorrectly but let me know if you need more detail.

**Comment by mweststrate** [comment]
The reason for that is that this middleware is based on `onAction`. Which only fires on the root action invocation, and not on any actions / flows that are spawned from that. ([source](https://github.com/mobxjs/mobx-state-tree/blob/d44f142b367353dec76ef8da5c88bfeccf93bda2/packages/mobx-state-tree/src/middlewares/on-action.ts#L211). 

The reasoning behind that is that for replayability, you only want to record 'root' invocations, as during replay you don't want to replay any of the other actions (after all, replaying the root invocation should in itself already result in spawning those). 

However, if you have a different use case for the middleware, it should be easy to write your own middleware, or extend the current one, by not basing it on `onAction`, but `addMiddleware` instead, in which case you can intercept all action / flow calls and act on that. You could take [actionLogger middleware](https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mst-middlewares/src/action-logger.ts) as basis, for example

**Comment by will-stone** [comment]
ok, thanks for the explanation.

**Comment by mweststrate** [comment]
(btw, I nowadays close questions immediately after answering them on
github, as it is otherwise impossible to see which questions are answered
already. It is suboptimal, so feel free to reopen if there are follow up
questions)

Op di 28 nov. 2017 om 20:46 schreef Will Stone <notifications@github.com>:

**Comment by kindy** [comment]
I just do a hack like this(@mweststrate  is this fine?):

```js
model.actions(self => ({
  a: flow(function *(){
    self.state = 1;
    yield a;
    self.state = 0;
    self.trackAction();
  }),

  trackAction(fake) {
    if (!fake) {
      setTimeout(() => self.trackAction(true), 0);
    }
  },
}));
```
