### ISSUE TITLE
1.2.0 release on npm does not contain volatile or the new reference syntax

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx-state-tree#545]
I can't find any trace of volatile or the new reference syntax on the new npm release :(

**Comment by mweststrate** [comment]
Uh oh, will check in an hour..

**Comment by mweststrate** [comment]
Identifier was not changed, reference was, it supports a second argument now

**Comment by xaviergonz** [comment]
Yeah sorry, just noticed and changed the title and content of the issue. Still neither ref nor volatile are on the npm package typedefs or code.

**Comment by mweststrate** [comment]
Ok, should be fixed now! booboo in release script
