### ISSUE TITLE
Using data from another store

### ISSUE THREAD

**Issue by vaclav-zeman** [mobxjs/mobx-state-tree#550]
Hi, I'm fairly new to the MobX world and I'm having trouble understanding how I should structure my data with the MST stores.

Example:
I have a `/users` endpoint that returns `[{ id: int, name: string, countryId: int }]`. 
Then there's a `/countries` endpoint that returns `[{ id: int, name: string }]`.
What I'm doing is that I create separate Countries and Users store and fetch the data there. I wish I would be able to transform the users objects in the Users store (in .views() preferably) to contain also the country name from the other store (so it's `{ id: int, name: string, country: string }`).

Is that somehow possible without having the method in the root store?

**Comment by mweststrate** [comment]
Did you check identifiers & (custom) references? They can typically be used for these kind of constructions

**Comment by vaclav-zeman** [comment]
Thanks! I think I'll use that.
