### ISSUE TITLE
Have `types.model` accept a Typescript interface?

### ISSUE THREAD

**Issue by cdeutsch** [mobxjs/mobx-state-tree#551]
How feasible is it to have `types.model(...)` accept a Typescript `interface` (type)?

I realize you can do the reverse: define your `types.model` then do `typeof Todo.Type`, but in my experience it's way more common to have the typescript interface already defined.

For instance I want a model that observes a `Location` from `History`
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e4a7331e99970b559938af34100c263a45deb761/types/history/index.d.ts#L26

It's already defined, so it seems redundant to have to define a model for it.

Something like:
```js
export const ViewStore = types.model({
  location: types.parseTypescript(Location, {}),
})
```

If this could be solved I'd love to switch to using `mobx-state-tree`. Having an opinionated library for Mobx stores is a great idea 👍

**Comment by mattiamanzati** [comment]
Unfortunately it can't be done, because interfaces are only a TypeScript abstract concept and cannot be converted to any JavaScript code to be read by the library :/

**Comment by cdeutsch** [comment]
Ah, that makes sense. Bummer. 

Thanks for the quick response!

**Comment by mattiamanzati** [comment]
Just a side-note, TypeScript has an ASST, so you could write a precompiler that given a file with only interfaces does that job! :)
