### ISSUE TITLE
[Question] recursive data types in MST, how?

### ISSUE THREAD

**Issue by chenyong** [mobxjs/mobx-state-tree#554]
Two pieces of recursive data:

```json
[
  "a",
  "b",
  "c",
  [
    "a",
    "b",
    "c",
    [
      "a",
      "b",
      "c"
    ]
  ],
  "d"
]
```

```json
{
  "type": "expr",
  "children": {
    "aaaa": {
      "type": "expr",
      "children": {
        "bbbb": {
          "type": "leaf",
          "text": "demo"
        }
      }
    },
    "bbbb": {
      "type": "leaf",
      "text": "demo2"
    }
  }
}
```

what's the model for each of them? I thought a bout that, for the array case, maybe I can use `types.union` with `types.late`. The second one is tougher, there might be several other keys besides `type children text`, and other ids other than `aaaa` `bbbb`, how to define such models in MST?

**Comment by the-noob** [comment]
Based on what I understand from the question I would define different models
```JavaScript
const Leaf = types.model('Leaf', {
  text: types.string,
});

const Node = types.model('Node', {
  text: types.string,
  // in your example `children` looks like a map (`{ }`), not array (`[ ]`)
  children: types.map(types.union(Node, Leaf)) 
});
```
(Sorry if I got some typos/invalid code, can't test now)

**Comment by artikq** [comment]
with `types.late(() => type)` you can define recursive structures.
`const TreeEntry = types.model('TreeEntry', {  
  id: types.identifier(types.number), 
  name: types.maybe(types.string), 
  children: types.optional(types.array(types.late(() => ComponentEntry)), []),  
});`
