### ISSUE TITLE
export CoreType<S, T>, Type<S, T> for adding custom-primitives?

### ISSUE THREAD

**Issue by devdoomari** [mobxjs/mobx-state-tree#555]
I've just ran into an issue of introducing 'bignumber' for a project.
digging for a solution, I found that types.Date has a solution for this:

```
export const DatePrimitive: IType<number, Date> = new CoreType<number, Date>(
    "Date",
    TypeFlags.Date,
    (v: any) => typeof v === "number" || v instanceof Date,
    (v: number | Date) => (v instanceof Date ? v : new Date(v))
)
;(DatePrimitive as any).getSnapshot = function(node: INode) {
    return node.storedValue.getTime()
}
```

I think it would be awesome if mobx-state-tree could export CoreType<S, T> and Type<S, T> for a general use case, so I can write my custom 'decimal-primitive' MST type.

Thanks!

**Comment by devdoomari** [comment]
sorry just found out that CoreType is exported by: 'mobx-state-tree/dist/types/primitives'

closing!

**Comment by mweststrate** [comment]
You can't import from there, that could result in bundling mst twice
depending on your setup. However, you can use references with custom setter
/ getter to achieve the same (might be less efficient though)

**Comment by devdoomari** [comment]
@mweststrate oh ok - so that wasn't a solution...

I'll open a PR

**Comment by mweststrate** [comment]
Did you try the reference option?
