### ISSUE TITLE
[question on internals] what does "TypeFlags" do?

### ISSUE THREAD

**Issue by devdoomari** [mobxjs/mobx-state-tree#556]
related: #555 

I'm trying to create a custom-primitive for the Decimal class (from decimal.js)

So far, I was trying to do something similar to DatePrimitive, until I saw this:
```
export const DatePrimitive: IType<number, Date> = new CoreType<number, Date>(
    "Date",
    //
    TypeFlags.Date, // <---------------???
    //
    (v: any) => typeof v === "number" || v instanceof Date,
    (v: number | Date) => (v instanceof Date ? v : new Date(v))
)
;(DatePrimitive as any).getSnapshot = function(node: INode) {
    return node.storedValue.getTime()
}
```
I suspected that MST was using TypeFlags for serializing/deserializing state trees, but couldn't find any meaningful usage of TypeFlags.

Is there any internal usage for the TypeFlags? 
Would it be dangerous if I set it to something arbitrary?

Thanks!

**Comment by robinfehr** [comment]
further discussions within #558
