### ISSUE TITLE
[help-needed] Trying to come up with a custom-type reference

### ISSUE THREAD

**Issue by devdoomari** [mobxjs/mobx-state-tree#558]
I'm trying to create a Decimal.js MST primitive, but the following code compiles but fails at runtime:

```typescript
import {
  IType,
  CoreType, // I've added a custom MST repo for a quick attempt
  TypeFlags,
} from 'mobx-state-tree';
import Decimal from 'decimal.js';

export const DecimalPrimitive: IType<string | number, Decimal> =
  new CoreType<string | number, Decimal>(
    'Decimal',
    TypeFlags.Reference,
    (v: any) => (
      typeof v === "string"
      || typeof v === "number"
      || v instanceof Decimal
    ),
    (v: string | Decimal) => (v instanceof Decimal? v : new Decimal(v)),
  );
```

Here's the model definition part:
```typescript
export const Wallet = types.model<WalletType>('Wallet', {
  balance: types.reference(DecimalPrimitive),
})
```
And this is what I get when I try to access someWallet.balance in a reactJS component:

```
render() {
   return (
     <div> { wallet.balance.toNumber() } </div>
   );
}

// --> Failed to resolve reference of type Decimal: '50' (in: /balance)
```

Any ideas on how I should proceed?
Thank you!

**Comment by mweststrate** [comment]
Just wondering, does this work?

```
const DecimalPrimitive = types.reference(Decimal, {
  get(value: string | number) {
    return new Decimal(value)
  },
  set(value: Decimal) {
    return value.toString()
  }
)

export const Wallet = types.model<WalletType>('Wallet', {
  balance: DecimalPrimitive
})
```

**Comment by devdoomari** [comment]
the "Decimal" is imported from 'decimal.js' npm library (not related to MST)

**Comment by devdoomari** [comment]
@mweststrate 
I kinda passed the 'reference' error by not using types.reference at all
(just occurred to me that I don't have wrap types.reference to use 'DatePrimitive').

So this is the next attempt:

```typescript
export const DecimalPrimitive: IType<string | number, Decimal> =
  new CoreType<string | number, Decimal>(
    'Decimal',
    TypeFlags.String,
    (v: any) => {
      return (
      typeof v === "string"
      || typeof v === "number"
      || v instanceof Decimal
    )},
    (v: string | Decimal) => (v instanceof Decimal? v : new Decimal(v)),
  );
```
**The code fails with:**
```
at path "/balance" snapshot `"1"` is not assignable to type: `Decimal` (Value is not a Decimal)
```
when I do:
```typescript
export const Wallet = types.model<WalletType>({
  currency: types.enumeration('currency', values(CURRENCY_UNITS)),
  balance: DecimalPrimitive,
  locked: DecimalPrimitive,
})
const _a = Wallet.create({
  currency: CURRENCY_UNITS.BTC,
  balance: new Decimal(1),
  locked: new Decimal(1),
});
```

**Comment by mweststrate** [comment]
For my original attempt, `Decimal, { // <-- can't do thi`, does it work if you use `types.frozen` there instead? (probably gives a typescript type error, but that is fixable)

**Comment by mweststrate** [comment]
@mattiamanzati what do you think the cleanest solution is here? exposing core type might be a bit risky at this stage, but maybe we should have an api around that?

**Comment by mattiamanzati** [comment]
Exporting the CoreType is absoultely a bad idea IMHO, I would go for this solution as suggested by @mweststrate  :)

```
const DecimalPrimitive = types.reference(types.string, {
  get(value: string | number) {
    return new Decimal(value)
  },
  set(value: Decimal) {
    return value.toString()
  }
)

export const Wallet = types.model<WalletType>('Wallet', {
  balance: DecimalPrimitive
})
```

**Comment by mweststrate** [comment]
only drawback is that inferred type of DecimalPrmitive is incorrect here.
An upcast to `IType<string, Decimal>` should fix that

Op vr 8 dec. 2017 om 18:02 schreef Mattia Manzati <notifications@github.com

**Comment by devdoomari** [comment]
@mweststrate @mattiamanzati 
I tried
```
import {
  types,
} from 'mobx-state-tree';
import Decimal from 'decimal.js';

export const DecimalPrimitive = types.reference(types.string as any, {
  get(value: string | number) {
    console.error(`
    ----------------------------
      DecimalPrimitive(REF):: get
      ${value}
    ----------------------------
    `);
    return new Decimal(value)
  },
  set(value: Decimal) {
    console.error(`
    ----------------------------
      DecimalPrimitive(REF):: set
      ${value}
    ----------------------------
    `);
    return value.toString()
  }
});

export const Wallet = types.model<WalletType>({
  balance: DecimalPrimitive,
  // ...
})
```
but this throws:
```
Reason: Error: [mobx-state-tree] Error while converting `{"currency":"BTC","balance":"1","locked":"1"}` to `AnonymousModel`:
at path "/balance" snapshot `"1"` is not assignable to type: `reference(string)` (Value is not a valid identifier, which is a string or a number), expected an instance of `reference(string)` or a snapshot like `reference(string)` instead.
```

**Comment by devdoomari** [comment]
@mweststrate @mattiamanzati 
I've set up a demo repo at: https://github.com/devdoomari/mst-decimal-demo

**Comment by mattiamanzati** [comment]
When doing Wallet.create, you should provide the decimal value as string instead of instance of Decimal.js :)

**Comment by devdoomari** [comment]
@mattiamanzati
I've changed Wallet.create as you said, and it works!

I've updated the demo to include a 'set' action, but it fails with:
```
Error: [mobx-state-tree] Error while converting `"3"` to `reference(string)`:
snapshot `"3"` is not assignable to type: `reference(string)` (Value is not a valid identifier, which is a string or a number), expected an instance of `reference(string)` or a snapshot like `reference(string)` instead.
```

**Comment by mattiamanzati** [comment]
Same concept, when setting you need .toString :)

**Comment by devdoomari** [comment]
@mweststrate  @mattiamanzati 
ok...
welp this string <--> Decimal conversion is getting tedious...
how about providing a way to create 'cust

**Comment by mweststrate** [comment]
@devdoomari will look into that!

**Comment by FredyC** [comment]
I am pretty much wondering about something similar. I want to use `mobx-react-form` and have a reference to form instance as a *volatile* property on the model. I am kinda stuck on what `types.*` to use for that. I tried `types.reference` with constructor of that class, but that's not working.

I think it kinda makes sense to have some untyped _type_ that is allowed as volatile since it doesn't need to be (de)serialized.

**Comment by mattiamanzati** [comment]
Have you checked out volatile state from the docs? :)

**Comment by FredyC** [comment]
@mattiamanzati I am not sure what you are referring to. Even the volatile state has to be typed if I am not mistaken?

**Comment by mattiamanzati** [comment]
No, it could be literally anything, it's just a scoped variable from the language perspective, and it's initialized either by a lifecycle method or by an action called externally

**Comment by FredyC** [comment]
@mattiamanzati Can you show me an example? I would like to use `types.optional` to initialize that value, but I don't know what type to supply to it.

```js
import MobxReactForm from 'mobx-react-form'
const model = types.model({...})
  .volatile(self => {
    form: types.optional(types.?(MobxReactForm), setupForm)
  })
```

**Comment by robinfehr** [comment]
custom types merged.

**Comment by FredyC** [comment]
In case someone is wondering what does that mean (like me), it's described in [API docs](https://github.com/mobxjs/mobx-state-tree/blob/master/API.md#typescustom).
