### ISSUE TITLE
Pause and Restart snapshot generation and tracking

### ISSUE THREAD

**Issue by sanketsahusoft** [mobxjs/mobx-state-tree#559]
Thanks for this amazing library! 🙌 

Need some help / suggestions! We are using MST to track (x, y) of mouse for a resizing element.

We would like a way to pause the snapshot generation when the Resize Handles are being dragged. Is there any way to pause and resume this to imitate plain MobX behaviour on the models?

What could be the most performant way to do that?

**Comment by robinfehr** [comment]
Do you want to stop that to be able to undo/redo to correct states- therefore ignore the states during the drag? Or is there another reason you would want to do that?

**Comment by sanketsahusoft** [comment]
For undo / redo, I am using my custom hooks. So that's sorted!

I am looking to pause that for performance improvements.

**Comment by mattiamanzati** [comment]
Uhm, have you got a setXY method or do you set them directly? There isn't a way to stop it as now, but you could make X and y a volatile prop, and sync it over the real X and y props, there is no way ATM to stop snapshots :/

**Comment by sanketsahusoft** [comment]
Thanks @mattiamanzati!

I will research a bit more and get back. Either we will fork MST or move to MobX. Tomorrow is a critical day.

Thanks a lot :-)

**Comment by robinfehr** [comment]
@sanketsahusoft I left you some tips on gitter :) e.g. translate instead of top,left (css - wise)

**Comment by sanketsahusoft** [comment]
@robinfehr Great! Let me check that. Thanks :-)

**Comment by mattiamanzati** [comment]
Also as said before consider upgrading to latest versions if not did yet, there are several perf improvements in v. >= 1.2 :)

**Comment by mweststrate** [comment]
Closing, question seems answered
