### ISSUE TITLE
How to list the observables of a mounted component?

### ISSUE THREAD

**Issue by sanketsahusoft** [mobxjs/mobx-state-tree#568]
We use `component.render.$mobx.observers` to list the observers on a mounted component. The same strategy is used by the MobX DevTools.

But, this debugging is disconnected from MST and so it makes it really hard to find out the real variable in the MST tree.

Any inputs on how to easily debug would be appreciated.

**Comment by sanketsahusoft** [comment]
Closing this as we wrote our own iterator to find out the Observables for a component and it's path!

**Comment by mweststrate** [comment]
Sounds cool! Something shareable :)?

Op do 21 dec. 2017 om 14:32 schreef Sanket Sahu <notifications@github.com>:

**Comment by sanketsahusoft** [comment]
A bit too dirty at the moment, we will share it after tidying it up a bit. :-)
