### ISSUE TITLE
[Feature Request] atomic reactions

### ISSUE THREAD

**Issue by KBorders01** [mobxjs/mobx-state-tree#571]
I am currently using reactions to perform cascading updates, like the following simple example:

1. `maxValue` and `currentValue` are observable numbers
2. When `maxValue` changes, a reaction fires that runs `if(this.currentValue > this.maxValue) this.currentValue = this.maxValue`

This reaction runs synchronously and has no side effects, similar to a derivation. However, the reaction that sets `currentValue` to `maxValue` emits a separate patch. Replaying patches would lead to a glitch state where `this.currentValue > this.maxValue`.

Is there a way to make reactions execute atomically with the action that triggers them to produce a single patch, or would it be reasonable to add this functionality? (I am new here, so forgive me if this request is more appropriate for mobx itself rather than MST. I am very interested in helping to add this feature.)

**Comment by mweststrate** [comment]
Reactions are already atomic, however patches are not (they don't have a build in grouping mechanism). But, if you apply the patches withing a single action, you should not be able to observe the glitches. Potentially middleware could be used to do the grouping of patches automatically for you. (For inspiration: the undo manager middleware does the same)

**Comment by KBorders01** [comment]
Perfect, thanks. I will check out the undo manager middleware.
