### ISSUE TITLE
types.map invoke merge with array

### ISSUE THREAD

**Issue by demoran23** [mobxjs/mobx-state-tree#573]
So my API returns an array of users, and I've got my UserStore all set up to accept it.

``` javascript
const props = {
  users: optional(types.map(MinimalUserInfo), {}),
};
```

I've got a test that ensures the data from my api makes ito to the store:

``` javascript
  test.only("fetch users and make them available via users", async () => {
    const { users } = store;
    await store.fetchVillagers();
    expect(fetchVillagers.mock.calls.length).toBe(1);

    expect(users.size).toBe(1);
    expect(users.has(bobbyV.Id)).toBe(true);
    const storeBobby = users.get(bobbyV.Id);
    expect(storeBobby.FirstName).toBe(bobbyV.FirstName);
  });
```

This test **fails** when I pass my villagers into merge:
``` javascript
import { flow, getEnv } from "mobx-state-tree";

export default (self) => {
  const actions = {};

  actions.fetchVillagers = flow(function* () {
    const villagers = yield getEnv(self).fetchVillagers();
    self.users.merge(villagers);
  });

  return actions;
};
```

But it passes when I pass my `obj` into merge
``` javascript
import { flow, getEnv } from "mobx-state-tree";
import { keyBy } from 'lodash';

export default (self) => {
  const actions = {};

  actions.fetchVillagers = flow(function* () {
    const villagers = yield getEnv(self).fetchVillagers();
    const obj = keyBy(villagers, v => v.Id);
    self.users.merge(obj);
  });

  return actions;
};
```

What's happening is the [ObservableMap is detecting that it is an array](https://github.com/mobxjs/mobx/blob/de51957a321ac5df098f270afc0e84d54643e627/src/types/observablemap.ts#L290), and it's setting the key and value to undefined:

``` javascript
            else if (Array.isArray(other))
                other.forEach(function (_a) {
                  console.log("merge array foreach", _a.Id);
                    var key = _a[0], value = _a[1];
                    console.log(`${key}:${value}`);
                    return _this.set(key, value);
                });
```

I expect that types would step in and say "hey, I know what you're supposed to be, and I know you've got an identifier, so I'm going to do this whole 'create an map from an array` for you."  

I don't really understand how the existing array implementation is supposed to work.  Is it expecting that the array is comprised of arrays of key value properties?  like `[ [ key, value ], [key, value] ]`?

**Comment by mweststrate** [comment]
Correct, this is to mimic the ES6 map api that iterables as being collections formatted like `[key, value]`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map
