### ISSUE TITLE
[Feature Request] Initialize volatile as part of .create function

### ISSUE THREAD

**Issue by yordis** [mobxjs/mobx-state-tree#574]
Using this shortcut

```js
.volatile(self => ({
    something: null
  }))
```

I can later say `store.something` but when I use `.create` there is no way I could initialize my volatile values, I will have to be calling setters after I create the store.

Ideally I would want to do 

```js
const store = Store.create(properties, volatiles, environments)
```

Other than shortcut is that in my current requirements, I am saving the firebase instance on the volatile key called `firebase` I want to be able to do this

```js
afterCreate() {
  self.firebase.auth().onAuthStateChanged(...)
},
```

so I can automatically change the value of my `currentUser`

**Comment by mweststrate** [comment]
I can see why this might be useful. But it can also be confusing, when deserializing or applying changes, or time travelling etc; these initial volatiles states are not captured and restored. Unlike properties which are always stored in snapshots, or environments, which are not stored, but only applicable to the root of the tree and for that reason will be preserved as well. 

So if you do something like `stores.todos.push(new Todo({ done: false }, { someVolatileProp: 1 }))` it becomes hard to reason what happens with `someVolatileProp` if you do things like time travelling, or applying json snapshots in the future etc. However, if you interact with volatile properties using actions, the same questions might rise, but it is more explicit what process-wise you are trying to achieve, and the behavior is more apparent from code.

**Comment by yordis** [comment]
@mweststrate I guess I would do `store.subscribeToAuthChange()` or something like that for this situations?

I have really strong deps with that volatile so I dont want to be doing `if(self.firebase)` everywhere in my code because I am preventing that somebody forgot to initialize it right after the store creation.

**Comment by robinfehr** [comment]
+1 recently faced that too, but in our case, it could even be an abbreviation of the current volatile. we'd need it for static non tracked values only.

at the moment we only add such values on '.create()'
therefore there'd be no problem with the time traveling and the serialization since it could simply be skipped.

we currently use a from the time traveling skipped action to add to to the volatiles.

**Comment by mattiamanzati** [comment]
"we'd need it for static non tracked values only"
Why not use environment for that? Seems like a good use case :)

**Comment by robinfehr** [comment]
@mattiamanzati thought about them too combined with a view but don't think that's a good idea in this case since the structure contains circular types. On creation of a new child I guess I'd overwrite the env var like that.

it's more like a static property of the model.

**Comment by yordis** [comment]
For now, just use `environments` for the most cases and `create a view getter` for the environment, this should work.


@robinfehr What about you?

**Comment by robinfehr** [comment]
for our case, this is no longer a need.

since the volatile states must be recreated in the case of a reload for example where a serialized store gets loaded from a server, it makes more sense to create them via actions on the fly (e.g. mounting of a component) instead of on the creation of a model and on the fly.

@mattiamanzati @mweststrate could be closed until it comes up again I guess.

**Comment by yordis** [comment]
Well to be honest the example about subscribing to firebase it is quite handy.

I am cool with the workaround but definitely something needed

**Comment by aksonov** [comment]
@robinfehr Creation via actions doesn't work well for trees. For example I want to use MST for new react-native-router-flux version and it plays very very well here (to maintain navigational tree and state) but I can't pass volatile state recursively - (React Component are volatile state) and should do dirty hacks like `init` action and some recursive `create` action that calls model create and then calls `init`.

**Comment by yordis** [comment]
@aksonov do you want me to reopen the issue?

**Comment by robinfehr** [comment]
@aksonov could you maybe open a thread on spectrum with a codesandbox attached? - like that we could have a little forth and back about it. it's a bit too high level to give a good answer.

**Comment by robinfehr** [comment]
@yordis there is a new issue opened for that already #730
