### ISSUE TITLE
observe is never run (not using React)

### ISSUE THREAD

**Issue by JamesRamm** [mobxjs/mobx-state-tree#579]
I am using `mobx-state-tree` without React. I have a `model` which contains an array of other models:

```
const DomainModel = types
  .model({
    components: types.array(Component), // Component is another types.model
  })
  .actions(self => ({
    addComponent(data) {
      ... // adds a component to the model
   }
  }))
```
I would like to listen to any change which adds or removes a component from the model so I can create/remove the corresponding view. 
Since I have the `addComponent` action, I have started by using `onAction`. However, this does not catch updates such as `applySnapshot`.

I have tried to use `observe` from Mobx, no changes are ever logged in the following code:

    observe(domainStore, (change) => console.log(change)); // domainStore is my app-wide instance of DomainModel

**Comment by mattiamanzati** [comment]
It is intended to work like this, observe from mobx will only look into changes of the item you passed it. So in your example it will trigger for updates of the roots tore object, and not for its child array. To observe child updates you need to use onSnapshot indeed :)
