### ISSUE TITLE
Implementing a custom type for a javascript Range

### ISSUE THREAD

**Issue by knoopx** [mobxjs/mobx-state-tree#588]
I'm trying to implement a custom type for a Range primitive, what would be the proper way to implement it? 

My raw representation of a range is an array of two values `[0,1]` and I would like it to be converted to a real javascript Range object.

Looking at similar issues, the `reference` trick won't work here as my primitive type is not an string or number. What is your suggested approach?

**Comment by mweststrate** [comment]
We are working on introducing limited custom type support in MST, so that it it possible to define your own scalar types.

**Comment by mweststrate** [comment]
Planned to be solved by https://github.com/mobxjs/mobx-state-tree/issues/673
