### ISSUE TITLE
in Typescript .create() losts type info

### ISSUE THREAD

**Issue by naivefun** [mobxjs/mobx-state-tree#589]
![screen shot 2018-01-10 at 9 26 40 am](https://user-images.githubusercontent.com/10683378/34751664-eabe82de-f5e8-11e7-9d3a-806aa1a41bdf.jpg)

Like this. How can I fix this?

```typescript
export const Todo = types.model({
  name: types.optional(types.string, ''),
  done: types.optional(types.boolean, false)
});

export const User = types.model({
  name: types.optional(types.string, '')
});

export type ITodo = typeof Todo.Type;
export type IUser = typeof User.Type;

const john = User.create({name: 'John'});
const eat = Todo.create();

console.log(john.name, eat.toJSON());
```

**Comment by mattiamanzati** [comment]
toJSON is not expected to be used in your code, it's just a tool for debugging in javascript console. It's an alias for getSnapshot(eat) :)
