### ISSUE TITLE
Integrate/use Joi for type definitions?

### ISSUE THREAD

**Issue by specimen151** [mobxjs/mobx-state-tree#590]
When creating a model, I've noticed that it does not have a lot of types, at least not as much as Joi. For example, using the Date type, it can not infer a ISO formatted date string, whereas in Joi it would be `Joi.date().iso()`. Also the syntax for refinement is (good but) more cumbersome, like: `Joi.string().min(5)` would be `types.refined(types.string, s => s.length>=5)`. 

Question is: Would it be good/bad/possible to use Joi for typing models? So not everything must be made from scratch? Or does it simply not fit in?

**Comment by mattiamanzati** [comment]
MobX State Tree types provide more information than just simple type validation, as how to handle patches, snapshot, etc... Why do you use also Joi? Is that for an existing codebase?
Because MST have Type.is(value) and Type.validate(value) too, where the first returns a boolean if the value is a valid value for the type, and the second one returns an array of positions where illegal values are passed in, and which type it was expecting :)

**Comment by specimen151** [comment]
The API I'm calling returns dates as strings in ISO format, e.g. `2018-01-09T20:38:14.015Z`, and I'd like to verify it, and it would also be nice to convert to a Date in the model. MST types.Date doesn't like the format, so currently I'm using
```
.preProcessSnapshot(snapshot => ({
    ...snapshot,
    start: new Date(snapshot.start)
}))
```

Also I have URL's to verify, and there is no URL primitive type (of course, I don't expect it to be), but would also need to validate those.

The examples (BookShop and the egghead.io series) use fetch within the model, effectively using the model as a data-transfer-object, and then extra validation (in/out) would certainly be useful.

**Comment by mweststrate** [comment]
@specimen151 did you check `types.refinement` ? You could use that for urls etc

**Comment by specimen151** [comment]
Yes, had a look at that. Solves many problems except it does not convert my iso formatted date string to a Date object. And it’s a bit more to type, but I guess it will do for now. Love MST BTW.
