### ISSUE TITLE
why actions return a class instance is depreciated? 

### ISSUE THREAD

**Issue by IAIAE** [mobxjs/mobx-state-tree#591]
```javascript
let Foo = types.model('Foo', {
    name: types.string
}).actions(self=>{
    class FooActions{
        constructor(s){
            this.self = s;
        }

        @clickInterval(500)
        setName(val){
            this.self.name = val;
        }
    }

    return new FooActions(self);
})
```

then i got:

Uncaught Error: [mobx-state-tree] actions initializer should return a plain object containing actions

**Comment by EdonGashi** [comment]
Looks like [this check](https://github.com/mobxjs/mobx-state-tree/blob/e32dfee5af7f10534c43f6c5b944e8a521838c5f/packages/mobx-state-tree/src/utils.ts#L65) is performed on the returned object. Even if it didn't throw you would have the problem of depending on an unbound `this` context, which negates the benefit of having a closure with `self`.

**Comment by mweststrate** [comment]
@IAIAE well, classes there doesn't mean anything, as the actions you return will be copied into `self`, and the `FooActions`  you created will simply be garbage collected. So, `Foo`  will never become a `FooActions`
