### ISSUE TITLE
how to model a object without all properties?

### ISSUE THREAD

**Issue by sam019** [mobxjs/mobx-state-tree#593]
example, I get a object like this:
`{ name: 'peter', age: 18 }`, and i only want to define 'age' property : 
`const People = t.model({ age: types.number })`,
but when i create a People instance: `const people = People.create({ name: 'peter', age: 18 })`
i get error...
so if there is a lot of properties in the object, and i only care about the 'age' property, i have to define all of the properties? it is bored and make no sense, how should i resolve this problem?

**Comment by specimen151** [comment]
It seems to work for me if you assign it to a variable first, e.g:
```javascript
const People = types.model({ age: types.number })
const people = People.create({ name: 'peter', age: 18 })
```
fails, but
```javascript
const People = types.model({ age: types.number })
const obj = { name: 'peter', age: 18 }
const people = People.create(obj)
```
works fine.

**Comment by sam019** [comment]
@specimen151 yes, in this way in works。but i can not access other properties that not defined in model....

i want a way than only properties defined in model is 'observable', and other properties can access   still (but when it is changeed, doesn't trigger any side effect, mst doesn't notice it)。but seemly there is no way....

**Comment by mweststrate** [comment]
@sam019 see: https://github.com/mobxjs/mobx-state-tree#where-is-the-any-type
