### ISSUE TITLE
How to set self = newData i none go?

### ISSUE THREAD

**Issue by IljaDaderko** [mobxjs/mobx-state-tree#596]
I've built an auth model

```
const AuthModel = types
  .model({
    email: types.string,
    token: types.string,
    intercom_hash: types.string,
    public_id: types.string,
    status: types.string
  })
  .actions(self => ({
    setAuthData(authObj) {
      self = authObj; // TODO here
    }
  }));
```

the `self = authObj` doesn't seem to work (authObj) reflects models structure correctly. It only works if I set each attribute one by one i.e
 ```
setAuthData(authObj) {
    self.email = "...";
    self.token = "...";
     /* And so on, this works fine */
}
```

**Comment by mattiamanzati** [comment]
self = authObj won't work at all, because refereces in JS does not exists :) it's something like trying to this = authObj inside a class method.
You should instead copy the attribute values, you could try Object.assign(self, authObj) :)

**Comment by IljaDaderko** [comment]
Ah I see, yes that does the trick! Thank you. Is there a spread shorthand for this, looks similar to how redux returns state, but the use `...`. I tried returning `{ ...self, ...authObj }`, but no luck

**Comment by luisherranz** [comment]
You could assign it: `self = { ...self, ...authObj };` althouth that's not `Object.assign(self, authObj)` but `Object.assign({}, self, authObj)` instead.

**Comment by mattiamanzati** [comment]
No wait, none of those would work, you cannot do any assignment using self as left operator. The object is mutable, so the instance needs to remain the same, I think the shortest one is Object.assing(self, authObj)

@luisherranz self = Object.assign({}, self, authObj) won't work for the reason mentioned above :)

**Comment by luisherranz** [comment]
Ohh, true! Then, there's no way to simplify it using `...authObj` I guess.

**Comment by robinfehr** [comment]
I think this will fail in some cases since doing so won't change the tree nodes type.
e.g. when you'd be using a union dispatcher to determine the actual custom type.

**Comment by a2f0** [comment]
I was trying so long to figure out how to assign the full object.  Thank you so much for this post, `Object.assign(self, authObj)` works beautifully.
