### ISSUE TITLE
What problem mobx-state-tree tries to solve?

### ISSUE THREAD

**Issue by SuperManEver** [mobxjs/mobx-state-tree#597]
Can you give me some high-level explanation what problem mobx-state-tree tries to solve? What can it do what MobX can't?

**Comment by mattiamanzati** [comment]
You can have a great overview in the readme
https://github.com/mobxjs/mobx-state-tree#philosophy--overview

Basically traceability, replayability, fine grained patches and time travelling, runtime type checking, etc.. :)
