### ISSUE TITLE
Question: is there a recommended approach to denormalize circular references?

### ISSUE THREAD

**Issue by bloudermilk** [mobxjs/mobx-state-tree#599]
*Apologies in advance if this is not the right forum for questions*

I'd like to expand on the the usual `Todo` example in the README by adding an optional `Tag` reference for each `Todo`. In my UI, I want users to be able to pick a `Tag` for each `Todo`, then see a collection of `Todos` by each `Tag`.

I see I can use `late()` to handle the circular reference problem. However, it's not clear to me how I would access all the `Todo` references for a `Tag` in a convenient way as `Tag` doesn't actually have an attribute which is an array of `Todo` identifiers when it comes back from the database.

Is there some way I can specify a getter function for my array of references or otherwise back it by an computed index on an array?

**Comment by mattiamanzati** [comment]
Does Tag have an identifier property? If so, MST supports as primary concept references.
In the readme it's shown that you can use it to point to a single object, but the most fun part, is that you can actually create an array of references.

https://github.com/mobxjs/mobx-state-tree#references-and-identifiers

```
const Tag = types.model({
    id: types.identifier(),
    title: types.string
})

const Todo = types.model({
    id: types.identifier(),
    title: types.string,
    tags: types.array(types.reference(Tag))
})

const TodoStore = types.model({
    todos: types.array(Todo),
    tags: types.array(Tag)
})

// create a store with a normalized snapshot
const storeInstance = TodoStore.create({
    todos: [{
        id: "47",
        title: "Get coffee",
        tags: ["1", "2"]
    }],
    tags: [{
        id: "1",
        title: "Office"
    },{
        id: "2",
        title: "Beverage"
    }]
})
```

**Comment by mattiamanzati** [comment]
Then from the tag side I'll define a view that returns all the todos with that given tag :)

**Comment by bloudermilk** [comment]
@mattiamanzati thank you for the response! Would you put your view function on `Tag` or `TodoStore`? I'd rather see `tag.todos` in the code over `storeInstance.tagTodos[tag]` but it seems like a leaky abstraction.

**Comment by mattiamanzati** [comment]
Ideally you could do something like:

```javascript
const Tag = types.model({
    id: types.identifier(),
    title: types.string
}).views(self => ({
   get todos(){
      return getParent(self).todos.filter(todo => todo.tags.indexOf(self) > -1)
   }
}))
```

Just beware that it assumes that there is a sibling node to the parent of Tag named "todos", so if you mount your tags somewhere else it will fail. I would recommend to define a place at root where to store tags and todos and use getRoot instead of getParent to access that path :)

**Comment by bloudermilk** [comment]
@mattiamanzati wow, that's great! I hadn't though of traversing the tree like that. In my case traversing to root each time makes a lot of sense as my raw data structure is completely flat, so all references can be found at root.

I imagine I'll want to keep an index at my root (TodoStore) to cache the result of the computation (I have somewhat large collections). This is where a "getter" view will come in handy, I guess? Something like `todosByTag` which computes and caches a map?

**Comment by mattiamanzati** [comment]
MST views are already cached if actively watched, as mobx does :)

**Comment by bloudermilk** [comment]
Got it! Thanks for all of the insight. With this knowledge I'll try to upgrade from plain mobx to MST.

**Comment by DmacMcgreg** [comment]
@mattiamanzati 
This is exactly the approach I am trying to use, however, the view does not get run after the sibling has updated.

For instance, I have a rootStore with AccountStore.accounts and UserStore.users
I want to be able to access the users on an account by setting up a view -> parent -> users

This is fine, but the computed value on the account model does not get updated once the UsersStore has been updated with the latest users...

Any idea how to work around this issue?

```export const Account = types.model("Account", {
  id: types.identifier(),
  //users: types.maybe(types.late(() => types.reference(types.map(User)))),
  name: types.string,
  author: types.string,
  price: types.number,
  isAvailable: true,
  users: types.array(
    types.reference(types.late(() => User))
  )
})```

```
Rootstore view...
get users() {
      return self.userStore.users
    }
```

```
export const User = types.model("User", {
  id: types.identifier(),
  name: types.string,
  author: types.string,
  price: types.number,
  isAvailable: true,
  account: types.maybe(types.reference(Account))
})

...

function updateUsers(json) {
      values(self.users).forEach((user: any) => (user.isAvailable = false))
      json.forEach(userJson => {
        self.users.push(userJson)
      })
    }
```
