### ISSUE TITLE
Custom references w. fetch side effects progress or alternatives

### ISSUE THREAD

**Issue by specimen151** [mobxjs/mobx-state-tree#602]
The docs mention that custom reference types can be used e.g. to trigger a fetch, and in the example there's a comment about views and side effects:

```javascript
getOrLoadUser(name) {
    const user = self.users.find(u => u.name === name) || null
    if (!user) {
        /*
            TODO: this is ugly, but workaround the idea that views should be side effect free.
            We need a more elegant solution..
        */
        setImmediate(() => self.loadUser(name))
    }
    return user
}
```
1. Are you getting any further on this? 
2. Is using references like this the recommended method to "build" a model tree in which the first fetch returns some data that includes more urls (like a html page w. img src, css etc as links), or is another pattern recommended? I'd really like some input.

**Comment by mweststrate** [comment]
I think you can currently use two approaches
1. the one described above
2. have a string identifier (array) as prop, and create a view that initiates the data fetching and save the resulting values in some closure. Optionally you can add logic to listen to patches on the identifier (array) to fetch additional data etc.

**Comment by specimen151** [comment]
**Thanks for taking the time to answer.** Can I follow up a bit before I close the "issue". 

You mention _"create a view that initiates the data fetching"_, so that means the view has a side effect? But it's okay? After all you created MST and the rules, so I guess that means yes.

When you say _save the resulting values in some closure_ do you mean something like

`window.fetch(url).then(res=>res.json()).then(json=>self.resources.put(url,MyModel.create(json))).catch(error => { error handling })`

Just asking, because I'm not totally up to speed on the terms. And maybe you have an example with generators which works better with MST, I think maybe the `self` won't work here, if I remember your egghead.io course correctly.

**Comment by mweststrate** [comment]
> You mention "create a view that initiates the data fetching", so that means the view has a side effect? But it's okay? After all you created MST and the rules, so I guess that means yes.

It is a gray-ish area indeed. For example, in MobX it is quite common to introduce a computed property that returns a `return mobxUtils.fromPromise(promise)`, which returns a clear view capturing the state of the promise, and a side effect creates / kicks off that promise. So it is not entirely pure, but it is a really powerful pattern, which so far never brought me into trouble. 

To avoid the MST protection, in the `then` clause you should invoke an action on `self`, rather then updating the state of self directly. With that, it should work.
