### ISSUE TITLE
Support Enums and union type for enumeration

### ISSUE THREAD

**Issue by yordis** [mobxjs/mobx-state-tree#605]
Based on this example

```typescript
type ApplicationStates = 'ACTIVE' | 'INACTIVE' | 'BACKGROUND'

enum ApplicationStatesEnum {
  ACTIVE,
  INACTIVE,
  BACKGROUND
}

const applicationStates = types.enumeration('ApplicationStates', [
  'ACTIVE',
  'INACTIVE',
  'BACKGROUND'
])
````

I want to be able to do 

```typescript
types.enumeration<ApplicationStatesEnum>(...)
// or

types.enumeration<ApplicationStates>(...)
```

Basically the Enum and/or union type should deconstruct to the array of allowed values I guess.

or at least be able to get the type from `types.enumeration` like

```typescript
const applicationStates = types.enumeration('ApplicationStates', [
  'ACTIVE',
  'INACTIVE',
  'BACKGROUND'
])

applicationStates.Types // <---- use this for typescript checking
```
the last one should give me a `union` of values back

**Comment by yordis** [comment]
I think enum should be the one that makes sense here

**Comment by FredyC** [comment]
The enums in Typescript generate runtime code like this. It's a bit cumbersome to extract string keys as it's mixed together. Should be possible though. However, I am not sure how to connect it together with an actual type definition.

```js
var Status;
(function (Status) {
    Status[Status["ACTIVE"] = 0] = "ACTIVE";
    Status[Status["INACTIVE"] = 1] = "INACTIVE";
    Status[Status["BACKGROUND"] = 2] = "BACKGROUND";
})(Status || (Status = {}));

// Object.keys(Status) === ['ACTIVE', 0, 'INACTIVE', 1, 'BACKGROUND', 2]
```

Personally, I like string unions more as it's much easier to define those and work with them in general. For use with MST [this approach](https://github.com/pelotom/runtypes/issues/38) looks promising, but it's another overhead for a runtime, so I am not so sure about it.

**Comment by yordis** [comment]
@FredyC yeah that would works as well, Enum are more restricted and it is the reason I like it

**Comment by FredyC** [comment]
I don't see how string union is less restrictive. When you type in wrong value, it will annoy you same way :) But that doesn't really matter for MST concerns.

@mweststrate do you think it's even possible to do something like this?

**Comment by yordis** [comment]
@FredyC more restricted because you do not deal with strings type but Enum type

But being said,

like I said on the comments, I prefer the Enum but I know there is not differences and probably union type is better.

**Comment by mweststrate** [comment]
Closing for now, don't see a real value, I think it is possible to combine the to, but not that in MST terms you  need to explicitly create a union of integer values, as that is what typescript enums (by default), boil down to.

**Comment by FredyC** [comment]
@mweststrate I think that the main point is type checking. If you have a numeric enum, then you basically need to use `types.number` and you are losing runtime type safety.  Or you can copy your enum keys to `types.enumeration`, but that's error-prone.

I also found [ts-enum-util](https://github.com/UselessPickles/ts-enum-util) package which is really neat, but wasn't able to test it out yet.

**Comment by kresli** [comment]
I know its quite old thread, but if anyone still looking for an answer, I can confirm this works well with TS 3.6.3 and MST 3.14.1. 
```
enum Operation {
  ADD = "add",
  REMOVE = "remove
}

const model = types.model({ op: types.enum(Object.values(Operation) }).create({ ... });

model.op = Operation.ADD // no TS error
model.op = "add" // TS error

```

**Comment by mbest** [comment]
I'm running into a problem trying to use `enumeration` in TypeScript. With the code below I get this compile error:

```
Type '"started"' is not assignable to type 'IOptionalIType<ISimpleType<OperationStatus>, [undefined]>'.
```

```ts
export declare type OperationStatus = "inert" | "started" | "finished" | "failed";
...
        status: t.optional(t.enumeration<OperationStatus>(["inert", "started", "finished", "failed"]), "inert"),
...
                        self.status = "started";
```
