### ISSUE TITLE
`afterCreateOnServer()` as nice helper function for SSR apps?

### ISSUE THREAD

**Issue by dargue3** [mobxjs/mobx-state-tree#606]
I'm using MST in a Next.js server-side rendered app (and it's the 🐝's knees). I've found myself writing the following code a bunch of times, since the model is created once on the server and once on the client.

```
afterCreate() {
    if (isServer()) {
      // do one thing
    } else {
      // do another
    }
}
```

Is there a more eloquent workaround than wrapping in an if statement that I'm missing? Otherwise could we consider making `afterCreateOnServer()` and `afterCreateOnClient()` life-cycle hooks that can be toggled by what you configure via `require('mobx-react').useStaticRendering(true)`? Not a huge deal but it's a small quality of life improvement!

**Comment by Bnaya** [comment]
unrelated comment,
I would inject something via the env and not call isServer(),

**Comment by robinfehr** [comment]
MST is not react only. I can't yet see a good alternative solution. please reopen if you'd have a good idea how to improve that in a more general way.
