### ISSUE TITLE
Typed types.maybe<S, T>(types.frozen)

### ISSUE THREAD

**Issue by hannes-o-brunner** [mobxjs/mobx-state-tree#608]
Minor quibble: I am trying to define a typed (in Typescript) frozen attribute in a model.
Problem is that `types.frozen` is fixed to `ISimpleType<any>` and not parametrisable like `types.maybe` or `types.optional`. So while the shorthand below compiles fine in Visual Code, it crashes at runtime with
`Error: [mobx-state-tree] Unable to declare `types.maybe(types.frozen)`. Frozen already accepts `null`. Consider using `types.optional(types.frozen, null)` instead.`

Instead of having something more compact like `session: types.maybe(types.frozen<SessionInfo>)`

we need to write it like this `session: types.optional<{}, SessionInfo | null>(types.frozen, null)`

Something I am missing here?

**Comment by mweststrate** [comment]
@hannes-o-brunner now you are correct that `frozen` is now anything-goes. We want to change it indeed to become a function (`types.frozen()`) so that it can become typed.

**Comment by mattiamanzati** [comment]
You could use something like 

const SessionInfoType = types.frozen ad IType<any, SessionInfo> :)

**Comment by hannes-o-brunner** [comment]
Alright, thanks for the quick reply 😀
