### ISSUE TITLE
[Typescript] view is not seeing other views

### ISSUE THREAD

**Issue by FredyC** [mobxjs/mobx-state-tree#611]
When I want to use `self.body` in the `isAvailable` getter, the Typescript is telling me...

>'Property 'body' does not exist on type '{ bodyArea: EBodyArea; } & IStateTreeNode'.'

```js
export const BodyAreaModel = types
  .model('BodyArea', {
    bodyArea: EBodyArea.None,
  })
  .views(self => ({
    get body() {
      const combatBody: TCombatBody = getParent(self)
      return combatBody.body
    },
    get isAvailable() {
      return self.body.isAreaAvailable(self.bodyArea)
    },
  }))
```

I ended up with the following, but it's not that pretty. Is it possible to fix this somehow or it's _too dynamic_?

```js
  .views(self => {
    const getBody = () => {
      const combatBody: TCombatBody = getParent(self)
      return combatBody.body
    }
    return {
      get isAvailable() {
        return getBody().isAreaAvailable(self.bodyArea)
      },
    }
  })
```

**Comment by mweststrate** [comment]
See https://github.com/mobxjs/mobx-state-tree/issues/610#issuecomment-358823960, same principles apply to actions

**Comment by FredyC** [comment]
I see. So my workaround here is essentially correct. However it's kinda different issue with _views_ because this removes reactivity, if I understand correctly. I mean if `combatBody.body` gets changed, the `isAvailable` is not recomputed, right?

**Comment by yordis** [comment]
@FredyC I am updating the documentation but in the mean time, essentially this is the statement that made me to understand.

> The type of `self` is what `self` was **before the action or views blocks starts**, and only after that part finishes, the actions will be added to the type of `self`.

**Comment by FredyC** [comment]
@yordis Yea, I think I am understand Typescript more and more. It's curious design problem though. For example now I have a `volatile` prop which depends on `action` and that depends on `view`. It can get rather messy when you need to sort it by dependencies. 

I guess the obvious way around would be to manually maintain definition file for that model with everything in place so it can be used no matter the order. I am not sure if there a "cleaner" solution.

**Comment by yordis** [comment]
@FredyC to be honest, I gave up to Typescript and `mst`, the time I expend fighting/figuring out Typescript and how `mst` works, I could have done so much.

`mst` do to many mutations at runtime that I think adding Typescript to the level that you and me expect is not possible unless they change the internals I guess.

I will update the documentation but I am not using Typescript anymore.

**Comment by mweststrate** [comment]
@FredyC, when there are lot of dependencies, use `extend` to create views
and actions in the same closure

Op di 23 jan. 2018 om 09:35 schreef Yordis Prieto <notifications@github.com

**Comment by ConneXNL** [comment]
@xaviergonz That doesn't work as a workaround for this issue, does it?

**Comment by xaviergonz** [comment]
It does for me
