### ISSUE TITLE
preProcessSnapshot not copied on compose

### ISSUE THREAD

**Issue by ssured** [mobxjs/mobx-state-tree#613]
Sometimes I encode a single *behaviour* of my objects into a helper function. This helper function then makes it easier to make type definitions more DRY and composable. Below is an example for adding an `id` identifier strategy.

Right now we have to wrap the type definition call. It would be nice to have a `.mixin` method, to allow for mixin in these behaviour generating functions.

```javascript
  // adds an automatic generated unique id to the object
  // and adds `shortId` property for displaying in the ui
  const withIdProperty = type =>
    type
      .props({
        // add id property with random default
        id: t.optional(
          t.identifier(t.string),
          () => `${type.name}-${generateUUID()}`
        ),
      })
      .views(self => ({
        get shortId() {
          // use this in the app
          return self.id.split('-')[1];
        },
      }));

  // current way
  const Record = withIdProperty(
    t.model('Record', {
      name: t.string,
    })
  );

  // proposed way
  const Record = t
    .model('Record', {
      name: t.string,
    })
    .mixin(withIdProperty);
```

Where `.mixin` could be implemented like:
```javascript
type.mixin = function(behaviour) {
  return behaviour(this);
}
```

**Comment by mweststrate** [comment]
Did you check `compose`? It is meant for exactly patterns like this. Also
see the related egghead io lession for an example

Op za 20 jan. 2018 om 15:46 schreef Sjoerd de Jong <notifications@github.com

**Comment by ssured** [comment]
Cool, you have thought of everything 👍 `types.compose` does allow for the pattern indeed, thanks it's already there! Is there still a place for the syntactical sugar described above? Right now you have to start with the `types.compose` invocation, IMHO it would be nicer to also be able to do it on the type definition chain. It's hard to improve something which is already awesome...

The original example from the docs:

```javascript
export const LoggingSquare = types
    .compose(
        // combine a simple square model...
        BaseSquare,
        // ... with the logger type
        CreationLogger
    )
    // ..and give it a nice name
    .named("LoggingSquare")
```

would then become:

```javascript
export const LoggingSquare = BaseSquare
    .compose(
        // combine a simple square model with the logger type
        CreationLogger
    )
    // ..and give it a nice name
    .named("LoggingSquare")
```

**Comment by ssured** [comment]
One more thing; while experimenting it seems the `.preProcessSnapshot` property is not copied to composed type, which is a bug I guess?

**Comment by mweststrate** [comment]
Possibly.  PR with test and  / or fix is welcome 😊. Note that model.extend
can be used to get closer to your mixin syntax

Op zo 21 jan. 2018 11:45 schreef Sjoerd de Jong <notifications@github.com>:

**Comment by mweststrate** [comment]
PR with solution, or at least unit test is welcome :)

**Comment by theRealScoobaSteve** [comment]
@mweststrate my bad for this push (9539044), meant to make a PR  should role this back

**Comment by xaviergonz** [comment]
Fix merged, will be available on the next version of MST
