### ISSUE TITLE
.volatile() problems

### ISSUE THREAD

**Issue by robinfehr** [mobxjs/mobx-state-tree#614]
recently, when we tried using .volatile() we're facing the main problem that we can't use mst-types within these.

e.g. 
```js
.volatile(self => ({
    friend: FriendModel
})
```

to overcome this we tried using `postProcessSnapshot` to cut the properties from a snapshot before using `getSnapshot` to actually persist them.

overcoming this with `postProcessSnapshot` leads to the problem that specialized models will fall back to its main mode when using a union. 

e.g. 

```js
const specialModels = types.union(
    (snapshot) => {
      if (snapshot.properties) return SpecialModel;
      return MainModel;
    },
    SpecialModel,
    MainModel
);
```
```js
export const SpecialModel = types.compose(
  MainModel,
  types.model('_SpecialModel',{
    properties: types.maybe(types.array(PropertyModel))
  }).actions(self => ({
    setProperties({ properties }) {
      self.properties = properties;
    },
    postProcessSnapshot(snapshot) {
      const {
        properties,
        ...cutSnapshot
      } = snapshot;
      return cutSnapshot;
    }
  }))
).named('SpecialModel');
```

creating a node which uses the `specialModels` as a type leads to the problem that only MainModels will be created because the `properties` property will be cut from the snapshot before reaching the union dispatcher.

so we ended up doing this non declaratively - meaning cutting all the props from the state after a getSnapshot by tree walking the snapshot.

would be nice to have a way to do that declaratively. maybe some ideas float around already :)

**Comment by robinfehr** [comment]
for the ones interested - this was caused using getSnapshot within an afterCreate hook 💅

**Comment by mattiamanzati** [comment]
Uhm, the real question here is: why do you want to use MOST types there? :)

**Comment by mattiamanzati** [comment]
*MST
