### ISSUE TITLE
preProcessSnapshot should always return a snapshot/not assign parent model

### ISSUE THREAD

**Issue by mjewell** [mobxjs/mobx-state-tree#616]
Here's a <a href="https://mattiamanzati.github.io/mobx-state-tree-playground/#src=import%20%7B%20getSnapshot%2C%20types%20%7D%20from%20%22mobx-state-tree%22%0Aimport%20%7B%20observer%20%7D%20from%20%22mobx-react%22%0A%0Alet%20id%20%3D%201%3B%0A%0Aconst%20GrandChild%20%3D%20types.model('GrandChild'%2C%20%7B%7D)%3B%0A%0Aconst%20Child%20%3D%20types.model('Child'%2C%20%7B%0A%20%20%20%20id%3A%20types.identifier()%2C%0A%20%20%20%20grandChild%3A%20GrandChild%0A%7D).preProcessSnapshot(snapshot%20%3D%3E%20%7B%0A%20%20%20%20%2F%2F%20this%20runs%20twice%0A%20%20%20%20%2F%2F%201)%20%7Bid%3A%201%2C%20grandChild%3A%20%7B%E2%80%A6%7D%7D%0A%20%20%20%20%2F%2F%202)%20%7B%24mobx%3A%20e%2C%20toString%3A%20%C6%92%2C%20%24treenode%3A%20e%2C%C2%A0%E2%80%A6%7D%0A%20%20%20%20%2F%2F%20on%20the%20second%20time%2C%20it%20fails%20with%0A%20%20%20%20%2F%2F%20Cannot%20add%20an%20object%20to%20a%20state%20tree%20if%20it%20is%20already%20part%20of%20the%20same%20or%20another%20state%20tree.%20Tried%20to%20assign%20an%20object%20to%20'%2Fchildren%2F1%2FgrandChild'%2C%20but%20it%20lives%20already%20at%20'%2FgrandChild'%0A%20%20%20%20console.log(snapshot)%3B%0A%20%20%20%20return%20Object.assign(%7B%7D%2C%20snapshot)%3B%20%0A%7D)%3B%0A%0Aconst%20Parent%20%3D%20types.model('Parent'%2C%20%7B%0A%20%20%20%20children%3A%20types.optional(types.map(Child)%2C%20%7B%7D)%0A%7D).actions(self%20%3D%3E%20(%7B%0A%20%20%20%20addChild()%20%7B%0A%20%20%20%20%20%20%20%20self.children.put(%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%3A%20id%2B%2B%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20grandChild%3A%20%7B%7D%0A%20%20%20%20%20%20%20%20%7D)%3B%0A%20%20%20%20%7D%0A%7D))%3B%0A%0Aconst%20parent%20%3D%20Parent.create()%0Aparent.addChild()%3B%0A">playground</a> demonstrating the issue.

I'm not sure exactly the cause, but it seems like if you have a `types.map` and you use `.put` to push an snapshot into it, it runs preProcessSnapshot twice, first with the snapshot, and then with an instance of the MST model. If the model you are pushing in has submodels (the GrandChild model, in my case), you get an error like this:

```
Error: [mobx-state-tree] Cannot add an object to a state tree if it is already part of the same or another state tree. Tried to assign an object to '/children/1/grandChild', but it lives already at '/grandChild'
```

**Comment by mattiamanzati** [comment]
preProcess running twice is expected and intended, first one is for typechecking, second one is for the actual store creation. That's why preProcess should be pure :) see also #348 and #510 

The second one looks like definetely a bug, will look onto it as soon as possible! :)

**Comment by mattiamanzati** [comment]
For now, please inspect if "snapshot" is a MST node and convert it to snapshot manually if this is blocking for you :)

https://mattiamanzati.github.io/mobx-state-tree-playground/#src=import%20%7B%20getSnapshot%2C%20types%2C%20isStateTreeNode%20%7D%20from%20%22mobx-state-tree%22%0Aimport%20%7B%20observer%20%7D%20from%20%22mobx-react%22%0A%0Alet%20id%20%3D%201%3B%0A%0Aconst%20GrandChild%20%3D%20types.model('GrandChild'%2C%20%7B%7D)%3B%0A%0Aconst%20Child%20%3D%20types.model('Child'%2C%20%7B%0A%20%20%20%20id%3A%20types.identifier()%2C%0A%20%20%20%20grandChild%3A%20GrandChild%0A%7D).preProcessSnapshot(snapshot%20%3D%3E%20%7B%0A%20%20%20%20%2F%2F%20this%20runs%20twice%0A%20%20%20%20%2F%2F%201)%20%7Bid%3A%201%2C%20grandChild%3A%20%7B%E2%80%A6%7D%7D%0A%20%20%20%20%2F%2F%202)%20%7B%24mobx%3A%20e%2C%20toString%3A%20%C6%92%2C%20%24treenode%3A%20e%2C%C2%A0%E2%80%A6%7D%0A%20%20%20%20%2F%2F%20on%20the%20second%20time%2C%20it%20fails%20with%0A%20%20%20%20%2F%2F%20Cannot%20add%20an%20object%20to%20a%20state%20tree%20if%20it%20is%20already%20part%20of%20the%20same%20or%20another%20state%20tree.%20Tried%20to%20assign%20an%20object%20to%20'%2Fchildren%2F1%2FgrandChild'%2C%20but%20it%20lives%20already%20at%20'%2FgrandChild'%0A%20%20%20%20console.log(JSON.stringify(snapshot))%3B%0A%20%20%20%20return%20Object.assign(%7B%7D%2C%20isStateTreeNode(snapshot)%20%3F%20getSnapshot(snapshot)%20%3A%20snapshot)%3B%20%0A%7D)%3B%0A%0Aconst%20Parent%20%3D%20types.model('Parent'%2C%20%7B%0A%20%20%20%20children%3A%20types.optional(types.map(Child)%2C%20%7B%7D)%0A%7D).actions(self%20%3D%3E%20(%7B%0A%20%20%20%20addChild()%20%7B%0A%20%20%20%20%20%20%20%20console.log(id)%0A%20%20%20%20%20%20%20%20self.children.put(%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%3A%20id%2B%2B%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20grandChild%3A%20%7B%7D%0A%20%20%20%20%20%20%20%20%7D)%3B%0A%20%20%20%20%7D%0A%7D))%3B%0A%0Aconst%20parent%20%3D%20Parent.create()%0Aparent.addChild()%3B%0Ainspect(parent)%0A

**Comment by mjewell** [comment]
Thanks for the quick reply. Temporary solution works great for now.

**Comment by gbiryukov** [comment]
> preProcess running twice is expected and intended, first one is for typechecking, second one is for the actual store creation

The issue here is that first time it called with passed snapshot and second time it called with object produced by first invocation that may (and should!) change initial snapshot shape/values.
So function purity isn't enough to make it work properly every time.

In my opinion it is huge source of confusion and inconvenience in MST.
I guess `preProcessSnapshot` should be called both times with initially passed snapshot.

**Comment by xaviergonz** [comment]
@mattiamanzati would this be solved if https://github.com/mobxjs/mobx-state-tree/issues/947 is adopted?

**Comment by xaviergonz** [comment]
Updated playground: https://codesandbox.io/s/3vxxolrv1
Still getting called 2 times (as expected and explained by @mattiamanzati), but no crash anymore with v3.7.0, so closing
