### ISSUE TITLE
change type of tree node

### ISSUE THREAD

**Issue by robinfehr** [mobxjs/mobx-state-tree#617]
this issue might be related to #614, #596.

once a node is created it has a type. 
there are situations where we'd like to change this type e.g. 

we only safe a partial tree to the backend and load this and refine it in the frontend with some local data that can change over time (volatile properties). we can't just always save them and overwrite them since sometimes the number of volatile entries can change. imagine a volatile array.

given such a situation we'd load the serialized snapshot and apply it.

once applied we'd have to refine it. 

refining it could look like: 

```js
refineNode: () =>  {
    const nodeDefinition = get(nodeDefinitions, self.id);
    const { context } = nodeDefinition;
    self.setContext({ context });
   //... other refinements
```

as long as we don't want to change the treenode.type by changing a property used within a dispatcher, all is fine.  but imagine we'd have a `.map` that is using a first class `.union` type that has a dispatcher to determine the actual underlying custom type / model. 

e.g. 

```js
nodes: types.optional(types.map(types.late(() => customTypes.customModels)), {}),
```

now we'd have to re-put the node to the nodes map to change the type. to do that we need to get rid of the actual node we want to refine and put it again on the map. 

the easiest solution that came to my mind was using `getSnapshot(node)` and using `.put`
but doing so leads to the problem that `postProcessSnapshot` hooks are getting invoked and the returned snapshot might not be correct anymore.

using any other method than (deepClone will fail too without making it fancy because of mobx types)
```js
JSON.stringify(JSON.parse(node))
```

will/ can lead to (within the `createNode() - src/core/node.js`)
```js
isStateTreeNode$$1(initialValue) === true
```

that can lead to the erorr on (within the `setParent() - src/core/node.js`)
``` js
newParent.root.identifierCache.mergeCache(this);
```

not sure how to approach this yet.
maybe you can help me out here. something like a `getSnapshot` that doesn't trigger any hooks before returning the snapshot would have solved it too but maybe there is another/ cleaner solution :)

**Comment by mweststrate** [comment]
I think introducing a feature like this will raise the complexity of MST to an undesirable level :-P.
