### ISSUE TITLE
unexpected warning: 'Cannot update during an existing state transition'

### ISSUE THREAD

**Issue by lidermanrony** [mobxjs/mobx-state-tree#619]
I might be missing something basic, but i'm getting the following warning:

> Warning: Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.

i'm aware of this part of the [mobx-react FAQ](https://github.com/mobxjs/mobx-react/blob/master/README.md#faq) but it doesn't seem to apply to my case as i have no constructors.

The only non-trivial thing i'm doing here is using an async action.

here's a [code sandbox](https://codesandbox.io/s/8203lm57wl) with the code, 
and below the actual code:
```
import React from 'react';
import { render } from 'react-dom';
import Hello from './Hello';

import { types, flow } from 'mobx-state-tree';
import { observer } from 'mobx-react';

const Model = types.model({
  fetched: types.optional(types.boolean, false),
  another: types.optional(types.string, 'initial value')
}).actions(self => ({
  fetch: flow(function* fetch() {
    yield new Promise((resolve, reject) => {
      setTimeout(() => {
        return resolve(7), 1000
      } )
    })

    self.fetched = true;
  }),
  setAnother: str => {
    self.another = str;
  }
}));

const model = Model.create({});

const styles = {
  fontFamily: 'sans-serif',
  textAlign: 'center',
};

const App = () => {
  if (!model.fetched) {
    model.fetch();
  } else {
    model.setAnother('another value');
  }
  return (
    <div style={styles}>
    <Hello name={model.another} />
  </div>
)};

const ObserverApp = observer(App)

render(<ObserverApp />, document.getElementById('root'));
```

**Comment by robinfehr** [comment]
that's a react error - `App` is a stateless component and therefore the same as `render` within a stateful component.

**Comment by lidermanrony** [comment]
@robinfehr - Thanks I am aware of this. As far as i understand there shouldn't be any warnings when interacting with the store from the render function, so unless i'm missing something , it does not explain the reason for the warning.

**Comment by robinfehr** [comment]
mobx-react leverages forceUpdate to rerender a component which does break react's lifecycle when used within a render.

**Comment by lidermanrony** [comment]
Thanks @robinfehr for the reply. 
That makes total sense - I just realized that up until this point I only called store methods from button click events handlers and not from inside the render function itself.

So in that case - what would be the right pattern to use?

Let's say i have a mobx-state-tree flow (Based on async generator), and I want to trigger another action as soon as the flow concludes.
Is the right pattern to use autorun in componentDidMount for that?

**Comment by robinfehr** [comment]
why not just triggering the action within the flow? a bit like here:
https://github.com/mobxjs/mobx-state-tree/blob/e32dfee5af7f10534c43f6c5b944e8a521838c5f/packages/mst-example-bookshop/src/stores/BookStore.js#L37

autorun seems to be the wrong choice here since you'd have to have an observable within the autorun to actually make it re-run which would lead to an endless loop after manipulating the node and therefore re-running the autorun again.

**Comment by lidermanrony** [comment]
Thanks @robinfehr for the information.

My actual scenario is as follows:
my users perform several sequential actions by interacting with the UI.
Some of these can trigger async flows that call server side. User waits for the call to return some data and then continues working with that data using the UI.

I would like to support a kind of 'deep link' functionality in which I map the URL to a (short) series of actions (some asynchronous) that need to execute sequentially.
This series of actions should be triggered whenever someone points the browses to the application.

So I guess what i need boils down to 
1. trigger my deep-link action once my root store is created (looks like there's a lifecycle hook for that - great)
2. my deep-link action will have to sequentially invoke this series of actions - some of which are async. (I'm guessing it is possible to yield an async flow from another async flow - if it's possible that's great).

Does that look like the right way to go?

**Comment by robinfehr** [comment]
not so sure I get what you're trying :) but 2. work yes
