### ISSUE TITLE
model attributes named "name" of type string causes Error

### ISSUE THREAD

**Issue by mrjjwright** [mobxjs/mobx-state-tree#620]
```javascript
  var Beer = types.model("Beer", {
    name: types.string,

    cells: types.maybe(
      types.map(
        types.late(function() {
          return Beer;
        })
      )
    )
  });

  var b = Beer.create({ id: uuid() });
  unprotect(b);
  var b2 = Beer.create({ id: uuid() });
  b.cells = {};
  b.cells.put(b2);

  var snapshot = getSnapshot(b);
  var b1 = Beer.create(snapshot);
```

throws on `applySnapshot` but changing the one line on how name is declared as so

``` javascript
var Beer = types.model("Beer", {
    id: types.identifier(),
    name: ""
```
does not.

**Comment by mrjjwright** [comment]
Actually I am not sure I identified that correctly, closing until I can narrow down further.

**Comment by skellock** [comment]
Is it related to `types.maybe()` by any chance?  Does the error tell you that `cells` is not optional even though you defined it with `types.maybe()`?

**Comment by mrjjwright** [comment]
Thanks for the reply but I moved on and closed this.  I decided to use straight mobx to better handle this design.

**Comment by mweststrate** [comment]
For future readers: Note that `name: types.string` makes string required,
but `name: ""` will make name optional, and have it defaulted to `""`

Op ma 29 jan. 2018 om 23:18 schreef John Wright <notifications@github.com>:

**Comment by mrjjwright** [comment]
👍🏼 thanks!
