### ISSUE TITLE
Suggestion - Adding a way to access path names and actions names using a model or node

### ISSUE THREAD

**Issue by omerman** [mobxjs/mobx-state-tree#627]
Hi, first of all love that library. Im already using it at various places.
Thank you guys for this wonderful library :)

I do have some suggestions:

What we have today - 
```javascript
onAction(store, call => {
 if (call.action === 'myActionName') {
   doSomething();
 }
});
```

What I think would be nicer and more developer friendly - 
```javascript
import { getActions } from 'mobx-state-tree';

onAction(store, call => {
 if (call.action === getActions(store).myActionName ) {
   doSomething();
 }
});
```

** same thing goes for supplied paths.

What we have today - 
```javascript
onPatch(store, call => {
 if (call.path === '/property') {
   doSomething();
 }
});
```

What I think would be nicer and more developer friendly - 
```javascript
import { getPaths } from 'mobx-state-tree';

onPatch(store, call => {
  if (call.action === getPaths(store).property ) {
    doSomething();
   }
});
```
I think adding those could add a lot of value to the development since these methods could throw if action/path does not exist. and I believe its better to work like this than with strings/consts that are written by the developer.

I'll be glad to hear what are your thoughts on this.
Thanks.

**Comment by mweststrate** [comment]
`getPaths(store).property`

> I think adding those could add a lot of value to the development since these methods could throw if action/path does not exist. and I believe its better to work like this than with strings/consts that are written by the developer.

I don't get the question entirely, I think it is a false sense of security, things like `getPaths` can accept anything so they cannot really reason about what exists compile time. `.property` might _look_ safer, but if the compiler doesn't flag it's non-existence it is just misleading, as it would be `undefined` and not helpful to your patch listener at all?

I am very much in favor of adding a reflection api, but to make it helpful you would need to do at least something like 

```
onAction(store, call => {
 const myAction = getActions(store).myActionName
 if (!myAction)
    throw "You are trying ot use an action that isn't defined on the store"
 if (call.action ===  myAction) {
   doSomething();
 }
});
```

In reality it is probably a bit more complicated, as actions can come from an arbitrarily deep place on the store, so you would need to fetch it from `getActions(call.object)`

**Comment by mweststrate** [comment]
Closing as question is answered
