### ISSUE TITLE
How to use types.* ?

### ISSUE THREAD

**Issue by chenxiaochun** [mobxjs/mobx-state-tree#628]
I read here, but I can't understand it very much. Could you give me a explame, thanks very much.

> If you want, for example, to make the name or todos property required when calling create, just remove the types.optional function call and just pass the types.* included inside.

**Comment by mattiamanzati** [comment]
That phrase should be read as following:

> If you want, for example, to make the name (declared as types.optional(types.**string**, "") ) property required when calling create, just remove the types.optional function call and just pass the types.**string** included inside.

Just put any type in place of * :)

**Comment by chenxiaochun** [comment]
Suddenly it was clear. Thanks very much.🚀
