### ISSUE TITLE
[Feature Request] Add a deterministic way to distinguish between models types

### ISSUE THREAD

**Issue by Bnaya** [mobxjs/mobx-state-tree#63]
Support similar mechanism for js `instanceof` for the models instances.
Another option would be to keep a reference to the factory on the model via well-known symbol.

My usecase: I have an react component that gets am array of models and needs to pick the component to use with a specific model

I want to do something like:

```js
const componentsMap = new Map([factoryUser, ReactComponentForUserModel]);

...
render() {
return <div>
{this.models.map((m) => return <componentsMap.get(m.factorySymbol)/>)}
</div>
}
```

**Comment by mattiamanzati** [comment]
Have you tried to use getFactory(m)?
