### ISSUE TITLE
Please example of chaining actions

### ISSUE THREAD

**Issue by lishine** [mobxjs/mobx-state-tree#630]
Fragment from the readme:

Some tips:
Note that multiple actions calls can be chained. This makes it possible to create multiple closures with their own protected volatile state.

**Comment by robinfehr** [comment]
what is meant is:
```js
const Store = types.model({
        todos: types.array(Todo),
        state: types.enumeration("State", ["loading", "loaded", "error"])
    })
    .actions(self => {
        const someVar = null // volatile state 1

        return {
            addTodo() { if (someVar) ... },
        }
    })
    .actions(self => {
        const someOtherVar = null // volatile state 2

        return {
            setState() { if (someOtherVar) ... }, //someVar can't be used here.
        }
    })
```

**Comment by lishine** [comment]
I see. Thanks.
I thought I could run actions in chain:
StoreInstance.action1().action2().
I am not sure there is need for this...
But if to implement: return self. But if there is need to retur

**Comment by robinfehr** [comment]
if the action is not async you could return self indeed and chain them.
