### ISSUE TITLE
Type hints take multiple seconds in Webstorm/PHPStorm

### ISSUE THREAD

**Issue by ConneXNL** [mobxjs/mobx-state-tree#638]
Trying to play with `mobx-state-tree` using Webstorm/PHPstorm as the IDE, it takes about 5 seconds before any type hinting pops up for anything related to mobx-state-tree. This includes the raw `types ` property from mobx-state-tree.

For example.

```
import {types} from "mobx-state-tree";
types.
```
takes 5 seconds before I get a list of options on` types` using PHPStorm 2017.3 on a fresh project.

Commenting the following lines seems to speed up the overall hinting to <1 sec.

https://github.com/mobxjs/mobx-state-tree/blob/52dbec0b2ae61540f15d0b818c236b6cbc0f88aa/packages/mobx-state-tree/src/types/utility-types/enumeration.ts#L20-L111

Is there any way to solve this in a different way? Also, are more people experiencing this issue?

**Comment by geowarin** [comment]
Yup definitely a problem for us too.
https://youtrack.jetbrains.com/issue/WEB-30646

I had to downgrade IntelliJ to 2017.2.x as the problem seems to have been included in 2017.3.x versions.

**Comment by ConneXNL** [comment]
@geowarin thanks for the link!

To what version did you go? I am currently on PHPStorm 2017.2.4 but its equally slow for me. 

Also seems like in a lot of cases its not just slow, types also don't seem to show up, for example I only see a single view getter on an instance.

**Comment by robinfehr** [comment]
closing this since it does not seem to affect other IDE's. a better way to solve this in TS would be appreciated, none found so far though.
