### ISSUE TITLE
Proper typescript typings

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#64]
`createFactory` seems to be quite impossible to make strongly typed in Typescript, without mapped types (even when not taking into consideration the partial subtypes of snapshots)

Two sample playgrounds demonstrating some of the problems:

[fails to reassign subfields](
http://www.typescriptlang.org/play/#src=type%20Factory%3CT%3E%20%3D%20T%20%26%20%7B%20()%3A%20T%20%7D%20%7C%20T%0D%0A%0D%0Afunction%20createFactory%3CT%3E(base%3A%20T)%3A%20Factory%3CT%3E%20%26%20%7B%20()%20%3A%20T%20%7D%20%7B%0D%0A%20%20%20%20return%20null%20as%20any%0D%0A%7D%0D%0A%0D%0Afunction%20primitive%3CT%3E(value%3A%20T)%3A%20Factory%3CT%3E%20%7B%0D%0A%20%20%20%20return%20null%20as%20any%0D%0A%7D%0D%0A%0D%0Aconst%20A%20%3D%20createFactory(%7B%0D%0A%20%20%20%20x%3A%20primitive(3%20as%20number)%2C%0D%0A%20%20%20%20y%3A%20primitive(%22boe%22%20as%20string)%0D%0A%7D)%0D%0A%0D%0A%2F%2F%20factory%20is%20invokable%0D%0Aconst%20a%20%3D%20A()%0D%0A%0D%0A%2F%2F%20property%20can%20be%20used%20as%20proper%20type%0D%0Aconst%20z%3A%20number%20%3D%20a.x%0D%0A%0D%0A%2F%2F%20property%20can%20be%20assigned%20to%20crrectly%0D%0Aa.x%20%3D%207%0D%0A%0D%0A%2F%2F%20wrong%20type%20cannot%20be%20assigned%0D%0Aa.x%20%3D%20%22stuff%22%20%2F%2F%20Red%20is%20ok%0D%0A%0D%0A%2F%2F%20sub%20factories%20work%0D%0Aconst%20B%20%3D%20createFactory(%7B%0D%0A%20%20%20%20sub%3A%20A%0D%0A%7D)%0D%0A%0D%0Aconst%20b%20%3D%20B()%0D%0A%0D%0A%2F%2F%20sub%20fields%20have%20proper%20type%0D%0Ab.sub.x%20%3D%204%0D%0Aconst%20d%3A%20string%20%3D%20b.sub.y%0D%0A%0D%0A%2F%2F%20sub%20fields%20can%20be%20reassigned%0D%0Ab.sub%20%3D%20A()%0D%0A)

[factories are not functions, but expose (possibly null) create method (note the `create!()`)](
http://www.typescriptlang.org/play/index.html#src=type%20Factory%3CT%3E%20%3D%20T%20%26%20%7B%20create%3F()%3A%20T%20%7D%0D%0A%0D%0Afunction%20createFactory%3CT%3E(base%3A%20T)%3A%20Factory%3CT%3E%20%7B%0D%0A%20%20%20%20return%20null%20as%20any%0D%0A%7D%0D%0A%0D%0Afunction%20primitive%3CT%3E(value%3A%20T)%3A%20Factory%3CT%3E%20%7B%0D%0A%20%20%20%20return%20null%20as%20any%0D%0A%7D%0D%0A%0D%0Aconst%20A%20%3D%20createFactory(%7B%0D%0A%20%20%20%20x%3A%20primitive(3%20as%20number)%2C%0D%0A%20%20%20%20y%3A%20primitive(%22boe%22%20as%20string)%0D%0A%7D)%0D%0A%0D%0A%2F%2F%20factory%20is%20invokable%0D%0Aconst%20a%20%3D%20A.create!()%0D%0A%0D%0A%2F%2F%20property%20can%20be%20used%20as%20proper%20type%0D%0Aconst%20z%3A%20number%20%3D%20a.x%0D%0A%0D%0A%2F%2F%20property%20can%20be%20assigned%20to%20crrectly%0D%0Aa.x%20%3D%207%0D%0A%0D%0A%2F%2F%20wrong%20type%20cannot%20be%20assigned%0D%0Aa.x%20%3D%20%22stuff%22%20%2F%2F%20Red%20is%20ok%0D%0A%0D%0A%2F%2F%20sub%20factories%20work%0D%0Aconst%20B%20%3D%20createFactory(%7B%0D%0A%20%20%20%20sub%3A%20A%0D%0A%7D)%0D%0A%0D%0Aconst%20b%20%3D%20B.create!()%0D%0A%0D%0A%2F%2F%20sub%20fields%20have%20proper%20type%0D%0Ab.sub.x%20%3D%204%0D%0Aconst%20d%3A%20string%20%3D%20b.sub.y%0D%0A%0D%0A%2F%2F%20sub%20fields%20can%20be%20reassigned%0D%0Ab.sub%20%3D%20A.create!()%0D%0A)

Something like: https://github.com/Microsoft/TypeScript/issues/13257 could definitely help!

This is  the best I could do so far:

```javascript
type Factory<T> = T & { create?(): T }

function createFactory<T>(base: T): Factory<T> {
    return null as any
}

function primitive<T>(value: T): Factory<T> {
    return null as any
}

const A = createFactory({
    x: primitive(3 as number),
    y: primitive("boe" as string)
})

// factory is invokable
const a = A.create!()

// property can be used as proper type
const z: number = a.x

// property can be assigned to crrectly
a.x = 7

// wrong type cannot be assigned
a.x = "stuff" // Red is ok

// sub factories work
const B = createFactory({
    sub: A
})

const b = B.create!()

// sub fields have proper type
b.sub.x = 4
const d: string = b.sub.y

// sub fields can be reassigned
b.sub = A.create!()
```

**Comment by mweststrate** [comment]
Hmm typewise the most safe approach is to let all factories only return their target type, and introduce a static `create` methods that instantiates a new instance given a factory (in a typesafe manner):

```javascript
function createFactory<T>(base: T): T {
    return null as any
}

function primitive<T>(value: T): T {
    return null as any
}

const A = createFactory({
    x: primitive(3 as number),
    y: primitive("boe" as string)
})

function create<T>(f: T): T {
    return null as any
}

// factory is invokable
const a = create(A)

// property can be used as proper type
const z: number = a.x

// property can be assigned to crrectly
a.x = 7

// wrong type cannot be assigned
a.x = "stuff" // Red is ok

// sub factories work
const B = createFactory({
    sub: A
})

const b = create(B)

// sub fields have proper type
b.sub.x = 4
const d: string = b.sub.y

// sub fields can be reassigned
b.sub = create(A)
```

**Comment by mweststrate** [comment]
[other option with explicit sub `object`](http://www.typescriptlang.org/play/#src=function%20createFactory%3CT%3E(base%3A%20T)%3A%20()%20%3D%3E%20T%20%7B%0D%0A%20%20%20%20return%20null%20as%20any%0D%0A%7D%0D%0A%0D%0Afunction%20primitive%3CT%3E(value%3A%20T)%3A%20T%20%7B%0D%0A%20%20%20%20return%20null%20as%20any%0D%0A%7D%0D%0A%0D%0Afunction%20object%3CT%3E(factory%3A%20()%20%3D%3E%20T)%3A%20T%20%7B%0D%0A%20%20%20%20return%20null%20as%20any%0D%0A%7D%0D%0A%0D%0Aconst%20A%20%3D%20createFactory(%7B%0D%0A%20%20%20%20x%3A%20primitive(3%20as%20number)%2C%0D%0A%20%20%20%20y%3A%20primitive(%22boe%22%20as%20string)%0D%0A%7D)%0D%0A%0D%0Afunction%20create%3CT%3E(f%3A%20T)%3A%20T%20%7B%0D%0A%20%20%20%20return%20null%20as%20any%0D%0A%7D%0D%0A%0D%0A%2F%2F%20factory%20is%20invokable%0D%0Aconst%20a%20%3D%20A()%0D%0A%0D%0A%2F%2F%20property%20can%20be%20used%20as%20proper%20type%0D%0Aconst%20z%3A%20number%20%3D%20a.x%0D%0A%0D%0A%2F%2F%20property%20can%20be%20assigned%20to%20crrectly%0D%0Aa.x%20%3D%207%0D%0A%0D%0A%2F%2F%20wrong%20type%20cannot%20be%20assigned%0D%0Aa.x%20%3D%20%22stuff%22%20%2F%2F%20Red%20is%20ok%0D%0A%0D%0A%2F%2F%20sub%20factories%20work%0D%0Aconst%20B%20%3D%20createFactory(%7B%0D%0A%20%20%20%20sub%3A%20object(A)%0D%0A%7D)%0D%0A%0D%0Aconst%20b%20%3D%20B()%0D%0A%0D%0A%2F%2F%20sub%20fields%20have%20proper%20type%0D%0Ab.sub.x%20%3D%204%0D%0Aconst%20d%3A%20string%20%3D%20b.sub.y%0D%0A%0D%0A%2F%2F%20sub%20fields%20can%20be%20reassigned%0D%0Ab.sub%20%3D%20A()%0D%0A)

**Comment by mattiamanzati** [comment]
What about this?
It needs to deprecate creating object by calling the function, and call .create instead.
This way factories becames an object with a create property (and others).

```typescript
export type IModel = {
    $treenode: any // Actually Node, but that should not be exposed to the public...
} & Object

export interface IFactory<S, T> {
    create(snapshot?: S, env?: Object): T & IModel
    factoryName: string,
    is: ITypeChecker
    isFactory: boolean // TODO: rename to isFactory
    type: IType
}

export interface IType {
    name: string
    is(thing: IModel | any): boolean
    create(snapshot, environment?): any
    factory: IFactory<any, any> // TODO type
    describe(): string
}

export type ITypeChecker = (value: IModel | any) => boolean

export type IBaseModelDefinition<S extends Object, T> = {[K in keyof T]: IFactory<any, T[K]> | T[K]}

export function createFactory<S extends Object, T extends S>(baseModel: IBaseModelDefinition<S, T>): IFactory<S, T>
export function createFactory<S extends Object, T extends S>(name: string, baseModel: IBaseModelDefinition<S, T>): IFactory<S, T>
export function createFactory(arg1, arg2?) {
    return null as any
}

const t_string: IFactory<string, string> = null as any
const t_number: IFactory<number, number> = null as any
const t_primitive = <T>(value: T) => T


const A = createFactory({
    x: t_primitive(3),
    y: t_primitive("boe")
})

// factory is invokable
const a = A.create()

// property can be used as proper type
const z: number = a.x

// property can be assigned to crrectly
a.x = 7

// wrong type cannot be assigned
a.x = "stuff" // Red is ok

// sub factories work
const B = createFactory({
    sub: A
})

const b = B.create()

// sub fields have proper type
b.sub.x = 4
const d: string = b.sub.y

// sub fields can be reassigned
b.sub = A.create()

```

**Comment by mquandalle** [comment]
@mweststrate Is the 0.2 API working with Typescript types? 

On the below example I would expect to have access to the `x` and `y` properties but I can't get it working:

![typescript mobx-state-tree 0.2](https://cloud.githubusercontent.com/assets/1730702/24552231/f1de5eca-1625-11e7-949d-18055bd20430.png)

**Comment by mattiamanzati** [comment]
Uhm, which TS version are you using @mquandalle ?

![cattura](https://cloud.githubusercontent.com/assets/13787614/24552501/fe4461d6-1626-11e7-8818-a5b8221fb583.PNG)

**Comment by mquandalle** [comment]
Currently, `typescript@2.3.0-dev.20170330` but I think I tried with the latest stable version, 2.2, and had the same result; I'm trying again right now.

**Comment by mquandalle** [comment]
It still doesn't work for me with Typescript 2.2. Here is my `yarn.lock` file which provide the exact version of all of my dependencies in case there is a problem in that: https://gist.github.com/mquandalle/d4aa3072fe0056fb63ac604b09d68a53

Note that the above screenshot comes from my editor but I get corresponding errors (namely `error TS2339: Property 'x' does not exist on type '{} & { $treenode?: MSTAdminisration | undefined; } & { toJSON(): Snapshot<{}>; }'.`) in the compiler output, so there is probably a problem with the project dependencies and probably not with VSCode.

**Comment by mattiamanzati** [comment]
typescript.tsdk points to your node_modules, right?

**Comment by mquandalle** [comment]
Yes

**Comment by mquandalle** [comment]
But then again, typescript fails to compile, so I doubt it's an issue with the editor. I see that I have the following error in the console:

```
Error in /home/mquandalle/react/myproject/node_modules/mobx-state-tree/lib/types/object.d.ts
(1,44): error TS2305: Module '"/home/mquandalle/react/myproject/node_modules/mobx/lib/mobx"' has no exported member 'IAction'.
```

**Comment by mquandalle** [comment]
Ok, the problem was with MobX version. Updating it fixed the issue, sorry for falsy report.
