### ISSUE TITLE
[Question] Is it possible to determine in the "view" getter the trigger of the changes (update)

### ISSUE THREAD

**Issue by swayf** [mobxjs/mobx-state-tree#645]
Again may be strange question =)

Sometimes, for performance optimisation,  is needed to now what was the trigger of the update (which field(s) of model that are used in the "view" getter).
Is it possible some how?

Thank you in advance

**Comment by swayf** [comment]
There is code example for the problem explanation:
```javascript
const TestRowModel = types.model({
    col1: types.identifier(types.string),
    col2: types.string
});

const baseModel = types.model('TestTableModel', {
        allData: types.array(TestRowModel),
        renderedCount: types.number
    })
    .views(self => ({
        get renderedData() {
             // can be expensive if allData is big and renderedCount is big enough
            return views.allData.slice(0, self.renderedCount); 
        }
    }))
    .actions(self => ({

        showMore(){
            self.renderedCount += 100;
        }
    }));
```
normally it started always with small renderedCount, and then after scrolling renderedCount is going to be bigger. In this case (if allData is not changed) it is better to do some in-place renderedData editing, like 

```javascript
renderedData.push(...allData.slice(renderedData.length, renderedCount - renderedData.length));
```
and save the cached rendered array as volatile for the next renderedCount change..
but if allData changes, then do whole work

if I know what kind of change has triggered the computation of the view, I could choose better algorithm to achieve it..

**Comment by mweststrate** [comment]
You can use `mobx.trace()` to see what triggered your view to update or (`mobx.trace(true)`) to actually pause the debugger, the causing change will that be in your stack. See https://mobx.js.org/best/trace.html for details.
