### ISSUE TITLE
[Question] validation failure when using types.union with dispatcher

### ISSUE THREAD

**Issue by vnayw** [mobxjs/mobx-state-tree#648]
Hi,

### Problem:
Model instance 'testmodel' has an items array which can contain other model instances. 
I use a dispatcher function for the items type e.g.
```
items: types.array( types.union(dispatcher)  )
```
When I try to add a model instance to testmodel's items array
```
const testmodel = P2.create({id:'parent', type:'P2', items:[]});
const child = P1.create({id:'child', type:'P1', items:[]});
testmodel.add(child);
```
I get this error
```
Error: [mobx-state-tree] Error while converting <P1@<root>(id: child)> to `()`:
value of type P1: <P1@<root>(id: child)> is not assignable to type: `()`, expected an instance of `()` or a snapshot like `()` instead. (Note that a snapshot of the provided value is compatible with the targeted type)
```

How do I get around this ?

### Example Details: 

Model P1 has an items array, which uses a dispatcher function to provide the type 
The dispatcher function returns either type P1 or P2
 
```
const P1 = types.model('P1',{
   id: types.identifier(),
   spec: 'some spec',
   type: types.optional(types.string, 'P1'),
   items: types.array( types.union(dispatcher)  )
}).actions(self=>({
   updateSpec(state) {
       self.spec = 'P1 ' + state;
   },
  add(child) {
       self.items.push(child);
  }
}));


function dispatcher(snapshot){
	if(snapshot.type === 'P2') {
		return types.late(()=> P2);
	} else {
		return types.late(()=> P1);
	}
}

const P2 = P1
.props({
	title: 'a title',
	type: types.optional(types.string, 'P2')
})
.actions(self=>({
	updateSpec(state) {
		self.spec = 'P2 ' + state;
	}
}));

const testmodel = P2.create({id:'parent', type:'P2', items:[]});
const child = P1.create({id:'child', type:'P1', items:[]});
testmodel.add(child);
```
The add fails.

It seems like when adding a model instance to the array, the type validation code tries to validate against the dispatcher function, which does not work.

**Comment by robinfehr** [comment]
in you case the first problem is that the union also needs the types since it uses them for checks internally. `types.union(dispatcher, type1, type2)`
 
the next would be that types are a first class concept in MST - it's always good to reuse them rather then redefine them.

reusing them would look like:
```js
const P1 = types.model('P1', {
  id: types.identifier(),
  spec: 'some spec',
  type: types.optional(types.string, 'P1'),
  items: types.array(types.late(() => Union)) // use the Union type
})

const Union =
  types.union((snapshot) => {
    if (snapshot.type === 'P2') {
      return P2;
    } else {
      return P1;
    }
  }, P1, P2)

```

**Comment by vnayw** [comment]
Thanks !
It seems like the use for the dispatcher function is somewhat restricted. I could do something like this (without the dispatcher function) and it would work
```
items: types.array( types.late(()=> P1), types.late(()=> P2) )
```
I guess the intent with the dispatcher function is to handle cases where there might be ambiguity while inferring the type between the already known types.

I was thinking more from a scenario where the types in the array are not available before hand (they are composed at run time ) - it does not quite help in that scenario.  e.g.

```
const P2 =  prepareType( additionalProps ) {
    return types.compose(P1, SomeOtherBaseType)
      .props( constructProps(additionalProps) )
      .named('P2')
}
```

The initial example I noted had static types because it was easier to describe and it seemed to result in the same issue.

Is there a way, already, to provide a name of a type e.g.
```
items: types.array( getTypeFromName(name_of_type1), getTypeFromName(name_of_type2) )
```
instead of providing the type ... the type would be composed at run time

**Comment by robinfehr** [comment]
```
I guess the intent with the dispatcher function is to handle cases where there might be ambiguity while inferring the type between the already known types.
```
correct. 

---

in you example...what is `name_of_type1` ?

do you want to get the type from a snapshot?
if yes - there is now the `getMembers` that might help you write a helper in which you'd create a prototype node to get the members.

**Comment by mweststrate** [comment]
Closing as question sems answered.
