### ISSUE TITLE
[Question] use map in types.array is err

### ISSUE THREAD

**Issue by sternelee** [mobxjs/mobx-state-tree#654]
I try a example like this:
```
import { types as t, onSnapshot } from 'mobx-state-tree';
...
const Store = t.model("Store", {
    todos: t.array(Todo),
    name: t.string
})
...
@observer
...
store.todos.map(v => <div>{v.title}</div>
```
console will show：
uncaught Error: Objects are not valid as a React child...
and store.todos is ObservableArray
where is wrong？

**Comment by robinfehr** [comment]
can't tell for sure since there is quite a bit of code missing in you snipped but it seems to be a missing wrapper element. 

e.g.
```
<div>
store.todos.map(v => <div>{v.title}</div>
</div>
```

you can also use fragments if your react version is up to date.
