### ISSUE TITLE
Do static typings with typescript actually work?

### ISSUE THREAD

**Issue by dfilatov** [mobxjs/mobx-state-tree#655]
I tried the simplest example:
```ts
const Test = types.model({
    id: types.number,
    type: types.string
});

Test.create({
    id: 'test'
});
```
I expected to see some typescript errors, but I saw only runtime errors.

Type for `Test` was inferred as:
```ts
IModelType<{
    id?: any;
    type?: any;
}, {
    id: number;
    type: string;
}>
```
which looks quite useless, cause I can pass everything as property values, even an empty object without properties at all.

**Comment by mweststrate** [comment]
Typing snapshots is pretty limited atm (so anything that is passed to
.create(), or returned from `getSnapshot`), but you will discover that,
beyond snapshots (which issues we can address once TS 2.8 is out!), you
will discover it is pretty powerful. E.g. if you had had stored your test,
`test = Test.create`, you would discover full autocompletion / typechecking
on test, including it's views, actions etc.

Op di 13 feb. 2018 om 16:38 schreef Filatov Dmitry <notifications@github.com

**Comment by dfilatov** [comment]
@mweststrate just to understand, what's the point of having:
```ts
IModelType<{
    id?: any;
    type?: any;
}, {
    id: number;
    type: string;
}>
```
instead of:
```ts
IModelType<{
    id: number;
    type: string;
}>
```
in this case? Or maybe it's typescript limitation, isn't it?
