### ISSUE TITLE
How to extend IdentifierReferenceType?

### ISSUE THREAD

**Issue by ConneXNL** [mobxjs/mobx-state-tree#659]
I am trying to extend the IdentifierReferenceType (I want to implement a check with getEnv() instead of the root tree while keeping the other functionality of IdentifierReferenceType).

However, the npm package doesnt contain the source files and there seems to be no way to access IdentifierReferenceType in order to extend it (with typescript).

Copying the /src/types/utility-types/reference.ts locally also doesn't cut it as it imports a chain of utility functions that would also have to be copied (as lots of them aren't available on the mobx-state-tree object).

Am I missing something or how would one go about making their own ReferenceType based on the internal IdentifierReferenceType ?

**Comment by ConneXNL** [comment]
Seems like i found a workaround:

import { INode, IType, IdentifierReferenceType } from "mobx-state-tree/dist/internal";

export class EnvironmentReferenceType<T> extends
 (types.reference(types.late(() => null)).constructor as typeof IdentifierReferenceType)<T> {

    getValue(node: INode) {
         ....
    }

}

**Comment by mweststrate** [comment]
@ConneXNL using custom references:

https://github.com/mobxjs/mobx-state-tree#customizable-references

combined with resolveIdentifier

https://github.com/mobxjs/mobx-state-tree/blob/master/API.md#resolveidentifier

should make it easy to create functionality similar to the built in identifierType
