### ISSUE TITLE
Possible performance issue (memory leak)

### ISSUE THREAD

**Issue by sorenhoyer** [mobxjs/mobx-state-tree#664]
Hi 

For the past couple of days @robinfehr has been so kind to help me with trying to get more performance from MST for a use case of mine. Unfortunately, after he reviewed the code, no significant performance improvements seemed possible (mostly cosmetic ones for improving readability), and yesterday, after creating a Redux equivalent (see the below urls to the 2 repositories), it shows that there most likely is a memory leak, that becomes a real problem when using MST for this sort of thing right now. I believe Rob is looking at / investigating it now.

I absolutely love MST - the way you keep your components separate from your business logic. It just feels more clean, and much faster to develop in. A pleasure to work with compared to Redux. But for the UI we're building we need it to run 24/7 without memory leaks, and we need it to scale well in terms of how many data points we can store in the state - 2000 is high right now, but 10K is not unthinkable in the future - that day might come where someone needs to monitor a wider span of data. The datapoints although a central part, is only one of many other things we keep in state, so I really would hate having to go back to Redux again.

So I was thinking that maybe I'm using MST the wrong way? Although it would be nice to have in state with MST models, maybe a better (more performant) place to put all of this, would be the volatile state, instead of MST models? I'm just a bit hesitant of doing so, since this data is quite a central part of the UI, and volatile afaik seem to be used more for other things, that either does not fit in state or aren't as important to persist. I'm not sure if that would solve the problem either, but if it sounds sensible I'll go ahead and try to make and example using volatile state.

https://github.com/sorenhoyer/mobx-live-data-performance-test (NEW )
https://github.com/sorenhoyer/mobx-state-tree-live-data-performance-test
https://github.com/sorenhoyer/redux-live-data-performance-test

My tests showed: 

**MobX**  (npm start - non-optimized build):

2000: 2% 400MB

**MST** (serve -s build - optimized production build)

0: 4% 350MB
500: 7% 420MB
1000: 12.5% 570MB
1500: 18% 750MB
1999: 25% 1250MB

**Redux** equivalent (npm start - non-optimized build):

0: 2% 370MB
500: 0% 350MB
1000: 0.3% 354MB
1500: 0 % 360MB
1999: 0% 373MB
2000+: 0% 342-356MB (356 after 1 hour of running)

Both tests were performed with:

- the chart commented out
- 2000 datapoints
- 100ms intervals
- chrome, without other tabs / windows open (no dev tools either)
- Dev tools commented out in code (is done by default)

CPU & Memory was monitored at 0, 500, 1000 etc from Windows 10 Task manager.

Performance profiles can be found here: 

https://github.com/sorenhoyer/performance-profiles/blob/master/mst-redux-live-data-performance-test.zip

Memory / heap timelines:

https://github.com/sorenhoyer/performance-profiles/blob/master/mst-redux-live-data-performance-test-heap-timeline.zip

![Image of Yaktocat](https://raw.githubusercontent.com/sorenhoyer/performance-profiles/master/mst-vs-redux-live-data-performance-test-heap-statistics.png)

**Update:**
Just added a [new test](https://github.com/sorenhoyer/mobx-state-tree-live-data-performance-test/tree/volatile) where I moved the datapoints (Sensor, Heap, Queue) into volatile state, and it seems to have made all the difference:

0:	2.5% 320MB
500:	4,2% 309MB
1000:	3.0% 307MB
1500:	2.0% 317MB
1999:	2.0% 319MB

It really sucks though, having to use volatile state, but hopefully it helps track down the real issue. MST will be kickass, once it's stabilized more and performance has been optimized!

**Comment by robinfehr** [comment]
@sorenhoyer sorry didn't find time to look at the profile yesterday.

will look at the profiles more closely. volatile should be used if you don't want them on the snapshots. no need to persist the data (`getSnapshot(store)`)
they're still observables and the rerendering of your component using the `@observer` would still work as it does at the moment.

**Comment by sorenhoyer** [comment]
@robinfehr no worries, and thanks a lot for your effort digging into this! (and for saving me the time to test with volatile.) :)

**Comment by mweststrate** [comment]
Closing and adding reference from #440 to keep one issue for performance related stuff.
