### ISSUE TITLE
[Feature Request] MST Components -> Data Binding

### ISSUE THREAD

**Issue by robstown** [mobxjs/mobx-state-tree#666]
I have sort of a crazy idea that in my head that I think would enhance MST to the next level of programming paradigm.  Let me start with some background.

One thing I love about MST is that it acts as both a data store and data documentation essentially in one.  The (forced/opinionated) schema structure forces conscious decisions and explicit definition of data form, composition, storage, and modification.  At the same time, it gives you great performance, time travel, little boilerplate, and is very readable.  The things that is missing in my view to bring it full circle is explicitly defining how that data is connected and bound to components.  

I started off thinking how cumbersome it is to programmatically add autoruns to non-react components.  For example, I can store a DOM element in the tree as volatile state in the model, but in order to bind the data to that element I need to add an autorun statement outside of the model.  For example, I might want to sync scroll in two elements. To do this I often: 

1) first create an event handler in a react component (or directly to DOM element) to listen for scroll changes.   In my case, I do this generically by wrapping the component with a wrapper function that adds things to the component and lifecyle events like the event handler, throttle/debounce functions, & axis options for scrolling.  Let call its @scroller

2) I bind the changes to my data model using by passing the wrapper function an action.  @scroller({target:MyStore.setScroll})

3) I then bind changes from the data store to the second component.  The easiest way is to use @observer decorator on a react component and pass in the store and reference the observable.  In some cases that may not work so I could store the DOM element as a volatile state and then set up an autorun function to update scrollTop whenever my scroll observable changes.  If I want do that programmatically, I have to engineer clever ways to make sure I add it to the right program scope and dispose of the autorun when I remove the component.

This shuffle with autorun can be cumbersome and has led to fragile code (mostly because I'm not the best programmer).    But it also got me thinking about all the other errors in function and performance I have encountered over time due to referencing observables in the wrong component or scope or just code creep overtime and loosing track of all the observable references in all my components.  The nature of being able to have a universal connector (autorun/observer) that pipes your entire reactive store to functions and react components by adding passing in the store or references to the store is awesomely powerful. At the same time, it makes it hard to keep track of where observables are being referenced and where state is being set without digging through a lot of code.  mobx-react was a great tool for mobx, as both were un-opinionated and gave you ultimate flexibility, however, it was up to you to use that power wisely.  

Enter MST.  MST added a great framework around mobx to provide explicit structural composition and traceability.  I wander if the same can be done for mobx-react, only make it more generic so it doesn't only apply to react.  Here is what I was thinking.  

You create a wrapper utility to generically wrap objects (components) to bind them to a MST store.  Let's call it MST-component for now.  The wrapper could define two classes of inputs, reactive and non-react, and an output.  Reactive inputs would be observables (MST models and views) and non-reactive could be MST internal/external volatile state, untracked-observables, environment variables, or even other components. The wrapper binds the outputs to MST actions.  

The wrapper binds these inputs and outputs to the underlining component (object/class/function).  Any properties or methods of the object will have access to them.  Anytime a model or view is updated, any method or property in that object that references it will be called/updated in the appropriate scope. As the data tree is populated, class components (like react components) would create new instances for each time that model is replicated in a tree branch.  If a plain object is referenced, different branches of the data store referencing that object would each would mutate it when reactive items update.  A function, (like console.log()), would just execute.   Any non-reactive inputs that are referenced will be passed into the method only at the time it is called due to a reactive component.  The methods can trigger reactions like UI updates, network calls, disk access, or calls to update the model via the actions bound in the output list.  As I was thinking how this might look, I found it helpful to mock up a contrived example:

```
import {types, component, getParent} from "mobx-state-tree"
import {App, FetchPhoto, OrderItemView, ListView, DetailView} from './libraries/compLib1.js'
import {NewItem, NavList, ShoppingList, NavWindow, ScrollNav} from './libraries/compLib2.js'

export const Widget = types.model({
    id: types.identifier(types.string),
    name: types.string,
    desc: types.string,
    specs: Specification,
    photo: types.string,
    cost: types.number,
    quantity: types.number,
    dateAdded: types.date
})
.actions(self=>{
    return {
        setField(field, value){this[field] = value;},
    };
})
.connections(self=>({
    fetchPhoto: component({
        component: FetchPhoto,
        observers: {photo:self.photo}
    }),
    listView: component({
        component: ListView,
        observers: {name:self.name, cost:self.cost, quant:self.quantity},
        references: {photo: self.fetchPhoto},
        actions: {add:getParent(self,2).addToCart}
    }),
    detailView: component({
        component: DetailView,
        observers: {name:self.name, desc:self.desc, specs:self.specs, cost:self.cost, quant:self.quantity},
        references: {photo: self.fetchPhoto},
        actions: {add:getParent(self,2).addToCart}
    }),
    editView: component({
        component: EditView,
        observers: {name:self.name, desc:self.desc, specs:self.specs, cost:self.cost, quant:self.quantity},
        references: {photo: self.fetchPhoto},
        actions: {change: self.setField, remove:getParent(self,2).removeItem}
    }),
    newItem: component({
        component: NewItem,
        observers: {name:self.name, desc:self.desc, specs:self.specs, cost:self.cost, quant:self.quantity},
        references: {photo: self.fetchPhoto},
        actions: {change: self.setField, add:getParent(self,2).addItem}
    }),
}));

export const OrderItem = types.model({
    widget: types.reference(Widget),
    quantity: types.string
})
.actions(self=>{
    return {
        setQuantity(value){this.quantity = value;},
    };
})
.connections(self=>({
    orderItemView: component({
        component: OrderItemView,
        observers: {widget:self.widget, quantity:self.quantity},
        actions: {setQuantity: self.setQuantity, remove: getParent(self,2).removeFromCart}
    })
}));

export const Store = types.model({
    id: types.identifier(types.string),
    widgets: array(Widget),
    cart: types.maybe(types.array(OrderItem)),
    filter: types.maybe(types.string),
    sort: types.maybe(types.enumeration(['name','cost','date'])),
    theme: types.maybe(Theme),
    goToItem: types.maybe(WidGet)
})
.volatile(self => ({
    navDOM: types.frozen
}))
.views(self=>({
    get displayWidgets(){
        return self.filter ? self.widgets.filter(widget=>widget.type === this.filter) : self.widgets;
    },
    get sortedWidgets(){
        return self.displayWidgets.sort((a,b)=>{sortfuntion});
    },
    get goToIndex(){
        return self.sortedWidgets.indexOf(self.goToItem);
    },
    get scrollTo(){
        return self.goToIndex * getParent(self).columnWidth;
    },
}))
.actions(self=>{
    return {
        setFilter(value){this.filter = value;},
        setSort(value){this.sort = value;},
        setGoToItem(value){this.goToItem = value;},
        addItem(item){this.widgets.push(item);},
        removeItem(index){this.widgets.splice(index);},
        addToCart(item){this.cart.push(item);},
        removefromCart(index){this.cart.splice(index);},
        clearCart(){this.cart = [];}
    };
})
.connections(self=>({
    shoppingList: component({
        component: ShoppingList,
        observers: {cart:self.cart},
    }),
    navList: component({
        component: NavList,
        observers: {items:self.sortedWidgets},
    }),
    shoppingCart: component({
        component: null,
        observers: {theme:self.theme},
        references: {navWindow: self.navDOM},
        actions: {remove:self.removefromCart, clearCart: self.clearCart}
    }),
    navWindow: component({
        component: NavWindow,
        observers: {theme:self.theme, scrollTo},
        references: {navList: self.navList},
        actions: {setSort: self.setSort, setFilter: setFilter, setGoToItem: self.setGoToItem},
    }),
    scrollNav: component({
        component: ScrollNav,
        observers: {scrollTo: self.scrollTo},
        references: {navWindow: self.navDOM}
    }),
    app: component({
        component: App,
        observers: {theme:self.theme},
        references: {shoppingCart: self.shoppingCart, navWindow: self.navWindow}
    }),
}));

```
The component library might be something like this:

```
Import React from 'react';
import {connector} from "mobx-state-tree"

@connector(name, cost, quantity, photo, addToCart)
export class ListView extends React.Component {...}

@connector(name, desc, specs, cost, quant, photo, add)
export class FetchPhoto extends React.Component {...}

@connector(name, desc, specs, cost, quant, photo, change, remove)
export class DetailView extends React.Component {...}

@connector(observers, desc, specs, cost, quant, photo, change, add)
export class NewItem extends React.Component {...}

@connector(items)
export class NavList extends React.Component {
    render() {
        return items.map(item=>item.navView);
    }
}

@connector(cart)
export class ShoppingList extends React.Component {
    render() {
        return cart.map(item=>item.orderItemView);
    }
}

@connector(theme, navWindow, remove, clearCart)
export class NavWindow extends React.Component {...}

@connector(scrollTo, navWindow)
export const ScrollNav = function(scrollTo, navWindow){
    if(navWindow && scrollTo) navWindow.scrollTop = scrollTo;
}

@connector(theme, navWindow, remove, clearCart)
export class App extends React.Component {...}

@connector(widget, quantity, setQuantity, removeFromCart)
export class OrderItemView extends React.Component {...}
```

Really, the bound components are just ‘black boxes’ with explicitly defined I/O interface to the data store.  The components are local and are not traced with history or updated with snapshots.  You could swap the component with another that has the same I/O connections and the store would not care. This could allow you to swap out development & production components, for example.  It would also allow you to connect test components for unit type testing.  If it was possible to hot-swap the components, you could use it for real-time software updating.  

Why I like it:
- Explicit definition of data binding
- Coordinated disposal of components/references
- Sideways loading of components while staying true to react tree-like structure
- Component structure aligned with data structure
- Creates an ICD and collates it with the schema (programming and documentation in the same step)
- Explicitly define which variables are reactive and non-reactive (references), avoiding pitfalls of correctly (de)referencing data items by 
- Easily track what and when observers will run/update without digging through a lot of code
- Promote finer granularity of components at lower levels (easier to get upper level from lower than vice versa)
- Hot swap modules?

Although the example seems detailed, I just used it to think through it and start a discussion.  I'm sure there are a lot of errors and things could be done better.  I'm also guessing there is better terminology to use.  I hope it gets the point across though. Would this be useful to others?  Is it even feasible?

**Comment by mweststrate** [comment]
I would say, go for it and let us know :)
