### ISSUE TITLE
[Question] Compare nodes in middleware

### ISSUE THREAD

**Issue by Vargentum** [mobxjs/mobx-state-tree#669]
Is it possible to get access to both: 
- snapshot before some update (can be accessed via onMiddleware or onSnapshot)
- snapshot of the same node after some update (can be accessed via onSnapshot)

in the same middleware?

**Comment by mweststrate** [comment]
@Vargentum yI think the following should suffice for that:

```javascript
export function snapshotLoggerMiddleware(call: IMiddlewareEvent, next: any) {
    console.dir(getSnapshot(call.context))
    const res = next(call)
    console.dir(getSnapshot(call.context))
    return res
}
```
