### ISSUE TITLE
Introduce custom types

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#673]
Some work was already done in #609, but there was no general issue describing the feature. So here it is. 

```
types.custom<S, T>({
   fromSnapshot(value: S): T {
        // will be cached from same S
    },
    toSnapshot(value: T): S {
        // only executed if value is different from the previous one
    }
})
```

This makes it possible to create custom types for Decimals, Dates etc. 

The contract is as follows:
* `T` is considered to be immutable (like frozen)
* `T` is allowed to be non-serializable (unlike frozen). After all, the Snapshot gets serialized in snapshots, patches etc
* `S` can be non-primitive, but should be serializable and immutable (see #588)
* Unlike (custom) references, the values are not computed, tracked, and getter and setter won't receive information about their usage context (like `parent`)

**Comment by mweststrate** [comment]
Example copied from #662:

```javascript
const MyBackendDate = types.custom<string, Date>({
   get(value: string): Date {
        const parsedDate = someWeirdParsingLogicFromTheString(value)
        return parseDate // a normal JS Date object
    },
    set(value: Date): string {
        const serializedForm = someWeirdUnparseLogicFromTheDate(value)
        return serializedForm // e.g. "Tue 7 Octobr '18'"
    }
})

const Appointment = types.model("appointment", {
   subject: types.string,
  date: MyBackendDate
})

const appointment = Appointment.create({
  subject: "Buy snacks",
  date:  "Tue 7 Octobr '18'"
})

console.log(appointment.date instanceof Date) // true
appointment.date = new Date() // n.p.
getSnapshot(appointment).date // some string representing the date
```

**Comment by robinfehr** [comment]
would it be doable to also implement a custom getSnapshot for them?
one could for example then implement the current Date type - while e.g. within react components working with the value from the getter - using another for the snapshot
or am I missing and such would already be achievable?

**Comment by mweststrate** [comment]
@robinfehr the return value from the setter / the input arg of the getter *is* the custom snapshot

**Comment by mweststrate** [comment]
but indeed, I think we should change the implemetation of `types.Date` to be a custom snapshot with this change

**Comment by robinfehr** [comment]
since i was quite confused here a quick summary from chat conversation:

`getter` , `setter` seem to be misleading names.
what was meant by them was:
`toSnapshot`, `fromSnapshot`

`toSnapshot`: invoked when using _getSnapshot(node)_
`fromSnapshot`: invoked when using _Appointment.create({ subject ... })_

also mentioned was: adding a third param:
`setter`: invoked on _appointment.date = new Date()_, to guarantee that toSnapshot can process the value which is stored.

**Comment by dnakov** [comment]
I'm wondering whether this can be used as a solution to #440...
Could I wrap a complex mobx observable object in it?
If yes, can `toSnapshot` be a computed property?

**Comment by philspitler** [comment]
Since merged, can this be closed @mweststrate?

Going through open issues to see if I may contribute and finding some in this state where it seems like it's wrapped up, but they are still open.

**Comment by robinfehr** [comment]
@philspitler thanks for reminding to close them all now :).

there are a few things that actually would need attention.
i'll try to open new issues with the pr welcome tag :)

**Comment by ryedin** [comment]
I know this is long closed, but just stumbled on it. 

Could you explain why this is true?

```
Unlike (custom) references, the values are not computed, tracked, and getter and setter won't receive information about their usage context (like parent)
```

**Comment by Aryk** [comment]
@mweststrate  - I'm finding that the value produced by my type.custom is triggering a render even though the input value did not change. Does the output value also have to satisfy "===" comparison from the old value?
