### ISSUE TITLE
Missing public types to generate type definitions in TS

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx-state-tree#679]
In order to generate type definitions for my library in TS (using declarations: true in tsconfig.json), TS asks for the following mbst types, which are not publicly available:

IContextEntry, INode, IValidationError, TypeFlags

This is a followup to https://github.com/mobxjs/mobx-state-tree/issues/256

**Comment by xaviergonz** [comment]
PS: it is really annoying to have to import those "fake" types just to create a library that depends on mbst, could all of those be declared as types instead of interfaces so they actually don't need to be exported/imported?

**Comment by mweststrate** [comment]
Is this a duplicate of https://github.com/mobxjs/mobx-state-tree#known-typescript-issue-5938 ? What TS version are you using? It seems to be fixed in TS 2.7 (ok, yes, MST is broken in 2.7, but there will be a fix for that early next week ;-))

**Comment by xaviergonz** [comment]
No dice with TS 2.7
Basically I need to re-export those types because i need declaration: true since it is a library, but they aren't exported from mobx-state-tree, so I'd need to re-export them from src/internals or whatever, which isn't pretty.

**Comment by mweststrate** [comment]
Could you create a PR with the missing ones?

Op wo 14 mrt. 2018 20:13 schreef Javier Gonzalez <notifications@github.com>:

**Comment by mweststrate** [comment]
Should have been fixed by #740
