### ISSUE TITLE
any options to turn typecheck into warning from throwing errors?

### ISSUE THREAD

**Issue by chenyong** [mobxjs/mobx-state-tree#680]
We are using MST however typechecking brings some inconvenience of throwing errors. We don't want it to throw errors after optimized code. Besides, errors thrown from minified code can hardly be understood. So we are seeking an solution for disabled errors in production. Best expectation is to turn them into warnings.

**Comment by robinfehr** [comment]
closing since #682 seems to be the same. feel free to reopen if you meant something else here.
