### ISSUE TITLE
Ask For Help: how to deal with a scenario like 'Department' and 'Employee'?

### ISSUE THREAD

**Issue by chj-damon** [mobxjs/mobx-state-tree#687]
Hi guys, I'm fairly new about MST but I'm trying to use it in my project to manage state. Here is the thing:
I have to entities: Department and Employee. One Department has many employees, one employee belongs to one department.
So this is how I create these two models:
```js
const Department = types.model('Department', {
  id: types.identifier(),
  name: types.string,
  employees: types.optional(types.array(Employee), [])
});

const Employee = types.model('Employee', {
  id: types.identifier(),
  name: types.string,
  department:            // I'm not sure how I should define this.
});
```
when I want to load employees, the backend server returns data like this:
```json
{
"employees": [{
  "id": 1, "name": "John", "department": {"id": 1, "name": "Design"}
}, {
  "id": 2, "name": "Susan", "department": {"id": 2, "name": "Frontend"}
}]
}
```
and when I want to load departments, the backend server returns data like this:
```json
{
"department": [{
"id": 1, "name": "Design", "employees": [{"id": 1, "name": "John"}]
}, {
"id": 2, "name": "Frontend", "employees": [{"id": 2, "name": "Susan"}]
}]
}
```
It works fine if I remove the 'department' in model 'Employee', but if I didn't remove it, the application reports an error.
I believe this is what it was called 'circular dependencies' in the document, 
but I tried `types.late(() => Department)` but it does not work neither.
I really need your help!
any comments would be appreciated!

**Comment by robinfehr** [comment]
hey there - i think that should get you going:
https://codesandbox.io/s/yq3q91q8z9
you might need to have a look at `preProcessSnapshot` too to slightly adjust the incoming data from the server.

**Comment by chj-damon** [comment]
@robinfehr I found a very confused problem:
see the demo link below:
[https://codesandbox.io/s/64n17j2n1w]()

the sequence I import these three stores actually affect the result:
If I didn't put `import {WorkshopStore} from './WorkshopStore';` on the first line, and I refresh the webpage, it will report an error:
```js
[mobx-state-tree] expected a mobx-state-tree type as the first argument, got undefined instead
```
BUT!! if I put it on the first line, it works fine!!!
I am so frustrated about this!
do you know any reason for this?

**Comment by robinfehr** [comment]
haven't looked close what the real issue below is but try to use `types.late` for these too.

**Comment by chj-damon** [comment]
the structure is copied from the demo in `mobx-state-tree/packages/mst-example-bookshop`, is there any other stucture I can learn from?

**Comment by chj-damon** [comment]
by using `normalizr` I think I've solved this problem.
