### ISSUE TITLE
Vue support

### ISSUE THREAD

**Issue by davidm-public** [mobxjs/mobx-state-tree#695]
just wondering if MST works with Vuejs?

**Comment by mweststrate** [comment]
MST itself works on any ES5 environment. To enable vueJS components to automatically react to mobx observables (which power MST as well), this probably probably offers that: https://www.npmjs.com/package/vue-mobx

**Comment by philspitler** [comment]
Does this need to be tested in order to close the issue @mweststrate?

**Comment by mweststrate** [comment]
Closing is fine. Can be reopened if needed if further questions arise.

Op wo 14 mrt. 2018 15:23 schreef Phillip Spitler <notifications@github.com>:
