### ISSUE TITLE
Mobx(4.0.1) and mobx-state-tree(1.3.1) not compatible

### ISSUE THREAD

**Issue by niral3737** [mobxjs/mobx-state-tree#698]
OS - Windows 10 x64
NodeJs v8.9.3
npm 5.7.1

repository for sample code - https://github.com/niral3737/testMobxStateTreeApp

I am working with mobx-state-tree and I have created a model Invoice with a field name. I am using that model in App.js class.

When it compiles, it throws

```
Failed to compile.

./node_modules/mobx-state-tree/dist/mobx-state-tree.module.js
2247:12-18 'mobx' does not contain an export named 'extras'.
```

I think the mobx version 4.0.1 is not compatible with mobx-state-tree version

**Comment by mweststrate** [comment]
Found, the peer dependencies where not migrated correctly when migrating to a mono repo, will fix
