### ISSUE TITLE
Exception in Todo MVC example

### ISSUE THREAD

**Issue by ochervak** [mobxjs/mobx-state-tree#7]
Steps:
- Add some similar todos name
- Mark some as completed
- Perform "Clear completed"

![screenshot_2016-11-24 12 48 59_sfaydm](https://cloud.githubusercontent.com/assets/13982649/20595888/810fdfb0-b244-11e6-81bc-79534d41f410.png)

**Comment by mattiamanzati** [comment]
Are you running the master branch on the npm-published one?

**Comment by ochervak** [comment]
Master branch

**Comment by mattiamanzati** [comment]
@ochervak It's actually a Known bug, and I have already encountered it.
You can temporarely remove these lines https://github.com/mobxjs/mobx-state-tree/blob/master/src/core/node.ts#L117-L120 since they only are safety checks. Unsure atm if they are actually needed.

**Comment by ochervak** [comment]
@mattiamanzati great. got it. thanks

**Comment by mweststrate** [comment]
Thanks @mattiamanzati! Sorry for the inactivity on the repo atm :) I'm still catching up with mobx itself, but I definitely continue on this in december ;-)

**Comment by mweststrate** [comment]
This should be fixed in the latest commits!
