### ISSUE TITLE
🚨 Looking for more maintainers 🚨

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#700]
Hi all, 

Over the pasts months it has become clear I don't have enough time to give MobX-state-tree the attention it deserves, which results in question remaining unanswered for too long. And although @robinfehr and @mattiamanzati stepped in, I think the package needs more maintainers. 

I'm pretty sure there are many people who have more practical experience with the package then I have, so please step up if you have used this package with success so far!

If you find diving into the code base to scary, just answering open, common questions and triaging bug reports would already be a great help!

**Comment by Bnaya** [comment]
I'm always around :)

**Comment by mweststrate** [comment]
@Bnaya, yes, noticed, and thanks for that! I've send an Github invite, that will make it even more easy :)

**Comment by luisherranz** [comment]
We (@orballo, @DAreRodz and me) are migrating a big project from Redux to MST. We love MST and we'd sure love to contribute more to the project. But time on startups is always scarce and Typescript is a big drawback. Neither of us knows it, nor have the time to learn it right now. So we can't contribute to the code or answer Typescript related issues but we'll try to help with the other issues!! :)

**Comment by Bnaya** [comment]
@benjaminjackman would love to see your progress on that!

**Comment by benjaminjackman** [comment]
@Bnaya I made an issue for using Conditional Types https://github.com/mobxjs/mobx-state-tree/issues/705 My implementation is still really more of a rough draft. I am able to use it for a couple of my projects but I need to clean it up quite a bit.

**Comment by KBorders01** [comment]
We are in the process of refactoring our main application to MST at Collage.com. Some of us may be able to contribute, but we are new to MST right now. We are particularly interested in helping with any performance optimizations.

**Comment by mweststrate** [comment]
Hey folks!

Thanks for all the positive responses! Really encouraging :) Everyone who responded above should have gotten a maintainers invite to this repository. Which means you will have full control over issues, and can push code, create branches etc. (Especially the last is way easier for collaboration then running your own forks)!

@robinfehr and me are currently compiling an overview of the status of the repo, and that should help to address any open issues in a more organized manner. Don't worry, there will be enough things to choose from :)

**Comment by jk-gan** [comment]
We are migrating our React app to MST in my company and we love it. I'm new to Typescript right now but I'm interested to contribute to the project.

**Comment by danpan1** [comment]
how can i help you with project? always wanted to take part in OSS. danpan@yandex.ru

**Comment by robinfehr** [comment]
@danpan1 https://github.com/mobxjs/mobx-state-tree/projects/1 here you can find issues which are good to chime in :)

**Comment by alexvcasillas** [comment]
I'll try to help with whatever I can in terms of usage and practical experience.
I'm also going to give a try to dive into the code base to see if I'm able to help with something!

**Comment by mweststrate** [comment]
Is someone interested in occasionally compiling a changelog and pushing a release to NPM?

**Comment by stariqmi** [comment]
@mweststrate  can I help? I've always wanted to help and grow by contributing to OSS :)

**Comment by mweststrate** [comment]
@stariqmi I hope! I am looking for someone who can monitor the open pull requests;

* Are they ready to be merged?
* Is there a changelog issue item linking to the PR, committer, and relevant issues?
* Is the proposed change breaking or non-breaking?
* Occasionally cut a release. Patches can always be released, breaking changes need coordination :-). 
* Occasionally ping either a reviewer or PR submitter if progress is stalled :-). 

Let me know if you are interested, then I'll send you the necessary invites. 

Thanks!

**Comment by stariqmi** [comment]
@mweststrate I am down for it!

**Comment by mweststrate** [comment]
@stariqmi! Cool! added you to the organization. If you need npm rights just send me your npm username :)

**Comment by stariqmi** [comment]
@mweststrate - thank you! my npm username is stariqmi as well :)

**Comment by mweststrate** [comment]
Hi folks! I made a rough roadmap for MST 3.0: https://github.com/mobxjs/mobx-state-tree/projects/2

So feel free to take a look in the things in the `Todo` lane and
1. Read it and place comments if you have doubts or think it is an awesome idea :)
2. If you feel for it, feel free to assign your own name to a story and pick it up!

I hope to spawn of a 3.0 branch ~tomorrow. 

Thanks in advance!

**Comment by mweststrate** [comment]
Also, if you feel anything is missing, feel free to bring it up, and open an issue  to discuss it!

**Comment by JoviDeCroock** [comment]
I think it would come in handy to set up a little guide on how to get started as a contributor, this could be a minimal setup guide for the project: how to get tests working, ... and maybe even a high level description about what file/folder handles what concern.

**Comment by mweststrate** [comment]
Anybody feeling for doing a proposal? I think most stuff is pretty straight
forward, but do use yarn.

Op do 28 jun. 2018 10:22 schreef Jovi De Croock <notifications@github.com>:

**Comment by chemitaxis** [comment]
Hi @mweststrate like you know we use MST in our product every day... and it’s time to help this project. Like @JoviDeCroock said, it would be amazing have a tutorial for starting to help. You use vscode normally, right? Prettier or something? It would be nice if you share the configuration of your editor and so staring and don’t waste time in these typical stuff. What do you think? Do I need to request an special access? I have contributed in other OSS projects. Thanks!

**Comment by mweststrate** [comment]
@chemitaxis @JoviDeCroock I updated the contributions guide: https://github.com/mobxjs/mobx-state-tree/tree/mst3#contributing. Hope it helps, and otherwise feel free to ask / PR any clarification!

Also, don't forget to keep an eye on https://spectrum.chat/mobx-state-tree!

**Comment by chemitaxis** [comment]
Thanks!

Chema Roldán

**Comment by shawnaxsom** [comment]
Are more maintainers still needed? While I am new to MobX State Tree, I've really enjoyed working on MobX itself on a few projects. I would be happy to help.

**Comment by mweststrate** [comment]
@shawnaxsom sure, all help is welcome! (sorry for late response, with enough projects Github notifications are useless, so I often miss new messages).

The easiest way to get started is to just browse through the issues, answer question or self assign stuff. If you have specific things you want to contribute, just let us know!

**Comment by krezicoder** [comment]
@mweststrate  I am also in for active contribution, I love MST made my life so easy on many projects.

**Comment by mweststrate** [comment]
@krezicoder awesome! I'll add you as maintainer. The most valuable contribution at this moment is probably helping people out with questions, but feel free to pick anything that peeks your interest :)

**Comment by mweststrate** [comment]
Or check open PRs :)

**Comment by mweststrate** [comment]
Re-opening this issue :) Could definitely use some more maintainers atm!

**Comment by krezicoder** [comment]
Hi, I am also interested. 

MST has helped us a lot in building many applications.

**Comment by FabriceReynolds** [comment]
I'm up for helping as I really like MST and would love to give back :)

**Comment by shawnaxsom** [comment]
I'm happy to help too. MST has been a great middle ground between Redux and
MobX, thanks for all of your work on MobX.

**Comment by mweststrate** [comment]
Awesome @FabriceReynolds & @shawnaxsom! The simplest way to get started is to dive into open issues and answer questions there and on https://spectrum.chat/mobx-state-tree. A lot of questions are about usage patterns, where your experiences could really help. 

Further there are minor bugs reported, that deserves addressing, so feel free up to put up PRs that verify or fix those! So there is nothing blocking from getting started right away. Usually I hand out more permissions once you need, so feel free to reach out as soon as you need them! For example, once you have multiple PRs, or want to close / moderate issues, maintainer permissions come in really useful!

**Comment by diegochavez** [comment]
Awesome :D I'll be here for help 👍

**Comment by mweststrate** [comment]
Awesome! Enough open issues to get started with! 😅 (if they are too old, they can probably just be closed)

**Comment by CmplxStack** [comment]
@mweststrate Hey, if additional maintainers are still needed I'd love to contribute! I've been having a great time helping with and advocating for all things mobx at work so the opportunity to help more just sounds like fun!

**Comment by mweststrate** [comment]
@CmplxStack that is awesome! First of all it'd be great if someone would take further care of #1569; testing, verifying and eventually releasing it :). Secondly there are a lot of issues that go unanswered now, being stale, valid bugs or answering the questions in there would be really great.

**Comment by zuhair-naqvi** [comment]
Used MST for several React Native apps, including the Australian Open. This is an awesome project that deserves much love, happy to help as a part time maintainer.

**Comment by mweststrate** [comment]
Did send invites! @zuhair-naqvi I'll reassign once accepted. Thanks!

**Comment by orlovcs** [comment]
@mweststrate MST has made life much easier, I'd be happy to help!

**Comment by mweststrate** [comment]
Awesome, #1569 or even processing any of the open PRs would be a great start!

**Comment by jesse-savary** [comment]
Hey, both @orlovcs and myself are looking to help out with MST.

We've been using it in for over the last year and it's been a massive time saver. Our whole app is structured around it and I've been looking for an opportunity to contribute back to Mobx(-State-Tree) as a company/developer.

I can confirm that Mobx 6 is working great for us without any need to change our code. I'll start poking through other PRs but is there anything in particular that needs to be done to get the release candidate out the door? I'm not entirely familiar with how your process works :)

**Comment by jesse-savary** [comment]
Hey @mweststrate, it's been a couple weeks now and I've reviewed a few PRs. I was recently tagged on one that has been open for quite some time but contains good code: https://github.com/mobxjs/mobx-state-tree/pull/1540/

What will it take for this PR and others to be merged?

**Comment by mweststrate** [comment]
@jesse-savary apologies, thought I had sent out invites already! Feel free to merge those you are comfortable with :). Releases can be coordinated with @Bnaya or @jamonholmgren. Thanks and sorry for the late follow up!

**Comment by jesse-savary** [comment]
No worries, I've accepted the invited now. Thank you very much!

**Comment by jamonholmgren** [comment]
@jesse-savary @Bnaya Looking forward to coordinating with you folks!

**Comment by jamonholmgren** [comment]
I think we can call this one "fixed". :-)

https://twitter.com/jamonholmgren/status/1331692221289041920
