### ISSUE TITLE
Add formater on models

### ISSUE THREAD

**Issue by pierrebiver** [mobxjs/mobx-state-tree#701]
I would like to know if it's possible to add a formater on models.
For instance:
```
export const Story = types.model(
    "Story",
    {
        id: types.identifier(),
        publishedOn: types.Date.format(val => new Date(val)),
        content: types.string,
    }
)
```
My model contains a field of type date, but I receive those data from my backend as string. Is there a method on models or type where I could do my transformation from a string to my date ?

**Comment by robinfehr** [comment]
checkout the custom types. they're designed to help in exactly such situations such as different date formats.

**Comment by pierrebiver** [comment]
Cool thank for your help!
