### ISSUE TITLE
Improve typing with Typescript 2.8 Conditional Types

### ISSUE THREAD

**Issue by benjaminjackman** [mobxjs/mobx-state-tree#705]
I don't see any open issues on this so I wanted to create an issue to track progress on using the upcoming Typescript 2.8 conditional types feature to provide stronger type guarantees for MST.

I have a very rough draft that I am experimenting with in a couple of projects and so far it looks very promising!

I will try to refine it into something that is intelligible enough to be shared. Currently since the conditional types stuff is so new I had to learn as I went, and so there is a lot of commented out and dead ends in the code.

A couple of quick notes on my implementation:
1. I implemented it as a hand written .d.ts file that provided most of the functionality I was using but is not exhaustive.

2. I used 3 distinct types for the factories: 
 a. Creation Type: This is a value that is legal to be passed into create and which has all the fields correctly marked as required / optional.
 b. Snapshot Type: This is what is emitted from toJSON / getSnapshot
 c. Runtime Type (which I just call Type): This is what is returned create is called.

Also, I have experimented with a deep readonly implementation for enforcing protected trees that should not be modified outside of an action. I had some success with it and think ultimately it could work, though I am not sure how to deal uniformly exposing types for unprotected trees.

**Comment by benjaminjackman** [comment]
I've made a package `h-mst` that facades the {types} import and published it here: https://yarnpkg.com/en/package/h-mst

It has considerably strengthened typing in my projects that use mobx-state-tree. 
I don't have a repo up for it yet because it's part of a larger project and because hopefully all it's mojo works it's way into mobx-state-tree proper.

I currently have it supporting mobx@4 & mst@2 I can backport to 1.4 if there is any demand.

**Comment by AaronFriel** [comment]
@benjaminjackman That's a great library, thank you so much.

**Comment by mweststrate** [comment]
@benjaminjackman would you be interested to create a PR on the core repo and apply these typing changes? I think it would greatly improve the project! 

If deep read only is troublesome you could skip that, but I think the that the 3 types generic change and mapped types are a great addition!

**Comment by ianschmitz** [comment]
TypeScript 2.8 is out :tada: 

https://blogs.msdn.microsoft.com/typescript/2018/03/27/announcing-typescript-2-8

**Comment by mweststrate** [comment]
Wip: https://github.com/mobxjs/mobx-state-tree/pull/774, h-mst helps a lot @benjaminjackman!

**Comment by benjaminjackman** [comment]
@mweststrate That's awesome! sorry for falling off the map on this, got sucked away to other stuff. I had attempted twice to rewrite mobx-state-tree to incorporate a lot of the changes, however it turned out to be a pretty large code bomb in both attempts and I didn't have time to finish it. Glad to hear it's helpful! I'll watch #774 to see if there is anything I can contribute.

**Comment by benjaminjackman** [comment]
Oh @mweststrate on challenge I encountered after adapting stuff to use conditional types + having a separated CreationType is that the typescript compiler got very slow. I noticed it was particularly bad with deep structural types. I managed to work around it by using classes, which made the inference / performance stuff go back to unnoticeable.

```typescript
export function clsModel<T extends object>(cls : {new () : T, name: string}) {
  return types.model<T>(cls.name, new cls())
}
```

which is then used like this

```
export const Resource = xtypes.clsModel(class Resource {
  id = types.identifier(types.string)
  color = "red"
  charCode = types.string
  abbrev = types.string
})
```

This is an example of something that without using classes was totally hosing build times (not that I wrote this test before I made the `clsModel` shortcut:

```typescript
test("Perf Testing", () =>{
  const M1 = types.model({})
  const M2 = types.model(new class {m= M1; o = types.maybe(M1)})
  const m2 = M2.create({m: {}})
  expect(m2).toEqual({m : {}, o: null})
  const M3 = types.model(new class {m= M2; o = types.maybe(M2)})
  const M4 = types.model(new class {m= M3; o = types.maybe(M3)})
  const M5 = types.model(new class {m= M4; o = types.maybe(M4)})
  const M6 = types.model(new class {m= M5; o = types.maybe(M5)})
  const M7 = types.model(new class {m= M6; o = types.maybe(M6)})
  const M8 = types.model(new class {m= M7; o = types.maybe(M7)})
  const M9 = types.model(new class {m= M8; o = types.maybe(M8)})
})
```

Thank you so much for all your hard work on mobx-state-tree!

**Comment by mweststrate** [comment]
First version can now be tried! `mobx-state-tree@2.0.4-types.1` Note that the new version is a lot more stricter around snapshots, but accurately :) (or it should be)

**Comment by mweststrate** [comment]
I'm especially curious about the performance impact in large projects on typescript / autocompletion etc. 

cc @mattiamanzati

**Comment by mweststrate** [comment]
@benjaminjackman curious, I can imagine that the same benefits are yielded when using interfaces more, and types less? Or maybe the cause for the speed change is that classes are nominal types; so they don't have to be structurally compared to other types

**Comment by Bnaya** [comment]
There's some times slowdown also with current MST, that this trick solves:
https://github.com/mobxjs/mobx-state-tree/pull/517/files 
Giving interface name to the typeof of the model's Type

**Comment by bourquep** [comment]
@mweststrate 

>I'm especially curious about the performance impact in large projects on typescript / autocompletion etc.

I've finished updating my project to MST v3.0.2, and one thing that is preventing me from merging it in our develop branch is that VSCode gets super slow for providing Intellisense and other live editing goodies.

Also, doing a production build of our React app seems to hang (the build has been running for 15 minutes now - it usually takes ~60 seconds to build).

I'm not sure if I should be opening a new issue for this, I am commenting here since this seems relevant to this thread but I'll file a new issue of you want me to.

**Comment by pelotom** [comment]
On my branch where I tried to upgrade to MST3, `tsc` is taking a very long time to compile now (~5 minutes, where before it took a few seconds), but WebPack still builds quickly! And VSCode seems just as usable as before. Very strange.

**Comment by benjaminjackman** [comment]
@pelotom What you are seeing may be related to this issue: https://github.com/Microsoft/TypeScript/issues/25023

you might want to turn off emitDeclarations if you have that on in your tsconfig.json

**Comment by pelotom** [comment]
@benjaminjackman 

>you might want to turn off emitDeclarations if you have that on in your tsconfig.json

You mean `declaration`? I wasn't setting it before at all, but explicitly setting to `false` doesn't help. I do notice though that there is only a problem when running in `--watch` mode, so it does seem related to the issue you linked...

**Comment by xaviergonz** [comment]
@mweststrate can this one be closed?

**Comment by mweststrate** [comment]
Yes, sorry! Has been released big time already indeed :)
