### ISSUE TITLE
Environment not available in pre-defined action hooks?

### ISSUE THREAD

**Issue by jayarjo** [mobxjs/mobx-state-tree#706]
It's kind of intuitively understandable why `getEnv(self)` is `undefined` in `afterCreate` of manually created child node, but what about `afterAttach`? Or environment is not automatically passed down to the child nodes as they are created and attached to the main tree?

**Comment by jayarjo** [comment]
Hm... wrote a test and it seems that env is available in `afterAttach` auto-magically after all. Probably got some discontinuity in my own code flow :/

Comments still appreciated, if any. Or - close.

**Comment by robinfehr** [comment]
look like a bug since it's inconsistent - on the root node we currently have the environment within the afterCreate hook but on any child node it will be undefined.

**Comment by robinfehr** [comment]
#708 tried to emphasise it a bit within the readme. 

a warning could be added later when we'd have more info about the currently running action which is something that we'll need for the middleware too.
