### ISSUE TITLE
Is There something wrong with types.map ?

### ISSUE THREAD

**Issue by kamalbennani** [mobxjs/mobx-state-tree#710]
I am getting this error while running test on mst-example-bookshop
![image](https://user-images.githubusercontent.com/14129459/37560076-da476858-2a31-11e8-818a-089474241626.png)

**Comment by mweststrate** [comment]
Looks like mobx 4 instead of 3

Op za 17 mrt. 2018 22:24 schreef Kamal Bennani Bouchiba <
notifications@github.com>:

**Comment by robinfehr** [comment]
PR welcome - the examples all need to be lifted to mobx 4.

**Comment by robinfehr** [comment]
closing in favour of #712
