### ISSUE TITLE
mobx-state-tree + CRA boilerplate?

### ISSUE THREAD

**Issue by corysimmons** [mobxjs/mobx-state-tree#713]
It'd make a nice companion repo to https://github.com/mobxjs/mobx-react-boilerplate

**Comment by sorenhoyer** [comment]
I'm not fan of that Idea.
Mobx and mst are straight-forward and easy enough to simply install in the official CRA repo. No need for a fork for those...  especially not now that you needn't eject CRA to use decorators thanks to the new Decorate API in Mobx4.

**Comment by corysimmons** [comment]
Yea tbh after I started getting used to it it seemed silly. Might help some newb like I was a few hours ago tho. :\
