### ISSUE TITLE
how to listen a variable  from store and make a new request

### ISSUE THREAD

**Issue by Frank1e0927** [mobxjs/mobx-state-tree#715]
I have a scene.
1:When I click on an item, I initiate a new request and update the data to a detail store.
2: And then I want to make a new request based on the change in the id in the detail.

--- others
in redux , i will use componentWillReceiveProps to listen props(id) change to make a new request,
But I found that in mobx-state-tree it doesn't trigger the componentWillReceiveProps.

so ,how to do this in mobx-state-tree？can somebody give me an easy example?

**Comment by robinfehr** [comment]
to setup an example I'd need a bit more information about your use case but:

- one option could be waiting for the result you get from the request and invoking another action from the action you've setup the first request. `flow` could make that more readable.

- another option could be setting up a `reaction` / `autorun` [mobx reaction docs](https://mobx.js.org/refguide/reaction.html)

hope that gets you going.

**Comment by Frank1e0927** [comment]
thank you so much , I solved the problem。

**Comment by Frank1e0927** [comment]
It does increase readability. I didn't use MST or mobx before, so I make it complicated. thank you

**Comment by harry-sm** [comment]
@luisherranz 
Could you elaborate on rob's second option? please, thanks.

**Comment by harry-sm** [comment]
I see. Thanks. Why do you have `self.fetchingFirstItem = true`? Is it used to prevent mutiple request  from the same end point?

**Comment by luisherranz** [comment]
It's just an example of other props involved in the sequence.

**Comment by harry-sm** [comment]
Ok, Thanks.
