### ISSUE TITLE
Empty sections in API.md

### ISSUE THREAD

**Issue by corysimmons** [mobxjs/mobx-state-tree#716]
https://github.com/mobxjs/mobx-state-tree/blob/master/API.md#complextype

Are these here because it's autogenerated or something?

**Comment by mweststrate** [comment]
@corysimmons yes, but no clue yet how to fix it, or even why it get's generated :'(

**Comment by corysimmons** [comment]
This link is 404'ing or I'd investigate. Which doc generator pkg are you using?

![image](https://user-images.githubusercontent.com/224636/37850187-ab345656-2eb0-11e8-859c-f0157ef5a255.png)

https://github.com/mobxjs/mobx-state-tree/blob/master/src/core/mst-operations.ts

**Comment by mweststrate** [comment]
The package is called `documentation`, see the `packages/mobx-state-tree/package.json` script `build-docs` to see how it is generated

**Comment by xaviergonz** [comment]
closing, since now it uses a different package to generate docs
although it has its own set of problems (namely lots of overloads showing), it doesn't exhibit this one
