### ISSUE TITLE
Error: [mobx-state-tree] expected a mobx-state-tree type as first argument, got function array

### ISSUE THREAD

**Issue by corysimmons** [mobxjs/mobx-state-tree#717]
Works:
```js
types.model({
  food: types.optional(types.string, ``),
})
```

Throws:
```js
types.model({
  food: types.optional(types.array, []),
})
```

why?

**Comment by corysimmons** [comment]
Also, how do I make `food` an empty array by default and load it with `fetch`'d JSON? I know how to use `flow` and await async data, but is there a preferred way to approach this common task?

**Comment by robinfehr** [comment]
could you please provide a codesandbox to reproduce it? 
the code you posted looks good.

**Comment by corysimmons** [comment]
@robinfehr Sure, https://codesandbox.io/s/l4jp1nnjj9

Just uncomment lines in both ShoppingList files to see err thrown.

**Comment by corysimmons** [comment]
Does `types.array` _always_ need to pass a subtype like `types.array(types.string)`?

**Comment by robinfehr** [comment]
huch - looks like i should go to bed instead of coding :D

it needs to be:
types.optional(types.array(types.string), [])

**Comment by corysimmons** [comment]
Let's say I don't know what type might show up in that array (e.g. `[1, 'str', { a: 2 }]`), is there a `types.any` I'm missing?

>looks like i should go to bed instead of coding :D
lol, I feel ya. Get some zzz

**Comment by mweststrate** [comment]
In that case use either a union of the things you know it can be, or
`frozen`. It is kinda the `any` type of MST, which this understanding, you
will not going to mutate the values (replacing is fine), as MST wont reason
about frozen things, but treat them as-is verbatim values

Op wo 21 mrt. 2018 om 00:32 schreef Cory Simmons <notifications@github.com>:

**Comment by corysimmons** [comment]
@mweststrate thanks!

**Comment by jstgermain** [comment]
So what was the solution? I am having the same issue right now.

**Comment by Abhishek12345679** [comment]
any update?

**Comment by Sean-Brown** [comment]
Apparently order of declaring the models matters

Throws:
```
const Template = types.model({
  id: types.identifierNumber,
  attributes: types.optional(types.array(TemplateAttribute), []),
});
const TemplateAttribute = types.model({
  id: types.identifierNumber,
  label: types.string,
});
```

Works:
```
const TemplateAttribute = types.model({
  id: types.identifierNumber,
  label: types.string,
});
const Template = types.model({
  id: types.identifierNumber,
  attributes: types.optional(types.array(TemplateAttribute), []),
});
```
