### ISSUE TITLE
async iterators/ async generators

### ISSUE THREAD

**Issue by robinfehr** [mobxjs/mobx-state-tree#720]
flow as well as async iterators made their way into mobx itself and should find their way into MST too. the plan is to expand the mobx flow to also be able to use it within MST.

e.g.:
```js
function delay(ms) {
  return new Promise(resolve => {
    setTimeout(resolve, ms)
  })
}
async function* asyncInterval(ms) {  
  while (true) {
    yield await delay(ms);
  }
}

const Store = types.model({
  count: types.number
}).actions(self => ({
  afterCreate: flow(async function * () {
    for await (const _ of asyncInterval(1000)) {
      self.count++;
    }
  })
}))
```

**Comment by duro** [comment]
Any update on timing for this? Very eager to get ahold of these core mobx features to enable things like flow cancellation and debounce.

**Comment by coolsoftwaretyler** [comment]
Hey folks - this MST issue is quite old, and I personally don't think it's on any near-term roadmap.

I'm going to close this out for now, but if folks are very excited about it, please feel free to send in a PR. I prioritize community PRs over my own planned work in MST, so I promise to be responsive if you do so. 

Thanks for your time!
