### ISSUE TITLE
types.Date dosnt work with moment - help needed

### ISSUE THREAD

**Issue by jennasalau** [mobxjs/mobx-state-tree#733]
It seems using https://momentjs.com/ will throw exception with `types.Date`

For example

```
import {types as T} from 'mobx-state-tree`
import moment from 'moment';

const MyModel = T.model('MyModel', {
     dateOfBirth: T.Date,
})


// Dosnt work
MyModel.create({
    dateOfBirth: moment('01/01/1990', 'DD/MM/YYY'),
})

// Works
MyModel.create({
    dateOfBirth: new Date('01/01/1990')
})
```

How can I make MST work with moment? Or should i use `T.frozen`?

Thanks for any advice.
Jenna

**Comment by Bnaya** [comment]
Moment creates a wrapper object around the native `Date` object
MST expects native `Date` object.
to can get the underlying object using:
```ts
moment('01/01/1990', 'DD/MM/YYY'). toDate()
```
 
Your create call will look like:
```ts
MyModel.create({
    dateOfBirth: moment('01/01/1990', 'DD/MM/YYY').toDate(),
})
```

and you can add a MST view to transform the date to moment object, or do it before use.

BTW Moment is considered not recommended for new projects.
there are other alternatives as:
https://github.com/moment/luxon
https://formatjs.io/

**Comment by jennasalau** [comment]
Okay thank you for the advice and quick response.

I had no idea moment js was dead.. Glad i asked.

Thanks
