### ISSUE TITLE
How to find identifier attribute from Model 

### ISSUE THREAD

**Issue by nachiket-p** [mobxjs/mobx-state-tree#735]
How can I get Identifier attribute for a Model?
Please provising something like identifierAttribute as described
e.g.
```
const Todo = types.model('Todo', {
    _id: types.identifier(),
    title: types.string,
    status: types.string,
 }),

printIdentifierAttribute = (Model) => console.log('Model ID Attr is: ' , Todo.identifierAttribute )
printIdentifierAttribute(Todo)
```

**Comment by robinfehr** [comment]
you could write you own fn using getMembers and check for the specific type.

**Comment by nachiket-p** [comment]
Hey @robinfehr , 
I am doing something like following for writing generic API calls, and for calling urls like /todos/{id} I need to know the attribute itself. 

```
const Todo = types.model(.....
const RestTodo types.compose(Todo, restify(Todo))
```

**Comment by robinfehr** [comment]
cannot see into your use case yet clear enough but the answer provided should get you going.
closing for now.  

if you need more help with your use case - please help us with a codesandbox. also it might be easier to put this conversation onto spectrum to communicate forth and back once a sample was provided.
