### ISSUE TITLE
[Feature request] Non-observable functions, props

### ISSUE THREAD

**Issue by elite174** [mobxjs/mobx-state-tree#738]
I know that it's possible to create volatile state, however this state still observable( through ref). It would be nice, if there was something like:

 ```
let a = types.model("someName", {
 bla bla
}).free({
   // this is the object, not a function that returns an object, 
  // because the functions inside this object shouldn't change observable properties
  variable:4,
  func: ()=>{}
})

a.func()
a.variable = 5
```

So in this case there is "free" or "sandbox" zone that can contain functions and variables, that are accessible but not observable (it's about performance)

**Comment by maxgallo** [comment]
Volatile state can be of two types, the one you refer to `.volatile` is indeed still observable but if you use volatile state in the context of the action it's not an observable anymore.

```javascript
const Store = types.model({
        todos: types.array(Todo),
        state: types.enumeration("State", ["loading", "loaded", "error"])
    })
    .actions(self => {
        const pendingRequest = null // a Promise
        const yourFunction = (a,b) => a + b;
```

I'm not entirely sure which functions do you need there but please do consider [Dependency Injection](https://github.com/mobxjs/mobx-state-tree#dependency-injection) as well as alternative solution

**Comment by Bnaya** [comment]
@elite174 can you give an example of a data you would save there?

**Comment by Bnaya** [comment]
You can do something with `views`
```ts
types.model("FooModel", {}).views((self) => {
  let notObzervableValue = 1;

  return {
    get notObzervableValue() {
      return notObzervableValue;
    },

    set notObzervableValue(v) {
      notObzervableValue = v;
    },
    plainFunction(n) {
      return n * notObzervableValue;
    }
  };
})
```

**Comment by elite174** [comment]
I just want to have non-observable properties that will be accessable through dot: someModel.nonObservableProperty
Maybe I shoud write some getters and setters in views for getting an access to variables in closure.
