### ISSUE TITLE
getSnapshot without postProcess

### ISSUE THREAD

**Issue by robinfehr** [mobxjs/mobx-state-tree#747]
issue to track the status of the PR #745.

it introduces:

```
getSnapshot(node, applyPostProcess: bool)
```

to deactivate the application of postProcessSnapshot fn to the snapshot when using `getSnapshot`.

**Comment by mweststrate** [comment]
@robinfehr just curious, what is the use case :)? And should we then also support the opposite, skip preProcessing? That can mess things really up though (like picking the wrong `types.union` branch as a result)

**Comment by robinfehr** [comment]
the use case is whenever someone needs a copy of node and apply refinements to e.g. `.create()` a new node but with a new property that leads to a different subtype (given an union with a dispatcher like you mentioned) or return the refined from within a view. (see #744)  i'm sure there are many other use cases. 

the current workaround is:
```
JSON.parse(JSON.stringify(self));
```

about the preProcessing...not so sure. this `applyPostProcess` flag is intended to be used on manually invoking `getSnapshot`, not to be used internally (yet).

**Comment by xaviergonz** [comment]
closing since this feature is already in MST
