### ISSUE TITLE
Having trouble with maybe type

### ISSUE THREAD

**Issue by duro** [mobxjs/mobx-state-tree#749]
I am working up a model like so:

```ts
const Session = types
  .model({
    token: types.maybe(types.string)
  })

const RootStore = types.model({
  session: types.optional(Session, {})
})

RootStore.create()
```

And getting the following error:

```
Error: [mobx-state-tree] Error while converting `null` to `AnonymousModel`:

    value `null` is not assignable to type: `AnonymousModel` (Value is not a plain object), expected an instance of `AnonymousModel` or a snapshot like `{ token: (string | null?) }` instead.
```

I guess I'm not fully grasping how to work with the maybe and optional types. Any help is appreciated.

**Comment by robinfehr** [comment]
your example works fine for me - just tested it.
https://codesandbox.io/s/x7p4knpnoz

would be great if you could provide an example of it as a sandbox.

**Comment by duro** [comment]
I was able to figure this out. It was not a problem with the setup of the tree, but something one of my actions was doing wrong. Still trying to get a hang of debugging MST & react-native
