### ISSUE TITLE
Flow actions mutations not syncing to Redux DevTools

### ISSUE THREAD

**Issue by duro** [mobxjs/mobx-state-tree#750]
Not sure if bug, or again a question (and if so, sorry for posting them all here, I tried the spectrum.chat room, but code pasting in there is a huge pain)

I have hooked up MST with Redux DevTools like so:

```js
const store = RootStore.create()
connectReduxDevtools(remotedev, store)
```

And I have some action that mutate one of the node like so:

```js
const SessionModel = types
  .model({
    token: types.maybe(types.string)
  })
  .actions(self => ({
    bootstrap: flow(function* bootstrap() {
      const sessionRaw = yield AsyncStorage.getItem(SessionStorageKey)
      if (sessionRaw) {
        const session = JSON.parse(sessionRaw)
        applySnapshot(self, session)
      }
    }),
    setToken: flow(function* setToken(token: string) {
      self.token = token
      yield AsyncStorage.setItem(
        SessionStorageKey,
        JSON.stringify(getSnapshot(self))
      )
    }),
    logout: flow(function* logout() {
      yield AsyncStorage.removeItem(SessionStorageKey)
      applySnapshot(self, {})
    })
  }))
```

When I trigger these actions, I notice no updates to the state tree in RDT. I see the actions firing, but the state does not update along with the actions.

Did I set this up wrong?

**Comment by ianschmitz** [comment]
I've noticed a very similar behavior. 

My experience has been that the flow action won't contain a tree diff, but a subsequent action unrelated action will include the state change that happened as part of the first flow action.

Can you confirm if you see your state changing in subsequent, unrelated actions?

**Comment by duro** [comment]
I am seeing the same behavior

**Comment by bourquep** [comment]
I have submitted PR #1032  with a fix for this.

**Comment by xaviergonz** [comment]
Made an alternative PR #1035 for it as well
