### ISSUE TITLE
disposer fn returned from addDisposer

### ISSUE THREAD

**Issue by robinfehr** [mobxjs/mobx-state-tree#758]
issue for the PR #753 

```js
const disposer = addDisposer(reaction(
  addDisposer(self, autoSaveDisposer)
    () => getSnapshot(self),
    snapshot => sendSnapshotToServerSomehow(snapshot)
))
```
makes reactions abort-able within view components (e.g. unmount) and on node destruction at the same time.

we might want to improve that further later (syntax wise)
maybe add reactions to mst itself so that doubly wrapped construct could become 
a simple `reaction`.

**Comment by xaviergonz** [comment]
Closing since returning the disposer was done in #1059 (without the disposing from the react component since mobx-react now has it's own personal disposeOnUnmount)
