### ISSUE TITLE
Method for introspecting on types

### ISSUE THREAD

**Issue by schicks** [mobxjs/mobx-state-tree#759]
I'm trying to construct types that asynchronously load data from a remote server. I'm doing this by wrapping some base type;
```javascript
function remote(type, initializer) {
    return types.model({errored:false, data:types.maybe(type)}).actions({...})
}
```
The problem is that I want to reflect the attributes, views, and actions of the wrapped type on the new returned type. Is there a way to pull out the names of all of these things so that I can generate getter actions on the wrapping type that reach down into the data attribute?

**Comment by robinfehr** [comment]
MST does only store them on the node, not on the type. 
on the the node you could use `getMembers`

you'd therefore probably have to create "fake" node to read them.
```js
getMembers(returnedType.create({...})) 
```

**Comment by schicks** [comment]
I suppose that makes sense, given that you would have to run the functions you give to `views` and `actions` to be able to figure out what methods the node will have.
