### ISSUE TITLE
Error: [mobx-state-tree] Functions are not supported as properties, use views instead

### ISSUE THREAD

**Issue by mortenko** [mobxjs/mobx-state-tree#760]
Hi I have following problem: 
Im trying to include my both models (SharedModel, DomainModel) into RootModel to keep it in one place but I get following error **Error: [mobx-state-tree] Functions are not supported as properties, use views instead**.  

This error I get when Im trying to import following line:

 `import { DomainModel } from "./domain-state";`

I dont understand why I have to use view instead. 

//index.js
```
import { types } from "mobx-state-tree";
import { SharedModel } from "./ui-state";
import { DomainModel } from "./domain-state";

const RootModel = types.model("RootStore", {
  sharedStore: types.optional(SharedModel, {}),
  domainStore: types.optional(DomainModel, {
    marked_photos: [],
    photos: [],
    matchedPath: "",
    photoName: "",
    state: "pending"
  })
});

const RootStore = RootModel.create({});

export default RootStore;
```
**UPDATE:**

// domain-state.js

Also I would like to ask when I need to access to the props of SharedModel .. it's is good solution I'm using here ? 

```
import { types, flow } from "mobx-state-tree";
import axios from "axios";
import { SharedModel } from "./ui-state";

export const DomainModel = types
  .model("DomainModel", {
    marked_photos: types.array,
    photos: types.array,
    matchedPath: types.string,
    photoName: types.string,
    state: types.enumeration("State", ["pending", "done", "error"]),
    sharedModel: types.optional(SharedModel, {})
  })
  .actions(self => ({
    handleUnZipFile: flow(function* handleUnZipFile() {
      const {
        userName,
        imagePath,
        archivePath,
        originalFileName,
        rootUniqueDirName
      } = self.sharedModel;
      try {
        const { data } = yield axios.post("/file/unzip", {
          userName,
          imagePath,
          archivePath,
          originalFileName,
          rootUniqueDirName
        });
        self.marked_photos = data.marked_photos;
        self.photos = data.photos;
      } catch (error) {
        throw new Error(error);
      }
    })
  }));

```

// ui-state.js
```

import { types, flow } from "mobx-state-tree";
import axios from "axios";

export const SharedModel = types
  .model("SharedModel", {
    isActiveScreen: "first",
    userName: "",
    isSuccessfullUploaded: false,
    inputValue: "",
    rootUniqueDirName: "",
    imagePath: "",
    archivePath: "",
    originalFileName: "",
    state: types.optional(types.enumeration("State", ["pending", "done", "error"]),"pending")
  })
  .actions(self => ({
   // here Im defining actions
  }));

```

It worked well before I import DomainModel into my index.js file where is defined RootModel. 

Thanks for help.

**Comment by robinfehr** [comment]
can you also show us the DomainModel? a quick [condesandbox](https://codesandbox.io/) is usually easier for such cases.

**Comment by luisherranz** [comment]
This looks fine to me. Could you please show us the code of `SharedModel`? Maybe the error is there.

**Comment by mortenko** [comment]
Thanks for fast answer. I updated my issue.

**Comment by mortenko** [comment]
Okey I found issue 
I didnt define the type of array in Domain Model 

```
export const DomainModel = types
  .model("DomainModel", {
   ....
  marked_photos: types.array(types.string),
   photos:  types.array(types.string),
  ....
  });
```
Anyway, I think it's strange error.

**Comment by luisherranz** [comment]
You need to specify the array type.

**Comment by luisherranz** [comment]
Yep, that's it! :)

Maybe we should improve that error.

**Comment by mortenko** [comment]
Yes, I agree because this error didnt give me any hint.

**Comment by robinfehr** [comment]
feel free to open an issue for the improvement of the message. if it would be created including a PR it would be even cooler ;)

**Comment by mortenko** [comment]
I have still one more question , which I asked: Also I would like to ask when I need to access to the props of SharedModel .. it's is good solution I'm using here ? in domain-state.js file.

**Comment by mortenko** [comment]
@robinfehr Okey I will look into :).

**Comment by luisherranz** [comment]
> I have still one more question , which I asked: Also I would like to ask when I need to access to the props of SharedModel .. it's is good solution I'm using here ? in domain-state.js file.

You can access the props of other nodes using `getParent` or `getRoot`. A view is usually a good place to store a pointer.

```js
export const DomainModel = types
  .model("DomainModel", {
    marked_photos: types.array,
    ...
  })
  .views(self => ({
    sharedStore: () => getRoot(self).sharedStore,
  })
  .actions(self => ({
    someAction: () => {
     const value = self.sharedStore.someprop
...
```
