### ISSUE TITLE
WebSocket buffer inside store suggestion

### ISSUE THREAD

**Issue by xgenvn** [mobxjs/mobx-state-tree#761]
Hi,

I'm trying to put a socket.io-client instance inside a mst definition. I want to make the socket.io buffered/data stream goes reactive, is it possible to do so? The reason to do this is I only want one socket.io-client instance alive between navigations.

Some options I'm thinking of:
- use plain mobx instead, and Atom (ref https://github.com/sampsonjoliver/mobx-websocket-store)
- use socket.io-client as normal prop

**Comment by robinfehr** [comment]
recently also asked on spectrum. they ended up using the dependency injection to do so and did setup an action on the channel. something like that:

```js
.actions(self => ({
  someAction(param, param2) {
      ...
  },
  afterCreate() {
    self.channel = getEnv(self).socket.channel("channelId")
    channel.on = self.someAction;
  }
 }))
```
