### ISSUE TITLE
destroy() result in Error: "This object has died and is no longer part of a state tree."

### ISSUE THREAD

**Issue by jayarjo** [mobxjs/mobx-state-tree#762]
I get this error when trying to remove a model from collection.
```
Error: [mobx-state-tree] This object has died and is no longer part of a state tree. It cannot be used anymore.
```
I was thinking that maybe I'm doing something wrong, but then I've found this [video](https://egghead.io/lessons/react-remove-model-instances-from-the-tree) and I'm basically doing exactly the same thing.

**Comment by jayarjo** [comment]
This might be related: https://github.com/mobxjs/mobx-state-tree/issues/506

**Comment by mweststrate** [comment]
Please provide a sandbox reproduction, this exception might very well be
valid

Op di 10 apr. 2018 19:49 schreef Davit Barbakadze <notifications@github.com

**Comment by jayarjo** [comment]
Turns out I was failing to update cached components that were observing models being removed.

**Comment by miguelrs** [comment]
I'm having this issue as well - @jayarjo what do you mean with this? 
> update cached components that were observing models being removed
