### ISSUE TITLE
Can't Access Properties From Mbox State Tree

### ISSUE THREAD

**Issue by chobo2** [mobxjs/mobx-state-tree#763]
I probably forgot to do something but my property is always undefined.

    import { types } from "mobx-state-tree";
    
    const AppStore = types
      .model("AppStore", {
        show_sidebar: true
      })
      .actions(self => ({
          toggleSidebar() {
              self.show_sidebar = !self.show_sidebar;
          }
      }))
      .views(self => ({}));
    
    export default AppStore;

Stores

    import {RouterStore} from 'mobx-react-router';
    import AppStore from '../stores/AppStore.js';
    const routingStore = new RouterStore();
    const stores = {
        routingStore,
        AppStore
    }
    
    export default stores;

index.js

    import React from 'react';
    import ReactDOM from 'react-dom';
    import { Provider  } from 'mobx-react';
    import { useStrict } from 'mobx';
    import createBrowserHistory from 'history/createBrowserHistory';
    import {syncHistoryWithStore } from 'mobx-react-router';
    import { Router } from 'react-router'
    
    import AppContainer from './components/App';
    
    const browserHistory = createBrowserHistory();
    
    import stores from '../src/stores/Stores';
    
    const history = syncHistoryWithStore(browserHistory, stores.routingStore);
    
    ReactDOM.render(
        <Provider {... stores}>
            <Router history={history}>
               <AppContainer />
            </Router>
        </Provider>,      
           document.getElementById('app')
    );

Component

    @observer
    @inject('routingStore', 'AppStore')
    export default class App extends Component {
      render() {
        const props = this.props;
        const {push} = props.routingStore;
        const AppStore = props.AppStore;
        console.log(AppStore.show_sidebar, AppStore, 'side');
     return ( ) // exuding to shorten code.
    }

**Comment by mweststrate** [comment]
Please submit bugs using a code sandbox reproduction. But a quick glance: you never actually create a store in the above code, you are just passing type definitions around. Use `AppStore.create()` to actually create a store and inject that into the tree

**Comment by chobo2** [comment]
Hey,

What do you mean code sandbox reproduction? How do that I do that.

I think you are right, I was following a video that I think is from a version that maybe did not require that. Thought I am not sure where to call AppStore.Create, do I do it in my store object?

**Comment by wbercx** [comment]
In your `stores.js`.

Note how you've created a new _instance_ of the `RouterStore`, and then put that into your `stores` object. You need to create an _instance_ of your AppStore as well. The way you do that in MST is **not** using the `new` keyword, but by calling `.create()`.

````
const stores = {
    routingStore,
    appStore: AppStore.create()
}
````

`.create()` also takes initial data as the first argument, should you have any. 

In your component, you should then refer to `appStore` rather than `AppStore`.

**Comment by chobo2** [comment]
Ok, cool. that works. Just need to import "mobx-state-tree" in as well.

How do you want me to post a bug up(I know this not a bug), but I might have run into an IE 11 issue, as what I got right now does not work in IE 11, get an exception.

{exception}	Object doesn't support property or method 'assign'
in mobx-state-tree.module.js

```
   var name = opts.name || defaultObjectOptions.name;
        // TODO: this test still needed?
        if (!/^\w[\w\d_]*$/.test(name))
            fail("Typename should be a valid identifier: " + name);
        **Object.assign(_this, defaultObjectOptions, opts);**
        // ensures that any default value gets converted to its related type
        _this.properties = toPropertiesObject(_this.properties);
        freeze(_this.properties); // make sure nobody messes with it
        return _this;
    }
```

`stack	"TypeError: Object doesn't support property or method 'assign'\n   at ModelType$$1 (eval code:3080:9)\n   at model$$1 (eval code:3349:5)\n   at eval code (eval code:9:1)\n   at ./src/stores/AppStore.js (http://localhost:8080/index_bundle.js:2136:1)\n   at __webpack_require__ (http://localhost:8080/index_bundle.js:710:12)\n   at fn (http://localhost:8080/index_bundle.js:95:13)\n   at eval code (eval code:9:1)\n   at ./src/stores/Stores.js (http://localhost:8080/index_bundle.js:2148:1)\n   at __webpack_require__ (http://localhost:8080/index_bundle.js:710:12)\n   at fn (http://localhost:8080/index_bundle.js:95:13)"
`

Maybe I don't have some babel setting to convert it?

**Comment by robinfehr** [comment]
just open a new issue for bugs. 

not so sure though we should support IE since idk how many polyfill's would need to be included. 
(i guess it might work using the ts compiler, but not so sure about async and other things)
