### ISSUE TITLE
atomic middleware is not safe or correct for async actions 

### ISSUE THREAD

**Issue by lostfictions** [mobxjs/mobx-state-tree#770]
The "atomic" middleware in the `mst-middlewares` package seems to unfortunately have some correctness issues when used with async actions (where presumably it's most useful.) Here's a simple failing test:

```patch
diff --git a/packages/mst-middlewares/test/atomic.ts b/packages/mst-middlewares/test/atomic.ts
index 1dca6f8..2aa9b15 100644
--- a/packages/mst-middlewares/test/atomic.ts
+++ b/packages/mst-middlewares/test/atomic.ts
@@ -31,6 +31,7 @@ const TestModel = types
                 return self.z
             }),
             throwingProcess: flow(function*(x) {
+                self.z += x
                 yield delay(2)
                 self.z += x
                 yield delay(2)
@@ -68,3 +69,15 @@ test("should rollback on async action failure", async t => {
         t.is(m.z, 1)
     }
 })
+
+test("should rollback on async action failure 2", async t => {
+    const m = TestModel.create()
+    try {
+        const p = m.throwingProcess(3)
+        m.inc(13)
+        await p
+    } catch (e) {
+        t.is(e, "Oops")
+        t.is(m.z, 14)
+    }
+})
```
The test will fail with a value of `1`, even though there was also another increment action that succeeded.

The problem is that all these state changes are dependent on existing state -- including changes that might have happened concurrently to the async process -- so it's insufficient to just record a stream of patches. To illustrate, let's look at the patch stream for this test:
```js
onPatch(m, (patch, inversePatch) => {
    console.log(JSON.stringify(patch), '\n', JSON.stringify(inversePatch))
})
```

```
{"op":"replace","path":"/z","value":4}
{"op":"replace","path":"/z","value":1}
```
This is the first change in the `throwingProcess` flow. So far so good.

```
{"op":"replace","path":"/z","value":17}
{"op":"replace","path":"/z","value":4}
```
Now we see the synchronous increment action. You might start to see the problem at this point.

```
{"op":"replace","path":"/z","value":20}
{"op":"replace","path":"/z","value":17}

{"op":"replace","path":"/z","value":23}
{"op":"replace","path":"/z","value":20}
```
The second and third flow patches are based on the values of the sync increment.

When we roll back, we apply the inverse patches in reverse order. Only the patches caused by the flow action were recorded, so we apply:
```
{"op":"replace","path":"/z","value":20}
{"op":"replace","path":"/z","value":17}
{"op":"replace","path":"/z","value":1}
```
and the final value of `z` is `1`, despite the fact that the `inc(13)` action also happened and succeeded. This is just a minimal contrived example, applying changes to a single property, but even here you can probably start to imagine several other cases where concurrent actions touching shared state would cause consistency problems, even if they're all using this middleware.

I think one solution to this would be to snapshot the state of the tree before an async atomic action, and then record all other actions -- not the patches, but the calls and arguments -- that happen during an action. Then if the action fails, roll back the state of the tree to before the flow started, and attempt to reapply the other actions. Even that approach, though, risks having issues if the arguments passed in to the action are based on intermediate state. It _might_ work if you could record all the properties being accessed, rather than the values themselves at that point in time.

Basically, _you can't rely on patches based on interleaved state_. You might have one or two objections here:

1. _What if I'm just setting an absolute value like "true" or "false" or "cat" or "dog", instead of incrementing a value relative to another? With some slight tweaks to how we listen to and replay patches, those state changes should be fine._
  
    Right, but if you're applying those absolute values _based on a state that was rolled back_ -- another value in the tree, a computed, or even a validation function that checks if you're allowed to perform that action -- those "absolute" values are still being applied based on incorrect information. This is arguably the case for a lot of non-trivial actions.
  
2. _What if we recorded deltas in the patches, instead of the state at the time the action is applied?_
  
    Right -- if the action is _commutative_ (like the addition actions in this test) that could work. But that's not the general case. This approach _could_ be generalized to be correct for all concurrent actions, but it basically means implementing [CRDTs](https://en.wikipedia.org/wiki/CRDT). (That would be awesome, but maybe outside the scope of MST or this five-LOC middleware.)

**Comment by mweststrate** [comment]
This problem is not generically solvable; there are two approaches to undo / redo:

1. record patches, inverse apply (which causes the problems as demonstrated)
2. record snapshots, inverse apply is safe (as in: goes back to the original state), but this will also undo changes _not_ caused by the current process!

To solve this undo / redo 100% reliable one should devise a merge / conflict strategy per node that might have changed and that strategy depends on the actual problem domain, (what does it mean when this and that value conflict, can we just pick a winner or should we bail out?), so this is more a best effort approach that could be used as basis for something more sophisticated.
