### ISSUE TITLE
Question: Pattern for edit forms in nested trees

### ISSUE THREAD

**Issue by jhholm** [mobxjs/mobx-state-tree#771]
I just migrated my project from mobx to mobx-state-tree as I needed a data model which is nested.

I have two types of models: books and pages with each having an identifier and a bookstore that has an array of books. A book has an array of pages.

I have an edit form created with React to edit a book or a page. So far I'm using a pattern to get the clone of the book or page from the bookstore to be kept in an internal React component state for editing. After editing I apply the snapshot to the book/page in the bookstore if changes are saved. I would like to remove all/most of the internal React component states. So what I'm asking is, what kind of a pattern should be used with mobx-state-tree to keep the editing state outside of a component.

With mobx-utils I could use createViewModel, but a similar concept does not seem to exist with mobx-state-tree. If I store the book/page that should be edited in another bookstore property, I get an error with duplicate identifiers. Any good patterns/ideas would be appreciated.

**Comment by luisherranz** [comment]
That's right, for most forms it's probably a simpler pattern to encapsulate its state and only modify your store after submission (and validation). 

There are cool solutions like [Final Form](https://github.com/final-form/react-final-form) which can help you create powerful forms without having to code the state yourself.

**Comment by mweststrate** [comment]
Architectural questions can best be discussed here: https://spectrum.chat/mobx-state-tree
