### ISSUE TITLE
mobx 4.2.0 compatibility

### ISSUE THREAD

**Issue by faassen** [mobxjs/mobx-state-tree#772]
I thought I'd try mobx 4.2.0 but it doesn't appear to be compatible with mobx-state-tree. When I upgrade to mobx 4.2.0 I get a warning on the console that multiple mobx versions are in use. I can't find anything obvious that's going wrong (package.json of mobx-state-tree doesn't look odd to me), but for some reason mobx-state-tree pulls in mobx 4.1.1 *in addition* to mobx 4.2.0.

**Comment by mweststrate** [comment]
It is probably because npm / yarn still don't treat peer dependencies
entirely correctly. If you are using yarn, adding a "resolutions" block to
your package.json might solve the issue

Op di 17 apr. 2018 om 11:41 schreef Martijn Faassen <
notifications@github.com>:

**Comment by mweststrate** [comment]
Ok, this is an actual config error in the package.json, where mobx was accidentally an explicit dependency. 

Just fixed in 2.0.4
