### ISSUE TITLE
"Failed to create" console.error log during typecheck

### ISSUE THREAD

**Issue by faassen** [mobxjs/mobx-state-tree#775]
I'm writing some tests that need to verify whether the model type I generate is correct. At first I used Model.create to do this verification -- if it throws when I expect to, the generated type is correct. But as a side effect this logs an ugly console.error in my console during the tests, which is rather ugly.

So I thought I'd switch to typecheck() instead. But it *still* throws the "Failed to create" errors. Is it correct that typecheck() does this too? If yes, does it make sense to introduce a way to shut these messages up?

**Comment by mweststrate** [comment]
Nope that sounds like a bug. Please create a sandbox reproduction

Op wo 18 apr. 2018 10:30 schreef Martijn Faassen <notifications@github.com>:

**Comment by faassen** [comment]
Yup, I will close as a dupe.

**Comment by mweststrate** [comment]
Note that this was fixed in the last release😊

Op ma 14 mei 2018 09:00 schreef Martijn Faassen <notifications@github.com>:
