### ISSUE TITLE
[Question] Remove registered listener such as `OnPatch`?

### ISSUE THREAD

**Issue by breakds** [mobxjs/mobx-state-tree#777]
By experiments I found that if a particular `OnPatch` is executed twice, 2 listener will be created  and the callback will be called twice upon each `patch` event. Therefore my questions are

1. Is there a way to find the already-registered listeners for a node?
2. Is there a way to unregister a listener?

I tried to search online but could not find an answer to this. Sorry if this is a too-trivial question.

Thanks!

**Comment by robinfehr** [comment]
the registered patches are not exposed.

the onPatch method returns a disposer. calling that disposes the listener.
```js
const onPatchHandler = () => { 
    console.log('patch catch')
}
const disposer = onPatch(node, onPatchHandler)
disposer(); // onPatchHandler shouldn't be called anymore
```

**Comment by breakds** [comment]
Thanks a lot for the answer! Sorry about the late reply - I discovered this from some code example and forgot to update here.

Closing the issue.
