### ISSUE TITLE
undo manager with async await

### ISSUE THREAD

**Issue by yonatanmn** [mobxjs/mobx-state-tree#779]
I have an existing project using MST. 
When starting it, I chose the `async await` pattern, using `actions` after the `await` so it will have proper context. 
I think it's cleaner, and also [works better with typescript](https://github.com/mobxjs/mobx-state-tree/issues/778) 

Everything worked fine, but when I've tried to add `UndoManager` it throws from this [file](https://github.com/mobxjs/mobx-state-tree/blob/56310e24e89e6f8a6b190edc79f4326a8791b1eb/packages/mobx-state-tree/src/middlewares/create-action-tracking-middleware.ts#L53) with
 
```
Cannot read property 'async' of undefined
```
in flows that used async await. 
When changing to the flow+generator patter,   `UndoManager` started working.

Apparently `atomic` + `UndoManager` also causes problems, but I still need to explore this more.

**Comment by robinfehr** [comment]
please provide a sandbox

**Comment by mweststrate** [comment]
Closing as there is still no reproduction
