### ISSUE TITLE
Disable console.errors in production mode when typechecking

### ISSUE THREAD

**Issue by nathanbirrell** [mobxjs/mobx-state-tree#781]
**Scenario**

* Use `typecheck` to validate a model at runtime (with `NODE_ENV=production`)
* Cause an exception in that check using invalid data

**Expected**

Error is thrown by MST, so that I can catch it a level above, but **no console.error gets logged** in production.

**Actual**

Error is thrown by MST, console.error gets logged.

Do we really want to log console errors in production?

**Comment by mweststrate** [comment]
I think that is a bug, can you create a test case showing where a type
error gets logged even when catched?

Op di 24 apr. 2018 08:49 schreef Nathan Birrell <notifications@github.com>:

**Comment by nathanbirrell** [comment]
Sure @mweststrate - take a look at https://github.com/mobxjs/mobx-state-tree/pull/785

**Comment by mweststrate** [comment]
This has been released a while ago
