### ISSUE TITLE
map.values() in getting started

### ISSUE THREAD

**Issue by vincentleeuwen** [mobxjs/mobx-state-tree#783]
Hey guys,

Quite a newbie so I might be doing something wrong. I wasn't able to get the getting started
tutorial working without spreading the map.values() being used:

```
[ ...store.todos.values() ].map(todo => <TodoView todo={todo} /> )
```

Not sure if I am missing something here?

Cheers,

Vincent

**Comment by luisherranz** [comment]
I think `.values()` returns now a generator. You can use either `Array.from(store.todos.values())` or import `values` from the `mobx` package and use `values(store.todos)`.

**Comment by luisherranz** [comment]
No problem, I found it ☺️

**Comment by paul42** [comment]
get the same error from the next code item, [Computed Properties](https://github.com/mobxjs/mobx-state-tree/blob/master/docs/getting-started.md#computed-properties)

it looks like the code sandboxes are not updated to the latest version of `mobx-state-tree` if it'd be helpful I could take a crack at updating docs once the PR (mentioned above) is accepted fully

**Comment by luisherranz** [comment]
> is this an acceptable use of 'values' ? will it still be computed properly or should I try a different tack?

Absolutely!

`values()` is now the recommended approach. I changed the docs and the [codesandbox](https://codesandbox.io/s/6vj27j6mqr). You can take a look at the PR here: https://github.com/mobxjs/mobx-state-tree/pull/784

Closing now. Feel free to reopen if needed!

**Comment by jvaclavik** [comment]
Just FYI, the same problem is also in this tutorial: https://egghead.io/lessons/react-more-mobx-state-tree-types-map-literal-union-and-enumeration

**Comment by kcharles52** [comment]
It can also be traced in the videos uploaded on youtube [here](https://www.youtube.com/watch?v=VF3FVGYUj_w&list=PLBguFN_KEgLifQh-8jiUqOtXNKll1bjEI&index=11)

**Comment by alexamy** [comment]
Hi. Now if I am using `values` from mobx I got working example, but messed up types - cannot access `todo.name`.
[Example](https://codesandbox.io/s/mobx-state-tree-playground-broken-values-7s9ujq?file=/src/Todos.tsx).
What I'm doing wrong?
