### ISSUE TITLE
Setting up a bidirectional many-many entity relationship for display and edit

### ISSUE THREAD

**Issue by late-warrior** [mobxjs/mobx-state-tree#790]
Hi,

Thanks for the great library you have here.  The conciseness of the solutions using this library has been very appealing.  I am getting started and am looking for general patterns to follow in organizing relationships using mst.

[Codesandbox Link](https://codesandbox.io/s/18z746m973) showing the issue.

Specifically, I have a many-many bidirectional relationship between ``User`` and ``Group``.   My use-case is to allow for limited edit (a couple of attributes) of group information from the user screen and also a limited edit of user information from the group screen.  

I've been managing them with a store that has ``userMap`` and a ``groupMap`` and then wiring up their relationship in a ``afterCreate`` lifecycle hook.  

1.  Is this idiomatic usage or is there a better recommended pattern ?
2.  I tried to follow the advice of the egghead [tutorial](https://egghead.io/lessons/react-build-forms-with-react-to-edit-mobx-state-tree-models) about using ``clone`` to manage a draft of the edited entity.    

This seems to throw an error like:

```
[mobx-state-tree] Failed to resolve reference 't1' to type 'User' (from node: /users/0)
```

Pasting the failing test for easy reference:

```
it("clones correctly", () => {
  const group1 = rootStore.groupMap.get("t1");
  // As expected
  expect(group1.users[0].name).toBe("Jim");
  // Clone the group
  const clonedGroup = clone(group1);
  // array lengths match as expected
  expect(group1.users.length).toBe(clonedGroup.users.length);
  // however dereferencing the cloned group's user reference array fails
  expect(clonedGroup.users[0].name).toBe("Jim");
});
```

Stripped down version of the bidirectional relationship and the failing test - in codesandbox [link](https://codesandbox.io/s/18z746m973)

EDIT: updated with correct codesandbox link

**Comment by DmacMcgreg** [comment]
I'm also in the same box as #1.

It would be great if maybe the reference system could be jigged to support a Many-Many relationship.

RIght now, I have Users and Accounts.

Account can have many Users
User can belong to many Accounts.

Currently, I'm trying to grab the related users through the root store using a computed value, but it doesn't seem that the computation is firing when the users are fetched and put into the User Store, which is held in the root store.

Is there an accepted way of doing this type of behaviour?

**Comment by mweststrate** [comment]
General design questions are best asked at https://spectrum.chat/mobx-state-tree
