### ISSUE TITLE
Is there a way to reset a model to its initial state?

### ISSUE THREAD

**Issue by marcofugaro** [mobxjs/mobx-state-tree#791]
Right now when I need to reset a model (for example when I navigate with the app router to a certain page), I have a `reset` action like this:

```js
reset() {
  self.name = ''
  self.owner = ''
  self.location = ''
  self.employees = 0
  self.isOpen = false
  self.list = []
},
```

These values are the same I pass as a second argument to the `t.optional` in the model, like this:
```js
const SampleModel = t
  .model('SampleModel', {
    name: t.optional(t.string, ''),
    owner: t.optional(t.string, ''),
    location: t.optional(t.string, ''),
    employees: t.optional(t.number, 0),
    isOpen: t.optional(t.boolean, false),
    list: t.optional(t.array(t.string), []),
  })
```

and this is how I initialize that state:
```js
const State = t
  .model('State', {
    sampleModel: t.optional(SampleModel, {}),
    otherSubState: t.optional(OtherSubState, {}),
  })
```

Is there a standard and easier way to reset a model to its initial state?

**Comment by luisherranz** [comment]
Maybe you can save it on `afterCreate`. Something like this:

```js
const State = t
  .model('State', {
    sampleModel: t.optional(SampleModel, {}),
    otherSubState: t.optional(OtherSubState, {}),
  })
  .actions(self => {
    let initialState = {};
    return {
      afterCreate: () => {
        initialState = getSnapshot(self);
      },
      reset: () => {
        applySnapshot(self, initialState);
      },
    }
  })
```

**Comment by kyhy** [comment]
I used the method mentioned above getting and saving snapshot on the initial state. It works great most of them time! However, when the model is big, entire UI locks waiting for, I'm guessing, garbage collection to finish?

Do you have any other recommendation for reinitializing?

**Comment by marcofugaro** [comment]
Here is what I ended up doing:

```js
const State = t
  .model('State', {
    sampleModel: t.optional(SampleModel, {}),
    otherSubState: t.optional(OtherSubState, {}),
  })
  .actions(self => ({
    resetSubState(subState) {
      const subStateName = subState.$treenode.subpath
      self[subStateName] = {}
    },
  }))
```

And this is what become of the reset method

```js
reset() {
  const { resetSubState } = getRoot(self)
  resetSubState(self)
},
```

A bit hacky, but this is what I needed to do.

**Comment by rdewolff** [comment]
And making a snapshot afterCreate() does not work in react-native if you restart the app. As a new afterCreate() will be triggered uppon app restore with the wrong snapshot.

**Comment by marcofugaro** [comment]
UPDATE: here is a better way to do it
```js
const State = t
  .model('State', {
    sampleModel: t.optional(SampleModel, {}),
    otherSubState: t.optional(OtherSubState, {}),
  })
  .actions(self => ({
    reset() {
      Object.keys(self).forEach(key => {
        self[key].reset && self[key].reset()
      })
    },
  }))
```

reset method:

```js
reset() {
  applySnapshot(self, {})
},
```

**Comment by rdewolff** [comment]
Yes that's a nice example, thanks @marcofugaro. And you could even compose this reset method with your stores ;)

**Comment by danikkks** [comment]
@marcofugaro so to reset model I just need to call `applySnapshot(self, {})`?

**Comment by marcofugaro** [comment]
that works too @danikkks!

**Comment by marcofugaro** [comment]
In my case I had some states that couldn't be reset (like [mst-react-router](https://github.com/alisd23/mst-react-router)). So I was checking if they had the reset method.

**Comment by danikkks** [comment]
ok, I got it, thanks!
