### ISSUE TITLE
Interacting with MST models from plain mobx

### ISSUE THREAD

**Issue by schicks** [mobxjs/mobx-state-tree#795]
I'm trying to build a view into a large set of data (~10k records loaded into the browser) that could change frequently from data changing on the server side or the user changing the query. I want to use MST for modeling the user queries, because my experience has been it's spectacularly good for forms and other user interaction state. However, the data itself is not particularly interactive, and I certainly don't need snapshotting capabilities on it. Given the concerns raised in #440, it seems like I should store the data in plain mobx and the user entered filters on the data in mst. Is it possible from the mobx side to react to changes in mst models?

**Comment by Bnaya** [comment]
You can use type.frozen to store the rows, so MST won't process them and it will be a lot quicker

**Comment by schicks** [comment]
But if I change the entire object, won't it have both saved somewhere in the tree? or am I misunderstanding how the persistence works?

**Comment by Bnaya** [comment]
```ts

interface IPlainObject {
  id: string;
  name: string;
  metadata: string[];
}

types
  .model("Repository", {
    // the as here is so you will get type info and all
    // might not be needed with future MST
    // the readonly is to help remember it's not obsverable data so you shound't change it 
    entires: types.array(types.frozen as Readonly<IType<IPlainObject, IPlainObject>>),
    selectedEntriesIds: types.map(types.string),
  })
  .actions(self => ({
    // this will trigger reaction, as the array itself is observable but not the entries in the array
    // and the old array and valus will be GC'd
    updateList(l: IPlainObject[]) {
      self.entires = l as any;
    },
    toggleSelection(id: string) {
      self.selectedEntriesIds.has(id) ? self.selectedEntriesIds.delete(id) : self.selectedEntriesIds.set(id, id);
    },
    // this will also trigger reaction
    addEntry(e: IPlainObject) {
      self.entires.push(e);
    }
  })).views((self) => ({
    get electedEntries() {
      return self.entires.filter(e => self.selectedEntriesIds.has(e.id))
    }
  }));
```

**Comment by schicks** [comment]
So if I understand correctly, changes to the array (adding entries, reordering, etc.) will be tracked still the way you have written this. My use case is that I have an array of ~10k objects that, on a given request, could be replaced completely. The entire array is immutable; I will never reorder or sort it, but I do want to have reactive views on it that give filtered entries as you presented. Could I do this by just gong one level up and making entries a frozen type itself rather than an array of frozen?

**Comment by Bnaya** [comment]
yes you can,
you can make @computed on mobx store, and access property on MST store, and they will work together.

And this is also should work, as you described 
```ts
  .model("Repository", {
    // the as here is so you will get type info and all
    // might not be needed with future MST
    // the readonly is to help remember it's not obsverable data so you shound't change it 
    entires: types.frozen as Readonly<IType<IPlainObject[], IPlainObject[]>>,
    selectedEntriesIds: types.map(types.string),
  })
  .actions(self => ({
    // this will trigger reaction as you change the refrence 
    updateList(l: IPlainObject[]) {
      self.entires = l as any;
    },
    toggleSelection(id: string) {
      self.selectedEntriesIds.has(id) ? self.selectedEntriesIds.delete(id) : self.selectedEntriesIds.set(id, id);
    },
  })).views((self) => ({
    get electedEntries() {
      return self.entires.filter(e => self.selectedEntriesIds.has(e.id))
    }
  }));
```

**Comment by schicks** [comment]
Thank you! I'm leaning toward the plain mobx route so that entries can be more than a plain object, but this has really helped me understand the usage of frozen better. Couldn't ask for a more helpful response.

**Comment by harry-sm** [comment]
> you can make @computed on mobx store, and access property on MST store, and they will work together.

@Bnaya How?
