### ISSUE TITLE
Mixing React HOC into MST store.

### ISSUE THREAD

**Issue by schabluk** [mobxjs/mobx-state-tree#796]
Hi.

Is this an anti-pattern?

```js
import { types, getParent } from "mobx-state-tree";
import React from "react";

export default types
  .model("HoC", {})
  .views(self => ({
    hoc(Component) {
      return class extends React.Component {
        render() {
          return <Component onClick={self.hancleClick} {...this.props} />;
        }
      };
    }
  }))
  .actions(self => ({
    hancleClick(event) {
      console.log("hancleClick", event);
    }
  }));

```

**Comment by skellock** [comment]
I would vote yes.  Usually you want to keep state & views further apart than this.

This kinda feels like what `mobx-react` brings to the table.

Disclaimer:  I'm a rando on the internet. What's more important than my opinion is your sense of exploration and discovery. Keep doing that.

**Comment by Bnaya** [comment]
I don't really see what's the benefit,
if you want a more elaborated discussion, you can try at spectrum
https://spectrum.chat/mobx-state-tree

**Comment by schabluk** [comment]
Yes, it seems a bit redundant.
Thank you.
