### ISSUE TITLE
Idea: introduce eager union

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#804]
See also: https://spectrum.chat/?t=2abe14ea-d0bc-4300-9f03-8953078b4c77

**Comment by mattruby** [comment]
I'd be happy to help with this one in any way.

**Comment by mweststrate** [comment]
Interested in PR with unit tests? (implementation is welcome as well of
course, but writing tests might be less intimidating and is at least as
helpful 😊)

Op wo 9  2018 16:19 schreef Matt Ruby <notifications@github.com>:

**Comment by mweststrate** [comment]
Eager should probably become the default, which has nice performance benefits

**Comment by mattruby** [comment]
I've been working on this: https://github.com/mobxjs/mobx-state-tree/compare/master...mattruby:feature/eager-union

Could someone help me out with how to take a varaible number of parameters first and an options object on the tail in TS?

The biggest change was here: https://github.com/mobxjs/mobx-state-tree/compare/master...mattruby:feature/eager-union#diff-4b29a6b67d0347e1e37b69c96cd65b7eR330

In doing this, I now properly sort the union types.  Before, the first types was appended to the end.

**Comment by mweststrate** [comment]
@mattruby awesome! I think the union order swap is correct indeed. @k-g-a noticed the same. 

I think there is a utility `isType`, so if you check `isObject(arguments[arguments.length -1]) && !isType(arguments[arguments.length -1]))` you can `.pop()` it of to get the options

**Comment by mweststrate** [comment]
Hey @mattruby! What is the status on this one? Need help somewhere? Feel free to open a PR already and mark it as `WIP:`

**Comment by mattruby** [comment]
Sorry for the delay. Let me see where I can get this morning.

**Comment by mweststrate** [comment]
Reviewed the branch, and merged it with some little changes! Saw the the trouble with that last argument indeed, so instead changed the setup to use `{ dispatcher: fn, eager: boolean }`. 

Thanks a lot @mattruby!

**Comment by mattruby** [comment]
THANKS!!
O man!  Moving the dispatcher function is a great decision.

**Comment by mweststrate** [comment]
Thank you! It was just the last push ;-)

**Comment by mweststrate** [comment]
Closing, will be part of MST 3
