### ISSUE TITLE
maps should serialize by default as entries

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#808]
The default serialization of maps should use entries format (`[[key1, value1], [key2, value2]]`) instead of objects. This better aligns with biult-in maps, and fixes type coercion issues of identifiers in snapshots.

`types.map` should still have an option to use the current format

See also #807

**Comment by Bnaya** [comment]
I think this will pave the way for `Set` support?

**Comment by mweststrate** [comment]
This might be not strictly needed anymore with #884

**Comment by mweststrate** [comment]
Superseded by #904 and there seem no immediate reason anymore to implement this
