### ISSUE TITLE
change `types.frozen` to `types.frozen<T>(defaultValue?: T)`

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#809]
This makes is possible to type `types.frozen`

**Comment by Bnaya** [comment]
Maybe also make the given type readonly recursively ?

**Comment by dsabanin** [comment]
I've been beating by this one for far too many times, so I'd like to volunteer to work on that. I have a basic solution but I want to polish it a little more.

**Comment by mweststrate** [comment]
The breaking change would be that you need to use `types.frozen()` instead
of `types.frozen`


Op do 24 mei 2018 om 04:23 schreef Jono Job <notifications@github.com>:

**Comment by fruitraccoon** [comment]
@mweststrate Ah of course, my bad.  

Perhaps the `types.frozen` could be redefined as an instance of `types.frozen()`?  It could be depreciated for removal in the next major release if you're wanting to keep the api surface tidy.  

I haven't checked the code so there may be reasons why this is a bad idea.  Just hoping that a strongly typed frozen might be available before v3.x :)  Will be looking forward to it whatever version it's in!

**Comment by mweststrate** [comment]
wel, to be able to `types.frozen()`, `types.frozen` has to be a function.
but MST types are not functions but objects. Theoretically we could mix in
all the properties of the MST Frozen type into the `frozen` api function,
but I think that would be quite messy and confusing

Op do 24 mei 2018 om 10:13 schreef Jono Job <notifications@github.com>:

**Comment by fruitraccoon** [comment]
Yes, I think you're right - it's not worth the added complexity.  I'll just have to be patient! :)

**Comment by mweststrate** [comment]
Closing, will be part of MST 3
