### ISSUE TITLE
How can we use this library with `lazyObservable`?

### ISSUE THREAD

**Issue by leesiongchan** [mobxjs/mobx-state-tree#81]
Given:
```javascript
const userFromApi = {
  image: 5,
  name: 'Brad Pitt',
};

const User = types.model({
  // $image: lazyObservable(),
  image: types.number,
  name: types.string,
});
```

How can we lazily fetch the `image` whenever we call `user.$image`? What is the best practice to handle this kind of use case?

**Comment by mweststrate** [comment]
At the moment, no, but #172 should allow to build similar patterns in MST types

**Comment by djgrant** [comment]
@mweststrate This pattern is only possible with reference types though. Is that correct?
