### ISSUE TITLE
minor question about egghead.io video tutorials series & observer on components

### ISSUE THREAD

**Issue by paul42** [mobxjs/mobx-state-tree#813]
Hey Team, loving MST so far, just wondering where the best place is to ask a question about the MST video tutorials?

Specifically I was watching [video #5 ](https://egghead.io/lessons/react-render-mobx-state-tree-models-in-react)

in one part (around 3:38) Michel applies the `observer` wrapper to the component `WishListView` in the video, after this is applied, the `setInterval` created previously (3:00-3:30) the component begins updating, however when i was trying it myself, I found that it did not start updating automatically - adding console.logs into my model's actions I found the methods were being called, but the view wasn't updating until I wrapped the smaller component `WishListItem` with `observer` as well, then it started updating - am I doing something wrong, or has there been some drift in the past 5 months? 

Thanks for your time, sorry for so many questions!
-Paul42

**Comment by mweststrate** [comment]
It might very well be that there was video capture edit mistake there (producing videos is a lot less linear then the end result looks :-)). But it is recommended to put `observer` on all of your components that relate to observables, so it sounds correct to add it.
