### ISSUE TITLE
is there a way to run actions in sequence (mixed sync/async) on various nodes of the tree?

### ISSUE THREAD

**Issue by jayarjo** [mobxjs/mobx-state-tree#817]
Suppose I have a heavily branched and nested node tree, now I need to trigger some actions in sequence. Some are sync actions, some are async. I've checked [applyAction](https://github.com/mobxjs/mobx-state-tree/blob/master/API.md#applyaction), but it seems that it requires action/actions to be invoked on the same target, but what if targets are scattered across the child nodes? How does one do that in a consistent way?

**Comment by mweststrate** [comment]
Not sure if I understand the question correctly, but I think this is more a general programming question, which can be solved by either using normal `async / await` or the `flow` utility from MST
