### ISSUE TITLE
Typing self in actions and views: documentation advices poorly performing way

### ISSUE THREAD

**Issue by k-g-a** [mobxjs/mobx-state-tree#818]
In the documentation:
https://github.com/mobxjs/mobx-state-tree/tree/v2.0.5#typing-self-in-actions-and-views
it's said that one can use local "views" variable to refer a prop:
```
const views = {
    get upperProp(): string {
        return self.prop.toUpperCase();
    },
    get twiceUpperProp(): string {
        return views.upperProp + views.upperProp;
    }
  }
```
However, accessing such computed values (e.g. inside render method of an observed component) always leads to full recompute. This is easily prooved by [tracing](https://mobx.js.org/best/trace.html) those properties.
Tracer says:
```
[mobx.trace] 'PROP NAME' is being read outside a reactive context. Doing a full recompute
```
Which is true, because 'views' object itself is not observed, but properties are copied to 'self' during instance initialization.

This leads to performance drop as every such property is recomputed on every re-render. 
Should we add a warning to the documentation or completely remove it in favor of
```
const Example = types
    .model({
        prop: types.string
    })
    .views(_self => {
        const self = _self as IExample;
        return {
            get upperProp(): string {
                return self.prop.toUpperCase();
            },
            get twiceUpperProp(): string {
                return self.upperProp + self.upperProp;
            }
        };

    });

type ExampleType = typeof Example.Type;
interface IExample extends ExampleType {}
```

**Comment by mweststrate** [comment]
Good catch! would you mind updating the readme?

**Comment by k-g-a** [comment]
Of course. Should I add a warning to existing example, provide the one from comment above or do both?

**Comment by mweststrate** [comment]
I think both. If it get's too long maybe put it in a separate md file in
docs. (the whole TS section). Thanks in advance!

Op ma 18 jun. 2018 om 17:13 schreef Gleb <notifications@github.com>:
