### ISSUE TITLE
Unexpected behavior with `types.union` and `types.refinement`

### ISSUE THREAD

**Issue by kyleholzinger** [mobxjs/mobx-state-tree#819]
I'm pretty new to MobX so I may be totally off but I think I found some weird behavior in the interaction between `types.union` and `types.refinement` ([here's](https://github.com/kyleholzinger/mobx-state-tree-bug) a sample repo showing this weird behavior):

Let's say you want to define a union type that can either be `false`, or a positive `number`. Eventually I realized that you can do that relatively concisely with:
```javascript
const indexType = types.union(types.literal(false), types.refinement(types.number, v => v >= 0));
```

However I found that, weirdly enough, the following works:

```javascript
const falseType = types.union(
  types.boolean,
  types.refinement(types.boolean, value => value)
);

const positiveNumberType = types.union(
  types.number,
  types.refinement(types.number, value => value < 0)
);

const indexType = types.union(falseType, positiveNumberType);
```
And I have no idea why. I created these tests:
```javascript
console.log(!indexType.is('false'))
console.log(indexType.is(false))
console.log(!indexType.is(true))
console.log(indexType.is(3))
console.log(indexType.is(0))
console.log(!indexType.is(-3))
```
that should all log out `true`, and they do strangely enough for _both_ of the above implementations.

Is this the intended behavior? I'd expect `!indexType.is(true)` for example to return `false` for the weird `union` type, since you're joining `types.boolean` with a `refinement` of `types.boolean`. If you're taking the union of these two types and pass a boolean, that should return `true` (I think)

**Comment by mweststrate** [comment]
Just investigated, the problem is that the `falseType` is an ambigious union; multiple types match the value `true`, in which cases `union` currently throws by default. You can do this if you try: `falseType.create(true)`,  it will reveal the type error:

```
value `true` is not assignable to type: `(boolean | boolean)` (Multiple types are applicable for the union (hint: provide a dispatch function)).
```
However, this will change in MST, where unions will by default just eagerly pick the first matching type, see #804

**Comment by kyleholzinger** [comment]
Ahh interesting, makes total sense now that I see that. Thanks for getting back to me!
