### ISSUE TITLE
Cannot get rootStore in nest store

### ISSUE THREAD

**Issue by asyntrix** [mobxjs/mobx-state-tree#822]
After learn mobx quite a while, I found it really easier to use than redux but to handle the state we still need to use MST. which I found it confusing with some methods that I cannot really access and I cannot found any useful document around. 

Here is the rootStore to use in the applicatoin. 

```
const RootStore = types.model("RootStore", {
    studentStore: types.maybe(StudentStore),
    subjectStore: types.maybe(SubjectStore)
});

export default RootStore.create({
    student: StudentStore.create({
        id: "A0-2018",
        firstName: "Sync",
        lastName: "John"
    }),
    subject: SubjectStore.create()
});
```

SubjectStore

```
const Subject = types.model({
    name: types.string,
    description: types.string
});

const SubjectStore = types.model("SubjectStore", {
    subjects: types.optional(types.array(Subject), [])
}).actions(self => ({
    getSubjectByStudentId(id) {
        //Get subjects by studentId
    }
}));
```

I want to access to the SubjectStore inside StudentStore, and this is what I do. 

```
const StudentStore = types.model("StudentStore", {
    id: types.identifier(),
    firstName: types.string,
    lastName: types.string,
    subjects: types.optional(types.array(Subject), [])
}).actions(self => ({
    getAllSubject() {
        let subjectStore = self.$treenode.subject;
        self.subjects = subjectStore.getSubjectByStudentId(self.id)
    }
}));
```
I'm not sure if this a correct behavior to access rootStore in MST, and can I use getRoot() method as mention in the document.

**Comment by jayarjo** [comment]
It's definitely more future-proof to access root node via `getRoot` rather than trying to use node properties directly.

**Comment by mweststrate** [comment]
I think you should look a second time at the model of your problem domain,
you have no subjects living in two places: inside the
RootStore.subjectStore, and inside RootStore.studentStore.subjects. I
suspect that the latter should be a types.array(types.reference(Subject))
instead. See the concept of references in the docs for more details

Op do 24 mei 2018 om 06:26 schreef Davit Barbakadze <
notifications@github.com>:

**Comment by asyntrix** [comment]
Nice to mention, but there is a different here. What we have here are two subject arrays, one for all students where the data already fetch from the server and other one for specific student where we want to filter it from all students store,. This where I think I can use rootStore to get advantage for the root structure. It would be nice if we can have an example to use getRoot.

**Comment by asyntrix** [comment]
Cool, I got what you mean this would be well structure with the reference type. Thanks
