### ISSUE TITLE
Error: 'Cannot modify 'store' the object is protected and can only be modified by using an action' when using multiple yield statements

### ISSUE THREAD

**Issue by abubberman** [mobxjs/mobx-state-tree#824]
HI,

I have an issue using the generator syntax inside async actions. When using multiple yield statements inside the action, i get the following runtime error: 'Cannot modify 'Store', the object is protected and can only be modified by using an action' 

![image](https://user-images.githubusercontent.com/13328911/40165987-b039617c-59bd-11e8-8214-7f2661442aa2.png)

When using only 1 yield , everything is working fine, but i need the result of the first call in the second call.

it is also working when calling a seperate action to process the received result, but I don't like the separate action....

![image](https://user-images.githubusercontent.com/13328911/40166128-18b61a42-59be-11e8-9e49-f1bfb56338cf.png)

Is it possible to use this syntax with multiple async calls? 

Many thanks!

**Comment by luisherranz** [comment]
Are you using `flow`?
https://github.com/mobxjs/mobx-state-tree/blob/master/docs/async-actions.md#asynchronous-actions-and-middleware

**Comment by abubberman** [comment]
Yes.. I'm using flow

**Comment by mweststrate** [comment]
Please provide a small reproduction for this issue, for example by forking the code sandbox linked in the issue template

**Comment by abubberman** [comment]
It seems to be a problem with only one project.
I have created a new project and no exceptions occur when executing 2 yields inside a flow function.  

At the moment, we are using the .then() syntax in our project, which is working fine. So if we decide to use flow again, I will have another look at it.

So i guess this issue can be closed.

**Comment by abubberman** [comment]
Thanks @bourquep, that fixed the problem. Now I only have one issue left. 
[https://github.com/mobxjs/mobx-state-tree/issues/823](url)

**Comment by rdewolff** [comment]
Thanks a lot @bourquep for your tip : encountered exactly this issue while refactoring some code. Could have spent some hours looking without your comment! 👍

**Comment by iofirag** [comment]
> FWIW, I've been struggling with a similar issue (_Cannot modify 'Store', the object is protected and can only be modified by using an action_ while modifying state within a `flow` async action) and the problem was that VSCode had auto-imported `flow` from `mobx`, not `mobx-state-tree`...
> 
> ¯_(ツ)_/¯

Thanks man, you saved my day. :)

**Comment by alvincrespo** [comment]
@bourquep You saved my life. Thank you.

**Comment by tvald** [comment]
Conflicting imports from `mobx` vs `mobx-state-tree` seems to be a common issue. Any chance some unique alias for the `mobx-state-tree` version could be added and recommended in documentation / examples?

**Comment by Carduelis** [comment]
> Conflicting imports from `mobx` vs `mobx-state-tree` seems to be a common issue. Any chance some unique alias for the `mobx-state-tree` version could be added and recommended in documentation / examples?

I found this the evilest thing in mst. I think the maintainers every time giggles when you use `flow` from `mobx` instead `flow` from `mobx-state-tree`.

**Comment by osrl** [comment]
I have the same issue and I use flow from `mobx-state-tree`. Do one of you guys have an idea about this?

**Comment by Syedanas-ctrl** [comment]
> I have the same issue and I use flow from `mobx-state-tree`. Do one of you guys have an idea about this?

see if there is a then block after await.
The function you pass to then is not an action. Note that functions that run within an action (or flow) do not count as the action itself.
