### ISSUE TITLE
Not a child error when setting boolean map twice

### ISSUE THREAD

**Issue by luisherranz** [mobxjs/mobx-state-tree#826]
If you try to set the same `id` twice in map of booleans, strings or numbers, it fails with a `No a child` error.

```js
const Store = types
  .model({
    map: types.optional(types.map(types.boolean), {})
  })
  .actions(self => ({
    toogleMap: id => {
      self.map.set(id, !self.map.get(id));
    }
  }));
```

Sandbox here: 
https://codesandbox.io/s/w07rrrx6j8
(click toggle twice)

The definition of `map.set` in mobx states this:
> `set(key, value)`. Sets the given key to value. The provided key will be added to the map if it didn't exist yet.

The part *"The provided key will be added to the map if it didn't exist yet"* gives the impression that `set` can be called more than once.

I don't know if this is the desired behaviour or not. Maybe I'm missing something!

**Comment by jonavila** [comment]
@mweststrate I'm experiencing a similar issue which I believe comes from this commit:
https://github.com/mobxjs/mobx-state-tree/commit/5e595283ffcd085e46f5e99f59a143f422c37221

All identifiers are cast to string, but if you use `set` instead of `put`, the identifiers are stored as numbers and this check fails:

https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mobx-state-tree/src/types/complex-types/map.ts#L136

I believe Mobx's ObservableMap.prototype.set doesn't do the conversion to string.

I'm using set instead of put because of #876. In the mean time, I'll use `set('' + id,  value)` to get around this issue.

**Comment by jonavila** [comment]
@mweststrate As soon as I find some time, I'll try to help with this. Can you provide some background as to why we need to normalize identifiers to string?

**Comment by mweststrate** [comment]
Historically there are two reasons, not entirely sure which one is in play here:

1. Older version of MST did this as they are backed by mobx observable maps, which only supported string keys (MobX 3 and below)
2. MST maps are currently serialized to key / value objects (this will change in MST 3). So, when taking a snapshot, generating a patch, etc etc, the key would always turn into a string (JavaScript does not have support for numeric keys on objects, even array indices are actually strings!)

**Comment by luisherranz** [comment]
I've updated my codesandbox with a couple of tests:
https://codesandbox.io/s/w07rrrx6j8

```js
const Store = types
  .model({
    map: types.optional(types.map(types.boolean), {})
  })
  .actions(self => ({
    toogleMap: id => {
      self.map.set(id, !self.map.get(id));
    }
  }));

// This one pass fine 👍
test("Toogling once shouldn't throw", () => {
  const store = Store.create({});
  expect(() => {
    store.toogleMap(1);
  }).not.toThrow();
});

// This one throws with 'Not a child 1' error 👎
test("Toogling twice shouldn't throw", () => {
  const store = Store.create({});
  expect(() => {
    store.toogleMap(1);
    store.toogleMap(1);
  }).not.toThrow();
});
```

Are they ok? Should I add them here: https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mobx-state-tree/test/map.ts?

**Comment by mweststrate** [comment]
@luisherranz sorry, missed your comment, but I copied the test to that file now indeed, and can confirm it passes in #904
