### ISSUE TITLE
getParentOfType should take into account composition

### ISSUE THREAD

**Issue by pelotom** [mobxjs/mobx-state-tree#828]
If a parent type is composed of 2 types,

```js
const ParentModel = compose(A, B);
```

then calling `getParentOfType(node, A)` or `getParentOfType(node, B)` on a descendent should be able to retrieve the `ParentModel` node.

**Comment by k-g-a** [comment]
Good day! 
This could not be implemented in current realisation of ```compose``` as it produces brand new type which in turn does not posess any knowledge about composed types. It works same way as ```.named()```/```.actions()```/```.views()``` etc.
Consider following example:
```javascript
const Child = types
  .model('Child', {})
  .actions(self => ({
    getA() {
      return hasParentOfType(self, ParentA)
    },
    getB() {
      return hasParentOfType(self, ParentB)
    }
  }));

const ParentA = types.model('ParentA', {
  child: Child
});
const ParentB = ParentA.named('ParentB');

const parentA = ParentA.create({child: {}})
console.log(parentA.child.getA()); //true
console.log(parentA.child.getB()); //false
const parentB = ParentB.create({child: {}})
console.log(parentB.child.getA()); //false
console.log(parentB.child.getB()); //true
```

But this issue made me think of ```types.union```, which won't (but could) be found in such manner. Although taking union types in considiration will incure slight overhead of checking nodes all the way up to the root for ```instanceof Union```. 
If we decide this is desired behaviour I can make PR.

**Comment by mweststrate** [comment]
MST is designed to work on actual types, as it is a runtime system, so that requires a slightly different type thinking pattern than in typical OO. Which mostly has benefits, but sometimes not, like in this case with composition; Compose is truly just behavior composition, not inheritance. So instead you should be checking for a parent that matches `types.union(A, B, ParentModel)`. See also: https://github.com/mobxjs/mobx-state-tree#simulate-inheritance-by-using-type-composition

**Comment by pelotom** [comment]
That unfortunately makes it less modular, because a child has to be aware of the exact union of things that make up their parent, rather than just being aware of the part that is relevant to them. This doesn't have anything to do with OO, it's just simple type theory that if `x: T`, then implicitly also `x: A | B | T`.
