### ISSUE TITLE
A version of `types.maybe` which uses `undefined` instead of `null`

### ISSUE THREAD

**Issue by pelotom** [mobxjs/mobx-state-tree#830]
[In TypeScript especially](https://medium.com/@basarat/null-vs-undefined-in-typescript-land-dc0c7a5f240a), `undefined` is almost always preferable to `null` as a representation of unset values, so it would be nice if there was a version of `types.maybe` (`types.maybeUndefined`?) which used `undefined` instead of `null`.

**Comment by Bnaya** [comment]
you have types.optional, which is i think what you look for

**Comment by pelotom** [comment]
Yes, you can implement it with `optional`,

```ts
export function maybeUndefined<S, T>(type: IType<S, T>): IType<S | undefined, T | undefined> {
  return types.optional(types.union(type, types.undefined), undefined);
}
```

but it would be cool if it were built in 🙂

**Comment by mweststrate** [comment]
I think it would be interesting to consider dropping `null` as default nullable, and use `undefined` instead. So that for example `maybe` accepts `undefined` instead of `null`, by default etc

**Comment by k-g-a** [comment]
It seems to me that we could introduce ‘types.nullable’ as direct replacement of current ‘maybe’, and convert ‘maybe’’s default to ‘undefined’, as proposed in previous comment

**Comment by mweststrate** [comment]
Done! In MST 3 `types.maybe` will use undefined as default value, and `types.maybeNull` can be used for the old behavior

**Comment by sis-dk** [comment]
This doc need an update stating this change?
https://mobx-state-tree.gitbook.io/docs/v/new-docs/types-overview
