### ISSUE TITLE
MST fails with an array of inputs fields

### ISSUE THREAD

**Issue by harry-sm** [mobxjs/mobx-state-tree#833]
I am using MST to populate a form with an array of fields for the [formik](https://github.com/jaredpalmer/formik) lib. However, when I try to edit a field that has been generated from an array it fails. I use the `clone` utility to pass a clone of the node to my form but it still fails. If I, however, use `getSnapshot` it works but I feel as though I'm not using `getShaphshot` the way it was intended. 

Here is an [example](https://stackblitz.com/edit/react-ts-jmrfbz?embed=1&file=StoreForm.tsx) of the issue.

MST is awesome!

**Comment by mweststrate** [comment]
Can you point a bit more exactly what goes wrong or what you would expect? I have for example no idea what `arrayHelpers.insert(emails.length, '')` means or whether it is even relevant for the question :)

I would not expect formik to understand MST models, so passing a snapshot instead of a clone sounds quite fine to me?

**Comment by harry-sm** [comment]
It is as you said formik does not understand MST models. So I just use `mobx.toJS()` instead.

`arrayHelpers.insert(emails.length, '')`
The `arrayHelpers` is an object containing a collection of methods that formik give you access to. It is intended to use as a helper with the manipulation of an array of fields, ie a group of checkboxes or radio buttons but in my case a list of input fields. The `insert(emails.length, '')` add a new item to the array which interns render a new input field.

So this
![image](https://user-images.githubusercontent.com/15040197/41257540-3357c8fa-6d9b-11e8-848f-8d7215337db0.png)

becomes this when I click the add new field button in my example.
![image](https://user-images.githubusercontent.com/15040197/41257554-4ad78bdc-6d9b-11e8-80a4-9d7db51e9b64.png)

The funny thing is if I add a new field before trying to edit the existing field no error is thrown.

**Comment by harry-sm** [comment]
I thought I closed this.
