### ISSUE TITLE
Changes in tree does not apply to components

### ISSUE THREAD

**Issue by vidyaevoleg** [mobxjs/mobx-state-tree#835]
Something strange happens. I faced with very random bug:

My code:
`class Parent extends Component {`
`  render () {`
  ` const {data} = this.props; // data is MST object`
  ` return <Child data={data} />`
 ` }`
`}`
After changing model data by action - Parent component rerender, but Child component does not.
But when I put `data.toJSON()` or call object field, that was changed (`console.log(data.field)`),  before returning in render fn - changes applied and Child component rendered. 

"mobx": "^4.3.0"
"mobx-react": "^5.1.2"
"mobx-state-tree": "^2.0.5"

Any help, guys!

**Comment by mattruby** [comment]
Your child component should be an observer. If you create a codesandbox.io
example, I can help you.

**Comment by vidyaevoleg** [comment]
@mattruby yep! thank you! It works. But why in some cases it works without `@observer` ?

**Comment by mattruby** [comment]
Because in the cases were it works, the parent component is observing the
data that you'd like the child component to react too.

**Comment by vidyaevoleg** [comment]
@mattruby  I understand! Thank you!!! 👍
