### ISSUE TITLE
mst-example-todomvc fails at runtime

### ISSUE THREAD

**Issue by lookfirst** [mobxjs/mobx-state-tree#836]
![image](https://user-images.githubusercontent.com/85355/40700172-9be4bc5e-6402-11e8-9cf1-19efaf290801.png)

**Comment by mweststrate** [comment]
Works on my PC :-).

If you cloned this repo, you might need to run `yarn run bootstrap` in the root of the clone first.

**Comment by lookfirst** [comment]
I probably haven't run `yarn run bootstrap` yet. Maybe change this issue to be titled: "document the install process".

Also, I noticed a link to this example is missing from the README.

**Comment by mweststrate** [comment]
PR is welcome :-)

Op di 12 jun. 2018 om 03:20 schreef Jon Stevens <notifications@github.com>:

**Comment by mweststrate** [comment]
No, that makes maintenaince hard and detect issues only lately.

Op di 12 jun. 2018 om 13:25 schreef Jon Stevens <notifications@github.com>:

**Comment by lookfirst** [comment]
Isn't that what CI is for?

**Comment by mweststrate** [comment]
exactly, now the examples are part of the CI, and that setup get's a lot
more complicated when this is no longer a mono repo (lerna now links
everything together, avoiding the need to create pre-release artificats etc
etc)

Op di 12 jun. 2018 om 15:43 schreef Jon Stevens <notifications@github.com>:

**Comment by lookfirst** [comment]
The irony here is that it isn't working right now as it is. https://github.com/mobxjs/mobx-state-tree/issues/836#issuecomment-396556251

**Comment by mweststrate** [comment]
Lerna linking caused some issues, removed the examples from the lerna setup, which should fix the issue. Not that `yarn install` needs to be run first now in the example dir
