### ISSUE TITLE
Empty patches on UndoManager

### ISSUE THREAD

**Issue by chemitaxis** [mobxjs/mobx-state-tree#837]
Hi @robinfehr I have detected that sometimes the undoManager is not working fine. I dont' know why, but when you are working with complex patches or many group actions, the patch that comes to addUndoState is empty, and the problem is that I need to call to times to undo().

I have solved the problem and I have the PR ready, please tell me is everything is ok.

Thanks team!

**Comment by chemitaxis** [comment]
Here you have a console.log showing the problem: 

<img width="487" alt="screen shot 2018-05-30 at 20 30 49" src="https://user-images.githubusercontent.com/1420409/40740381-f89891dc-6448-11e8-8c78-a6af800ba995.png">

**Comment by mweststrate** [comment]
Fix released as 2.1.0
