### ISSUE TITLE
Change names: amountOfChildren

### ISSUE THREAD

**Issue by AjaxSolutions** [mobxjs/mobx-state-tree#843]
I don't want to be a smart guy (MST is a great library), but I just wanted to point out a minor grammatical error.

The word "amount" should be used with nouns that cannot be counted, but children, trees or people can be counted.

I suggest changing the word amount to number or count in the following:

"There is no limit to the amount of MST trees ..."
"amountOfChildren"
"amountOfPeopleOlderThan"

**Comment by mattruby** [comment]
@AjaxSolutions please cut a PR with your suggested changes.
