### ISSUE TITLE
Cannot get values from type.map

### ISSUE THREAD

**Issue by mreed** [mobxjs/mobx-state-tree#844]
This probably is a user issue. I am new to mobx and mobx-state-tree but I cannot figure out how to iterate or map the objects in a types.map
I have:
export const Phrase = types.model({
    id : types.identifier(),
    name : types.string
   
})
export const Store = types.model({
    phrases : types.map(Phrase)

within my component i have:

@inject("store")
@observer
export default class PhraseContainer extends React.Component {
    addPhrase(e){
        this.props.store.addPhrase(e.target.value)
    }
    render(){
        let {phrases } = this.props.store
       
       // Object.values(phrases).map(k => console.log(k.id))
        
        return (
        <div>
            <h1>Student Phrases</h1>
            <p> PhraseCount = {this.props.store.phraseCount()} </p>
            <select onChange = {this.addPhrase.bind(this)}>
                <option key="phrase1" value="Course">Course</option>
                <option key="phrase2" value="Ethnicity">Ethnicity</option>
            </select>
            <ul>
                {
                   // this.props.store.phrases &&
                    this.props.store.phrases.values().map(phrase => (
                        <li>{phrase.name}</li>
                   ))
                }
            </ul>
        </div>
    )}
}
 this.props.store.phrases.values().map(phrase => (
                        <li>{phrase.name}</li>
i get:  this.props.store.phrases.values(...).map is not a function
there is an example on egghead.io lesson 6 that uses this exact syntax : group.user.values().map

**Comment by mattruby** [comment]
Please create a codesandbox.io example.

**Comment by luisherranz** [comment]
> i get: this.props.store.phrases.values(...).map is not a function

This changed in Mobx 2. Now `.values()` returns an iterator. You should use `Array.from(this.props.store.phrases.values()).map` or import `values` from mobx (not mobx-state-tree) and use `values(this.props.store.phrases).map`.

**Comment by mreed** [comment]
> This changed in Mobx 2. Now .values() returns an iterator. You should use Array.from(this.props.store.phrases.values()).map or import values from mobx (not mobx-state-tree) and use values(this.props.store.phrases).map.

Thank you. This fixed my issue. Both ways you suggested worked.
