### ISSUE TITLE
Question: why does IdentifierCache use observables?

### ISSUE THREAD

**Issue by k-g-a** [mobxjs/mobx-state-tree#849]
Good day! 
At identifier-cache.ts private cache property is initialized as observable:
```typescript
private cache = observable.map<string, IObservableArray<ObjectNode>>()
```
So there are two questions:
- why is it observable? I could not find any codepath that relies on it;
- why do we use ```map```? As far as key is ```string``` we could use simple ```object``` which is faster and uses less memory.

**Comment by mattiamanzati** [comment]
It is observable mainly because this way any reference will automatically update and throw accordingly if the watched entry disappears :)

**Comment by mweststrate** [comment]
Closing as question seems answered
