### ISSUE TITLE
RFC: do not use @observable at Node

### ISSUE THREAD

**Issue by k-g-a** [mobxjs/mobx-state-tree#854]
Good day!
While implementing [#810](https://github.com/mobxjs/mobx-state-tree/issues/810) I spent some time profiling memory consumption. 
Quite soon I realized that many arrays are allocated by mobx observables used in ObjectNode/ScalarNode. Those are ```parent``` and ```subpath```, thich are in turn used by ```path``` computed. 
I also used ```getAtom(this, 'snapshot').trackAndCompute()``` to effectively invalidate snapshots.
Combining those two points, we can use simple properties for ```parent``` and ```subpath``` and manually invalidate ```path``` at ```setParent()``` and ```finalizeDeath()```.
I've already tried to do so at branch on top of [deferred-observable-creation](https://github.com/k-g-a/mobx-state-tree/tree/deferred-observable-creation).
This does not affect user experience in any way, all tests are passing and results are quite impressive. Creating 10 models in a loop, each having 100 children with 10 grand children (10k ObjectNodes):

1) deferred-observable-creation (prod):
![01-deferred](https://user-images.githubusercontent.com/12710451/41102477-643ab40a-6a80-11e8-89df-331b66d184dd.png)

2) optimize-internal-observables (prod):
![02-no-observables](https://user-images.githubusercontent.com/12710451/41102507-7cd11928-6a80-11e8-854c-0a6a25434ee4.png)

3) speedtest
![03-speedtest](https://user-images.githubusercontent.com/12710451/41102795-1962e2d0-6a81-11e8-9a45-b79c09f0bc34.png)

It shows 3-3.5x creation time improvement over deferred-observable-creation branch. Those two combined show 8-10x improvement over current master.

Changes are purely internal and do not require deferred-observable-creation branch. If this idea is accepted by maintainers, I can backport it to master and make PR.

**Comment by mweststrate** [comment]
For `ScalarNode`, `parent` could become non-observable. I am not entirely sure about subpath, I don't know from the top of my head whether MST moves ScalarNodes in arrays, or generates new ones when splicing. (The answer is in the array reconciler).

For ObjectNode, I am pretty sure stuff will break when making those non-observable, for example if one sets up a reaction that use `getPath(..)` of a certain node, and then that node is moved around using `detach` api.

But I think you already incorporated this background, so I was wondering, what do you mean by "invalidate path at setParent()". Could you link to the relevant change / code? Did you create a simple Atom for that?

Great stuff btw! I scheduled your node initializing PR for MST 3.0, but I do need to go it in much detail still :)

**Comment by k-g-a** [comment]
Good day!
Here's the code at ObjectNode.ts:
```typescript
    subpath: string = ""
    parent: ObjectNode | null = null
    ...
    @computed
    public get path(): string {
        ...
    }
    ...
    private _invalidateComputed(prop: string) {
        const atom = getAtom(this, prop) as any
        atom.trackAndCompute()
    }
   ...
   setParent(...) {
      ...
        } else {
            this.subpath = subpath || ""
            if (newParent && newParent !== this.parent) {
                newParent.root.identifierCache!.mergeCache(this)
                this.parent = newParent
                this.fireHook("afterAttach")
            }
            this._invalidateComputed("path")
        }
   }
   ...
  detach() { 
    ...
    this.parent = null
    this.subpath = ""
    this._invalidateComputed("path")
    this.state = NodeLifeCycle.FINALIZED
  }
  finalizeDeath() {
     ...
     this.state = NodeLifeCycle.DEAD
     this.subpath = ""
     this.parent = null
     this._invalidateComputed("path")
  }
```

The main idea is that ```getAtom(...).trackAndCompute()``` forces recalculation of ```@computed```, which otherwise wouldn't recompute as none of it's dependencies is ```@observable```. 

I made a simple example to check your suggestion about reactions:
```typescript
const ArrayItem = types.model('ArrayItem', {
  id: types.identifier(),
  text: types.string
})

const TwoArraysParent = types.model({
  firstArray: types.array(ArrayItem),
  secondArray: types.array(ArrayItem)
})

const example = TwoArraysParent.create({
  firstArray: [{id: '1', text: 'one'}, {id: '2', text: 'two'}],
  secondArray: [{id: '3', text: 'three'}, {id: '4', text: 'four'}]
})

unprotect(example);

reaction(
  () => example.firstArray.map(i => i),
  arr1 => console.log('firstArray', arr1.map(i => getPath(i))),
  {fireImmediately: true}
)
reaction(
  () => example.secondArray.map(i => i),
  arr2 => console.log('secondArray', arr2.map(i => getPath(i))),
  {fireImmediately: true}
)
console.log('-----------');
const two = detach(example.firstArray[1])
example.secondArray.unshift(two)
```
And the console output was correct:
```typescript
firstArray (2) ["/firstArray/0", "/firstArray/1"]
secondArray (2) ["/secondArray/0", "/secondArray/1"]
-----------
firstArray ["/firstArray/0"]
secondArray (3) ["/secondArray/0", "/secondArray/1", "/secondArray/2"]
```

**Comment by mweststrate** [comment]
@k-g-a closing as the PR is merged and released
