### ISSUE TITLE
How to Make An Array Type?

### ISSUE THREAD

**Issue by chobo2** [mobxjs/mobx-state-tree#856]
Hi

I am having problems with making an array type. I am trying to make a step wizard and I want keep track of the state in Mbox.

```
import { types } from "mobx-state-tree";
import Step from "./Step";
const WizardStore = types
  .model("WizardStore", {
    steps: types.optional(Step, [])
  })
  .actions(self => ({}))
  .views(self => ({}))
  .create();

export default WizardStore;

import { types } from "mobx-state-tree";

const Step = types
  .model("Step", {
     name: "Step 1"
    Component: // this is an actual react component I don't know what type I should be using Object? 
   data would look like <Step 1 />
  })
  .actions(self => ({}))
  .views(self => ({}))
  .create();

export default Step;
```

I get
```

Uncaught Error: [mobx-state-tree] expected a mobx-state-tree type as first argument, got Step@<root> instead
    at fail (mobx-state-tree.module.js:2201)
    at Object.optional$$1 [as optional] (mobx-state-tree.module.js:3898)
    at eval (WizardStore.js:16)
    at Object../src/stores/WizardStore.js (index_bundle.js:5873)
    at __webpack_require__ (index_bundle.js:717)
    at fn (index_bundle.js:99)
    at eval (Stores.js:13)
    at Object../src/stores/Stores.js (index_bundle.js:5861)
    at __webpack_require__ (index_bundle.js:717)
    at fn (index_bundle.js:99)
```

**Comment by chobo2** [comment]
I did find this in the documentation:  todos: types.optional(types.map(Todo), {})

I think this what I need, though I don't see an explanation about it.  My second part is still outstanding though with how to store a component.

**Comment by k-g-a** [comment]
Hi
You can either use ```types.optional(types.map(Todo), {})``` or ```types.optional(types.array(Todo), [])``` depending on how you want to traverse steps: by id or by index.
Considering your second question: you definitely should not store a component inside model. Views are typically built over the data, not visa versa.

**Comment by chobo2** [comment]
@k-g-a 

Hey thanks, I am guessing by map is by id and array is by index.

Do you have an suggestions on how I could hookup MST in this scenario? 

I am trying to make a reusable component called Wizard. When this component is generated it creates a navigation bar like(https://wikiki.github.io/components/steps/). Then when you would click a button next it would go to the next step.

Right now I am passing in an arrary of objects 

```
const steps = [ {id: 'first', name: 'Step 1', component:   <Step1 /> }, 
                    {id: 'second', name: 'Step 2', component:   <Step2 /> }];
```

Now once these go into my Wizard Component, there is another component (WizardSteps) inside that actually generates the navigation bar and code that would figure out which component to render. I would need to modify the "steps object' once it gets into my Wizard  Component as I need to adding some more properties like "IsCompleted" which would tell the WizardSteps component to add another class to change the icon to a checkmark to signify that step is done.

This is why I was trying to store the component into MST.

**Comment by chobo2** [comment]
I got another question on type. In my store I only need 1 "Model" what type is it?

For instance I only see "Todos" in the example but what happens if your making a registration form. Say for a company & employee.

I would have a registrationStore and then 2 other models called Company and Employee.  Now in my Store I can add an array for Employees(as you can create many at one time). But there should only be 1 company object.

```
types
  .model("RegistrationStore", {
    company: types.optional(?????),
    employee: types.optional(types.array(Employee), []) //though I guess this could be in company to make a link between the employees and that company.
  })


```

**Comment by mweststrate** [comment]
@chobo2, you can simply do `company: Company`, or `company: types.optional(Company, 
{})`. See the types section for more details. 

Closing the issue for now as issues should handle only one question, not two different ones :). 

For general questions, a recommend the [spectrum channel](https://spectrum.chat/?t=0d5d753a-4277-4eeb-8190-7f0f84921605), as response will often be quicker there.
