### ISSUE TITLE
error TS4023: Exported variable 'Store' has or is using name 'IMSTNode' ...

### ISSUE THREAD

**Issue by RainerAtSpirit** [mobxjs/mobx-state-tree#86]
I've created a small MST example in https://github.com/RainerAtSpirit/mstStore.

There's one oddity (not sure if it's Typescript behavior or me doing something wrong), which forces me to add several interfaces to make Typescript happy.

https://github.com/RainerAtSpirit/mstStore/blob/master/src/mst/createAppStore.ts#L4
```javascript
import {IObservableArray, action} from 'mobx'
import {IMSTNode} from 'mobx-state-tree/lib/core/mst-node'
import {IModelType} from 'mobx-state-tree/lib/types/complex-types/object'
import {ISnapshottable} from 'mobx-state-tree/lib/types/type'
```
However the interfaces are buried somewhere deeper in mobx-state-tree, so it took some time to find them. Would it be possible to expose all Interfaces via mobx-state-tree like `IObersableArray`?

**Comment by mweststrate** [comment]
Thanks! will investigate. Ideally one doesn't need these interfaces explicitly, and are they just used by the compiler for inference. But for allowing to omit the name it should probably be `type`s instead of `interface`s.

**Comment by mattiamanzati** [comment]
@RainerAtSpirit Does this issue still exists with newer MST versions? :)

**Comment by RainerAtSpirit** [comment]
Yes. Upgraded example to mst 0.7.3 latest typescript/mobx and still see the same behavior.

https://github.com/RainerAtSpirit/mstStore/tree/0.7.3

**Comment by mweststrate** [comment]
0.9.0 explicitly exports the the type `IStateTreeNode` now
