### ISSUE TITLE
Single Model Type?

### ISSUE THREAD

**Issue by chobo2** [mobxjs/mobx-state-tree#860]
Hi 

Say if I have a Company and Employee. I have created a RegistartionStore but I don't know what to put as the type for Company as I only will Register one company at a time.

```
  .model("RegistrationStore", {
    company: types.optional(?????),
  })

  .model("Company", {
    employees: types.optional(types.arrary(Employee), []),
  })

```

**Comment by mattiamanzati** [comment]
var Company = types.model("Company", {
    employees: types.optional(types.arrary(Employee), []),
  }) 

 var RegistrationStore = types.model("RegistrationStore", {
    company: types.optional(Company),
  })

  Just use the defined Company type :)

**Comment by chobo2** [comment]
@mattiamanzati 

Ah so simple :). Though I been thinking about how Stores work. I am now thinking maybe I should have an array of Customers as the registration would be used by a CSR who may in one session register many companies and I am thinking the RegistrationStore would live for the entire life on the users session?
