### ISSUE TITLE
Nested Models (Like a Database almost)?

### ISSUE THREAD

**Issue by chobo2** [mobxjs/mobx-state-tree#861]
Hi

I am reviewing all the tutorials again starting with the [first one](https://github.com/mobxjs/mobx-state-tree/blob/master/docs/getting-started.md#getting-started) and I am a bit confused on what the best way of structuring data is.

I have right now 

ResgistrationStore
CompanyModel
MembershipModel
EmployeeModel

* This would be in a wizard(that you can go back and forth and at the end after submitting you can create a new user..... Wizard steps would be  Company (at this point you choose membership)--- Employee -> submit.)

Now if I would apply the tutorial and how I understand it I should basically do this

```
const RegistrationStore = types
  .model("RegistrationStore", {
    companies: types.optional(types.array(Company), []),
    memberships: types.optional(types.array(Membership), []),
    employees:  types.optional(types.array(Employee), []),
  })
  .actions(self => ({}))
  .views(self => ({}))
  .create({});


const Company = types.model({
    name: types.optional(types.string, ""),
    membership: types.maybe(types.reference(types.late(() => Membership))),
})
  
const Membership = types.model({
    id: types.identifier(types.number),
    name: types.optional(types.string, "")
})

const Employee = types.model({
    id: types.identifier(types.number),
    name: types.optional(types.string, ""),
    company: types.maybe(types.reference(types.late(() => Company))),
})
```
Where I was thinking before reading the tutorial it might look something like this where it is almost like realtional database. 

```
const RegistrationStore = types
  .model("RegistrationStore", {
    companies: types.optional(types.array(Company), []), // should this be a single company and then later on cleared when they hit submit? Or should be an array and find the company through a reference? Only 1 company will be shown at a time as your signing up a company.
    memberships: types.optional(types.array(Membership), []),
  })
  .actions(self => ({}))
  .views(self => ({}))
  .create({});


const Company = types.model({
    name: types.optional(types.string, ""),
    membership: types.maybe(types.reference(types.late(() => Membership))),
    employees:  types.optional(types.array(Employee), []),
})
  
const Membership = types.model({
    id: types.identifier(types.number),
    name: types.optional(types.string, "")
})

const Employee = types.model({
    id: types.identifier(types.number),
    name: types.optional(types.string, ""),
    company: types.maybe(types.reference(types.late(() => Company))),
})

```

**Comment by robinfehr** [comment]
i guess that is not rly a mst question so my advice is to actually model it for your needs. 

if you need employees to be able to work within two or more companies for example you'd put them and the companies onto the RegistrationStore as collections and then and give the exmployee itself an array of references to companies. like that you could also delete the company without deleting the employees...but it really is something that you need to handle yourself according to your use case.

**Comment by chobo2** [comment]
@robinfehr 

Hmm, I am bit surprised by your answer as I thought MST would have a best practice way. I remember in mbox they recommended against making relational structures was bad practice.

**Comment by mweststrate** [comment]
The MST recommendation is: not to think in terms of normalization or
denormalization, but in terms of composition versus association
relationships. Whether that results in normalized data depends on the
semantics of the relations between your data, as Rob indicated :)

Op di 12 jun. 2018 om 18:10 schreef chobo2 <notifications@github.com>:

**Comment by chobo2** [comment]
Ok, I guess I will have to try both ways out and see what makes more sense for my data.
