### ISSUE TITLE
MST flow() causes strange parameter behavior in generators

### ISSUE THREAD

**Issue by harry-sm** [mobxjs/mobx-state-tree#863]
If I have more than one parameter declared in a generator consumed by the flow function, that function now has a requirement of 8 parameters.

![image](https://user-images.githubusercontent.com/15040197/41259149-893df726-6da0-11e8-996b-4c868101b796.png)

**Comment by mweststrate** [comment]
Which TS version are you using?

Op di 12 jun. 2018 om 03:04 schreef Rojay Simpson <notifications@github.com

**Comment by harry-sm** [comment]
I am using TS 2.8.4 in one project and 2.9.1 in another. The issue occurs in both versions.

**Comment by mweststrate** [comment]
And MST 2.1?

Op di 12 jun. 2018 21:58 schreef Rojay Simpson <notifications@github.com>:

**Comment by harry-sm** [comment]
MST 2.0.3

**Comment by harry-sm** [comment]
The issue is still present even after updating to MST 2.1.0 :(

**Comment by harry-sm** [comment]
I deleted my yarn.lock file and did a fresh install and the issue was resolved.
![image](https://user-images.githubusercontent.com/15040197/41443491-30144624-700b-11e8-8341-817b67fcb544.png)
