### ISSUE TITLE
Creating model instance fails: $mobx is undefined

### ISSUE THREAD

**Issue by vuphuctho** [mobxjs/mobx-state-tree#869]
Was following mst's [Getting Started](https://github.com/mobxjs/mobx-state-tree/blob/master/docs/getting-started.md) document, and got stuck at creating the first model instance. 

Dependencies (in `package.json`)
```
"mobx": "^5.0.2",
"mobx-react": "^5.2.3",
"mobx-state-tree": "^2.1.0",
"react": "^16.4.0",
"react-dom": "^16.4.0",
"react-scripts": "1.1.4"
```

Steps to reproduce:
1. Create a new React app with command `create-react-app`
2. Add packages `mobx`, `mobx-react` and `mobx-state-tree` to app.
3. Add following codes to file `src/App.js` and run `npm run start` to run app in localhost
```
...

import { types } from 'mobx-state-tree'

const User = types.model({
    name: ""
})

const user = User.create({
  name: 'John'
})
...
```

Observations: received following error in console:
```
Uncaught TypeError: Cannot read property 'values' of undefined
    at ModelType$$1../node_modules/mobx-state-tree/dist/mobx-state-tree.module.js.ModelType$$1.getChildNode (mobx-state-tree.module.js:3268)
    at mobx-state-tree.module.js:3284
    at mobx-state-tree.module.js:3323
    at Array.forEach (<anonymous>)
    at ModelType$$1../node_modules/mobx-state-tree/dist/mobx-state-tree.module.js.ModelType$$1.forAllProps (mobx-state-tree.module.js:3323)
    at ModelType$$1../node_modules/mobx-state-tree/dist/mobx-state-tree.module.js.ModelType$$1.getSnapshot (mobx-state-tree.module.js:3280)
    at ObjectNode$$1.get (mobx-state-tree.module.js:1025)
    at trackDerivedFunction$$1 (mobx.module.js:1073)
```
After I looked into mst js file and made some loggings, I found out that the property `$mobx` is missing from `storedValue` of the created node.

**Comment by mweststrate** [comment]
MST should be used with MobX 4, not 5

Op wo 13 jun. 2018 om 08:57 schreef Vu Phuc Tho <notifications@github.com>:

**Comment by mweststrate** [comment]
(you should have gotten a warning about this when installing your packages
by npm / yarn; as the peer dependency specifies 4)

Op wo 13 jun. 2018 om 09:04 schreef Michel Weststrate <mweststrate@gmail.com

**Comment by vuphuctho** [comment]
Thanks @mweststrate. It works fine now.
