### ISSUE TITLE
Flow.js support

### ISSUE THREAD

**Issue by Peterabsolon** [mobxjs/mobx-state-tree#870]
After very positive experience using MST with Typescript, I've decided to use it on a Flow.js based project at work. Sadly

```javascript
export type TAppStore = typeof AppStore.Type
```

doesn't work for Flow. Any plans on supporting it?

**Comment by mweststrate** [comment]
No. The type system of MST is very complex, and afaik most parts of it
cannot even be expressed in Flow. Anyhow the burden of keeping them in sync
manually would be pretty big

Op do 14 jun. 2018 om 12:41 schreef Peter Absolon <notifications@github.com
