### ISSUE TITLE
postProcessSnapshot hook does not apply recomputed (returned) snapshot to the model

### ISSUE THREAD

**Issue by fbeaulieu** [mobxjs/mobx-state-tree#871]
Whenever we hook on postProcessSnapshot, this function receives the current model snapshot and it is supposed to return a new object (snapshot) to be eventually applied to the model within the current transaction. OnSnapshot global hook gets called with the new returned snapshot and with the values computed by postProcessSnapshot (as expected). BUT, the new recalculated snapshot is never applied to the model and the values never get changed at all.

**Comment by mweststrate** [comment]
Please provide a reproduction

Op do 14 jun. 2018 20:58 schreef fbeaulieu <notifications@github.com>:

**Comment by benbold** [comment]
import { types } from 'mobx-state-tree';

const SomeModel = types
  .model({
    description: 'Initial'
  })
  .actions(self => ({
    postProcessSnapshot(snapshot) {
      console.log('postProcessSnapshot - initial snapshot', snapshot);

      let newSnapshot = JSON.parse(JSON.stringify(snapshot));
      newSnapshot.description = 'Updated';

      console.log('postProcessSnapshot - updated snapshot', newSnapshot);
      return newSnapshot;
    }
  }))
;

let aModel = SomeModel.create();
console.log(aModel.description); // shouldn't description equal 'Updated' at this point?

**Comment by k-g-a** [comment]
It looks like you're trying to use postProcessSnapshot instead of **pre**ProcessSnapshot. 
Post-processing is responsible for converting model's data back to snapshot.

**Comment by benbold** [comment]
@k-g-a, thanks for your comment.

I was not aware that the postProcessSnapshot lifecycle hook is responsible for converting the model's data back to a snapshot. So we may be misusing this hook then?

Our use case is to have an interceptor which may alter the snapshot being applied to a model instance. Something along the lines of:

 ```
 .actions(self => ({
    postProcessSnapshot(snapshot) { // preProcessSnapshot instead?
      // pseudo code
      return someInterceptor.alterSnapshot(snapshot);
    }
  }))
```
So in this case, would you still suggest the use of preProcessSnapshot?

Thanks again for your input

**Comment by fbeaulieu** [comment]
Thanx @k-g-a , could you please provide some details on the postProcessSnapshot and its effect on the model/properties then ?
