### ISSUE TITLE
Cannot compose more than 3 models. Expected 2-4 arguments, but got 5.

### ISSUE THREAD

**Issue by pravinbashyal** [mobxjs/mobx-state-tree#873]
I want to try following: 

```javascript
export const Shipment = types
  .compose('ModelName', model1, model2, model3, mode4) // Expected 2-4 arguments, but got 5.
```
but it gives `expected 2-4 arguments warning`.

The [source](https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mobx-state-tree/src/types/complex-types/model.ts#L538): 
```javascript
export function compose(...args: any[]): IModelType<any, any> {
    // TODO: just join the base type names if no name is provided
    const typeName: string = typeof args[0] === "string" ? args.shift() : "AnonymousModel"
    // check all parameters
    if (process.env.NODE_ENV !== "production") {
        args.forEach(type => {
            if (!isType(type)) fail("expected a mobx-state-tree type, got " + type + " instead")
        })
    }
    return (args as ModelType<any, any>[])
        .reduce((prev, cur) =>
            prev.cloneAndEnhance({
                name: prev.name + "_" + cur.name,
                properties: cur.properties,
                initializers: cur.initializers
            })
        )
        .named(typeName)
}
```

and [documentation](https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mobx-state-tree/src/types/complex-types/model.ts#L530): 

 - Composes a new model from one or more existing model types.
 - This method can be invoked in two forms:
 - *Given 2 or more model types, the types are composed into a new Type*

does not seem to limit the number of models to compose from. but somehow its limited in [types](https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mobx-state-tree/src/types/complex-types/model.ts#L519): 
```javascript
export declare function compose<T1, S1, T2, S2, T3, S3>(t1: IModelType<T1, S1>, t2: IModelType<T2, S2>, t3?: IModelType<T3, S3>): IModelType<T1 & T2 & T3, S1 & S2 & S3>;
export declare function compose<T1, S1, A1, T2, S2, A2, T3, S3, A3>(name: string, t1: IModelType<T1, S1>, t2: IModelType<T2, S2>, t3?: IModelType<T3, S3>): IModelType<T1 & T2 & T3, S1 & S2 & S3>;
```
I solved it using following: 
```javascript
types.compose(model1, types.compose( model2, types.compose(model3, ...)))
```

But is it how its supposed to be done? isnt horizontal compose better than vertical one?

**Comment by mweststrate** [comment]
Feel free to PR the types and just add a few more variations :)

Op vr 15 jun. 2018 om 10:18 schreef Pravin Bashyal <notifications@github.com

**Comment by t49tran** [comment]
I made a PR for this issue, I think the challenge with this `compose` function type definition is we want to take advantage of Typescript generic type inferencing on one hand, but also want to support multiple arguments.

Basically, the current overload definition can only work with 2 - 4 arguments in order to enable Typescript to infer the output type:

```javascript
export function compose<T1, S1, T2, S2, T3, S3>(
    t1: IModelType<T1, S1>,
    t2: IModelType<T2, S2>,
    t3?: IModelType<T3, S3>
): IModelType<T1 & T2 & T3, S1 & S2 & S3> // ...and so forth...
export function compose<T1, S1, A1, T2, S2, A2, T3, S3, A3>(
    name: string,
    t1: IModelType<T1, S1>,
    t2: IModelType<T2, S2>,
    t3?: IModelType<T3, S3>
): IModelType<T1 & T2 & T3, S1 & S2 & S3>
```

A solution to support an unknown number of arguments is to add additional overload types that cover these case, but then we need to sacrifice the type inferencing and fallback to any for these cases (when more than 4 arguments used).

**Comment by mweststrate** [comment]
PR merged and will be part of MST 3
