### ISSUE TITLE
Question: applySnapshot without snapshot

### ISSUE THREAD

**Issue by benbold** [mobxjs/mobx-state-tree#874]
Hi,

It seems that invoking applySnapshot without providing a snapshot object resorts to using the model instance's current snapshot. Reading the documentation, it is unclear if this is by design or not.

Is this the intent and is this reliable for the future?

**Comment by mweststrate** [comment]
The type signature doesn't not give any hint that the snapshot can be omitted, so if you do the behavior is not defined.

https://github.com/mobxjs/mobx-state-tree/blob/d88a7065a23c8657f4b3b1c040293b2d5f0448e8/packages/mobx-state-tree/src/core/mst-operations.ts#L252
