### ISSUE TITLE
[Question] Best practices on Model definition

### ISSUE THREAD

**Issue by hugues-vincent** [mobxjs/mobx-state-tree#877]
I am wondering where should I define some variables. Let say I want to create a todo list using MST.
` const Todos = types.model({todos: types.array(Todo)})`

Supposing that I want to add a computed variable that gives a filtered list of Todos, depending on the variable `filter`. We get something like 
```
.views(self => ({
    get filteredTodos(){ 
        switch (filter) {
            case "Completed":
                return self.todos.filter(item => item.completed);
            case "Active":
                return self.todos.filter(item => !item.completed);
            default:
                return this.todos;
        }
    }
}))
```
My question is where should I define the `filter` variable, either in `.model({})` or in `.volatile({})`.

Maybe it is even better to implement this logic inside the component, but in that case I wont be able to define a compute variable.
Do you have an idea? 
By the way is there a list of best pratices of this kind somewhere?

Thank you

**Comment by mweststrate** [comment]
All three solutions are valid. 

1. `volatile`, I wouldn't use volatiles, as volatiles are mostly for unserializable stuff that is limited to the lifecycle of the object, like network connectoins or something
2. create a parameterized view (`filteredTodos(filter)`) would work fine, assuming that only that single component needs to know about the current state of the filter
3. prop: I would use that as soon as the currently selected filter is relevant at multiple places

**Comment by mweststrate** [comment]
Closing question as answer has been provided, feel free to re-open
