### ISSUE TITLE
Update egghead tutorial to use mobx@4

### ISSUE THREAD

**Issue by kgwebsites** [mobxjs/mobx-state-tree#878]
Currently the mobx-state-tree egghead tutorial has you install the latest version of mobx which is 5. When you try to run your first test you get a pretty unhelpful error: "Cannot read property 'values' of undefined".

Looking where the error was caused there is a TODO comment of "Blegh". Maybe a more meaningful TODO at the very least?

**Comment by harry-sm** [comment]
Same here

**Comment by matewilk** [comment]
Same here, I've set up the whole app, wanted to start using `mobx-state-tree`, installed all the latest libs, and getting the same error. Tried with the clean app too, even simple model isn't possible to create!

**Comment by harry-sm** [comment]
@matewilk 
I can confirm this setup works

typescript 2.9.2
mobx 4.3.1
mobx-react 5.2.3
mobx-state-tree 2.1.0

**Comment by mweststrate** [comment]
Sorry for the incovenience! The installation instructions mentioned to use Mobx 4 before, but in the mean time MST 2.2 is compatible with both MobX 4 and 5 :)
