### ISSUE TITLE
Nullable parameter absent in MST flow() generators

### ISSUE THREAD

**Issue by harry-sm** [mobxjs/mobx-state-tree#880]
When a parameter is made nullable it is absent from the flow generator param list. 
![image](https://user-images.githubusercontent.com/15040197/41517100-8252b66e-7286-11e8-95a4-225e64716cf7.png)

typescript 2.9.2
mobx 4.3.1
mobx-react 5.2.3
mobx-state-tree 2.1.0

**Comment by mweststrate** [comment]
Is this about `flow` from `mobx` or `mobx-state-tree`? The type hint seems to suggest the first in which case this is reported in the wrong repository

**Comment by harry-sm** [comment]
Ah, your right it's mobx `flow`, must be have been auto-imported with vs code from mobx. The issue is present in MST `flow` too.

![image](https://user-images.githubusercontent.com/15040197/41553789-d31d5782-7300-11e8-84b3-6d39029f4f1a.png)

Should I open this issue over mobx too?

**Comment by harry-sm** [comment]
@mweststrate 
WOW! I have been getting strange issues all over my code, vs code auto-imported flow from mobx and I didn't notice. 

Thanks.
