### ISSUE TITLE
Maps should have consistent behavior for non string keys

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#884]
This issue aggregates several issues around maps. 

Related issues will be linked here and closed

**Comment by mweststrate** [comment]
Proposed solution: only accept strings as keys. What about identifiers? Either
* normalize them to strings
* ..or: only support string keys in the first place

**Comment by mweststrate** [comment]
keep some administration in the map itself whether identifiers used are strings or numbers (can never be both!) so that it knows how to interpret json patches. But, can it be inferred from the types statically...?

**Comment by mweststrate** [comment]
Solution for now: since at many places identifiers and map keys are normalized to strings (for example in snapshots, json patches, internal caches during reconcilation etc), the clearest solution is now to make map keys and identifiers _always_ strings. 

A benefit is that `types.identifier` doesn't need parameterization anymore, and becomes a real primitive

If number identifiers are often used we could introduce a `types.identifierNumber` that behaves the same, but serializes as number in the snapshots

**Comment by mweststrate** [comment]
See #904

**Comment by mweststrate** [comment]
Closing, scheduled

**Comment by kristianmandrup** [comment]
@mweststrate I had an issue with missing key in the Getting started example. Not sure how to best reference or add a todo key for the `map` iterator.

Please have a [quick look](https://github.com/mobxjs/mobx-state-tree/issues/976) thanks!

**Comment by kristianmandrup** [comment]
Not sure how to follow [this suggestion](https://github.com/mobxjs/mobx-state-tree/issues/958#issuecomment-411117345) how/where would I set the key using the same field on `Todo`? Thanks

**Comment by auvipy** [comment]
can this be closed? or need more works?

**Comment by mweststrate** [comment]
I think this has been solved in v3 IIRC (and given the messages above), so I guess this should have been closed already :)

**Comment by auvipy** [comment]
I will be triaging all the open issues over the next couple of weeks since I will be using them in real projects. so having a better understanding of this project is needed for me.

**Comment by mweststrate** [comment]
Perfect, thanks!
