### ISSUE TITLE
Instead of the .Type trick, define a type operator to extract the inferred type

### ISSUE THREAD

**Issue by pelotom** [mobxjs/mobx-state-tree#885]
I have:

* [x] Feature request
   * [x] Describe the feature and why you feel your feature needs to be generically solved inside MST
   * [x] Are you willing to (attempt) a PR?

Suppose we have a model

```ts
const Foo = types.model({ x: number });
```

The `typeof Foo.Type` trick for getting the inferred type of the model isn't ideal because it falsely indicates that you have a value of a certain type when you don't:

```ts
console.log(Foo.Type.x); // type checks, but is an error at runtime
```

In TS 2.8 we can do better using conditional types:

```ts
type TypeOf<T extends IType<any, any>> = T extends IType<any, infer T2> ? T2 : never;
type SnapshotTypeOf<T extends IType<any, any>> = T extends IType<infer S, any> ? S : never;

type Foo = TypeOf<typeof Foo>;
type FooSnapshot = SnapshotTypeOf<typeof Foo>;
```

**Comment by mweststrate** [comment]
Tried and this works perfectly fine. Although this approach is slightly neater, I don't think the benefits are big enough to justify everybody to migrate, so leaving it as is for now unless others have strong opinion about this :)
