### ISSUE TITLE
Make "object has died" a warning instead of error

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#888]
A lot of people are running into this error. It is there because it signals a conceptually mistake, however, in most cases it often does not lead to immediate runtime problems. 

So it might be intersting to make this a warning instead of an error so that people are not immediately forced to fix it. 

Downside is that it might be slightly harder to fix; as you cannot break on the exception.

**Comment by mattiamanzati** [comment]
Maybe a global option? Something like `setBreakOnDie(parent, boolBreakOrWarn)`?

**Comment by aretecode** [comment]
I stopped using mobx-state-tree & went to pure mobx because of this error.

**Comment by mweststrate** [comment]
Introduced the `setLivelynessChecking("warn" | "error" | "ignore")` api in the MST 3 branch.

**Comment by mweststrate** [comment]
Scheduled, closing
