### ISSUE TITLE
Attaching views and actions to complex non-model types

### ISSUE THREAD

**Issue by pelotom** [mobxjs/mobx-state-tree#890]
* [x] Feature request
   * [x] Describe the feature and why you feel your feature needs to be generically solved inside MST
   * [x] Are you willing to (attempt) a PR?

It seems like it should be possible to attach views and actions not only to `IModelType`s, but any `IComplexType`. For example, it would be nice to be able to augment a `types.map`,

```ts
export const MyMap = types.map(types.string)
  .views(self => ({
    get asString() {
      return _.strs
        .sortN(self.keys())
        .pipe(attrKey => `${attrKey}=${self.get(attrKey)}`)
        .join(',');
    }
  })).actions(self => ({
    removeFoos() {
      [...self.keys()].forEach(k => {
        if (k === 'foo')
          self.delete(k)
      })
    }
  }));
```

as it is, one has to "box" the map,

```ts
export const MyMap = types
  .model({
    fields: types.map(types.string),
  })
  .views(self => ({
    get asString() {
      return _.strs
        .sortN(self.fields.keys())
        .pipe(attrKey => `${attrKey}=${self.fields.get(attrKey)}`)
        .join(',');
    },
  }))
  .actions(self => ({
    removeFoos() {
      [...self.fields.keys()].forEach(k => {
        if (k === 'foo') self.fields.delete(k);
      });
    },
  }));
```

and then clients have to be aware of the extra level of indirection, accessing the traditional map methods through e.g. `x.fields.add(...)` instead of `x.add(...)`.

**Comment by mattiamanzati** [comment]
@pelotom Please check out #893 and give feedback about it :)

**Comment by xaviergonz** [comment]
Duplicate of #893
