### ISSUE TITLE
Information hiding

### ISSUE THREAD

**Issue by pelotom** [mobxjs/mobx-state-tree#891]
* [x] Feature request
   * [x] Describe the feature and why you feel your feature needs to be generically solved inside MST
   * [x] Are you willing to (attempt) a PR?

It would be cool to be able to hide information on a model, making certain props, views and actions "private". I could imagine an `exposing` method which requires specifying all things  that you want to reveal to the outside world:

```ts
const M = types
  .model({
    x: types.number,
    y: types.boolean,
    z: types.number,
  })
  .views(self => ({
    get computed1() {
      return self.y ? self.x : self.z;
    },
    get computed2() {
      return self.y && self.x > self.z;
    },
  }))
  .actions(self => ({
    doSomething1() {
      self.z = 42;
    },
    doSomething2() {
      self.x = 3;
      self.y = true;
    },
  }))
  .exposing('x', 'y', 'computed2', 'doSomething1');
```

The resulting static type of the model would then be

```ts
{
  x: number;
  y: number;
  computed2: boolean;
  doSomething1(): void;
}
```

and accessing private members at runtime would throw an exception. Views and actions declared prior to the `.exposing(...)` are of course able to access private members.

**Comment by mweststrate** [comment]
You can use `extend`, as shown in the second example here: https://github.com/mobxjs/mobx-state-tree#volatile-state

**Comment by mattiamanzati** [comment]
@pelotom I would do the opposite TBH, I would implement an "hide" that works just at typescript level to hide specific methods :)

**Comment by pelotom** [comment]
@mattiamanzati why not have both? :)

**Comment by mweststrate** [comment]
Closed for now, I don't think huge api overhauls don't serve the project at the current stage. Forking is always fine of course :)
