### ISSUE TITLE
Clear/Reset history in UndoManager 

### ISSUE THREAD

**Issue by abruzzihraig** [mobxjs/mobx-state-tree#897]
I have:
* [x] Feature request
   * [x] Describe the feature and why you feel your feature needs to be generically solved inside MST
   * [x] Are you willing to (attempt) a PR?
   
Is it possible to have a 'clear' method to clear histories and reset undoIdx in undo manager?

Imagine the situation when users made some operations that recorded to undoManager's history, and at the same time, users want to apply a snapshot from a server(might be JSON) to reset everything to that snapshot. In that case, I think there should be a method reset/clear in undoManager so that developers can decide what time the history could be cleared.

If it makes sense, I'm willing to send a PR.

**Comment by mweststrate** [comment]
@robinfehr ?

**Comment by zhangtao07** [comment]
you can try add an action to reset the history data.  

``
resetHistory() {
     self.history.history = [];
     self.history.undoIdx = 0;
}
``

**Comment by xaviergonz** [comment]
@abruzzihraig are you still willing to make a PR or is the solution provided good enough?

**Comment by abruzzihraig** [comment]
@xaviergonz sorry for late to reply. Yes, I am still willing to make a PR for solving this limitation.

The solution that @zhangtao07 recommended doesn't make sense. UndoManager is an individual module, it is not a part of the store where it attaches. The property `history` is in UndoManager so you cannot just simply call it by `self.history` out of its context. That function `resetHistory` must be a part of UndoManager then it can work. That's why I think we have to change the code.

**Comment by xaviergonz** [comment]
Closing, implemented in https://github.com/mobxjs/mobx-state-tree/pull/1108
