### ISSUE TITLE
Binding to floating point numbers

### ISSUE THREAD

**Issue by tomitrescak** [mobxjs/mobx-state-tree#898]
I have:

* [x] A conceptual question. 
  * [x] I've checked documentation and searched for existing issues
  * [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3) first

Hi, I have a silly question. I'm binding input to MST value. Yet, when I try to write floating point numbers it errors out on ".". How do I create a controlled input, bound to MST field so that I can write "444.66" ?

**Comment by tomitrescak** [comment]
Nevermind, it cannot be done easily. I had to bind to string values and then on successful validation the value is converted to float.

**Comment by elliotlarson** [comment]
I encountered this problem while walking through the MST EggHead course.  To add onto what @tomitrescak is saying, here's the code I ended up using to get this working (in case it helps someone else:

```javascript
import React, { useState } from "react";
import { observer } from "mobx-react";

function WishListItemEdit({ item }) {
  const [priceString, setPriceString] = useState(item.price);

  const onNameChange = (event) => {
    item.changeName(event.target.value);
  };

  const onPriceChange = (event) => {
    setPriceString(event.target.value);
    const price = Number.parseFloat(event.target.value);
    if (!isNaN(price)) item.changePrice(price);
  };

  const onImageChange = (event) => {
    item.changeImage(event.target.value);
  };

  const { name, image } = item;

  return (
    <div className="item-edit">
      <div className="form-row">
        <label>Thing:</label>
        <input value={name} onChange={onNameChange} />
      </div>
      <div className="form-row">
        <label>Price:</label>
        <input value={priceString} onChange={onPriceChange} />
      </div>
      <div className="form-row">
        <label>Image:</label>
        <input value={image} onChange={onImageChange} />
      </div>
    </div>
  );
}

export default observer(WishListItemEdit);
```
