### ISSUE TITLE
server side generated types.identifier()

### ISSUE THREAD

**Issue by RainerAtSpirit** [mobxjs/mobx-state-tree#90]
What would be the recommended way to deal with server side generated `identifier`?

Within the box example I see that a random Identifier must be added otherwise the type system will throw.
```
export const Box = types.model("Box", {
    id: types.identifier(),
....

addBox(name, x, y) {
        const box = Box.create({ name, x, y, id: randomUuid() })
```

However when using an Odata endpoint to persist a new box it would expect a POST request without the `id` property and in the response we get the server side generated `id` back.

I can envision several ways to address this, but wanted to ask for some best practices before moving on.

**Comment by mattiamanzati** [comment]
Once #100 will be in, you will be able to provide a random internal ID and omit it from snapshot by postprocessing the snapshot :)

**Comment by mweststrate** [comment]
Note that the goal of identifiers is primarily to be able to reconcile objects, and look up references. Especially the first introduces the requirement for them to be defined upfront. If the `id` property is not used for these purposes, a `types.refinement(types.string, validateFunc)`  is probably better suited to verify id's are properly formatted etc.

**Comment by RainerAtSpirit** [comment]
Excellent. Thanks for the clarification.
