### ISSUE TITLE
node of `types.reference` doesn't see itself as part of the branch where it is attached

### ISSUE THREAD

**Issue by jayarjo** [mobxjs/mobx-state-tree#900]
Node of `types.reference` doesn't see itself as part of the branch where it is attached, but instead assumes itself to be part of  the branch where original node is attached (which it is referencing).

Not what one would expect I think.

Simple sandbox: https://codesandbox.io/s/k2pz501vo7

**Comment by mweststrate** [comment]
@jayarjo I don't see how this behavior is unexpected? References are like symlinks, if you follow them, and ask do `pwd`, you will always end up in the original location of the thing. That is why it is called a _reference_

**Comment by jayarjo** [comment]
Actually if you symlink a folder and then enter it, `pwd` will show you the path to the symlink, not the path to the folder that was referenced. Unless you specifically tell it to show _real path_ with: `pwd -P`.

**Comment by mweststrate** [comment]
Interesting! Never noticed that. 

Anyway, MST doesn't keep track on _how_ you navigated to an object, so the reported location is where the thing actually lives, not from where it is referred (which might be many places), so this is working according to spec :)

**Comment by jayarjo** [comment]
This becomes a problem if referred complex object relies on its position in the tree (requesting some values from its immediate parents, which obviously might differ for the reference).

**Comment by Mosho1** [comment]
I don't see how this can be done. if you use `getParent` on the object and it has multiple reference including it's actual position in the tree, what would be returned?

**Comment by jayarjo** [comment]
No no, that's not the scenario. If you use `getParent` on an actual object it should return it's actual parent. The question is what should be returned when you use `getParent` on its `types.reference`.

**Comment by mweststrate** [comment]
how would you invoke the getParent on a types.reference? The 'actual'
reference is nowhere accessible in the tree as first class citizen (a ref
like store.selectedUser gives a real user object back, exactly the same
instance of the user it refers to in store.users (for example))

Op vr 13 jul. 2018 om 14:29 schreef Davit Barbakadze <
notifications@github.com>:
