### ISSUE TITLE
[Question] How to store react ref in MST ?

### ISSUE THREAD

**Issue by designalchemy** [mobxjs/mobx-state-tree#903]
Hello 

i want to store a react ref in MST, not sure what type to use or if this is even a good idea

i want to use the formRef on another action 

```
<form ref={ref => store.storeRef(ref)} />

.model('x', {
  formRef: type ? 
})
.action(self => ({
  storeRef(ref) {
    formRef = ref
  }
}))

```
Is this possible ? am i going around this wrong ?

Thanks

**Comment by k-g-a** [comment]
Storing ref in model looks like bad idea, but you can check [volatile state documentation](https://github.com/mobxjs/mobx-state-tree#volatile-state).

**Comment by mattiamanzati** [comment]
Please check out volatile state :)

https://github.com/mobxjs/mobx-state-tree#volatile-state

**Comment by designalchemy** [comment]
@k-g-a 

What would be a better way of interacting with a ref ? 

but will check volatile out,  

Thanks

**Comment by designalchemy** [comment]
@mattiamanzati 

im using Atlassian UI kit, the <Form> has a formRef.validate() which allows me to validate the fields on the page, would you suggest making this a traditional react class, rather than trying to use a stateless component with a MST store attached ?
