### ISSUE TITLE
Introduce `types.integer`

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#905]
Could be easily added to `primitives.ts` and nicely leverages the fact that MST can actually do runtime type checking

**Comment by jayarjo** [comment]
I was looking for the relatively easy angle to enter MST internals. Can I PR this one perhaps?

**Comment by mweststrate** [comment]
Sure!

Op vr 13 jul. 2018 om 10:57 schreef Davit Barbakadze <
notifications@github.com>:

**Comment by jayarjo** [comment]
Perhaps consider that PR as a draft. There are some arguable points, like the polyfill for `Number.isInteger` for example or placement and the value of `TypeFlags.Integer`. Also not sure whether integer number should actually be considered `types.integer` by default.

**Comment by jayarjo** [comment]
Will close, since it is merged now.
