### ISSUE TITLE
Make array and map types optional by default

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#906]

**Comment by mweststrate** [comment]
array and map types will be optional by default when used _directly_ as model properties. 

Tried making child objects optional as well, but this became very confusing in combination with `maybe` and such (since `undefined` would then be an acceptable value, leaving a field in a snapshot would be inferred to `{}` instead of `null`, etc..

**Comment by mweststrate** [comment]
Scheduled for 3.0, closing

**Comment by jlgrall** [comment]
How to make them mandatory when I need it ?

Seems to me the only way would be adding a `refinement()` over the current implicit `optional()` wrapping:
```javascript
var MyList = types.model({
	list: types.refinement(types.array, v => v !== undefined);
});
```

Would this refined type still return `true` with a call to `isOptionalType(value)` ?
