### ISSUE TITLE
Are changes to a model inside an action "transactioned"?

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx-state-tree#909]
I have:

* [x] A conceptual question. 
  * [x] I've checked documentation and searched for existing issues
  * [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3) first
* [ ] I think something is not working as it should.
  * [ ] I've checked documentation and searched for existing issues
  * [ ] I've made sure your project is based on the latest MST version
  * [ ] Fork [this](https://codesandbox.io/s/jlnmjqr7xv) code sandbox or another minimal reproduction. 
  * [ ] Describe expected behavior
  * [ ] Describe observed behavior
* [ ] Feature request
   * [ ] Describe the feature and why you feel your feature needs to be generically solved inside MST
   * [ ] Are you willing to (attempt) a PR?
   
_Not following the above template might result in your issue being closed without further notice_

Say that:
- I have a model with an array of 100 numbers.
- An action that basically (for example) just increases all numbers in the array by 1
- A view based on this array that is being observed by a react component (or whatever)

If I run this action, will the computed value trigger its "I have changed!" reaction to the observer 100 times or just once?

**Comment by mweststrate** [comment]
Once

Op do 5 jul. 2018 21:37 schreef Javier Gonzalez <notifications@github.com>:

**Comment by xaviergonz** [comment]
Thanks!
