### ISSUE TITLE
[mobx] invalid option for (extend)observable: proxy

### ISSUE THREAD

**Issue by sanatshah** [mobxjs/mobx-state-tree#910]
Hello, 

I am trying to run the simple example, 

```
import { types } from "mobx-state-tree"

// declaring the shape of a node with the type `Todo`
 const Todo = types.model({
     title: types.string
 })
 
 // creating a tree based on the "Todo" type, with initial data:
 const coffeeTodo = Todo.create({
     title: "Get coffee"
 })
```

But I am getting the error: 

`Uncaught Error: [mobx] invalid option for (extend)observable: proxy
    at invariant (mobx.module.js:2681)
    at fail$1 (mobx.module.js:2676)
    at assertValidOption (mobx.module.js:1483)
    at Array.forEach (<anonymous>)
    at asCreateObservableOptions (mobx.module.js:1493)
    at Function.object (mobx.module.js:1569)
    at ModelType$$1._this.createNewInstance (mobx-state-tree.module.js:3092)
    at createNode$$1 (mobx-state-tree.module.js:2050)
    at ModelType$$1.instantiate (mobx-state-tree.module.js:3281)
    at ModelType$$1.ComplexType$$1.create (mobx-state-tree.module.js:1346)`

I am on mobx version 4.1.1 and mobx-state-tree version 2.2.0. I attempted to debug through the source to get more of an idea of what was going on and it seems that the variable, 

```
mobxShallow = {
    deep: false, 
    proxy : false
}

```
is being passed to asCreateObservableOptions and is causing it to fail in assertValidOption.

```
function assertValidOption(key) {
    if (!/^(deep|name|defaultDecorator)$/.test(key))
        fail$1("invalid option for (extend)observable: " + key);
}
function asCreateObservableOptions(thing) {
    if (thing === null || thing === undefined)
        return defaultCreateObservableOptions;
    if (typeof thing === "string")
        return { name: thing, deep: true };
    if (true) {
        if (typeof thing !== "object")
            return fail$1("expected options object");
        Object.keys(thing).forEach(assertValidOption);
    }
    return thing;
}

```
Any help is appreciated, thanks.

**Comment by mweststrate** [comment]
Which mst / mobx version?

Op vr 6 jul. 2018 03:30 schreef Sanat Shah <notifications@github.com>:

**Comment by mweststrate** [comment]
Upgrading mobx to 4.3.1 should solve the issue, as specified in the peer dependencies of MST.
