### ISSUE TITLE
Dynamic keyed object maps via mobx 5 proxies supported?

### ISSUE THREAD

**Issue by steve8708** [mobxjs/mobx-state-tree#914]
I have:

* [x] A conceptual question. 
  * [x] I've checked documentation and searched for existing issues
  * [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3) first
* [ ] I think something is not working as it should.
  * [ ] I've checked documentation and searched for existing issues
  * [ ] I've made sure your project is based on the latest MST version
  * [ ] Fork [this](https://codesandbox.io/s/jlnmjqr7xv) code sandbox or another minimal reproduction. 
  * [ ] Describe expected behavior
  * [ ] Describe observed behavior
* [ ] Feature request
   * [ ] Describe the feature and why you feel your feature needs to be generically solved inside MST
   * [ ] Are you willing to (attempt) a PR?
   
Love this project, and really thrilled about Mobx5 being released with support for dynamic keyed objects via proxies.

Is this supported in MST yet? Or is there any plan to? I've looked through the docs and issues and see no mention of this, so wanted to pose the question as it's something I'd really be interested in using

I could see it possibly being an option in `types.map` or a new `types.proxyMap` or whatnot?

Thanks!

**Comment by Bnaya** [comment]
MST requires you to pre-declare the shape of the object,
Not sure if dynamic keyed objects makes sense

**Comment by steve8708** [comment]
Totally see your point @Bnaya, but MST does have `types.map` that allow dynamic key/value pairs using getters and setters, and a big appeal to me of allowing proxied key/value maps is the major consistency and interoperability benefits that comes with it

E.g. before in mobx 4 or MST, if you want to operate on data with libraries like lodash, or really any of your existing internal code that is built to work with plain arrays and objects, you'd have to convert them to json or js, do your operations, and map your results back, which isn't always the most elegant or efficient.

That, or you can make all separate functions for operating on mobx types separate from standard js object/array types, which can be tedious and create duplicate code and potential for more bugs

I think a big benefit of the proxying abilities of mobx 5 is being able to use all the same code on mobx types as you do any other plan JS types in your apps. 

I think this consistency and library compatibilty has a lot of benefits, especially for developers new to mobx.

**Comment by Bnaya** [comment]
types.map is more like js `Map`, with `get` and `set` methods and not plain objects, it's not getters and setters, but regular functions.

You want MST store that will behave like plain object? but what would be the keys types and what the possible properties values?

**Comment by mweststrate** [comment]
The only feasible way is to declare it the same way as current maps, but use proxy objects as storage structure (so that the key / values have a consistent structure).

Won't add this on the short term for now, as it would require a hard dependency on MobX 5, and hence a fork of the project, which would be too much of a maintenance burden. 

Once proxies are acceptable for all consumers we could support this :)
