### ISSUE TITLE
The behaviour of getPath has changed since 2.2.0

### ISSUE THREAD

**Issue by abruzzihraig** [mobxjs/mobx-state-tree#917]
I have:

* [x] I think something is not working as it should.
  * [x] I've checked documentation and searched for existing issues
  * [x] I've made sure your project is based on the latest MST version
  * [x] Fork [this](https://codesandbox.io/s/jlnmjqr7xv) code sandbox or another minimal reproduction. 
  * [x] Describe expected behavior
  * [x] Describe observed behavior

I would think this is a bug specifically in version 2.2.0.
   
**Expected behavior:**
The method `getPath` for a child instance should return a full path from itself to its root. Everything is fine before 2.2.0. The following code sandbox uses MST v2.1.0 and it works fine.
https://codesandbox.io/s/kwll5wryov

**Observed behavior:**
The method `getPath` for a child instance only returns a relative path based on where it does initialize.
The following code sandbox shows the issue in logs. It only changed the dependency MST to v2.2.0
https://codesandbox.io/s/4r6pol3m64

e.g. If we initialize an instance tree like below:
```
const store = TodoStore.create({
  todos: [
    Todo.create({
      title: "get Coffee",
      subTodos: [
        SubTodo.create({
          title: "test"
        })
      ]
    })
  ]
});

console.info(store.todos[0].path);
console.info(store.todos[0].subTodos[0].path);
```
The expected logs should be like below:
```
/todos/0 
/todos/0/subTodos/0
```
rather than the observed:
```
/todos/0 
/subTodos/0
```

**Comment by mweststrate** [comment]
This is probably a bug, will investigate

Note that unrelated to that, there is no need to create the children like you do above, all the `.create` calls except for the outer one are superfluos and will cause the children to be created before their parents (as that is the normal JS evaluation order)

**Comment by mweststrate** [comment]
Added the testcase to the MST 3 branch, it is fixed in there, so closing the issue for now. Thanks for reproducing!

Should release early next week
