### ISSUE TITLE
What TS type should i declare for a param in indexOf if the array is array of Mobx State Tree type?

### ISSUE THREAD

**Issue by exztinct01** [mobxjs/mobx-state-tree#918]
I have the ff:

    const Rule = types
     .model("Rule", {
       id: types.number,
       name: types.string,
       long1: RuleMovingAverageModel,
       long2: RuleMovingAverageModel,
       long3: RuleMovingAverageModel,
       long4: RuleMovingAverageModel,
       condition1: RuleCondition1Model,
       condition2: RuleCondition2Model,
       condition3: RuleVolatilityModel,
       condition4: RuleCondition4Model,
       condition5: RuleDayCountModel,
       stop1: RuleMovingAverageModel,
       stop2: RuleMovingAverageModel,
       stop3: RuleMovingAverageModel,
       volatilitystop: RuleVolatilityModel,
       timestop: RuleDayCountModel,
       varstop: RuleVaRStopModel,
       absolutestop: RuleAbsoluteStopModel,
       spread: RuleSpreadModel
    })
    .actions((self) => ({
       setname(name: string) {
       self.name = name;
    }
  }));

The model types above are all IModelType's (e.g. RuleMovingAverageModel, ... ). 
Then a RulesStore

    const Rules = types.model({
        rules: types.array(Rule),
    })
    .actions(self => ({
        removeRule(id: number) {
            const index = self.rules.indexOf(rule => rule.id === id);
            if (index !== -1) {
              self.rules.splice(index, 1);
            }
        }

What should be the type of the `rule` inside `indexOf` to prevent typescript errors?
The above does not work because `rule` is of type `any` and cannot be assigned to `'{id: number, name: string, ...'`
When I use the type `typeof Rule.Type`, another error occurs

        removeRule(id: number) {
            const index = self.rules.indexOf((rule: typeof Rule.Type) => rule.id === id);
            if (index !== -1) {
              self.rules.splice(index, 1);
            }
        }

    `Argument of type '(rule: {id: number, ...' is not assignable to parameter of type `{id: number, ...`

**Comment by mweststrate** [comment]
Please add more context, I don't see `typeof` in the above issue at all?

**Comment by exztinct01** [comment]
I edited the first post above
