### ISSUE TITLE
optional types are no longer typed as optional in 3.0.0

### ISSUE THREAD

**Issue by Mosho1** [mobxjs/mobx-state-tree#924]
* [x] I think something is not working as it should.
  * [x] I've checked documentation and searched for existing issues
  * [x] I've made sure your project is based on the latest MST version
  * [ ] Fork [this](https://codesandbox.io/s/jlnmjqr7xv) code sandbox or another minimal reproduction. 
  * [x] Describe expected behavior
  * [x] Describe observed behavior
   
I'm not sure why, but codesandbox stopped showing me errors. The example is simple though:

```typescript
import { types } from 'mobx-state-tree';

export const Foo = types.model('Foo', {
    optional: types.optional(types.string, '') // or just ''
});

const foo: typeof Foo.SnapshotType = {};
```
Expected behavior - no errors.
Observed behavior - The last line shows the error: `Property 'optional' is missing in type '{}'`.

**Comment by xaviergonz** [comment]
You may want to check the new Foo.CreationType
CreationType is the "snapshot" type that can be used to create a type, SnapshotType is now the output of getSnapshot, and Type is still the instance (node) type
