### ISSUE TITLE
API.md needs more examples

### ISSUE THREAD

**Issue by marcofugaro** [mobxjs/mobx-state-tree#925]
Hey! I love MST, really fun to use. My only issue with it is the API.md docs. 

The main documentation is well written and very elaborate, but 80% of the times I come here I end up on the API.md document. It happened multiple times that the method I was looking for had only a brief descripton and its arguments, and a lot of time that wasn't enough. For example I struggle to know what are the types you can pass to the `hasParentOfType` function, it would have been easier with an example.

I think a good heuristic is that every function should be documented with an example, even if it sounds really straight-forward.

Sorry if I can't really do a PR right now! 

(Also does `resolve(node, path)` still work? I noticed it's in the `README.md` but not in the `API.md`)

* [x] Feature request
   * [x] Describe the feature and why you feel your feature needs to be generically solved inside MST
   * [ ] Are you willing to (attempt) a PR?

**Comment by coolsoftwaretyler** [comment]
Hey @marcofugaro - this is an old issue over here in MobX-State-Tree. I'm gonna go ahead and close it since no one has taken action on it or assigned to themselves.

If you or anyone else sees this comment, we're always happy to accept PRs to improve our documentation.

Thanks for your time!
