### ISSUE TITLE
getSnapshot() doesn't traverse all nodes in the tree

### ISSUE THREAD

**Issue by bourquep** [mobxjs/mobx-state-tree#926]
I have:

* [ ] A conceptual question. 
  * [ ] I've checked documentation and searched for existing issues
  * [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3) first
* [x] I think something is not working as it should.
  * [x] I've checked documentation and searched for existing issues
  * [x] I've made sure your project is based on the latest MST version
  * [x] Fork [this](https://codesandbox.io/s/jlnmjqr7xv) code sandbox or another minimal reproduction. 
  * [x] Describe expected behavior
  * [x] Describe observed behavior
* [ ] Feature request
   * [ ] Describe the feature and why you feel your feature needs to be generically solved inside MST
   * [ ] Are you willing to (attempt) a PR?
   
_Not following the above template might result in your issue being closed without further notice_

---

It seems like `getSnapshot()` is broken in v3.0.0. 

Running this repro code:

```javascript
const { types, getSnapshot } = require("mobx-state-tree");

const Nested = types.model("Nested", {
    foo: "bar",
    name: "",
}).postProcessSnapshot(snapshot => ({ ...snapshot, "fooz": "barz" }));

const Root = types.model("Root", {
    foo: "bar",
    name: "",
    nested: types.array(Nested)
});

const nested = Nested.create({});
const root = Root.create({nested: [nested]});

console.log("Snapshot of nested node includes 'fooz' attribute added in post-process:");
const nestedSnap = getSnapshot(nested);
console.dir(nestedSnap);

console.log();

console.log("But snapshot of root node does not include post-processed attribute:");
const rootSnap = getSnapshot(root);
console.dir(rootSnap.nested[0]);
```

Yields this output:

```
Snapshot of nested node includes 'fooz' attribute added in post-process:
{ foo: 'bar', name: '', fooz: 'barz' }

But snapshot of root node does not include post-processed attribute:
{ foo: [Getter/Setter], name: [Getter/Setter] }
```

Running the same code against MST v2.2.0 (after moving `postProcessSnapshot()` to an action) yields this output:

```
Snapshot of nested node includes 'fooz' attribute added in post-process:
{ foo: 'bar', name: '', fooz: 'barz' }

But snapshot of root node does not include post-processed attribute:
{ foo: 'bar', name: '', fooz: 'barz' }
```

As you can see, calling `getSnapshot()` on a root node does not process the nested node's snapshot.

**Comment by bourquep** [comment]
Here's a test suite that reproduce the problem:

```typescript
import { types, getSnapshot } from "../src"

const Nested = types
    .model("Nested", {
        fooz: "",
        name: ""
    })
    .postProcessSnapshot(snapshot => ({ ...snapshot, fooz: "barz" }))

const Root = types.model("Root", {
    nested: types.array(Nested)
})

const nested = Nested.create()
const root = Root.create({ nested: [nested] })

const rootWithSnapshot = Root.create({
    nested: [
        {
            fooz: "",
            name: ""
        }
    ]
})

test("it should include nested snapshot when root created with snapshot", () => {
    expect(getSnapshot(rootWithSnapshot)).toEqual({
        nested: [
            {
                fooz: "barz",
                name: ""
            }
        ]
    })
})

test("it should include nested snapshot when root created with model", () => {
    expect(getSnapshot(root)).toEqual({
        nested: [
            {
                fooz: "barz",
                name: ""
            }
        ]
    })
})

test("it properly snapshots nested model", () => {
    expect(getSnapshot(root.nested[0])).toEqual({ fooz: "barz", name: "" })
    expect(getSnapshot(rootWithSnapshot.nested[0])).toEqual({
        fooz: "barz",
        name: ""
    })
})
```

**Comment by xaviergonz** [comment]
The problem seems to be about the array not applying the children post processors.
A single object seems fine

**Comment by mweststrate** [comment]
@k-g-a ideas? Maybe we should start instantiating stuff even when just requesting the snapshot? (Or kill snapshot processors)

**Comment by mweststrate** [comment]
I'm not entirely sure this is a bug, even though the processors are indeed not run, postProcess should be the covariant of PreProcess. If your app *requires* your post processes to have run, it means that you are basically relying on side effects of the instantiation of your tree. I don't know where this post processing is needed for, but if it does not have a preProcessor counterpart it sounds that you should be using a view instead.

**Comment by bourquep** [comment]
I actually do have both pre and post processors. I may have oversimplified the test case a bit.

**Comment by mweststrate** [comment]
Let me put it differently to understand the problem better: why is it a
problem that your postProcessor is not applied, if your preProcessor isn't
applied to the snapshot either? What assumptions are made down the line
about the snapshots that are broken now?

Op do 26 jul. 2018 om 15:21 schreef Pascal Bourque <notifications@github.com

**Comment by bourquep** [comment]
The assumption that whenever I call `getSnapshot()` on a node, it will give me a properly formatted snapshot that includes any post-processing that I need to do.

**Comment by mweststrate** [comment]
Yes I get that, but it doesn't answer the "why" questions ;-). What post-process assumptions are you making? Why would `a view like `get myCoolJSONFormattedData() { ... }` not be an option? etc.

**Comment by bourquep** [comment]
I'm not sure I understand... I use getSnapshot to persist the state of my app, and expect to be able to pass that snapshot to `Model.create()` to load it back up. Right now, because of this issue, it doesn't work in MST3.

**Comment by mweststrate** [comment]
Ah, but if it doesn't boot up that means your preProcessor and
postProcessor are not each others counterpart? Or that it matters for the
preProcessor whether postProcessing is applied or not. What if you made it
work for both cases? Could you share the offending preProcessor and
postProcessor combination?

Op do 26 jul. 2018 om 15:54 schreef Pascal Bourque <notifications@github.com

**Comment by mweststrate** [comment]
I understand the example and see what is potentially wrong with it.

But I am trying to understand how this feature is used in real life & what
kind of assumptions are build on top of it. So beyond the foo/bar/baz
level. Is your real life case also introducing new attributes in
postProcess, which are not available in the original snapshot? Are they
adding information or where they just optional fields that have a default?
Or are they coming from volatile state? What do these additional attributes
represent?

Op do 26 jul. 2018 om 16:28 schreef Pascal Bourque <notifications@github.com

**Comment by mweststrate** [comment]
@k-g-a could there be a discrepancy here? While storing the snapshots for lazy node initialization, the preprocessed snapshot should be stored instead of the raw one, (and the entire tree should be traversed to do so)?

**Comment by xaviergonz** [comment]
In my case my use case for pre process snapshot is versioning. for example if the snapshot is version 1 then I convert it to the latest version before feeding it into MST create.

This versioning has to be applied to each node independently since each node has its own versioning handling. 

if this is not fixed (at least for pre processors) then it won't work for nodes inside arrays/maps

**Comment by mweststrate** [comment]
Could those cases easily be solved outside MST? As in, fix the snapshots before passing them into `.create` / back from the server?

**Comment by bourquep** [comment]
> Could those cases easily be solved outside MST

I suppose, yes.

**Comment by k-g-a** [comment]
Hi guys! 
Unfortunately, I’m on vacation until 6th of August and the most smart device with me is iPad :)
Nevertheless, I still can’t understand the issue. PreProcessSnaphot is called only on model creation, meaning it is fully initialized, which in turn, means getSnapshot return actual (post-processed) snapshot. We do not deeply pre-process snapshots, so how come we must deeply post-process them? Relying on such inconsistent behaviour feels like gateway to errors.
Of course, as a quick fix we can recuresevly call “initializeObservableInstance” from getSnapshot (not within get snapshot itself, as i’d kill all the optimizations).

**Comment by k-g-a** [comment]
Peeked into a code.
At ObjectNode._getInitialSnapshot we could do something like:
```
const snapshot = {}
Object.keys(this._childNodes).forEach(k => snapshot[k] = this._childNodes[k].snapshot)
return ... //same as it is
```
This way we’ll get depth-first post-process, same as for fully-initialized tree.

BTW, it seems like we could keep _childNodes after _createObservableInstance() happened (we nullify them ATM) and use those for getCildNode/getChildren always instead of non-obvious _autoUnbox hack?

**Comment by bourquep** [comment]
Ok, I got rid of our snapshot pre/post processing requirements. So this issue is no longer a concern to me, but I believe it's worth keeping the discussion going.

**Comment by xaviergonz** [comment]
In my case I basically use it like this:
- basically every model has a _version property with an integer
- if the preprocess snapshot detects that the version of the node is not the latest one then it will make a conversion to adapt it to the latest one
- when a file is loaded I expect every node to use this mechanism to auto "update" itself

right now that breaks since only some nodes will update to the latest version while some other "inner" nodes won't

while it could theoretically be moved to a separate function it would be kind of painful, since there would be one function per type and the top types would need to call the bottom types in the proper order

**Comment by mweststrate** [comment]
@bourquep that's great to hear! 

Just released MST 3.1.0 which fixes this problem. But earlier raised concerns still remain so in the next major this might very well change, as being discussed in #947

**Comment by mweststrate** [comment]
@xaviergonz could you move your case to #947?

**Comment by xaviergonz** [comment]
done!
