### ISSUE TITLE
Error: [mobx-state-tree] setParent is not supposed to be called on scalar nodes

### ISSUE THREAD

**Issue by maxguzenski** [mobxjs/mobx-state-tree#928]
[EDITED]
Change "self.items.unshift(id)" by "self.items = [id, ...self.items.slice()]" fixed issue
[/EDITED]

I have:

* [x] I think something is not working as it should.
  * [x] I've checked documentation and searched for existing issues

Error below only happen with mobx-state-tree 3.0. I basically put a model into a array [ self.items.unshift(model) ] This model has another model that call getParent.

works perfectly with mobx 2.2 

```
Error: [mobx-state-tree] setParent is not supposed to be called on scalar nodes
    at fail (mobx-state-tree.module.js:2286)
    at ScalarNode$$1.setParent (mobx-state-tree.module.js:885)
    at ArrayType$$1.willChange (mobx-state-tree.module.js:2979)
    at interceptChange$$1 (mobx.module.js:2688)
    at ObservableArrayAdministration.spliceWithArray (mobx.module.js:2856)
    at Proxy.unshift (mobx.module.js:3012)
    at unshift (page.js:126)
    at executeAction$$1 (mobx.module.js:613)
    at res (mobx.module.js:605)
    at runMiddleWares (mobx-state-tree.module.js:1907)
```

code example. I have many pages, that only keep ids, and I have a central repository to find itens with that id. I think that issue is with "get list()"

```javascript
t.model('activityPage', {
  items: t.optional(t.array(t.number), [])
})

.views(self => {
  get list() { return self.items.map(id => getRoot(self).getItem('activity', id)) }
})

.actions(self => {
  unshift(id) {
    self.items.unshift(id)
  }
})
```

**Comment by hiepnguyen1195** [comment]
+1

**Comment by jeffberry** [comment]
+1

**Comment by Krivega** [comment]
+1

**Comment by mweststrate** [comment]
@maxguzenski / @hiepnguyen1195  / @jeffberry the provided information is not sufficient to reproduce the issue. Please create a code sandbox demonstrating the issue

**Comment by mweststrate** [comment]
Next +1, submit a PR with test (and/or fix) or link to a sandbox. +1-ing doesn't help otherwise :)

**Comment by Krivega** [comment]
To reproduce [codesandbox](https://codesandbox.io/s/rj523q015n)

**Comment by jchamb** [comment]
Happens when simply splicing as well. [codesandbox](https://codesandbox.io/s/mqpm2w944p)

**Comment by Nexi** [comment]
+1

**Comment by mweststrate** [comment]
Released as 3.0.3. 

I hope this solves all the cases! Otherwise, please provide additional sandboxes or PR a unit test

**Comment by rihok** [comment]
It seems that unshifting is still not working (prependObject):
https://codesandbox.io/s/zxx8klwq1l

**Comment by Maher4Ever** [comment]
The same error still happens when trying to remove an item from an array of scalars: https://codesandbox.io/s/xv2j597oq. The funny thing is that if you try to remove the *last* item in the array it works! Also, if your array contains a single item it also works. In all the other cases this error is thrown. Note also that the model in my sandbox doesn't have a parent. model!

**Comment by xaviergonz** [comment]
Released 3.2.2, please check if this solves the issue

**Comment by Maher4Ever** [comment]
@xaviergonz I can confirm that the issue with removing items from an array has been resolved on my end 🎉

**Comment by xaviergonz** [comment]
@Maher4Ever thanks for checking! closing
