### ISSUE TITLE
global error handler middleware fails with: Cannot read property 'done' of undefined error

### ISSUE THREAD

**Issue by jayarjo** [mobxjs/mobx-state-tree#933]
I'm not sure if it's an issue or simply something wrong in the way I implement it, but it's quite a pattern, so I thought I'd report it.

I have global middleware that is meant to intercept any unhandled exceptions in the actions (both sync and async) and do something meaningful, instead of crashing - show a modal or report to the external service. Something like:

```ts
addMiddleware(someStore, (call, next, abort) => {
  try {
    next(call);
  } catch (err) {
    console.info(err);
  }
});
```

And it would probably work if it wouldn't hit `Unhandled Rejection (TypeError): Cannot read property 'done' of undefined` error, after every exception thrown from an action.

Minimal sandbox to reproduce the problem: https://codesandbox.io/s/yk4r230ow1

From what I see it originates in: https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mobx-state-tree/src/core/flow.ts#L108

```ts
function onRejected(err: any) {
    let ret
    try {
        // prettier-ignore
        wrap((r: any) => { ret = gen.throw(r) }, "flow_resume_error", err) // or yieldError?
    } catch (e) {
        // prettier-ignore
        setImmediate(() => {
            wrap((r: any) => { reject(e) }, "flow_throw", e)
        })
        return
    }
    next(ret)
}
```
Instead of making its way into `catch` block (as one would expect), exception somehow jumps over it and executes `next(ret)` with a `ret`, that is `undefined`, 'causing the abovementioned error to be thrown.

**Comment by mweststrate** [comment]
@jayarjo `try / catch` don't do anything for rejected promises. For promises / flows you should execute `next` and then attach a reject handler to the returned promise.

This utility might come in handy as well / serve as inpsiration: https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mobx-state-tree/src/middlewares/create-action-tracking-middleware.ts

**Comment by xaviergonz** [comment]
Closing since question was answered, @jayarjo feel free to repoen it if more help is required

**Comment by dmitry-zaets** [comment]
@jayarjo Can you please share a working example?
