### ISSUE TITLE
Defining properties on observable arrays is not supported?

### ISSUE THREAD

**Issue by alvaro1728** [mobxjs/mobx-state-tree#940]
I have the latest versions of mobx and mobx-state-tree.  Here's my code:

```
import {types} from 'mobx-state-tree';

export const ItemModel = types
  .model({
    id: types.identifier,
    name: types.string,
  });

export const TestModel = types
  .model({
    items: types.optional(types.array(ItemModel), []),
  })
  .actions(self => ({
    load: () => {
      self.items = [{id: "a", name: "A"}, {id: "b", name: "B"}];
    }
  }));

const test = TestModel.create({});
test.load();
```

 I'm getting this exception on the line that assigns to self.items:

**[mobx] Defining properties on observable arrays is not supported, directly assign them instead**

What am I doing wrong?

Thanks,
Alvaro

**Comment by mweststrate** [comment]
Which mobx and mobx-state-tree versions?

Op za 21 jul. 2018 19:26 schreef alvaro1728 <notifications@github.com>:

**Comment by alvaro1728** [comment]
```
    "mobx": "5.0.2",
    "mobx-react": "^5.2.3",
    "mobx-state-tree": "^3.0.0",
```

**Comment by alvaro1728** [comment]
I just realized I wasn't using the latest mobx, which is 5.0.3.  This issue is fixed there.

Thanks,
Alvaro

**Comment by mweststrate** [comment]
Please verify claims like `I have the latest versions of mobx and mobx-state-tree.` next time, these versions are out for a while already ;-)

**Comment by alvaro1728** [comment]
Yep, sorry.  I was definitely using the latest mobx-state-tree and didn't realize my mobx was outdated.

**Comment by mweststrate** [comment]
Ah! In that case npm / yarn install should have given a peer dependency
warning. But since these are not very intrusive most people miss them :-(
(including me)

Op za 21 jul. 2018 om 21:46 schreef alvaro1728 <notifications@github.com>:
