### ISSUE TITLE
applyAction doesn't accept third, IActionCallOptions argument

### ISSUE THREAD

**Issue by jayarjo** [mobxjs/mobx-state-tree#941]
Documentation states that [applyAction](https://github.com/mobxjs/mobx-state-tree/blob/master/API.md#applyaction) accepts third argument `options IActionCallOptions?`, but from what I see in the code, it never gets considered or referenced. Should documentation be patched perhaps?

I was looking for a way to apply action bypassing middlewares.

**Comment by mweststrate** [comment]
That argument was obsolete indeed, removed it from the docs
