### ISSUE TITLE
Question: how to mock implementation of substores in testing

### ISSUE THREAD

**Issue by nathanbirrell** [mobxjs/mobx-state-tree#944]
What is the recommended approach for mocking models/views/actions on substores for testing?

## Problem

I have a `ParentStore` that has a substore `ChildStore` that gets instantiated on `afterCreate`. I want to test _ParentStore_ alone, and mock it's children's implementations, because the substores get tested individually.

`ParentStore.ts`:

```javascript
  types
  .model('Parent', {
    child: ChildStore,
  })
  .actions((self) => ({
    afterCreate: () => {
      self.child = ChildStore.create()
    }
  }))
```

I've tried:

**1) Mocking implementation with a simple object**

`ParentStore.test.ts`:

```javascript
  jest.mock('./ChildStore', () => ({
    create: () => ({
      mockedAction: jest.fn()
    })
  }))
```

But this fails, understandably, with: `[mobx-state-tree] expected a mobx-state-tree type as first argument, got [object Object] instead`

**2) Mocking implementation with a mock MST model**

`ParentStore.test.ts`:

```javascript
  jest.mock('./ChildStore', () => (
    types
    .model('Child', {})
    .actions(() => ({
      mockedAction: jest.fn()
    }))
  ))
```

But this also fails understandably, due to jest mock restrictions on variable scoping:

```
  babel-plugin-jest-hoist: The module factory of `jest.mock()`is not allowed to reference any out-of-scope variables.    Invalid variable access: types    Whitelisted objects: Array, ArrayBuffer, Boolean, ...
```

Is there a better way to go about testing these stores individually? Or is this approach to instantiating the substore incorrect?

**Comment by nathanbirrell** [comment]
Solved! With a variant of # 2.

In `ParentStore.test.ts`:

```js
const mock = jest.fn() // keep mock fn outside of mock implementation scope, for tests

jest.mock('./ChildStore', () => (
    const { types } = require('mobx-state-tree') //  can't `import` MST normally, due to jest scope issues, need to require inside of the mock implementation
    types
    .model('Child', {})
    .actions(() => ({
      mockedAction: mock
    }))
))
```

Still open to better alternatives if anyone finds one.

**Comment by mweststrate** [comment]
Environments can be used for this. So you could pass in a factory to create
ChildStores. Which in the normal case will be `snapshot =>
ChildStore.create(snapshot)` and in your test setup `() => {}`. See
`getEnv` for more details

Op di 24 jul. 2018 om 06:17 schreef Nathan Birrell <notifications@github.com
