### ISSUE TITLE
Various question in regard to factories

### ISSUE THREAD

**Issue by RainerAtSpirit** [mobxjs/mobx-state-tree#95]
I'm in the process of building some Factories that would allow storing Odata options.

Starting point are some types that I'd like to convert into their MST counter parts.
```javascript
export type SortDir = 'asc' | 'desc'

export type SortExpression = {
	dir: SortDir,
	field: string
};

export type Sort = Array<SortExpression>

export type Odata = {
	expand?: Array<string>,
	select?: Array<string>,
	orderby?: Sort,
	filter?: FilterGroup,
	top?: number
}

export type FilterLogic = 'or' | 'and'

export type FilterExpression = {
	field: string,
	operator: string,
	value: any
}

export type FilterGroup = {
	logic: FilterLogic,
	filters: Array<FilterExpression | FilterGroup>
}
```
And  here's my first attempt to build some Factories instead.
There are three main aspects of the above that I'm unsure of how to model them correctly.
* how to express Typescript union types like `export type FilterLogic = 'or' | 'and'`
* in `FilterExpression`: how to allow `any` value. (might be number, string, Date, object etc.)
* in `FilterGroup`: how to allow filters array to use either `FilterExpression` or `FilterGroup`

https://github.com/RainerAtSpirit/mobx-state-tree/blob/odata/test/odata.ts
```javascript
const createTestFactories = () => {

    const FilterExpression = types.model("FilterExpression", {
        field: types.string,
        operator: types.string, // should be union of allowed operator 
        value: types.string // how to have a value: any?
    })

    const FilterGroup = types.model("FilterGroup", {
        logic: types.string, // what would be the equivilant of export type FilterLogic = 'or' | 'and'
        filters: types.array // how to allow either FilterExpression or FilterGroup?
    })

    const SortExpression = types.model("SortExpression", {
        field: types.string,
        dir: types.string // what would be the equivilant of export type SortDir = 'asc' | 'desc'
    })

    const Odata = types.model("Odata", {
        expand: types.array(types.string),
        select: types.array(types.string),
        orderby: types.array(SortExpression),
        filter: types.maybe(FilterGroup),
        top: types.withDefault(types.number, 30)
    })

    return { Odata }
}
```

**Comment by mattiamanzati** [comment]
- how to express Typescript union types like export type FilterLogic = 'or' | 'and'
They can be expressed using the literal and the union types: `t.union(t.literal('or'), t.literal('and'))`
- in FilterExpression: how to allow any value. (might be number, string, Date, object etc.)
You can use t.frozen to accept any value, it simply will be frozen once assigned.
- in FilterGroup: how to allow filters array to use either FilterExpression or FilterGroup
You can use t.array(t.union(FilterExpression, FilterGroup))

**Comment by RainerAtSpirit** [comment]
@mattiamanzati 
thanks for `.literal` and `.frozen`. Need to further check `.frozen` though as I'd like to update the filter value later down the road.

However based on the recursive nature the following throws
`[ts] Block-scoped variable 'FilterGroup' used before its declaration.`

```javascript
const FilterGroup = types.model("FilterGroup", {
        logic: types.union(types.literal('or'), types.literal('and')),
        filters: types.array(types.union(FilterExpression, FilterGroup))
    })
```

Thought I could use `this` instead, but that throws `[TypeError: factory.describe is not a function]​​`
```javascript
    const FilterGroup = types.model("FilterGroup", {
        logic: types.union(types.literal('or'), types.literal('and')),
        filters: types.array(types.union(FilterExpression, this))
    })
```

**Comment by RainerAtSpirit** [comment]
@mattiamanzati Did a quick test in regards to `.frozen`.  I could update a `.frozen` prop, which is fine with me. Just wondering about the name ;).

```javascript

test("it should accept any serializable value", t => {
    const Factory = types.model({
        value: types.frozen
    })

    const doc = Factory.create()

   reaction (
        () => toJS(doc.value),
        (filter) => console.log('filter', filter)
    )

    doc.value = {a: 1, b: 2}
    t.deepEqual<any>(getSnapshot(doc), {value: {a: 1, b: 2}})

    doc.value = {a: 2, b: 3}
    t.deepEqual<any>(getSnapshot(doc), {value: {a: 2, b: 3}})
})
```

**Comment by mattiamanzati** [comment]
To allow a recursive type declaration, you need to use t.recursive ;) its called frozen because if you set an object (e.g. {a:1,b:2}) and then try to update a prop (e.g. Obj.a=3) you wont be able cause it will be frozen. Thats because in MST changing objects need administration nodes to manage the changes. Frozing a value ensures that you can not change it, so no need for an administraton node to manage changes

**Comment by RainerAtSpirit** [comment]
@mattiamanzati thanks for the explanation. 
There are no tests yet for `recursive`. I've found the following in an earlier commit https://github.com/mobxjs/mobx-state-tree/commit/8e0a1383efa8f689b089a495faec1418cd6a9dc8, but it throws `[TypeError: Cannot read property 'name' of undefined]​​`
```javascript
import { test } from "ava"
import { getSnapshot, types } from "../src"

test("it should create recursive factories", t => {
    const Factory = types.recursive('Factory', type =>
        types.model({
            child: types.array(type)
        })
    )

    const doc = Factory.create({child: []})
    t.deepEqual<any>(getSnapshot(doc), {child: []})
})

```

**Comment by RainerAtSpirit** [comment]
@mattiamanzati 

After going back a bit back and forth I've currently settled on the below Factory definition.
This is working as expected, but if possible I'd like to use a better definition for `$filter` than `types.frozen`. 
In an ideal world something along the line of 

```javascript
export const FilterExpression = types.model('FilterExpression', {
	field: types.string,
	operator: types.union(
		types.literal('eq'),
		types.literal('ne')
		// todo: implement other
	),
	value: types.frozen
})

export const FilterGroup = types.model('FilterGroup', {
	logic: types.union(
		types.literal('and'),
		types.literal('or')
	),
	filters: types.frozen //e.g. types.array(types.union(FilterExpression, FilterGroup))
})
```
Is that something that should be currently supported by mst?
```javascript
...
export const Odata = types.model('Odata', {
	$expand: types.withDefault(types.array(types.string), []),
	$filter: types.withDefault(types.frozen, {}),
	$orderby: types.withDefault(types.array(SortExpression), []),
	$select: types.withDefault(types.array(types.string), []),
	$top: types.withDefault(types.number, 30),
	// actions have to be moved into second argument once https://github.com/mobxjs/mobx-state-tree/pull/99 has been merged
	expand(options: string[] | null) {
		if (options === null) {
			return toJS(this.$top)
		}
		this.$expand = options
	},
	filter(filterObj?) {
		if (!filterObj) {
			return toJS(this.$filter)
		}
		this.$filter = filterObj
	},
	orderby(options: ISortExpression[] | null) {
		if (!options) {
			return toJS(this.$orderby)
		}
		this.$orderby = options
	},
	top(options: number | null) {
		if (options === null) {
			return toJS(this.$top)
		}
		this.$top = options
	}
})
```
Full code example at https://github.com/RainerAtSpirit/mstStore/blob/master/src/core/Model/Odata.ts with some initial tests. https://github.com/RainerAtSpirit/mstStore/blob/master/test/Odata.ts

**Comment by RainerAtSpirit** [comment]
@mattiamanzati. Thanks to @tomitrescak solved via https://github.com/mobxjs/mobx-state-tree/issues/137

```javascript
export const FilterExpression = types.model('FilterExpression', {
  field: types.string,
  operator: types.union(
    types.literal('eq'),
    types.literal('ne'),
    types.literal('startswith')
    // todo: implement other
  ),
  value: types.frozen
})

export type IFilterExpression = typeof FilterExpression.Type

export type FilterGroupInstance = {
  logic: string,
  filters: (FilterGroupInstance | IFilterExpression)[]
}
export type FilterGroupModel = IModelType<FilterGroupInstance, FilterGroupInstance>

// TypeScript is'nt smart enough to infer self referencing types -> We are smarter ;)
const late = types.late<any, FilterGroupInstance>(() => FilterGroup)

export const FilterOrGroup = types.union(snapshot => snapshot && 'logic' in snapshot
    ? late
    : FilterExpression,
  FilterExpression, late)

export const FilterGroup: FilterGroupModel = types.model({
  logic: types.optional(types.union(types.literal('and'), types.literal('or')), 'and'),
  filters: types.optional(types.array(FilterOrGroup), [])
})

export type IFilterGroup = typeof FilterGroup.Type
```

https://github.com/RainerAtSpirit/mstStore/blob/0.6.2/src/core/Model/Odata.ts
