### ISSUE TITLE
Passing store to all children components as props

### ISSUE THREAD

**Issue by sirromdev** [mobxjs/mobx-state-tree#954]
I'm just looking to figure out how props can be passed to all components in a given application similar to redux's connect.  Is it possible to do the same in MST?

**Comment by Mosho1** [comment]
You can use mobx-react's `Provider` and `inject`. You can also use React's context API directly.

**Comment by sirromdev** [comment]
Ya, I think I figured it out ok with inject and provider

**Comment by sirromdev** [comment]
thanks!

**Comment by mattruby** [comment]
Please be sure to close your issues.
