### ISSUE TITLE
Can we use getKey option for array reconciliation？

### ISSUE THREAD

**Issue by liuqiang1357** [mobxjs/mobx-state-tree#958]
I have:
* [x] Feature request
   * [x] Describe the feature and why you feel your feature needs to be generically solved inside MST
   * [x] Are you willing to (attempt) a PR?
   
_Not following the above template might result in your issue being closed without further notice_

Like `key` prop in React, we can get key from array item by a user defined function. I think this will have better performance and accuracy.

**Comment by liuqiang1357** [comment]
I known `types.identifier`, but identifier is a unique value in the whole state tree. In some cases, what I need is a local uniqueness. For example, a primitive value array, I can use `item => item` to get the key for reconciliation.

**Comment by mweststrate** [comment]
@liuqiang1357 identifiers are unique and resovled _per type_. So that might suffice?

**Comment by kristianmandrup** [comment]
How to best assign the key then? We shouldn't have to do sth as complex as [this suggestion](https://github.com/mobxjs/mobx-state-tree/issues/780#issuecomment-383940461) I'm sure.

Ah, I guess `key` should just be made into a computed property which mirrors `id`?
