### ISSUE TITLE
Utility Design Question

### ISSUE THREAD

**Issue by OverseePublic** [mobxjs/mobx-state-tree#966]
Hello, I always appreciate the great framework from MST.

I have a following structure:
```
const staticUtil = {
  secondOperation: () ...
}
```
```
types.model('root', {
  firstStore: ...
});
```

In my application, I want to execute particular call from each store and then call secondOperation in staticUtil.

```
> firstStore.doSomething();
> staticUtil.secondOperation();
```

My question is: **How do I design utilities that calls MST action and regular utilities**

**Option1:**
design a wrapperUtil that takes a MST node as a parameter (I don't like this)
```

import staticUtil ...
const wrapperUtil = {
  callTwo(MSTNode) {
   MSTNode.doSomething();
   staticUtil.secondOperation()
  }
}
```

**Option2:**
design a MST node that has no tracking field in model and use ENV to access the staticUtil (I like this)
```
const root = types.model('root', {
  firstStore: ...,
  firstStoreUtil, ...
});

root.create({}, {staticUtil});

firstStoreUtilAction.js
self => ({
  callTwo() {
    getRoot(self).firstStore.doSomething();
    getEnv(self).staticUtil.secondOperation();
  }
})
```

**Option 3:**
Just friggin call it in firstStore via get Env, but this creates a tight coupling :(

My writing and explanation is terrible. Please let me know if you understand any questions. I would appreciate contributor / author responses. Thanks.

* [x] A conceptual question. 
  * [x] I've checked documentation and searched for existing issues
  * [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

**Comment by luisherranz** [comment]
If you need the `secondOperation` to be called inside an MST action for whatever the reason, then yes, `getEnv` is probably the way to go.

**Comment by xaviergonz** [comment]
@OverseePublic feel free to reopen the issue if the provided answers do not solve your question :)
