### ISSUE TITLE
noImplicitAny in model methods

### ISSUE THREAD

**Issue by mjewell** [mobxjs/mobx-state-tree#97]
Using the `noImplicitAny` typescript configuration you get errors from methods that do anything with `this`. The example at the bottom of the readme looks like this:

```
const Todo = types.model({
  title: types.string,
  setTitle(v: string) {
    this.title = v;
//  ^^^^  [ts] 'this' implicitly has type 'any' because it does not have a type annotation.
  },
});
```

Typescript let's you provide the `this` type by [providing it as a fake first argument](https://www.typescriptlang.org/docs/handbook/functions.html#this-parameters). But you can't use the `.Type` property as suggested because then it references itself:

```
const Todo = types.model({
//    ^^^^ [ts] 'Todo' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
  title: types.string,
  setTitle(this: ITodo, v: string) {
    this.title = v;
  },
});

type ITodo = typeof Todo.Type;
```

Is there a way around this without just defining a separate interface with all the same properties?

**Comment by mjewell** [comment]
Looks like one not great workaround is this:

```
const Todo = types.model({
  title: types.string,
  setTitle(this: any, v: string) {
    const self = this as ITodo;
    self.title = v;
  },
});

type ITodo = typeof Todo.Type;
```

**Comment by mattiamanzati** [comment]
Have you tried using TS2.3 with vscode insider? In dev branch it fixed this problem on my case

**Comment by mjewell** [comment]
I still get the same issues on typescript 2.3.2 (with and without vscode insider), only change is I also get this:

`[ts] Type alias 'ITodo' circularly references itself`

**Comment by mattiamanzati** [comment]
Have you removed the this: ITodo? With TS2.3 the type of this will be inferred correctly.

**Comment by mjewell** [comment]
Oh, my bad, you're right. Looks like this is not an issue. Feel free to close it
