### ISSUE TITLE
Proptypes validation problem

### ISSUE THREAD

**Issue by the-smaug** [mobxjs/mobx-state-tree#971]
Hi, i've checked issues and i think the chat isn't the appropriate tool to my question ;)

Here is my model files where i define my model and the associated propTypes for components that need to use it.
```js
import { types, flow, getParent } from 'mobx-state-tree'
import { bool } from 'prop-types'

import { MangaDetail, MangaDetailPropTypes } from './Manga'

export const DetailPropTypes = {
  manga: MangaDetailPropTypes,
  isOpen: bool.isRequired
}

export const Detail = types
  .model({
    manga: types.maybeNull(MangaDetail),
    isOpen: types.optional(types.boolean, false)
  })
```

And for propTypes validation i have a problem 
```js
import React, { Component } from 'react'
import { observer, inject, PropTypes } from 'mobx-react'

import { MangaDetailPropTypes } from '../models/Manga'

@inject('detail')
@observer
class Detail extends Component {
  static propTypes = { detail: PropTypes.observableObject(MangaDetailPropTypes) }

  render() {...}
}
```

and i've got this error : `VM1997:20 Warning: Failed prop type: inject-Detail-with-detail: prop type "detail" is invalid; it must be a function, usually from the "prop-types" package, but received "object"`

I've tried by wrapping all propTypes inside the observableObject method but my linter is crying 😅 

Am i using the good Proptypes method ?
Thanks

**Comment by mweststrate** [comment]
Should be just `PropTypes.observableObject`, Those propTypes are from the mobx-react binding and are further unaware of MST types. It should be easy to build your own propType checker though for mst, something along the lines

```
function modelProp(mstType) {
   return (props, propName) => {
       if (!mstType.is(props[propName])) throw new Error("Not a valid model")
   }
} 


///

static propTypes = { detail: modelProp(MangaDetailPropTypes) }

```

**Comment by mattruby** [comment]
Closed due to inactivity.  Feel free to re-open.
