### ISSUE TITLE
Getting Started tutorial is broken. Relies on ancient dependencies. Fix/update needed and suggested here

### ISSUE THREAD

**Issue by kristianmandrup** [mobxjs/mobx-state-tree#976]
I have:
* [x ] I think something is not working as it should.
  * [x ] I've checked documentation and searched for existing issues
  * [x ] I've made sure your project is based on the latest MST version
  * [x ] Describe expected behavior
  * [x ] Describe observed behavior

Been following the [Getting Started]() tutorial on the main Readme.
Have gotten to the step [improving render performance](https://github.com/mobxjs/mobx-state-tree/blob/master/docs/getting-started.md#improving-render-performance) where the app is rendered as 2 components

Works in [this codesandbox](https://codesandbox.io/s/m3rw1wll79)

But in my own environment on  VSC I've had to wrap the result of `values()` with `Array.from` to convert the `Iterator` into an `Array` that can be mapped.

```js
const AppView = observer(props => {
  const todos = props.store.todos;
  const values = Array.from(todos.values())
  console.log({todos, values})
  return (
    <div>
      <button
        onClick={e => props
        .store
        .addTodo(randomId(), "New Task")}>
        Add Task
      </button>
      {values.map(todo => <TodoView todo={todo}/>)}
    </div>
  );
})
```

Secondly, React now rightly complains that it wants a `key` property on a map to be rendered.
This needs to be integrated with the ObservaleMap generated somehow.

```bash
index.js:2178 Warning: Each child in an array or iterator should have a unique "key" prop.

Check the render method of `_class`. See https://fb.me/react-warning-keys for more information.
    in _class (at index.jsx:77)
    in _class (at index.jsx:83)
```

See React [lists and keys](https://reactjs.org/docs/lists-and-keys.html#keys)

Keys help React identify which items have changed, are added, or are removed. Keys should be given to the elements inside the array to give the elements a stable identity:

```js
const numbers = [1, 2, 3, 4, 5];
const listItems = numbers.map((number) =>
  <li key={number.toString()}>
    {number}
  </li>
);
```

So I guess it should look sth like the following, with a `key={props.todo.id}` on the container element. Ideally given latest React conventions, it should no longer be a div though, but an empty fragment, right? Not sure what the best practice is in this context?

```js
const TodoView = observer(props => <div key={props.todo.id}>
  <input
    type="checkbox"
    checked={props.todo.done}
    onChange={e => props
    .todo
    .toggle()}/>
  <input
    type="text"
    value={props.todo.name}
    onChange={e => props
    .todo
    .setName(e.target.value)}/>
</div>);
```

This naive approach turns out to be the [wrong way]() however, as outlined in [extracting-components-with-keys](https://reactjs.org/docs/lists-and-keys.html#extracting-components-with-keys)

The key should instead be specified in the map iteration function when instantiating each list item.

```js
const listItems = numbers.map((number) =>
    // Correct! Key should be specified inside the array.
    <ListItem key={number.toString()}
              value={number} />
```

Finally got the map working using `name` as the key (hack)

`{values.map(todo => <TodoView key={todo.name} todo={todo}/>)}`

First tried using `todo.id` but it complained that there was no such thing as an `id` on `todo`
Need to add a `key` or `id` field as `identifier` type. 

```js
const Todo = types.model({
  key: types.identifier,
  name: types.optional(types.string, ""),
```

Then update `todos` assignment in the `RootStore` creation

```js
  todos: {
    "1": {
      key: "1",
      name: "Eat a cake",
      done: true
    }
  }
```

Now when you click `add` button which calls `addTodo`:

```bash
mobx-state-tree.module.js:2296 Uncaught Error: [mobx-state-tree] Error while converting `{"name":"New Task"}` to `AnonymousModel`:

    at path "/key" value `undefined` is not assignable to type: `identifier` (Value is not a valid identifier, expected a string).
```

So `addTodo` needs to be updated to set the `key` as well

```js
  function addTodo(key, name) {
    self
      .todos
      .set(key, Todo.create({key, name}));
  }
```

Would be nice if there was a smart way to reuse such a common pattern. Perhaps using a few factory methods?

Dependencies for my local environment (Aug 2018)

```json
    "mobx": "^5.0.3",
    "mobx-react": "^5.2.5",
    "mobx-state-tree": "^3.2.1",
    "react": "^16.4.2",
    "react-dom": "^16.4.2"
```

Dependencies in code sandbox referenced in Getting Started tutorial

```json
    "mobx": "^3.2.2",
    "mobx-react": "^4.2.2",
    "mobx-state-tree": "^0.10.1",
    "react": "^15.5.3",
    "react-dom": "^15.5.3"
```

Sandbox referenced is clearly very outdated! React version 15 vs current latest version 16.
MobX 2 versions behind. MobX-React one version behind. MobX State Tree using a pre 1.0 version.

Please update code sandbox and examples to work with latest versions as of August 2018.
Thanks :)

My solution that works with latest dependency versions:

```js
import React from "react";
import {render} from "react-dom";
import {types} from "mobx-state-tree";
import {observer} from "mobx-react";

const randomId = () => Math.floor(Math.random() * 1000).toString(36);

const Todo = types.model({
  key: types.identifier,
  name: types.optional(types.string, ""),
  done: types.optional(types.boolean, false)
}).actions(self => {
  function setName(newName) {
    self.name = newName;
  }

  function toggle() {
    self.done = !self.done;
  }

  return {setName, toggle};
});

const User = types.model({
  name: types.optional(types.string, "")
});

const RootStore = types.model({
  users: types.map(User),
  todos: types.optional(types.map(Todo), {})
}).actions(self => {
  function addTodo(id, name) {
    self
      .todos
      .set(id, Todo.create({name}));
  }

  return {addTodo};
});

const store = RootStore.create({
  users: {},
  todos: {
    "1": {
      key: "1",
      name: "Eat a cake",
      done: true
    }
  }
});

const TodoView = observer(props => <div>
  <input
    type="checkbox"
    checked={props.todo.done}
    onChange={e => props
    .todo
    .toggle()}/>
  <input
    type="text"
    value={props.todo.name}
    onChange={e => props
    .todo
    .setName(e.target.value)}/>
</div>);

const AppView = observer(props => {
  const values = Array.from(props.store.todos.values());
  return (
    <div>
      <button
        onClick={e => props
        .store
        .addTodo(randomId(), "New Task")}>
        Add Task
      </button>
      {values.map(todo => {
        return (<TodoView key={todo.key} todo={todo}/>)
      })}
    </div>
  );
})

render(
  <AppView store={store}/>, document.getElementById("root"));
```

**Comment by xaviergonz** [comment]
Getting started fixed + updated code sandboxes
