### ISSUE TITLE
How to type safe call of action from another action

### ISSUE THREAD

**Issue by tomitrescak** [mobxjs/mobx-state-tree#989]
I have:

* [x] A conceptual question. 
  * [x] I've checked documentation and searched for existing issues
  * [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3) first
* [x] I think something is not working as it should.
  * [x] I've checked documentation and searched for existing issues
  * [x] I've made sure your project is based on the latest MST version
  * [x] Fork [this](https://codesandbox.io/s/jlnmjqr7xv) code sandbox or another minimal reproduction. 
  * [x] Describe expected behavior

     I want to call action from another action in Typescript. 
    The only way to do it is via `(self as any).anotherAction()` as "self" is only typed for props in action.
    Is there any other way?    

  * [ ] Describe observed behavior
_Not following the above template might result in your issue being closed without further notice_
* [ ] Feature request
   * [ ] Describe the feature and why you feel your feature needs to be generically solved inside MST
   * [ ] Are you willing to (attempt) a PR?

**Comment by xaviergonz** [comment]
For now one of the alternatives is separating them
```
types.model({x: 5})
.actions(self => ({
  a1() {}
})
.actions(self => ({
  a2() {
    self.a1()
  }
})
```

for new alternatives being proposed please check https://github.com/mobxjs/mobx-state-tree/issues/982

**Comment by tomitrescak** [comment]
Thank you all for your answers. I have A LOT of different approaches. I'm sorry I meesed that bit in the documentation. I read it quite a few times ...

**Comment by malekpour** [comment]
@mweststrate I tried to use the following approach from https://github.com/mobxjs/mobx-state-tree#typing-self-in-actions-and-views but TypeScript 3 doesn't like it. I think `Example` becomes any if referenced inside its initialization.

```ts
const Example = types
  .model("Example", { prop: types.string })
  .views((self: typeof Example.Type) => ({
      // use typeof instead of predefined type to avoid circular references
      get upperProp(): string {
          return self.prop.toUpperCase()
      },
      get twiceUpperProp(): string {
          return self.upperProp + self.upperProp
      }
  }));
```
The error is:
`
[ts] 'Example' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
`

**Comment by xaviergonz** [comment]
@malekpour 
try this instead
```ts
    const Example = types
        .model("Example", { prop: types.string })
        .views((self) => ({
            get upperProp(): string {
                return self.prop.toUpperCase()
            }
        }))
        .views((self) => ({
            get twiceUpperProp(): string {
                return self.upperProp + self.upperProp
            }
        }));
```

**Comment by xaviergonz** [comment]
@malekpour just fixed the readme with the "this" approach rather than the incorrect typeof one, thanks for pointing it out!

**Comment by tomitrescak** [comment]
Strange, in action, this for me is "window".

**Comment by malekpour** [comment]
And this type is any for me.

**Comment by mweststrate** [comment]
Type inference depends on the compiler settings, so they might differ

Op di 28 aug. 2018 00:31 schreef Ali Malekpour <notifications@github.com>:

**Comment by xaviergonz** [comment]
maybe you are using Arrow functions? The 'this' trick doesn't work with those

**Comment by zmayor** [comment]
> or alternatively this
> 
> ```ts
> const Example = types.model("Example", { prop: types.string }).views(self => ({
>         get upperProp(): string {
>             return self.prop.toUpperCase()
>         },
>         get twiceUpperProp(): string {
>             return this.upperProp + this.upperProp
>         }
>     }))
> ```

When using `flow` to write async action, `this` is implicit, does this means the only solution is writing multiple `.action()` ?

**Comment by zmayor** [comment]
Can I call `action3` in `action2`?

```
mstModel
.actions((self) => ({
    action1: flow(function*() {
      console.log('this is action1');
    }),
  }))
  .actions((self) => ({
    action2: flow(function*() {
      self.action1(); // right
      self.action3(); // wrong
      console.log('this is action2');
    }),
  }))
  .actions((self) => ({
    action3: flow(function*() {
      console.log('this is action3');
    }),
  }))
```

**Comment by zmayor** [comment]
> Can I call `action3` in `action2`?
> 
> ```
> mstModel
> .actions((self) => ({
>     action1: flow(function*() {
>       console.log('this is action1');
>     }),
>   }))
>   .actions((self) => ({
>     action2: flow(function*() {
>       self.action1(); // right
>       self.action3(); // wrong
>       console.log('this is action2');
>     }),
>   }))
>   .actions((self) => ({
>     action3: flow(function*() {
>       console.log('this is action3');
>     }),
>   }))
> ```

@xaviergonz 
Maybe this is the best solutions ?

```
.actions((self) => {
    const actions  = {
      action1: flow(function*() {
        console.log('this is action1');
      }),
      action2: flow(function*() {
        actions.action1(); // right
        actions.action3(); // right
        console.log('this is action2');
      }),
      action3: flow(function*() {
        console.log('this is action3');
      }),
    };
    return actions;
  })
```

**Comment by xaviergonz** [comment]
that's a way to solve it yes

**Comment by zmayor** [comment]
What does that mean? Please tell me more details. Thank You.

**Comment by flatcoke** [comment]
Using getRoot and find current model like reflection
```javascript
.actions(self => ({
   a: () => {
    const root = getRoot(self)
    root.currentModel.b()
  },
 b: () => {
  console.log('called b function')
 }
```
