### ISSUE TITLE
Array of custom reference does not trigger getter and setter

### ISSUE THREAD

**Issue by rdewolff** [mobxjs/mobx-state-tree#999]
I have:

* [x] I think something is not working as it should.
  * [x] I've checked documentation and searched for existing issues
  * [x] I've made sure your project is based on the latest MST version
  * [x] Forked sandbox with issue : https://codesandbox.io/s/mml2xvyxox
  * [ ] Describe expected behavior
Creating an array of custom reference should work and trigger it's getter and setters.
  * [ ] Describe observed behavior
Creating an array of custom reference does *not* trigger getter and setter.
* [ ] A conceptual question. 
  * [x] I've checked documentation and searched for existing issues
  * [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3) first
* [ ] Feature request
   * [ ] Describe the feature and why you feel your feature needs to be generically solved inside MST
   * [ ] Are you willing to (attempt) a PR?
   
Hello all

This is my first issue reported here so let me know if there is any way to do this in a better way :) While trying to implement a list of references, I noticed my getter and setter didn't trigger. So I forked a sandbox and hoped to make some kind of mistake somewhere. But here it is, https://codesandbox.io/s/mml2xvyxox 
Setting a single reference with `singleSelection` trigger the getter and setter just fine, as expected.
But using the array `multipleSelection` doesn't trigger any getter or setter.

Is there a workaround? Is this a wanted behaviour?

**Comment by rdewolff** [comment]
Meanwhile, I found the following workaround : https://codesandbox.io/s/n34z7o33ql

**Comment by xaviergonz** [comment]
I'm not really sure what you are trying to accomplish.

references are pointers to nodes that have an identifier, but the actual nodes your references point to seem to be missing?

e..g
```
const s = Store.create({
  users: [],
  multipleSelection: ["Mattia", "Jose"], // there's no User node with name "Mattia" or "Jose" in the data
  singleSelection: "Romain" // there's no User node with name "Romain" in the data
});
```

**Comment by xaviergonz** [comment]
Nevermind I see now what you mean :D

The getter/setter is not getting triggered because the reference is not being accessed
Since references trigger those when accessed, you need to access them:

https://codesandbox.io/s/88m2v5z4z2

Console output
```
starting up 
Object {users: ObservableArray, multipleSelection: ObservableArray, singleSelection: Object}
UserByNameReference.get(Romain) 
loading Romain 
UserByNameReference.get(Mattia) 
loading Mattia 
UserByNameReference.get(Jose) 
loading Jose 
UserByNameReference.get(Romain) 
loaded Romain 
loaded Mattia 
loaded Jose 
Object {users: ObservableArray, multipleSelection: ObservableArray, singleSelection: Object}
UserByNameReference.get(Romain) 
```
the access part added is here
```
s.singleSelection
s.multipleSelection[0]
s.multipleSelection[1]
```

if that solves your question please feel free to close the issue ;)

**Comment by rdewolff** [comment]
Thanks for that, this works fine. 

Am trying to update the code sandbox to reproduce I have in my project.

**Comment by rdewolff** [comment]
Here it is, updated version, where I could isolate my issue :

https://codesandbox.io/s/z39w6xpoj3

**Comment by rdewolff** [comment]
I have found my problem, I was using a `reference` of a `reference`... gosh!
Thanks for the help and learnt a lot.
